### ISSUE TITLE
Getting Started Page

### ISSUE THREAD

**Issue by bruqui** [aws-amplify/docs#1001]
When I try to go through the simple tutorial on the getting started page, I can't get the tutorial to work.
**To Reproduce**
1. Go to https://aws-amplify.github.io/docs/js/start?platform=react
1. Go through the first five steps.
1. `npm start` the app built from the steps.
1. Open http://localhost:3000/ in Chrome
1. Open the network tab in the dev console in Chrome
1. Refresh the page. 
1. In the console, there will be an error `Uncaught (in promise)` for the getData function
1. Check the network tab and there are no server calls.
1. Click on the "Add todo" button in the page.
1. Observe the network tab. Still no calls to an external server.
1. Click on the console tab. Another `Uncaught (in promise)` error is created.

**Expected behavior**
When I run through the tutorial for Amplify with React, I should not get `Uncaught (in promise)` errors in the console and I should be able to create a todo list. The records created should show up on the page with the `getData` function.

**Screenshots**
Console tab after clicking on Add todo
![image](https://user-images.githubusercontent.com/1043204/68588272-47614400-0446-11ea-9c32-4c02f8559432.png)

Network tab after clicking on Add todo 
![image](https://user-images.githubusercontent.com/1043204/68588381-98713800-0446-11ea-807b-c01463d55aee.png)

Here is the code I created based from the tutorial...

```
import React, { useEffect, useReducer } from 'react'

import { listTodos } from './graphql/queries'

import API, { graphqlOperation } from '@aws-amplify/api'
import PubSub from '@aws-amplify/pubsub';
import { createTodo } from './graphql/mutations'

import config from './aws-exports'
API.configure(config)             // Configure Amplify
PubSub.configure(config);

const initialState = {todos:[]};
const reducer = (state, action) =>{
  switch(action.type){
    case 'QUERY':
      return {...state, todos:action.todos}
    case 'SUBSCRIPTION':
      return {...state, todos:[...state.todos, action.todo]}
    default:
      return state
  }
}

async function createNewTodo() {
  const todo = { name: "Use AppSync" , description: "Realtime and Offline"}
  await API.graphql(graphqlOperation(createTodo, { input: todo }))
}

function App() {
  const [state, dispatch] = useReducer(reducer, initialState);

  useEffect(() => {
    getData()
  }, [])

  async function getData() {
    const todoData = await API.graphql(graphqlOperation(listTodos))
    dispatch({type:'QUERY', todos: todoData.data.listTodos.items});
  }

  return (
    <div className="App">
      <div><button onClick={createNewTodo}>Add Todo</button></div>
      <div>{ state.todos.map((todo, i) => <p key={todo.id}>{todo.name} : {todo.description}</p>) }</div>
    </div>
  );
}

export default App;
```
**Desktop (please complete the following information):**
 - OS: macOS Catalina Version 10.15.1
 - Browser: Chrome
 - Version: Version 78.0.3904.97 (Official Build)

**Additional context**
It also doesn't seem like everything is getting fully created in AWS. For example, if I check out the DynamoDB table, there is no name field. Only an ID field. Not sure if that's expected behavior and the fields are created as records are created or something. Either way, I'm reluctant to use a framework that has problems with the simple tutorial on getting started; however, it does seem like a very robust framework and would like to try to go further with it.

Also, it doesn't seem like it's even worth having a chat button on [this page](https://aws-amplify.github.io/docs/js/start?platform=react) if nobody is going to respond.

**Comment by sammartinez** [comment]
@bruqui Thanks for the feedback on this. After testing the sample you provided and comparing the Getting Started code, I do see there are couple of issues with the Getting started snippets. I am working on getting an update out for this. 


To your second point, regarding only seeing the `ID` within the DynamoDB table, I am unable to reproduce this as I do see the mutation call passing the name, ID, and Description and showing in DynamoDB. 

![mutation](https://user-images.githubusercontent.com/7387880/69092908-41e59a00-0a02-11ea-95f4-ca02f4ebd63d.png)

Did you do auto generated graphQL mutations? Please see below of what the auto generated provides:

```
/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const createTodo = `mutation CreateTodo($input: CreateTodoInput!) {
  createTodo(input: $input) {
    id
    name
    description
  }
}
`;
export const updateTodo = `mutation UpdateTodo($input: UpdateTodoInput!) {
  updateTodo(input: $input) {
    id
    name
    description
  }
}
`;
export const deleteTodo = `mutation DeleteTodo($input: DeleteTodoInput!) {
  deleteTodo(input: $input) {
    id
    name
    description
  }
}
`;
```

In the meantime, I will be finishing up the code snippets and getting an update out.

**Comment by thepastelsuit** [comment]
You ever get this working? I am seeing this issue still with `Uncaught (in promise) undefined` every time there is a call to graphql
