### ISSUE TITLE
Suggestion, add react expo walk-through to Auth Javascript docs.

### ISSUE THREAD

**Issue by jonsmirl** [aws-amplify/docs#1005]
I'm in the process of trying to walk some new programmers through adding Amplify to the demo react expo app just to learn how things work. This process is not going very smoothly.  The main problem is that the AWS Auth docs mix together all kinds of complex use cases (Auth0, custom Auth, hosted UI) and these new programmers don't have the background necessary to separate out which pieces are relevant to their task.

So my suggestion would be to add a walk through in the documentation between the Overview and Identity Pool sections. This walk thought would create the expo tab demo app (one of the choices in expo init) and then add Federated login to it using native UI (not hosted). Please don't use withAuthenticator() because that simply avoids the whole learning process.  Helpful to keep a working copy of the finished app on github as a reference.

The goal here is to get people who don't want to focus on Auth development past the point where they need to add Auth support while teaching them the basics.  Right now my guys have been stuck at this step three days trying to figure things out.

It might be interesting for the doc people to take someone who is not already an expert and ask them to do this task.

**Comment by swaminator** [comment]
We've added a getting started page in the new docs that walkthrough getting started with Auth: https://docs.amplify.aws/lib/auth/getting-started/q/platform/js

Let me know if there is more you'd wish to see.
