### ISSUE TITLE
Nodejs 8.10 End Of Life

### ISSUE THREAD

**Issue by kimfucious** [aws-amplify/docs#1009]
[This page](https://aws-amplify.github.io/docs/cli/lambda-node-version-update) mentions upgrading from Node 6.10 to 8.10.

I received an email mid-October from AWS that described Node 8.x as end of life:

> The Node community has decided to end support for Node.js 8.x on December 31, 2019 [1]. From this date forward, Node.js 8.x will stop receiving bug fixes, security updates, and/or performance improvements. To ensure that your new and existing functions run on a supported and secure runtime, language runtimes that have reached their EOL are deprecated in AWS [2].

I believe this might merit an update of the above page, so that folks are aware that Node 10.x is the way forward at the moment.

**Comment by sammartinez** [comment]
@kimfucious Thanks for the feedback, we will look to get this updated. I will state that we are open to pull requests if you wanted to provide the update for this documentation.

**Comment by brene** [comment]
Thanks fro the feedback, we've addressed the issue here: https://docs.amplify.aws/cli/migration/lambda-node-version-update
