### ISSUE TITLE
Documentation: Incorrect definitions of methods

### ISSUE THREAD

**Issue by jnguyenCIG** [aws-amplify/docs#1018]
**Describe the bug**
The page lists the "Administrative Actions" default routes and the definition of each function, but all of the definitions are listing the same thing for each route --> "Adds a user to a specific Group"

**To Reproduce**
1. Go to [https://aws-amplify.github.io/docs/cli-toolchain/quickstart#administrative-actions](https://aws-amplify.github.io/docs/cli-toolchain/quickstart#administrative-actions)
2. Scroll down to "The default routes and their functions, HTTP methods, and expected parameters are below"
3. Look at the definitions of the bullet points

**Expected behavior**
When you read each definition of each of the routes, it should not all say "Adds a user to a specific Group," but it should list its respective definition.

**Screenshots**
In the screenshots, a majority of the definitions state "Adds a user to a specific Group."
![image](https://user-images.githubusercontent.com/51932261/69177728-f3e19c80-0abc-11ea-8352-56e241e24972.png)
![image](https://user-images.githubusercontent.com/51932261/69177737-f643f680-0abc-11ea-8839-9768957ee9f5.png)

**Comment by swaminator** [comment]
Fixed: https://docs.amplify.aws/cli/auth/admin
