### ISSUE TITLE
Difficult to follow examples

### ISSUE THREAD

**Issue by kiwicloudninja** [aws-amplify/docs#1019]
https://aws-amplify.github.io/docs/js/api#connect provides an example that has a number of confusing issues.
Because it's a code fragment, it's unclear that Amplify.configure(awsconfig); is required. It would be useful to include the following in the head of the example:
import awsconfig from './aws-exports';
Amplify.configure(awsconfig);

The code block that is difficult to understand is as follows:
```
<Connect query={graphqlOperation(queries.listTodos)}>
                {({ data: { listTodos }, loading, errors }) => {
                    if (errors) return (<h3>Error</h3>);
                    if (loading || !listTodos) return (<h3>Loading...</h3>);
                    return (<ListView todos={listTodos.items} /> );
                }}
            </Connect>
```
It's not clear whether { listTodos } and (queries.listTodos) are two different things or the same things.
The 'errors' object seems to become defined, so the code always returns <h3>Loading...</h3> even when errors is empty. Empty but defined.

After a lot of experimentation I got the following code to work:
```
render()
    {
        const ListView = ({ stops }) => (
            <div>
                <h3>All Stops</h3>
                <ul>
                    { stops.map(stop => <li key={stop.stop_id}>{stop.stop_name}:[{stop.stop_lat},{stop.stop_lon}]</li>) }
                </ul>
            </div>
        );

        return (
            <Connect query={graphqlOperation(queries.listRtfsStops)}>
                {({ data: { listRtfs_stops }, loading, errors }) => {
                    if (listRtfs_stops) return (<ListView stops={listRtfs_stops.items} /> );
                    return (<h3>Loading...</h3>);
                }}
            </Connect>
        )
    }
```

The documentation would also be much easier to follow if there was one whole end to end solution rather than fragments. It's difficult to work out what fragments are required, and what fragments aren't.

EG: If you're using <Connect> you don't need 
`const allTodos = await API.graphql(graphqlOperation(queries.listTodos));`

The whole https://aws-amplify.github.io/docs/js/api#simple-query block has problems as well. If you copy this code verbatim into a file, you get an error that await isn't allowed outside of an async function.

For people new to React and Amplify, these turn into major blockers for easily understanding how the code and tools work.

**Comment by swaminator** [comment]
@kiwicloudninja try out our new getting started category page: https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/js
