### ISSUE TITLE
Social Provider Setup instructions for Google are flipped

### ISSUE THREAD

**Issue by leosoaivan** [aws-amplify/docs#1029]
**Describe the bug**
The instructions for setting up Google as a social provider appear to be flipped. It seems that one should configure a project prior to configuring OAuth2 credentials.

**To Reproduce**
Review the instructions and confirm.

**Comment by swaminator** [comment]
@leosoaivan the doc is updated here: https://docs.amplify.aws/lib/auth/social/q/platform/js#setup-social-provider
