### ISSUE TITLE
AWSAppSync and AWSMobileClient require different versions of AWS Core

### ISSUE THREAD

**Issue by rwm1210** [aws-amplify/docs#1033]
XCode Version 11.1.
iOS app was recieving subscription updates from Dynamo DB just fine. Then I went to add push Notifications/ required API and:

CocoaPods could not find compatible versions for pod "AWSCore": In Podfile:

    AWSAppSync (~> 2.14.3) was resolved to 2.14.3, which depends on
      AWSCore (~> 2.11.0)

    AWSMobileClient (~> 2.12.2) was resolved to 2.12.2, which depends on
      AWSAuthCore (= 2.12.2) was resolved to 2.12.2, which depends on
        AWSCore (= 2.12.2)

Thanks in advance for any help!

**Comment by rwm1210** [comment]
I made it run by specifying older version (2.11.0) of AWSMobileClient.

**Comment by palpatim** [comment]
@rwm1210 Is this a problem in documentation? If so, could you add a link to the page where you found it?
