### ISSUE TITLE
sessionToken and expiration fields not available in AWSMobileClient android version

### ISSUE THREAD

**Issue by devxpy** [aws-amplify/docs#1034]
android - `implementation 'com.amazonaws:aws-android-sdk-mobile-client:2.16.4'`

ios - `'AWSMobileClient', '= 2.9.8'`

I want the `sessionToken`, in order to perform [SigV4 signing for aws iot](https://docs.aws.amazon.com/iot/latest/developerguide/mqtt-ws.html).

But the android version of this library only has the following fields -
```java
public interface AWSCredentials {
    String getAWSAccessKeyId();

    String getAWSSecretKey();
}
```
On the other hand, the iOS sdk has all the fields I need - 

```swift
/**
 An AWS credentials container class.
 */
@interface AWSCredentials : NSObject

/**
 Access Key component of credentials.
 */
@property (nonatomic, strong, readonly) NSString *accessKey;

/**
 Secret Access Key component of credentials.
 */
@property (nonatomic, strong, readonly) NSString *secretKey;

/**
 Session Token component of credentials.
 */
@property (nonatomic, strong, readonly, nullable) NSString *sessionKey;

/**
 Date at which these credentials will expire.
 */
@property (nonatomic, strong, readonly, nullable) NSDate *expiration;
```

---

I noticed that `AWSMobileClient` is hiding a `CognitoCachingCredentialsProvider` object under the attribute `CognitoCachingCredentialsProvider cognitoIdentity`. This object has `AWSSessionCredentials`. Can you just make that public?

**Comment by davedega** [comment]
how about this?
```        String sessionToken = ((AWSSessionCredentials) AWSMobileClient.getInstance().getCredentials()).getSessionToken();
```

**Comment by jpignata** [comment]
Thanks @davedega! @devxpy - please let us know if you have any additional questions.

**Comment by ajeet-inspify** [comment]
@jpignata 
It is still missing expiration.

/**
 Date at which these credentials will expire.
 */
NSDate *expiration;
