### ISSUE TITLE
Documentation help for setting up Vue using ES6 module export

### ISSUE THREAD

**Issue by nav064** [aws-amplify/docs#1035]
I was trying to import and use amplify-authenticator and amplify-signup modules. But it is not clear whether I can directly use the tags <amplify-authenticator> <amplify-signup> 

1. directly after initializing in "MyComponent" (mentioned in [documentation](https://aws-amplify.github.io/docs/js/vue)) OR 
2. in a separate form component and then make use of events to trigger "My Component" 

An example of how "My Component" is used in a sign-up form, especially in ES6 style, will give a better picture. 

I was following this link. 
https://stackoverflow.com/questions/52209553/how-can-i-get-started-with-integrating-aws-amplify-to-a-nuxt-js-project

A more detailed explanation on this will definitely help. Specifically information on how to link these components to signup/signin forms.

**Comment by haverchuck** [comment]
@nav064  - To clarify:  you're trying to use the entire authenticator component (which includes signup) or simply the signup component on its own?

**Comment by nav064** [comment]
Hi Dustin!
Yes, I'm trying to initially test it with signup component.
Will definitely need confirmSignup and signIn modules also.
If this works well, I'm also thinking about Chatbot component.
Seeing some issues with aws-lex-web-ui especially on ES6 configuration with
Vue even there.

**Comment by nav064** [comment]
I'm able to view the component with this setting on nuxt.config.js

```
plugins: [
    {
        src: '~plugins/amplify.js',
        ssr: false
    }
]
```
I was missing "ssr" setting earlier.

**Comment by sammartinez** [comment]
For the using Vue with es6 modules, this is now standard within our documentation and the [Vue Components](https://docs.amplify.aws/ui/auth/authenticator/q/framework/vue) are able to do so with this. Resolving
