### ISSUE TITLE
No Documentation or Example for "Infer" option in category “Predictions”

### ISSUE THREAD

**Issue by sofnix-source** [aws-amplify/docs#1037]
There is no detailed documentation and example for "Infer" option in a new category in Amplify Framework called as “Predictions”. I am unable to use this "Infer" option due to lack of documentation.

**Describe the solution you'd like**
Description of API for "Infer" option and example code in VueJS.

**Comment by mrrainey** [comment]
I am also having the same issue - trying to implement code for inference of an image against a Sagemaker Model endpoint but don't know where to begin as it seems the "Predictions" object from '@aws-amplify/predictions' has no Predictions.Infer() function.

**Comment by sammartinez** [comment]
@sofnix-source We currently not supported within Amplify JS to use `Amplify.infer(...)`, I have cut a feature request to the Amplify JS repository - https://github.com/aws-amplify/amplify-js/issues/5859. Resolving this issue in favor of the Feature Request.
