### ISSUE TITLE
DataStore API Ref Link 404s

### ISSUE THREAD

**Issue by jonoirwinrsa** [aws-amplify/docs#1044]
**Describe the bug**
The link at the bottom of https://aws-amplify.github.io/docs/js/datastore "visit our API Reference" links to https://aws-amplify.github.io/amplify-js/api/classes/DataStoreclass.html takes you to a 404 page

**To Reproduce**
Click the link

**Expected behavior**
Finds a real page

**Comment by jamesonwilliams** [comment]
This issue was later duplicated in https://github.com/aws-amplify/amplify-js/issues/4604, which is being used for tracking.
