### ISSUE TITLE
Improve push notifications documentation 

### ISSUE THREAD

**Issue by idanlo** [aws-amplify/docs#1064]
**Is your feature request related to a problem? Please describe.**
The docs for push notifications are very limited and don't give any examples, for example - how often do you call `updateEndpoint`? What does the `address` parameter mean (the device unique id, the notification token, the user id, etc...)? How do I test notifications for a certain user (you need to get the endpointId, which I don't know where to get it from)? And many more questions that are unanswered in the Amplify docs.

The `updateEndpoint` method doesn't even appear in the `Push Notification` page, only in the `Analytics` page, but according to what I understood, `updateEndpoint` is **required** for notifications to work (because of the `address` parameter) 

**Describe the solution you'd like**
I think the docs regarding push notifications should be updated, maybe give a repository with a full example

**Describe alternatives you've considered**
I tried researching, and looking at issues on the `amplify-js` repo, but most (if not all) issues were closed because of stale bot

**Comment by dantasfiles** [comment]
@idanlo Until AWS Amplify updates the official documentation, I have [a writeup of my experiences setting up AWS Amplify push notifications](https://medium.com/@dantasfiles/setting-up-android-push-notifications-with-aws-amplify-e6334c6356d8).

**Comment by dabit3** [comment]
@idanlo thanks for the feedback, yes there are some great ideas here and the docs could definitely use some improvement.

What platform are you building for (native iOS / Android or React Native)?

**Comment by mauerbac** [comment]
Closing this issue as it's outdated. Please open a new issue with feedback on our push notification docs
