### ISSUE TITLE
Please clarify "Overwriting Resolvers"

### ISSUE THREAD

**Issue by fregadev** [aws-amplify/docs#1066]
**Is your feature request related to a problem? Please describe.**
On the docs, https://aws-amplify.github.io/docs/cli-toolchain/graphql#overwriting-resolvers describes a way of overwriting resolvers by changing files that are constantly being rewritten by the library itself. It is unclear if changes made to those files will actually be kept.

**Describe the solution you'd like**
A clearer description of when it is or isn't safe to change files that are constantly undergoing code generation by the library (such as the ones mentioned above).

**Comment by brene** [comment]
@fregadev - we've moved & shifted our docs quite significantly since Dec. LMK if this section addresses your concerns: https://docs.amplify.aws/cli/graphql-transformer/resolvers#overwriting-resolvers
