### ISSUE TITLE
Applying plugin in project gradle gives ERROR in Android Studio Windows 10

### ISSUE THREAD

**Issue by abhidaa1233** [aws-amplify/docs#1075]
I am currently following the aws amplify guide for Android for Windows in  https://aws-amplify.github.io/docs/android/api 
and after setting up when I came to the step->  _(Optional) Add Gradle Plugin to auto generate models_ Section. There after adding the plugin **apply plugin:'com.amplifyframework.amplifytools'** as shown to my project's gradle and after syncing it caused an ERROR: C:\Users\MYPC\AndroidStudioProjects\MyAppName\amplify-gradle-config.json (The system cannot find the file specified). Removing only that particular line removed the error. Any help would be great. This is my first time posting please forgive me of any mistake.

**Comment by abhidaa1233** [comment]
Any updates regarding this issue?

**Comment by hanrahma123** [comment]
I'm having this issue too, very frustrating

**Comment by alhg** [comment]
I got the same error when on macOS Catalina when I had to add the plugin to my gradle build file in https://aws-amplify.github.io/docs/android/start?ref=amplify-android-btn#step-1-configure-your-app. I fixed the issue by using the updating `amplify-tools-gradle-plugin` to version 0.2.1

This was the classpath that I used: `classpath 'com.amplifyframework:amplify-tools-gradle-plugin:0.2.1'`

**Comment by nikhname** [comment]
Closing with https://github.com/aws-amplify/docs/pull/1365
