### ISSUE TITLE
updateUserAttributes does not update localStorage values

### ISSUE THREAD

**Issue by ahallora** [aws-amplify/docs#1079]
**Describe the bug**
I use the Auth library to signUp and signIn Cognito users (not federated), like this:

```javascript
Auth.signUp({
    'username': 'jdoe',
    'password': 'mysecurerandompassword#123',
    'attributes': {
        'email': 'me@domain.com',
        'name': 'My old name'
    }
});
```

I now want to update the name attribute of a logged in Cognito-user so I use the snippets found at https://aws-amplify.github.io/docs/js/authentication#working-with-user-attributes and do this:

```javascript
let user = await Auth.currentAuthenticatedUser();
let result = await Auth.updateUserAttributes(user, {
    'name': 'My new cool name'
});
```

The result returns `SUCCESS` however, the old name value are stil kept in localStorage key `CognitoIdentityServiceProvider.39qtq......4.userData` with the (old) data still:
```json
{"UserAttributes":[{"Name":"name","Value":"My old name"}, {"Name":"sub","Value":"0b92...24"},{"Name":"email_verified","Value":"true"},{"Name":"email","Value":"me@domain.com"}],"Username":"0b21...94"}
````

**To Reproduce**
Steps to reproduce the behavior; See above.

**Expected behavior**
I expect that `Auth.updateUserAttributes` will also update the values in localStorage. 

**Desktop (please complete the following information):**
 - OS: OSX 10.15.1
 - Browser: Chrome 79.0.3945.88 64-bit

**Comment by kfwebdev** [comment]
@ahallora I was also having this issue and was able to get around it using [this](https://github.com/aws-amplify/amplify-js/issues/2534#issuecomment-470882136). https://github.com/aws-amplify/amplify-js/issues/2534#issuecomment-470882136

**Comment by elorzafe** [comment]
That issue was fixed on the library https://github.com/aws-amplify/amplify-js/pull/5394, that workaround is no longer need. So docs change is not required
