### ISSUE TITLE
Interactions js api docs missing

### ISSUE THREAD

**Issue by Judgeja** [aws-amplify/docs#1087]
**Describe the bug**
Getting "Page Not Found" when following link for the docs

**To Reproduce**
1. Go to 'https://aws-amplify.github.io/docs/js/interactions'
2. Click on 'visit our API Reference' at the bottom of the page
3. The link opens at 'https://aws-amplify.github.io/docs/api/classes/interactions.html'
4. Page Not Found

**Expected behavior**
To see the documentation for the Interactions JS API

**Comment by sammartinez** [comment]
@Judgeja, Thanks for bringing this to our attention! I did create a Pull Request to resolve this. Once it's approved we can get it merged in. Also, I want callout that we do accept Pull Request if there is a next time you come across a similar link
