### ISSUE TITLE
Amplify.API.mutate or AWSAppSyncClient ?

### ISSUE THREAD

**Issue by cabeaulac** [aws-amplify/docs#1094]
**Is your feature request related to a problem? Please describe.**
The documentation here: https://aws-amplify.github.io/docs/ios/start
show using `Amplify.API` to access an API.
The document here: https://aws-amplify.github.io/docs/cli-toolchain/graphql
shows using `AWSAppSyncClient`

The two aren't compatible as pod versions conflict.
Podfile
```
  use_frameworks!
  # Pods for nike-athlete-ios
  pod 'amplify-tools'
  pod 'Amplify'
  pod 'AWSPluginsCore'
  pod 'AmplifyPlugins/AWSAPIPlugin'
  pod 'AWSMobileClient', '~> 2.12.0'      # Required dependency
  pod 'AWSAuthUI', '~> 2.12.0'            # Optional dependency required to use drop-in UI
  pod 'AWSUserPoolsSignIn', '~> 2.12.0'   # Optional dependency required to use drop-in UI
  # pod 'AWSAppSync', ' ~> 2.9.0'
```
If you add AWSAppSync you get this error
```
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "AWSCore":
  In snapshot (Podfile.lock):
    AWSCore (= 2.12.3)

  In Podfile:
    AWSAppSync (~> 2.9.0) was resolved to 2.9.2, which depends on
      AWSCore (~> 2.8.0)

    AWSAuthUI (~> 2.12.0) was resolved to 2.12.3, which depends on
      AWSCore (= 2.12.3)
```

Here is an example of an API schema using owner permissions with Cognito user pools auth.
```
type Profile @model
@auth (
  rules: [
    { allow: owner },
    { allow: private, operations: [create, read, update] }
  ]
)
{
  id: ID!
  email: String!
  firstname: String
  lastname: String
}
```
Notice there is no `owner` field in the API. Some documentation says to add it into the schema, some says the framework handles it for you.

**Describe the solution you'd like**
What is the correct way to access the API endpoint? `Amplify.API` or `AWSAppSyncClient`? Do we need to add an owner field and how does `Amplify.API` populate it and use it during retrieval?

**Describe alternatives you've considered**
Changing the app back to using AWSAppSyncClient but Amplify.API is easier to read. 

**Additional context**
Don't know what the clear direction is here. Please help.

**Comment by jamesonwilliams** [comment]
@cabeaulac At this time, the Amplify projects for iOS and Android are still in "Preview" (beta). As such, `AWSAppSyncClient` is the only suitable option for production interaction with an AppSync endpoint, at this time. When Amplify achieves a 1.0 release, `Amplify.API.mutate` would be the preferred mechanism for interacting with an AppSync endpoint.

**Comment by cabeaulac** [comment]
Hey @jamesonwilliams Thanks for the update and direction. Really appreciate it. Switching back to `AWSAppSyncClient` now. :-)

**Comment by lingxiao** [comment]
@jamesingham  is this still true as of April 20th, 2020?

**Comment by jamesingham** [comment]
> @jamesingham is this still true as of April 20th, 2020?

I'm not sure! Did you mean to tag someone else? ;)

**Comment by jamesonwilliams** [comment]
@lingxiao @jamesingham Looks like maybe you wanted me, @jamesonwilliams!

This is still a true statement as of 20APR2020, but we will be making an announcement "soon".

> At this time, the Amplify projects for iOS and Android are still in "Preview" (beta). As such, AWSAppSyncClient is the only suitable option for production interaction with an AppSync endpoint, at this time. When Amplify achieves a 1.0 release, Amplify.API.mutate would be the preferred mechanism for interacting with an AppSync endpoint.

**Comment by ashishverma1108** [comment]
```
[!] CocoaPods could not find compatible versions for pod "Amplify":
  In snapshot (Podfile.lock):
    Amplify (= 0.11.0)

  In Podfile:
    Amplify

    AmplifyPlugins was resolved to 0.9.0, which depends on
      AmplifyPlugins/AWSAPIPlugin (= 0.9.0) was resolved to 0.9.0, which depends on
        AWSPluginsCore (= 0.9.0) was resolved to 0.9.0, which depends on
          Amplify (= 0.9.0)

```
I am trying to follow tutorial on https://aws-amplify.github.io/docs/ios/start and getting this error... appreciate any suggestions to resolve this, thanks.

**Comment by wooj2** [comment]
Hey @ashishverma1108 ,

Thanks for reaching out!

Hmm.. I'm surprised that you are seeing AmplifyPlugins resolve to our initial version of `0.9.0`.
1.  Could you include a copy of your Podfile (or at least the AWS/Amplify relevant pieces)?  Based on the "getting started" link you included above, I would expect the `Podfile` to look something like this:
```
target 'MyTestApp' do
  use_frameworks!

    pod 'amplify-tools'
    pod 'Amplify'
    pod 'AWSPluginsCore'
    pod 'AmplifyPlugins/AWSAPIPlugin'
end
```
2.  Have you tried clearing your cache?  You can try running the command to clear your cache, and then update your repo:
```
pod cache clean --all && pod install --repo-update
```
3.  Finally, if all else fails, you can delete the `Podfile.lock` file (and the generated Pods directory), and try to execute the command above to clean the cache and update your repo.

Best of luck!

**Comment by ashishverma1108** [comment]
Hi @wooj2 

Thanks for prompt response!
bit more context for you.. I've been looking at two different tutorial and am sure I mixed things up. [here](https://aws.amazon.com/blogs/mobile/introducing-aws-amplify-for-ios-and-android/) is the other one. 

1. My podfile looks a little different because I was trying to integrate S3. But seems like there may be better ways to do this
````
platform :ios, '13.0'

AWS_SDK_VERSION = "2.12.0"

target 'easytest1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Amplify'
  pod 'AWSPluginsCore'
  pod 'AmplifyPlugins/AWSS3StoragePlugin'

  pod "AWSMobileClient", "~> #{AWS_SDK_VERSION}"
  pod 'AWSAuthUI', "~> #{AWS_SDK_VERSION}"
  pod 'AWSUserPoolsSignIn', "~> #{AWS_SDK_VERSION}"
  # Pods for easytest1

end

```

2. To fix this error I actually updated the podfile.lock to downgrade the amplufy version to 0.9.0 and it worked perfectly. Would you recommend using 0.11.0?

Also, the tutorial page seem to have updated.. thank you so much for pushing new material!

**Comment by brene** [comment]
> I am trying to follow tutorial on https://aws-amplify.github.io/docs/ios/start and getting this error... appreciate any suggestions to resolve this, thanks.

Hi @ashishverma1108 - we have recently updated our documentation. Here's the new iOS SDK getting started guide. https://docs.amplify.aws/start/q/integration/ios
and here's the iOS Amplify Libraries (preview) getting started guide: https://docs.amplify.aws/lib/getting-started/setup/q/platform/ios

**Comment by ashishverma1108** [comment]
Thanks so much @brene

**Comment by Maxim-Gorin** [comment]
> 404
Apologies––we can't seem to find the page for which you're looking. If this is a mistake, please file an issue and we'll fix it ASAP.
