### ISSUE TITLE
Amplify Roadmap

### ISSUE THREAD

**Issue by cmckni3** [aws-amplify/docs#1096]
Does the Amplify team have a public roadmap similar to [containers](https://github.com/aws/containers-roadmap) and [cloudformation](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap) teams have? 

I am also looking for a public Cognito roadmap as well.

**Comment by cmckni3** [comment]
Any updates?

**Comment by cmckni3** [comment]
Guessing from [comment in a previous issue](https://github.com/aws-amplify/amplify-js/issues/2045#issuecomment-436006265) this won't happen.

**Comment by baldfatchris** [comment]
If there is no roadmap, am I right to assume there is no strategic plan behind this project?
If that's the case then there's a high chance it will get canned before there is ever a production release?

**Comment by jackvhall** [comment]
> If there is no roadmap, am I right to assume there is no strategic plan behind this project?
> If that's the case then there's a high chance it will get canned before there is ever a production release?

I feel like this is a valid concern. The lack of a public roadmap, in addition with the staleness of the community at https://amplify.aws/community/ (no "monthly newsletter" in 2 months, no events), gives me pause before starting an app on Amplify if AWS isn't going to put out the effort.

**Comment by rraczae** [comment]
+1

**Comment by zzZCodeZzz** [comment]
+1

**Comment by shetshrikant** [comment]
Latest newsletter - Week 9 - March 4th to March 10th 2021. Is the project closing?

**Comment by matart15** [comment]
+1

**Comment by michblazek** [comment]
+1

**Comment by jamesmillerburgess** [comment]
This is reassuring - There is a job post for an amplify senior product manager whose job is to manage the product backlog: https://www.amazon.jobs/en/jobs/1948727/sr-product-manager-technical-aws-amplify-aws-amplify?no_int_redir=1

**Comment by adityadua24** [comment]
+1 
Absence of a public roadmap makes me hesitant to use amplify extensively in my business

**Comment by tagazok** [comment]
+💯

**Comment by ernestostifano** [comment]
+1

**Comment by eoghanatfacet** [comment]
For anyone who swings by here, hopefully what you're looking for is at 
https://github.com/orgs/aws-amplify/projects/130
