### ISSUE TITLE
Problem faced in subscribe() method of the https://aws.amazon.com/blogs/mobile/building-an-android-app-with-aws-amplify-part-2/

### ISSUE THREAD

**Issue by abhidaa1233** [aws-amplify/docs#1099]
I faced an issue in [https://aws.amazon.com/blogs/mobile/building-an-android-app-with-aws-amplify-part-2/](https://aws.amazon.com/blogs/mobile/building-an-android-app-with-aws-amplify-part-2/), This is Part 2 of the series and the code is exact;y same and continuation as Part 1 of the same the issue is whenever I'm calling the subscribe() method for testing, my screen first shows a completely white blank screen without the floating button for 3-4 seconds then becomes black completely and freezes, the code is exactly as per part 1 and 2, any guidance would be helpful

**Comment by jamesonwilliams** [comment]
Thanks @abhidaa1233 for filing #1075. Closing #1099 as a duplicate.

**Comment by abhidaa1233** [comment]
@jamesonwilliams  but both were different issues not duplicates

**Comment by jamesonwilliams** [comment]
Hi @abhidaa1233, it looks like, in both cases, you are receiving this error:

> apply plugin: 'com.amplifyframework.amplifytools' caused an ERROR: C:\Users\MYPC\AndroidStudioProjects\MyAppName\amplify-gradle-config.json (The system cannot find the file specified)

Can you provide more information about how #1099 is different from #1075? If they are indeed different, please feel free to re-open #1099, with additional information. Thanks!

**Comment by abhidaa1233** [comment]
@jamesonwilliams First of all Thank you for your time sir.
 #1099 is different because I remember the problem I faced in both. You can view what's the heading of #1099 and it's description is which I wrote at the beginning. Later when someone responded I told him about another issue I faced which is in the amplify framework. The issue of #1099 is that Subscibe() freezes the screen and there is a complete black freezed screen with no error thrown, it just hangs forever. The issue #1075 is what you said.
This #1099 issue is regarding an article which is very nicely written and is in aws blog. I asked what the issue is or if its old what are the changes I should make. This issue is faced by few other people also which you can see in the comments in that article.
 It becomes easy for a beginner when functionalities of aws are given with some sample examples as it can be a bit confusing at first with so many functionalities. And by googling we get only those article.
But anyways thank you again for your time and consideration.

**Comment by bugzbuks** [comment]
I'm stuck with the same problem. **amplify-gradle-config.json** is not generated on windows 10. Is there a work around? Can I generate this json file myself?

**Comment by bugzbuks** [comment]
Okay I've played around and generated the json configuration manually with the following:

```
{
    "profile": "<PROFILE_NAME>", // for example "default"
    "envName": "<ENVIRONMENT_NAME>", //for example "amplify"
    "syncEnabled": true
}
```

Next I placed the file in the folder : _<YourAndroidApp>\app\src\main\res\raw_

Now the error changed to the following:
ERROR: <_**YourAndroid>\amplify\backend\api\amplifyDatasource\transform.conf.json (The system cannot find the path specified)**_

**Comment by abhidaa1233** [comment]
No bro I left working with Amplify Framework when I faced these errors and moved on to their Android Sdk 2.0. As Amplify framework is in development process there are some problem and it may take some time. I would suggest please open a new issue so that they can work upon it.

**Comment by bugzbuks** [comment]
Boo! :( That's not good! Is there a way to use AWS Cognito without Amplify?

**Comment by abhidaa1233** [comment]
yes you can follow this https://aws-amplify.github.io/docs/sdk/android/authentication
