### ISSUE TITLE
Clarity on Guest Access

### ISSUE THREAD

**Issue by NigamAnkit** [aws-amplify/docs#1101]
**Is your feature request related to a problem? Please describe.**
Uploading file as guest user need to have a clarity, because as soon i set up and initialize AWSMobileClient and check status i get .signedOut and i was thinking to get guest access before i try yo upload any file.
Also Amplify SDK needs to update about the Background Transfer on iOS.
Another Problem while uploading file with guest access gives access issue if file is accessed from broweser as Unauthenticated user.

**Describe the solution you'd like**
May be I would like see any func that could give an some callback with status GUEST, so that developer can find it ok to upload file.

**Describe alternatives you've considered**
I thought any storage api before proper upload call.

**Comment by kneekey23** [comment]
Hi @desokroshan this should be fixed now as I added a note in PR #1122 to clarify this.
