### ISSUE TITLE
Documentation error - authentication page

### ISSUE THREAD

**Issue by kbanman** [aws-amplify/docs#1119]
The page https://aws-amplify.github.io/docs/js/authentication has a minor textual error:

In the example showing the use of `Auth.signIn()`, after the `validationData` property, the comment states "Optional, a random key-value pair map..."

"random" should be "arbitrary"

Also, clicking the "Edit" button at the top of that page leads me to a github 404 page.

**Comment by MikeVolo-SURGE** [comment]
Also, on the same Authentication document page, in a code example under "OAuth and HostedUI", it says  `'./aws_exports';`   instead of ` './aws-exports';`  

It has an underscore instead of dash

**Comment by brene** [comment]
Addressed in this: https://github.com/aws-amplify/docs/pull/1659
