### ISSUE TITLE
Amplify OAuth documentation not updated with SignInWithApple

### ISSUE THREAD

**Issue by t-moedano** [aws-amplify/docs#1127]
**Describe the bug**
If you look at Amplify authorization documentation and tutorials there is any information about SignInWithApple but the feature is implemented

**To Reproduce**
1. Go to https://aws-amplify.github.io/docs/js/authentication#oauth-and-federation-overview
2. See there is not instruction about SignInWithApple 
3. Go to https://aws-amplify.github.io/amplify-js/api/enums/cognitohosteduiidentityprovider.html
4. See that does not show that one provider options is 'SignInWithApple' although this option is a possible parameter in federatedSignIn method

**Expected behavior**
See instructions/information about the use of SignInWithApple option in AWS Amplify.

**Additional context**
SignInWithApple it is a important feature to be explained. Apple requires that new social logins contain Sign In With Apple option in order to approve new apps. It is good that AWS Amplify already support this feature but I didn't see any place AWS Amplify documentation talking about it.

**Comment by kneekey23** [comment]
hi @t-moedano have you tried following these instructions here? https://aws.amazon.com/blogs/security/how-to-set-up-sign-in-with-apple-for-amazon-cognito/

**Comment by t-moedano** [comment]
Hello @kneekey23 ! Yes, I also followed this guide when building my application. But what Im pointing is that the Amplify documentation should be updated at least pointing to other Apple related AWS guide. (As does with facebook and google)

Just looking at Amplify documentation it doesn’t seem that Amplify supports SignInWithApple but it really does. So, in the same way Amplify pages explain and give examples with Facebook and Google, should also include Sign In With Apple.

And also, the API reference itself seems to be outdated because it doesnt include SignInWithApple parameter as a possible option for federatedSignIn method.

**Comment by kneekey23** [comment]
Closing re: above mentioned PR
