### ISSUE TITLE
Use of red on black in code samples impedes use by people who are color-blind

### ISSUE THREAD

**Issue by shaunprocter** [aws-amplify/docs#1132]
The code samples use red on black which greatly impedes readability for people like myself who are color-blind.

It would be great if you could review this and choose a code styling theme that is more color-blind friendly, or a more complex approach would be to provide users the ability to dynamically switch between alternate code styling themes.

https://www.templatemonster.com/blog/designing-colorblind-friendly-website/
https://www.toptal.com/designers/colorfilter/

For now, I will work-around the issue by copying the sample code into my IDE.

Regards,

Shaun

**Comment by sammartinez** [comment]
@shaunprocter Can you provide a link to the sample code that you are referring to?

**Comment by shaunprocter** [comment]
Thanks @sammartinez I missed your question earlier otherwise I would have responded sooner.

The following page is an example of key characters such as @, ", :, -, and {} using red on black. The styling tries to highlight them by having what appears to be close to a true black as the background color for just these characters that are red. I took a screengrab and sampled the colors in Photoshop, what is appearing to me as a red to me might actually be dark pink, the black is definitely close but not quite true black. I'm colour blind so I initially missed some of these key characters when using this page the other night and it took me a while to realise I was missing something.

It would be great if these could use higher contrasting colours.

https://aws-amplify.github.io/docs/cli-toolchain/graphql'

Hope that helps, thanks.

**Comment by brene** [comment]
We've updated the design. Let me know if that addresses your concern.
