### ISSUE TITLE
Error in documentation of Storage of AWS amplify

### ISSUE THREAD

**Issue by shrishtychandra** [aws-amplify/docs#1138]
**Describe the bug**
Wrong class name here. it should be `MyStorage` and not `MemoryStorage`

![image](https://user-images.githubusercontent.com/57787398/74052539-16ba8780-4a00-11ea-92ff-6a3dc438d2d7.png)

**To Reproduce**
https://aws-amplify.github.io/docs/js/authentication#managing-security-tokens

React Native code

**Comment by sammartinez** [comment]
@ashika01 Where are these at?

**Comment by sw-yx** [comment]
@sammartinez the link provided shows this 
![image](https://user-images.githubusercontent.com/6764957/85350347-7fc81500-b533-11ea-9298-e9b1c5b0ccb2.png)

it does look like the name is wrong

**Comment by ashika01** [comment]
@sw-yx @shrishtychandra The docs has been updated to reflect the right way of using this.

**Comment by sw-yx** [comment]
nice one!
