### ISSUE TITLE
GraphQL Doc Feedback

### ISSUE THREAD

**Issue by chisholmd** [aws-amplify/docs#1139]
Its not a feature or a bug its a comment on the docs.
In the first example of creating a post and associating it with a blog the doc has this:
    createPost(input:{title:"My Post!", postBlogId: $blogId}) {

Tell me, where did the field "postBlogId" come from? It is not in the scheme created above, so is the field automatically created by the @connection directive in the notation?  Its like magic and I don't understand.  Please help.

**Comment by chisholmd** [comment]
Looks like the foreign key field is created in the 'many' table.  Unless I am way off in my understanding maybe a sentence in the doc that using the @connection annotation to set up relationships automatically creates a fk field using the pattern   childParentId  or postBlogId.  If this name is coming from somewhere else that I can't figure out, please set me straight.

**Comment by palpatim** [comment]
@chisholmd Thanks for the feedback. As you discovered, that field is part of the input type that is auto-generated by Amplify's GraphQL Transformer. You can see a direct analogy in the [`@connection` Usage docs](https://aws-amplify.github.io/docs/cli-toolchain/graphql#usage-3). 

I'll flag @nikhil-dabhade to review this to see if there's an opportunity to clarify this without cluttering the sample code with references to other parts of the docs.

**Comment by mauerbac** [comment]
This is resolved today. Please open up a new issue with follow-up questions.
