### ISSUE TITLE
Invalid JavaScript under Refreshing JWT Tokens docs

### ISSUE THREAD

**Issue by cmckni3** [aws-amplify/docs#1141]
**Describe the bug**

`Refreshing JWT Tokens` section has invalid JavaScript sample code.

**To Reproduce**

1. Go to https://aws-amplify.github.io/docs/js/authentication#react-components
2. Scroll to Refreshing JWT Tokens

The `refreshToken` function and `Promise` have syntax errors

**Expected behavior**

```javascript
function refreshToken() {
    // refresh the token here and get the new token info
    // ......

    return new Promise((res, rej) => {
        const data = {
            token, // the token from the provider
            expires_at, // the timestamp for the expiration
            identity_id, // optional, the identityId for the credentials
        }
        return res(data);
    });
}
```

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 80.0.3987.87

**Comment by amhinson** [comment]
#2015 will remove this section since it is meant for Identity Pool Federation and not User Pool Federation, which is covered on the [Advanced workflows](https://docs.amplify.aws/lib/auth/advanced/q/platform/js#token-refresh) page.
