### ISSUE TITLE
Angular doc improvements

### ISSUE THREAD

**Issue by manu2504** [aws-amplify/docs#1153]
**Problem**
Doc does not provide a way to subscribe to sign outs auth state change (only sign ins are described).

The [amplify doc for Angular](https://aws-amplify.github.io/docs/js/angular) reads:
> The authState’s ‘state’ attribute must be a string with one of the following values:
> 
> ‘confirmSignIn’
> ‘confirmSignUp’
> ‘forgotPassword’
> ‘requireNewPassword’
> ‘signedIn’
> ‘signIn’
> ‘signUp’

Also, the [code](https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-angular/src/providers/auth.state.ts) describes things inconsistent with the doc as it reads:
```typescript
export interface AuthState {
	state: string; // signedOut, signedIn, mfaRequired, newPasswordRequired
	user: any;
}
```
Why does the doc mention ‘requireNewPassword’ while the code 'newPasswordRequired'?

**Suggested solution**

- An update of the doc with the 'signedOut' option, as well as all other options applicable.
- An update of the code's comments so it is consistent with the doc

**Alternatives I've considered**
An explanation why 'signedOut' state is not in the list, if applicable

**Additional context**
Seems like integrating aws-amplify-angular is a painful task.
Shouldn't Amazon invest more in it? As far as I know, AWS is getting paid for developers using their backend services...

**Comment by manu2504** [comment]
@royjit I assume clarifying the Authentication API doc would bring enough value to the dev community to justify that you why not give it a go? That'd be lovely.

**Comment by brene** [comment]
Hey @manu2504 we've revamped our docs can you check if this is addressing your concerns?
https://docs.amplify.aws/start/q/integration/angular
https://docs.amplify.aws/ui/q/framework/angular

**Comment by manu2504** [comment]
Hey @brene,
Thanks, nice revamp, however the doc is still missing about [subscribing to auth state change](https://docs.amplify.aws/start/getting-started/nextsteps/q/integration/angular#subscribe-to-authentication-state-changes):
'signedOut' state still missing in the list, although in practice I get this state when signing out.

**Comment by brene** [comment]
@jordanranz / @dabit3 - can you look into this?

**Comment by mauerbac** [comment]
These docs have been updated
