### ISSUE TITLE
Refreshing JWT Tokens misplaced in user pool authentication section

### ISSUE THREAD

**Issue by khelnagar** [aws-amplify/docs#1162]
**Describe the bug**
`Refreshing JWT Tokens` section is misplaced in user pool federation section.

**To Reproduce**
1. Go to https://aws-amplify.github.io/docs/js/authentication#react-components
2. Scroll to Refreshing JWT Tokens

**Expected behavior**
- Talking about AWS credentials in the context of Cognito User Pools authentication does not apply.
- This statement about automatic token refresh should be only in Cognito Identity Pool Federation as in https://aws-amplify.github.io/docs/js/authentication#token-refresh where Cognito does refresh tokens of Google/Facebook automatically to keep AWS credentials valid at all times.

**Screenshots**
N/A

**Additional context**
- Related issue where user asking why Facebook/Google tokens returned in user pool idp attribute mapping are not refreshed, during Cognito user pool own id/access tokens are refreshed.
- User expected the above misplaced statement to mean that FB/Google tokens returned by attribute mapping (if any) would be refreshed as well.

**Comment by AdonousTech** [comment]
Speaking of this. Can someone verify whether Amplify also automatically refreshes LoginWithAmazon tokens. The implementation is similar insofar as using Auth.federatedSignin({customProvider: 'LoginWithAmazon'}), but it is unclear whether the token is automatically refreshed like Google/Facebook. Any clarification would be appreciated.

**Comment by khelnagar** [comment]
> Speaking of this. Can someone verify whether Amplify also automatically refreshes LoginWithAmazon tokens. The implementation is similar insofar as using Auth.federatedSignin({customProvider: 'LoginWithAmazon'}), but it is unclear whether the token is automatically refreshed like Google/Facebook. Any clarification would be appreciated.

I would like to point your attention into what meant by Amplify statement refreshing FB/Google tokens, is in the context of Federation in Identity Pool to keep AWS credentials valid at all times. My issue is that the doc has the same statement in **User Pool** Federation, which does not make sense regarding keeping AWS credentials valid.

I have looked at your [issue](https://github.com/aws-amplify/amplify-js/issues/5082) and found that it is irrelevant to the [documentation](https://aws-amplify.github.io/docs/js/authentication#token-refresh) you have mentioned (identity pool federation). I think you are asking about refreshing user pool tokens (in user pool federation using `Auth.federatedSignIn`) which should be done on the `CognitoUser` irrespective of whether user authenticated in user pool or federated with external IdP.

Note that federation in user pool is different than federation in identity pool. User is a `CognitoUser` in the former while is not in the latter.

**Comment by AdonousTech** [comment]
@khelnagar thanks for the clarification. I have only used federation (federated users) in the context of user pools. So yes, I was referring to user pool federation. User Pool federation seems to cover many of the required use cases (Facebook/Google/LWA/SAML/OIDC) so standalone identity pool federation seems to be less useful nowadays.

**Comment by khelnagar** [comment]
@AdonousTech 
> standalone identity pool federation seems to be less useful nowadays.

They're [different](https://aws.amazon.com/premiumsupport/knowledge-center/cognito-user-pools-identity-pools/); identity pools are not for authenticating users, they're for issuing temporary credentials to use AWS resources. These resources means a DynamoDB table for example which requires an AWS IAM permissions to access, these permissions are given in an IAM role (role is tied to the credentials) you assume when you federate with identity pool. APG is not considered AWS resource as it is a public REST API endpoint so anyone on the internet can hit - the authorizer is just to restrict the public endpoint to be hit with an authorized request/user.

Reiterating on the main issue is that AWS credentials does not make sense with user pool authentication, so is irrelevant in context of user pool federation in documentation.

**Comment by AdonousTech** [comment]
I get what you are saying, but you are viewing it very narrowly. I understand that identity federation is for authorizing access to AWS resources. When you use Federated Identities with a Cognito User Pool, the Cognito User Pool is a linked login (providing the Authentication piece). Have you used Federated Identities in conjunction with Cognito User Pools? The 2 are tightly integrated. Cognito User Pools is a Identity Provider for the Identity Pool.

For example, if I set up an IdentityPool, I pass in my Cognito User Pool as an identity provider (IdP). My authenticated CognitoUser assumes the Authenticated Role in my Identity Pool. 

```        "IdentityPool": {
            "Type": "AWS::Cognito::IdentityPool",
            "DependsOn": ["UserPool","UserPoolClient"],
            "Properties": {
                "IdentityPoolName": {"Ref": "IdentityPoolName"},
                "AllowUnauthenticatedIdentities": false,
                "CognitoIdentityProviders": [
                    {
                        "ClientId": {"Ref": "UserPoolClient"},
                        "ProviderName": {"Fn::Join" : 
                            [ "", [ {"Fn::Sub": "cognito-idp.${AWS::Region}.amazonaws.com/"},
                                    {"Ref": "UserPool"}
                                  ] 
                            ] }
                    }
                ]
            }
        }

Anyhow, my question is specifically related to Identity Federation within Cognito User Pools. So, yes, it is not relevant to standalone Identity Pool Federation. I use a combination (as shown above). So, that could explain the confusion.

**Comment by mauerbac** [comment]
following up on this issue as it's a year old. It looks like you originally linked to our old docs and auth has been re-organized here: https://docs.amplify.aws/lib/auth/advanced/q/platform/js. 

Please open a new issue with feedback on this. Thank you
