### ISSUE TITLE
When is AWS Amplify will be in production mode?

### ISSUE THREAD

**Issue by AbdallahFathoom** [aws-amplify/docs#1164]
It shows in your documentation that AWS Amplify for Android and iOS is in preview and not in production at the current time, wanted to inquire regarding that and when it will be ready.
there is lack of documentation on your website and community support.
I managed to do Sign up, Sign in and forget password and confirm user for my android app. I am stuck now implementing the chat feature for the app.

Thank you

**Comment by lawmicha** [comment]
hi @AbdallahFathoom, thanks for taking the time to open this question. Here's a response over in the Amplify iOS which is relavant for Android as well. 
https://github.com/aws-amplify/amplify-ios/issues/335#issuecomment-593408357

If you are having some troubles with implementing a chat feature in your app in android, feel free to open an issue over on the Android repo for your question or if you are facing a bug

https://github.com/aws-amplify/amplify-android/issues
