### ISSUE TITLE
Missing Android dependency declaration for Cognito HostedUI

### ISSUE THREAD

**Issue by janejjshen** [aws-amplify/docs#1166]
**Describe the bug**
Following the instruction under Using Hosted UI for Authentication, app crashes at run time because of a `NoClassDefFoundError` error for the `com.amazonaws.mobileconnectors.cognitoauth.Auth` class.

**To Reproduce**
Follow the instructions and add the following dependencies:
```
//For AWSMobileClient only:
implementation ('com.amazonaws:aws-android-sdk-mobile-client:2.16.+') { transitive = true }

//For the drop-in UI also:
implementation ('com.amazonaws:aws-android-sdk-auth-userpools:2.16.+') { transitive = true }
implementation ('com.amazonaws:aws-android-sdk-auth-ui:2.16.+') { transitive = true }
```

and added code to use the HostedUI:
```
 HostedUIOptions hostedUIOptions = HostedUIOptions.builder()
                .scopes("openid", "email")
                .build();
        SignInUIOptions signInUIOptions = SignInUIOptions.builder()
                .hostedUIOptions(hostedUIOptions)
                .build();

        // 'this' refers to the current active Activity
        AWSMobileClient.getInstance().showSignIn(this, signInUIOptions, new Callback<UserStateDetails>() {
            @Override
            public void onResult(UserStateDetails details) {
                Log.d(TAG, "onResult: " + details.getUserState());
            }

            @Override
            public void onError(Exception e) {
                Log.e(TAG, "onError: ", e);
            }
        });
```

**Expected behavior**
App should launch the HostedUI with the code example provided

**Smartphone (please complete the following information):**
 - Device: Android Emulator
 - OS: Pixel XL, API level 23

**Additional context**
Documentation missing the needed dependency as below that is not documented anywhere.
`implementation ('com.amazonaws:aws-android-sdk-cognitoauth:2.16.+')`

**Comment by TrekSoft** [comment]
Yes, you're 100% right. Just fixed it.
