### ISSUE TITLE
Amplify Configure issue

### ISSUE THREAD

**Issue by prmacias** [aws-amplify/docs#1167]
**Describe the bug**

I typed amplify configure in terminal and got this error -

```
/Users/xxx/.nvm/versions/node/v8.16.0/lib/node_modules/@aws-amplify/cli/lib/plugin-manager.js:47
    catch {
          ^

SyntaxError: Unexpected token {
    at Generator.next (<anonymous>)
    at Object.Module._extensions..js (module.js:664:10)
```

**To Reproduce**
1. install npm
2. install amplify
3. type amplify configure
4. got the error.

I reinstalled the amplify but didn't work. I tried another project - test to see if it works - didn't work.

**Expected behavior**

I would like to configure the amplify and init my ios project.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 10.14.4

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kaustavghosh06** [comment]
@prmacias The minimum node v required to run the CLI is v10.x. Could you please upgrade your node version and let me know if you're still seeing this issue?

**Comment by prmacias** [comment]
@kaustavghosh06 yes, upgraded node to 10.x and fixed the issue. Thanks!
