### ISSUE TITLE
Amplify - DataStore generate models from RDS Aurora

### ISSUE THREAD

**Issue by noorcreative** [aws-amplify/docs#1171]
**Describe the problem**
I have RDS in the backend and trying to use AppSync in react-native development, but so far, most of the support is only for DynamoDB!
Are you planing to add the feature of generating models from RDS Aurora that can be handled by DataStore.

**Comment by undefobj** [comment]
@noorcreative RDS is not supported for Conflict Resolution in AppSync so we cannot add it for DataStore at this time. We've raised it with AppSync team as well however if you'd like to request this and track it for their roadmap please raise a request at https://github.com/aws/aws-appsync-community

**Comment by nniirraavv** [comment]
Hello @undefobj 
Looking for DataStore RDS support for Conflict Resolution in AppSync.
Any update on this.?
