### ISSUE TITLE
Update Amazon Pinpoint Push Notifications documentation

### ISSUE THREAD

**Issue by teo029** [aws-amplify/docs#1180]
**Is your feature request related to a problem? Please describe.**
Amazon Pinpoint Push Notifications documentation is deprecated. It requires the [PushNotificationIOS](https://reactnative.dev/docs/pushnotificationios) library which is also deprecated and when using the new library that replaced it ([react-native-push-notification-ios](https://github.com/react-native-community/react-native-push-notification-ios)), it also uses depracated methods in the AppDelegate file.

Moreover, everything needs manual linking, while most new packages use auto-linking.

**Describe the solution you'd like**
Seems like the AWS Push Notification docs need a redo.

**Describe alternatives you've considered**
Using Google's FCM react native push notifications while letting AWS PinPoint funnelling behind.

**Comment by amhinson** [comment]
@teo029 We've recently updated the [Push Notification docs](https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/js) just a bit to replace any outdated information. Do you see any other parts that might need to be addressed?

**Comment by teo029** [comment]
@amhinson I will check the docs when I'll setup another project. You can close it by now and thank you!
