### ISSUE TITLE
No mention of Auth#userAttributes() method in documentation

### ISSUE THREAD

**Issue by chantzlarge** [aws-amplify/docs#1188]
**Describe the bug**
No mention of `Auth#userAttributes()` in 'Authentication' documentation for retrieving user attributes. Current documentation incorrectly states to retrieve user attributes using `Auth#currentAuthenticatedUser()`.

**To Reproduce**
1. Create a default user pool
2. Register a use
3. Set standard attributes user `Auth#updateUserAttributes`
4. Attempt to retrieve user attributes using method currently described in documentation: 
![image](https://user-images.githubusercontent.com/4284843/75988740-4cdc1180-5eaf-11ea-9313-60d08ade6570.png)

**Expected behavior**
User attributes (i.e. given_name, familiy_name, would appear in the resulting user#attributes property. However, in order to retrieve the attributes the unmentioned `Auth#userAttributes()`  method must be used.

**Comment by ericclemmons** [comment]
@chantzlarge If the issue was that updated attributes weren't available via `user.attributes`, this may have fixed via this PR:
> https://github.com/aws-amplify/amplify-js/pull/5394

Your issue sounds similar to https://github.com/aws-amplify/amplify-js/issues/5043, where you're correct in expecting updates to be persisted immediately.

**Comment by elorzafe** [comment]
@chantzlarge You mean using it like this?

```javascript
const user = await Auth.currentAuthenticatedUser();
const attributes = await Auth.userAttributes(user);
```

Both ways are still valid, but this seems more work than the one that is mentioned on the docs.

**Comment by chantzlarge** [comment]
@elorzafe correct. As @ericclemmons assumptions were correct regarding the usage intent--I had expected the method response to include the most recent changes as similarly described in [#5043](https://github.com/aws-amplify/amplify-js/issues/5043) the issue was the the `#userAttributes()`. 


Personally, I wrap this function in my application for convenience and feel like it would have saved me time if it were included in the ["Managing User Attributes"](https://docs.amplify.aws/lib/auth/manageusers/q/platform/js#managing-user-attributes) section of the documentation but that's my humble opinion.

**Comment by dabit3** [comment]
@chantzlarge thanks for the issue. I've been thinking about this and since we now add the `attributes` directly from calling `Auth.currentAuthenticatedUser`, I think we should recommend using that method as it's less steps.

Please have a look at [this PR](https://github.com/aws-amplify/docs/pull/2563/commits/6b0905b5af2fd77a1f6f8cc93a078b132eec7208) and let me know if you think it addresses the issue in a way that would make sense for future developers.
