### ISSUE TITLE
Auto Delete S3 buckets when environment is removed

### ISSUE THREAD

**Issue by daghanacay** [aws-amplify/docs#1209]
**Is your feature request related to a problem? Please describe.**
When we delete an nevironment it does not delete the s3 buckets corresponding to that environment

**Describe the solution you'd like**
when I execute

amplify env remove [envname]

**Describe alternatives you've considered**
manual deletion of S3 buckets

**Additional context**
When the team members grow workfole defined here https://aws-amplify.github.io/docs/cli-toolchain/quickstart?sdk=js#concepts-1 becomes untractable and leaves a lot of orphan S3 buckets

**Comment by jamesonwilliams** [comment]
Move to CLI project as https://github.com/aws-amplify/amplify-cli/issues/3627
