### ISSUE TITLE
Getting Started page for purejs needs older stable "aws-amplify" module

### ISSUE THREAD

**Issue by tmiki** [aws-amplify/docs#1213]
**Describe the bug**
A webpack dev web server cannot run when I run the "npm start" command, although I followed  steps on the Getting Started (purejs) document below as per instruction.

https://aws-amplify.github.io/docs/js/start?platform=purejs

Then, I run the "npm start" command, the following error messages appeared.

```
$ npm start

> amplify-js-app@1.0.0 start D:\Dev\git-practice\practice-amplify-js
> webpack && webpack-dev-server --mode development

Hash: 159e8ed28afe5ec76c05
Version: webpack 4.42.0
Time: 129ms
Built at: 2020-03-10 1:18:38 AM
         Asset      Size  Chunks             Chunk Names
    index.html  1.66 KiB          [emitted]
main.bundle.js  31.2 KiB    main  [emitted]  main
Entrypoint main = main.bundle.js
[./src/app.js] 949 bytes {main} [built]
[./src/aws-exports.js] 662 bytes {main} [built]

ERROR in ./src/app.js
Module not found: Error: Can't resolve 'aws-amplify' in 'C:\practice-amplify-js\src'
 @ ./src/app.js 4:0-43 7:0-7
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! amplify-js-app@1.0.0 start: `webpack && webpack-dev-server --mode development`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the amplify-js-app@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\myname\AppData\Roaming\npm-cache\_logs\2020-03-09T16_18_38_740Z-debug.log
```

**To Reproduce**
1. Go to "https://aws-amplify.github.io/docs/js/start?platform=purejs"
2. Hover the mouse cursor over the button below of the "Select your framework", then click "JavaScript".
3. Create a new JS app project with following the chapter "Step 1. Create a New App"
4. Create the following files with copy&paste as the document instructs.
- package.json
- webpack.config.js
- index.html
- src/app.js
5. Run "npm install"
6. Run "npm start"

**Expected behavior**
A webpack dev server with listening TCP/8080 port runs without any errors.
And it should return sample contents when I open the URL "http://localhost:8080".

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: -(This error occurred on a CLI.)
 - Node.js version: v10.19.0
 - npm version: 6.13.4

**Additional context**
I tried to use the older "aws-amplify" module instead of the latest ones.
The sample app worked expectedly.

I modified the package.json with the following change to use older one (version 1.1.33).

The original package.json:

```
{
  "name": "amplify-js-app",
  "version": "1.0.0",
  "description": "Amplify JavaScript Example",
  "dependencies": {
    "@aws-amplify/api": "latest",
    "@aws-amplify/pubsub": "latest"
  },
```

Modified package.json:

```
{
  "name": "amplify-js-app",
  "version": "1.0.0",
  "description": "Amplify JavaScript Example",
  "dependencies": {
    "aws-amplify": "^1.1.33"
  },
```

**Comment by swaminator** [comment]
@tmiki can you try this: https://docs.amplify.aws/start/getting-started/setup/q/integration/js

**Comment by ericclemmons** [comment]
I created a PR to address this, namely using `aws-amplify` over individually installing `@aws-amplify/api|pubsub`:
> https://github.com/aws-amplify/docs/pull/1985
