### ISSUE TITLE
error downloading cli

### ISSUE THREAD

**Issue by GitAfterIt1** [aws-amplify/docs#1219]
**Describe the bug**
the CLI won't download on my Mac. it says command not found. I checked to see if Node.js was installed also said command not found. tried to download node.js. it wouldn't open.

**To Reproduce**
download node.js on Mac  it won't go.

**Expected behavior**
stuff to download

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by brene** [comment]
hi @GitAfterIt1 - it looks like you haven't install npm & node. Please follow the links on the pre-requisite pages to install those dependencies. https://docs.amplify.aws/start/getting-started/installation/q/integration/js
