### ISSUE TITLE
Add docs for custom resolvers for batch requests.

### ISSUE THREAD

**Issue by janhesters** [aws-amplify/docs#1232]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to spent hours, moving from one error to another, not knowing if I'm doing things right. This time I'm trying to create a batch resolver to create multiple items while still retaining authentification (following the advice given by @manueliglesias in [this issue](https://github.com/aws-amplify/amplify-js/issues/2873)). So basically I'm trying to write `"BatchPutItem"` resolvers (`req` and `res`) for this scheme:

```graphql
type Todo @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  title: String!
  description: String
  completed: boolean
}

type Mutation {
  batchAddTodos(todos: [TodoInput]): [Todo]
}
```

Here are the `CustomResources.json` I wrote:

```json
 "Resources": {
    "EmptyResource": {
      "Type": "Custom::EmptyResource",
      "Condition": "AlwaysFalse"
    },
    "BatchAddTodosResolver": {
      "Type": "AWS::AppSync::Resolver",
      "Properties": {
        "ApiId": {
          "Ref": "AppSyncApiId"
        },
        "DataSourceName": "TodoTable",
        "TypeName": "Mutation",
        "FieldName": "batchAddTodos",
        "RequestMappingTemplateS3Location": {
          "Fn::Sub": [
            "s3://${S3DeploymentBucket}/${S3DeploymentRootKey}/resolvers/Mutation.batchAddTodos.req.vtl",
            {
              "S3DeploymentBucket": {
                "Ref": "S3DeploymentBucket"
              },
              "S3DeploymentRootKey": {
                "Ref": "S3DeploymentRootKey"
              }
            }
          ]
        },
        "ResponseMappingTemplateS3Location": {
          "Fn::Sub": [
            "s3://${S3DeploymentBucket}/${S3DeploymentRootKey}/resolvers/Mutation.batchAddTodos.res.vtl",
            {
              "S3DeploymentBucket": {
                "Ref": "S3DeploymentBucket"
              },
              "S3DeploymentRootKey": {
                "Ref": "S3DeploymentRootKey"
              }
            }
          ]
        }
      }
    }
  },
```

**Describe the solution you'd like**
It would be awesome if the docs had an example for how to achieve this, because as I assume this is a common issue.

**Describe alternatives you've considered**
The alternative is figuring it out myself, which I'm still trying to do. It would just be great to have more examples for custom resolvers in the docs 🤗 

**Edit:** [This issue](https://github.com/aws-amplify/amplify-cli/issues/1079) is the current state of my attempt.

**Comment by mauerbac** [comment]
Hi everyone -- sorry for the delay. Will try to get this documented asap. cc @brene

**Comment by Ronyo** [comment]
Has there been any progress on allowing bath operations with Amplify CLI?
