### ISSUE TITLE
Documentation Issue - Administrative actions

### ISSUE THREAD

**Issue by challapradyumna** [aws-amplify/docs#1260]
The documentation for endpoints and the expected parameters for those endpoints under   [Administrative actions](https://aws-amplify.github.io/docs/cli-toolchain/quickstart#administrative-actions) has repetitive wording that does not make much sense. Please update the documentation.

**Comment by mayteio** [comment]
Agreed. Most actions just say "Adds a user to a specific Group. Expects username and groupname in the POST body". I don't think, for example, `removeUserFromGroup` adds a user to a specific group.

**Comment by xitanggg** [comment]
Agreed. CLI has clear documentation error for the Administrative Actions section. See **bolded**, in which everything is described as `Adds a user to a specific Group`, which clearly wrong.
[https://aws-amplify.github.io/docs/cli-toolchain/quickstart#administrative-actions](https://aws-amplify.github.io/docs/cli-toolchain/quickstart#administrative-actions)

> addUserToGroup: Adds a user to a specific Group. Expects username and groupname in the POST body.
removeUserFromGroup: **Adds** `(Should be Remove)` a user **to** `(of)` a specific Group. Expects username and groupname in the POST body.
confirmUserSignUp: **Adds a user to a specific Group** . Expects username in the POST body.
disableUser: **Adds a user to a specific Group**. Expects username in the POST body.
enableUser: **Adds a user to a specific Group**. Expects username in the POST body.
getUser: **Adds a user to a specific Group**. Expects username as a GET query string.
listUsers: **Adds a user to a specific Group**. You can provide an OPTIONAL limit as a GET query string, which returns a NextToken that can be provided as a token query string for pagination.
listGroupsForUser: **Adds a user to a specific Group**. Expects username as a GET query string. You can provide an OPTIONAL limit as a GET query string, which returns a NextToken that can be provided as a token query string for pagination.
listUsersInGroup: **Adds a user to a specific Group**. Expects groupname as a GET query string. You can provide an OPTIONAL limit as a GET query string, which returns a NextToken that can be provided as a token query string for pagination.
signUserOut: Signs a user out from User Pools, but only if the call is originating from that user. Expects username in the POST body.

**Comment by swaminator** [comment]
@xitanggg @challapradyumna  this is resolved: https://docs.amplify.aws/cli/auth/admin
