### ISSUE TITLE
A couple of subscriptions API documentation bugs/suggestions

### ISSUE THREAD

**Issue by aharbick** [aws-amplify/docs#1279]
**Describe the bug**

In this documentation: https://aws-amplify.github.io/docs/cli-toolchain/graphql?sdk=js#filter-subscriptions-by-model-fields-andor-relations

First the mutations code is wrong.  I think it requires an array and should be:
```
  onUpdateComment(id: ID, commentTodoId: String): Comment @aws_subscribe(mutations: ["updateComment"])
```

Otherwise you get a deploy error like this:
```
UPDATE_FAILED               GraphQLSchema                                  AWS::AppSync::GraphQLSchema Fri Mar 20 2020 14:54:24 GMT-0400 (Eastern Daylight Time) Schema Creation Status is FAILED with details: Schema has the following errors:  - The mutations argument on the aws_subscribe directive has an invalid value
```

Second it wasn't clear to me that you can add multiple subscriptions by naming them differently and then using different parameterizations.  Perhaps adding an example like this would help:

```
type Subscription {
...
  onUpdateComment(id: ID): Comment @aws_subscribe(mutations: ["updateComment"])
  onUpdateCommentForTodo(id: ID, commentTodoId: String): Comment @aws_subscribe(mutations: ["updateComment"])
...
}
```

**Comment by mauerbac** [comment]
hi @aharbick - thanks for pointing this out. I believe the first code sample no longer exists and the AppSync docs are better suited to address this -> https://docs.aws.amazon.com/appsync/latest/devguide/real-time-data.html
