### ISSUE TITLE
[v2-feedback] Possible duplicate/wrong snippet

### ISSUE THREAD

**Issue by jimcal** [aws-amplify/docs#1311]
**Page**: [`https://docs.amplify.aws/start/getting-started/data-model?integration=js`](https://docs.amplify.aws/start/getting-started/data-model?integration=js)

**Feedback**: 
From the screenshot, it looks like the first and second code snippets were identical. With the mention of SDL and 

> The @model directive 

I wonder if the second one meant to be a different snippet, i.e. more like the following

`type Todo @model {
  id: ID!
  name: String!
  description: String
}`

**Comment by brene** [comment]
@dabit3 - I think there is an opportunity here to simplify the content. WDYT?

**Comment by dabit3** [comment]
Thanks @brene, having a look

**Comment by dabit3** [comment]
Thanks for the issue @jimcal , we've updated the docs based on your feedback.
