### ISSUE TITLE
[v2-feedback] Better directives navigation

### ISSUE THREAD

**Issue by awsed** [aws-amplify/docs#1312]
**Page**: [`https://docs.amplify.aws/cli/graphql-transformer/directives`](https://docs.amplify.aws/cli/graphql-transformer/directives)

**Feedback**: 

Suggest the navigation bar on the right side could have the directives in bold so it's easier to visualize and navigate.

**Comment by brene** [comment]
@awsed - what do you think if we just had them in `code` format?

**Comment by brene** [comment]
closing as this has become stale. Please re-open if this is still a passionate request.
