### ISSUE TITLE
[v2-feedback]

### ISSUE THREAD

**Issue by jimcal** [aws-amplify/docs#1313]
**Page**: [`https://docs.amplify.aws/start/getting-started/data-model?integration=react-native`](https://docs.amplify.aws/start/getting-started/data-model?integration=react-native)

**Feedback**: 
While the name isn't necessary have to be the same as the comment shows here, using `amplify-api` could cause unnecessary confusion ("-" is not allowed.)

> ? Provide API name:
> # (amplify-api)

**Comment by swaminator** [comment]
Good feedback: addressed here: https://github.com/aws-amplify/docs/pull/1339

**Comment by brene** [comment]
Seems like we regressed. Re-addressed the issue here: #1492
