### ISSUE TITLE
Android SDK Setup Options Page missing from V2

### ISSUE THREAD

**Issue by jpignata** [aws-amplify/docs#1371]
**Describe the bug**
https://aws-amplify.github.io/docs/android/manualsetup is not represented in V2, however there is content that refers to it and attempts to link to it.

**To Reproduce**
1. Go to https://aws-amplify.github.io/docs/android/manualsetup
2. See the informative content
3. Go to the v2-preview branch
4. Notice its absence
5. Feel feelings

**Expected behavior**
It's expect the content to be represented in v2, as it is intended to be a higher-quality superset.

**Comment by mlabieniec** [comment]
@jpignata I found a similar issue with iOS for push notifications. I copied the MD file over and added an entry in the `menu.json`, and added a parent/fragment, see here: https://github.com/aws-amplify/docs/pull/1399/files#diff-78e7e6c1ae4911f5e55b1161cc90be5a

**Comment by jpignata** [comment]
I'll port it over, make it a top level item, and reconcile for Android and iOS in a separate PR.

**Comment by jpignata** [comment]
@brene @jordanranz and I chatted, and are considering placing this content on this page under a header: https://docs.amplify.aws/sdk?platform=android -- do you have a better idea?

**Comment by jpignata** [comment]
@brene and I discussed, and after saying it out loud I hated my idea. We're going to pull this in as a nav item on the bottom of the list as it is today. I'll work on a pull for Android and iOS to resolve this.
