### ISSUE TITLE
Broken link on js auth getting-started page

### ISSUE THREAD

**Issue by jpignata** [aws-amplify/docs#1372]
**Describe the bug**
The link to "Install and Configure" the Amplify CLI is broken. Reporting this as this page was held as the gold standard, and still has issues.

**To Reproduce**
1. Go to https://docs.amplify.aws/lib/auth/getting-started?platform=js
2. Click on "Install and configure"
3. Wait a moment, and notice nothing is happening
4. Click again because, idk, maybe you didn't click hard enough
5. Nope, still nothing, this must be a broken link. Dang.

![](https://149360821.v2.pressablecdn.com/wp-content/uploads/2013/11/Dead-Link.jpg)

**Expected behavior**
I'd expect this link to work and take me to the Amplify CLI install page.

**Comment by brene** [comment]
I can’t repro this. Which browser & device did you use?

**Comment by jpignata** [comment]
macOS Catalina, Chrome 80. [Here's a gif](https://share.getcloudapp.com/2NuBDyXb).

**Comment by brene** [comment]
Ah. Sorry. Didn’t follow the repro steps properly. Will fix in a bit!

**Comment by swaminator** [comment]
This works for me.. unless it was already fixed.

**Comment by jpignata** [comment]
> This works for me.. unless it was already fixed.

Yes, fixed in https://github.com/aws-amplify/docs/pull/1375. Closing.
