### ISSUE TITLE
Bug in App.js - AddTodo method - React Docs

### ISSUE THREAD

**Issue by johnnycheadshot** [aws-amplify/docs#1378]
**Describe the bug**
When a new todo is added through the sample app, the back-end responds with an error. The GraphQL schema does not require a description.

(I believe the description string needs to be set to null if there is the length of the input description is 0). [https://docs.amplify.aws/start/getting-started/data-model?integration=react#connect-frontend-to-api](url) -- lines 31 - 34.

**To Reproduce**
1. Go to the hosted sample app.
2. Click on name field.
3. Enter a name.
4. Submit the todo.

**Expected behavior**
The todo is submitted to the back-end, saved to DynamoDB, and persists in the todo list on refresh.

**Desktop**
 - OS: Ubuntu 18.04
 - Browser: Brave

Also, I'm not sure if this kind of thing warranted a PR or not, I'm brand new to this kind of thing.

**Comment by dabit3** [comment]
@johndmulhausen, please double check that you have a "description" field in your GraphQL schema. Also, I've pushed an update to the docs example to check to make sure both fields are populated before creating a mutation.
