### ISSUE TITLE
[v2-feedback] Incorrect Angular hosting guide

### ISSUE THREAD

**Issue by nhanna-suplari** [aws-amplify/docs#1379]
**Page**: [`https://docs.amplify.aws/start/getting-started/hosting?integration=angular`](https://docs.amplify.aws/start/getting-started/hosting?integration=angular)

**Feedback**: Should probably change the default for angular projects for the DistributionDir config. The default is incorrect for an angular 8 app, which namespaces the build output by the app name. Also, the error you get when you make that mistake (a 403 after publishing the app) is hard to trace back to the actual problem if you are using the amplify hosting solution, so would probably be good to add a warning during the publish step in the cli as well.

**Comment by jnathanh** [comment]
@sammartinez looks like this just got marked stale. It also looks like @nachbar 's fix would work.

**Comment by sammartinez** [comment]
resolving as the above PR has been merged
