### ISSUE TITLE
[v2-feedback] links don't work on next steps

### ISSUE THREAD

**Issue by nhanna-suplari** [aws-amplify/docs#1380]
**Page**: [`https://docs.amplify.aws/start/getting-started/nextsteps?integration=angular`](https://docs.amplify.aws/start/getting-started/nextsteps?integration=angular)

**Feedback**: your next step links are not actually linked to anything

**Comment by swaminator** [comment]
@nhanna-suplari fixed by #1381. Can you please check if it works for you? Thanks for filing a bug!

**Comment by nhanna-suplari** [comment]
it works now, thanks for the fast response @swaminator !
