### ISSUE TITLE
[v2-feedback]

### ISSUE THREAD

**Issue by nhanna-suplari** [aws-amplify/docs#1394]
**Page**: [`https://docs.amplify.aws/start/getting-started/data-model?integration=angular`](https://docs.amplify.aws/start/getting-started/data-model?integration=angular)

**Feedback**: I don't think `{% raw %}{{item.name}}{% endraw %}` is valid in an angular template, I took the raw/endraw out and it worked.

**Comment by brene** [comment]
Fixed.
