### ISSUE TITLE
no link to "Getting Started" for library Analytics in doc v2

### ISSUE THREAD

**Issue by JohannesKonings** [aws-amplify/docs#1404]
**Describe the bug**
In the "Getting Started" section of the library analytics is no link.

**To Reproduce**
1. Go to https://docs.amplify.aws/lib/analytics/getting-started?platform=js
2. Click on "Install and configure the Amplify CLI"

**Expected behavior**
A link to https://docs.amplify.aws/cli/start/install

**Screenshots**
![image](https://user-images.githubusercontent.com/14806640/78158902-21aef880-7442-11ea-98cd-9318769f73f7.png)

**Desktop (please complete the following information):**
 - Browser [ chrome]
 - Version [ev2]

**Additional context**
I assume in this file https://raw.githubusercontent.com/aws-amplify/docs/v2-preview/docs/lib/analytics/getting-started.md this schould be change from:
> Prerequisite:</b> [Install and configure the Amplify CLI](..)
to
> Prerequisite:</b> [Install and configure the Amplify CLI](~/cli/start/install.md)

**Comment by brene** [comment]
We fixed this issue.
