### ISSUE TITLE
[v2-feedback]

### ISSUE THREAD

**Issue by alteredorange** [aws-amplify/docs#1413]
**Page**: [`https://docs.amplify.aws/start/getting-started/data-model?integration=js`](https://docs.amplify.aws/start/getting-started/data-model?integration=js)

**Feedback**: We're building a todo app, but then top paragraph talks about photos: "Given these requirements, we’ll need to be able to display a list of photos and upload photos, meaning there will definitely be a Photo entity in the app. " Possibly mixing two tutorials.  Also, right below that you show the two same code snippets. I believe the second one is supposed to include the "@model", but it's missing:
type Todo {
  id: ID!
  name: String!
  description: String!
}

**Comment by brene** [comment]
@dabit3 - can you take a look at this?

**Comment by brene** [comment]
Closing this as it was addressed.
