### ISSUE TITLE
[v2-feedback]

### ISSUE THREAD

**Issue by filipemcg** [aws-amplify/docs#1435]
**Page**: [`https://docs.amplify.aws/lib/auth/getting-started?platform=js`](https://docs.amplify.aws/lib/auth/getting-started?platform=js)

**Feedback**: The new version looks much better but still not on point.
Please get rid of the code boxes "grayed shadows".
Aim for a sober look.
But yes looks better. Thank you team!

**Comment by brene** [comment]
Addressed in #1492
