### ISSUE TITLE
[v2-feedback] DataStore Getting Started "amplify-meta.json" missing

### ISSUE THREAD

**Issue by kay-is** [aws-amplify/docs#1438]
**Page**: [`https://docs.amplify.aws/lib/datastore/getting-started?platform=js`](https://docs.amplify.aws/lib/datastore/getting-started?platform=js)

**Feedback**: 

I ran the example:

    npx create-react-app amplify-datastore --use-npm
    cd amplify-datastore
    npx amplify-app@latest

but after I ran `amplify status` I got an error:

    ENOENT: no such file or directory, open '/home/ec2-user/environment/amplify-datastore/amplify/backend/amplify-meta.json'

**Comment by sammartinez** [comment]
@kay-is Did you do the [pre-reqs](https://docs.amplify.aws/cli/start/install) for DataStore? Thanks ahead of time
