### ISSUE TITLE
GraphQL Issue for Vanilla JS Tutorial

### ISSUE THREAD

**Issue by jjbuck** [aws-amplify/docs#1446]
**Describe the bug**
I'm working through the vanilla JS tutorial as described in https://aws-amplify.github.io/docs/js/start?ref=amplify-js-btn&platform=purejs. The issue is that when I get to the end of Step 5 and attempt to exercise the sample app, it doesn't seem to work as expected.

When I go to the URL assigned to my app and click the "Add Data" button, I see the following in my browser's console.

```
[Error] TypeError: Must provide Source. Received: undefined
	parse (parser.mjs:40)
	(anonymous function) (API.js:477:85)
	Eval Code (app.js:52)
	eval
	./src/app.js (main.bundle.js:4632)
	__webpack_require__ (main.bundle.js:726)
	(anonymous function) (main.bundle.js:793)
	Global Code (main.bundle.js:794)
[Error] Unhandled Promise Rejection: TypeError: Must provide Source. Received: undefined
	parse (parser.mjs:40)
	(anonymous function) (API.js:477:85)
	(anonymous function) (app.js:38)
	asyncFunctionResume
	Eval Code (app.js:45)
	eval
	./src/app.js (main.bundle.js:4632)
	__webpack_require__ (main.bundle.js:726)
	(anonymous function) (main.bundle.js:793)
	Global Code (main.bundle.js:794)
```

What's more, the auto-created DDB table is empty. Now what's also interesting is that when I look at my terminal after typing `amplify publish`, I see some potentially relevant warnings.
```
WARNING in ./src/app.js 11:44-54
"export 'createTodo' was not found in './graphql/mutations'

WARNING in ./src/app.js 31:31-40
"export 'listTodos' was not found in './graphql/queries'

WARNING in ./src/app.js 45:29-41
"export 'onCreateTodo' was not found in './graphql/subscriptions'
```

In the process of Googling these warnings, I came to suspect that it might have to do with the GraphQL auto-generation. I was never actually prompted to auto-generate code while creating the app, so I ran `amplify codegen add && amplify codegen` and accepted all the defaults.

Now after republishing the app, it appears to be somewhat more functional - but still not perfect. When I click the "Add Data" button, it correctly shows the "Mutation Results" and the "Subscription Results," but it doesn't show anything under "Query Results" (see screenshot).

**To Reproduce**
Follow the tutorial in https://aws-amplify.github.io/docs/js/start?ref=amplify-js-btn&platform=purejs. Upon completing Step 5, click the "Add Data" button in the browser.

**Expected behavior**
Clicking the "Add Data" button should show a "Use AppSync - Realtime and Offline" under "Mutation Results," "Query Results," and "Subscription Results"

**Screenshots**
https://imgur.com/a/N7y5i8f

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.1 (19B88)
 - Browser: Safari 13.0.3 (15608.3.10.1.4)
 - Amplify CLI version: 4.17.2

**Additional context**

**Comment by brene** [comment]
@dabit3 - can you look into this?

**Comment by dabit3** [comment]
Thanks @brene, having a look.

**Comment by dabit3** [comment]
@jjbuck when you say "step 5", are you saying that this happens after you deploy to the hosting service?

Did you also get the error when running the app locally on localhost?

**Comment by dabit3** [comment]
@jjbuck can you confirm that your code looks something like this:

```js
import API, { graphqlOperation } from '@aws-amplify/api'
import PubSub from '@aws-amplify/pubsub';
import { createTodo } from './graphql/mutations'
import { listTodos } from './graphql/queries'
import { onCreateTodo } from './graphql/subscriptions'

import awsconfig from './aws-exports';
API.configure(awsconfig);
PubSub.configure(awsconfig);

async function createNewTodo() {
  const todo = { name: "Use AppSync" , description: "Realtime and Offline"}
  return await API.graphql(graphqlOperation(createTodo, { input: todo }))
}

const MutationButton = document.getElementById('MutationEventButton');
const MutationResult = document.getElementById('MutationResult');
const QueryResult = document.getElementById('QueryResult');
const SubscriptionResult = document.getElementById('SubscriptionResult');

API.graphql(graphqlOperation(onCreateTodo)).subscribe({
  next: (evt) =>{
    SubscriptionResult.innerHTML = `SUBSCRIPTION RESULTS`
    const todo = evt.value.data.onCreateTodo;
    SubscriptionResult.innerHTML += `<p>${todo.name} - ${todo.description}</p>`
  }
});

MutationButton.addEventListener('click', (evt) => {
  MutationResult.innerHTML = `MUTATION RESULTS UPDATED:`;
  createNewTodo().then( (evt) => {
    MutationResult.innerHTML += `<p>${evt.data.createTodo.name} - ${evt.data.createTodo.description}</p>`
  })
});

async function getData() {
  QueryResult.innerHTML = `QUERY RESULTS`;
  API.graphql(graphqlOperation(listTodos)).then((evt) => {
    evt.data.listTodos.items.map((todo, i) => 
    QueryResult.innerHTML += `<p>${todo.name} - ${todo.description}</p>`
    );
  })
}

getData();
```

**Comment by jjbuck** [comment]
Appreciate your fast response @dabit3. Let's just chalk this one up to user error 😅. The docs appear to have been updated slightly in the last couple of weeks. Whatever the case, the critical piece of this that I was missing before (where the CLI prompts "Do you want to generate code for your newly created GraphQL API") seems pretty clear now. I'll just go ahead and close this one out.
