### ISSUE TITLE
incorrect function call in getting started - vue step 4

### ISSUE THREAD

**Issue by justin8** [aws-amplify/docs#1450]
**Describe the bug**
Under step 4 of the vue getting started docs (https://aws-amplify.github.io/docs/js/start?platform=vue ) you have `Update your main.js file to configure the library with Amplify.configure() like so:` with code that calls out to `API.configure(awsconfig);`.

One of those is incorrect, since there is no call to `Amplify.configure()` in the code; I'm presuming it is referring to the API.configure call?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by swaminator** [comment]
This seems resolved: https://docs.amplify.aws/start/getting-started/setup/q/integration/vue#set-up-frontend
