### ISSUE TITLE
Getting started suggests to use "latest" but latest tag is much newer than the doc

### ISSUE THREAD

**Issue by helloPiers** [aws-amplify/docs#1451]
On page https://github.com/aws-amplify/docs/blob/master/js/start.md the suggestion package.json includes:
```
  "dependencies": {
    "@aws-amplify/api": "latest",
    "@aws-amplify/pubsub": "latest"
  },
```
Well, **today**, `latest` gets you 
```
        "@aws-amplify/api": {
            "version": "3.1.4"
```
and
```
        "@aws-amplify/pubsub": {
            "version": "3.0.5",
```

But are the these the versions that the document was written with in mind? Will it always be?

It would seem good practice to update the document to pin at least the major versions that the walk-though was last tested against, to prevent future mismatches.

**Comment by sammartinez** [comment]
@helloPiers This is correct that we are suggesting to use the latest published packages for getting started with Amplify. Please let us know if you are experiencing any issues with this. Thanks !

**Comment by helloPiers** [comment]
So.. maybe you can help with my confusion. It looks to me from reverse engineering the way publishes to npm are done that release branch = latest tag. And looking in the release branch it looks like, for example, `latest` for @aws-amplify/api went from version 2.2.1 to version 3.1.0 only 7 days ago or so. 

I see warnings on the main front README about 3.x.x.x having breaking changes.

I guess I'm thinking if the getting started guide recommend version as "^v2" or whatever is the notation, then, it would need, rightly, to be a deliberate act to change that getting started guide to "^v3", made by someone who knows the changes from 2.2.1 to 3.1.0 don't in fact have any material changes that affect the getting started. Ideally someone who runs through the guide and checks for any issues. 

But perhaps I'm reading too much into what looks like a big semver bump? Maybe v2 to v3 is not in fact a breaking change here. But what about v4 that nobody has conceived of yet (for example)? 

I guess my thinking is it creates an unnecessary hostage to fortune to just blindly track latest versions *at the semver major level*, in any context. 

Thanks for your time!

**Comment by mauerbac** [comment]
We've updated to 3.0.0 now so this should no longer be an issue.
