### ISSUE TITLE
[v2-feedback]

### ISSUE THREAD

**Issue by cmbaykal** [aws-amplify/docs#1493]
**Page**: [`https://docs.amplify.aws/sdk/pubsub/working-api?platform=android`](https://docs.amplify.aws/sdk/pubsub/working-api?platform=android)

**Feedback**: I'am using android sdk. When I want to make a custom authorization with mqtt it says you are "Already connected". And I can see the connection in the logs but after 1 second it kicks me out.

**Comment by jpignata** [comment]
We'll track this in https://github.com/aws-amplify/aws-sdk-android/issues/1550.
