### ISSUE TITLE
[v2-feedback] Custom Configuration for REST Api

### ISSUE THREAD

**Issue by ammarkarachi** [aws-amplify/docs#1504]
**Page**: [`https://docs.amplify.aws/cli/restapi`](https://docs.amplify.aws/cli/restapi)

**Feedback**: 
Do we still need the custom configuration for REST Api?
https://aws-amplify.github.io/docs/js/api#manual-setup

**Comment by ammarkarachi** [comment]
I guess this would show up in the Libraries section

**Comment by brene** [comment]
this is part of the library section anyway: https://docs.amplify.aws/lib/restapi/getting-started?platform=js#import-existing-rest-api
