### ISSUE TITLE
[v2-feedback] initialize new project wording

### ISSUE THREAD

**Issue by edwardfoyle** [aws-amplify/docs#1506]
**Page**: [`https://docs.amplify.aws/cli/start`](https://docs.amplify.aws/cli/start)

**Feedback**: Mostly just preference but I would change the wording of [this section](https://docs.amplify.aws/cli/start#initialize-new-project) to:

To initialize a new Amplify project, run the following command from the root directory of your ~~frontend app~~ project.

**Comment by brene** [comment]
I think the wording is fine and fairly consistent. If you feel passionate about it, we can reopen this.
