### ISSUE TITLE
[v2-feedback]

### ISSUE THREAD

**Issue by akshbhu** [aws-amplify/docs#1507]
**Page**: [`https://docs.amplify.aws/cli/usage/files`](https://docs.amplify.aws/cli/usage/files)
Folder structure : https://docs.amplify.aws/cli/usage/files

**Feedback**: 

Proper representation of folder structure:
```
amplify 
   - .config
   - #current-cloud-backend
   - backend
```

**Comment by brene** [comment]
Addressed in #1529
