### ISSUE TITLE
[v2-feedback] Clone sample amplify project links to old docs

### ISSUE THREAD

**Issue by edwardfoyle** [aws-amplify/docs#1509]
**Page**: [`https://docs.amplify.aws/cli/start`](https://docs.amplify.aws/cli/start)

**Feedback**: The "click here for more details" in [this section](https://docs.amplify.aws/cli/start#clone-sample-amplify-project) links to the old docs. Not sure if this is intentional or not

**Comment by brene** [comment]
#1531
