### ISSUE TITLE
[v2-feedback]

### ISSUE THREAD

**Issue by akshbhu** [aws-amplify/docs#1519]
**Page**: [`https://docs.amplify.aws/cli/usage/plugin`](https://docs.amplify.aws/cli/usage/plugin)
https://docs.amplify.aws/cli/usage/plugin#plugin-types
**Feedback**: 
Under provider plugin section
**actual**  : access credentials, api invoke and wait logic, and response data parsing
**expected** : access credentials, api invoke , wait logic and response data parsing

**Comment by brene** [comment]
#1533
