### ISSUE TITLE
[v2-feedback] setup function sentence structure

### ISSUE THREAD

**Issue by edwardfoyle** [aws-amplify/docs#1520]
**Page**: [`https://docs.amplify.aws/cli/function`](https://docs.amplify.aws/cli/function)

**Feedback**: move comma in text in https://docs.amplify.aws/cli/function#set-up-a-function

You can add a Lambda function to your project which you can use alongside a REST API, or as a datasource ~~, as a part of~~ in your GraphQL API using the @function directive.

Also would be nice if @function linked to https://docs.amplify.aws/cli/graphql-transformer/directives#function

**Comment by brene** [comment]
#1535
