### ISSUE TITLE
UI Components Home page - no text/intro ? [v2-feedback]

### ISSUE THREAD

**Issue by bolzon2000** [aws-amplify/docs#1522]
**Page**: [`https://docs.amplify.aws/ui?framework=react`](https://docs.amplify.aws/ui?framework=react)

**Feedback**: 
Seems st
<img width="1215" alt="Screen Shot 2020-04-09 at 4 20 21 PM" src="https://user-images.githubusercontent.com/36417463/78948719-2c8b0e00-7a7e-11ea-9597-059a800000a2.png">
range that the UI components Nav bar leads to a screen filled with large framework buttons without any explanatory text.

**Comment by jordanranz** [comment]
Hey @bolzon2000, the introduction should appear after you have selected a framework but maybe this page can explain a bit about what the UI Components are. We can look into adding some information here, thanks for the feedback!

Also, https://docs.amplify.aws/ui?framework=react should actually bring you to an introduction page, is that not the case?

**Comment by mauerbac** [comment]
This has been updated -> https://docs.amplify.aws/ui/q/framework/react. Thanks again for pointing this out.
