### ISSUE TITLE
toggling framework does not update the command [v2-feedback]

### ISSUE THREAD

**Issue by bolzon2000** [aws-amplify/docs#1525]
**Page**: [`https://docs.amplify.aws/ui?framework=react`](https://docs.amplify.aws/ui?framework=react)

**Feedback**: 
When I toggle the framework within UI components the installation instructions don't update. In this example I selected ionic but get angular install instructions.
<img width="697" alt="Screen Shot 2020-04-09 at 4 25 06 PM" src="https://user-images.githubusercontent.com/36417463/78949010-15005500-7a7f-11ea-8e68-e6f3fa0fe88f.png">

**Comment by brene** [comment]
It's expected. Ionic can use angular components
