### ISSUE TITLE
[v2-feedback] Wrong import for react auth integration

### ISSUE THREAD

**Issue by jbernalvallejo** [aws-amplify/docs#1547]
**Page**: [`https://docs.amplify.aws/start/getting-started/auth?integration=react`](https://docs.amplify.aws/start/getting-started/auth?integration=react)

**Feedback**: 
Hi. In "Create login UI" section, `import` is wrong. I believe it should be `@aws-amplify/ui-react` instead of` aws-amplify-react`.

**Comment by swaminator** [comment]
Duplicate #1630
