### ISSUE TITLE
[v2-feedback]  UI - Angular - unclear description on how to remove fields

### ISSUE THREAD

**Issue by DeniseJames** [aws-amplify/docs#1559]
**Page**: [`https://docs.amplify.aws/ui/auth/authenticator?framework=angular`](https://docs.amplify.aws/ui/auth/authenticator?framework=angular)

**Feedback**: How do I remove the username and phone number fields?

![image](https://user-images.githubusercontent.com/17970321/79069159-a1826180-7c91-11ea-9c7e-1a6c2c4bb54b.png)

**Comment by brene** [comment]
@jordanranz

**Comment by jordanranz** [comment]
Hey @DeniseJames,

Thanks for posting your feedback and using Amplify! Trying to get to all your feedback in a timely manner :D

If you want to use the authenticator for "Sign in with Email" you can use the [usernameAlias prop](https://docs.amplify.aws/ui/auth/authenticator?framework=angular#prop-username-alias) and pass in `'email'`
like:
```
<amplify-authenticator usernameAlias="email"></amplify-authenticator>
```

However, if you want to also get rid of the phone field here, we just added support for custom form fields here: https://github.com/aws-amplify/amplify-js/commit/c8518396ccdb04c3bb780a48bec3ce1ba33d21d4

This feature is currently on `@aws-amplify/ui-angular@unstable` and not on the latest version.

Here is a bit of usage documentation:
https://github.com/aws-amplify/amplify-js/issues/5298#issuecomment-615491944

For your particular Angular use case it would be something like:
```
// app.component.html
<amplify-authenticator>
    <amplify-sign-up
      headerText="Custom form"
      [formFields]="formFields"
      slot="sign-up"
    ></amplify-sign-up>

   <div>My App</div>    
</amplify-authenticator>
```
```
// app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'Amplify Authenticator Angular Starter';
  formFields: Array<any>;

  constructor() {
    this.formFields = [
      {
        type: 'email',
        label: 'Custom Email Label',
        placeholder: 'custom email placeholder',
        required: true,
      },
      {
        type: 'password',
        label: 'Custom Password Label',
        placeholder: 'custom password placeholder',
        required: true,
      },
    ]
  }
}

```

Hope this helps

**Comment by ashika01** [comment]
@pechisworks : We have made some changes, so with the recent unstable from today should even Jordan's changes should work now.

**Comment by DeniseJames** [comment]
@jordanranz  Thank you so much for the code. I am not sure what I did but I get this message when I use in my browser

![image](https://user-images.githubusercontent.com/17970321/80289952-b0dcc280-8707-11ea-82aa-9e54904deed7.png)


Also, I attemped to add the username also, does this look accurate:

      {
        type: 'text',
        label: 'username',
        placeholder: 'username ',
        required: true,
      },

**Comment by DeniseJames** [comment]
I installed the unstable amplify UI and it works!  thanks @jordanranz

**Comment by brene** [comment]
@ashika01 - is this ready to be closed?

**Comment by jordanranz** [comment]
@DeniseJames All of this should be release on the latest version of the UI libraries now. Please feel free to open up a new issue if you experience any more problems. Thank you for providing great feedback for us.
