### ISSUE TITLE
`.identified` is not available on lists from GraphQL

### ISSUE THREAD

**Issue by mrtom** [aws-amplify/docs#1560]
**Describe the bug**
In [the docs](https://aws-amplify.github.io/docs/sdk/ios/api#considerations-for-swiftui) on APIs, you have the following:

"When using List and ForEach for SwiftUI the structure needs to conform to Identifiable. The code generated for Swift does not make the structure Identifable but as long as you have a unique id associated with the object then you can retroactively mark a field as unique. Here is some example code for ListTodosQuery()"

When I try and run this code I get the following:
`Value of type '[ListMessagesQuery.Data.ListMessage.Item]' has no member 'identified'`

**To Reproduce**
Run through the getting started docs for iOS and add to a SwiftUI project.
Added a GraphQL API with the schema below
Followed along with https://github.com/aws-samples/aws-amplify-swiftui-demo

```
 type Message @model {
   id: ID!
   body: String!
   replies: [Reply] @connection(keyName: "byMessage", fields: ["id"])
 }

 type Reply @model @key(name: "byMessage", fields: ["messageID"]) {
   id: ID!
   body: String!
   messageID: ID!
   message: Message @connection(fields: ["messageID"])
 }
```

**Expected behavior**
The code compiles

**Screenshots**
![Screenshot 2020-04-12 at 14 58 40](https://user-images.githubusercontent.com/174462/79070500-4327a400-7cce-11ea-903e-451db8477649.png)

**Desktop**
 - OS: MacOS 10.15.3
- Xcode: 11.4
- iOS: 13.4 (in Simulator)

**Additional Info**

Here's a gist of the generate API.swift file: https://gist.github.com/mrtom/54ec44e7e8f2d2f286b18c09822b51d2

**Comment by mrtom** [comment]
Note: I 'fixed' this by writing an extension on my modal object:

```
extension ListMessagesQuery.Data.ListMessage.Item : Identifiable {
  var getId: String {
    return id
  }
}
```

And was then able to remove the `identified(by:)` call completely:

```
List(messageStore.listMessages) { message in
    VStack(alignment: .leading) {
      Text("\(message.body)")
    }
}
```

**Comment by brene** [comment]
@drochetti - can you look into this?
