### ISSUE TITLE
[v2-feedback] Require example for event handler

### ISSUE THREAD

**Issue by F-JJTH** [aws-amplify/docs#1571]
**Page**: [`https://docs.amplify.aws/ui/auth/authenticator?framework=angular

Hi, 

First, I really like the new documentation ! And specifically the large number of example for each framework (I'm using Angular, so Angular example are very welcome :) )

Can you give an example how to use event on component ?
For instance, I try to use `handleSubmit` because I want to set custom properties during signup process but I can't get my component controller function called (`onSignupSubmit($event)`).

`<amplify-sign-up (handleSubmit)="onSignupSubmit($event)"></amplify-sign-up>`

What am I missing ?

**Comment by sammartinez** [comment]
@F-JJTH Is this in regards to the Legacy Angular code? Please let us know

**Comment by F-JJTH** [comment]
@sammartinez my comment is not about Legacy Angular code.

I want to call a function in my Angular controller when a user submit the «sign-up» form. 
To realize this I read in the documentation there is a property named `handleSubmit` of type `(event: Event) => void`.
So when I read this part of the documentation, my understanding is that `handleSubmit` is the good solution for my use case.

Then I wrote this code (see below) but «form has been submited !» never happen in my Console, so I guess the function `onSignupSubmit` is never called, while I expected it would be called.

![Selection_086](https://user-images.githubusercontent.com/6074450/79308966-cb3dc180-7ef9-11ea-8bc7-af0a70b11ea7.jpg)

Because the behaviour is not what I expected I'm asking for some code sample in the new documentation in order to understand how to use `handleSubmit`

**Comment by sammartinez** [comment]
We have done updates to the documentation called out about to improve the events around Auth. Resolving as there is no further action for us to take.

**Comment by juancpgo** [comment]
How do I use the `handleSubmit` property when using web components?
