### ISSUE TITLE
Two contradictory sections about M-M connections in Directives 

### ISSUE THREAD

**Issue by saevarb** [aws-amplify/docs#1572]
**Describe the bug**
There are two kind of contradictory sections on how to create M-M connections under Directives.

**Expected behavior**
I expect there to be a single section that is not contradictory and explains the benefits and downsides of either approach.

**Screenshots**
![image](https://user-images.githubusercontent.com/441474/79264922-9b5cd280-7e95-11ea-90bb-b2962aca7d2e.png)

**Additional context**
I was trying to implement M-M connections to use with DataStore. The first section uses keys and connections with `keyName`, which is [currently not possible with DataStore](https://github.com/aws-amplify/amplify-cli/issues/3909).

**Comment by brene** [comment]
@saevarb - this was address in #1576

**Comment by brene** [comment]
Thanks for raising this!
