### ISSUE TITLE
[v2-feedback] Vue Getting Started guide is not accurate

### ISSUE THREAD

**Issue by D1g1talW00d** [aws-amplify/docs#1582]
**Page**: [`https://docs.amplify.aws/start/getting-started/data-model?integration=vue`](https://docs.amplify.aws/start/getting-started/data-model?integration=vue)

**Feedback**: 
When following the Vue-flavour tutorial, the section 'Connect frontend to API' contains code from the general JavaScript tutorial, rather than the Vue specific tutorial (in the old version it is Vue-specific here: https://aws-amplify.github.io/docs/js/start?platform=vue)

**Comment by brene** [comment]
@dabit3 - can you look into this?

**Comment by dabit3** [comment]
Hey @brene , will be looking into this today.

**Comment by dabit3** [comment]
Thanks @D1g1talW00d , this has now been fixed and we've improved the Vue getting started to also include authentication. We appreciate the issue!

**Comment by dabit3** [comment]
Thanks @D1g1talW00d , this has now been fixed and we've improved the Vue getting started to also include authentication. We appreciate the issue!
