### ISSUE TITLE
[amazon-cognito-identity-js] completeNewPasswordChallenge with SR

### ISSUE THREAD

**Issue by lebnic** [aws-amplify/docs#1587]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **
According to your doc (ref: https://www.npmjs.com/package/amazon-cognito-identity-js), it is said that "The password features use the Secure Remote Password (SRP) protocol to avoid sending cleartext passwords over the wire." , which is awesome IMO. I've tested it for "standard login" (ie: authenticateUser) and it works fine: There is no password to be found in the "network calls" made to cognito within my browser.

However, I was not able to respond to the "NEW_PASSWORD_REQUIRED" with SRP using your code...  (ie: password is in clear text in the payload...). Could it be that this particular use-case is not covered by your doc, or perhaps it is not supported yet by this project ?

Indeed, according to your documentation (Use case 23. Authenticate a user and set new password for a user that was created using AdminCreateUser API.), the following command shall be used to respond to the "NEW_PASSWORD_REQUIRED" challenge returned by `initiate-auth`:

```
cognitoUser.completeNewPasswordChallenge(newPassword, sessionUserAttributes);
```

However, the above command "sends the password in the payload" , and thus (in my understanding) does not properly implement SRP...

**Here's my request:** Could you update the documentation to show us how to respond to the "NEW_PASSWORD_REQUIRED" challenge using SRP ?

---------------
note that it might be possible to "update the verifier" without sending the new password:
![image](https://user-images.githubusercontent.com/6682795/78792696-78a35900-797f-11ea-8b55-448213e2fa4a.png)
ref: https://github.com/simbo1905/thinbus-srp-npm

**Comment by mauerbac** [comment]
Hi @lebnic - sorry for the delay. This doc might help as it explains this a bit -> https://docs.amplify.aws/lib/auth/switch-auth/q/platform/js. It's not clear that signUp or setNewPassword send the password through the wire. I will close this and check with the Cognito team if they have someone working to explain this. Thank you!
