### ISSUE TITLE
[v2-feedback] Predictions API identify file source example

### ISSUE THREAD

**Issue by kay-is** [aws-amplify/docs#1597]
**Page**: [`https://docs.amplify.aws/lib/predictions/identify-text?platform=js`](https://docs.amplify.aws/lib/predictions/identify-text?platform=js)

**Feedback**: 

The examples are a bit confusing here.

The first example uses this:

```javascript
Predictions.identify({
    text: {
        source: file
    }
})
```

And later, when talking about plain text it uses this:

```javascript
Predictions.identify({
    text: {
        source: {
            file
        },
        format: "PLAIN", 
    }
})
```

I tried for over an hour to find the right data-type for `source`, while I had a blob all along that just had to be nested deeper into a `{ file }`

**Comment by brene** [comment]
Fixed in the PR above.
