### ISSUE TITLE
[v2-feedback] Document @searchable directive not compatible with DataStore with conflict resolution enabled

### ISSUE THREAD

**Issue by ammarkarachi** [aws-amplify/docs#1602]
**Page**: [`https://docs.amplify.aws/cli/graphql-transformer/directives#generates-4]
The @searchable directive is not compatible with DataSore with conflict resolution enabled

https://github.com/aws-amplify/amplify-cli/issues/3796#issuecomment-615514817

**Comment by brene** [comment]
completed in #1611
