### ISSUE TITLE
How to setup a production enviroment and a development enviroment [v2-feedback]

### ISSUE THREAD

**Issue by waldothedeveloper** [aws-amplify/docs#1610]
**Page**: [`https://docs.amplify.aws/lib/restapi/fetch?platform=js`](https://docs.amplify.aws/lib/restapi/fetch?platform=js)

**Feedback**: 
When you visit the AWS Amplify on AWS and check the documentation eventually you can get to this: 

> "Your app now has two deployments available at https://master.appid.amplifyapp.com and https://dev.appid.amplifyapp.com. This may vary from team-to-team, but typically the master branch tracks release code and is your production branch. The develop branch is used as an integration branch to test new features. This way beta testers can test unreleased features on the develop branch deployment, without affecting any of the production end users on the master branch deployment.
 
That seems good, but in my modest opinion,  I would like to have at least a short section in the new docs where you can see this, and maybe have some short examples like the AWS docs have:
 [https://docs.aws.amazon.com/amplify/latest/userguide/multi-environments.html](URL) 
Can this be done on the CLI?  -I have no idea-. 

Everything else I've already read on the new docs is awesome! 
shout-out to the whole team!!

**Comment by brene** [comment]
Hi @waldothedeveloper - I'm not sure I fully understand this issue. I was wondering if you've seen this section on the new docs: https://docs.amplify.aws/cli/teams/overview LMK if that addresses your concern.

**Comment by waldothedeveloper** [comment]
I definitely miss that section, many thanks
