### ISSUE TITLE
Sooo slow and buggy[feedback]

### ISSUE THREAD

**Issue by domezi** [aws-amplify/docs#1629]
**Page**: [`https://docs.amplify.aws/start/getting-started/data-model/q/integration/vue`](https://docs.amplify.aws/start/getting-started/data-model/q/integration/vue)

**Feedback**: 
Am I the only one experiencing lags and pageloads of up to 5-10 seconds? When I click on links the first display wrong content and then they change after a few seconds to the correct page... But sooo sloooow everything!
Firefox 75, Linux Mint, 32GB RAM. Without any plugins enabled.

**Comment by pedrobergamini** [comment]
Same here. Some times I have to close the browser and retry 2-3 times to access the docs

**Comment by swaminator** [comment]
@domezi @pedrobergamini that shouldn't be the case. Where are you accessing from?

**Comment by brene** [comment]
@domezi @pedrobergamini - where are you based?

**Comment by domezi** [comment]
Germany, Dresden

**Comment by pedrobergamini** [comment]
Brazil

**Comment by swaminator** [comment]
@domezi can we get on a call with you to do a screenshare to show what's happening? We aren't able to repro it here.

**Comment by pedrobergamini** [comment]
Sure! You can contact me at pedrohgbergamini@gmail.com

**Comment by swaminator** [comment]
@pedrobergamini sent you an email.

**Comment by jordanranz** [comment]
Hey @pedrobergamini @domezi, 
Could you try clearing cache and local storage in the browser. 

Also is it possible to share a screenshot of the "When I click on links the first display wrong content and then they change after a few seconds to the correct page" experience (wrong content for the route active)

**Comment by brene** [comment]
@pedrobergamini @domezi - we've issued a fix for the "old content" that you'll see when you first hit the page. We are still investigating the load time issues in parallel.

**Comment by domezi** [comment]
> @domezi or @pedrobergamini can we get on a call with you to do a screenshare to show what's happening? We aren't able to repro it here.

You can reach me at dominik.ziegenhagel@gmail.com

**Comment by brene** [comment]
hi Dominik! we've identified the latency issue and are working on a fix. I'll update this thread as we roll out.

**Comment by juancpgo** [comment]
Same here. Every page within https://docs.amplify.aws is painfully slow to respond.

(accessing from a Mac, in Brazil)
