### ISSUE TITLE
import should be @aws-amplify/ui-react

### ISSUE THREAD

**Issue by fidoogle** [aws-amplify/docs#1630]
**Page**: [`https://docs.amplify.aws/start/getting-started/auth/q/integration/react`](https://docs.amplify.aws/start/getting-started/auth/q/integration/react)

**Feedback**: The import should be '@aws-amplify/ui-react' not 'aws-amplify-react'

**Comment by brene** [comment]
fixed!

**Comment by brene** [comment]
Thanks for raising this!
