### ISSUE TITLE
[feedback]

### ISSUE THREAD

**Issue by iqre8** [aws-amplify/docs#1635]
**Page**: [`https://docs.amplify.aws/start/getting-started/setup/q/integration/vue`](https://docs.amplify.aws/start/getting-started/setup/q/integration/vue)

**Feedback**: 
Would appreciate the policy required for the AWS profile/accessKeyId

**Comment by swaminator** [comment]
@iqre8 follow the instructions here: https://docs.amplify.aws/start/getting-started/installation/q/integration/vue#install-and-configure-the-amplify-cli
