### ISSUE TITLE
Documentation references both "Amplify/Tools" and "amplify-tools"

### ISSUE THREAD

**Issue by wooj2** [aws-amplify/docs#1643]
**Describe the bug**
In our getting started guide, we reference "amplify-tools"
https://docs.amplify.aws/lib/getting-started/setup/q/platform/ios#prerequisites
In the datastore guide, we reference: "Amplify/Tools"
https://docs.amplify.aws/lib/datastore/getting-started/q/platform/ios#using-cocoapods

We need to choose one (or none) and update the documentation accordingly

**Comment by swaminator** [comment]
Closing as these docs have changed for iOS and Android Libs.
