### ISSUE TITLE
[Feedback]  Algolia search shows three responses for the same thing

### ISSUE THREAD

**Issue by kimfucious** [aws-amplify/docs#1644]
**Page**: [`/lib/auth/switch-auth/q/platform/js`](https://docs.amplify.aws/lib/auth/switch-auth/q/platform/js)

**Feedback**:

Hi there,

The new docs are looking good!

One nit is that the Algolia search provides three responses for something like "custom auth".

It is apparent that the responses are for Android, iOS, and JavaScript after clicking on them, but these are not labelled in the search drop down.

This makes it kind of a guessing game with each search.

**Comment by jordanranz** [comment]
Hey @kimfucious, thank you for submitting feedback!

We are currently in the process of improving how Algolia indexes our content. This should increase the accuracy of our search results. Will post an update when this has been executed. Thanks again for the comments.

**Comment by kimfucious** [comment]
Sounds good, @jordanranz 

The new docs, overall, are a big improvement!

**Comment by swaminator** [comment]
@kimfucious we fixed this in our latest release. Let us know if you have any more feedback.
