### ISSUE TITLE
[Feedback] out-of-date `queries` reference in `@auth` docs

### ISSUE THREAD

**Issue by cyrfer** [aws-amplify/docs#1645]
**Page**: [`/cli/graphql-transformer/overview`](https://docs.amplify.aws/cli/graphql-transformer/overview)

**Feedback**:

still refering to `queries` in `@auth` docs.
https://docs.amplify.aws/cli/graphql-transformer/directives#owner-authorization

```graphql
type Draft @model
  @auth(rules: [

    # Defaults to use the "owner" field.
    { allow: owner },

    # Authorize the update mutation and both queries. Use `queries: null` to disable auth for queries.
    { allow: owner, ownerField: "editors", operations: [update, read] }
  ]) {
  id: ID!
  title: String!
  content: String
  owner: String
  editors: [String]
}
```

**Comment by mauerbac** [comment]
hi @cyrfer - just took a look with the team. Can you provide more information in a follow-up ticket if this still requires an update? Will close out.

**Comment by cyrfer** [comment]
@mauerbac The example I cited seems fixed now.

If I was confusing, here is a link that shows exactly that `queries` is deprecated verbiage in `auth`.
https://docs.amplify.aws/cli/graphql-transformer/directives#definition-2

```graphql
  # The following arguments are deprecated. It is encouraged to use the 'operations' argument.
  queries: [ModelQuery]
  mutations: [ModelMutation]
```
