### ISSUE TITLE
[Feedback] Requires additional details on DataSourceName in Cloudformation template

### ISSUE THREAD

**Issue by cyrfer** [aws-amplify/docs#1647]
**Page**: [`/cli/graphql-transformer/resolvers`](https://docs.amplify.aws/cli/graphql-transformer/resolvers

Really from:
https://docs.amplify.aws/cli/graphql-transformer/resolvers#add-a-custom-resolver-that-targets-a-dynamodb-table-from-model

Where does this name come from?
`"DataSourceName": "CommentTable",`

How should we know the right value of the DataSourceName in the Cloudformation template?

**Comment by mauerbac** [comment]
Thanks @cyrfer !! We just created a PR for this.
