### ISSUE TITLE
Explain how to hide Sign Up in Vue.js amplify-authenticator

### ISSUE THREAD

**Issue by mrichman** [aws-amplify/docs#1653]
**Page**: [`/ui/q/framework/vue`](https://docs.amplify.aws/ui/q/framework/vue)

**Feedback**:

There is no documentation on how to hide the signup link and text. This is the "No account? Create account" prompt.

**Comment by jordanranz** [comment]
This discussion will provide the current solution for this: https://github.com/aws-amplify/amplify-js/discussions/5593

I'll look to add documentation about this in the Docs site.

**Comment by scottpederick** [comment]
Just as a note for anyone else looking, you can pass 'hide-sign-up' as a boolean:

```
<amplify-authenticator :authConfig="authConfig">
    <amplify-sign-in slot="sign-in" hide-sign-up="true"></amplify-sign-in>
</amplify-authenticator>
```
