### ISSUE TITLE
[Feedback] Introduce examples for UI components

### ISSUE THREAD

**Issue by scottkelso** [aws-amplify/docs#1654]
**Page**: [`/ui/auth/authenticator/q/framework/vue`](https://docs.amplify.aws/ui/auth/authenticator/q/framework/vue)

**Feedback**:

Docs look great but I feel like there needs to be more relevant examples. I am finding it especially hard to add authentication functionality to my app using the UI Components - a solution which should be the easiest to implement. However the examples given don't include any use of the parameters listed so it is trial and error to figure out how they might be used.

For example, there are no examples of how you tell the component what fields it needs to use to setup a correct integration with AWS User Pool. There are a number of additional attributes Cognito accepts but am unsure how to implement using the UI Components.

Why is there a component for each of amplify-sign-out, amplify-sign-in , & amplify-sign-up, when each includes markup for all of them? This is not exampled or explained.

I am new to the amplify framework but I am finding it hard to use based on what is there currently. Hope this helps!

**Comment by brene** [comment]
@dabit3 - can you look into this? This is good feedback to improve upon. Thoughts?

**Comment by mauerbac** [comment]
Thanks @scottkelso . Also pinging @jordanranz for input

**Comment by mauerbac** [comment]
Just followed up with @jordanranz , @scottkelso . We will be releasing new demo apps in a GitHub repo shortly that will address this. Thanks for sharing your feedback as it's very helpful! :)
