### ISSUE TITLE
[Feedback] Documentation on Cognito for User App Pools

### ISSUE THREAD

**Issue by ammarkarachi** [aws-amplify/docs#1658]
**Page**: [`/cli/auth/groups`](https://docs.amplify.aws/cli/auth/groups)

**Feedback**:

https://github.com/aws-amplify/amplify-cli/issues/4100

Add documentation for Cognito User Pool App Clients: Adding Auth creates two Clients one for native and one for Web, The native Pool Client supports secret key required for native clients

**Comment by mauerbac** [comment]
Hi @ammarkarachi - I think it's best if we keep this documented on the JavaScript side here https://docs.amplify.aws/lib/auth/overview/q/platform/js#sign-up-and-sign-in

**Comment by jszyba** [comment]
Where exactly does this closed issue state "...Adding Auth creates two Clients one for native and one for Web, The native Pool Client supports secret key required for native clients..." The link provided does not explain this, nor does any other section of the docs attempt to explain why the extra resources are created when clearly not needed in most cases. Is this truly marked closed or is there another issue still open to address this?
