### ISSUE TITLE
Ui components docs are not sync with libraries

### ISSUE THREAD

**Issue by mehmetkemalbayer** [aws-amplify/docs#1662]
**Page**: [`/ui/q/framework/react`](https://docs.amplify.aws/ui/q/framework/react)

**Feedback**:

formFields does not work and sign in with aws button cannot be hidden.
ui components is not working as shown in the webpage.

**Comment by brene** [comment]
@jordanranz - can you look into this issue?

**Comment by jordanranz** [comment]
@mehmetkemalbayer,

What do you mean by: "formFields does not work"? Also which aws button are talking about?

**Comment by mehmetkemalbayer** [comment]
Hi,
formFields was my mistake, package was previous version so you can ignore that.
AWS is at the top and I couldn't find how to add Google/Facebook buttons.
Please find attached sceenshot.
Thanks.
<img width="453" alt="Screen Shot 2020-04-30 at 09 30 39" src="https://user-images.githubusercontent.com/7826969/80679490-a20a5d00-8ac5-11ea-9543-c5eb8dbf37ed.png">

**Comment by jordanranz** [comment]
We are in the process of porting over the README docs to the docs site. Let me know if this helps:
https://github.com/aws-amplify/amplify-js/tree/master/packages/amplify-ui-components#amplify-authenticator-federated

**Comment by mehmetkemalbayer** [comment]
Hi,
By using the link you provided I could add google and facebook button but I still can't remove "Sign in with AWS" button. 
Please find the code and the ss. 
Best.
```
import React from 'react';
import { AmplifyAuthenticator,  } from '@aws-amplify/ui-react';

const federated = {
  facebookAppId: "708449659898938",
  googleClientId: "835775604232-m4ukddj5hubvcssrft1rq9v2ghicu2f3.apps.googleusercontent.com",
  oauthConfig: {
    redirectSignIn: "http://localhost:1234/",
    redirectSignOut: "http://localhost:1234/",
  }

}
const App = () => (
  <AmplifyAuthenticator federated={federated} />
);
export default App;
```

<img width="438" alt="Screen Shot 2020-05-06 at 15 23 12" src="https://user-images.githubusercontent.com/7826969/81176324-af37b800-8fad-11ea-90ee-3c82292e8cd7.png">

**Comment by mehmetkemalbayer** [comment]
By the way I cant use formfields attribute with sign-up by using the link you provide me @jordanranz

**Comment by mauerbac** [comment]
Hey @mehmetkemalbayer - did the updated docs help? We also have a [Discord server](www.discord.gg/amplify) with a #ui-help channel. That might be easier for realtime help.

**Comment by lack-of-gravitas** [comment]
Why are these instructions still buried and still not clearly referenced in the Amplify Auth documentation (https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#recommended-usage) or when setting up the Amplify Admin UI (where they logically make sense) -- had to waste an hour searching for this.
