### ISSUE TITLE
Mobile access to url using fragment renders empty screen

### ISSUE THREAD

**Issue by gsans** [aws-amplify/docs#1664]
**Describe the bug**
When accessing the url below from a mobile device it renders empty. Reported originally by Austin @amcdnl.

https://docs.amplify.aws/cli/graphql-transformer/directives#searchable 

**To Reproduce**
Steps to reproduce:
1. Go to 'https://docs.amplify.aws/cli/graphql-transformer/directives#searchable' using a Mobile device
2. Screen looks empty but you can scroll quite deeply.

**Expected behavior**
Page content renders as expected.

**Screenshots**
![Screenshot_20200429_183556_com android chrome](https://user-images.githubusercontent.com/4660316/80629093-4222a080-8a4a-11ea-96d4-8c57ce458899.jpg)

**Smartphone (please complete the following information):**
 - Device: Huawei P20 Lite
 - OS: Android 9
 - Browser: Chrome 
 - Version 80.0.3987.119

**Comment by brene** [comment]
@jordanranz / @harrysolovay - can you validate this?

**Comment by harrysolovay** [comment]
Apologies––didn't see this till now. Checking it out.

**Comment by harrysolovay** [comment]
Odd, it's rendering fine for me on both a real iOS device and the iOS simulator. I don't have a physical Android device to test on. @gsans can we find a time to screen-share and debug together?

**Comment by gsans** [comment]
I don't think that's going to help. Without access to an Android device, my
first thought would be to install Android Studio and use a remote debugger
as you want to inspect this behaviour in Chrome Mobile during runtime.

**Comment by harrysolovay** [comment]
Fair enough. Will try to repro.

**Comment by harrysolovay** [comment]
@brene @gsans I'm unable to repro. This is loading correctly in my emulator ("Nexus 5X emulator API 29 x86"). I could not find a Huawei P20 Lite emulator. Any advice on how to repro would be greatly appreciated. Could this be related to [the latency issue](https://github.com/aws-amplify/docs/issues/1629)?

**Comment by gsans** [comment]
Here I'm attaching a recording. First accessing the docs successfully and then using the url with and without fragment.

**Comment by gsans** [comment]
I've asked @amcdnl who originally reported this issue and he is using an iPhone.

**Comment by swaminator** [comment]
@gsans are you still repro'ing this issue?

**Comment by gsans** [comment]
Yes. I can confirm is not working.

**Comment by mauerbac** [comment]
Works for me on iOS (latest). This might have resolved itself? 

![IMG-7182](https://user-images.githubusercontent.com/1507886/83886475-1a8fb980-a715-11ea-901a-599a5c0e2988.PNG)

**Comment by gsans** [comment]
Something is certainly at play on mobile as it's not usable as is.
Confirmed again by myself and the user who reported it to me.

My proposed solution at this point is that this section has too much
content on it and should be splitted in smaller bits.

**Comment by mauerbac** [comment]
I think i'm missing something - i'm able to scroll through and read the documentation pretty well. It also has the mobile friendly hamburger button in the lower right to navigate.  

Are you talking about mobile support or this section's content in general?

**Comment by gsans** [comment]
This is specially for the url reported.

If you check the video I sent over again. It does work fine for other
urls/sections. This is about this particular page.

**Comment by mauerbac** [comment]
@gsans - @harrysolovay and I weren't able to reproduce. Looks like it has been resolved. Please create a new issue if this happens again.
