### ISSUE TITLE
docs.amplify.aws content viewport is too constrained from 13" MacBook

### ISSUE THREAD

**Issue by jamesonwilliams** [aws-amplify/docs#1674]
**Describe the bug**
From a 13" MacBook, the main content of the docs site is too constrained, and it creates a usability issue.

The website includes a left nav-bar, and a right nav-bar, and a top nav-bar. The three bars  constrain the main content view considerably. The purpose of the docs site is vend content. However, I need to scroll around to actually engage with the content.

**To Reproduce**
1. Go to https://docs.amplify.aws/lib/auth/getting-started/q/platform/android#initialization
2. View any of the code snippets. Note that the content viewport displays a very small portion of them, since the left and right nav bars constrain the visible content considerably.

**Expected behavior**
I expect to see documentation content to be more focused in the window.

The nav bars don't just create too small of a space for the content, they also visually distract from the content.

One or more of the nav bars should disappear automatically, or possibly not even be part of the layout, for a screen of my size.

**Screenshots**
<img width="1143" alt="Screen Shot 2020-04-30 at 12 48 09 AM" src="https://user-images.githubusercontent.com/899569/80676744-0f45d000-8a7d-11ea-9b81-80bb6c74005e.png">

**Desktop (please complete the following information):**
 - OS:  Mac OS X Mojave 10.14.6
 - Browser: Google Chrome Version 81.0.4044.129 (Official Build) (64-bit)
 - User-Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36`
 - MacBook Pro, Retina, 13-inch, Early **2015**
 - Screen size: 13.3-inch (2560 x 1600)

**Comment by brene** [comment]
@jamesonwilliams - what scaling factor do you have? I'm on a 13" MBP and it shows significantly more screen real estate: 
![image](https://user-images.githubusercontent.com/4989523/80677518-e2d68780-8a6d-11ea-93bb-68a2cd6015c0.png)

**Comment by jamesonwilliams** [comment]
@brene - This is an Early 2015 model, the screen is 13.3-inch (2560 x 1600), and I have no special zoom / density modifications.

**Comment by swaminator** [comment]
@jamesonwilliams thanks for the feedback. Would it help if we had the ability to minimize the menu bars?

**Comment by jamesonwilliams** [comment]
@swaminator Yea, that could work! I think there are potentially _a number_ of different ways to deal with it:

1. Like you say, making the bars "collapsible";
    a. As a P1, having them _automatically_ animate-collapse when the mouse is in the content area;
2. Falling back to a different layout (mobile layout?) on screens that are smaller than your desktop-design target;
3. Fixing the navs to the document, instead of to the window. Then, allowing content to flow under/around the divs. The content would be bounded by body padding in the widest parts, and bounded between the two fixed bars, in the narrowest parts;
4. Making a "small screens" layout, that uses a single nav bar (like the old docs site, sigh.)

**Comment by jamesonwilliams** [comment]
In some instances, this means I can't actually read the content at all. This page has a video which doesn't expand. It's so constrained on my screen that the text isn't readable:

<img width="269" alt="Screen Shot 2020-05-26 at 7 10 00 PM" src="https://user-images.githubusercontent.com/899569/82958890-89864900-9f84-11ea-85eb-8c0b6ceb5cc8.png">

**Comment by brene** [comment]
@jamesonwilliams we've adjusted the breakpoints a bit more. Can you verify if that's better?

**Comment by brene** [comment]
we're also actively looking into a dismissable right hand nav to make even better use of the screen real estate. More to follow soon.

**Comment by mauerbac** [comment]
@brene , this looks a lot better when mimicking a 13inch screen. Will close out. Thanks
