### ISSUE TITLE
[Feedback]Note for @searchable support only for instances with version >=6.x

### ISSUE THREAD

**Issue by akshbhu** [aws-amplify/docs#1676]
**Page**: [`/cli/graphql-transformer/directives`](https://docs.amplify.aws/cli/graphql-transformer/directives)

**Feedback**:
We can have a Note in the searchable directive , something like
 "**Not supporting t2.micro in amplify-cli as it only works with version 1.5 and 2.3 and amplify-cli supports version >= 6.x**"
Min supported instanceType : "t2.small.elasticsearch"

**Comment by brene** [comment]
@akshbhu - can you submit a PR directly against master branch?
