### ISSUE TITLE
[missing-page] AppSync for Web

### ISSUE THREAD

**Issue by fanderzon** [aws-amplify/docs#1685]
**Page**: [`https://docs.amplify.aws/lib/graphqlapi/overview/q/platform/js`](https://docs.amplify.aws/lib/graphqlapi/overview/q/platform/js)

**Feedback**: 
This page is linked to from https://aws.amazon.com/appsync/resources/ as "AppSync for Web" but returns a 404

**Comment by brene** [comment]
Hi @fanderzon - thanks for raising this. We're looking into this now.

**Comment by swaminator** [comment]
Resolved
