### ISSUE TITLE
datastore.clear() not documented

### ISSUE THREAD

**Issue by rpostulart** [aws-amplify/docs#1691]
I am looking for more background information in the docs about how Datastore security is working. Are there any additional security measures on top of IndexedDB  is something encrypted and how does this work? For what kind of privacy related use case it can and can't work?

So my question is if there can be made more docs available about this ?

thx

**Comment by undefobj** [comment]
Hello @rpostulart there is no Encryption at the moment but we are investigating this as a feature request. Browser engines themselves don't support encryption, so for us to accomplish this a layer on top needs to be developed. For use cases where multiple users are on the same app and you're concerned of shared data we provide `DataStore.clear()` allowing you to control if you need to remove data for different scenarios.

**Comment by rpostulart** [comment]
Ok cool, I am looking forward for this and willing to test! 

I can't find much information about datastore.clear() is there somewhere some more info about this?

**Comment by undefobj** [comment]
Good catch we can provide more info on clear. @brene
