### ISSUE TITLE
Move Lambda Triggers to Functions

### ISSUE THREAD

**Issue by undefobj** [aws-amplify/docs#1692]
It’s non intuitive looking for the Lambda triggers (which I’ve had to do severall times) in the “Advanced workflows” section as my intuition is to look in the Function category.

I think we should move this stuff:
https://docs.amplify.aws/cli/usage/lambda-triggers

To here:
https://docs.amplify.aws/cli/function

Maybe as a separate section than the “Overview” one but under that nav

**Comment by mauerbac** [comment]
Spoke with @brene and will keep this outside of the category for now.
