### ISSUE TITLE
Rewrite the CLI workflows doc

### ISSUE THREAD

**Issue by JohnLockwood** [aws-amplify/docs#1699]
**Page**: [`/cli`](https://docs.amplify.aws/cli)

**Feedback**:

This is a good high-level marketing sort of overview, but what I was looking for was more on usage.  Maybe this is the fault of missing features.  Specifically it seems to me a cloudformation based CLI, especially one that advertises "Infrastructure as Code" as a high level bullet item, should have a way of exporting the Cloudformation-related goodies locally so I can modify them / commit them / etc.  The other problem here is that the cloudformation support seems to be category based? So if I were to configure this with Cloudformation, what categories exist? (doc issue)  And how do I set up my local tree CFN templates go in what category?  As a developer, how do I organize this in such a way that I can move beyond toy applications or demos?

Also, the CLI has no help?  "amplify pull help" or "amplify pull --help" tells me it pulls something.  What did it pull?  Why won't the tool tell me what it's doing?  Where's the --verbose switch? Etc. etc.

**Comment by JohnLockwood** [comment]
In retrospect this is obvious from poking around in the code a bit more.  But should it be documented?

**Comment by mauerbac** [comment]
HI @JohnLockwood - in the meantime, I was going to suggest looking at the CLI repo. It sounds like 1) you suggest a deep dive into how the CLI works under the hood? Maybe an architecture diagram with underlying services would help? 2) a feature request to add a help to all CLI commands ?

**Comment by mauerbac** [comment]
Action item -> update this doc: https://docs.amplify.aws/cli/start/workflows
