### ISSUE TITLE
Non-resolvable function in the Android Authentication tutorial

### ISSUE THREAD

**Issue by Trivoc** [aws-amplify/docs#170]
**Describe the bug**
I followed the guide for making an Android appUI  from "Getting started" to Authentication - the Drop-In UI describes a non-existing function signature: 

`AWSMobileClient.getInstance().showSignIn(this);`

This function call also requires a SignInUIOptions parameter.

**Comment by muellerfr** [comment]
Hello @Trivoc,

Issue has been fixed
https://github.com/aws-amplify/docs/pull/179#merged-event

Please review.

**Comment by minbi** [comment]
Hi @Trivoc ,

You will need to call `AWSMobileClient.getInstance().initialize(Context, Callback<UserStateDetails>)` before making calls to any of the other functions.

Also, for the `showSignIn` there is a requirement to pass in the options for now. (We will look into fixing it in a release.)

```
AWSMobileClient.getInstance().showSignIn(this, SignInUIOptions.builder()
        .logo(R.drawable.default_sign_in_logo) // This logo is available through the library
        .backgroundColor(R.color.colorPrimaryDark) // This color should be generic to Android, but you may choose another
        .canCancel(true)
        .build(), new Callback<UserStateDetails>() {
    @Override
    public void onResult(UserStateDetails userStateDetails) {
        Log.d(TAG, "onResult: showSignIn " + userStateDetails.getUserState());
    }

    @Override
    public void onError(Exception e) {
        Log.e(TAG, "onError: showSignIn", e);
    }
});
```
