### ISSUE TITLE
[Feedback] Outdated Vue UI component content

### ISSUE THREAD

**Issue by stravi** [aws-amplify/docs#1701]
**Page**: [`/ui/auth/authenticator/q/framework/vue`](https://docs.amplify.aws/ui/auth/authenticator/q/framework/vue)

**Feedback**:

The docs is outdated current API is here https://www.npmjs.com/package/aws-amplify-vue

**Comment by mauerbac** [comment]
hi @stravi - I just checked with the team and the doc you linked to is up to date as you are looking at our legacy vue library. Our newer version can be seen on the docs sites. Please open a new issue with further questions.
