### ISSUE TITLE
[Feedback] Add info about Translations

### ISSUE THREAD

**Issue by xavierraffin** [aws-amplify/docs#1707]
**Page**: [`/ui/auth/authenticator/q/framework/react`](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react)

**Feedback**:

It could be nice to show an example of how to override the translation of the internal labels:
https://github.com/aws-amplify/amplify-js/blob/master/packages/amplify-ui-components/src/common/Translations.ts

Used here 
https://github.com/aws-amplify/amplify-js/blob/master/packages/amplify-ui-components/src/components/amplify-sign-in/amplify-sign-in.tsx#L237

Showing a small code snippet of an override would be helpful.
It is not obvious how to import the Translations file.

**Comment by swaminator** [comment]
@xavierraffin are you referring to this: https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#custom-form-fields
