### ISSUE TITLE
[Feedback] Not user friendly documentation

### ISSUE THREAD

**Issue by ashanderey** [aws-amplify/docs#1710]
**Page**: [`/ui/q/framework/react`](https://docs.amplify.aws/ui/q/framework/react)

**Feedback**:

Documentation is not user friendly and super high level and it makes no sense until you fully understand the amplify.

**Comment by swaminator** [comment]
@ashanderey can you be a bit more specific about what you mean by that?

**Comment by mauerbac** [comment]
Closing since we haven't heard back. @ashanderey - feel free to ping me on [Discord](http://discord.gg/amplify) with further feedback
