### ISSUE TITLE
team-provider-info.json clarification

### ISSUE THREAD

**Issue by alexkates** [aws-amplify/docs#1713]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
All

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
4.18.0

**What AWS Services are you utilizing?**
Cognito, Lambda, S3

**Provide additional details e.g. code snippets**
After running `amplify env add` and looking in our `team-provider-info.json` file, I'm noticing differences between my file and the file in the documentation located here: https://aws-amplify.github.io/docs/cli-toolchain/quickstart#sharing-projects-outside-the-team-

Specifically, my file has additional information related to categories. My question is how are these used in the cli? Are they updated when I add/remove Categories? 
```
...
"categories": {
            "auth": {
                "cognito": {}
            },
            "function": {
                "service1": {},
                "service2": {},
                "service3": {}
            }
        }
```

**Comment by nateous** [comment]
I notice that the file has ARNs in it. It is also checked into source control. Is this env meant to be shared between multiple devs?

I'm having trouble setting up what I have on another dev's machine. It only works for me since I set it up initially.

Would be nice to have more docs on how to use this in a team.

**Comment by mauerbac** [comment]
Hi everyone - this is actually documented here -> https://docs.amplify.aws/cli/teams/shared#sharing-projects-outside-the-team. I agree that this should be linked or discoverable. Will create a PR. Thank you

**Comment by sampeka** [comment]
I'm not sure I understand this and after reading a bunch of answers around it, and reviewing the docs, I'm still confused about how this can be safely committed to source even if the codebase isn't public.

The example workflow in the docs has two long running brunches, `dev` and `prod`. It suggests that when we need to deploy new features to production, we can merge `dev` into `prod` and then `amplify push`. 

But how can this be possible when this file is updated when we switch between amplify environments? There will always be merge conflicts, unless I'm missing something?
