### ISSUE TITLE
[Feedback]Update command to create new Ionic App

### ISSUE THREAD

**Issue by asopian** [aws-amplify/docs#1716]
**Page**: [`/start/q/integration/ionic`](https://docs.amplify.aws/start/q/integration/ionic)

**Feedback**:

The command for "Creating a new Ionic App" is outdated.
According to Ionic's [Getting Started page](https://ionicframework.com/getting-started) the command should be updated from:
```
npm install -g ionic
ionic start myAmplifyProject blank --type=angular 
cd myAmplifyProject
npm install && npm start
```
 to:
```
npm install -g @ionic/cli
ionic start myAmplifyProject blank --type=angular
cd myAmplifyProject
ionic serve
```
Or even better to use:
(to use per project Ionic CLI, and avoid potential conflict with previously installed older Ionic CLI)
```
npx -p @ionic/cli ionic start myAmplifyProject blank --type=angular
cd myAmplifyProject
npx ionic serve
```
There is no need to run `npm install` (again), because `ionic start` already automatically install all dependencies.
User should not call `npm start`, but should call `ionic serve` instead.

**Comment by jordanranz** [comment]
Great feedback, we definitely should definitely have Ionic specific documentation for both Getting Started and the UI components. Looking to improve this content in the near future.

**Comment by mauerbac** [comment]
I believe this is a similar issue -> https://github.com/aws-amplify/docs/issues/1224.

**Comment by mauerbac** [comment]
https://github.com/aws-amplify/docs/issues/2018
