### ISSUE TITLE
[Feedback]API Reference

### ISSUE THREAD

**Issue by scottkelso** [aws-amplify/docs#1717]
**Page**: [`/cli`](https://aws-amplify.github.io/amplify-js/api/)

**Feedback**:

Hi there,

I'm wondering if the [API Reference](https://aws-amplify.github.io/amplify-js/api/) structure could be made more clear? I currently rarely use it because I can't find anything and don't understand how anything links together. 

Might I suggest at least a key to describe what the distinguishing symbols are on each item in the left side menu? Some are clearly objects while others are functions but no hierarchical structure to say which relate to each other until you click into some of them.

**Comment by mauerbac** [comment]
Hi @scottkelso - that is our low level documentation and is auto generated, so it's difficult for us to change the way it's structured. Ideally our main [docs](https://docs.amplify.aws/) explain these concepts. Will close this as we don't plan to change that documentation page. If you have other suggestions or improvements, please open a new issue. Thank you
