### ISSUE TITLE
[Feedback] unknown file in config docs

### ISSUE THREAD

**Issue by cyrfer** [aws-amplify/docs#1731]
**Page**: [`/cli/usage/headless`](https://docs.amplify.aws/cli/usage/headless)

**Feedback**:

I don't have the file mentioned in this documentation about `awsconfiguration.json`.

> Config files
> When performing operations against the local mock endpoint, the Amplify CLI will automatically update your aws-exports.js and awsconfiguration.json with the local endpoints

```bash
$ amplify -v
4.18.1
```

**Comment by brene** [comment]
@cyrfer - can you run an `amplify push` and check if the file is still not there?

**Comment by cyrfer** [comment]
Yes. It's definitely not there. I also tried `amplify push` with an updated version of the CLI.
```bash
$ amplify --version
4.19.0
```

I have not noticed any other documentation talking about this file. What does it do?

![image](https://user-images.githubusercontent.com/4392990/81794565-d3205f80-94bf-11ea-8b2e-67775585250e.png)

**Comment by cyrfer** [comment]
I don't see the file mentioned in the docs anymore. Was it removed?

**Comment by swaminator** [comment]
@cyrfer seems like you are building a react app - you should be looking for the aws-exports.js file

**Comment by cyrfer** [comment]
I know that. I was contributing to the documentation that cited `awsconfiguration.json`.

**Comment by mauerbac** [comment]
Sorry for the back and forth @cyrfer - i also can confirm it was removed from the JS sections. It looks like it used in the [mobile SDKs](https://github.com/aws-amplify/docs/search?q=awsconfiguration.json+with+the+local+endpoints&unscoped_q=awsconfiguration.json+with+the+local+endpoints) 

Are you still running into an issue here?
