### ISSUE TITLE
[missing-page]

### ISSUE THREAD

**Issue by chowerth** [aws-amplify/docs#1735]
**Page**: [`https://docs.amplify.aws/lib/analytics/autotrack/q/platform/js`](https://docs.amplify.aws/lib/analytics/autotrack/q/platform/js)

**Feedback**: Seems the "Automatically Track Sessions" link for the JavaScript Amplify Docs is broken.

**Comment by brene** [comment]
@chowerth can you be a bit crisper? The link seems to work for me.

**Comment by chowerth** [comment]
False alarm. Turns out my uBlock origin plugin was blocking that page of the tutorial/guide and I didn't notice (the other links worked fine with it active). If I disable it I can view that link fine. 

![AWS404](https://user-images.githubusercontent.com/56286587/81626042-94f44480-93c8-11ea-934c-876b747e3166.PNG)


![AWSFine](https://user-images.githubusercontent.com/56286587/81626048-96be0800-93c8-11ea-8d31-feaa865f0021.PNG)

**Comment by sammartinez** [comment]
resolving as the false alarm
