### ISSUE TITLE
[Feedback]Triggers and Functions

### ISSUE THREAD

**Issue by scottkelso** [aws-amplify/docs#1736]
**Page**: [`/cli/function`](https://docs.amplify.aws/cli/function)

**Feedback**:

Apologies, I am new to aws and amplify, but I am having trouble understanding how to do something that should be rather simple because of a lack of documentation. I would like to add a user to a group on signup. From what the community is saying, this is currently done via a post-confirmation lambda trigger. The documentation describes nothing about triggers, which would lead me to believe they are something to do with `amplify add function` pathway. An example would be great!

**Comment by brene** [comment]
Hi @scottkelso - can you check out this page? https://docs.amplify.aws/cli/usage/lambda-triggers#cognito-lambda-triggers

I agree that the docs here to be better structured to naturally point you to the correct content. Tagging this issue for the team to pick up.
