### ISSUE TITLE
[Feedback]Should not suggest user to upgrade to 

### ISSUE THREAD

**Issue by ivenxu** [aws-amplify/docs#1737]
**Page**: [`/ui/q/framework/react`](https://docs.amplify.aws/ui/q/framework/react)

**Feedback**:

[Migration](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#migration) implies using amplify-ui-react is better than aws-amplify-react. However, the theme override feature in aws-amplify-react is not implemented.

Basically, the @aws-amplify/ui-react is not production ready yet. This migration section should never been there.

There's missing feature such as theme customization. see https://github.com/aws-amplify/amplify-js/issues/5733

**Comment by ericclemmons** [comment]
Theme customization does exist for the new components via CSS variables:
> https://docs.amplify.aws/ui/customization/theming/q/framework/react

(More details in my response here: https://github.com/aws-amplify/amplify-js/issues/5733#issuecomment-626879813)

**Comment by brene** [comment]
cc @jordanranz @sammartinez
