### ISSUE TITLE
[Syntax issues] REST API docs

### ISSUE THREAD

**Issue by ffxsam** [aws-amplify/docs#1740]
https://docs.amplify.aws/lib/restapi/fetch/q/platform/js

Two issues I wanted to point out:

```js
async getData() { 
  const apiName = 'MyApiName';
  const path = '/path';
  const myInit = { // OPTIONAL
    headers: {}, // OPTIONAL
  };

  return await API.get(apiName, path, myInit);
}

getData();
```

Besides the fact it's missing `function` on line 1, and `await` is missing on the actual function call, this should code example instead be:

```js
function getData() { 
  const apiName = 'MyApiName';
  const path = '/path';
  const myInit = { // OPTIONAL
    headers: {}, // OPTIONAL
  };

  return API.get(apiName, path, myInit);
}

await getData();
```

`return await` is redundant inside an `async` function, in fact, it's an [ESLint error/warning](https://eslint.org/docs/rules/no-return-await). The function is already returning a Promise implicitly when it's declared with `async`, so it's sufficient to just return the function that returns a Promise.

Same issue with the second code snippet on the page:

```js
async function head() { 
    const apiName = 'MyApiName';
    const path = '/path';
    const myInit = { // OPTIONAL
        headers: {}, // OPTIONAL
    };

    return await API.head(apiName, path, myInit);
}

head();
```

**Comment by brene** [comment]
cc @sammartinez

**Comment by mtliendo** [comment]
#1776

**Comment by sammartinez** [comment]
Resolving as the Pull Request was merged
