### ISSUE TITLE
Saving Example does not work for DataStore relational js

### ISSUE THREAD

**Issue by GeorgeBellTMH** [aws-amplify/docs#1743]
const post = await DataStore.save(
  new Post({
    title: "My Post with comments",
    rating: 10,
    status: PostStatus.ACTIVE
  })
);

await DataStore.save(
  new Comment({
    content: "Loving Amplify DataStore!",
    post
  })
);

should likely be post:post

**Comment by brene** [comment]
@GeorgeBellTMH - this seems to be the correct ES6 notation: https://alligator.io/js/object-property-shorthand-es6/ What environment are you using DataStore in?

**Comment by GeorgeBellTMH** [comment]
Typescript...

**Comment by undefobj** [comment]
@GeorgeBellTMH can you test again? The documentation has been updated.
