### ISSUE TITLE
[Feedback] we don't need to add firebase-core anymore 

### ISSUE THREAD

**Issue by dakeshi** [aws-amplify/docs#1747]
**Page**: [`/sdk/push-notifications/getting-started/q/platform/android`](https://docs.amplify.aws/sdk/push-notifications/getting-started/q/platform/android)

**Feedback**:

in https://firebase.google.com/docs/android/setup#available-libraries, 

> The Firebase Android library firebase-core is no longer needed. This SDK included the Firebase SDK for Google Analytics.

so, it needs to be updated codes in app/build.gradle

**Comment by jpignata** [comment]
Thanks! Is the idea here that we need to remove the line where we include firebase-core?

**Comment by dakeshi** [comment]
@jpignata exactly. there is no problem in my pinpoint integration test without firebase-core
