### ISSUE TITLE
Amplify Android : Getting Started : errors in Kotlin code

### ISSUE THREAD

**Issue by sebsto** [aws-amplify/docs#1778]
# Android Getting Started Doc 

## Step 3 : Integrate in your App 

**URL** : https://next-docs.amplify.aws/lib/getting-started/integrate/q/platform/android#configure-amplify-and-datastore

Kotlin code snipet is invalid, correct one is below:

```kotlin

import com.amplifyframework.AmplifyException
import com.amplifyframework.core.Amplify
import com.amplifyframework.api.aws.AWSApiPlugin
import com.amplifyframework.datastore.AWSDataStorePlugin


        try {
            Amplify.addPlugin(AWSDataStorePlugin()) 
            Amplify.addPlugin(AWSApiPlugin())
            Amplify.configure(applicationContext)

            Log.i("Tutorial", "Initialized Amplify")
        } catch (e: AmplifyException) {

            Log.e("Tutorial", "Could not initialize Amplify", e)
        }
```

**Comment by jpignata** [comment]
Hmm, is the code different, or are you saying we should include the imports? If the latter, I actually omit them everywhere as Android developers will option-enter the imports in generally. Thanks for the report!

**Comment by sebsto** [comment]
The code is different too, the doc says 

`new AWSDataStorePlugin()`

while, in Kotlin, `new` is not necessary 


`new AWSDataStorePlugin()` => `AWSDataStorePlugin()`

**Comment by jpignata** [comment]
Thank you!
