### ISSUE TITLE
Amplify iOS : Getting Started : errors in order of steps 

### ISSUE THREAD

**Issue by sebsto** [aws-amplify/docs#1780]
# iOS Getting Started Doc

## Step 3 : Integrate your app 

URL : https://next-docs.amplify.aws/lib/getting-started/add-api/q/platform/ios

When following the steps at the above URL, the step 

> Testing your API

Is not working before the `amplify push`
To test the API and actually run the application, it is necessary to create the backend resources first, i.e. the follow the step in the "Connect to the cloud" section

**Comment by drochetti** [comment]
Hi Sébastien, the `next-docs` instructions relies on the unreleased version of Amplify iOS. So you need to pull the dependencies from master for the time being.

We have an RC release scheduled to Thursday.

`Podfile` using master:

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'TodoAmplify' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TodoAmplify
  pod 'Amplify', :git => 'https://github.com/aws-amplify/amplify-ios.git', :branch => 'master'
  pod 'Amplify/Tools', :git => 'https://github.com/aws-amplify/amplify-ios.git', :branch => 'master'
  pod 'AWSPluginsCore', :git => 'https://github.com/aws-amplify/amplify-ios.git', :branch => 'master'
  pod 'AmplifyPlugins/AWSAPIPlugin', :git => 'https://github.com/aws-amplify/amplify-ios.git', :branch => 'master'
  pod 'AmplifyPlugins/AWSDataStorePlugin', :git => 'https://github.com/aws-amplify/amplify-ios.git', :branch => 'master'

  # Tooling
  pod 'SwiftFormat/CLI'

end
```

ps: The `Podfile` above is from an implementation of the Todo app I have in my personal repo. Feel free to reach out to me with questions regarding it: https://github.com/drochetti/todo-app-amplify-ios

**Comment by sebsto** [comment]
I confirm the steps in the 1.0.0 doc at https://docs.amplify.aws/start/getting-started/native_integrate/q/integration/ios are working.
