### ISSUE TITLE
[Feedback]Allow hiding of left and/or right panes in the docs

### ISSUE THREAD

**Issue by kimfucious** [aws-amplify/docs#1813]
**Page**: [`/cli/graphql-transformer/dataaccess`](https://docs.amplify.aws/cli/graphql-transformer/dataaccess)

**Feedback**:

It would be great if there were a way to hide the left and/or right panes in the docs, .esp for the purposes of reading code examples.

It's really hard, for me at least, to get the gist of a code example, when having to scroll horizontally to read it.  I find myself having to copy the code out and pasting it somewhere to read it more easily.

If not hiding the panes, then perhaps a popout/modal to show it by itself.

**Comment by mauerbac** [comment]
Thanks @kimfucious - I imagine you mean across the site, correct?

**Comment by kimfucious** [comment]
Hi @mauerbac 

Yeah, pretty much in all the docs, as horizontal scrolling make it tedious to read code examples.

I realize that this is a "nice to have", but it would be nice to have.

Thanks.

**Comment by mauerbac** [comment]
not stale

**Comment by kimfucious** [comment]
Thanks for keeping this alive, @mauerbac 

While I know that you're most likey on different, 2-pizza-sized teams, the folks who maintain [these pages](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminInitiateAuth.html), are doing exactly what I was imagining.

Best,

Kim

**Comment by kimfucious** [comment]
Did @mauerbac fly the coop?

**Comment by mauerbac** [comment]
sorry, forgot to respond! I actually learned something...https://twitter.com/mauerbac/status/1281288919603195904 

This task is prioritized and will be worked on in next week or so. Should help with the mobile experience!

**Comment by kimfucious** [comment]
Not stale yet, unless @mauerbac says so!

**Comment by tjleing** [comment]
Resolved!  Go check it out on live 😄
