### ISSUE TITLE
[Feedback] Missing policy dynamodb:DescribeTimeToLive in /cli/usage/iam

### ISSUE THREAD

**Issue by small4all** [aws-amplify/docs#1821]
**Page**: [`/cli/usage/iam`](https://docs.amplify.aws/cli/usage/iam)

**Feedback**:
Missing policy `dynamodb:DescribeTimeToLive`. This is necessary after activating datastore for an existing GraphQl API via cli.

```
Resource Name: AmplifyDataStore-xxx (AWS::DynamoDB::Table)
Event Type: create
Reason: User: arn:aws:iam::xxx:user/xxx is not authorized to perform: dynamodb:DescribeTimeToLive on resource: arn:aws:dynamodb:eu-central-1:xxx:table/AmplifyDataStore-xxx-dev (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: AccessDeniedException; Request ID: xxx)
```

**Comment by palpatim** [comment]
@small4all Thanks for reporting this issue. Can you clarify: This is only applicable to activating DataStore on an existing API, not when creating a new API/DataStore from scratch via the CLI, right?

**Comment by small4all** [comment]
@palpatim 

Note that this is not a fault of the CLI, this is only a partial documentation of the policy.

I haven't found a way to activate the datastore directly with `amplify add api`. Maybe the datastore's documentation is also incomplete, after finishing this documentation i was missing the relevant dynomo db table for the datastore: https://docs.amplify.aws/lib/datastore/getting-started/q/platform/js. maybe i am too stupid ;).

For this reason i chose the way via `amplify update api` to activate the datastore.  

This is the CLI command to activate the datastore:
```
https://docs.amplify.aws/lib/datastore/getting-started/q/platform/js#automated-model-generation-with-npx

amplify update api
? Please select from one of the below mentioned services: GraphQL
? ? select from the options below 
  Walkthrough all configurations 
  Update auth settings 
❯ Enable DataStore for entire API 
```

If the datastore can be activated directly I expect the same error. Because 'DescribeTimeToLive' is probably always needed when datastore is activated.

The docs create the user immder with 'admin' policy, so it might affect the fewest. For security reasons I recommend a reduced policy and therefore the docu for the policy is very important: https://docs.amplify.aws/cli/usage/iam


Would be cool of course if there was a managed policy already in AWS :)

**Comment by brene** [comment]
We've added the `dynamoDB:DescribeTimeToLive` policy now.
