### ISSUE TITLE
Not able to Re-Build android app after running amplify push

### ISSUE THREAD

**Issue by cgaribay** [aws-amplify/docs#1862]
**Describe the bug**
I'm using the Getting Started Tutorial for Android and on _Step 4: Push changes_, after I run the command`amplify push`, I then run a Gradle Sync and Re-build my app and the build fail with the following message:
```
npm ERR! Windows_NT 10.0.18362
npm ERR! argv "C:\\Users\\kay_8\\Documents\\AWSExampleApp\\app\\.gradle\\nodejs\\node-v6.7.0-win-x64\\node.exe" "C:\\Users\\kay_8\\Documents\\AWSExampleApp\\app\\.gradle\\nodejs\\node-v6.7.0-win-x64\\node_modules\\npm\\bin\\npm-cli.js" "install" "apollo-codegen@0.17.0-alpha.13" "--save" "--save-exact"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code EPROTO
npm ERR! errno EPROTO
npm ERR! syscall write

npm ERR! write EPROTO 101057795:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:openssl\ssl\s3_clnt.c:2010:
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\kay_8\Documents\AWSExampleApp\app\build\apollo-codegen\npm-debug.log

> Task :app:installApolloCodegen FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installApolloCodegen'.
> Process 'command 'C:\Users\kay_8\Documents\AWSExampleApp\app\.gradle\nodejs\node-v6.7.0-win-x64\node.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 13s
```

**Desktop (please complete the following information):**
 - OS: Windows 10
- Android Studio 3.6.3
[npm-debug.log](https://github.com/aws-amplify/docs/files/4690916/npm-debug.log)

**Comment by jamesonwilliams** [comment]
Hi @cgaribay, one thing I notice of the bat is that your `node` and `npm` are out of date:
```
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
```

The [Android Amplify Tutorial lists these pre-requisites](https://docs.amplify.aws/start/getting-started/installation/q/integration/android):
 - Node.js v10.x or later
 - npm v5.x or later
 - git v2.14.1 or later
 - Install Android Studio version 3.1 or higher.
 - Install Android SDK for API level 28 (Android 9.0).

Updating your dependencies to compatible versions would be a good place to start.

**Comment by cgaribay** [comment]
On my computer I have node version 12.17.0 and npm version 6.14.4. How do I change the dependencies of the project to make it use the versions I installed on my local computer?

**Comment by mauerbac** [comment]
hi @cgaribay - can you check the dependencies in the directory ?

**Comment by cgaribay** [comment]
Looks like I was following an old tutorial from AWS, I found the new one and it is working fine. Thanks

**Comment by umerk44** [comment]
@cgaribay Could you mention the tutorial you are referring to? I am facing the same issue.
