### ISSUE TITLE
[Feedback] Getting Started Guide - React

### ISSUE THREAD

**Issue by drclohite** [aws-amplify/docs#1869]
**Page**: [`/start/getting-started/setup/q/integration/react`](https://docs.amplify.aws/start/getting-started/setup/q/integration/react)

**Feedback**:

This page shows lines 7,8 and 9 as 1,2,3. I did that. Then I ran npm start to check it works (could be an added instruction to help people on this page), it failed. The error seemed to tell me to move the content around and eventually, I deduced the error was trying to tell me the additional lines of code should go in after the current lines of code inserted automatically during creation.  When I made this simple change it worked. 
 
1: import React from 'react';
2: import ReactDOM from 'react-dom';
3: import './index.css';
4: import App from './App';
5: import * as serviceWorker from './serviceWorker';
6:
7: import Amplify from "aws-amplify";
8: import awsExports from "./aws-exports";
9: Amplify.configure(awsExports);

**Comment by drclohite** [comment]
Also I got warning as follows, which I have ignored, as the app worked, although this may concern the code author ...

(webpack)/buildin/module.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Users\Multiple Monitors\ESORMA\react-amplified\node_modules\babel-loader\lib\index.js??ref--6-oneOf-2!C:\Users\Multiple Monitors\ESORMA\react-amplified\node_modules\webpack\buildin\module.js
    Used by 2 module(s), i. e.
    C:\Users\Multiple Monitors\ESORMA\react-amplified\node_modules\babel-loader\lib\index.js??ref--6-oneOf-2!C:\Users\Multiple Monitors\ESORMA\react-amplified\node_modules\node-libs-browser\node_modules\punycode\punycode.js
* C:\Users\Multiple Monitors\ESORMA\react-amplified\node_modules\babel-loader\lib\index.js??ref--6-oneOf-2!C:\Users\Multiple Monitors\esorma\react-amplified\node_modules\webpack\buildin\module.js
    Used by 2 module(s), i. e.
    C:\Users\Multiple Monitors\ESORMA\react-amplified\node_modules\babel-loader\lib\index.js??ref--6-oneOf-2!C:\Users\Multiple Monitors\esorma\react-amplified\node_modules\lodash\lodash.js

This was a fresh install from scratch following the directions on the page.

**Comment by wlee221** [comment]
Hi @drclohite , thanks for your feedback! You are right, lines 7-9 in your code should be placed below the last import, as written in the documentation. I see that the line numbers next to the code fragments can be confusing; I'll pass this to the team to see if we can make it clearer. 

For the second issue, these warnings often occur from a casing typo in the import statements. Please feel free to open an issue in amplify-js repo if the warnings persist!
