### ISSUE TITLE
[Feedback]Codegen statement missing when building api from cli

### ISSUE THREAD

**Issue by ashishverma1108** [aws-amplify/docs#1870]
**Page**: [`/sdk/api/graphql/q/platform/ios`](https://docs.amplify.aws/sdk/api/graphql/q/platform/ios)

**Feedback**:

The tutorial for building api from cli doesn't include "amplify codegen add" statement needed to create model swift code.

**Comment by TrekSoft** [comment]
Isn't it here? Or are you talking about something else?

![Screen Shot 2020-05-28 at 10 47 50 AM](https://user-images.githubusercontent.com/5085574/83156703-ba739480-a0d0-11ea-9b7e-a54007377bef.png)

**Comment by ashishverma1108** [comment]
I believe this is for api created using console, where you can provide apiId. For api created using, cli, the document doesn't say if the above command should be used or not... so I actually ended up using "amplify codegen add". Please let me know if I m not thinking about this correctly.

**Comment by TrekSoft** [comment]
Were you using the Amplify Framework or the old AppSync SDK? If you're not sure, post a rough code snippet you use to make an API call and I can tell you.

**Comment by ashishverma1108** [comment]
I am using Amplify framework.  
`
self.appSyncClient?.fetch(query: ListLandmarksQuery(limit:100), cachePolicy: .fetchIgnoringCacheData ) {(result, error) in`

Sample code above. It's not currently work :) I've decided to rewrite my entire backend and associated swiftui files again... assuming I am using some outdated functions currently. I was initially following an old tutorial: https://amplify-ios-workshop.go-aws.com/30_add_authentication/20_client_code.html. Planning to follow new one now.

**Comment by palpatim** [comment]
@ashishverma1108 That code snippet is actually from the AppSync SDK, not the Amplify framework. :)

The tutorial page you linked https://docs.amplify.aws/sdk/api/graphql/q/platform/ios seems to be accurate. To clarify, there are two main ways of creating your API, the AppSync console and the Amplify CLI. The doc snippet @TrekSoft referenced is for adding Amplify generated models to an API created in the console. If you create an API via the Amplify CLI, the CLI will prompt you to create models as part of the `amplify push` step, as noted in the doc snippet:

> The `amplify push` process will prompt you to enter the codegen process and walk through configuration options.

You should not need to use `amplify codegen add` in this case.

Hope this helps.

**Comment by ashishverma1108** [comment]
Hey @palpatim  I believe you're right... I am sorry I mixed up the two libraries. I believe we can close this.. sorry for wasting your time. Appreciate your inputs. 
Will really appreciate if you could answer an unrelated question... is AWSMobileClient Library deprecated?

**Comment by ashishverma1108** [comment]
Also, should I not be using any appSync code and move to use amplify for everything?

**Comment by mauerbac** [comment]
Hey @ashishverma1108 - will close this since it seems this has been resolved. In terms of your last question, it might be easiest to get a higher level explanation from our community in our [Discord Server](www.discord.gg/amplify). We have a #ios-help channel
