### ISSUE TITLE
[Feedback] Tutorial in Vue.js (Connect API and database to the app)

### ISSUE THREAD

**Issue by Tolluset** [aws-amplify/docs#1878]
Page: [/start/getting-started/data-model/q/integration/vue](https://docs.amplify.aws/start/getting-started/data-model/q/integration/vue)

__Feedback__:

I'm going to talk about some confusing things during the tutorial.

https://docs.amplify.aws/start/getting-started/data-model/q/integration/vue#create-graphql-api-and-database

The code section describing GraphQL describes it twice as 

```GraphQL
description: String!
```

Non-nullable status with ! in String.

![amplify-1](https://user-images.githubusercontent.com/50096419/83192692-ddee1c00-a170-11ea-884e-130a839e78cf.PNG)

But as below (amplify/backend/api/myapi/schema).
Code under GraphQL In the actual description section, there is no ! as 

```GraphQL
description: String
```
(nullable)

![amplify-2](https://user-images.githubusercontent.com/50096419/83192716-e8101a80-a170-11ea-85ea-30605901fa99.PNG)

So, I also checked the code on the amplify-cli. 

https://github.com/aws-amplify/amplify-cli/blob/b12d20b9d85f7fc6abf7e2f7fbe11e1a108911b9/packages/amplify-category-api/provider-utils/awscloudformation/appsync-schemas/single-object-schema.graphql

It was 
```GraphQL
description: String
```

So the "description" should have no exclamation mark(!), (nullable).

![amplify-4](https://user-images.githubusercontent.com/50096419/83192795-0249f880-a171-11ea-9830-25b0cb4cfa51.PNG)

If the content above is correct, I think the code in the tutorial below should be changed. 

```JavaScript
if (!name | !description) return;
```
In this code without the "description", todo was not created.

So I think it should be changed to 

```JavaScript
if (!name) return;
```
![amplify-3](https://user-images.githubusercontent.com/50096419/83194881-4f7b9980-a174-11ea-91ca-199280580904.PNG)

And I tested it, and It works.

![amplify-6](https://user-images.githubusercontent.com/50096419/83195118-ae411300-a174-11ea-88a5-f51f18567981.PNG)

https://github.com/Tolluset/Amplify-Vue.js-Tutorial/blob/master/src/App.vue

![amplify-5](https://user-images.githubusercontent.com/50096419/83195325-0546e800-a175-11ea-93da-f303dd6d3979.PNG)

https://dev.d22s4bb9uyvy69.amplifyapp.com/

Of course, it's not a big part, but I write because I think it's something that beginners like me can be confused about. 

If there is something wrong, please tell me!

**Comment by brene** [comment]
cc @dabit3
