### ISSUE TITLE
[Feedback]Building Project Fails in "Initialize Amplify API" Step

### ISSUE THREAD

**Issue by kwomackcodes** [aws-amplify/docs#1880]
**Page**: [`/lib/graphqlapi/getting-started/q/platform/ios`](https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/ios#next-steps)

**Feedback**:

After adding code as instructed to AppDelegate’s application:didFinishLaunchingWithOptions method the build fails with three errors as seen in the screenshot.

<img width="271" alt="Screen Shot 2020-05-29 at 8 05 51 AM" src="https://user-images.githubusercontent.com/22060567/83257886-40501800-a183-11ea-94c4-f04fb8507b0e.png">

Can anyone reproduce by simply following the steps in the tutorial?

**Comment by palpatim** [comment]
@kwomackcodes Sorry for the trouble you're having with this. We've noticed that the first compilation sometimes has problems (https://github.com/aws-amplify/amplify-ios/issues/489). We've been able to work around it by doing a **Clean Build Folder (Shift-Cmd-K)**, then rebuilding. Hope this workaround works for you while we try to figure out what's going on.

**Comment by kwomackcodes** [comment]
Thanks for the help @palpatim ! Build succeeds after the workaround you suggested.
