### ISSUE TITLE
Inconsistency in iOS Getting Started Tutorial 

### ISSUE THREAD

**Issue by Leinadzet** [aws-amplify/docs#1886]
**Page**: [`/start/q/integration/ios`](https://docs.amplify.aws/start/q/integration/ios)

**Feedback**:

Seems like the 2nd sentence under the "Generate Model Files" is somehow wrong. Is doesn't make sense?

"Amplify DataStore will use this model to persist data to your local device <Something is missing here?> will be synchronized to a backend API without writing any additional code. "

![image](https://user-images.githubusercontent.com/8782897/83409971-c4213300-a415-11ea-9a18-8bc9d90bf9f5.png)

**Comment by Leinadzet** [comment]
Also seems like the in the next paragraph the location of the Schemafile is misleading:

"open the schema file located at AmplifyConfig > schema.graphql. In your project folder, this is located at: "amplify/backend/api/amplifyDatasource/schema.graphql"."

First part is not sufficient for iOS, the second part is, as it is within my folder. But there is no "AmplifyConfig" folder. See attached the screenshot of how the structure looks like after first build. 

<img width="267" alt="image" src="https://user-images.githubusercontent.com/8782897/83410290-65a88480-a416-11ea-9a58-214fda9ac228.png">

**Comment by Leinadzet** [comment]
Also the file in step 2 is not called "amplifytools.xcconfig" but "amplifyxc.config": 

"Next, generate the classes for these models. Update the amplifytools.xcconfig file and change modelgen=false to:"

![image](https://user-images.githubusercontent.com/8782897/83410551-dd76af00-a416-11ea-976f-e653ad7fbfa7.png)

**Comment by Leinadzet** [comment]
I redid everything with a fresh install of my Mac and now I see the AmplifyConfig folder - which brings me to the feedback that these instructions are not correct:

<img width="780" alt="image" src="https://user-images.githubusercontent.com/8782897/83430802-96001b00-a436-11ea-8ff9-aec5f1ed8f7c.png">


It says that a "amplify" folder is generated - this should be the "AmplifyConfig" folder right?

**Comment by seriyvolk83** [comment]
> I redid everything with a fresh install of my Mac and now I see the AmplifyConfig folder - which brings me to the feedback that these instructions are not correct:
> 
> <img alt="image" width="780" src="https://user-images.githubusercontent.com/8782897/83430802-96001b00-a436-11ea-8ff9-aec5f1ed8f7c.png">
> 
> It says that a "amplify" folder is generated - this should be the "AmplifyConfig" folder right?

There is no such instruction in this tutorial. Where did you get that?

**Comment by Leinadzet** [comment]
Well, it was there in a previous version. Seems like it’s been updated.
