### ISSUE TITLE
Doc doesnot have explanation for sign in next step

### ISSUE THREAD

**Issue by royjit** [aws-amplify/docs#1892]
**Describe the bug**
Explanation of the next steps in signin for iOS and Android. Developers doesnot know what to do when they get one of this next step.

```
    /// Auth step is SMS multi factor authentication.
    ///
    /// Confirmation code for the MFA will be send to the provided SMS.
    case confirmSignInWithSMSMFACode(AuthCodeDeliveryDetails, AdditionalInfo?)

    /// Auth step is in a custom challenge depending on the plugin.
    ///
    case confirmSignInWithCustomChallenge(AdditionalInfo?)

    /// Auth step required the user to give a new password.
    ///
    case confirmSignInWithNewPassword(AdditionalInfo?)

    /// Auth step required the user to change their password.
    ///
    case resetPassword(AdditionalInfo?)

    /// Auth step that required the user to be confirmed
    ///
    case confirmSignUp(AdditionalInfo?)

    /// There is no next step and the signIn flow is complete
    ///
    case done
```

**Comment by dougie181** [comment]
I also cannot find any documentation that describes next steps. For instance, when creating a user manually and then performing an Auth.signIn(...), the message returned is Amplify.AuthSignInStep.confirmSignInWithNewPassword. I have tried with no joy the following
1) Auth.signIn(...) with the new password,
2) Auth.update(..) to change old password to new password

Neither work and not sure what the next steps should actually be!

I did find this document: [https://docs.aws.amazon.com/cognito/latest/developerguide/signing-up-users-in-your-app.html], but it is also not clear on what the next step should be. It does say that:
> The user is required to change the password before signing in. 

But, I do not know what method to call to action this.

While this would not be something that would come up often, It would still be helpful if there was some docs on the correct process here!

**Comment by cboebel** [comment]
@dougie181 did you ever find an answer for this?

**Comment by jamesonwilliams** [comment]
We should look at the stalebot config. It's closing stuff that shouldn't be, like this. I agree 100% with @royjit that this is confusing gap in our docs. We have no docs describing the Auth system end-to-end. Sign-up and sign-in are intuitive perhaps. But even those can have multiple steps. The context of a "next step" is entirely undocumented right now, even thought its a critical aspect of the public APIs.

**Comment by dougie181** [comment]
> @dougie181 did you ever find an answer for this?

Yes... in my case, the 'nextStep' was to perform a Amplify.Auth.confirmSignIn with the challengeResponse being the a new password.

There may be other scenarios that my code hasn't covered though, so improving the docs make sense to me.

**Comment by royjit** [comment]
iOS documentation added - https://github.com/aws-amplify/docs/pull/2936
