### ISSUE TITLE
iOS SDK Reference 

### ISSUE THREAD

**Issue by HollyWallace** [aws-amplify/docs#1893]
**Page**: [`/sdk/q/platform/ios`](https://docs.amplify.aws/sdk/q/platform/ios)

**Feedback**:

Hi - it's 2020 and it's (still) being a real pain in the neck to figure out how to use Cognito to manage the user sign-in process.  I don't need my users to connect to AWS Services, I don't need anything but to manage users signing into my app with a username and password.  Should be the simplest possible case.  I have spent days on this and am hugely frustrated.  I just want to see an API reference that pertains to the Swift SDK.  I don't want to use Amplify, I just want to get the simplest possible use-case for Cognito working.  Where is the damned reference???  About the Swift SDK??? About the code, the methods, the properties, the order in which these things are called and what they do???  Is it buried in the hundreds of pages of developer guide?  I just want the Swift SDK API reference.  Please.

**Comment by jpignata** [comment]
Hi there. Are you looking for the API reference for the V2 iOS SDK? You can find that in the top navigation under the API Reference link. Here's a direct link: https://aws-amplify.github.io/aws-sdk-ios/docs/reference/ -- does that help?

**Comment by swaminator** [comment]
@HollyWallace is there any particular reason why you do not want to use Amplify?

**Comment by swaminator** [comment]
Closing this issue. Feel free to reopen if you have any questions.
