### ISSUE TITLE
Indicate how to disable auto generated createdAt and updatedAt fields

### ISSUE THREAD

**Issue by brene** [aws-amplify/docs#1895]
**Is your feature request related to a problem? Please describe.**

CLI started adding createdAt and updatedAt by default to a model.

We should update the docs with how to disable these auto generated fields for customers who have advanced use cases 

**Describe the solution you'd like**
We should update the docs with how to disable these auto generated fields for customers who have advanced use cases 

**Describe alternatives you've considered**
N/A

**Additional context**
Discussed on discord: https://discordapp.com/channels/705853757799399426/708077731711156284/717401539920265247

**Comment by kozarip** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> CLI started adding createdAt and updatedAt by default to a model.
> 
> We should update the docs with how to disable these auto generated fields for customers who have advanced use cases
> 
> **Describe the solution you'd like**
> We should update the docs with how to disable these auto generated fields for customers who have advanced use cases
> 
> **Describe alternatives you've considered**
> N/A
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.
> Discussed on discord: https://discordapp.com/channels/705853757799399426/708077731711156284/717401539920265247

Hey renebrandel,

I have a same issue, Did you find any solution?

BR
Peter
