### ISSUE TITLE
[Feedback]Android and iOS Amplify Documentation

### ISSUE THREAD

**Issue by jamesmalin** [aws-amplify/docs#1897]
**Page**: [`/start/q/integration/android`](https://docs.amplify.aws/start/q/integration/android)

**Feedback**:

React Native walkthrough is good.

Android & iOS are lacking in documentation and I can find multiple pages that are outdated with misleading steps.

Examples:
https://docs.amplify.aws/start/getting-started/native_setup/q/integration/android
https://docs.amplify.aws/lib/project-setup/create-application/q/platform/android#n2-install-amplify-libraries

The React Native project you can walkthrough without trying to figure out additional steps in between. Can you do the same for Android & iOS?

**Comment by swaminator** [comment]
@jamesmalin could you help us with some specifics? What does React Native have that iOS and Android are missing in particular?
