### ISSUE TITLE
[Request] Increase visual distinction on legacy docs to prevent confusion

### ISSUE THREAD

**Issue by sw-yx** [aws-amplify/docs#1908]
**Is your feature request related to a problem? Please describe.**
Hi! i was helping [Donald Pipowitch](https://twitter.com/PipoPeperoni) with an issue and he got confused because we were literally not on the same page - he was on the Legacy docs and didn't know it. The only distinction is the latest/legacy toggle on the left:
![image](https://user-images.githubusercontent.com/6764957/83670104-3441db80-a605-11ea-995f-4850a19f5f85.png)

and it doesn't even show up on mobile (!) until you click the menu.

**Describe the solution you'd like**
add some warning banner and possibly a different color scheme to prevent confusion?

happy to help implement if you think its a good idea, should be an easy one

**Describe alternatives you've considered**
do nothing

**Comment by mauerbac** [comment]
Hi @sw-yx - our plans for latest vs Legacy docs are here -> https://github.com/aws-amplify/amplify-js/issues/3279#issuecomment-589909938 . does that help?

**Comment by sw-yx** [comment]
thanks! hmm. was that the right link? that link just talks about the new ui web components, not about docs design.

**Comment by mauerbac** [comment]
Yes, I spoke to @jordanranz - can you provide more context ?

**Comment by sw-yx** [comment]
@mauerbac that link https://github.com/aws-amplify/amplify-js/issues/3279#issuecomment-589909938 seems to be talking about the feature parity plan for latest **libraries** - whereas my issue here focuses on increasing visual distinction in the **docs** covering *both* "latest" and "legacy" to avoid user confusion when they search/browse our docs. Unless i missed something, i dont think that link is relevant to this issue?

**Comment by sw-yx** [comment]
still here

**Comment by sw-yx** [comment]
still here.
