### ISSUE TITLE
Error in the section "Ownership with create mutations"

### ISSUE THREAD

**Issue by UnleashedMind** [aws-amplify/docs#1910]
**Describe the bug**
In this section of the document: 
https://docs.amplify.aws/cli/graphql-transformer/directives#multiple-authorization-rules
The `editors` are only allowed to perform operations `update` and `read`
```graphql
type Draft @model
  @auth(rules: [
    # Defaults to use the "owner" field.
    { allow: owner },

    # Authorize the update mutation and both queries.
    { allow: owner, ownerField: "editors", operations: [update, read] }
  ]) {
  id: ID!
  title: String!
  content: String
  owner: String
  editors: [String]
}
```

The last mutation defined in this section of the document (copied below) for the above schema will return error instead of the data presented in the document, because the `editors` does not have `create` in its `operations`:

```graphql
mutation CreateDraft {
  createDraft(
    input: {
      title: "A new draft",
      editors: ["someuser@my-domain.com"],
      owner: null
    }
  ) {
    id
    title
    owner
    editors
  }
}
```
We need to either remove the last mutation from the document, or add `create` into the editor's `operations` array (which does not seem to be the intention of the schema design), to make the document coherent. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mauerbac** [comment]
Checked in with the team and there is a PR ready for this.
