### ISSUE TITLE
Improve Search

### ISSUE THREAD

**Issue by mauerbac** [aws-amplify/docs#1911]
Epic to improve search 

#1677 

- Search terms map to incorrect pages. ie. "queryfield" -> https://docs.amplify.aws/lib/datastore/data-access/q/platform/android#query-with-predicates

**Comment by swaminator** [comment]
https://github.com/aws-amplify/docs/issues/1941

**Comment by mauerbac** [comment]
Both issues in this epic are closed. Closing

**Comment by swaminator** [comment]
Reopening issue: we still need to provide a way for developers to be able to better find content. This is engineering work that @brene is driving.
