### ISSUE TITLE
[Feedback]Auth operations demo

### ISSUE THREAD

**Issue by scottkelso** [aws-amplify/docs#1921]
**Page**: [`/cli/graphql-transformer/directives`](https://docs.amplify.aws/cli/graphql-transformer/directives)

**Feedback**:

I am finding getting my head around the logic of auth operations difficult. Converting the permission tables into an interactive demo would be very handy to test/understand better the logic. Similar to Quasar and their https://quasar.dev/layout/grid/flex-playground.

**Comment by mauerbac** [comment]
Closing in favor of a larger epic #2017 . Thanks for the suggestion.
