### ISSUE TITLE
Redirect needed for https://docs.amplify.aws/lib/auth

### ISSUE THREAD

**Issue by jamesonwilliams** [aws-amplify/docs#1929]
**Describe the bug**
https://docs.amplify.aws/lib/auth/ yields a 404 page not found.

The "landing page" for Auth is actually at https://docs.amplify.aws/lib/auth/getting-started.

**To Reproduce**

1. Try to visit https://docs.amplify.aws/lib/auth/
2. Notice the 404

**Expected behavior**
https://docs.amplify.aws/lib/auth should be a usable link.

**Additional context**
I didn't check yet, but I assume this same issue exists for all categories.

**Comment by mauerbac** [comment]
Thanks @jamesonwilliams . Pinging our docs eng team - @harrysolovay

**Comment by jamesonwilliams** [comment]
Closing out some of my stale issues
