### ISSUE TITLE
Tutorial doesn't show where to set the API key

### ISSUE THREAD

**Issue by TylerSustare** [aws-amplify/docs#1936]
**Page**: [`/start/getting-started/data-model/q/integration/react`](https://docs.amplify.aws/start/getting-started/data-model/q/integration/react#create-a-graphql-api-and-database)

**Feedback**:

The app doesn't run locally because from what I can tell the API key isn't set anywhere in the instructions. I realize the API key pattern isn't really awesome and that the preferred way is to go Cognito, but it would have been nice to have the tutorial work the way it was presented. 

```
error creating todo: Error: No credentials
    at GraphQLAPIClass.<anonymous> (0.chunk.js:5857)
    at step (0.chunk.js:5639)
    at Object.next (0.chunk.js:5570)
    at fulfilled (0.chunk.js:5524) 
```

**Comment by swaminator** [comment]
@TylerSustare you should have created an API key right here in the tutorial: https://docs.amplify.aws/start/getting-started/data-model/q/integration/react#create-a-graphql-api-and-database

**Comment by TylerSustare** [comment]
Hi, @swaminator thank you, and I did. What do you do with the key once you create it?

**Comment by swaminator** [comment]
@TylerSustare the key is what you use to manage access to your API. Learn more here: https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/js

**Comment by TylerSustare** [comment]
That seems like a great thing to add to the tutorial.

**Comment by SJI-ParthaSarathi** [comment]
@TylerSustare I am facing the same issue!
I am using NextJS and GraphQL but problem is I have cloned it from another existing project and replicated baekend via Amplify CloudFormation template.

Now all the frontend and backend resources are working file on AWS Console but from Local system I can't run GraphQL operations. Which is throwing this error

`[WARN] 03:00.59 GraphQLAPI - ensure credentials error No Cognito Identity pool provided for unauthenticated access
Error: No credentials
    at GraphQLAPIClass.eval (webpack-internal:///./node_modules/@aws-amplify/api-graphql/lib-esm/GraphQLAPI.js:205)
    at step (webpack-internal:///./node_modules/@aws-amplify/api-graphql/lib-esm/GraphQLAPI.js:55)
    at Object.eval [as next] (webpack-internal:///./node_modules/@aws-amplify/api-graphql/lib-esm/GraphQLAPI.js:36)
    at fulfilled (webpack-internal:///./node_modules/@aws-amplify/api-graphql/lib-esm/GraphQLAPI.js:27)`

I have gone through the above Amplify docs provided by @swaminator but confused where to place API keys! 
Please guys help me out! :-(

**Comment by TylerSustare** [comment]
I'm not going to lie I've completely given up on Amplify because of stuff like this. AWS is obviously amazing but if I need something like Amplify I go right to Firebase and TODO use AWS if it turns into an actual product.

**Comment by emmby** [comment]
I too am unclear on how to use my api keys. The https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/js link provided by @swaminator does not discuss API keys.
