### ISSUE TITLE
Following the getting started gives me auth errors

### ISSUE THREAD

**Issue by TylerSustare** [aws-amplify/docs#1938]
**Page**: [`/start/q/integration/react`](https://docs.amplify.aws/start/getting-started/auth/q/integration/react)

**Feedback**:
```
1.chunk.js:302032 [ERROR] 42:42.431 AuthError - 
            Error: Amplify has not been configured correctly. 
            The configuration object is missing required auth properties. 
            Did you run `amplify push` after adding auth via `amplify add auth`?
            See https://aws-amplify.github.io/docs/js/authentication#amplify-project-setup for more information
```
I haven't done anything except what the tutorial mentioned. I ran `amplify push` after adding auth. This is the second time it happened after running `amplify auth remove`.
Sad panda.

**Comment by mauerbac** [comment]
hi @TylerSustare - i wasn't able to reproduce this. Can you share more about your environment ? Are you in our Discord server? I can help you get started there.

**Comment by TylerSustare** [comment]
hey @mauerbac I realized the issue 🤦‍♂️the code snippet in the previous step https://docs.amplify.aws/start/getting-started/data-model/q/integration/react#connect-frontend-to-api doesn't include `Amplify.configure(awsconfig);` so I'm not surprised when I blindly copy/pasta that it didn't work.

**Comment by TylerSustare** [comment]
@mauerbac I have the PR ☝️ to scratch my own itch if you want to take a look, or modify it in any way.

**Comment by swaminator** [comment]
@TylerSustare we ask users to import Amplify in the index.js here: https://docs.amplify.aws/start/getting-started/setup/q/integration/react#set-up-frontend

Prefer not to duplicate it in both places. Closing this, please re-open if you feel the need.
