### ISSUE TITLE
[Request] Separate search by language/platform to prevent accidental jumps

### ISSUE THREAD

**Issue by sw-yx** [aws-amplify/docs#1941]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/6764957/84196335-a10c1880-aad2-11ea-8410-59440dc5c745.png)

**Describe the solution you'd like**

some ideas:

1. offer a way to do "faceted search" eg. specify that you are only searching within js or android or cli or whatever
2. if there are undocumented flags with algolia that let the user filter within their own query, teach the user with a friendly popup
3. offer an "advanced search" UI

**Comment by mauerbac** [comment]
Thanks @sw-yx . Feedback makes sense. Essentially, you'd like to be able to search docs by library. Will move into a FR for our docs engineering team.

**Comment by sw-yx** [comment]
i have minimal algolia experience but i imagine they have sort of some advanced option to enable faceted search of some sort.

as another option i was just checking out the js sdk docs the other day. this is at least less frustrating bc of more control, even if it causes a page navigation away to the search interface.

![image](https://user-images.githubusercontent.com/6764957/84406426-15ae9680-ac3c-11ea-85f5-36e9830db756.png)

we could do worse than adopt something like that

**Comment by swaminator** [comment]
We should build an opinion on how we do search. If I am in the JS repo and search for 'sign in'. We should:
1. Return sign-in related search results specific to the JS repo (with a tag saying which category the page belongs to)
2. If no results are available tell the user that "no results found.. search all platforms". Clicking on search all platforms will then allow them to find content from other.

I also like what @sw-yx suggested. Here's an example of search done well: https://docs.airship.com/

cc @brene

**Comment by swaminator** [comment]
Tracking this feedback here.

**Comment by sw-yx** [comment]
(reach goal) make it easy to search github issues/discussion too :)

**Comment by sw-yx** [comment]
not entirely addressed but at least now the search shows all results.
