### ISSUE TITLE
[missing-page]

### ISSUE THREAD

**Issue by Sam31000** [aws-amplify/docs#1944]
**Page**: [`https://docs.amplify.aws/lib/push-notifications/overview/q/platform/js`](https://docs.amplify.aws/lib/push-notifications/overview/q/platform/js)

**Feedback**: "Push Notification" section of the amplify documentation is not available.

**Comment by Sam31000** [comment]
Thank you for the reply.

Thanks to you I figured out that my browser (BRAVE) didn't allow me to see this page. I got instead a 404 not found page, that's why I was disturbed : 
![image](https://user-images.githubusercontent.com/7100939/84484022-753b8f00-ac9a-11ea-9ad1-ebe900af44d7.png)

I'm able to see the page with my browser adblocker disabled. Thank you.

**Comment by tjleing** [comment]
Should be fixed now due to #3110 being merged in!  Please reopen if the problem persists 😄
