### ISSUE TITLE
Documentation on JS GraphQL List filtering

### ISSUE THREAD

**Issue by TrekSoft** [aws-amplify/docs#1959]
I didn't see any documentation on how to filter on a JavaScript GraphQL list query. Did I just miss something?

**Comment by mauerbac** [comment]
Thanks @TrekSoft. Doesn't appear to be in the docs. This looks pretty recent and might help -> https://stackoverflow.com/questions/60853978/how-to-filter-list-queries-with-and-or-operators-aws-amplify-javascript-graphql . Shared with the JS team to get feedback around adding.

**Comment by TrekSoft** [comment]
Thanks - yeah I stumbled across that as well but seems like something pretty basic we should have documented for customers.

**Comment by sammartinez** [comment]
I believe this is what you are looking for: https://docs.amplify.aws/lib/graphqlapi/query-data/q/platform/js#compound-filters Let me know if it is not @TrekSoft :)
