### ISSUE TITLE
[missing-page]

### ISSUE THREAD

**Issue by melsaq** [aws-amplify/docs#1960]
**Page**: [`https://docs.amplify.aws/lib/getting-started/setup/q/platform/android`](https://docs.amplify.aws/lib/getting-started/setup/q/platform/android)

**Feedback**:

**Comment by jamesonwilliams** [comment]
The #4 search result for:

https://www.google.com/search?q=android+getting+started+amplify

Is a link to:

https://aws-amplify.github.io/docs/android/start?ref=amplify-android-btn

That link redirects to https://docs.amplify.aws/lib/getting-started/setup/q/platform/android

Which I have confirmed returns a 404 as @melsaq notes.

I suspect this redirect should point to https://docs.amplify.aws/start/getting-started/setup/q/integration/android , instead.

**Comment by mauerbac** [comment]
Thanks for reporting @melsaq. Appreciate reproducing @jamesonwilliams. @harrysolovay, is this something you could help with?

**Comment by harrysolovay** [comment]
Yep––this does in fact seem to be a bug! Will investigate.

**Comment by harrysolovay** [comment]
Seems that we have an incorrect redirect from the GitHub-hosted docs (legacy). Will investigate.

**Comment by mauerbac** [comment]
Thanks @harrysolovay !

**Comment by mauerbac** [comment]
Just verified this is fixed. @brene merged a PR that resolves this. Thanks
