### ISSUE TITLE
Provide documentation on how to use Amplify with existing resources  

### ISSUE THREAD

**Issue by mauerbac** [aws-amplify/docs#1966]
As a developer who is previously using underlying Amplify service components, how can I use the CLI to build and manage my Amplify project.  How do I manage my existing backend?

Similar to this [JS authentication guide](https://docs.amplify.aws/lib/auth/start/q/platform/js). 

This can be achieved through 1) a central how to use existing resource guide per category 2) replicate the above JS Auth guide per category and framework

**Comment by sw-yx** [comment]
i would like this too.
