### ISSUE TITLE
[missing-page] Analytics Auto-track sessions

### ISSUE THREAD

**Issue by heitorlessa** [aws-amplify/docs#1967]
Searching for Analytics and selecting the first result leads to a missing page

![image](https://user-images.githubusercontent.com/3340292/84804942-6129c180-affb-11ea-8d27-7cd2b2debdb9.png)

**Comment by mauerbac** [comment]
hey @heitorlessa - the first result leads me here https://docs.amplify.aws/lib/analytics/autotrack/q/platform/android. I'm able to load the page. Can you share the URL that isn't loading. thank you

**Comment by heitorlessa** [comment]
Hey Matt - Feel free to close it. Apparently there was something bogus in
both of my browsers.
