### ISSUE TITLE
[Request] API (REST) - Document what is `path`, or possibly change signature of `API.get`

### ISSUE THREAD

**Issue by sw-yx** [aws-amplify/docs#1969]
> Note - everything below is thinking out loud from the POV of a new user

**Is your feature request related to a problem? Please describe.**

the [docs for REST API fetching](https://docs.amplify.aws/lib/restapi/fetch/q/platform/js) says "To invoke an endpoint, you need to set `apiName`, `path` and `headers` parameters".

let's say I know what my `apiName` is, I know what `headers` are.

-  what is `path` and where do I get it? 
- if i forgot my `path`, where in the console and where in the CLI should I look to retrieve it?  (i tried looking; no idea. do i dig through the json blobs in `/amplify`? why do i have to do that?)
- when should my `path` be the same as `apiName`, when should it not be the same?
- if `path` is always more important (as it is in webdev outside of AWS/Amplify), why do i have to specify `apiName` at all? 

All this is unclear to me when I read the docs.

**Describe the solution you'd like**

better document what `path` is! 

additional points of user confusion - accidentally using function names and api names instead of path. maybe we can implement "did you mean...." error messages in dev mode.

i'm filing this to represent sincere user confusion, as these are Amplify-isms that are not reflected on other platforms, and therefore will surprise users who read these docs

**Comment by mauerbac** [comment]
Thank you @sw-yx . This is quite clear. Will move to JS

**Comment by sw-yx** [comment]
happy to hop on a call if someone wants my help working this one out, i bet the docs are easy but there may be some api design that needs to be explained to me/improved

**Comment by mauerbac** [comment]
Need to work out with @sammartinez / @swaminator who will update this. Probably makes more sense for you to chat with them :)

**Comment by sw-yx** [comment]
tagging @dabit3

**Comment by dabit3** [comment]
+1 on this.

I think that most developers are used to working with APIs in this way and, even though it will be more verbose, it will provide an alternate and in my opinion better overall DX.

Alternately if there is a way to offer either API Name or API path as an option for the first argument, that would also make sense.

**Comment by mauerbac** [comment]
Going to resolve this and will sync internally. Let's use the FR you opened on CLI moving forward
