### ISSUE TITLE
missing docs for auth interview with fb login

### ISSUE THREAD

**Issue by cyrfer** [aws-amplify/docs#1970]
**Which Category is your question related to?**
Auth

**Amplify CLI Version** 
4.21.3

**What AWS Services are you utilizing?**
Cognito?

**Provide additional details e.g. code snippets**
I ran the command "amplify auth add" and I chose the FB login. I am trying to answer the questions, but I cannot find documentation about what value I should use for one step,

*Enter the URL that your users will be redirected to upon account confirmation*

What am I supposed to answer with?

**Comment by mauerbac** [comment]
Developer is looking for more details around social login with Facebook when using the CLI. He isn't sure what URL to use as the redirect URL. 

@cyrfer - we will make this more clear. in the meantime, this guide explains it well -> https://dev.to/dabit3/the-complete-guide-to-user-authentication-with-the-amplify-framework-2inh

**Comment by mauerbac** [comment]
@cyrfer - this should now be added here https://docs.amplify.aws/lib/auth/social/q/platform/js#setup-social-provider. Hope Nader's guide helped as well.

**Comment by cyrfer** [comment]
@mauerbac Unfortunately I do not see the question I faced when using the CLI addressed in that article.

> Enter the URL that your users will be redirected to upon account confirmation

**Comment by mauerbac** [comment]
I see - can you copy/paste the options in the CLI you chose after `amplify add auth` ? I would believe that is the URL on your end (ie /welcome , /dashboard)  . Are you getting an error when you try yourappdomain.com/hello ?
