### ISSUE TITLE
nodeJS version with AWS Lambda 

### ISSUE THREAD

**Issue by varmeEqualsthis** [aws-amplify/docs#1978]
**Page**: [`/start/getting-started/auth/q/integration/react`](https://docs.amplify.aws/start/getting-started/auth/q/integration/react)

**Feedback**:

Thank you for the excellent documentation. Looks like there is a problem adding auth using "amplify add auth". It is still using nodeJS v8.x and AWS lambda won't support this version. So I had to update the version in my cloud formation template manually.

**Comment by varmeEqualsthis** [comment]
Updating to the latest amplify cli solved the problem.

**Comment by mauerbac** [comment]
Great
