### ISSUE TITLE
Updated codegen docs describing query customization

### ISSUE THREAD

**Issue by yuth** [aws-amplify/docs#199]
Update amplify codgen doc detailing how users can just use generation of types without generating statements

**Comment by danielrobleM** [comment]
Any updates ?

**Comment by jaredmessenger** [comment]
I believe this has been fixed. It's not an ideal solution, but you can edit the `queries.graphql` file and generate the API without the statements stomping on your queries' changes.
```
amplify codegen types [--nodownload]
```
https://aws-amplify.github.io/docs/cli/codegen
