### ISSUE TITLE
[missing-page] Push Notifications

### ISSUE THREAD

**Issue by skypper** [aws-amplify/docs#1991]
**Page**: [`https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/js`](https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/js)

**Feedback**: 

I clicked on the Push Notifications link [here](https://docs.amplify.aws/start/getting-started/nextsteps/q/integration/react) and lead me to a non-existent page.

**Comment by mauerbac** [comment]
hey @skypper - looks like you are looking for Android? I just addressed this here -> https://github.com/aws-amplify/docs/issues/2006
