### ISSUE TITLE
[Docs] Angular "Getting Started > Next Steps" page is out of date

### ISSUE THREAD

**Issue by sw-yx** [aws-amplify/docs#1995]
**Page**: [`/start/getting-started/nextsteps/q/integration/angular`](https://docs.amplify.aws/start/getting-started/nextsteps/q/integration/angular)

**Feedback**:

from customer: https://github.com/aws-amplify/amplify-js/discussions/6112#discussioncomment-28170

this tutorial still references `aws-amplify-angular` when the rest of the tutorial has been updated to `@aws-amplify/ui-angular`.

the customer has given some sample code we can adapt.

**Comment by mauerbac** [comment]
Thanks for reporting @sw-yx . WIll get this prioritized.

**Comment by ericclemmons** [comment]
The references to `aws-amplify-angular` appear to be updated in the Angular docs linked above.

Unless there's a specific action that still needs to be taken, I'm going to close this out.
