### ISSUE TITLE
[Feedback] Auth UI support Korean language?

### ISSUE THREAD

**Issue by choipd** [aws-amplify/docs#2001]
**Page**: [`/ui/q/framework/react`](https://docs.amplify.aws/ui/q/framework/react)

**Feedback**:

Hello I would like to know if amplify authentication ui supports international languages out of box or any chance to customize default language to Korean.

**Comment by mauerbac** [comment]
Hello, this is possible using the utility in out components:
https://docs.amplify.aws/lib/utilities/i18n/q/platform/js. Hope that helps!

**Comment by mauerbac** [comment]
This might help as well https://github.com/aws-amplify/amplify-js/blob/main/packages/amplify-ui-components/src/common/Translations.ts
