### ISSUE TITLE
[Feedback]Issues with tutorial

### ISSUE THREAD

**Issue by jayy-mize** [aws-amplify/docs#2003]
**Page**: [`/start/q/integration/angular`](https://docs.amplify.aws/start/q/integration/angular)

**Feedback**:

Following tutorial just fine up until "amplify push". After following all the prompts, always getting an error on the creation of the API.

`CREATE_FAILED      apimyapi                           AWS::CloudFormation::Stack Tue Jun 23 2020 10:25:26 GMT-0500 (Central Daylight Time) Parameters: [S3DeploymentRootKey, S3DeploymentBucket] must have values`

Looked inside my backend/api/myapi/build/parameters.json and the values for S3DeploymentBucket and also S3DeploymentRootKey have values set. 

Why is amplify push not picking up on these?

Also, after amplify push, there are a lot more prompts that could use some clarification in the tutorial about what is really going on. Spamming the "Y" key does not help me learn at all what is going on.

**Comment by mauerbac** [comment]
hi @jayy-mize - just to confirm, you are using Angular?

**Comment by sw-yx** [comment]
agnostic of framework, the points about error message descriptiveness, and teachability of the prompting are well taken.

**Comment by mauerbac** [comment]
Closing this as it's outdated and related to the CLI tool
