### ISSUE TITLE
[Feedback] Handling push notification

### ISSUE THREAD

**Issue by baole** [aws-amplify/docs#2006]
**Page**: [`/lib/q/platform/android`](https://docs.amplify.aws/lib/q/platform/android)

**Feedback**:

I don't see any documents which relates to handle push notification for Android

**Comment by mauerbac** [comment]
@baole - Hello, we do not have a push notification category for iOS or Android yet. This should help for now: https://docs.amplify.aws/sdk/push-notifications/getting-started/q/platform/android
