### ISSUE TITLE
[Feedback]REST

### ISSUE THREAD

**Issue by tomreineke** [aws-amplify/docs#2013]
**Page**: [`/start/q/integration/angular`](https://docs.amplify.aws/start/q/integration/angular)

**Feedback**:
I'd love a page where you describe the integration of a Java backend (e. g. spring-boot).

**Comment by mauerbac** [comment]
hi - @tomreineke - we have resources here -> https://github.com/dabit3/awesome-aws-amplify . Our [Discord](www.discord.gg/amplify) also has different resources. I can put this down but we can't also get to specific frontend framework with language specific backends.
