### ISSUE TITLE
[Feedback]Docs Needs little Improvement 

### ISSUE THREAD

**Issue by tewarig** [aws-amplify/docs#2014]
**Page**: [`/start/getting-started/nextsteps/q/integration/react-native`](https://docs.amplify.aws/start/getting-started/nextsteps/q/integration/react-native)

**Feedback**:
I like how each and everything is explained. But it would be great if more examples of projects were given, Like the todo list app. 
Also, it was great to see how AWS-amplify is supporting React-Native.

**Comment by mauerbac** [comment]
Thanks for the feedback @tewarig . I'll pass this to the team.
