### ISSUE TITLE
Ensure Ionic 5 is supported

### ISSUE THREAD

**Issue by mauerbac** [aws-amplify/docs#2018]
* Ensure Amplify supports Ionic 5 properly #1716
* Ensure getting started guide works as expected with Ionic 5 #1224

**Comment by mauerbac** [comment]
cc @jordanranz

**Comment by sammartinez** [comment]
For this one @mauerbac, we need to do a SPIKE in order to validate that Ionic 5 will work properly.

**Comment by mauerbac** [comment]
Issues in epic are closed

**Comment by letsbelopez** [comment]
@mauerbac If this is still open, I can do a SPIKE to validate. Is there a specification for the SPIKE and can I do it, or does it have to be done by an org member?

**Comment by mauerbac** [comment]
@letsbelopez - Hello! Thanks for offering to help. Anyone can help out here. We just wanted to check that if you follow our ionic getting started guides Ionic 5 is supported.

**Comment by letsbelopez** [comment]
> @letsbelopez - Hello! Thanks for offering to help. Anyone can help out here. We just wanted to check that if you follow our ionic getting started guides Ionic 5 is supported.

I went through the ionic getting started guide. There were no issues with setting up amplify, graphql api, and hosting the front end app. I think you can close this issue. I can give you the finished getting started app and the front end URL to confirm if you'd like.
