### ISSUE TITLE
[Feedback]AppClientSecret should not be provided to iOS or Android apps

### ISSUE THREAD

**Issue by jpangburn** [aws-amplify/docs#2021]
**Page**: [`/lib/graphqlapi/authz/q/platform/ios`](https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/ios)

**Feedback**:

In the iOS and Android pages for configuring authorization modes, under the "Amazon Cognito User Pools" section, it talks about putting the following configuration into amplifyconfiguration.json:

>     "awsCognitoAuthPlugin": {
>         "CognitoUserPool": {
>             "Default": {
>                 "PoolId": "[POOL-ID]",
>                 "AppClientId": "[APP-CLIENT-ID]",
>                 "AppClientSecret": "[APP-CLIENT-SECRET]",
>                 "Region": "[REGION]"
>             }
>         }
>     }

I'm new to Cognito but my understanding for providing a secret is that it gives trusted machine->machine access.  This seems like a really bad idea for providing inside of an iOS or Android app, as anyone can easily open these app packages up and read config files like these.  Then a bad actor would have your pool's app client id and secret.

The javascript setup for web pages has no such thing, I believe it's only holding the pool id and app client id.  In the documentation for [amplifyconfiguration.json](https://docs.amplify.aws/cli/usage/files#amplifyconfigurationjson-file) it is acknowledged that it is for "non-sensitive" information.  So why is there a "secret" being stored in it?  I think there should just be a pool id and an app client id for unauthenticated actions like signing up a new user, forgot password, etc.

**Comment by kuabhish** [comment]
I am building an Android application in Java and using the **Cognito User Pool** [(using this demo)](https://github.com/awslabs/aws-sdk-android-samples/tree/main/AmazonCognitoYourUserPoolsDemo) to generate **User Session Tokens** to authenticate the Rest Api calls.

In the  [sample repo](https://github.com/awslabs/aws-sdk-android-samples/tree/main/AmazonCognitoYourUserPoolsDemo) the client secret and client id  is written in the the AppHelper class. 

So, my question is : What is the best way to hide the client id?

**Comment by jpignata** [comment]
@kuabhish I'd only include the Client ID and generate an App Client with a secret.

**Comment by jpignata** [comment]
Thank you for reporting your concern. This usage of the app client with a secret doesn’t present a security issue. An app client created with or without a secret provides the same level of access. We’ve [updated our documentation](https://github.com/aws-amplify/docs/pull/2612) to clarify this.
