### ISSUE TITLE
[Feedback]@Connection limit set to 10 by default

### ISSUE THREAD

**Issue by scottkelso** [aws-amplify/docs#2025]
**Page**: [`/cli`](https://docs.amplify.aws/cli)

**Feedback**:
No mention of @Connection limit set to 10 by default

_**Please ignore this is I have simply failed to find this information in the documentation.**_

A small thing but I struggled for a while wondering why one of my queries was only returning 10 items instead of the documented default 100. I only figured it out after reading this [StackOverflow](https://stackoverflow.com/questions/55717302/i-need-to-extend-the-10-item-limit-in-connection-responses) post that said that nested `@connection` parameters are limited to 10. Could this be included somewhere, maybe in the [CLI > GraphQL > Directives > @connection](https://docs.amplify.aws/cli/graphql-transformer/directives#connection) section?

Thanks

**Comment by scottkelso** [comment]
If I'm not mistaking I think this is still valid.

**Comment by yuth** [comment]
The default limit has been increased to [100 recently](https://github.com/aws-amplify/amplify-cli/blob/1a68c4d589e2101357dec4e980719fc547964e23/packages/graphql-transformer-common/src/ResourceConstants.ts#L4) and this change was released in Amplify CLI v 4.19.0 which was released on May 8th 2020. 

Is your connected field protected with `@auth` directive? If it indeed is protected, then there the filtering of the record happens after fetching those 100 records.
