### ISSUE TITLE
[Feedback]Documentation Lacking

### ISSUE THREAD

**Issue by RobertGardner** [aws-amplify/docs#2044]
**Page**: [`/ui/auth/authenticator/q/framework/react`](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#withauthenticator)

**Feedback**:

Documentation on how to use the new Authenticator components is woefully inadequate and doesn't come close to providing enough information to write serious software with it. The examples get you started, but when looking for simple details like what types of authstates are available, when it transitions between them, and so on, there's nothing there. I even spent several hours digging through the source code on Github. I was only able to get something working after reading Github bugs and Stackoverflow questions/answers.

**Comment by mauerbac** [comment]
Sorry to hear this and for the delay @RobertGardner . I wish I got to this sooner. We've made updates so I assume you've moved passed this. Please create a new issue with feedback and I'll get on it asap .
