### ISSUE TITLE
Documentation for Amplify Container in Samples repo 

### ISSUE THREAD

**Issue by sammartinez** [aws-amplify/docs#2050]
**Is your feature request related to a problem? Please describe.**
Within our [Samples repo](https://github.com/aws-amplify/amplify-js-samples/blob/main/samples/react/auth/authenticator/README.md) we callout usage of the `AmplifyContainer` component. We don't have full documentation of this presentational component and getting some ask from customers to have it.  

**Describe the solution you'd like**
Update our documentation with the `AmplifyContainer` component

**Comment by ahouck** [comment]
Was there an update? The documentation at https://docs.amplify.aws does not contain a reference to `AmplifyContainer`
