### ISSUE TITLE
[Guides][JS] Create entry in DynamoDB after user post-confirmation

### ISSUE THREAD

**Issue by khalidbourhaba** [aws-amplify/docs#2054]
**Is your feature request related to a problem? Please describe.**
This question was asked many times by the members of the Discord community.

**Describe the solution you'd like**
I would like to write up a guide to demonstrate how to add an entry in DynamoDB with user info, using a post-confirmation trigger.

**Additional context**
The guide is to be integrated to "Functions" part in the [JS guides](https://docs.amplify.aws/guides/q/platform/js)

**Comment by khalidbourhaba** [comment]
Hey @gsans ! What do you think about this ?

**Comment by gsans** [comment]
Sounds cool yeah 😃

**Comment by mauerbac** [comment]
Thanks @khalidbourhaba . Sounds like a great addition to the new guide section.

**Comment by sw-yx** [comment]
cosign!! would love to feature this too!

**Comment by dabit3** [comment]
Thanks @khalidbourhaba , great idea.

**Comment by sw-yx** [comment]
not stale

**Comment by gsans** [comment]
I'm following with Khalid and done a review already over the weekend.

**Comment by khalidbourhaba** [comment]
PR : https://github.com/aws-amplify/docs/pull/2188

**Comment by khalidbourhaba** [comment]
Closing
