### ISSUE TITLE
error in package.json file ?

### ISSUE THREAD

**Issue by robmoores** [aws-amplify/docs#2056]
**Page**: https://docs.amplify.aws/start/getting-started/setup/q/integration/js#create-a-new-javascript-app

**Feedback**:

"dependencies": {
    "aws-amplify": "latest",
  },

I think the , after the word "latest" above - the JSON that you have to paste into package.josn - should not be there ...
Cheers
Rob

**Comment by mauerbac** [comment]
Thanks @robmoores . You are correct. That comma has been removed.
