### ISSUE TITLE
[Feedback]Minor Bug in Amplify Tutorial

### ISSUE THREAD

**Issue by sherwinlu** [aws-amplify/docs#2059]
**Page**: [`/start/getting-started/setup/q/integration/js`](https://docs.amplify.aws/start/getting-started/setup/q/integration/js)

**Feedback**:

When I ran the npm install command, it gave me the following error:

```
npm ERR! code EJSONPARSE
npm ERR! file /Users/sherwin/dev/aws/amplify-js-app/package.json
npm ERR! JSON.parse Failed to parse json
npm ERR! JSON.parse Unexpected token } in JSON at position 150 while parsing near '...plify": "latest",
npm ERR! JSON.parse   },
npm ERR! JSON.parse   "devDependencie...'
npm ERR! JSON.parse Failed to parse package.json data.
npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.
```

I'm running:

```
➜  amplify-js-app npm -v
6.14.5
➜  amplify-js-app node -v
v12.18.2
```

This is because in your example, you have this line:

`"aws-amplify": "latest",`

The `,` at the end is what's causing the command to fail.

**Comment by mauerbac** [comment]
This is resolved. Thanks @sherwinlu for reporting!
