### ISSUE TITLE
[Feedback]Invalid Project Name in React Tutorial

### ISSUE THREAD

**Issue by sherwinlu** [aws-amplify/docs#2061]
**Page**: [`/start/q/integration/js`](https://docs.amplify.aws/start/q/integration/js)

**Feedback**:

In the tutorial, it's showing for the name of the project, `react-amplified`, but the project name complains about the **-** in it.

**Comment by sw-yx** [comment]
not sure i understand. what is the complaint?

**Comment by mauerbac** [comment]
Hi @sherwinlu - I was unable to reproduce your issue. If you need help, please reach out in our Discord channel (discord.gg/amplify).
