### ISSUE TITLE
[Feedback] missing how to sign out from social  web UI 

### ISSUE THREAD

**Issue by m-aljammali-inkerz** [aws-amplify/docs#2069]
**Page**: [`/lib/auth/social_signin_web_ui/q/platform/android`](https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/android)

**Page**: [`/lib/auth/signOut/q/platform/android`](https://docs.amplify.aws/lib/auth/signOut/q/platform/android)

**Feedback**:

I am unable to find a comparable option to "invalidateTokens(true)" which exist in AWSMobile API

Sign Out from HostedUI
```
AWSMobileClient.getInstance().signOut(SignOutOptions.builder().invalidateTokens(true).build(), new Callback<Void>() {
    @Override
    public void onResult(Void result) {
        Log.d(TAG, "onResult: ");
    }

    @Override
    public void onError(Exception e) {
        Log.e(TAG, "onError: ", e);
    }
}); 
```

without this option the signout is pointless. when trying to sign in again you are not given the option to choose between your google accounts and automatically logged in with the previous logged in account.

**Comment by mauerbac** [comment]
cc @jpignata, can you take a look here?

**Comment by jpignata** [comment]
@m-aljammali-inkerz Looks like we call `invalidateTokens(true)` automatically [here](https://github.com/aws-amplify/amplify-android/blob/3b09af4516c508da62aed5b14f681e7cf5dbc6ba/aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java#L782). Let me know if you have any follow up questions or if I missed your point.
