### ISSUE TITLE
Algolia dropdown not usable

### ISSUE THREAD

**Issue by CanRau** [aws-amplify/docs#207]
**Describe the bug**
The items in the algolia search dropdown are cropped/clipped and therefore not readable

**To Reproduce**
1. Go to https://aws-amplify.github.io/
2. Type something in the search field in the upper right
3. Wait for the suggestions dropdown

**Expected behavior**
Readable links

**Screenshots**
![bildschirmfoto 2018-11-17 um 07 57 08](https://user-images.githubusercontent.com/5196971/48661380-e8d5d580-ea3e-11e8-966e-204d9f7d5d06.png)

**Desktop (please complete the following information):**
 - OS: macOS Sierra
 - Browser: Chrome
 - Version: 70.0.3538.102

**Comment by stephenhuh** [comment]
same issue here on Chrome

**Comment by muellerfr** [comment]
I am taking a look.

**Comment by muellerfr** [comment]
Hello @CanRau and @stephenhuh,

the issue has been fixed. Please reopen the issue if you still see it.

**Comment by CanRau** [comment]
seems to work 💯 👍
