### ISSUE TITLE
Analytics Location must be provided by user

### ISSUE THREAD

**Issue by ohlr** [aws-amplify/docs#2070]
When deciding for Amplify I believed (from looking at pinpoint) that pinpoint captures location based on IP-Address automatically (like GA).

[Obviously](https://github.com/aws-amplify/amplify-js/issues/6190
) that's not the case.

Please extend the current docs in that regard.

**Comment by mauerbac** [comment]
@ohlr - thanks for calling this out. Where would you want this to be added? Are you interested in submitting a PR to add it :)

**Comment by ohlr** [comment]
https://docs.amplify.aws/lib/analytics/autotrack/q/platform/js

**Comment by offlineprogrammer** [comment]
Closed with the PR 4235
