### ISSUE TITLE
[Auth] Ambiguous heading 'Social sign in with web UI' in Android and iOS auth documentation

### ISSUE THREAD

**Issue by secretshardul** [aws-amplify/docs#2072]
**Describe the bug**
The heading 'Social sign in with web UI' is ambiguous. It could imply any of the two:

1. **Cognito's hosted login screen** with Facebook/Google login enabled
    ![image](https://user-images.githubusercontent.com/49580849/86814656-5795f580-c09f-11ea-8562-43059781a88f.png)

2. **Web based login provided by Google or Facebook**: This is the right option.
    ![image](https://user-images.githubusercontent.com/49580849/86814686-61b7f400-c09f-11ea-8936-5b7ccf0396a4.png)

To compound the matter:
1. This heading 'Social sign in with web UI' immediately follows 'Sign in with web UI'.
    ![image](https://user-images.githubusercontent.com/49580849/86815218-06d2cc80-c0a0-11ea-800b-8c09859e8edf.png)

2. Javascript documentation uses a different heading- **Social sign-in (OAuth)**.
    ![image](https://user-images.githubusercontent.com/49580849/86815290-1baf6000-c0a0-11ea-9fa7-64b6f27890dc.png)

3. Documentation doesn't provide screenshots on the end result.

**To Reproduce**
[Visit documentation.](https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/android)

**Expected behavior**
Some suggestions:
1. Use the same heading in Javascript documentation- **Social sign-in (OAuth)**
2. Add screenshot/video to the documentation. You could use my FB login screenshot.
3. A disclaimer box on web based social login: Amplify social login for Android, iOS and React Native is web based and not native SDK based. Users are redirected to the social provider's web page to complete auth. This may not be suitable for all use cases so should be clearly conveyed by the documentation.

**Comment by mauerbac** [comment]
Thanks @secretshardul - I think social sign-in is referring to social providers like Facebook/Google. I do see that it could be clearer. @dabit3 - what's your feedback here?
