### ISSUE TITLE
[Feedback]TYPO in package.json contents

### ISSUE THREAD

**Issue by harish-lendup** [aws-amplify/docs#2073]
**Page**: [`/start/getting-started/setup/q/integration/js`](https://docs.amplify.aws/start/getting-started/setup/q/integration/js)

**Feedback**:

Type 
"aws-amplify": "latest",
remove the additional comma otherwise you will get 

npm ERR! code EJSONPARSE
npm ERR! file /Users/harishseshadri/dev/amplify-js-app/package.json
npm ERR! JSON.parse Failed to parse json
npm ERR! JSON.parse Unexpected token } in JSON at position 150 while parsing near '...plify": "latest",
npm ERR! JSON.parse   },
npm ERR! JSON.parse   "devDependencie...'
npm ERR! JSON.parse Failed to parse package.json data.
npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.

**Comment by mauerbac** [comment]
This has been fixed. Thank you @harish-lendup
