### ISSUE TITLE
iOS "Project Setup" documentation should be updated to cover SwiftUI Apps using @main

### ISSUE THREAD

**Issue by jtbergman** [aws-amplify/docs#2075]
**Problem**
I recently started learning Amplify for use in SwiftUI apps. The [documentation](https://docs.amplify.aws/lib/project-setup/create-application/q/platform/ios) shows how to set up a project using the `UIApplicationDelegate` approach. In iOS 14, there is the `App` approach using only SwiftUI. It is not clear how to call `Amplify.configure()` when using this approach.

**Solution**
The docs could be updated to cover both types of apps. This doesn't require a new set of docs, but just a callout on how to add an app delegate to SwiftUI only apps. For example, [this tutorial](https://www.hackingwithswift.com/quick-start/swiftui/how-to-add-an-appdelegate-to-a-swiftui-app) shows how to add an app delegate. Once that is done nothing needs changed.

**Alternatives**
N/A

**Additional context**
The solution I found was to create a file named AppDelegate with 
```swift 
import Foundation
import UIKit
import Amplify

class AppDelegate: NSObject, UIApplicationDelegate {
    func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil
    ) -> Bool {
        do {
            Amplify.Logging.logLevel = .verbose
            try Amplify.configure()
        } catch {
            print("Amplify could not be configured: \(error)")
        }
        return true
    }
}
```

Then update the `App` to the following 
```swift 
import SwiftUI

@main
struct AuthenticationApp: App {
    @UIApplicationDelegateAdaptor(AppDelegate.self) var appDelegate
    
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
```

I realize that this is a small change, but with SwiftUI Apps being so new, it was not immediately clear that an `AppDelegate` could be added.

**Comment by lawmicha** [comment]
Hi @jtbergman, thanks for pointing this out, I added something similar over in https://github.com/aws-amplify/docs/pull/2916 addressing the same issue from another developer.
