### ISSUE TITLE
DataStore limitations

### ISSUE THREAD

**Issue by lenarmazitov** [aws-amplify/docs#2077]
Currently there are no limitations noted in DataStore documentation.
What will happen with Sync operation when DataStore attached to huge amount documents table 100.000.000+?
How much will it cost if you have 1 million users and each tries to sync 100 million documents table?  etc.

I know that DataStore could evolve but it is very important to add notes about currently limitations

**Comment by mauerbac** [comment]
@iartemiev , @ArkamJ - could you help here?

**Comment by mauerbac** [comment]
hi @lenarmazitov, thanks for reaching out. 

It sounds like you are looking for a clear section that outlines limitations of DataStore. That makes sense. In the meantime, does this help in the section "The Sync Engine will run a GraphQL..." https://docs.amplify.aws/lib/datastore/how-it-works/q/platform/js#sync-data-to-cloud . 

Does that help. Flagging this as a feature request for additional documentation.

**Comment by sammartinez** [comment]
@mauerbac or @medelman17, this does seem to be more of a discussion question more so than anything. @lenarmazitov correct me if im wrong but are you looking for more of an understanding on cost base on your use case? Please let us know.
