### ISSUE TITLE
[Feedback] Extra comma in JS Getting Started Guide --> Build Failure

### ISSUE THREAD

**Issue by kkbava** [aws-amplify/docs#2078]
**Page**: [`/start/getting-started/setup/q/integration/js`](https://docs.amplify.aws/start/getting-started/setup/q/integration/js)

**Feedback**:

https://docs.amplify.aws/start/getting-started/setup/q/integration/js#create-a-new-javascript-app contains lines to be added into package.json but has an extra comma at end of line 6 ( "latest",) - that results in error when I type npm install
I removed in my local copy and moved forward

**Comment by jamesonwilliams** [comment]
@kkbava https://github.com/aws-amplify/docs/pull/2083/files
