### ISSUE TITLE
[Feedback] It's small Typographical error :)

### ISSUE THREAD

**Issue by kobusan** [aws-amplify/docs#2079]
**Page**: [`/lib/auth/social/q/platform/js`](https://docs.amplify.aws/lib/auth/social/q/platform/js#full-samples)

**Feedback**:

In Full Samples
at Line 42
```diff
-        <button obClick={() => Auth.federatedSignIn()}>Federated Sign In</button>
+        <button onClick={() => Auth.federatedSignIn()}>Federated Sign In</button>
```

Thanks !

**Comment by sammartinez** [comment]
Thanks for reporting this issue, this has been resolved and now live on the site
