### ISSUE TITLE
[Feedback] Is REST API docs page out of date?

### ISSUE THREAD

**Issue by ffxsam** [aws-amplify/docs#2084]
**Page**: [`/lib/restapi/getting-started/q/platform/js`](https://docs.amplify.aws/lib/restapi/getting-started/q/platform/js)

**Feedback**:

It says to `import API from '@aws-amplify/api'`, but in the source code I see this:

```js
/**
 * @deprecated
 * Use RestApi or GraphQLAPI to reduce your application bundle size
 * Export Cloud Logic APIs
 */
```

So are we to use `import RestAPI from '@aws-amplify/api-rest` now?

**Comment by mauerbac** [comment]
hi @ffxsam - Sorry for the delay! I believe this has been updated?

**Comment by ffxsam** [comment]
I still see it at the bottom of the page:

<img width="727" alt="image" src="https://user-images.githubusercontent.com/12532733/93137732-92ba3380-f6a3-11ea-850e-cdef855cbe12.png">

**Comment by mauerbac** [comment]
Following up and looks updated
