### ISSUE TITLE
[Feedback] Too SwiftUI centric

### ISSUE THREAD

**Issue by SMK-DP** [aws-amplify/docs#2087]
**Page**: [`/start/q/integration/ios`](https://docs.amplify.aws/start/q/integration/ios)

**Feedback**:

A somewhat anecdotal thought:

The above link points to some nice useful docs that very much are **exclusively** focused on using Amplify in SwiftUI. But a significant number of app developers have not actively switching to SwiftUI yet. The reasons for this are everything from training, business needs, to backwards compatibility and available time. In a lot of cases, they are still learning the huge Swift ecosystem that is very much rooted in storyboard/programmatic UI (that will be around for a long while to go yet). 

While it is kind of obvious how to extrapolate into the other paradigm (if you have spent enough time in that world), it would be good if the docs / examples considered that huge base. Not every reader will be an iOS veteran who can easily move between the two AND learn Amplify at the same time.

**Comment by mauerbac** [comment]
hi @SMK-DP - thank you so much for taking the time to provide us this feedback. I just passed this to our iOS engineering lead. They have ack'ed this feedback so going to close this out. Please continue to provide feedback on this forum!
