### ISSUE TITLE
TOTP Setup doesn't work if Cognito Pool has remember devices

### ISSUE THREAD

**Issue by BDNilsson** [aws-amplify/docs#2093]
Posted this in the wrong section please delete.

**Describe the bug**
If a cognito pool has settings to remember a device (opt-in or always) the login fails when setting up MFA.

**To Reproduce**
1. Create cognito pool with MFA required, and devices remembered
2. Use a user created by an admin without a phone number to enforce MFA SETUP
3. Login as the new user, scan the qr code and enter the code.
4. You will get an error: "NotAuthorizedException" "Invalid Refresh Token."
5. Refresh and try to log in now
6. log in will be successful

**Expected behavior**
Login should be successful on initial setup  (this is true if devices are not remembered)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Firefox

**Additional context**
Expected behavior does indeed happen if the user pool has device settings set to No.

I believe in the initial MFA setup no device settings are sent which causes the refresh token error, however when not doing the initial setup device settings are sent which is why it works.

**Comment by BDNilsson** [comment]
Sorry, posted this in the wrong section please delete.

Re-posted https://github.com/aws-amplify/amplify-js/issues/6283

**Comment by mauerbac** [comment]
Thanks @BDNilsson
