### ISSUE TITLE
[Feedback]Datastore documentation is lacking.

### ISSUE THREAD

**Issue by SeanRenet** [aws-amplify/docs#2102]
**Page**: [`/lib/datastore/getting-started/q/platform/js`](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/js)

**Feedback**:

It appears that in order to query the datastore you need an association table to retrieve the record you need.

For instance here is a GraphQL user profile where the profile id is the cognito user sub (3722f35e-de54-45b2-b26e-676e2cc48160) which makes the user profile easy to access by Auth.currentUserPoolUser() 

schema looks like this:

```
type User @model  {
  id: ID!
  username: String
  userPhone: String
  createdAt: String
  updatedAt: String
}
```

user profile loaded into DataStore is 
```
  Object {
  "createdAt": 1593774031,
  "id": "3722f35e-de54-45b2-b26e-676e2cc48160",
  "userPhone": "",
  "username": "One Two",
}
```

```
let input = {
                id: id,
                username: username,
                userPhone: userPhone,
                createdAt: createdAt,
            }
 let myDataStore = await DataStore.save(new User({input}));
```

once it is saved to the Datastore it looks like this.

```
dataStore is   User {
  "_deleted": undefined,
  "_lastChangedAt": undefined,
  "_version": undefined,
  "id": "f86d3252-7b1d-44f6-b4cd-b8a7a3a88def",
  "input": Object {
    "createdAt": 1593774031,
`    "id": "3722f35e-de54-45b2-b26e-676e2cc48160",`
    "userPhone": "",
    "username": "One Two",
  },
}
```

In order to query the Datastore and get this record I need to query the datastore with the datastore id:

`DataStore.query(User, c => c.id("eq", "f86d3252-7b1d-44f6-b4cd-b8a7a3a88def"));`

However the only way to know what the datastore id is to create another table that associates the datastore id with the user profile id which in this case is the user's cognito sub.

This does NOT work

`DataStore.query(User, c => c.input.id("eq", "3722f35e-de54-45b2-b26e-676e2cc48160"));`

This does NOT work

`DataStore.query(User, c => c.id.id("eq", "3722f35e-de54-45b2-b26e-676e2cc48160"));`

Is the recommended architecture to create an association table that connects a user's cognito sub with every associated datastore id or is there another way to access the properties of the datastore record?

I've read through the documentation and all of it seems to just explicitly pass the datastore record id which isn't all that helpful in practical use.
.
.

**Comment by j1mr10rd4n** [comment]
I'm just getting to grips with DataStore myself, but shouldn't the query by `id` be:
```
DataStore.query(User, "f86d3252-7b1d-44f6-b4cd-b8a7a3a88def");
```
I found this documented in the [DataStore.query API Reference](https://aws-amplify.github.io/amplify-js/api/classes/datastore.html#query) but it should definitely also be mentioned in the [Manipulating Data page]<https://docs.amplify.aws/lib/datastore/data-access/q/platform/js> in the Library documentation. #1903 already has a lot of work on revamping the DataStore docs - perhaps this could be added in.

**Comment by SeanRenet** [comment]
@j1mr10rd4n thanks I will give that a shot.

**Comment by mauerbac** [comment]
Thanks for taking the time to provide this feedback @SeanRenet ! I've asked @manueliglesias to process this feedback.

**Comment by mauerbac** [comment]
+1 request to improve DS Docs: https://github.com/aws-amplify/docs/issues/2077

**Comment by mauerbac** [comment]
https://github.com/aws-amplify/docs/issues/2145

**Comment by mauerbac** [comment]
https://github.com/aws-amplify/docs/issues/2294

**Comment by iartemiev** [comment]
@SeanRenet If your User object needs to be flat like you have in the schema you've defined, I wouldn't pass `new User( {input})` to `save`, i.e., with curly braces around `input`, since that will create a nested object inside your model with a key of `input`, in other words, you're saving

```js
{
  input: {
    "createdAt": 1593774031,
    "id": "3722f35e-de54-45b2-b26e-676e2cc48160",
    "userPhone": "",
    "username": "One Two",
  }
}
```

That doesn't match the shape of the schema you've defined, since there's no `input` field there.
I think the following would be the easiest way for you to achieve the result you're looking for:

```graphql
type User @model  {
  id: ID!
  userSub: String
  username: String
  userPhone: String
  createdAt: String
  updatedAt: String
}
```

And this app code:
```js
const input = {
  userSub: id,
  username: username,
  userPhone: userPhone,
  createdAt: createdAt,
}

await DataStore.save(new User(input)); // no { } around input here, to prevent it from getting nested
```

You could then query by the user sub with the following: 
```js
const user = await DataStore.query(User, c => c.userSub("eq", "3722f35e-de54-45b2-b26e-676e2cc48160"))
```
