### ISSUE TITLE
User Attributes 

### ISSUE THREAD

**Issue by Marwan-N** [aws-amplify/docs#2108]
**Page**: [`/lib/auth/user-attributes/q/platform/android`](https://docs.amplify.aws/lib/auth/user-attributes/q/platform/android)

**Feedback**:

any update on when the authentication ->  user attributes will be available?

**Comment by jpignata** [comment]
@Marwan-N We're actively working on this, but no specific timeline yet. It's in our short term plan.

**Comment by Marwan-N** [comment]
thanks for the update.
