### ISSUE TITLE
Different URLs in React points to same page

### ISSUE THREAD

**Issue by helios1101** [aws-amplify/docs#2109]
**Describe the bug**
Upon following the the project setup for react from documentation, next Link at [page](https://docs.amplify.aws/start/getting-started/setup/q/integration/react) points to same old page.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to  https://docs.amplify.aws/start/getting-started/setup/q/integration/react
2. Go to https://docs.amplify.aws/start/getting-started/data-model/q/integration/react

**Expected behaviour**
Different pages should have appear for documentation.

**Screenshots**
Links will suffice.

**Desktop (please complete the following information):**
 - OS: [MacOSX]
 - Browser [e.g. chrome]
 - Version [e.g. 83]

**Smartphone (please complete the following information):**
 - Browser [e.g. chrome]
 - Version [e.g. 83]

**Additional context**
NA

**Comment by mauerbac** [comment]
hey @helios1101 - I'm not able to reproduce this issue. Both links are working as expected. Can you explain this "`next Link at page points to same old page.`" ? What behavior are you expecting ? Screenshots would be helpful. Thank you
