### ISSUE TITLE
[Feedback] exhaustive reference for cli options

### ISSUE THREAD

**Issue by cyrfer** [aws-amplify/docs#2110]
**Page**: [`/cli`](https://docs.amplify.aws/cli)

**Feedback**:

Where is the exhaustive reference for options to commands like `amplify init` ?

I'm looking for something like:
https://docs.aws.amazon.com/cli/latest/reference/

**Comment by sw-yx** [comment]
i like this idea but not sure it has a ton of depth - most `amplify ___` commands use prompts rather than CLI flags. still, worth documenting.

**Comment by cyrfer** [comment]
I only care about coverage. I cannot find descriptions for options on several amplify commands.

Normally, commands support `help` or `-h` or `--help` that describe their options, but I've not been able to find info on options for commands, despite people mentioning those options in other github issues, e.g.

```bash
amplify init \
--amplify $AMPLIFY \
--providers $PROVIDERS \
--yes
```
https://github.com/aws-amplify/amplify-cli/issues/3292

Documention like this is built into some CLI frameworks, like [oclif](https://oclif.io/).

**Comment by dabit3** [comment]
If we were to put this in the docs, where would it make sense for us to provide it?

**Comment by cyrfer** [comment]
hey @dabit3 

I think you can put them anywhere. Some ideas (maybe all of them):

1. in the body of https://docs.amplify.aws/cli
   * specifically https://docs.amplify.aws/cli#reference
2. make the docs here more detailed: https://github.com/aws-amplify/amplify-cli#commands-summary
3. another item under `Reference`
![image](https://user-images.githubusercontent.com/4392990/88318058-09a00500-cccf-11ea-9888-0a006384ff94.png)

**Comment by dsypniewski** [comment]
I just found this https://docs.amplify.aws/cli/usage/headless
Maybe someone here will find it useful as I just did, but still built in -h/--help and at least some reference to the headless page from already mentioned places like "Reference" section would be nice as well.

**Comment by sw-yx** [comment]
fwiw I strongly agree that any professional quality CLI should support standard conventions like  - - help. it's just that the ask here is also for a web version. I don't mind putting one together.

pinging @renebrandel for this feedback on the cli
