### ISSUE TITLE
[Feedback]There are blank pages in the docs

### ISSUE THREAD

**Issue by cky8080** [aws-amplify/docs#2139]
**Page**: 
[`/lib/auth/existing-resources/q/platform/js`](https://docs.amplify.aws/lib/auth/existing-resources/q/platform/js)
[`/lib/storage/existing-resources/q/platform/js`](https://docs.amplify.aws/lib/storage/existing-resources/q/platform/js)
[`/lib/auth/existing-resources/q/platform/ios`](https://docs.amplify.aws/lib/auth/existing-resources/q/platform/ios)
[`/lib/storage/existing-resources/q/platform/ios`](https://docs.amplify.aws/lib/storage/existing-resources/q/platform/ios)

**Feedback**:

Above pages are currently blank.
Looking at the Android counterparts, I think they are not supposed to be blank.
Would you take a look and fill them in?
Thanks.

**Comment by jpignata** [comment]
This was my error. Thanks for the report, @cky8080!
