### ISSUE TITLE
[Feedback] Storage - Automatically Track Events page 404s

### ISSUE THREAD

**Issue by gweinhold** [aws-amplify/docs#2142]
**Page**: [`/lib/storage/getting-started/q/platform/js`](https://docs.amplify.aws/lib/storage/getting-started/q/platform/js)

**Feedback**:

While on any of the storage sub-pages, if you click "Automatically Track Events" no page change occurs.  If you take the target URL directly into a tab you'll get a 404.

https://docs.amplify.aws/lib/storage/autotrack/q/platform/js

**Comment by mauerbac** [comment]
hey @gweinhold -  I just tried clicking the link and it worked for me. I'm unable to replicate. Can you try again? In an incognito tab? What browser are you using? and what OS?

**Comment by gweinhold** [comment]
Found it.  Brave with "Shields Up" seems to latch onto the json payload.  Maybe the word "track"?

![image](https://user-images.githubusercontent.com/1418266/88589013-548e8500-d00d-11ea-9ea1-faeed7574f95.png)

Chrome w/ uBlock Origin same behavior too.  Looks like it's matching /autotrack.js in the URL from EasyPrivacy
![image](https://user-images.githubusercontent.com/1418266/88589294-c2d34780-d00d-11ea-9915-e6d775db5727.png)

**Comment by mauerbac** [comment]
I have seen issues with browser extensions like this. Will make note of it.
