### ISSUE TITLE
CLI command documentation

### ISSUE THREAD

**Issue by dabit3** [aws-amplify/docs#2143]
Feedback from customers is that there is no central location with clear explanations of the CLI commands in the documentation for things like `configure`, `init`, `codegen`, etc..

A single piece of documentation outlining these commands would be beneficial to customers.

**Comment by mauerbac** [comment]
Similar to this https://github.com/aws-amplify/docs/issues/2110 , @dabit3 ?

**Comment by sw-yx** [comment]
yes. probably can merge them. this one is really on us, this is autogenerated with other CLI setups

**Comment by dabit3** [comment]
Yep @mauerbac @sw-yx 

I think it's needed, either in the docs, the CLI, or both. I will close this issue and continue with some comments on the other one.
