### ISSUE TITLE
New file ended up in wrong directory

### ISSUE THREAD

**Issue by JPVan** [aws-amplify/docs#2144]
**Page**: [`/start/q/integration/android`](https://docs.amplify.aws/start/q/integration/android)

**Feedback**:

Hi, the tutorial didn't tell me what folder should be highlighted, so when I made the new Kotlin file, it ended up in with schema.graphql, and ended up being a .kts file.

**Comment by mauerbac** [comment]
@jamesonwilliams - would you be able to help here?

**Comment by jamesonwilliams** [comment]
Hi @JPVan, are you referring to the step [Configure Amplify and DataStore, here](https://docs.amplify.aws/start/getting-started/integrate/q/integration/android#configure-amplify-and-datastore)? 

Based on the other information shown the docs, the correct directory for `MyAmplifyApplication.kt` would be `app/src/main/java/com/example/todo`.

To confirm: are you suggesting that we include/highlight this path in the documentation?

I agree that it'd reduce ambiguity, thanks for the suggestion.

**Comment by jamesonwilliams** [comment]
@KristinaPeterson is actively addressing this in https://github.com/aws-amplify/docs/pull/2166.
