### ISSUE TITLE
Docs issue - What's the correct way to create and query one-to-many relationships with DataStore/AppSync?

### ISSUE THREAD

**Issue by Jahans3** [aws-amplify/docs#2145]
**Describe the bug**
Two related issues related to documentation: creating the relationships and querying them using DataStore.

The way the Amplify JS docs suggest creating one-to-many relationships seems a bit counterintuitive, it suggests using a combination of `@connection` and `@key` directives then storing IDs. Using this method they don't appear to have a genuine relationship - this is highlighted by the suggested way of querying relations, which simply involves querying **all** instances of a model with have the ID of their parent as a property and then **filtering by parent ID on the client**. Surely this isn't scalable. Why is this suggested over using the predicate argument of `DataStore.query`?

So I had a look at the sister Amplify libraries and the iOS one makes much more sense. Not only do they suggest a different way of defining relationships - two `@connection` directives (more intuitive, what I had initially thought was correct), but the way they show querying makes a lot more sense too.

The backend shouldn't care what front end library I use, so why are there two suggested methods? Which is correct?

Furthermore, with the querying, the Swift examples are exactly what I would expect:

```swift
Amplify.DataStore.query(Post.self, byId: "123") {
    switch $0 {
    case .success(let post):
        if let postWithComments = post {
            if let comments = postWithComments.comments {
                for comment in comments {
                    print(comment.content)
                }
            }
        } else {
            print("Post not found")
        }
    case .failure(let error):
        print("Post not found - \(error.localizedDescription)")
    }
}
```

But the JS version requires us to manually piece together any "related" models:

```js
const post = await DataStore.query(Post, "123");
const comments = (await DataStore.query(Comment)).filter(c => c.postID === post.id);
```

What's going on here? Admittedly my knowledge of AppSync isn't amazing, it all comes from Amplify, which is perhaps why this is so confusing to me. But still I'd love the docs to be accurate since it's making developing using Amplify difficult at times.

And I'd love to know which is the correct method? 🙂

**To Reproduce**
See JS docs vs iOS docs

JS: https://docs.amplify.aws/lib/datastore/relational/q/platform/js

iOS: https://docs.amplify.aws/lib/datastore/relational/q/platform/ios

Thanks very much - sorry for not following the template, I felt a lot wasn't relevant to a documentation issue.

**Comment by sw-yx** [comment]
@Jahans3 unfortunately im gonna defer this qtn to the team because i dont know myself yet and dont want to give you the wrong answer. sorry. might also want to ask in the amplify discord too with more experts there

**Comment by Jahans3** [comment]
@mauerbac might be worth creating a similar issue in the JS repo about this lazy loading/DataStore JS issue? Feel like this is a pretty major flaw

@sw-yx no problem, thanks for the suggestion. Cheers for the help today 👍

**Comment by sw-yx** [comment]
pretty sure there's an issue for the lazyloading one, i've seen it in a few places. im sure theres a v good reason why it hasnt been implemented yet

**Comment by mauerbac** [comment]
Sorry for the delayed follow-up. We are tracking the lazy loading feature request here: https://github.com/aws-amplify/amplify-js/issues/5054
