### ISSUE TITLE
[Feedback]FEW links on page are not working under react native section of Amplify doc

### ISSUE THREAD

**Issue by danandguru** [aws-amplify/docs#2149]
**Page**: [`/start/getting-started/installation/q/integration/react-native`](https://docs.amplify.aws/start/getting-started/installation/q/integration/react-native)

**Feedback**:

Hi , 
When I was reading docs for amplify and went to react native option page in amplify doc section , I found that 2 links ( highlighted in attached screen shots ) are not working and showing no message as well. Its really confusing to me that if  say for example "Add authentication"  or "Next Steps" is not available then links should be removed. I clicked couple of time then realized that it not working . 

Please take necessary action. 

Regards 
![awsamplify_doc_error](https://user-images.githubusercontent.com/41638257/88420912-43732780-ce05-11ea-8e90-c5ad83ba5eac.png)

**Comment by mauerbac** [comment]
Hey @danandguru - I just tried clicking both links and it worked for me. I'm unable to replicate. Can you try again? In an incognito tab? What browser are you using? and what OS?

**Comment by mauerbac** [comment]
Are you using any extensions? Will close for now
