### ISSUE TITLE
better documentation for connect component 

### ISSUE THREAD

**Issue by Spodeopieter** [aws-amplify/docs#215]
I'm frustrated with the documentation for the react connect component. 

https://aws-amplify.github.io/docs/js/api#react-components

Please improve upon this , especially the part covering subscriptions. I can use this component to do queries , but can't get your subscription example to work.

**Comment by zjullion** [comment]
Just wanted to piggy-back on this issue: https://github.com/aws-amplify/docs/blame/master/js/api.md#L455 is incorrect, it should read

```
await onCreate(input)
```

**Comment by jordanranz** [comment]
@zjullion, how is your mutation defined?
