### ISSUE TITLE
[Feedback] Under Create authentication service - please provide detail about which selections to make 

### ISSUE THREAD

**Issue by JPVan** [aws-amplify/docs#2151]
**Page**: [`/start/q/integration/react`](https://docs.amplify.aws/start/q/integration/react)

**Feedback**:

Under the "Create authentication service" section on this tutorial page, please provide detail about which selections to make. 

I chose "no" when it asked if I wanted to update the GraphQL now, but I'm not sure if that's the right thing. Thanks!

**Comment by mauerbac** [comment]
This is outdated and is updated
