### ISSUE TITLE
[Feedback]Vue Tutorial broken at amplify publish step.

### ISSUE THREAD

**Issue by tobemedia** [aws-amplify/docs#2152]
**Page**: [`/start/getting-started/hosting/q/integration/vue`](https://docs.amplify.aws/start/getting-started/hosting/q/integration/vue)

**Feedback**:

The Setup works with a dev build locally using 
`npm run serve`

Running the app in production build, the setup is broken using
`amplify publish`
leads to a javascript error
`main.js:7 Uncaught TypeError: Cannot read property 'configure' of undefined`

changing the import statement fixed the error for me
```
- import Amplify from 'aws-amplify';
+ import Amplify from '@aws-amplify/core';
```

**Comment by gsans** [comment]
It seems this issue can be introduced by having both dependencies `aws-amplify` and `@aws-amplify/core` in your `package.json` as mentioned in [#6130](https://github.com/aws-amplify/amplify-js/issues/6130). 

Make sure you only have `aws-amplify` and the original code should work.

**Comment by gsans** [comment]
This could also be related to this issue [#6411](https://github.com/aws-amplify/amplify-js/issues/6411) related to webpack version.

**Comment by mauerbac** [comment]
@tobemedia - can you try this suggestion?

**Comment by jennapederson** [comment]
I was able to resolve this by pinning webpack to 4.43.0 (without using the named import) OR by updating to use the named import (with webpack 4.44.0) as described in [#6411](https://github.com/aws-amplify/amplify-js/issues/6411). Running through this Vue tutorial, I did not have multiple, overlapping `aws-amplify` dependencies.
