### ISSUE TITLE
[Feedback] Great Tutorial!

### ISSUE THREAD

**Issue by GregJacobs82** [aws-amplify/docs#2153]
**Page**: [`/start/getting-started/installation/q/integration/vue`](https://docs.amplify.aws/start/getting-started/installation/q/integration/vue)

**Feedback**:

Very simple & easy walk-through tutorial! Thank you!

**Comment by mauerbac** [comment]
Awesome. Thanks!

**Comment by sw-yx** [comment]
thanks!
