### ISSUE TITLE
[Feedback]Missing docs about where Api Key (for local api execution) is located

### ISSUE THREAD

**Issue by tobiasfeil** [aws-amplify/docs#2154]
**Page**: [`/cli/graphql-transformer/directives`](https://docs.amplify.aws/cli/graphql-transformer/directives), specifically https://docs.amplify.aws/cli/graphql-transformer/directives#public-authorization

It says you need an API key for public authorization and I remember that at some point in some configuration file somewhere in the project, I found the key for local execution. But now I can't find it anymore and I can't find any docs about where it is

**Comment by mauerbac** [comment]
Thanks @tobiasfeil for submitting the PR as well. I think this is helpful and we should include iOS and Android as well.
