### ISSUE TITLE
[Feedback] Java not mentioned as a requirement when mocking 

### ISSUE THREAD

**Issue by sywor** [aws-amplify/docs#2157]
**Page**: [`/start/q/integration/react (Optional) Test your API`](https://docs.amplify.aws/start/getting-started/data-model/q/integration/react#optional-test-your-api)

**Feedback**:

Under the section "Test your API" you should mention that the mock api requires Java

**Comment by mauerbac** [comment]
Thanks @sywor . That's a great callout. This has come up previously.

**Comment by mauerbac** [comment]
@renebrandel , is this okay with you?

**Comment by renebrandel** [comment]
Done: https://github.com/aws-amplify/docs/pull/2169

**Comment by jamesonwilliams** [comment]
Closing; @renebrandel provided #2169.
