### ISSUE TITLE
Need example of how to add a logo to AmplifyGreetings

### ISSUE THREAD

**Issue by nonbeing** [aws-amplify/docs#2158]
**Describe the bug**
I am trying to customize the `AmplifyGreetings` component in my React app. I'm using the instructions at [the official amplify docs](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#greetings).

I am using `"@aws-amplify/ui-react": "^0.2.8"`. 

I am passing props to the `AmplifyGreetings` component in my App.js like `<AmplifyGreetings logo={Hello} username={userEmail}></AmplifyGreetings>`, just as described in the docs. However the logo never displays, it's always `undefined` (see screenshot below).

Here's a more complete example:
```javascript
const App = () => {
  const Hello = () => <h1>Hello!</h1>

  return (
    <AmplifyAuthenticator usernameAlias='email'>
      <AmplifySignIn
        headerText='Sign In to Your Account'
        slot='sign-in'
      ></AmplifySignIn>
      <AmplifyGreetings logo={Hello} username={userEmail}></AmplifyGreetings>
      <div className='App'>
      // nothing special here, just a form and a button
      </div>
    </AmplifyAuthenticator>
  )
}
```

In my App.css I have managed to customize the colors using: 

```
amplify-greetings {
  --background-color: #02387b;
  --border-color: #02387b;
  color: #eff0f4;

}
```

I actually want to pass in an SVG component to the `logo` prop of `AmplifyGreetings`. I am able to import a logo component like so: `import svglogo from './logo/svglogo'` and render `svglogo` inside `  <div className='App'>` - in other words, I know the SVG component is working and I am able to show it in the app, but it doesn't work in `AmplifyGreetings`.

The docs for `AmplifyGreetings` say:
![docs](https://i.imgur.com/iRkIlXd.png)

The problem with the above docs is that `FunctionalComponent<{}>` is really very ambiguous, and I have been scouring the Internet on how to pass this `FunctionalComponent<{}>` logo to `AmplifyGreetings`, but haven't been able to find a single example. As you can see from the snippet I shared above, `const Hello = () => <h1>Hello!</h1>` is a simple, purely-functional React component, but even this is also getting rendered as `undefined`. There is no help from Amplify's console logs on what I am doing wrong - no warnings or errors or feedback of any kind. 

This is incredibly frustrating, and you guys really need to add an example for adding a logo (among the other glaring missing examples in the Amplify framework) to `AmplifyGreetings` to your docs at: https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#greetings

I am blocked on this issue, so would immensely appreciate if you could please share a working example of passing a sample logo `FunctionalComponent<{}>` (whatever that is supposed to be) to `AmplifyGreetings`.

**To Reproduce**
Try to use the above code.

**Expected behavior**
The functional logo component should get rendered, instead of the `undefined` that is displayed. OR share a working example for me to emulate.

**Screenshots**
Please see this:
![this screenshot](https://i.imgur.com/cfMrxpr.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser: Chrome v84

**Smartphone (please complete the following information):**
None.

**Additional context**
None.

**Comment by nonbeing** [comment]
The logo not working in `AmplifyGreetings` has been confirmed as a bug here: https://github.com/aws-amplify/amplify-js/issues/6446

Please leave this `docs` bug open for tracking, until the other bug (#6446) is fixed and the Amplify docs are consistent with the expected functionality.

**Comment by jordanranz** [comment]
Pending some testing from https://github.com/aws-amplify/amplify-js/issues/6446#issuecomment-670085302, we will get some docs added for this.

**Comment by mauerbac** [comment]
Hey @jordanranz , friendly ping to add docs to it :)

**Comment by mauerbac** [comment]
logo docs is added
