### ISSUE TITLE
[Feedback] Customize Auth Components 

### ISSUE THREAD

**Issue by vomc** [aws-amplify/docs#2159]
**Page**: [`/ui/auth/authenticator/q/framework/react`](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#withauthenticator)

**Feedback**:

The docs are ok - a bit better as the previous ones were so light on detail that it was not even worth reading them. Taking away the ability to customize auth in the change of withAuthenticator is a major bummer... now we have to rewrite our custom login using 'web component slots' ... thanks to the team for creating all of this extra work for us.

**Comment by mauerbac** [comment]
Thanks for feedback @vomc and sorry to hear you are frustrated. I've passed this feedback to the team. In the meantime, you should be able to continue using `aws-amplify-react` ?

**Comment by vomc** [comment]
> Thanks for feedback @vomc and sorry to hear you are frustrated. I've passed this feedback to the team. In the meantime, you should be able to continue using `aws-amplify-react` ?

Hi Matt, thanks for the response. 

Unfortunately no, because the password reset flow for Cognito users is not working in Chrome on iOS. I filed the issue here and a team-member said that the regular `aws-amplify-react` library is no longer in active development so I guess they will just leave this broken... Great stuff

https://github.com/aws-amplify/amplify-js/issues/6417

- J

**Comment by dabit3** [comment]
Hey @vomc yes agreed about the `withAuthenticator` and we are working to get back to feature parity with what we had before.

In the meantime we've submitted some updates on how to customize the `AmplifyAuthenticator` here:

https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#managing-user-state-and-layout

This is a little more code but it gives you more control. In the meantime we are working on improving the configurability of the `withAuthenticator` and will follow back up here as soon as those updates are released.
