### ISSUE TITLE
[Feedback]FEEDBACK_TITLE_HERE

### ISSUE THREAD

**Issue by ferplie** [aws-amplify/docs#2172]
**Page**: [`/start/getting-started/generate-model/q/integration/android`](https://docs.amplify.aws/start/getting-started/generate-model/q/integration/android)

**Feedback**:

<I was running the tutorial, but when I click on the "Integrate in your app"link, the wrong link opens, as it reverts back to the "Generate model files">

**Comment by mauerbac** [comment]
Hello @ferplie -- thanks for reaching out. I wasn't able to reproduce the issue. Can you try in an incognito tab? We've found certain extensions might interfere with the site. If it's still a problem, what browser are you on? 
<img width="1412" alt="Screen Shot 2020-08-03 at 4 14 13 PM" src="https://user-images.githubusercontent.com/1507886/89236097-81f6a800-d5a4-11ea-8a6a-5d01ad59d04c.png">
