### ISSUE TITLE
What is in Amplify.configure(awsconfig);

### ISSUE THREAD

**Issue by mehrbat** [aws-amplify/docs#2174]
**Page**: [`/ui/auth/authenticator/q/framework/angular`](https://docs.amplify.aws/ui/auth/authenticator/q/framework/angular)

**Feedback**:

Would have been great to write an explanation for what exactly is in awsconfig ('aws-exports').

**Comment by jamesonwilliams** [comment]
@mehrbat To be sure, you're requesting that we document the configuration options that one can put into the `awsconfig`?

**Comment by mehrbat** [comment]
@jamesonwilliams Hi James. Thanks for your reply. 
When I wrote my post here I was a bit frustrated with not being able to find some doc on the configuration options immediately on Google, so I came here and nagged :) I have moved away from Amplify now, as I found an alternative solution that I can deliver my project faster with so I am not even sure if there is enough doc on the net about configuration options or not as I did not dig deeper for that.

**Comment by jamesonwilliams** [comment]
Thanks so much for taking the time to provide this feedback, @mehrbat. Hope you'll decide to try us again in the future. Meanwhile, this type of feedback will help us to prioritize documentation, as a team.

**Comment by mauerbac** [comment]
This has been addressed https://docs.amplify.aws/lib/client-configuration/configuring-amplify-categories/q/platform/js

**Comment by Nanobrainiac** [comment]
Just came across this from a google search and am VERY thankful you guys worked this into the docs!  Thank you thank you!

**Comment by hariseldon78** [comment]
i'd love to see an example of dual authentication for appsync access, with API_KEY and COGNITO authentications. Typescript type for the awsconfig object would be the best way, better than documentation.
