### ISSUE TITLE
Vue Amplify Getting Started -  "Subscribe only available for AWS AppSync endpoint" and  "No graphql endpoint provided."

### ISSUE THREAD

**Issue by dinnouti** [aws-amplify/docs#2177]
if you are following the [AWS Vue / Amplify Getting started](https://docs.amplify.aws/start/q/integration/vue) and getting a  "**Subscribe only available for AWS AppSync endpoint**" and  "**No graphql endpoint provided**." error on Chrome console.

It would be nice to have this example in the tutorial:

```javascript
import Vue from 'vue'
import App from './App.vue'

import Amplify from 'aws-amplify';
import '@aws-amplify/ui-vue';
import aws_exports from './aws-exports';

Amplify.configure(aws_exports);

Vue.config.productionTip = false

new Vue({
  render: h => h(App),
}).$mount('#app')
```

**Comment by mauerbac** [comment]
hey @dinnouti - can you provide the selections and input you provided to see that error? Thank you

**Comment by dinnouti** [comment]
In the documentation wasn't very clear where to put the AWS Amplify imports. Not a bug but a clarification and a recommendation for the documentation.

**Comment by mauerbac** [comment]
Got it. That makes sense to me. Will mark to add it.

**Comment by mauerbac** [comment]
@dinnouti - just brought this up with the team. We've recently reviewed the Vue getting started and with the newer updates feel it is clear with using the Amplify imports. Could you open a new issue if aspects could still be improved or contribute directly?

**Comment by ZYinMD** [comment]
For those who google their way here, but didn't understand exactly what the OP meant (maybe because you're not a vue user), here's the gist: Make sure your subscriptions are added _after_ `Amplify.configure(awsconfig)`

In other words, if you need to do things at the top level of your code, e.g. add subscriptions, do them _in the same file_, where `Amplify.configure(awsconfig)` goes first.

**Comment by skradiansys** [comment]
I am getting the same error and it's working fine on the localhost but on the production it's giving the same error. I have checked the region and all the api keys and id they are all fine but don't what's wrong. Any help will be appreciated
