### ISSUE TITLE
AWS IOT - Pubsub subscribe got no response using amplify

### ISSUE THREAD

**Issue by arun-electronut** [aws-amplify/docs#218]
**Describe the bug**
I have created ionic application with aws starter template. Did setup aws amplify from https://aws-amplify.github.io/
Also did completed setting up cognito link. I am able to signup and signin as well.
After SignIn , when i try to connect using this code :

 ` 
PubSub.subscribe("myTopic").subscribe({ 
         next: data => console.log('Message received', data),
         error: error => console.error(error),
         close: () => console.log('Done'),
    }); 
`

**To Reproduce**
1. Setup Ionic and create a project using aws starter template 
2. Add aws amplify following documentation from website.
3. Add Cognito feature.
4. Now use PubSub to connect to AWS IOT
5. No data received when subscribing. Nor on aws iot test console when publishing.

**Expected behavior**
Connection to aws iot should be made and data should be received on subscribing.

**Desktop (please complete the following information):**
 - OS: Linux - Kubuntu 18.04
 - Browser: Chrome
 - Version: 70.0.3538.67

**Additional context**

Additionaly , following document from aws amplify, PubSub.subscribe method uses 2 parameters, but when using in Ionic App , PubSub.subscribe require 3 parameters, third one being ProviderOptions.
What options are available , can't find them anywhere.

**Comment by arun-electronut** [comment]
Update : I didn't updated anything, and now its not even requesting for any resources. 
I guess updated documentation for PubSub will help.

**Comment by jordanranz** [comment]
Hey @arun-electronut, apologies for the late response. Do you see any error in your browser console when using PubSub?

**Comment by arun-electronut** [comment]
@jordanranz I remember there was no error in console.
```Additionaly , following document from aws amplify, PubSub.subscribe method uses 2 parameters, but when using in Ionic App , PubSub.subscribe require 3 parameters, third one being ProviderOptions.
What options are available , can't find them anywhere.
```
This also stops the app to be build, i don't know how to proceed on this. Though i have other workaround using aws-sdk working right now.
