### ISSUE TITLE
[Feedback]Collaborator's comment in production docs?

### ISSUE THREAD

**Issue by tobiasfeil** [aws-amplify/docs#2180]
**Page**: [`/cli/graphql-transformer/dataaccess/17`](https://docs.amplify.aws/cli/graphql-transformer/dataaccess#n17-get-sales-representatives-ranked-by-order-total-and-sales-period)

**Feedback**:

It looks like the text in the 17th section is a collaborator's comment. I personally would say rather remove the section altogether than leave this in the official docs

**Comment by sw-yx** [comment]
wow, good catch

**Comment by mauerbac** [comment]
Thanks @tobiasfeil and for the fix @sw-yx
