### ISSUE TITLE
[missing-page]

### ISSUE THREAD

**Issue by Rye434** [aws-amplify/docs#2189]
**Page**: [`https://docs.amplify.aws/lib/push-notifications/getting-started`](https://docs.amplify.aws/lib/push-notifications/getting-started)

**Feedback**:

**Comment by sw-yx** [comment]
what exactly is missing?

**Comment by Rye434** [comment]
https://docs.amplify.aws/lib/push-notifications/getting-started

this link gives me a 404

**Comment by sw-yx** [comment]
weird... 
![image](https://user-images.githubusercontent.com/6764957/89336797-89b16c00-d6cc-11ea-9115-2d4942304f2a.png)

**Comment by Rye434** [comment]
<img width="1680" alt="Screen Shot 2020-08-04 at 3 35 51 PM" src="https://user-images.githubusercontent.com/22172083/89336979-39082780-d668-11ea-8f9b-3d3e5a192579.png">

**Comment by jamesonwilliams** [comment]
I'm not able to reproduce this, either.

Please provide details about what browser you're using, as well as your user agent. Re-open if you can.
