### ISSUE TITLE
npm ERR! missing script: start[Feedback]FEEDBACK_TITLE_HERE

### ISSUE THREAD

**Issue by SSSangha90** [aws-amplify/docs#2190]
**Page**: [`/start/getting-started/setup/q/integration/react`](https://docs.amplify.aws/start/getting-started/setup/q/integration/react)

**Feedback**:

When running npm start in the command line, I get the following error:

npm ERR! missing script: start

**Comment by sw-yx** [comment]
check your package.json. it needs to have a `start` script setup. if you followed the `npx create-react-app`  instructions you should not have this problem

**Comment by SSSangha90** [comment]
I checked and I do not have a start script. I do in the folder amplify/config folder, but not in my main package.json file.

I definitely used npx create-react-app. What should I set the start script too, I even tried inserting one, no luck.

**Comment by SSSangha90** [comment]
I checked and I do not have a start script. I do in the folder amplify/config folder, but not in my main package.json file.

I definitely used npx create-react-app. What should I set the start script too, I even tried inserting one, no luck.

**Comment by sw-yx** [comment]
example https://github.com/netlify/create-react-app-lambda/blob/master/package.json#L12

**Comment by SSSangha90** [comment]
Thanks for the example. 

I added the start script and received an error: no index.html file found in the public folder (along those lines).

I've manually created an index html file in a public folder. This runs and works :)

**Comment by sw-yx** [comment]
i think your create react app session failed somehow. this is not supposed to happen. in any case, its not an amplify issue.
