### ISSUE TITLE
[Feedback]There are two pages with different iOS setup

### ISSUE THREAD

**Issue by moaible** [aws-amplify/docs#2199]
**Feedback**

There are two pages with different iOS setup.

**To Reproduce**

1. Go to 'Getting Started' -> 'Start the Tutorial'
2. Click on 'Tutorial -> Set up fullstack project'
3. Scroll down to 'Add Amplify to your application'

<img width="680" alt="image" src="https://user-images.githubusercontent.com/6584297/89502970-d1391480-d800-11ea-824e-6dc065c2fbcf.png">

4. Go to 'Libraries'
5. Click on 'Project Setup -> Prerequisites'
6. Scroll down to 'Create your application'

<img width="680" alt="image" src="https://user-images.githubusercontent.com/6584297/89503154-1f4e1800-d801-11ea-81a8-413815a19947.png">

Which right?

| Tutorial | Libraries |
| --- | --- |
| <img width="320" alt="image" src="https://user-images.githubusercontent.com/6584297/89502970-d1391480-d800-11ea-824e-6dc065c2fbcf.png"> | <img width="320" alt="image" src="https://user-images.githubusercontent.com/6584297/89503154-1f4e1800-d801-11ea-81a8-413815a19947.png"> |

**Comment by mauerbac** [comment]
thanks @moaible - Ill have someone from the iOS team take a look

**Comment by drochetti** [comment]
Hi @moaible,

Thanks for the feedback.

As for your question, both are right. They have different intent though. The tutorial is an opinionated and quick way of getting Amplify working without diving too deep into details.

On the _Libraries / Prerequisites_ you will find the minimum config needed common to all Amplify categories (DataStore, Predictions, API, etc) and then you will need to refer to each category docs to get something working.

The main difference, as highlighted by your code snippets, is the number of dependencies. That's what I meant by the tutorial being opinionated.
