### ISSUE TITLE
[Feedback]404 Error when attempting to install Amplify cli.

### ISSUE THREAD

**Issue by Sasinda98** [aws-amplify/docs#2200]
**Page**: [`/cli`](https://docs.amplify.aws/cli)

**Feedback**:
I get the following error on the terminal when I try to install the amplify cli globally. 

npm ERR! code E404
npm ERR! 404 Not Found - GET http://registry.npmjs.org/@aws-amplify%2fcli - Not found
npm ERR! 404 
npm ERR! 404  '@aws-amplify/cli@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by mauerbac** [comment]
hi @Sasinda98 - did you run this command? `npm install -g @aws-amplify/cli` Can you confirm? Can you also tell us more details about your OS?

**Comment by Sasinda98** [comment]
Yeah, OS is MacOS Catalina 10.15.6 . I tried the command like two hours later and it worked as expected without the 404 error, don't know why it couldn't install when I tried initially though..

**Comment by jamesonwilliams** [comment]
@Sasinda98 In the window of time you are mentioning, I believe there was an NPM outage. We also had people complaining about this in our Discord chat.

https://status.npmjs.org/incidents/cksjqc1w11v5

**Comment by Sasinda98** [comment]
Oh okay, that explains it.
