### ISSUE TITLE
[Feedback] Please include complete final source on page or in repository 

### ISSUE THREAD

**Issue by JPVan** [aws-amplify/docs#2202]
**Page**: [`/start/q/integration/vue`](https://docs.amplify.aws/start/q/integration/vue)

**Feedback**:

Maybe I'm missing it, but as a beginner, I followed every step and I've got weird errors at the end. I'm fixing them one by one, but:

- **it would be really great if I could compare my results to a complete and working directory of the source files I'm supposed to have when I'm finished.** I don't care if it's a repository, or if it's a zip file or even a bunch of raw files on the web server that are linked to individually. 

My problem at the moment happens to be Module not found: Error: Can't resolve './graphql/mutations" in the views directory. But before this error it was another one because I missed one line during a copy and paste. It would be so nice to have something to compare against as a complete correct and working final program. 

Thanks! I love that you have feedback available on these tutorials and the docs and that the feedback goes right into an issue on GitHub.

**Comment by gsans** [comment]
That's a great point. Thanks! This requires a bit more thought as it will apply to all frameworks.

**Comment by mauerbac** [comment]
Hey @JPVan - just following up on this issue. It will be tough for the team to support this given the scope of the ask and number of configurations. This would be a great point to raise in our Discord and folks have probably taken a stab at this.
