### ISSUE TITLE
[Feedback] Webpack Error "Insufficient number of arguments or no entry" 

### ISSUE THREAD

**Issue by tobyhede** [aws-amplify/docs#2203]
**Page**: [`/start/getting-started/setup/q/integration/js`](https://docs.amplify.aws/start/getting-started/setup/q/integration/js)

**Feedback**:

Following the JS Tutorial. 
After adding content to all of the relevant files, the `npm start` results in an error. 
Looks like it might be an interaction with the configuration and updated Webpack version.

![Screen Shot 2020-08-07 at 10 41 42 am](https://user-images.githubusercontent.com/28390/89596477-997eab00-d89a-11ea-80c2-4cc1b4e28101.png)

**Comment by tobyhede** [comment]
10 seconds after I post this I fixed it. 
How embarrassment.

**Comment by sw-yx** [comment]
![image](https://user-images.githubusercontent.com/6764957/89661964-f5cae480-d905-11ea-9caf-1dc1bf267602.png)
