### ISSUE TITLE
[Feedback] More Vue heavy code samples and tutorials 

### ISSUE THREAD

**Issue by JPVan** [aws-amplify/docs#2216]
**Page**: [`/lib/datastore/getting-started/q/platform/js`](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/js)

**Feedback**:

It would be nice if this doc page mentions how to use DataStore with Vue, or that DataStore is not yet available for use with Vue.

**Comment by sw-yx** [comment]
it's framework agnostic, so it does. 

if we can make that more clear in the docs, we should try to do so. i understand examples are react centric.

**Comment by mauerbac** [comment]
HI @JPVan - what additional context would you like to see on this page?

**Comment by JPVan** [comment]
Sorry for the slow reply! Thanks for asking what additional context I'd like to see. 

Under Getting Started -> Platform Integration, I'd love to see mention of Vue (or simply all other web platforms other than React). I guess it's sort of covered under Option 2 Use Amplify CLI, but as someone new to Amplify it seemed very open to doubt as to whether Vue is recommended/supported with DataStore. I think I read elsewhere that (at least at some point in the past) DataStore was only recommended for use with React for web projects. Enough people are using Vue, that it would be nice to have it mentioned specifically. And once an example DataStore Vue app is available, linking to it as well could be nice. Also, since Option 1 Platform Integration started off by saying, "The fastest way to get started is using the amplify-app npx script", it seemed like anything else wasn't ideal or fully recommended. Hope this helps!

**Comment by JPVan** [comment]
I just now discovered these: 
 - [https://github.com/aws-amplify/docs/pull/2186](url) 
 - [https://docs.amplify.aws/lib/datastore/examples/q/platform/js](url)

So, as of a week or two ago, there is a Vue DataStore example available. But it would also be great to have Vue mentioned in most/all places where React is mentioned in these DataStore docs pages, for those who are not reading completely/linearly.

**Comment by mauerbac** [comment]
Such a good point. Our docs are very React heavy/focused. Will keep this to track more Vue examples

**Comment by cwomack** [comment]
@JPVan, wanted to follow up on this issue now that there is a Vue example for DataStore integration that can be found on the following page: https://docs.amplify.aws/lib/datastore/examples/q/platform/js/#example-application. 

I'll close out the issue since this was implemented in 2021. Please let us know if you have more feedback on the Vue docs tied to this.
