### ISSUE TITLE
AWS Neophyte

### ISSUE THREAD

**Issue by UncleRic** [aws-amplify/docs#2217]
**Page**: [`/start/q/integration/ios`](https://docs.amplify.aws/start/q/integration/ios)

**Feedback**:

There are quite a few courses, tutorials over non-iOS AWS.  Hence this one is critical for me.
UI is simple and modular which makes it difficult to go astray.
I prefer this approach for the neophyte; from which further docs could be accessed accordingly.
From an iOS-Developer perspective, this is important & preferable.

**Comment by mauerbac** [comment]
Hi @UncleRic - just to be clear, do you have any specific feedback about this tutorial?
