### ISSUE TITLE
[Feedback]Update needed for Ionic Amplify Tutorial

### ISSUE THREAD

**Issue by PaulMacSiena** [aws-amplify/docs#2224]
**Page**: [`/start/getting-started/setup/q/integration/ionic`](https://docs.amplify.aws/start/getting-started/data-model/q/integration/ionic#create-a-new-ionic-app)

**Feedback**:

The code snippet 

<img width="606" alt="Screen Shot 2020-08-10 at 11 38 37 PM" src="https://user-images.githubusercontent.com/33580162/89854719-a03f4380-db62-11ea-9996-629b76cb1fb3.png">

should have "awsconfig" replaced with "awsmobile" like so 

<img width="325" alt="Screen Shot 2020-08-10 at 11 39 49 PM" src="https://user-images.githubusercontent.com/33580162/89854785-c95fd400-db62-11ea-9faf-c59b4a04b768.png">

because the auto-generated aws-exports.js file exports a javascript module named "awsmobile", not "awsconfig".

<img width="650" alt="Screen Shot 2020-08-10 at 11 41 23 PM" src="https://user-images.githubusercontent.com/33580162/89854872-01671700-db63-11ea-9ea3-fde3bf7b4d10.png">

I would also add that for whatever reason I also had to create a @types/aws/aws-exports.ts file

<img width="311" alt="Screen Shot 2020-08-10 at 11 42 36 PM" src="https://user-images.githubusercontent.com/33580162/89854930-2d829800-db63-11ea-8d16-1c8123754dc3.png">

<img width="312" alt="Screen Shot 2020-08-10 at 11 43 32 PM" src="https://user-images.githubusercontent.com/33580162/89854978-4ee38400-db63-11ea-91bc-28ee58773e33.png">

and add the field "allowJs": true to the tsconfig.json file. I found this solution [`here`](https://duncanleung.com/aws-amplify-aws-exports-js-typescript/)

Maybe this was just an issue for me. I wonder if anyone else ran into this issue

**Comment by mauerbac** [comment]
hey @PaulMacSiena - I don't believe the import name should be relevant. It didn't work with `awsconfig` ?

I think your second point makes sense -- as some folks have strict TypeScript settings and it will complain theres no definition. Will mark this as a feature request for the CLI to generate that and for us to update the doc for TS.

**Comment by PaulMacSiena** [comment]
@mauerbac It did not work with `awsconfig` as the import, but at that time I also had not allowed js in my typescript settings, so as you said, I think it was just the issue in my second point.
