### ISSUE TITLE
Broken rendering in iOS Getting Started Guide in setup.md

### ISSUE THREAD

**Issue by jamesonwilliams** [aws-amplify/docs#2230]
**Describe the bug**

There is a rendering bug in the iOS getting started documentation, wherein a (seemingly well-encoded) code snippet breaks on a new line, leaving a stray `end` in the main document, where it should continue to be displayed in code formatting.

The next portion is also broken -- a list item becomes  embedded into the next code snipped, and then next command snippet is broken.

The image below better illustrates the issue, than these words.

**To Reproduce**
Look-ie here, see?

https://docs.amplify.aws/start/getting-started/setup/q/integration/ios#add-amplify-to-your-application

**Expected behavior**

`Podfile` text is shown as a single block, and the numbered list continues to increment upwards, from where it had left off (now, it resets to 1.) `pod install --repo-update` is show in its own code area.

**Screenshots**
<img width="1167" alt="Screen Shot 2020-08-11 at 11 51 18 PM" src="https://user-images.githubusercontent.com/899569/89979897-fdec9200-dc2d-11ea-98c5-07558832dd53.png">

**Desktop (please complete the following information):**
 - OS:  Mac OS X Catalina 10.15.6
 - Browser: Chrome 
 - Version: Version 84.0.4147.105 (Official Build) (64-bit)

**Additional Context**

The code that produces this window is in https://github.com/aws-amplify/docs/blame/master/docs/start/getting-started/fragments/ios/setup.md#L58-L76.

---------------

cc: @drochetti

**Comment by drochetti** [comment]
Thanks for catching that @jamesonwilliams !
