### ISSUE TITLE
[Feedback] Codeblocks need to be searchable as well

### ISSUE THREAD

**Issue by ericclemmons** [aws-amplify/docs#2236]
**Page**: [`/lib/auth/advanced/q/platform/js`](https://docs.amplify.aws/lib/auth/advanced/q/platform/js#facebook-sign-in-react-native---expo)

**Feedback**:

Some APIs (e.g. `cookieStorage`, `Auth.federatedSignIn('facebook', { token, expires_at: expires}, { name: 'USER_NAME' })`) only exist within code.

Search the docs to answer customer requests means that we can't use the docs search, but instead have to search the raw code and work our way back to where that code is rendered. (This gets tougher with fragments)

**Comment by harrysolovay** [comment]
@ericclemmons please review PR #2361 –– should (in combination with the updated Algolia config) resolve this issue.
