### ISSUE TITLE
Several things to be refactored in Amplify Android project setup tutorial

### ISSUE THREAD

**Issue by changxu0306** [aws-amplify/docs#2238]
In [project setup section of Amplify Android doc](https://docs.amplify.aws/lib/project-setup/create-application/q/platform/android), there are three little defects needed to be refactored:

**1. Some of the guidance is not consistent with the screenshots.**

Here, the name of the new project in the screenshot should be changed into `MyAmplifyApp`.
![image](https://user-images.githubusercontent.com/42978935/90105024-11652f00-dcfa-11ea-9f42-16aea0b85d0d.png)

Here, replace `build.gradle(Module: MyAmplifyApp)` with `build.gradle(Module: app)`.
![image](https://user-images.githubusercontent.com/42978935/90166540-48196480-dd4f-11ea-8ebf-37aa1562a258.png)

**2. A warning box is better to be added to tell users how to fix the error they may meet.**

Problem: After adding Amplify Core library in the dependencies block and run Gradle Sync, an error occurs. _"In order to use core library desugaring, please enable multidex."_
This is because the tutorial uses Android 16 as minSDK. For minSDK >= 21, we don't have this problem. But for minSDK < 21, this problem might happens. 
[Reference link](https://stackoverflow.com/questions/26609734/how-to-enable-multidexing-with-the-new-android-multidex-support-library/61606097#61606097)

Solution: Add a warning box saying "If you target an API level below 21, you will need to add explicit multidex support. Please see regarding [Android documentation](https://developer.android.com/studio/build/multidex?authuser=1#mdex-pre-l)."

**3. For Android Studio 4.x, the prompt for creating a new class has been changed.**
Now, the doc asked users to create an Application class using prompt.
![image](https://user-images.githubusercontent.com/42978935/90107580-e250bc80-dcfd-11ea-94b1-cb19cefc6632.png)

But in Android 4.x, the prompt has changed into:
![image](https://user-images.githubusercontent.com/42978935/90107648-fb596d80-dcfd-11ea-8922-50fb9b5b2490.png)

So, In project prerequisites, let's be sure it says Android Studio 4.0.0 or higher. Then ask users to copy and paste the following code if they cannot directly enter superclass in a prompt:

```
package com.example.myamplifyapp;

import android.app.Application;
import android.util.Log;
import com.amplifyframework.AmplifyException;
import com.amplifyframework.core.Amplify;

public class MyAmplifyApp extends Application {
    @Override
    public void onCreate() {
        super.onCreate();

        try {
            Amplify.configure(getApplicationContext());

            Log.i("MyAmplifyApp", "Initialized Amplify");
        } catch (AmplifyException error) {
            Log.e("MyAmplifyApp", "Could not initialize Amplify", error);
        }
    }
}

```

**Comment by jamesonwilliams** [comment]
@changxu0306 What's the status of this #2238?

**Comment by changxu0306** [comment]
> @changxu0306 What's the status of this #2238?

The second issue has been addressed. The other two needs new pictures for reference. I can do that if needed.
