### ISSUE TITLE
[missing-page]

### ISSUE THREAD

**Issue by spirift** [aws-amplify/docs#2243]
**Page**: [`https://docs.amplify.aws/lib/storage/autotrack/q/platform/js`](https://docs.amplify.aws/lib/storage/autotrack/q/platform/js)

**Feedback**: I see a 404 when going directly to the page. When navigating from with the amplify docs the browser simple shows the same screen.

**Comment by mauerbac** [comment]
Hey @spirift - can you verify using an incognito window? Can you confirm what page you start on, what link you press and the behavior? Thank you

**Comment by spirift** [comment]
Seems to be related to the Brave browser. It works fine in Chrome. I think because the page is about tracking and the resources to the load the page have the word track in them it's blocking them. I'll raise that with the Brave team. Sorry for wasting your time a little
