### ISSUE TITLE
Amplify configure command overwrites existing default profile

### ISSUE THREAD

**Issue by gsans** [aws-amplify/docs#2252]
**Describe the bug**
After running amplify configure the default profile has been overwritten.

**Amplify CLI Version**
4.24.1

**To Reproduce**
`amplify configure`

**Expected behavior**
The default profile should be preserved for better interoperability with other libraries sharing profile information. See extract below from user.

**Screenshots**
NA

**Desktop (please complete the following information):**
OS: OS
Node Version: 14.5.0

**Additional context**
Issue reported during Amplify Days workshop

From Discord:
Guessing it would be better to maintain a separate profile in my ~/.aws/config file for Amplify. We're using us-west-1 for most things with our app so just noticed I overwrote my default config with us-west-2 :man_facepalming: should have been obvious to me

**Comment by offlineprogrammer** [comment]
Closed by the PR 2329
