### ISSUE TITLE
[missing-page] Getting Started with Amplify Flutter

### ISSUE THREAD

**Issue by rubensdemelo** [aws-amplify/docs#2257]
**Page**: [`https://docs.amplify.aws/start/getting-started/installation/q/integration/flutter`](https://docs.amplify.aws/start/getting-started/installation/q/integration/flutter)

**Feedback**: https://github.com/aws-amplify/amplify-flutter

**Comment by mauerbac** [comment]
Thanks @rubensdemelo ! Fix is here https://github.com/aws-amplify/amplify-flutter/pull/54
