### ISSUE TITLE
[Feedback] Minor issue - JavaScript docs say to "Add the files to the Xcode project"

### ISSUE THREAD

**Issue by JPVan** [aws-amplify/docs#2265]
**Page**: [`/lib/datastore/getting-started/q/platform/js`](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/js)

**Feedback**:

The JavaScript docs for Amplify - Getting Started - Code Generation Amplify CLI tell you to "Add the files to the Xcode project"
 - [https://docs.amplify.aws/lib/datastore/getting-started/q/platform/js#code-generation-amplify-cli](url)

No biggie obviously, but I thought you would like to know. Thanks! 

I briefly tried editing this rather than submitting an issue, but it wasn't obvious which file to edit. X) I did download the repository and searched file contents for Xcode, but Windows file search is kind of useless (even after enabling searching contents for non-indexed locations) and that's all I've got here at the moment.

**Comment by renebrandel** [comment]
@sammartinez is it possible that the reference is there because of React Native? If yes, we should make that clearer. If not, we should just remove the line as @JPVan suggested.

**Comment by sammartinez** [comment]
> @sammartinez is it possible that the reference is there because of React Native? If yes, we should make that clearer. If not, we should just remove the line as @JPVan suggested.

This seems to be specific to DataStore itself that when you codegen the models they are produced for you to place inside the project. But thanks for the feedback on this @JPVan ! We can be more clear on the fragment files that would need to be adjusted for this.

**Comment by JPVan** [comment]
Cool, thanks!
