### ISSUE TITLE
Drop-in UI for AWSMobileClient - Can't change the logo image (2.7.0)

### ISSUE THREAD

**Issue by Samnor** [aws-amplify/docs#227]
**Describe the bug**
Hi! I'm a IOS developer that uses  the drop-in auth ui. According to https://aws-amplify.github.io/docs/ios/authentication the logo can be changed easily through passing a UIImage to the AWSMobileClient.sharedInstance()
    .showSignIn() function. This does not work however. The default logo always shows up. My code looks as follows:
`
if(AWSMobileClient.sharedInstance().isSignedIn == false){
            AWSMobileClient.sharedInstance().showSignIn(navigationController: self.navigationController!, signInUIOptions: SignInUIOptions(canCancel: true, logoImage: UIImage(named: "Icon-Small"), backgroundColor: UIColor.black), { (result, error) in
                if(error == nil){       //Successful signin
                    print("now logged in")
                }
            })
        }
`

**To Reproduce**

**Expected behavior**
The default logo should be replaced by the custom image.
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
Iphone X

**Additional context**

**Comment by muellerfr** [comment]
Hello @Samnor,

sorry, you are running in this issue. We are already tacking the issue [here](https://github.com/aws-amplify/aws-sdk-ios/issues/1115). Please monitor this thread for updates.
