### ISSUE TITLE
[Feedback] One Bracket too much in Amplify.Storage.uploadData example code

### ISSUE THREAD

**Issue by ppoh71** [aws-amplify/docs#2272]
**Page**: [`/lib/storage/upload/q/platform/ios`](https://docs.amplify.aws/lib/storage/upload/q/platform/ios)

**Feedback**:

let dataString = "My Data"
let data = dataString.data(using: .utf8)!
Amplify.Storage.uploadData(key: "ExampleKey", data: data, 
    progressListener: { progress in
        print("Progress: \(progress)")
    }, resultListener: { event in
        switch event {
        case .success(let data):
            print("Completed: \(data)")
        case .failure(let storageError):
            print("Failed: \(storageError.errorDescription). \(storageError.recoverySuggestion)")
    }
) // ####### ----> This should not be here !!
})

The combine example has a problem too.

**Comment by mauerbac** [comment]
Thanks @ppoh71 - asking our iOS team to take a look @drochetti

**Comment by ppoh71** [comment]
Looking good again.
The Combine Version might have a problem too. 
Not using combine yet but it doesn't compile:

let storageOperation = Amplify.Storage.uploadData(key: "ExampleKey", data: data) 
// -> Missing argument for parameter 'resultListener' in call
