### ISSUE TITLE
Remove 'new' keyword

### ISSUE THREAD

**Issue by justinfargnoli** [aws-amplify/docs#2273]
**Page**: https://docs.amplify.aws/lib/project-setup/create-application/q/platform/flutter#n4-initialize-amplify-in-the-application

**Feedback**:

The code snipped uses the new keyword which [isn't recommend by the Dart language](https://dart.dev/guides/language/effective-dart/usage#dont-use-new).

**Comment by fjnoyp** [comment]
Thanks @justinfargnoli for bringing this to our attention.  We have a PR to fix the docs based on what you pointed out here.

**Comment by haverchuck** [comment]
@justinfargnoli Closing, as I believe this has been fixed.
