### ISSUE TITLE
Missing imports & variable declarations

### ISSUE THREAD

**Issue by justinfargnoli** [aws-amplify/docs#2274]
**Page**: https://docs.amplify.aws/lib/project-setup/create-application/q/platform/flutter#n4-initialize-amplify-in-the-application

**Feedback**:

The code snippet is missing import statements for `AmplifyAnalyticsPinpointPlugin()` and `AmplifyAuthCognito()` and does not initialize the `mounted` and `amplifyInstance` variables.

**Comment by fjnoyp** [comment]
Thanks @justinfargnoli for bringing this to our attention.  We have a PR to fix the docs based on what you pointed out here.

**Comment by haverchuck** [comment]
@justinfargnoli Closing, as I believe this has been fixed.
