### ISSUE TITLE
[Feedback]FEEDBACK_TITLE_HERE

### ISSUE THREAD

**Issue by pierina27** [aws-amplify/docs#2287]
**Page**: [`/sdk/push-notifications/setup-push-service/q/platform/android`](https://docs.amplify.aws/sdk/push-notifications/setup-push-service/q/platform/android)

**Feedback**:

This documentation sucks, It's very frustraiting, and confunsing.

**Comment by mauerbac** [comment]
Hey @pierina27 - can you provide a few details on what needs improving and what you would like to see?
