### ISSUE TITLE
[Feedback]<amplify-s3-album /> gives an ERROR

### ISSUE THREAD

**Issue by genisgen** [aws-amplify/docs#2289]
**Page**: [`/ui/storage/s3-album/q/framework/angular`](https://docs.amplify.aws/ui/storage/s3-album/q/framework/angular)

**Feedback**:

`<amplify-s3-album />` gives the following error.
```
ERROR in Errors parsing template: Only void and foreign elements can be self closed "amplify-s3-album" ("  <amplify-authenticator>
  <div>

[ERROR ->]<amplify-s3-album />

"):
```

The error can be simply avoided by `<amplify-s3-album></amplify-s3-album>` instead of  `<amplify-s3-album />`.

**Environment**:
amplify 4.27.3

Angular CLI: 10.0.7
Node: 12.18.3
OS: win32 x64

Angular: 10.0.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
@angular-devkit/architect         0.1000.7
@angular-devkit/build-angular     0.1000.7
@angular-devkit/build-optimizer   0.1000.7
@angular-devkit/build-webpack     0.1000.7
@angular-devkit/core              10.0.7
@angular-devkit/schematics        10.0.7
@angular/cli                      10.0.7
@ngtools/webpack                  10.0.7
@schematics/angular               10.0.7
@schematics/update                0.1000.7
rxjs                              6.5.5
typescript                        3.9.7

**Comment by mauerbac** [comment]
cc @gsans

**Comment by gsans** [comment]
This is because Angular doesn't support self enclosing HTML elements.

**Comment by genisgen** [comment]
It is really nice of you to have them fixed right away.
