### ISSUE TITLE
Amplify Authenticator Vue Handle Submit

### ISSUE THREAD

**Issue by tdevil3126** [aws-amplify/docs#2296]
**Describe the bug**
I can't access the handleSubmit prop from the Vue Authenticator component.  I'm trying to grab the username and set it to lowercase before it gets submitted for SignUp, SignIn, and Forgot Password.

**Expected behavior**
handleSubmit logs event

**Comment by mauerbac** [comment]
Could you tell us a bit more info? What versions are you using? Can you send a code sample?

**Comment by tdevil3126** [comment]
@mauerbac, @aws-amplify/ui-vue@0.2.8

I've attempted multiple variants to access handle submit.  

`<amplify-sign-up handleSubmit=consoleLog></amplify-sign-up>`
`<amplify-sign-up :handleSubmit=consoleLog></amplify-sign-up>`
`<amplify-sign-up @handleSubmit=consoleLog></amplify-sign-up>`

`consoleLog(event) {
      console.log(event);
    },`

I've also added the put consoleLog in "", {}, attempted console.log directly.

**Comment by tdevil3126** [comment]
@mauerbac I've updated to the latest version 0.2.14 since it appears handleSubmit was modified or added after 0.2.8 in the change logs.  I've attempted with the new version and still have the same issue.

**Comment by gsans** [comment]
This should work:

```
<amplify-sign-up :handleSubmit=consoleLog></amplify-sign-up>
```

Do you mind sharing your project on GitHub so I can troubleshoot?

**Comment by mauerbac** [comment]
@tdevil3126 - did you try this?

**Comment by calvinchso** [comment]
I'm also running into the same issue and can't make handleSubmit property to work. The handler I specify just doesn't get fired. What is the correct way to use "handleSubmit" property in "amplify-sign-up" ?

**Comment by juancpgo** [comment]
> This should work:
> 
> ```
> <amplify-sign-up :handleSubmit=consoleLog></amplify-sign-up>
> ```
> 
> Do you mind sharing your project on GitHub so I can troubleshoot?

Does this also work for web components?

**Comment by mrnexeon** [comment]
In Vue, use `:handleSubmit.prop="..."`
