### ISSUE TITLE
[Feedback] Missing Documentation

### ISSUE THREAD

**Issue by bjoern-from-kopply** [aws-amplify/docs#2297]
**Page**: [`/ui/q/framework/react-native`](https://docs.amplify.aws/ui/q/framework/react-native)

**Feedback**:

Hi, 
I just browsed through the UI components for React-Native and couldn't find a documentation for some components:
- S3 ImagePicker
- S3 Text
- S3 TextPicker

Cheers,
Bjoern :)

**Comment by mauerbac** [comment]
Thanks for reporting this @bjoern-from-kopply . I'm not sure why those sections are empty. Investigating.

**Comment by mauerbac** [comment]
This should be fixed here https://github.com/aws-amplify/docs/pull/2301
