### ISSUE TITLE
[Feedback]Syntax Error: Unterminated string constant '@aws-amplify/ui-components`

### ISSUE THREAD

**Issue by yvafdevnsk** [aws-amplify/docs#2303]
**Page**: [`/ui/auth/authenticator/q/framework/vue`](https://docs.amplify.aws/ui/auth/authenticator/q/framework/vue)

**Feedback**:

[AuthState](https://docs.amplify.aws/ui/auth/authenticator/q/framework/vue#authstate) > Usage  

```
import { AuthState, onAuthUIStateChange } from '@aws-amplify/ui-components`;
```

Last backtick is incorrect.
Use single quote instead of backtick.

**Comment by mauerbac** [comment]
Thank you @yvafdevnsk ! I'll put up a PR for this

**Comment by mauerbac** [comment]
Just added PR https://github.com/aws-amplify/docs/pull/2388

**Comment by mauerbac** [comment]
merged PR
