### ISSUE TITLE
Add Documentation for Custom Auth

### ISSUE THREAD

**Issue by palpatim** [aws-amplify/docs#2306]
We have not yet documented custom auth for Amplify Android and Amplify iOS. We need to do so, since customers are currently unclear whether this is a supported flow or not.

**Comment by palpatim** [comment]
@royjit has put the current steps in https://github.com/aws-amplify/aws-sdk-ios/issues/1567#issuecomment-681153259

**Comment by royjit** [comment]
PR - https://github.com/aws-amplify/docs/pull/2589

**Comment by royjit** [comment]
Added documentation for iOS. @TrekSoft can you check this for Android as well.

**Comment by TrekSoft** [comment]
I'll add a ticket for this to our backlog

**Comment by palpatim** [comment]
Resolved 

https://docs.amplify.aws/lib/auth/signin_with_custom_flow/q/platform/ios
