### ISSUE TITLE
Styling documentation for UI components ( --box-shadow)

### ISSUE THREAD

**Issue by elorzafe** [aws-amplify/docs#2307]
**Is your feature request related to a problem? Please describe.**
Add information related to styling for UI components.
```
  --background-color
  --width
  --min-width
  --border-radius
  --padding
  --margin-bottom
  --box-shadow
```
**Describe the solution you'd like**
Include this on the docs

**Additional context**
Original issue on JS repo https://github.com/aws-amplify/amplify-js/issues/6644

**Comment by siegerts** [comment]
Closing now since this is possible with the updated Authenticator component https://ui.docs.amplify.aws/components/authenticator#additional-css-styling.
