### ISSUE TITLE
[Feedback]FEEDBACK_TITLE_HERE

### ISSUE THREAD

**Issue by bombchu** [aws-amplify/docs#2312]
**Page**: [`/start/getting-started/data-model/q/integration/react`](https://docs.amplify.aws/start/getting-started/data-model/q/integration/react)

**Feedback**:

scrolling horizontally is not fun. Either have the webpage width to either resize when you zoom out, or put line wrap on the text or something. Thank you.

**Comment by mauerbac** [comment]
Would you say the sidebar is a root cause? https://github.com/aws-amplify/docs/issues/1813
