### ISSUE TITLE
Insufficient documentation on custom resolvers

### ISSUE THREAD

**Issue by ahansson89** [aws-amplify/docs#2316]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**

Custom AppSync resolvers

**Amplify CLI Version** 

Latest

**What AWS Services are you utilizing?**

AppSync

**Provide additional details e.g. code snippets**

I find the documentation for how to do custom resolvers insufficient.

The documentation does not mention where to store your custom VTL files.
From what I have read, there is no documentation on how to do simple things, like a conditional check between two fields: `if(field.one !== field.two) return null` in the Amplify documentation.
I know VTL can do more advanced stuff like proxying requests to and from a third party API such as Stripe, but I have found no documentation on that either.

Is it recommended that we use Lambda functions for anything custom? If so can the CLI at least create the base function with the basic functionality if @function is used? And if this is the way to go, why not just use Lambda functions as a standard vs using VTL at all?

**Comment by mauerbac** [comment]
Closing as this is outdated. Please let us know what can be improved in a new issue. Thank you
