### ISSUE TITLE
Multi-tenant design for secure app that include member users and multiple organizations

### ISSUE THREAD

**Issue by marianolc** [aws-amplify/docs#2317]
**Which Category is your question related to?**

Cognito, GraphQL, DynamoDB

**Amplify CLI Version** 

4.24.1

**What AWS Services are you utilizing?**

AppSync, Cognito, DynamoDB

**Provide additional details e.g. code snippets**

I'm trying to design a multi-tenant app using DataStore and AppSync. The app needs to follow the following rules:

1) Should allow free registration of an user account
2) Should allow the user to register an organization (a tenant). The user who registers an organization would become its admin
3) Should allow an admin to create staff records for his organization
4) Should allow admin to send invites to other registered users and upon verification that user would be registered as the staff with the specified role (admin or member)
5) Should allow a user to be a staff of multiple organizations
6) Should allow staff of an organization to manage (create, read, update & delete) they records.
7) Should allow admin to read all the data of all his staff
8) Should not allow user with member role to read/write records of other members of his and/or other organizations
9) Should not allow admin of an organization to read/write records of other organizations where he is not registered and/or is a member

_those rules are extracted from another blogpost for another engine/service._

(1) is achieved using cognito. This is no issue.

(2) This is achieved using the @auth directive with the owner field:

```
type Organization @model 
  @auth(rules: [{allow:owner}]) 
  @key(fields: ["owner","name"]) 
{
  id: ID!
  owner: ID!
  name: ID!
  description: String
}
```

_Note that i'm using owner+name as Partition Key and Sort Key with an extra ID field because DataStore needs that field to exists locally. So its basically using ID as local PK and owner+name as remote._

(4) Here is were the trouble begins. I know that amplify allow to add user to a group using code. But should the organizations become a cognito group to achieve this?

(6) This is the other big issue. This is basically row-level access for every user based on the organization(or group?) he belongs.

How can I achieve this kind of security access using amplify?

**Comment by marianolc** [comment]
Ok, seeing that the issue using developer authenticated identities is not going to be fixed soon I used the lamba route. If someone have the same issue as me this is how I solved it:

First created a dynamodb table for the user-company relations. Very simple just add the companies to jwt claims as a concatenated string separated with "|" :

```
type CompanyUsers @model @key(fields: ["user","company"])
{
  id: ID!
  user: ID!
  company: ID!
  role: String
} 
```

With that table I created a Lambda for the pre jwt generation:

```
var AWS = require("aws-sdk");
// Set the region
AWS.config.update({
    region: 'us-east-1'
});

// Create DynamoDB service object
var ddb = new AWS.DynamoDB({
    apiVersion: '2012-08-10'
});

exports.handler = (event, context, callback) => {
    const params = {
        TableName: 'xxx',
        KeyConditionExpression: "#user = :user",
        ExpressionAttributeNames: {            "#user": "user",         },
        ExpressionAttributeValues: {
            ":user": {                "S": event.userName             }
        }
    };

    const userCompanies = [];
     ddb.query(params, function(err, data) {
        if (err) {
            throw ("Unable to query. Error:" + JSON.stringify(err, null, 2));
        }
        else {
            console.log("Query succeeded.");
            data.Items.forEach(function(item) {
                userCompanies.push(item.company['S'])
            });

            if (userCompanies.length === 0)
                throw "No companies for user: " + userCompanies.length;

            event.response = {
                "claimsOverrideDetails": {
                    "claimsToAddOrOverride": {
                        // replace this with DynamoDB
                        "organizations": userCompanies.join('|')
                    }
                }
            };
            // Return to Amazon Cognito
            callback(null, event);
        }
    });
};

```

This will bring the Companies in the session token. Note that for use this token in the resolvers you need to add it manually client side ( from https://github.com/aws-amplify/amplify-cli/issues/2192 ) . Like this:

```
Amplify.configure(awsconfig);

Amplify.configure({
  API: {
    graphql_headers: async () => {
    const session = await await Amplify.Auth.currentSession()
    return ({
        'Authorization': session.getIdToken().getJwtToken()
    })}
  }
});
```

Now you can use $ctx.identity.claims.get("organizations") in the resolvers. 

For the resolver I just added this in the top:

```
## ************************************************************
## ************************************************************
## simple check. this value is mandatory
#if( $util.isNull($ctx.args.organization) )
    $util.error("organization is mandatory", "InvalidArgumentsError")
#end

## check flag default false = not found **
#set( $isLocalOwnerAuthorized = false )

## split organization values to array
#set( $organizations = $util.defaultIfNull( $ctx.identity.claims.get("organizations"),"__ERROR__") )

#if( $organizations == "__ERROR__" )
    $util.error("no companies in token", "InvalidArgumentsError")
#end
#set( $myList = $organizations.split("[|]"))
#foreach( $organization in $myList )    	
    #if( $organization == $ctx.args.organization )    
        #set( $isLocalOwnerAuthorized = true )
    #end
#end

#if( $isLocalOwnerAuthorized == false )
	#set( $err = "user trying to use wrong organization $organizations" )
    $util.error($err, "InvalidArgumentsError")
#end 

## ************************************************************
## ************************************************************
```

Very simple. It just force the filter for organization and check that the organization is listed in the JWT.

If someone have any suggestion, comment or critic about this approach... please do!

**Comment by econtentmaps** [comment]
I have to say, this has been as useful a collection of words as I think I've ever read. Thank you all for your insight. I have one small question, if I may... Is it possible to just import the one, common block of velocity into all resolvers with some sort of magic, or do they all need overwriting?

**Comment by istais** [comment]
I would also like to thank you for this very interesting discussion. I wonder how many extra seconds (delay) this approach adds in the existing authentication process. I estimated that the function (with graphql & axios) needs 3 seconds

**Comment by mauerbac** [comment]
Going to close this issue as it seems like a discussion that has concluded. If you have future docs improvements or requests, please open a new issue!
