### ISSUE TITLE
Complete new password does not exist :( 

### ISSUE THREAD

**Issue by sphairo** [aws-amplify/docs#2319]
**Describe the bug**
There is no method to complete the step of creating a new password

**To Reproduce**
we just need to use *Amplify.Auth. ?? *
no method allows to execute a complete new password.

**Expected behavior**

**Environment(please complete the following information):**
 - Amplify (1.1.0)
 - AmplifyPlugins/AWSCognitoAuthPlugin (1.1.0)
 - Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: any device or simulator
 - iOS Version:  iOS 11

**Additional context**
In the javascript documentation the implementation appears but in the iOS documentation there is nothing similar

For example:
[Reference to Docs amplify](https://docs.amplify.aws/lib/auth/manageusers/q/platform/js#complete-new-password)

**Comment by palpatim** [comment]
The Android & iOS `signIn` flow will return a next step of `confirmSignInWithNewPassword` in cases where a new password is required (e.g., Admin-provided initial passwords); we need to document the correct way to call `Amplify.Auth.confirmSignIn()` with the appropriate new password and username payload for those cases.

**Comment by sphairo** [comment]
I have solved the problem thanks to the answer @palpatim 

My code is this: 

`_ = Amplify.Auth.signIn(username: username, password: password, options: nil, listener: { signResult in
                let result = try? signResult.get()
                if let nextStep = result?.nextStep {
                    print(nextStep)
                    
                    switch nextStep {
                    case .confirmSignInWithSMSMFACode(_, _):
                        print("SignIn::: confirmSignInWithSMSMFACode")
                        break
                    case .confirmSignInWithCustomChallenge(_):
                        print("SignIn::: confirmSignInWithCustomChallenge")
                        break
                    case .confirmSignInWithNewPassword(_):
                        Amplify.Auth.confirmSignIn(challengeResponse: "hereYourNewPassword") { operationResult in
                            switch operationResult {
                            case .success(let success):
                                print("success --confirmSignIn: \(success)")
                            case .failure(let error):
                                print("failure --confirmSignIn: \(error.localizedDescription)")
                            }
                        }
                        print("SignIn::: confirmSignInWithNewPassword")
                        break
                    case .resetPassword(_):
                        print("SignIn::: resetPassword")
                        break
                    case .confirmSignUp(_):
                        print("SignIn::: confirmSignUp")
                        break
                    case .done:
                        print("SignIn::: done")
                        break
                    }
                }
                
                switch signResult {
                    
                case .success(_):
                    print("SignIn :::OK")
                    isLogedIn = true
                    getToken()
                    break
                case .failure(let error):
                    print("SignIn :::ER -> \(error)")
                    isLogedIn = false
                    DispatchQueue.main.async {
                        completion?(isLogedIn)
                    }
                    break
                }
            })`

**Comment by palpatim** [comment]
@sphairo Glad you were able to figure that out. As you discovered, the correct call for iOS is `Amplify.Auth.confirmSignIn(challengeResponse: "the new password")`. Amplify retains the state of the sign in challenge for the current app session, so you don't have to send the username.
