### ISSUE TITLE
[Feedback]IAM Access Least Privilege on AWS CLI Install documentation

### ISSUE THREAD

**Issue by sigitp-git** [aws-amplify/docs#2320]
**Page**: [`/cli/start/install`](https://docs.amplify.aws/cli/start/install)

**Feedback**:

Let's put warning that users created have to follow https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html guide and https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html#grant-least-privilege guide.

Administrator Access users here are only for example tutorial, in the real world, users have to limit best on least privilege principles.

**Comment by markstos** [comment]
Yes. Please provide an alternative to requiring admin access during setup.

Also, please clarify up front which permissions are needed for one-time setup compared ongoing use.

**Comment by markstos** [comment]
If it's AWS is to be leader in a web security, please stop advising using Administrator Access for project setup merely because it's convenient. Follow the best practice of use an IAM policy with minimal allowed permissions.

**Comment by markstos** [comment]
Imagine a malicious typo'ed version of this package that offers the same wizard of suggesting users go creating a new "Admin Access" account and then feeding the credentials back to the malicious script. A whole business could be destroyed due to the overly broad permissions request.  

Set a better example, Amazon. Follow your own advice to grant least privileges!

**Comment by markstos** [comment]
@sigitp-git @renebrandel @yuth I see that following AWS security best practices was moved from "High priority" to "more conversation needed" a year ago. So what conversation is needed here? What's the rationale for not providing a documented setup option that follows security best practices of granting only the permissions required for the task at hand?

**Comment by renebrandel** [comment]
The PR is merged. Now please @-mention me if there's anything else regarding this :-) Thanks for raising the issue.
