### ISSUE TITLE
[Feedback]iOS API Subscription guide is in JS when it should be in Swift

### ISSUE THREAD

**Issue by michaelgutierrez0** [aws-amplify/docs#2323]
**Page**: [`/guides/api-graphql/subscriptions-by-id/q/platform/ios`](https://docs.amplify.aws/guides/api-graphql/subscriptions-by-id/q/platform/ios)

**Feedback**:

Hi, I am looking at the above page for example code and the code for iOS is in JS but I need it in swift since it is an iOS page.

**Comment by palpatim** [comment]
Thanks for the report, we'll get that taken care of. In the meantime, you can use https://docs.amplify.aws/lib/graphqlapi/subscribe-data/q/platform/ios to see the iOS code for subscribing to GraphQL mutations.

**Comment by leungy2** [comment]
Even in the link you sent above, it doesn't show how to pass in subscription arguments for the iOS code. Any chance there is one for passing in subscription arguments?

**Comment by lawmicha** [comment]
Hi @leungy2, currently there isn't a way to pass subscription arguments when using the static builders, ie. `Amplify.API.subscribe(.onCreate())`. you will have to create a custom GraphQL document and set the responseType to the codegenerated Model like https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/ios#subset-of-data

**Comment by lawmicha** [comment]
hi @leungy2, feel free to take a look at https://github.com/aws-amplify/docs/pull/2465/files#diff-8206f27647e697d277d95eac4e0cb045 for the code snippet of the guide.

**Comment by mauerbac** [comment]
This has been addressed
