### ISSUE TITLE
[Feedback]AWS.Signers class no longer exists in node.js SDK but is referenced in doc

### ISSUE THREAD

**Issue by markjaniczak** [aws-amplify/docs#2336]
**Page**: [`/lib/graphqlapi/graphql-from-nodejs/q/platform/js`](https://docs.amplify.aws/lib/graphqlapi/graphql-from-nodejs/q/platform/js#mutation)

**Feedback**:

AWS.Signers class no longer exists in the node.js SDK, or at least is no longer documented and is not typed. Referring to [this documentation](https://github.com/aws/aws-sdk-js).

**Comment by sammartinez** [comment]
This is correct, please refer to this [documentation](https://github.com/aws/aws-sdk-js-v3/#configuration) within the AWS SDK repository for more information on this.
