### ISSUE TITLE
[Feedback]How to use Amplify in Javascript browser mode?

### ISSUE THREAD

**Issue by alucard001** [aws-amplify/docs#2344]
**Page**: [`/start/q/integration/js`](https://docs.amplify.aws/start/q/integration/js)

**Feedback**:

- If I am using browser mode like this: `<script src="https://sdk.amazonaws.com/js/aws-sdk-2.744.0.min.js"></script>`, how are we going to use it?  Are there any example that allow us to do so?

- If I want to integrate it with Google Tag Manager, how are we going to do it?

Please give us full, completed example(s).

Thank you.

**Comment by mauerbac** [comment]
hi @alucard001 - can you elaborate a bit more? I'm not sure what you mean by browser mode? Did you go through the entire guide you linked ? Were you looking for info here? https://aws.amazon.com/sdk-for-browser/
