### ISSUE TITLE
[Feedback] CLI example not accurate to what appears in current release 

### ISSUE THREAD

**Issue by Billy1s** [aws-amplify/docs#2345]
**Page**: [`/lib/datastore/getting-started/q/platform/js`](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/js)

**Feedback**:
Within the  "Option 2: Use Amplify CLI" section the following step is missing in the shown example

 Choose a schema template:
  Single object with fields (e.g., “Todo” with ID, name, description)
 One-to-many relationship (e.g., “Blogs” with “Posts” and “Comments”)

also the bottom two examples shown no longer appear in the cli

? Do you want a guided schema creation?
    `No`
? Provide a custom type name
    `Post`

**Comment by mauerbac** [comment]
hi @Billy1s - I was not able to replicate your issue. Can you try going through the steps again and ensure you make the correct selections. 
![Screen Shot 2020-09-10 at 12 27 59 PM](https://user-images.githubusercontent.com/1507886/92763049-2963b900-f361-11ea-9e17-a64c775df942.png)

**Comment by Billy1s** [comment]
Hey @mauerbac , just updated amplify and ran through it again. Screenshot below.

For reference this is from a windows machine and inside a vuejs project. 

![image](https://user-images.githubusercontent.com/42093840/92768918-6004f800-f390-11ea-9d03-0772e8f1ff9e.png)

**Comment by renebrandel** [comment]
HI @Billy1s - you've correctly identified a bug. I'll update this later today.
