### ISSUE TITLE
Clarify support for AppSync's GraphQL Directives

### ISSUE THREAD

**Issue by jamesonwilliams** [aws-amplify/docs#2350]
The Amplify CLI documentation [discusses a number of AppSync's GraphQL directives](https://docs.amplify.aws/cli/graphql-transformer/directives):

1. [`@auth`](https://docs.amplify.aws/cli/graphql-transformer/directives#auth)
2. [`@connection`](https://docs.amplify.aws/cli/graphql-transformer/directives#connection)
3. [`@function`](https://docs.amplify.aws/cli/graphql-transformer/directives#function)
4. [`@http`](https://docs.amplify.aws/cli/graphql-transformer/directives#http)
5. [`@key`](https://docs.amplify.aws/cli/graphql-transformer/directives#key)
6. [`@model`](https://docs.amplify.aws/cli/graphql-transformer/directives#model)
7. [`@predictions`](https://docs.amplify.aws/cli/graphql-transformer/directives#predictions)
8. [`@searchable`](https://docs.amplify.aws/cli/graphql-transformer/directives#searchable)
9. [`@versioned`](https://docs.amplify.aws/cli/graphql-transformer/directives#versioned)

Some of these AppSync directives (`@model`, `@auth`) are central the the public APIs/customer experience on all platforms.

Others (like `@predictions`, as an example) are definitely _not_ supported on some platforms (iOS, Android).

----------------------

1. Are these AppSync directives supported in the **API category**? If so, on which platforms?

|              | iOS | JS | Android | Flutter | RN |
|--------------|-----|----|---------|---------|----|
| @auth        |     |    |         |         |    |
| @connection  |     |    |         |         |    |
| @function    |     |    |         |         |    |
| @http        |     |    |         |         |    |
| @key         |     |    |         |         |    |
| @model       |     |    |         |         |    |
| @predictions |     |    |         |         |    |
| @searchable  |     |    |         |         |    |
| @versioned   |     |    |         |         |    |

2. Are these AppSync directives supported in the **DataStore**? If so, on which platforms?

|              | iOS | JS | Android | Flutter | RN |
|--------------|-----|----|---------|---------|----|
| @auth        |     |    |         |         |    |
| @connection  |     |    |         |         |    |
| @function    |     |    |         |         |    |
| @http        |     |    |         |         |    |
| @key         |     |    |         |         |    |
| @model       |     |    |         |         |    |
| @predictions |     |    |         |         |    |
| @searchable  |     |    |         |         |    |
| @versioned   |     |    |         |         |    |

**Comment by mauerbac** [comment]
Thanks @jamesonwilliams. This is a great initiative. Will work with @renebrandel on this one.

**Comment by renebrandel** [comment]
we're addressing this as part of an "FAQ" that we're developing.
