### ISSUE TITLE
[Feedback]FEEDBACK_TITLE_HERE

### ISSUE THREAD

**Issue by s37justin** [aws-amplify/docs#2354]
**Page**: [`/guides/api-graphql/graphql-pagination/q/platform/js`](https://docs.amplify.aws/guides/api-graphql/graphql-pagination/q/platform/js)

**Feedback**:

The example of passing in a `nextToken` to do pagination isn't very helpful. Can you please show how the `nextToken` from one request is passed to the next request until all results have been returned? The code provided in this page doesn't fit very well with the example created in the Get Started guide (https://docs.amplify.aws/start/getting-started/data-model/q/integration/js#testing-your-api)

**Comment by mauerbac** [comment]
Hey @dabit3 - this looks like feedback with one of the guides. Would you mind taking a look? https://docs.amplify.aws/guides/api-graphql/graphql-pagination/q/platform/js

**Comment by dabit3** [comment]
Hey @s37justin , great feedback. I agree. We will get this updated soon. Thanks for the issue!

**Comment by dabit3** [comment]
Hey, check out the updated docs, we've added more clarity on how this works.
