### ISSUE TITLE
Update Social Sign-in with Google UI screenshots

### ISSUE THREAD

**Issue by junos-citrus21** [aws-amplify/docs#2364]
**Is your feature request related to a problem? Please describe.**
https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/android
The Google Cloud UI has changed. "Social sign in with web UI" document is old.

**Describe the solution you'd like**
So it would be nice to update "Social sign in with web UI" official manual.

**Describe alternatives you've considered**

**Additional context**

**Comment by mauerbac** [comment]
Thanks for pointing that out. Will flag to update screenshots.

**Comment by junos-citrus21** [comment]
I find it now.
https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/ios

and iOS "Social sign in with web UI" document is old.

**Comment by jpignata** [comment]
This isn't Android specific, but rather is documentation shared by all platforms.
