### ISSUE TITLE
Flutter Auth Documentation

### ISSUE THREAD

**Issue by chrisandrew** [aws-amplify/docs#2365]
**Page**: [`/lib/auth/signin/q/platform/flutter`](https://docs.amplify.aws/lib/auth/signin/q/platform/flutter)

**Feedback**:

The tutorial/walk-through is missing critical steps. For example, the code displayed for the Auth flow doesn't indicate which file, method, or function it should belong to.

**Comment by mauerbac** [comment]
Thank you @chrisandrew . Will flag to the Flutter team to review the tutorial.

**Comment by mlabieniec** [comment]
@chrisandrew can you let us know which steps you think are missing? FYI there is also a fully working Auth example with all the code within the library and pub.dev: https://pub.dev/packages/amplify_auth_cognito/example
