### ISSUE TITLE
[Feedback] Docs API Is inaccurate

### ISSUE THREAD

**Issue by adamfillion** [aws-amplify/docs#2366]
**Page**: [`/lib/auth/signin/q/platform/flutter`](https://docs.amplify.aws/lib/auth/signin/q/platform/flutter)

**Feedback**:

Looks like the API calls are out of date, in my project I had to use:
```

    AmplifyAuthCognito authPlugin = AmplifyAuthCognito();
    AmplifyAnalyticsPinpoint analyticsPlugin = AmplifyAnalyticsPinpoint();

    amplifyInstance.addPlugin(
        authPlugins: [authPlugin], analyticsPlugins: [analyticsPlugin]);
```

whereas in the document it suggests:

Amplify.addPlugin(new AWSCognitoAuthPlugin());
Amplify.addPlugin(new AmplifyAnalyticsPinpointPlugin());

**Comment by fjnoyp** [comment]
Thanks @adamfillion for bringing this to our attention.  We'll fix it and update the docs.

**Comment by haverchuck** [comment]
@adamfillion Thanks for the feedback. Did you receive an error message when you attempted to use two separate calls? When you say "in the document", which document are you referring to, exactly?
