### ISSUE TITLE
[Feedback]FEEDBACK_TITLE_HERE

### ISSUE THREAD

**Issue by davidallenmann** [aws-amplify/docs#2368]
**Page**: [`/ui/q/framework/vue`](https://docs.amplify.aws/ui/q/framework/vue)

**Feedback**:
https://docs.amplify.aws/ui/auth/authenticator/q/framework/vue#usage
This is a helpful addition for managing changing auth states.
Looks like the last App.Vue codeblock was left over from previous doc.

**Comment by gsans** [comment]
Hi David! Thanks for your feedback.

Regarding the last App.Vue codeblock. Are you referring to this section?
https://docs.amplify.aws/ui/auth/authenticator/q/framework/vue#manage-auth-state-and-conditional-app-rendering
