### ISSUE TITLE
Importing Aurora serverless datasource, not relevat documentation

### ISSUE THREAD

**Issue by lenarmazitov** [aws-amplify/docs#2384]
Hi, currently in documentation noted that
```
The Amplify CLI currently supports importing serverless Amazon Aurora MySQL 5.6 databases running in the us-east-1 region
```
https://docs.amplify.aws/cli/graphql-transformer/relational

But when I perform 
```
amplify api add-graphql-datasource
```

I've get 
<img width="708" alt="Screenshot 2020-09-11 at 18 09 14" src="https://user-images.githubusercontent.com/600133/92942237-00731f00-f45a-11ea-875e-a20c7a153ada.png">

P.S
Will you plan to support eu-central-1 region?

**Comment by mauerbac** [comment]
hi @lenarmazitov - im a bit confused by your statement. The documentation should list all the regions that are supported? Not sure about `eu-central-1` let me do some digging on that.
