### ISSUE TITLE
[Feedback] InvalidDirectiveError: @auth directive error in Next.js tutorial

### ISSUE THREAD

**Issue by ForwardslashDevelopment** [aws-amplify/docs#2397]
**Page**: [`/start/getting-started/data-model/q/integration/next`](https://docs.amplify.aws/start/getting-started/data-model/q/integration/next)

**Feedback**:

*IT FUCKIN SUCKED!  WASTED SO MANY HOURS WITH ERRORS..*  **InvalidDirectiveError: @auth directive with 'userPools' provider found, but the project has no Cognito User Pools authentication provider configured.**  TRY ADDING THAT IN NEXT FUCKING TIME

**Comment by renebrandel** [comment]
Hi @ForwardslashDevelopment - We take customer feedback very seriously but please ensure you follow our code of conduct: https://aws.github.io/code-of-conduct
