### ISSUE TITLE
Errors in Next.js tutorial

### ISSUE THREAD

**Issue by ForwardslashDevelopment** [aws-amplify/docs#2398]
**Page**: [`/start/getting-started/installation/q/integration/next`](https://docs.amplify.aws/start/getting-started/installation/q/integration/next)

**Feedback**:
[redacted].**

**Comment by renebrandel** [comment]
Hi @ForwardslashDevelopment - We take customer feedback very seriously but please ensure you follow our code of conduct: https://aws.github.io/code-of-conduct
