### ISSUE TITLE
[Feedback] Amplify Next.js getting started

### ISSUE THREAD

**Issue by vvo** [aws-amplify/docs#2408]
**Page**: [`/start/q/integration/next`](https://docs.amplify.aws/start/q/integration/next?sc_channel=sm&sc_campaign=Mobile_Campaign&sc_publisher=TWITTER&sc_country=Mobile&sc_geo=GLOBAL&sc_outcome=awareness&trk=sm-mobile-community_TWITTER&linkId=99672898)

**Feedback**:

1. Hi there, while trying the tutorial, one thing that I completely missed is that I had to press `SPACE` when selecting "Amazon Cognito User Pool". It would be nice to indicate that next to the terminal output in the getting started page:

`# Amazon Cognito User Pool (press space to select it)`

2. Click on "If you’d like to go ahead and connect the front end, you can jump to the next step." leads to nothing. 

3. Default signup form says phone number is mandatory, it has only US phone numbers. And the code is then sent by email if you do not provide a phone number. This is not very easy to understand (people will stop here). We could ship a version that removes the phone number from the UI (I found that in the AuthController docs)

4. Last deploy step says "Note: Amplify Console is adding support for Server-Side Rendering (SSR). Vote & comment on this issue to show your support!" while I thought it was supported from reading the announcement of amplify + Next.js :) It was fine, but I was surprised

5. Link to UI components renders empty pages like https://docs.amplify.aws/ui/auth/authenticator/q/framework/next

That's it! Thanks :)

**Comment by mauerbac** [comment]
cc @ericclemmons

**Comment by ericclemmons** [comment]
@vvo Great feedback!

1. I agree, this is easy to miss. It's tough to document the interactive CLI behavior. @renebrandel How should we better document this? Is there an example I can model after that works well?

2. I'll fix that!

3. The `<AmplifyAuthenticator />` form only has US phone numbers? The country code is a drop-down on the front, but I'll check it again...

4. Ah yes, I can see that. Amplify JS didn't officially support to SSR until lately.  You could always deploy SSG sites with Amplify Console (like CRA, Gatsby, & Next.js), but the missing piece are the dynamic routes.

**Comment by vvo** [comment]
As for the phone number: I completely missed the fact that the +xx were international numbers. Maybe adding the country info would be sufficient. + indicating that either email or phone is required, noth both (in the UI they were both marked as *required).

Thanks, and good luck!

**Comment by mauerbac** [comment]
hey @harrysolovay , do you mind reviewing the attached PR and updating this issue?
