### ISSUE TITLE
PubSub documented configuration doesn't work

### ISSUE THREAD

**Issue by maximelebastard** [aws-amplify/docs#2413]
**Describe the bug**
I want to add PubSub to my Amplify app, for authenticated users. I followed exactly the procedure described here:
https://docs.amplify.aws/lib/pubsub/getting-started/q/platform/js

- I created an IoT Policy
````
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "iot:*",
      "Resource": "arn:aws:iot:eu-west-1:123123123123:*/*"
    }
  ]
}
````
- I attached this policy to my Cognito Identity 
```
aws iot attach-principal-policy --policy-name 'OtherIotPolicy' --principal 'eu-west-1:6xxxxxxxxxxxxxxxxx'
```
- I also attached the policies `AWSIoTDataAccess` and `AWSIoTConfigAccess` to my authRole and unauthRole from the root stack of the Amplify project.

Despite of that, I still get that client error when subscribing:
```
error: {invocationContext: undefined, errorCode: 8, errorMessage: "AMQJS0008I Socket closed."}
```

And in the Cloudwatch logs of AWS IoT that I enabled I get
```
{     "timestamp": "2020-07-12 14:25:54.988",     "logLevel": "ERROR",     "traceId": "9d0xxx",     "accountId": "4xxxxx",     "status": "Failure",     "eventType": "Connect",     "protocol": "MQTT",     "clientId": "ddxxxxx",     "principalId": "Axxxxxx:CognitoIdentityCredentials",     "sourceIp": "xxxxx",     "sourcePort": 57696,     "reason": "AUTHORIZATION_FAILURE",     "details": "Authorization Failure" }
````

- 
**To Reproduce**

Follow the documentations steps https://docs.amplify.aws/lib/pubsub/getting-started/q/platform/js#aws-iot

**Expected behavior**
I should be able to subscribe and published to IoT as I'm a logged user.

**What is Configured?**
- Authentication
- API
- Storage

**Comment by mauerbac** [comment]
TODO: getting started guides, setup full stack project 
For IE 11 support, please refer to babel polyfills -> https://reactjs.org/docs/javascript-environment-requirements.html

**Comment by sammartinez** [comment]
Unable to reproduce this, please let us know if you are still experiencing this issue with the callout above. Thanks!
