### ISSUE TITLE
[Feedback]Create React App --> Next App

### ISSUE THREAD

**Issue by paragbaxi** [aws-amplify/docs#2418]
**Page**: [`/start/q/integration/next`](https://docs.amplify.aws/start/q/integration/next)

**Feedback**:

`In this case it knew we are using Create React App and provided the proper configuration for type of app, framework, source, distribution, build, and start options.`

Change `Create React App` to `Create Next App`.

**Comment by mauerbac** [comment]
Good catch. Thank you @paragbaxi . just created a PR
