### ISSUE TITLE
[Feedback] Unclear documentation

### ISSUE THREAD

**Issue by cwinters8** [aws-amplify/docs#2420]
**Page**: [`/lib/graphqlapi/authz/q/platform/js`](https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/js)

**Feedback**:
On the above mentioned page, there is this section:
![image](https://user-images.githubusercontent.com/40615752/93723598-b3c3ce00-fb54-11ea-8786-702d9d79acba.png)
I find it pretty unclear how withAuthenticator would provide the token in this case. I will likely go with just passing the jwtToken directly but I wanted to give some feedback here in case there might be some clarification added to that particular section. 

I genuinely appreciate the Amplify tooling and docs, and my only goal here is to further improve the developer experience. Thanks for all that you do.

**Comment by mauerbac** [comment]
Sorry for that. This is documented here https://docs.amplify.aws/ui-legacy/auth/authenticator/q/framework/react#using-withauthenticator-hoc
