### ISSUE TITLE
[Feedback] Imports not included in Android code samples

### ISSUE THREAD

**Issue by LeoSalemann** [aws-amplify/docs#2421]
**Page**: [`/start/getting-started/setup/q/integration/android`](https://docs.amplify.aws/start/getting-started/setup/q/integration/android#what-well-build)

**Feedback**:

MyAmplifyApplication.java wouldn't build unless I added a bunch of import lines to it. [Here's the commit in my repo](https://github.com/LeoSalemann/AmplifyAndroidTutorial/commit/ba43da04a16b0e4cd8ea018dd7472895e25112a6)

**Comment by mauerbac** [comment]
@jpignata - could you take a look at this?

**Comment by jpignata** [comment]
Heya @LeoSalemann! Thanks for the feedback. I intentionally omitted the import statements as your IDE should add them automatically as you resolve each token through your IDE. In user testing this seemed to work and reduced the amount of noise in code samples. Can you let me know your thoughts on our decision, and if you'd like to see the imports explicitly added?

**Comment by LeoSalemann** [comment]
Wow, you folk are quick!  Thanks for replying.

I’m a fan of clean code samples, but tbh I’m also a fan of code that ‘just works’ when it’s pasted into the IDE.  I’m a total n00b to Android dev in general, so the less friction the better.

That said, if everyone’s import statements are going to vary, it makes sense to leave them out, but add a couple lines of text explaining what users need to do/right-click in order to get the import statements they need.


BTW, I was running a Win10 VM in virtual box, hosted on a MacBook Pro, so perhaps my infrastructures a bit exotic.

Happy to help if you have additional questions.  Thanks again for jumping on this!

> Leo

**Comment by jpignata** [comment]
Hmm interesting. Yeah, in general in Android Studio you can resolve imports automatically when prompted here: https://www.jetbrains.com/help/idea/creating-and-optimizing-imports.html. This is pretty standard for IntelliJ, and what we're relying on. Can you let me know if that works for you?

**Comment by LeoSalemann** [comment]
I tried it a couple more times, and it’s kinda inconsistent.  Sometimes I get prompts in Android Studio; sometimes I just get red text. Sometimes I get a prompt to click ‘import’; sometimes I get a prompt to het Alt+Enter.

Here’s some examples from my  Insta:
1. Initial file <https://www.instagram.com/p/CFanRrDlEBY/?utm_source=ig_web_copy_link>
2. Pasted from tutorial, no prompts <https://www.instagram.com/p/CFang84F29g/?utm_source=ig_web_copy_link>
3. Got a prompt to import class after mousing on some red text.  <https://www.instagram.com/p/CFan1t0FzMD/?utm_source=ig_web_copy_link>
4. Got a prompt to hit Alt+Enter after more mousing on red text. <https://www.instagram.com/p/CFaoKnSlzPQ/?utm_source=ig_web_copy_link>

The clean text with no import lines in the tutorial is okay, but IMHO it’d be good to add a bit of verbiage between steps 5 and 6 of Configure Amplify and DataStore, to explain how to handle the red text and potential popups.

Best,
> Leo

**Comment by jpignata** [comment]
Thanks, @LeoSalemann! We'll include a callout here to help customers resolve imports.
