### ISSUE TITLE
[Feedback]Teardown instructions would be good

### ISSUE THREAD

**Issue by chkothe** [aws-amplify/docs#2424]
**Page**: [`/start/q/integration/react`](https://docs.amplify.aws/start/q/integration/react)

**Feedback**:

It would be good to explain how to deprovision the created demo stack in line with other AWS services' getting-started tutorials. Especially because hitting "delete application" in the amplify console didn't seem to actually delete the cfn stacks.

**Comment by mauerbac** [comment]
This is a great point. Will work on adding these instructions. Thank you
