### ISSUE TITLE
Discord invite invalid

### ISSUE THREAD

**Issue by thomasklein-winemaker** [aws-amplify/docs#2434]
Click on "Open Chat" and end up [here](https://discord.com/invite/jWVbPfC) - which is the discord page for invalid/expired invites.

<img width="357" alt="Screenshot 2020-09-23 at 10 47 59" src="https://user-images.githubusercontent.com/64782880/93989516-47caab00-fd8a-11ea-9c14-ead0e3021a9b.png">

**Comment by mauerbac** [comment]
hey @thomasklein-winemaker - what is the error you get? I'm not able to replicate it. Do you have the Discord desktop client? Can you try discord.gg/amplify ? Please provide more info. thank you

**Comment by thomasklein-winemaker** [comment]
Turns out I needed to reauthenticate - but the discord error message was confusing:

<img width="524" alt="Screenshot 2020-09-23 at 16 58 04" src="https://user-images.githubusercontent.com/64782880/94030495-2c799300-fdbe-11ea-92c6-dbc22401e439.png">

All good now, thanks!
