### ISSUE TITLE
[Feedback] missing description of backend-config.json

### ISSUE THREAD

**Issue by cyrfer** [aws-amplify/docs#2437]
**Page**: [`/cli/reference/files`](https://docs.amplify.aws/cli/reference/files)

I think the intention of this page includes describing `amplify/backend/backend-config.json`.

A proper description is critical for allowing developers to enhance this file as needed for addition of custom cloudformation described here:
https://docs.amplify.aws/cli/usage/customcf

**Comment by cyrfer** [comment]
@renebrandel the “improved” docs are too light. How about describing the schema of the file before closing this ticket?

**Comment by reberthkss** [comment]
Indeed, the document was added don't explain all possible parameters for `backend-config.json`.

**Comment by renebrandel** [comment]
Hey - sorry for missing the comments after closure. We're rethinking the files overall right now to:
- reduce the number of file overall that Amplify provides (less noisy)
- reduce customer dependencies on the backend-config.json. For example, making add custom resources easier without touching this file.

**Comment by cyrfer** [comment]
@renebrandel where are the priorities documented for Amplify? I worry you are trying to change what is already working, rather than filling gaps of what is not working.

It's not hard to add a few lines of JSON to backend-config.json. It would be nice if you documented what can be added, hence this ticket.
