### ISSUE TITLE
Cannot find file '../aws-exports' - now worse than ever

### ISSUE THREAD

**Issue by Trevor-mc2** [aws-amplify/docs#2438]
**Describe the bug**
To configure Amplify to use an API, the documentation explains that you should reference a file called aws-exports.js. This works fine locally because it's created locally. But when I commit the file and pull it from the repo, the build complains that it's not there. The docs don't explain where this file should be remotely and how you can refer to a file locally yet not check it in.

That file should be generated automagically by AMP, as part of the online-build/deploy process, but apparently it is not being created (or is not being created by the time the front end tries to reference it).

**To Reproduce**
1. Create a react js application
2. Initialize the application with amplify init
3. Notice init creates the src/aws-exports.js file and correctly adds it to the .gitignore file
4. Add this code to your App.js file:
```javascript
import Amplify from 'aws-amplify';
import aws_exports from '../aws-exports';

Amplify.configure(aws_exports);
```
5. Run the application locally. It works correctly.
6. Run amplify push
7. Look at the Frontend build output and notice it fails to build

**Expected behavior**
_The app's front end deploys successfully_

**Screenshots**

**Desktop (please complete the following information):**
- N/A

**Smartphone (please complete the following information):**
- N/A

**Additional context**
This problem was dismissed in https://github.com/aws-amplify/docs/issues/503 ...and it's gotten worse since then.  People who used to be able to deploy their code via Amp are now unable to do so (since 9/15/2020).

**Workaround**
Adding aws-exports.js to git works to unblock online deployment, but does not work in multi-environment deployment situations, since that file should be different for every env.

**Comment by mauerbac** [comment]
oof, sorry to see this @Trevor-mc2 . This is not a good experience. Ive flagged this to the team and we are working on a fix.

**Comment by swaminator** [comment]
Apologies @Trevor-mc2 . We fixed the tutorial here: https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/module-three/. Search for 'Set up CI/CD of the frontend and backend`.

**Comment by tobiasriemenschneider** [comment]
> Apologies @Trevor-mc2 . We fixed the tutorial here: https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/module-three/. Search for 'Set up CI/CD of the frontend and backend`.

Would be great to have this included in languages !== english, too.
<img width="1911" alt="Modul_3__Erstellung_einer_React-Anwendung_auf_AWS_und_Module_Three_-_Build_a_React_Application_on_AWS" src="https://user-images.githubusercontent.com/3159548/94451452-b3f44700-01ae-11eb-853e-e3c778399b40.png">

**Comment by tobiasriemenschneider** [comment]
> Apologies @Trevor-mc2 . We fixed the tutorial here: https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/module-three/. Search for 'Set up CI/CD of the frontend and backend`.

Would be great to include that for languages !== english, too.
