### ISSUE TITLE
[Documentation] Clarify connection between amplify api and AppSync

### ISSUE THREAD

**Issue by cortex** [aws-amplify/docs#2442]
When I got started using Amplify, I didn't understand that amplify api was actually setting up an AppSync API, and the directives were creating VTL templates that I could read up more on in the AppSync documentation. 

I suggest documenting this more prominently in the overview: https://docs.amplify.aws/cli/graphql-transformer/overview This would have both helped me understand what code is actually being generated, and how I could exend and modify it as needed. I also suggest linking to the VTL documentation for advanced users. I understand this shouldn't be the default way, but knowing what is going on is very helpful when working with this.

**Comment by mauerbac** [comment]
thanks for calling this out @cortex. Let me sync to the team on this.

**Comment by Straubulous** [comment]
The docs describe this now. closing.
https://docs.amplify.aws/cli/graphql/overview/
https://docs.amplify.aws/cli/graphql/custom-business-logic/#vtl-resolver
