### ISSUE TITLE
[Feedback] amplify add api behavior differs from tutorial.

### ISSUE THREAD

**Issue by LeoSalemann** [aws-amplify/docs#2444]
**Page**: [`/start/getting-started/data-model/q/integration/react-native`](https://docs.amplify.aws/start/getting-started/data-model/q/integration/react-native)

**Feedback**:

When following instructions to _Create a GraphQL API and database_ amplify prompts me to choose a schema template, while the tutorial talks about guided schema
<img width="722" alt="amplify-rn-pic02" src="https://user-images.githubusercontent.com/6365898/94097428-57261480-fddb-11ea-82a9-06b207914383.png">
 creation.

**Comment by mauerbac** [comment]
thanks @LeoSalemann. I see the docs are outdated here. Marking as a CLI bug. Thank you
