### ISSUE TITLE
[Feedback]Amplify push behavior differs from tutorial.

### ISSUE THREAD

**Issue by LeoSalemann** [aws-amplify/docs#2445]
**Page**: [`/start/getting-started/setup/q/integration/android`](https://docs.amplify.aws/start/getting-started/setup/q/integration/android)

**Feedback**:

_amplify push_ prompts for _Enter the file name pattern of graphql queries, mutations, and subscriptions_, Tutorial does not mention this. 

PS - I was following the React Native tutorial; not sure why the page says android.

**Comment by mauerbac** [comment]
Thanks again.

**Comment by josefaidt** [comment]
Closing issue as steps for `amplify push` are no longer included in this tutorial page, nor for React Native.
