### ISSUE TITLE
[Feedback]Java/Coretto needed for amplify mock api

### ISSUE THREAD

**Issue by LeoSalemann** [aws-amplify/docs#2446]
**Page**: [`/start/getting-started/setup/q/integration/android`](https://docs.amplify.aws/start/getting-started/setup/q/integration/android)

**Feedback**:

_amplify mock api_ call from **(Optional) Test your API** returns a Java not found error; Java not listed among pre requisites in **Getting Started**

<img width="557" alt="amplify-rn-pic04" src="https://user-images.githubusercontent.com/6365898/94099322-90f91a00-fddf-11ea-919d-5c5ad74620ae.png">

**Comment by jpignata** [comment]
@LeoSalemann Thanks! Were you able to get it working after installing Java?

**Comment by LeoSalemann** [comment]
I was! I'm trying the react version of the tutorial now, and I see the little note to add java before running amplify mock api!
