### ISSUE TITLE
[Feedback] UserSub poorly named and not explained with first mention

### ISSUE THREAD

**Issue by jorisw** [aws-amplify/docs#2448]
**Page**: [`/lib/auth/emailpassword/q/platform/js`](https://docs.amplify.aws/lib/auth/emailpassword/q/platform/js#setup-totp)

**Feedback**:

As a first time reader of the docs, I'm somewhat distracted by the poor choice of naming of the `UserSub`. I have no idea what 'Sub' means in this context, and I needed to Google "Cognito UserSub" to find out. Clicking the `ISignUpResult` or `CognitoUser` link takes me to code on GitHub where `UserSub` is part of a type, but it's not explained in there either. If it was named better, it would have been self-explanatory. How is it not, for example, an ID, and therefore named `GloballyUniqueUserID` or `gUUID` or something?

I understand this naming is fixed now that it exists, but I would suggest to explain what it is the first time it appears in an example.

**Comment by mauerbac** [comment]
Got it. Will update these details on our docs https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_SignUp.html

**Comment by evcodes** [comment]
Hey @jorisw, 

Thank you for bringing this. You are 100% correct, just wrote a quick PR to fix this.

Thanks again for using Amplify to build your apps!
