### ISSUE TITLE
[Feedback] AUTH?

### ISSUE THREAD

**Issue by mconnor** [aws-amplify/docs#2450]
**Page**: [`/start/q/integration/next`](https://docs.amplify.aws/start/q/integration/next)

**Feedback**:

Following this tutorial. Not seeing where Auth is set up.

I'm only getting:
| Category | Resource name | Operation | Provider plugin   |
| -------- | ------------- | --------- | ----------------- |
| Api      | nextamplified | Update    | awscloudformation |

**Comment by ericclemmons** [comment]
Auth is configured as part of `amplify add api`:
> https://docs.amplify.aws/start/getting-started/data-model/q/integration/next#create-a-graphql-api-and-database

Did you choose "Yes" for "Configure additional auth types?"?
