### ISSUE TITLE
Angular 6+ Support Is this a Permanent Workaround?

### ISSUE THREAD

**Issue by ByEqualation** [aws-amplify/docs#2463]
**Page**: [`/start/q/integration/angular`](https://docs.amplify.aws/start/q/integration/angular)

**Feedback**:

Under "Angular 6+ Support"  Could you please advise or confirm if this is a permanent feature of using Angular?  
If you could possibly indicated that Someone will revisit when/if this is no longer required that would be great.

Steve

**Comment by mauerbac** [comment]
hey @sammartinez or @gsans , can you help here?

**Comment by gsans** [comment]
This is still required.
