### ISSUE TITLE
Investigate browser extensions issues

### ISSUE THREAD

**Issue by tanzorly** [aws-amplify/docs#2468]
**Page**: [`https://docs.amplify.aws/lib/analytics/autotrack/q/platform/android`](https://docs.amplify.aws/lib/analytics/autotrack/q/platform/android)

**Feedback**:

**Comment by mauerbac** [comment]
Hello @alok-tanzorly - which page is broken?

**Comment by alok-tanzorly** [comment]
https://docs.amplify.aws/lib/analytics/autotrack/q/platform/android - this shows 404.

**Comment by mauerbac** [comment]
Can you try in incognito mode? it works for me. Some browser extensions have been known to cause problems. What browser and OS are you using ?

**Comment by alok-tanzorly** [comment]
It works in incognito. 

I think some extensions might be causing the problem. The browser is Google Chrome Version 85.0.4183.121 (Official Build) (64-bit) and OS is Windows 10 Version 10.0.19041 Build 19041.  "HTTPS Everywhere" or "UBlock Origin" might be the cause of the issue.

**Comment by mauerbac** [comment]
thanks @alok-tanzorly , ill leave this open for us to review
