### ISSUE TITLE
[Feedback][Docs] React Getting Started > "Next Steps" is Empty

### ISSUE THREAD

**Issue by renrut** [aws-amplify/docs#2472]
**Page**: [`/nextsteps/q/integration/react`](https://docs.amplify.aws/start/getting-started/nextsteps/q/integration/react)

**Feedback**:

The page says 
```
🎉 Congratulations! Your app is built, with a realtime backend.

What next? Here are some things to add to your app:
```

But is missing any next steps.

**Comment by mauerbac** [comment]
oof , thanks for flagging this @renrut . that is not good. Will work on a fix

**Comment by mauerbac** [comment]
Fixed
