### ISSUE TITLE
RFC: Increase visibility of Discord Community  

### ISSUE THREAD

**Issue by mauerbac** [aws-amplify/docs#2475]
Looking for ideas on how to grow the Discord community

**Comment by hellosagar** [comment]
@mauerbac  should we change the color of "discord open chat " to some active color like this

![image](https://user-images.githubusercontent.com/50016799/94722990-b654cd80-0375-11eb-971d-1abfe8b8e1af.png)

**Comment by mauerbac** [comment]
![Screen Shot 2020-10-01 at 3 05 10 PM](https://user-images.githubusercontent.com/1507886/94981937-76702080-0504-11eb-8cbb-02ff589dfb57.png)
How about left hand side too?

**Comment by sammartinez** [comment]
cc @renebrandel to get some weigh in on this.

**Comment by renebrandel** [comment]
I like the left hand side model but we should make it even more prominent though.

**Comment by mauerbac** [comment]
Okay, cool! Going to assign @tjleing. I can mock a design

**Comment by mauerbac** [comment]
Spoke to @harrysolovay --

- Clean up of the current button 
- Try left side align (desktop)
- When expanded on mobile, add a button

**Comment by harrysolovay** [comment]
None of these quite feel right. I think Matt's mock from 17 days ago is the right call: moving the discord link into the menu, beneath the edit and feedback buttons. Will try that one out as well & follow up tomorrow.

<img width="720" alt="Screen Shot 2020-10-19 at 4 55 39 PM" src="https://user-images.githubusercontent.com/4893548/96524060-14b1f500-122c-11eb-8c72-4d7058467b44.png">
<img width="720" alt="Screen Shot 2020-10-19 at 4 55 48 PM" src="https://user-images.githubusercontent.com/4893548/96524064-167bb880-122c-11eb-8d09-49172d1caf34.png">
<img width="1440" alt="Screen Shot 2020-10-19 at 4 56 03 PM" src="https://user-images.githubusercontent.com/4893548/96524065-17ace580-122c-11eb-8fe8-8f4b5214baf5.png">

**Comment by mauerbac** [comment]
Added
