### ISSUE TITLE
Amplify upload works, download reports Access Denied

### ISSUE THREAD

**Issue by trpster** [aws-amplify/docs#2493]
**Page**: [`/lib/debugging/dev-menu/q/platform/android`](https://docs.amplify.aws/lib/debugging/dev-menu/q/platform/android)

**Feedback**:

I've followed the Android tutorial exactly, multiple times, through the upload example which seems to work perfectly: the bucket shows the uploaded data, the logcat shows:
```console
I/MyAmplifyApp: Successfully uploaded: ExampleKey
```

When I attach the download code below the upload code, I get:
```console
E/MyAmplifyApp: Download Failure
```
followed by multiple lines saying "Access Denied."

How can access be allowed for the upload, but not for the download?

I've tried all manner of permissions, even including turning ON every category of Public permission, but consistently get Access Denied for the download code.

Here is the code:
```kotlin
private fun uploadFile() {
    val exampleFile = File(applicationContext.filesDir, "ExampleKey")

    exampleFile.writeText("Yet another sample file")

    Amplify.Storage.uploadFile(
        "ExampleKey",
        exampleFile,
        { result -> Log.i("MyAmplifyApp", "Successfully uploaded: " + result.getKey()) },
        { error -> Log.e("MyAmplifyApp", "Upload failed", error) }
    )
    Amplify.Storage.downloadFile(
        "ExampleKey",
        File("${applicationContext.filesDir.toString()}/download.txt"),
        { result -> Log.i("MyAmplifyApp", "Successfully downloaded: ${result.getFile().name}") },
        { error -> Log.e("MyAmplifyApp", "Download Failure", error) }
    )
}
```
I've tried creating different IAMs and different apps, but every attempt results in the same result: download failure due to Access Denied.  Give me a clue... what's happening?

**Comment by raphkim** [comment]
Hi @trpster,

I was able to successfully download the file when I followed the tutorial. However, I _was_ able to reproduce the error you are receiving with a small modification in the steps. Is it possible that during the CLI setup stage, you did not specify READ access to guest and/or auth users? The prompt should look like this:

![Screen Shot 2020-10-06 at 11 06 38 AM](https://user-images.githubusercontent.com/52714340/95242482-160f0680-07c4-11eb-9ad4-607bbf084dc6.png)

I can see how this step can be confusing because the selections look like radio buttons. The tutorial requires you to toggle _ALL_ three options to enable both uploading and downloading files.

Please let me know if this intuition was incorrect.

**Comment by trpster** [comment]
Wow, you guessed it; I thought the selection choices were radio buttons.  How do I re-run the "amplify add storage" to change the settings?  When I tried I got the message "Amazon S3 storage was already added to your project."  Do I need to create another app so I can add the correct settings, or is there an amplify command like "amplify modify project" or something similar.  Or maybe go to the app section of the console and delete the app?  
     Anyway, thanks for figuring out what I was doing wrong; I felt like I was close.
              Tom

**Comment by raphkim** [comment]
Glad I could help! You can re-configure existing resources with `amplify update <category>`.

If you ever need to remove a resource, it will be `amplify remove <category>`.

**Comment by trpster** [comment]
Hold on; I can't get the updated configuration to push, says bucket already exists even after deleting, pushing, and adding.  Maybe this app has had too many things wrong with it,  The amplifyconfiguration.json file for example still refers to the bucket from the previous attempts.  I'll create yet another new app and see if I can get it to work.  I'm pretty sure you're right about my initial failed attempts, but recovering wasn't as simple as "amplify update storage" "push" or "amplify remove storage" "amplify push" "amplify add storage" "amplify push."
BTW, where does the numeric come from that gets attached to the bucket name?

OK, the new app, hereafter known as "MyFifthAttempt" does indeed work.
    Thanks for your help!
           Tom
