### ISSUE TITLE
[Feedback]FEEDBACK_TITLE_HERE

### ISSUE THREAD

**Issue by eric-gardyn** [aws-amplify/docs#2494]
**Page**: [`/start/q/integration/react-native`](https://docs.amplify.aws/start/q/integration/react-native)

**Feedback**:
Adding an API (GraphqL) as per tutorial at https://docs.amplify.aws/start/getting-started/data-model/q/integration/react-native
leads to error: An error occurred during the push operation: EROFS: read-only file system, mkdir '/graphql'

**Comment by amhinson** [comment]
Are you still experiencing this issue?
