### ISSUE TITLE
React Native Tutorial Feedback

### ISSUE THREAD

**Issue by Kamran21** [aws-amplify/docs#2495]
**Page**: [`/start/q/integration/react-native`](https://docs.amplify.aws/start/q/integration/react-native)

**Feedback**:

I liked the tutorials but I think two things are missing:
1. More details about the different options available for the questions presented in the CLI and with a short explanation about each
2. I couldn't find any examples on how to combine AWS Amplify CI/CD with a React Native App's built with Expo.

(I am not an experienced React Native developer, And found it hard to get stated with building CI/CD For React Native apps With AWS Amplify. It will be nice to have some CI/CD capabilities like Microsoft App Center built to AWS Amplify or Integrated with it. )

I think by adding this information it will make it easier to get started building React Native apps with AWS Amplify which seems to be a great tool for rapid development, And in general I hope more content will be added to the docs.

**Comment by Straubulous** [comment]
@josefaidt  to confirm if still an issue with current tutorial and CLI

**Comment by josefaidt** [comment]
Hey @Kamran21 :wave: apologies for the delay here! This guide has evolved over the past year and a half and I wanted to follow-up to see if you have specific concerns around the guide's content and to clarify this note from your original post:

> It will be nice to have some CI/CD capabilities like Microsoft App Center built to AWS Amplify or Integrated with it

Are you looking for general documentation around deploying your app to Microsoft App Center from the Amplify Hosting CI/CD pipelien?

**Comment by rachelnabors** [comment]
@Kamran21 We recently updated the Getting Started docs for React Native. Does this help? https://docs.amplify.aws/start/getting-started/installation/q/integration/react-native/
