### ISSUE TITLE
[Feedback]FEEDBACK_TITLE_HERE

### ISSUE THREAD

**Issue by vickey58** [aws-amplify/docs#2498]
**Page**: [`/guides/api-graphql/subscriptions-by-id/q/platform/android`](https://docs.amplify.aws/guides/api-graphql/subscriptions-by-id/q/platform/android)

**Feedback**:

 This page gives the android example for subscription for a perticular id , but at the end of the page contains the Nodejs code, it should be a java code. and please let me knw wher i can get the java code for the same?

**Comment by jpignata** [comment]
Thanks, @vickey58! We're updating these pages with the appropriate iOS and Android snippets. Follow https://github.com/aws-amplify/docs/issues/2323 for updates. cc: @Kilo-Loco @dabit3
