### ISSUE TITLE
[Feedback]expo init wants a project type.

### ISSUE THREAD

**Issue by LeoSalemann** [aws-amplify/docs#2502]
**Page**: [`/start/q/integration/react`](https://docs.amplify.aws/start/q/integration/react)

**Feedback**:

Typing _expo init_ prompts for multiple project types.
`? Choose a template: (Use arrow keys)`
`  ----- Managed workflow -----`
`❯ blank                 a minimal app as clean as an empty canvas `
`  blank (TypeScript)    same as blank but with TypeScript configuration` 
` tabs (TypeScript)     several example screens and tabs using react-navigation and TypeScript `
`  ----- Bare workflow -----`
`  minimal               bare and minimal, just the essentials to get you started`
`  minimal (TypeScript)  same as minimal but with TypeScript configuration `

I'm assuming I should choose the default, blank.

**Comment by dabit3** [comment]
Thanks for the issue @LeoSalemann , I've updated the guide in [this pr](https://github.com/dabit3/docs/commit/ba45db116472c089de360b6c8a27dfee68381d48) fo address this.
