### ISSUE TITLE
Documentation for scanncount

### ISSUE THREAD

**Issue by supercodes1223** [aws-amplify/docs#2504]
[HowtocountthenumberofresultswithAWSAmplifyDynamoDBandGraphQL.pdf](https://github.com/aws-amplify/docs/files/5337114/HowtocountthenumberofresultswithAWSAmplifyDynamoDBandGraphQL.pdf)

**Comment by jpignata** [comment]
Heya @supercodes1223! I'm pretty confused by this issue given there's no context provided. Please let us know what it is you'd like to see -- please use one of the provided templates on the repo to help us capture the information we need. Thank you!
