### ISSUE TITLE
Cannot find file './aws-exports' in './src'

### ISSUE THREAD

**Issue by duncangroenewald** [aws-amplify/docs#2505]
**Describe the bug**
When building Frontend with AWS CI/CD we are now getting this error.

**To Reproduce**
Any time we commit code the CodeCommit and the front-end application is deployed we get this error during the build process

**Expected behaviour**
The build process should automatically create the aws-exports.js file relevant for the environment being deployed to. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
It's not clear what other information is required.  As we understand it the aws-exports.js file should be created automatically by AWS Amplify when the Frontend is built.  It's unclear where there is anything we need to do to or might have don't to affect creation of the aws-exports.js file.

I have eventually managed to work around the problem by building a whole new environment.  It seems that because we have two different branched connected to the same back-end something gets confused because the two branches may end up with different backend configurations.

Does there need to be some documentation about how to handle the situation where the repo has different branches and the back-end code may become out of sync on one branch if that branch is only being used for testing new front end features - for example.

**Comment by mauerbac** [comment]
@swaminator , can you help out here ?

**Comment by swaminator** [comment]
@duncangroenewald can you do the following:
1. https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#frontend-with-backend: Update your build settings to add the backend phase in your build pipeline (Under App settings > Build settings)
2. Go to App settings > General, and choose Edit. Create a service role for the console to automatically update the backend as well.
