### ISSUE TITLE
[Feedback] using `amplify init` in a shared environment

### ISSUE THREAD

**Issue by duncangroenewald** [aws-amplify/docs#2507]
**Page**: [`/cli/teams/shared`](https://docs.amplify.aws/cli/teams/shared)

**Feedback**:

When I run Amplify init I never get prompted to use an existing environment - what is with that?  

Instead it goes off and creates a whole new app with the exact same name as the one that already exists.

Am I misunderstanding something about these instructions?  

<img width="785" alt="image" src="https://user-images.githubusercontent.com/13807324/95322997-279dfe80-08e9-11eb-917f-2a145e3cb9f0.png">

**Comment by ammarkarachi** [comment]
@duncangroenewald are you running `amplify init` in a project folder?

**Comment by swaminator** [comment]
@duncangroenewald that's because you probably do not have the amplify prjoect folder set up. You need to have the `amplify` folder in order to re-use existing envs. We added a callout in the docs.
