### ISSUE TITLE
[Feedback] Incorrect documentation. Storage.get does not directly return a Blob. 

### ISSUE THREAD

**Issue by ferdingler** [aws-amplify/docs#2512]
**Page**: [`/lib/storage/download/q/platform/js`](https://docs.amplify.aws/lib/storage/download/q/platform/js)

**Feedback**:

Documentation states that `Storage.get` returns a `Blob` of object data if download is true, which is incorrect. `Storage.get` returns an **object that contains a property `Body`** which is a `Blob`. That is different than saying that that the response of Storage.get is a Blob. 

Spent a few minutes debugging an issue because of this slight confusion.

**Comment by sw-yx** [comment]
aye. that was my fault, I'm sorry about that. i currently have a PR pending review with a fix and even more info. https://github.com/aws-amplify/docs/pull/2521/files

**Comment by sw-yx** [comment]
welp, that was fast, i think we fixed it

**Comment by ferdingler** [comment]
Thanks for the quick fix!
