### ISSUE TITLE
[Feedback]How to implement handleAuthStateChange should be documented

### ISSUE THREAD

**Issue by kjetilge** [aws-amplify/docs#2513]
**Page**: [`/lib/utilities/hub/q/platform/js`](https://docs.amplify.aws/lib/utilities/hub/q/platform/js#state-management)

**Feedback**:

There is a nice explanation [here:](https://github.com/aws-amplify/amplify-js/issues/6113)

At the very least include the following with a little explanation :

```
    handleAuthStateChange (nextAuthState, authData) {
      console.log('Next state: ', nextAuthState, 'auth data: ', authData)
      Hub.dispatch('UI Auth', {
        event: 'AuthStateChange',
        message: nextAuthState,
        data: authData ? authData.user : null,
      });
    }
```
And usage:
```
this.handleAuthStateChange(AuthState.ConfirmSignUp, { user: { username: user.username } })
```

**Comment by mauerbac** [comment]
Thanks for calling this out. I moved the issue you [tagged](https://github.com/aws-amplify/docs/issues/2549) over and will work to update the documentation. Will close this one.
