### ISSUE TITLE
[Feedback] Flutter tutorial - amplify init feedback

### ISSUE THREAD

**Issue by Sean-Sekora** [aws-amplify/docs#2515]
**Page**: [`/start/q/integration/flutter`](https://docs.amplify.aws/start/q/integration/flutter)

**Feedback**:

after the `amplify configure` step I received the following error when running `amplify add analytics`
```
You are not working inside a valid Amplify project.
Use 'amplify init' in the root of your app directory to initialize your project, or 'amplify pull' to pull down an existing project.
```
To resolve this I ran `amplify init` again and then `amplify add analytics` completed successfully

**Comment by mauerbac** [comment]
can you provide a bit more info so we can reproduce this? Did you follow the steps in the end?

**Comment by sw-yx** [comment]
@Sean-Sekora we do instruct people to init before running add analytics https://docs.amplify.aws/start/getting-started/add-api/q/integration/flutter#setup-aws-cloud-resources-with-amplify-cli
