### ISSUE TITLE
Incorrect geo-location instructions

### ISSUE THREAD

**Issue by akilisosa** [aws-amplify/docs#2517]
**Describe the bug**

**To Reproduce**
1. Go to 'https://docs.amplify.aws/cli/graphql-transformer/resolvers#add-a-custom-geolocation-search-resolver-that-targets-an-elasticsearch-domain-created-by-searchable'
2. Click on 'Add a custom geolocation search resolver that targets an Elasticsearch domain created by @searchable'
3. Scroll down to 'Add a custom geolocation search resolver that targets an Elasticsearch domain created by @searchable'
4. See error - Todo model, referencing itself

```
type Todo @model @searchable {
  id: ID!
  name: String!
  description: String
  comments: [Todo] @connection(name: "TodoComments")  <-- right here
}

```

**Expected behavior**

the walkthrough to work and be error free. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

as i continued down i also realized that the put, and insert instructions also needed a delete step. 

this is the schema i used :
```
type Comment  @model {
  id: ID!
  content: String
  todoID: ID!
}

type TodoConnection {
  items: [Todo]
  nextToken: String
}


type Todo @model @searchable {
  id: ID!
  name: String!
  description: String
  #comments: [Comment] @connection(name: "TodoComments")
  location: Location
}

type Location {
  lat: Float
  lon: Float
}
input LocationInput {
  lat: Float
  lon: Float
}

type Query {
  nearbyTodos(location: LocationInput!, km: Int): TodoConnection
}

```

That with the delete button allow you to complete the little tutorial you guys have

**Comment by dabit3** [comment]
Thanks @akilisosa for the issue. Do you mind taking a look at [this](https://github.com/dabit3/docs/commit/1f92ee7cc89c08601f878871ef4563681be48849) update to see if it helps address the issue? Thanks
