### ISSUE TITLE
[Feedback]Change file permissions 

### ISSUE THREAD

**Issue by VG2000** [aws-amplify/docs#2527]
**Page**: [`/start/getting-started/generate-model/q/integration/ios`](https://docs.amplify.aws/start/getting-started/generate-model/q/integration/ios)

**Feedback**:

You need to highlight the fact that you have to change file permissions in order to edit the schema.graphsql. the file permissions don't necessarily default to the logged in user even if they have administrative permissions.

**Comment by dabit3** [comment]
Hi @VG2000, when you mention permissions are you referring to file permissions on you local machine?
