### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by VG2000** [aws-amplify/docs#2528]
**Describe the bug**
I am trying to follow the tutorial at https://docs.amplify.aws/start/getting-started/setup/q/integration/ios and I follow the tutorial to the letter but keep getting a "Command PhaseScriptExecution failed with a nonzero exit code" error when I attempt a build. 

**To Reproduce**
Follow steps 1- 6 on the getting started page and after step 6 (open Todo workspace) the workspace will attempt to build and fail with the error below:

**Screenshots**
![Screenshot 2020-10-10 at 08 11 13](https://user-images.githubusercontent.com/47152273/95648568-31358b00-0ad0-11eb-97ed-b3bf5c3b846a.png)

**Desktop (please complete the following information):**
 -iOS: 10.15.7
-Xcode 12.0.1
-Amplify 1.3.1
-Amplify CLI version 4.29.6
Installing AWSAuthCore (2.17.0)
Installing AWSCognitoIdentityProvider (2.17.0)
Installing AWSCognitoIdentityProviderASF (2.17.0)
Installing AWSCore (2.17.0)
Installing AWSMobileClient (2.17.0)
Installing AWSPluginsCore (1.3.1)
Installing Amplify (1.3.1)
Installing AmplifyPlugins (1.3.1)
Installing AppSyncRealTimeClient (1.4.1)
Installing ReachabilitySwift (5.0.0)
Installing SQLite.swift (0.12.2)
Installing Starscream (3.1.1)

**Additional context**

**Comment by lawmicha** [comment]
Hi @VG2000, are you still seeing this issue?

**Comment by VG2000** [comment]
I never did get it resolved. We decided to change tack to workaround this...

**Comment by lawmicha** [comment]
I recall that error usually occured when using AmplifyTools. the latest docs no longer use that, closing the issue now. Feel free to open another if you are seeing isses following the guide
