### ISSUE TITLE
I recommend adding a specific reference to "ng serve" at end of this page.  It would have spared me some frustration.

### ISSUE THREAD

**Issue by ByEqualation** [aws-amplify/docs#2529]
**Page**: [`/start/q/integration/angular`](https://docs.amplify.aws/start/q/integration/angular)

**Feedback**:
I get to this point...  BUT what does it mean to "Open the app in another browser window when I don't have it open in a single browser and I don't know how to do that.  At what step exactly should I have seen a browser???  

Now, open the app in another browser window so that you have two side by side. When creating a new item in one window, you should see it come through in the other window in real-time.

🙌 Great job! You have successfully deployed your API and connected it with your app!
} 

I ran "ng serve" at end of this page, is that what what I am supposed to do?  It is not totally obvious to me that this is going to call AWS for anything,  I can see that the data is passed across the two browsers as described but explicitly saying "ng serve" to restart your server it is not running',  Would have saved some anguish.

Then control click on  http://localhost:4200/ TWICE to have two browsers open and this is working???  It does what  is described.  I think this should be added to the instructions.  

Many thanks for all you do for the community,
Steve

**Comment by sw-yx** [comment]
@gsans any thoughts?

**Comment by gsans** [comment]
Steve it seems to me you are following some other instructions. There's no real-time in the getting started for Angular.

**Comment by gsans** [comment]
Sorry about the confusion. Let me know if you need any more help

**Comment by ByEqualation** [comment]
I am not making any deep observations,  I am only sharing that 

In the tutorial, BOTTOM of Page "Connect API and database to the app"

IF the the student working through the tutorial has inadvertantly killed the running server (which of course I did) i.e. closes her terminal then...  The instruction to...

_Then control click on http://localhost:4200/ TWICE to have two browsers open and this is working??? It does what is described. I think this should be added to the instructions._

is unsatisfying because FIRST the student needs to open their terminal (if no terminal is open) AND run "ng serve".

This is all that I had to do, but for about 10 minutes I thought I was going to have to start from scratch.

Many thanks.

**Comment by gsans** [comment]
I understand. Thanks for the extra details. The team will review in the next iteration and make the changes if deemed necessary.

**Comment by dabit3** [comment]
Thanks for the issue @ByEqualation, have a look at [this](https://github.com/aws-amplify/docs/pull/2563/files#diff-232441956ece11f0daa926959b898d849622605899f392e19b27f6dd5ee66e1d) update and let me know if it is what you had in mind.

**Comment by ByEqualation** [comment]
All,  Many thanks for the action.  Apologies for the confusion, it must be a real challenge to support multiple frameworks.  My hat is off to the team.   I can clearly see how the below is more general to all the frameworks and gets the task completed.  This is truly encouraging to me to continue providing feedback.  I will make every effort to avoid framework specific bias in my feedback to avoid confusion. 

Best regards,
Steve
//  Next, run the app:
npm start // :)
