### ISSUE TITLE
Generic Card

### ISSUE THREAD

**Issue by mehrab-haque** [aws-amplify/docs#2531]
**Page**: [`/ui/interactions/chatbot/q/framework/react`](https://docs.amplify.aws/ui/interactions/chatbot/q/framework/react)

**Feedback**:

Not getting generic card having images and buttons, just the text is being loaded.

**Comment by mauerbac** [comment]
What code are using ? What are seeing? Can you provide more info?

**Comment by mehrab-haque** [comment]
In my ReactJs app, I used both <ChatBot/> and <AmplifyChatbot/> components as shown in the doc ( https://docs.amplify.aws/ui/interactions/chatbot/q/framework/react ) , everything is working fine, but when generic response cards having images and buttons are being sent from chatbot, it is not being rendered in the frontend, just the text is being shown.
Here is the code snippet =>
![image](https://user-images.githubusercontent.com/59254540/95806793-59b8c180-0d2a-11eb-8886-44ab296f5efe.png)
Here is the web app, there were response cards with "Which food do you want to haveeee ?" message =>
![image](https://user-images.githubusercontent.com/59254540/95806854-8c62ba00-0d2a-11eb-80e9-7e02d4c731a2.png)
Now how would I solve this in ReactJs ?

**Comment by mauerbac** [comment]
@mehrab-haque - ah, I see. We currently don't support this behavior. This is a FR in our JS repo: https://github.com/aws-amplify/amplify-js/issues/3404. Please give it an upvote.
