### ISSUE TITLE
GraphQL @Auth directive

### ISSUE THREAD

**Issue by hutch120** [aws-amplify/docs#2535]
Hi All!

Details below, but basically, I'm having trouble figuring out how how to manage mutation access to a connected table via the @auth directive where the parent table has a list of cognito `editors`? Seems like a fairly common use case. Any tips would be most appreciated. I've gone over the [documentation](https://docs.amplify.aws/cli/graphql-transformer/directives) again and again, but it is not clear how to proceed.

So, here are the details of my implementation.

I have `type Team` and `type Contact`. A `Contact` can belong to one `Team` and has an @connection directive (see schema below). I am able to add `editors` (cognito usernames) to `type Team` and those users then have access to listTeams, getTeam, updateTeam, etc. Great so far!

So, then I wanted to manage access to `type Contact`, same as `type Team` but it doesn't work. Mutations such as `updateContact` seem to need have their own @auth directives separate from queries.

I added `{ allow: private, operations: [update] }` to `type Contact` to allow anyone to update, but this is not great, I only want `editors` defined in `type Team` to access the mutations for `type Contacts`.

I feel like I'm missing something obvious here... I thought maybe I need to copy the `type Team editors` to `type Contact` but this becomes a data management nightmare, and has other side effects such introducing race conditions.

```gql
type Team
  @model
  @auth(
    rules: [
      { allow: owner }
      { allow: owner, ownerField: "editors", operations: [update, read] }
    ]
  ) {
  id: ID! # Auto generated ID
  title: String! # Name of the team
  editors: [String] # List of Cognito UserIDs
  contacts: [Contact] @connection(name: "TeamContacts")
}

type Contact
  @model(queries: null)
  @auth(
    rules: [{ allow: private, operations: [update] }]
  ) {
  id: ID! # Auto generated ID
  name: String # Name of the contact (Full name: Joe Smith)
  team: Team! @connection(name: "TeamContacts") # Team ID that this contact belongs to.
}
```

Thanks in advance.

**Comment by SwaySway** [comment]
Hello @hutch120 

`@auth` provides authorization on the type and it's fields. It does not apply auth on the connected type rather it applies auth on the field resolver for `contacts`. This allows you to define additional auth rules on Contact since the same auth rules on `Team` may not always apply to Contact.

The dynamic rule you applied is limited to the type. An alternative here would maybe be a static group where members are assigned to be editors? you could also apply a dynamic group rule where you can dynamically change access on what groups have access to certain types. 

Docs: 
- [Static Groups](https://docs.amplify.aws/cli/graphql-transformer/auth#static-group-authorization)
- [Dynamic Groups](https://docs.amplify.aws/cli/graphql-transformer/auth#dynamic-group-authorization)

**Comment by hutch120** [comment]
@SwaySway Wow, thanks for the reply.... got to be honest, 4 months later, I've moved on from that project. I did end up building and deploying a client facing system based on this library that worked with some application level hacks, but here is a bit of feedback/reflection. 

Firstly, don't get me wrong, GraphQL is an amazing bit of tech, but...

For anyone reading this.... my advice, take the [blue pill](https://en.wikipedia.org/wiki/Red_pill_and_blue_pill) and go back to your favourite database / REST API. 

Anyone who thinks GraphQL is a silver bullet to building a database/API, it is not... be prepared for a very deep rabbit hole.

I think there should be warnings on these types of OS projects that indicate how much of a learning curve, maybe some upfront info on how much support to expect and what projects should be attempted with this tech.

In hindsight I now believe that I should have simply build an SQL schema in MySQL/PostGre or whatever, and saved myself a few weeks of frustration.

Anyway, thanks again.. please feel free to close this issue report.

**Comment by SwaySway** [comment]
Transferring this issue into the CLI repo, for better tracking.
Should you have further questions on the transformer we have our discord server here: https://discord.gg/jWVbPfC
If you run into any issues with this please comment below.
