### ISSUE TITLE
Missing documentation for Amplify.Hub on iOS

### ISSUE THREAD

**Issue by drochetti** [aws-amplify/docs#2539]
**Describe the bug**
The `Amplify.Hub` category in the native implementations is not documented.

**Expected behavior**
The category should be properly documented.

**Comment by div5yesh** [comment]
Hub is documented within each category separately. 
Auth: https://docs.amplify.aws/lib/auth/auth-events/q/platform/android/
Datastore: https://docs.amplify.aws/lib/datastore/datastore-events/q/platform/android/

We can improve the experience even further if we create a Hub category similar to JS docs https://docs.amplify.aws/lib/utilities/hub/q/platform/js/ and also document public APIs for Hub.

**Comment by tylerjroach** [comment]
Removing Android tag, as Android documentation has been added.

**Comment by ameter** [comment]
Added for iOS in [this PR](https://github.com/aws-amplify/docs/pull/4453).
