### ISSUE TITLE
Document AmplifyOperation and cancel() on iOS and Android

### ISSUE THREAD

**Issue by drochetti** [aws-amplify/docs#2540]
**Describe the bug**
The `AmplifyOperation` along with its `cancel` capability (among other things) is not documented.

**Expected behavior**
Document how to use `AmplifyOperation` and in which scenario customers should use it or when it's safe to ignore it.

**Comment by brennanMKE** [comment]
Started a doc to share with PM and docs team to determine where the docs should live.

* [Operations](https://quip-amazon.com/cqWlARS4b6oj/Docs-Operations) (Quip)

**Comment by brennanMKE** [comment]
Attempted to create a Swift Playground in the Xcode workspace but it will not build due to a missing variant which is not being produced by the build. This is meant to create sample code which can be used in the docs and also could be live code which can be referenced in the workspace.

**Comment by lawmicha** [comment]
storage related one https://github.com/aws-amplify/docs/pull/3290
- identify if we should mention `cancel` in other categories

**Comment by brennanMKE** [comment]
PR: https://github.com/aws-amplify/amplify-ios/pull/1281

Merged to main.

**Comment by brennanMKE** [comment]
See: [OPERATIONS.md](https://github.com/aws-amplify/amplify-ios/blob/main/OPERATIONS.md)
