### ISSUE TITLE
[Feedback]Guess access does not work

### ISSUE THREAD

**Issue by dioufb** [aws-amplify/docs#2542]
**Page**: [`/lib/auth/guest_access/q/platform/flutter`](https://docs.amplify.aws/lib/auth/guest_access/q/platform/flutter)

**Feedback**:  This page suggests that you can fetch creds for unauth. It does not work. This is page should be removed for now.

**Comment by mauerbac** [comment]
Thanks @dioufb . Checking with the team

**Comment by sophiagatliff** [comment]
Any update here? This is the same on iOS.
