### ISSUE TITLE
[Feedback] Typo

### ISSUE THREAD

**Issue by sobiyang** [aws-amplify/docs#2543]
**Page**: [`/lib/storage/getting-started/q/platform/js`](https://docs.amplify.aws/lib/storage/getting-started/q/platform/js)

**Feedback**:

In section "Mocking and Local Testing with Amplify CLI" there is a typo, instead of "lock mock server" it should be "local mock server".

**Comment by mauerbac** [comment]
Thanks! You can submit a quick PR, if you'd like :)

**Comment by mauerbac** [comment]
fixed
