### ISSUE TITLE
[Feedback]there's an error on the create GraphL api and database

### ISSUE THREAD

**Issue by andresogando** [aws-amplify/docs#2545]
**Page**: [`/start/getting-started/data-model/q/integration/next`](https://docs.amplify.aws/start/getting-started/data-model/q/integration/next)

**Feedback**:

# No
? Choose a schema template:
# Single object with fields (e.g., “Todo” with ID, name, description) **HERE WE ARE CREATING A TODO APP INSTEAD A BLOG APP! **
? Do you want to edit the schema now? 
# Yes

**Comment by dabit3** [comment]
Thanks @andresogando, please  have a look at #2562 and see if that addresses everything.

**Comment by swaminator** [comment]
Resolved
