### ISSUE TITLE
using @aws-amplify/ui-react how to fully customize the Auth flows documentation needed

### ISSUE THREAD

**Issue by ecomonestop** [aws-amplify/docs#2549]
**Is your feature request related to a problem? Please describe.**
Fully customizing the Auth flows by providing your own "slot"(not using AmplifyUIComponents at all; only using AmplifyAuthenticator and your custom component "slot" that uses Auth API itself ) is not well documented, especially how to handle AuthState changes.  Furthermore, the way I implemneted it seems to be very boilerplate code that I would think AmplifyAuthenticator would handle.  The old Authenticator did handle this boilerplate I believe; not sure why not in the new library. 

**Describe the solution you'd like**
I would like a clear documentation on how to fully customize your AuthFlows using the new library.  I believe there is a big gap when it comes to handling AuthState changes.  Further, maybe some of the boilerplate below can be handled by AmplifyAuthenticator?

**Describe alternatives you've considered**
Currently, I'm doing the following: ("See below code") Notice how I have to handle AuthState changes myself.  Should this be handled by the AmplifyAuthenticator?  As of today, is this best practice?  Finally, Please note that the <Cust.../> components are my own React components that have its own custom UI and calls the Auth API.

```
const AuthLayout = ({ children, initAuthState }) => {
  const [authState, setAuthState] = React.useState(initAuthState)
  const [authData, setAuthData] = React.useState(null)
  const handleAuthStateChange = (nextAuthState, authData) => {
    Hub.dispatch(UI_AUTH_CHANNEL, {
      event: AUTH_STATE_CHANGE_EVENT,
      message: nextAuthState,
      data: authData ? authData.user : null,
    });
  }
  React.useEffect(() => {
    return onAuthUIStateChange((nextAuthState, authData) => {
      setAuthState(nextAuthState)
      setAuthData(authData)
    });
}, []);

  return (
    <AmplifyAuthenticator initialAuthState={initAuthState}  >
      <CustSignUp authState={authState} authData={authData} handleAuthStateChange={handleAuthStateChange} ></CustSignUp>
      <CustConfirmSignUp authState={authState} authData={authData} handleAuthStateChange={handleAuthStateChange} ></CustConfirmSignUp>
      
      {authState === AuthState.SignedIn && authData && children}
    </AmplifyAuthenticator>
  )
}
```

**Comment by dabit3** [comment]
Closing this issue as we've made various improvements to the docs since this issue was raised. If there are still concerns, I'd suggest opening a separate issue outlining what else needs to be documented / clarified.
