### ISSUE TITLE
[Amplify Tutorial] SSR deployment error (Next.js/serverless-component 1.16.0 version)

### ISSUE THREAD

**Issue by komisukee** [aws-amplify/docs#2560]
**Describe the bug**

I tryed to deploy SSR Next.js Application as described in "Deploy and host app" of Amplify Tutorial.
But I received "InvalidArgument" error when I executed "npx serverless" command.

URL:
https://docs.amplify.aws/start/getting-started/hosting/q/integration/next

Error whole:
```
  message: 'The parameter MinTTL is required.',
  code: 'InvalidArgument',
  time: 2020-10-17T04:01:17.106Z,
  requestId: [request id],
  statusCode: 400,
  retryable: false,
  retryDelay: 44.1905403949236
```

As a result of inspection, 
**I succeed deployment by fixing "serverless-component" version `1.16.0` to `1.17.0`.**
```
# serverless.yml
nextamplified:
  component: "@sls-next/serverless-component@1.17.0"
```

**To Reproduce**
I reproduced by setting serverless.yml as follows.
```
# serverless.yml
nextamplified:
  component: "@sls-next/serverless-component@1.16.0"
```

**Expected behavior**
success deployment in cloudfront.

**Screenshots**
![image](https://user-images.githubusercontent.com/32454934/96328569-94e72780-107f-11eb-9682-83c7dac38f3b.png)

Please fix document corresponding part.
Thank you.

**Comment by dabit3** [comment]
Thanks @komisukee, I've submitted an update for this in #2563. Appreciate the issue!
