### ISSUE TITLE
[Feedback]FEEDBACK_TITLE_HERE

### ISSUE THREAD

**Issue by zaheer800** [aws-amplify/docs#2564]
**Page**: [`/start/getting-started/data-model/q/integration/angular`](https://docs.amplify.aws/start/getting-started/data-model/q/integration/angular)

**Feedback**:

src/types/restaurant.ts this file is not available or the instruction to create it is not available

**Comment by dabit3** [comment]
Hi @zaheer800, I believe there are instructions to do this. Do you see this step?
![Screen Shot 2020-10-19 at 10 22 50 AM](https://user-images.githubusercontent.com/1857282/96471588-1dd39f80-11f5-11eb-8f3a-19b27bbede06.png)
