### ISSUE TITLE
[Feedback]FEEDBACK_TITLE_HERE

### ISSUE THREAD

**Issue by yosoi** [aws-amplify/docs#2565]
**Page**: [`/ui/auth/authenticator/q/framework/react`](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react)

**Feedback**:

> signInText
> --
> sign-in-text
> Used for the submit button text in sign up component

This is the description for `submitButtonText`. The description for `signInText` should be used here instead.

**Comment by mauerbac** [comment]
Thanks @yosoi . I'll create a PR for that.

**Comment by mauerbac** [comment]
https://github.com/aws-amplify/amplify-js/pull/7005

**Comment by swaminator** [comment]
Resolved
