### ISSUE TITLE
[Feedback]Error when trying the deploy step

### ISSUE THREAD

**Issue by msglab** [aws-amplify/docs#2571]
![error](https://user-images.githubusercontent.com/72324126/96523018-a3ca0780-1242-11eb-8512-2ab5979d7ccf.png)
**Page**: [`/start/q/integration/next`](https://docs.amplify.aws/start/q/integration/next)

**Feedback**:

<
I get to the last step and when I run npx serverless I get this error:
InvalidArgument: The parameter MinTTL is required.
>

**Comment by dabit3** [comment]
Hi @msglab , check out the most recent updated version [here](https://docs.amplify.aws/start/getting-started/hosting/q/integration/next#option-1-watch-the-video-guide) that now specifies to use version `1.17.0` which should fix the issue that you have.

**Comment by msglab** [comment]
Thank you very much! it worked!
