### ISSUE TITLE
[Feedback] API URL for GraphQL endpoint in Lambda function

### ISSUE THREAD

**Issue by JpOnline** [aws-amplify/docs#2577]
**Page**: [`/guides/functions/graphql-from-lambda/q/platform/ios`](https://docs.amplify.aws/guides/functions/graphql-from-lambda/q/platform/ios#mutation)

**Feedback**:

I needed to replace `process.env.API_URL` to `process.env.API_<MY_API_NAME>_GRAPHQLAPIENDPOINTOUTPUT`

**Comment by mauerbac** [comment]
hey - which line number did you do that on ?

**Comment by JpOnline** [comment]
19 on the mutation example.

**Comment by mauerbac** [comment]
This is updated
