### ISSUE TITLE
[Feedback]Error in sample app

### ISSUE THREAD

**Issue by edwin-github2** [aws-amplify/docs#2580]
**Page**: [`/start/q/integration/ionic`](https://docs.amplify.aws/start/q/integration/ionic)

**Feedback**:

Hi, knowing little about AWS and ionic, I follow the guide on the page.
It says to add the following to `main.ts`:

```javascript
import awsconfig from './aws-exports';
```

But VS Code give me an error:

> Could not find a declaration file for module './aws-exports'.

After googling, I copied the file `aws-exports.js` to `aws-exports.ts`, but then I get message:

> aws-exports.ts is part of the TypeScript compilation but it's unused.

The result of the sample app is message:

> Error: Uncaught (in promise): Error: No credentials

How can I solve this issue?

Thanks in advance,
Edwin

**Comment by mauerbac** [comment]
@edwin-github2 - it looks like your AWS credentials aren't setup correctly. Can you follow the setups about setting up the CLI? https://docs.amplify.aws/start/getting-started/installation/q/integration/react-native.

Let me know if that helps.

**Comment by ChihweiLHBird** [comment]
Maybe this is helpful
https://docs.amplify.aws/lib/auth/start/q/platform/js#re-use-existing-authentication-resource

**Comment by ChihweiLHBird** [comment]
> @edwin-github2 - it looks like your AWS credentials aren't setup correctly. Can you follow the setups about setting up the CLI? https://docs.amplify.aws/start/getting-started/installation/q/integration/react-native.
> 
> Let me know if that helps.

Many people come to the docs with an existing backend (user pool) ready, so it is a good idea that adding a link on the doc that tells them how to add the config manully.

**Comment by edwin-github2** [comment]
Thanks for your comments. AWS takes considerable time to get familiar with and if something fails you're lost. I now have achieved the same with some php scripts.
