### ISSUE TITLE
[Request] RedwoodJS end to end tutorial

### ISSUE THREAD

**Issue by ajcwebdev** [aws-amplify/docs#2583]
**Is your feature request related to a problem? Please describe.**

I love the idea of these end to end tutorials and would like to get as many frameworks involved as possible.

**Describe the solution you'd like**

Redwood is a mono-repo containing two main directories:
* `web` - frontend
* `api` - backend

# Web

The front end is much like other projects in React with an `index.html` containing a `div` for loading the root component, and an `index.js` for that root component.

```html
// web/src/index.html

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" type="image/png" href="/favicon.png" />
    <title><%= htmlWebpackPlugin.options.title %></title>
  </head>
  <body>
    <div id="redwood-app"></div>
  </body>
</html>
```

```javascript
// web/src/index.js

import ReactDOM from 'react-dom'
import { RedwoodProvider, FatalErrorBoundary } from '@redwoodjs/web'
import FatalErrorPage from 'src/pages/FatalErrorPage'
import Routes from 'src/Routes'

ReactDOM.render(
  <FatalErrorBoundary page={FatalErrorPage}>
    <RedwoodProvider>
      <Routes />
    </RedwoodProvider>
  </FatalErrorBoundary>,
  document.getElementById('redwood-app')
)
```

```javascript
// web/src/Routes.js

import { Router, Route } from '@redwoodjs/router'

const Routes = () => {
  return (
    <Router>
      <Route path="/" page={HomePage} name="home" />
      <Route notfound page={NotFoundPage} />
    </Router>
  )
}

export default Routes
```

# API

The `api` folder contains four main directors. I will use an example from a demo application that uses FaunaDB on the backend:
* `services` - `posts.js`
* `lib` - `db.js`
* `graphql` - `posts.sdl.js`
* `functions` - `graphql.js`

## Services

```javascript
// api/src/services/posts.js

import { request } from 'src/lib/db'
import { gql } from 'graphql-request'

export const posts = async () => {
  const query = gql`{
    posts {
      data {
        title
      }
    }
  }`

  const data = await request(query, 'https://graphql.fauna.com/graphql')

  return data['posts']
}
```

## Lib

```javascript
// api/src/lib/db.js

import { GraphQLClient } from 'graphql-request'

export const request = async (query = {}) => {
  const endpoint = 'https://graphql.fauna.com/graphql'

  const graphQLClient = new GraphQLClient(endpoint, {
    headers: {
      authorization: 'Bearer ' + process.env.FAUNADB_SECRET
    },
  })

  try {
    return await graphQLClient.request(query)
  } catch (error) {
    console.log(error)
    return error
  }
}
```

## GraphQL

```javascript
// api/src/graphql/posts.sdl.js

export const schema = gql`
  type PostPage {
    data: [Post]
  }

  type Post {
    title: String
  }

  type Query {
    posts: PostPage
  }
`
```

## Functions

```javascript
// api/src/functions/graphql.js

import {
  createGraphQLHandler,
  makeMergedSchema,
  makeServices,
} from '@redwoodjs/api'
import schemas from 'src/graphql/**/*.{js,ts}'
import services from 'src/services/**/*.{js,ts}'

import { db } from 'src/lib/db'

export const handler = createGraphQLHandler({
  schema: makeMergedSchema({
    schemas,
    services: makeServices({ services }),
  }),
  db,
})
```

On the back end Redwood uses GraphQL and was initially designed to work with AWS Lambda's, so it should be a natural fit for AppSync and Amplify. So natural that there is [already an example app](https://community.redwoodjs.com/t/how-can-i-wire-up-a-graphql-api-to-redwoodjs/1112) on the community forums with AppSync that bears a close resemblance to the FaunaDB application. The challenges will revolve our how to see up auth and which database to connect.

**Describe alternatives you've considered**

### Auth

Redwood has built-in integration for a number of different [auth providers](https://redwoodjs.com/tutorial/authentication) including Netlify Identity, GoTrue, Auth0, Magic Links, GoogleAuthProvider, and Supabase. As far as I know there haven't been any integrations built for AWS authentication services.

For examples of different ways to implement auth in Redwood see the following links:

* [GoTrue Auth](https://redwoodjs.com/cookbook/gotrue-auth)
* [Role-based Access Control (RBAC)](https://redwoodjs.com/cookbook/role-based-access-control-rbac)
* [Redwood Tutorial-Blog with Netlify Identity and RBAC](https://github.com/dthyresson/redwoodblog-rbac)
* [Custom github JWT Auth with Redwood Auth](https://community.redwoodjs.com/t/custom-github-jwt-auth-with-redwood-auth/610)
* [Here’s how I implemented Auth0 on the api side](https://community.redwoodjs.com/t/how-to-heres-how-i-implemented-auth0-on-the-api-side/739)

### Database

By default Redwood uses [Prisma 2](https://redwoodjs.com/tutorial/saving-data) and most developers are connecting it to a Postgres database hosted on a service like Heroku. But there are many other ways to setup Redwood's back end including [getting rid of it entirely](https://redwoodjs.com/cookbook/disable-api-database).

Prisma does not currently support any NoSQL databases like DynamoDB (there is an [open issue](https://github.com/prisma/prisma/issues/1676) but Prisma is not actively developing any NoSQL solutions at this time).

This means that the easiest way to setup Redwood on AWS with a database would likely be RDS for PostgreSQL and there is [some documentation](https://redwoodjs.com/docs/connection-pooling#aws) explaining how to setup RDS with connection pooling.

However, I think looking at where Redwood wants to go (which seems to be a similar direction Amplify wants to go), it would be better served in the long run by DynamoDB. Then in maybe a year or two if/when Prisma starts supporting Dynamo it can be brought back in.

**Additional context**

* [redwoodjs.com](https://redwoodjs.com)
* [Community Forum](https://community.redwoodjs.com/)
* [GitHub](https://github.com/redwoodjs/redwood)

**Comment by dabit3** [comment]
Hey @ajcwebdev this is a really great issue, I appreciate you opening it. I'll be exploring this later today and will get back with you if I have any questions. We'd really love to have a Redwood + AWS tutorial in our docs!
