### ISSUE TITLE
[Bug] Amplify Docs Very Slow - takes 6 Seconds to Render Anything on screen. 7 seconds Time to Interactive. Largest Contentful Paint 8 seconds.

### ISSUE THREAD

**Issue by sw-yx** [aws-amplify/docs#2585]
**Describe the bug**

https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fdocs.amplify.aws%2Flib%2Fstorage%2Fgetting-started%2Fq%2Fplatform%2Fjs

![image](https://user-images.githubusercontent.com/6764957/97020883-b1ee8f80-1584-11eb-8047-13c5d55793e3.png)

**To Reproduce**

go to https://docs.amplify.aws/lib/storage/getting-started/q/platform/js without VPN

**Expected behavior**

it should be fast and ideally statically rendered

**Comment by mauerbac** [comment]
Fixed.
