### ISSUE TITLE
[Feedback] "amplify init" (step 2) should be executed after setting up user access with "amplify configure" (step 3)

### ISSUE THREAD

**Issue by tomtanti** [aws-amplify/docs#2592]
**Page**: [`/start/getting-started/add-api/q/integration/flutter`](https://docs.amplify.aws/start/getting-started/add-api/q/integration/flutter)

**Feedback**:
Running `amplify init` before `amplify configure` produces this error `The security token included in the request is invalid`.

**Comment by fjnoyp** [comment]
Hi @tomtanti thanks for bringing this to our attention.  We'll fix the documentation to have the proper ordering.
