### ISSUE TITLE
[Docs Request] Document Amplify as a standalone bundle

### ISSUE THREAD

**Issue by sw-yx** [aws-amplify/docs#2594]
**Is your feature request related to a problem? Please describe.**

People want to use Amplify as a standalone js bundle (eg for embedded apps within Salesforce). Its possible, but not well documented.

**Related notes**

What I’ve done is generate a standalone bundle using webpack, similar to:
https://docs.amplify.aws/start/getting-started/setup/q/integration/js

Related, here’s an example where Amplify gets exported to a global object on window:
https://github.com/aws-amplify/amplify-js/issues/4510#issuecomment-579961345

To generate the standalone bundle, you would import, configure, & export the parts of Amplify you need.

Then, this can be embedded on a page and used with calls like `window.Amplify.Auth.signIn(…)`

cc @ericclemmons

**Comment by ameykshirsagar** [comment]
I was able to do it in this way. It works perfectly
```html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="./node_modules/aws-amplify/dist/aws-amplify.min.js"></script>
    <script>

        aws_amplify.Amplify.configure({
            // content of aws-exports.js
        });

        try {
            const user = aws_amplify.Amplify.Auth.signIn("<username>", "<pass>");
            console.log(user);
        } catch (error) {
            console.log('error signing in', error);
        }

        try {
            const { user } = aws_amplify.Amplify.Auth.signUp({
                username: "<username>",
                password: "<pass>",
                attributes: {
                    email: "<email>" // optional

                }
            });
            console.log(user);
        } catch (error) {
            console.log('error signing up:', error);
        }
    </script>
</head>
<body>
    
</body>
</html>`

**Comment by nadetastic** [comment]
Closing this out as the docs have had some updates since this issue was opened. Currently the guide at [1] shows how you can do this.

[1] https://docs.amplify.aws/start/getting-started/setup/q/integration/js/
