### ISSUE TITLE
Angular tutorial does not work with latest angular cli, core and compiler.

### ISSUE THREAD

**Issue by rolance** [aws-amplify/docs#2598]
**Page**: [`/start/getting-started/setup/q/integration/angular`](https://docs.amplify.aws/start/getting-started/setup/q/integration/angular#create-a-new-amplify-backend)

**Feedback**:

Had to roll back in order to get this to work:
 ng update @angular/cli@8.3.17 @angular/core@8.2.13 @angular/compiler-cli@8.2.13

**Comment by sammartinez** [comment]
Thanks for opening this issue, I cannot reproduce what you are experiencing and testing on the latest Angular. I am going to resolve this issue as I cannot reproduce what you are experiencing. Please let us know if this continues and we can reopen this issue. Thanks !
