### ISSUE TITLE
Cognito email uniqueness

### ISSUE THREAD

**Issue by rudyhadoux** [aws-amplify/docs#260]
Hi,
For the command **amplify add auth**, the Cognito email uniqueness configuration should be the default one. It is not.
With that : 
UsernameAttributes:
       - "email"

**Comment by erinewt1982** [comment]
Thanks

**Comment by kaustavghosh06** [comment]
@rudyhadoux Please use the latest version of the CLI. We now support multiple options in the default auth flow to support this use-case.

**Comment by rudyhadoux** [comment]
Ok thanks.
