### ISSUE TITLE
[Feedback] One extra step 

### ISSUE THREAD

**Issue by ghost** [aws-amplify/docs#2603]
**Page**: [`/start/getting-started/installation/q/integration/react-native`](https://docs.amplify.aws/start/getting-started/installation/q/integration/react-native#install-and-configure-the-amplify-cli)

**Feedback**:

Hi I'm following the tutorial on how to set up react native (https://docs.amplify.aws/start/getting-started/setup/q/integration/react-native#install-amplify-libraries)

It says run this code $npx pod-install, but it didn't work. 

It had the following error:  WARNING: 'missing' script is too old or missing

I searched the error and I found someone who said run this line of code:

 $sudo xcode-select --switch /Applications/Xcode.app

I ran it and now everything works. FYI

David

**Comment by sw-yx** [comment]
cc @Kilo-Loco

**Comment by abdallahshaban557** [comment]
I have tried following the quick-start guide, and was not able to run into this issue. Closing this for now. I am making a change to pull up the creation of the app before initializing the Amplify Project.
