### ISSUE TITLE
[Feedback]Authenticator - Basic Usage section is blank

### ISSUE THREAD

**Issue by sobiyang** [aws-amplify/docs#2614]
**Page**: [`/ui/auth/authenticator/q/framework/angular`](https://docs.amplify.aws/ui/auth/authenticator/q/framework/angular#basic-usage)

**Feedback**:

The _Basic Usage_ section for the Angular version of the Authenticator UI component is blank. I'm guessing the last code block in the _Recommended Usage_ section is misplaced?

**Comment by sammartinez** [comment]
From looking at the link, I cannot produce a blank section. Im going to resolve this issue, but please let us know if you are still experiencing it.
