### ISSUE TITLE
https://aws-amplify.github.io/docs/js/api 404

### ISSUE THREAD

**Issue by tuanardouin** [aws-amplify/docs#2615]
Hello,

**Describe the bug**
JS API document return a 404

**To Reproduce**
1. https://aws-amplify.github.io/docs/js/api

Thanks

**Comment by mauerbac** [comment]
Where did you find this link? @tuanardouin

**Comment by mauerbac** [comment]
Confirmed this is 404'ing. Working to fix. For now, the docs can be viewed at https://docs.amplify.aws/

**Comment by mauerbac** [comment]
this is fixed now @tuanardouin . Sorry about that
