### ISSUE TITLE
[Feedback] AmplifyTOTPSetup is not found.

### ISSUE THREAD

**Issue by poad** [aws-amplify/docs#2626]
**Page**: [`/ui/auth/authenticator/q/framework/react`](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react)

**Feedback**:

The `AmplifyTOTPSetup` component is not found in `@aws-amplify/ui-react`.

The available component name is `AmplifyTotpSetup`.

**Comment by sammartinez** [comment]
Thanks for this feedback, we have updated our documentation to reflect this. https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#totp-setup. Resolving
