### ISSUE TITLE
Google Translated Page Routing Bug

### ISSUE THREAD

**Issue by MadakaHeri** [aws-amplify/docs#2629]
**Describe the bug**
Google Translated page routing.
The contents of the menu and the page do not match.

**To Reproduce**
1. Go to 'https://docs.amplify.aws/start/q/integration/js'
2. Google Translete -> Japanese
3. Click on 'some menu button'
4. See page content

**Expected behavior**
page transition

**Screenshots**
https://drive.google.com/file/d/1e-lCJTpNAXUbqGfOpNeuXeguuHY9xU-0/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [chrome]
 - Version [86.0.4240.111]

**Comment by mauerbac** [comment]
Thank you. We spoke on Discord. This will be entered into our product roadmap.
