### ISSUE TITLE
[missing-page]

### ISSUE THREAD

**Issue by codelious** [aws-amplify/docs#2630]
**Page**: [`https://docs.amplify.aws/ui/storage/tracking-events/q/framework/angular`](https://docs.amplify.aws/ui/storage/tracking-events/q/framework/angular)

**Feedback**: 
I can't see the documentation page for Storage Tracking Events

**Comment by akshbhu** [comment]
Hi @codelious 

 Is the above link not opening for you?

**Comment by codelious** [comment]
Hi @akshbhu 

That's right, the link to "Storage Tracking Events" doesn't open for Angular or the other frameworks

**Comment by mauerbac** [comment]
@codelious - can you try in an incognito window? Do you not see this?
![Screen Shot 2020-11-05 at 12 49 13 PM](https://user-images.githubusercontent.com/1507886/98277477-716c1a00-1f65-11eb-8367-9e92a785d60d.png)

**Comment by codelious** [comment]
@mauerbac 
Apparently it is a problem with brave browser, when trying with safari it works ok. Thank you very much

![image](https://user-images.githubusercontent.com/1330568/98283106-e8151180-1f7d-11eb-8f63-ea0000bae19e.png)
