### ISSUE TITLE
TypeScript based User Authenticatio React Project Error: Property 'username' does not exist on type 'object'.

### ISSUE THREAD

**Issue by ChihweiLHBird** [aws-amplify/docs#2642]
I followed the document, https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#basic-usage.
And I got some an error with the typescript based react project.
`Property 'username' does not exist on type 'object'.  TS2339`

My code:

```
import React from 'react';
import './App.css';
import Amplify from 'aws-amplify';
import { AmplifyAuthenticator, AmplifySignOut } from '@aws-amplify/ui-react';
import { AuthState, onAuthUIStateChange } from '@aws-amplify/ui-components';

Amplify.configure({
  Auth: {
      userPoolId: 'some ID',
      region: 'us-east-1',
      userPoolWebClientId: 'some ID'
  }
});

const AuthStateApp: React.FunctionComponent = () => {
    const [authState, setAuthState] = React.useState<AuthState>();
    const [user, setUser] = React.useState<object | undefined>();

    React.useEffect(() => {
        return onAuthUIStateChange((nextAuthState, authData) => {
            setAuthState(nextAuthState);
            setUser(authData)
        });
    }, []);

  return authState === AuthState.SignedIn && user ? (
      <div className="App">
          <div>Hello, {user.username}</div>
          <AmplifySignOut />
      </div>
  ) : (
      <AmplifyAuthenticator />
  );
}

export default AuthStateApp;

```

How can I fix it?

![image](https://user-images.githubusercontent.com/43905414/98452353-df524600-210b-11eb-8906-3f2e000dfc85.png)

**Comment by ironspur5** [comment]
I am also facing this issue. Trying to display the username within the AmplifyGreetings component. @palpatim Any update on this?

**Comment by mauerbac** [comment]
Closing as this issue is outdated and our UI docs have been updated -> https://ui.docs.amplify.aws/components/authenticator .

**Comment by shanecp** [comment]
Update the code as `user?.username`.

The error code is still present here - https://docs.amplify.aws/react/start/getting-started/auth/
