### ISSUE TITLE
Document CLI GraphQL transformer passthrough directives

### ISSUE THREAD

**Issue by attilah** [aws-amplify/docs#2647]
**Describe the bug**

Add documentation about Amplify CLI GraphQL transformer passthrough directive support for AppSync directives like `@aws_iam`, etc.

**Comment by undefobj** [comment]
@renebrandel Should basically mention that we do this for type extensions, and also explain this is what `@auth` generates under the covers anyway then link customers direct to the AppSync docs that explain these directives in detail.
