### ISSUE TITLE
GraphQL Transform - specifying keys for DynamoDB table when using @model

### ISSUE THREAD

**Issue by gvlachos** [aws-amplify/docs#265]
when using the @model directive (as described here https://aws-amplify.github.io/docs/cli/graphql#directives) is there a way to define a field for sort key ?  iiuc once the table is created in DynamoDB this is no longer possible i.e. I can't define the sort key on an existing table

**Comment by kaustavghosh06** [comment]
@gvlachos We released the @key directive to solve for your use case. Please take a look at - https://aws-amplify.github.io/docs/cli/graphql#key for more information.
