### ISSUE TITLE
How to observe changes for specific entry?

### ISSUE THREAD

**Issue by nikitazernov** [aws-amplify/docs#2650]
** Which Category is your question related to? **
DataStore / API

** What AWS Services are you utilizing? **
DynamoDB / AppSync

** Provide additional details e.g. code snippets **
The following returns a `Publisher` for the entire `Request`s table:

```swift
Amplify.DataStore.publisher(for: Request.self) ....
```

How can I get a `Publisher` for specific entry by `id`?

**Comment by jamesonwilliams** [comment]
@nikitazernov You can call the [`publisher` method](https://github.com/aws-amplify/amplify-ios/blob/eb5b7ff98ae9ac090dc8c71e374b8f3bcb0ee472/Amplify/Categories/DataStore/Subscribe/DataStoreCategory%2BSubscribe.swift#L12), and then apply [Combine's `filter` operator](https://developer.apple.com/documentation/combine/publishers/merge/filter(_:)).

**Comment by nikitazernov** [comment]
@jamesonwilliams Thanks for your suggestion. It is acceptable as a temporary solution, but what if Requests table contains million entries? It wouldn't be right to fetch them all and filter in mobile app.

**Comment by jamesonwilliams** [comment]
Hi @nikitazernov, we are currently implementing a feature called "selective sync," which should help with that issue. It doesn't hook into the `publisher` as you've suggested -- that's for monitoring changes to the local store. Will take this as a request to document Selective Sync!

**Comment by diegocstn** [comment]
hi @nikitazernov,
we released "Selective Sync" in [Amplify iOS 1.5.0](https://github.com/aws-amplify/amplify-ios/blob/main/CHANGELOG.md#150-2020-12-03), you can find the documentation [here](https://docs.amplify.aws/lib/datastore/sync/q/platform/ios#selectively-syncing-a-subset-of-your-data).
I'll optimistically close this issue but feel free to reopen if you have other questions.
