### ISSUE TITLE
[Feedback] Provide full code not snippets

### ISSUE THREAD

**Issue by bfleming-ciena** [aws-amplify/docs#2658]
**Page**: [`/start/q/integration/vue`](https://docs.amplify.aws/start/q/integration/vue)

**Feedback**:

When there is code, could it just be the entire file's content, rather than "put this at the top" snippets.  We just want to progress through the tutorial with the full code for each step and then work out the details later.

**Comment by mauerbac** [comment]
hey @bfleming-ciena - thanks for the feedback. that's helpful. We have an item to improve our code snippets, so I will add this to that work.
