### ISSUE TITLE
[Feedback] Documenation - Confirm signup code usage wrong

### ISSUE THREAD

**Issue by adampblack** [aws-amplify/docs#2659]
**Page**: [`/ui/auth/authenticator/q/framework/react`](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react)

**Feedback**:

https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#confirm-sign-up

It shows code as confirm sign in.
https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#confirm-sign-in

**Comment by mauerbac** [comment]
Thanks @adampblack - nice catch. Just put this up https://github.com/aws-amplify/docs/pull/2662

**Comment by adampblack** [comment]
Thanks, much appreciated.
