### ISSUE TITLE
Docs for organization based auth

### ISSUE THREAD

**Issue by pedroapfilho** [aws-amplify/docs#2666]
Imagine I have an app that manages salaries. Usually, these apps are made for multiple organizations, so imagine the situation where I want to disclose salary info for that organization admin, not for every admin on the user pool. I want to have an admin role for each organization.

So:

1- Admin creates organization
2- Admin adds users to the organization and sends them an email for them to sign in
3- The user signs up with that email and fills up his data.

Then I'll have a `User` model created by the `admin`, a `Cognito User` created by the `user`, and linked together.

The organization holds an array of Users, and each User has a Cognito User attached to it. This workflow would be nice to be documented because I have no idea where to start.

**Comment by pedroapfilho** [comment]
So, Anyone could help here by explaining if is there any best-practices for it? How should we add multi-tenancy on `Amplify`? How to have admins per organization? Could we create something in the docs for it?

**Comment by pedroapfilho** [comment]
Something like this:

```
type Post
  @model
  @auth(
    rules: [
      { allow: owner }
      { allow: owner, ownerField: "tenant", identityClaim: "custom:tenant" }
      { allow: groups, groups: ["OWNER", "ADMIN"], operations: [read] }
    ]
  ) {
  id: ID!
  tenant: ID!
  content: String!
  owner: String
  comments: [Comment] @connection(name: "PostComments")
}

type Comment @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  content: String
  post: Post @connection(name: "PostComments")
}

```

**Comment by palpatim** [comment]
Flagging this as a "Feature Request" for a multi-tenancy "Guide"

**Comment by palpatim** [comment]
Leaving this feature request open
