### ISSUE TITLE
amplify and .gitignore

### ISSUE THREAD

**Issue by tbehunin** [aws-amplify/docs#267]
**Describe the bug**
The `amplify <cmd>` commands generate a slew of generated files/directories, where it is unclear which should be checked into source control and which ones shouldn't. I found [this little nugget](https://aws-amplify.github.io/docs/cli/migrate#gitignore) in the docs (via searching for `.gitignore` - not navigable via the menu system btw 👎) that specifies which files should be added to the .gitignore file. After updating it as outlined there and performing other amplify commands (e.g. `init`, `add <something>`, `push`, `publish`, etc.), there are still other files and changes that I'm unsure whether they _should_ exist in source control or not:

- .amplifyrc
- amplify/.config/aws-info.json
- amplify/.config/project-config.json
- amplify/backend/auth/cognito.../...cloudformation-template.yml
- amplify/backend/auth/cognito.../parameters.json
- amplify/backend/awscloudformation/nested-cloudformation-stack.yml
- amplify/backend/hosting/S3AndCloudFront/template.json
- ...

Are the files above acceptable to be added to source control and/or are the docs updated to reflect the correct `.gitignore` files to be added?

**To Reproduce**
1. `amplify init`, `amplify add <something>`, `amplify push`, etc.

**Expected behavior**
The files generated should be acceptable to check in to source control, after applying the necessary `.gitignore` updates.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Browser chrome
 - Version 70.0.3538.110

**Smartphone (please complete the following information):**
n/a

**Additional context**
none

**Comment by kaustavghosh06** [comment]
@tbehunin Yes, thats correct. If you're using the multienv version of the CLI, a .gitignore file gets autogenerated for you (if none present) after the init step and the corresponding amplify files (to be gitignored) gets appended to it. 

Closing this issue for now. Let me know if you've further questions around this.
