### ISSUE TITLE
White blank page when viewing docs

### ISSUE THREAD

**Issue by nubpro** [aws-amplify/docs#2681]
**Describe the bug**
Open any docs page on Chrome, spinner on favicon disappears, page is blank. After several seconds later, the content loads.
This happens quite frequently in random manners.

Here's a video: https://streamable.com/8o9t48

**Desktop (please complete the following information):**
Windows Chrome 86

**Comment by mauerbac** [comment]
Thanks @nubpro. This is a known issue with our docs site. Will keep open to track.

**Comment by tjleing** [comment]
This should be mostly resolved now, but should be even more resolved once #2826 is merged in.  Will close once that's done.

**Comment by nubpro** [comment]
> This should be mostly resolved now, but it should be _even more_ resolved once #2826 is merged in. Will close once that's done.

This issue is even worse now.
All I see is a blank white page and it never loads. Had to switch to incognito mode.
![image](https://user-images.githubusercontent.com/762914/110416487-cc0db200-80ce-11eb-8928-0a670cb2877e.png)

**Comment by tjleing** [comment]
@nubpro Could you please take another look now that #2826 is in?  We're hoping that the issue is fully resolved now.

**Comment by nubpro** [comment]
> @nubpro Could you please take another look now that #2826 is in? We're hoping that the issue is fully resolved now.

Yes, it definitely works a lot better now.
I think it's safe to say we can put this behind us :)
