### ISSUE TITLE
Fonts used in the docs is creating artifacts on normal zoom level

### ISSUE THREAD

**Issue by DevTGhosh** [aws-amplify/docs#2696]
**Describe the bug**
The font used in the docs has weird artifacts that are visible on a 1080p 15.6inch laptop screen. Most visible on bold text but can also be seen on normal text too if looked closely. This is visible on firefox, edge and chrome. 

**To Reproduce**

1. Go to: [https://docs.amplify.aws/cli/graphql-transformer/auth#owner-authorization](https://docs.amplify.aws/cli/graphql-transformer/auth#owner-authorization)

Check the bold text, also check the g in `signed` in the plain text
![image](https://user-images.githubusercontent.com/25743418/100128606-79551500-2ea6-11eb-995e-1dffb576cbf8.png)

**Expected behavior**
No artifacts

**Comment by DevTGhosh** [comment]
Issue is still there.

**Comment by medelman17** [comment]
@jakeburden and @tjleing -- can you get to the bottom of the above?

**Comment by jakeburden** [comment]
We can try adding some font smoothing and antialiasing css properties to the text.

@DevTGhosh when you have a chance could you let me know which operating system you are seeing this on? Thank you!

**Comment by DevTGhosh** [comment]
@jakeburden Windows 10.

**Comment by fortejas** [comment]
I've noticed these too - seems to be smoothing / css / rendering thing. I'm on Windows 10 - Firefox. Just looks a bit unpolished - doesn't really affect functionality.

![Badly rendered fonts](https://user-images.githubusercontent.com/38068706/144465102-ee7be8ad-0dcc-488a-b185-65eae5f6a0a0.PNG)

**Comment by mauerbac** [comment]
Is this still an issue?
