### ISSUE TITLE
UI Components > Auth > "Select MFA Type" shows undefined

### ISSUE THREAD

**Issue by watilde** [aws-amplify/docs#2705]
**Describe the bug**
UI Components > Auth > "Select MFA Type" shows `undefined ` when I come from "Sign out" menu.

**To Reproduce**
1. Open https://docs.amplify.aws/ui/auth/select-mfa-type/q/framework/react
2. Click "Sign Out" in the side bar
2. Click "Select MFA Type" in the side bar
3. See `undefined`

**Expected behavior**
It should show `Properties` table.

**Screenshots**
<img width="660" alt="Screen Shot 2020-11-25 at 21 30 14" src="https://user-images.githubusercontent.com/1716463/100228032-6c4b2b00-2f65-11eb-9b8b-dd77a070a2d0.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version Version 87.0.4280.67 (Official Build) (x86_64)

**Additional context**
Originally reported at https://twitter.com/tacck/status/1331446663299272706.

**Comment by mauerbac** [comment]
Thanks @watilde . I see Sam will review your PR

**Comment by watilde** [comment]
This seems to be still exisiting. I'd appriciate if I can ask for your team's review on PR :)

**Comment by medelman17** [comment]
Thanks, @watilde, for bumping this. Will start to ping relevant stakeholders tomorrow to get resolution ASAP. My apologies for the delayed response.
