### ISSUE TITLE
How to setup multi-datacenter infrastructure

### ISSUE THREAD

**Issue by GeorgeBellTMH** [aws-amplify/docs#2709]
Until there is a way to do this from the cli, it would be good to document how to run amplify across multiple data-centres and setup data-syncs.

**Comment by GeorgeBellTMH** [comment]
https://github.com/aws-amplify/amplify-cli/issues/5971

**Comment by mauerbac** [comment]
Hi @GeorgeBellTMH - to be clear, you'd like documentation on how to deploy Amplify in multiple Regions (what we call datacenters ) ?

**Comment by GeorgeBellTMH** [comment]
Yes, multiple regions. It may be useful to give examples of how to setup a few different use-cases or designs that may be common.

- multiple active/loadbalanced regions where users can end up using any region
- directing users to their local region and keeping local data in that region
- multiple regions used in an active/passive - where one region becomes active if another region is unavailable 
- situations that are unsupported, or unlikely to work currently

It would also be good to discuss how to manage data, including:
- syncing data between data centres
- not syncing data
- custom syncing
- how this works for s3, dynamo, dB, pinpoint, cognito, etc...

It may also be useful to have cli commands to help with the above. I know in theory it's possible now to just deploy to multiple regions using environments...but it may be helpful to include multiple regions in an environment (ie prod has us-east-1 and us-west-1) with some mechanisms used in development and deployment to make this smooth (ie be able to do an a-b deployment, or be able to do both simultaneously)

**Comment by ykethan** [comment]
Hey, Amplify currently supports utilizing `amplify export` to export a Amplify project to CDK this would enable cross region and cross account capabilities. Please refer to https://docs.amplify.aws/cli/usage/export-to-cdk/ for additional information.
Closing the issue due to age.
