### ISSUE TITLE
Amplify push error

### ISSUE THREAD

**Issue by martinduo** [aws-amplify/docs#2713]
**Page**: [`/start/getting-started/installation/q/integration/react`](https://docs.amplify.aws/start/getting-started/installation/q/integration/react)

**Feedback**:

I'm working on your tutorial, but I am stuck at the step where I enter the command "amplify push". 
Apparently tmdir is blocked trying to delete the amplify/.temp folder. I'm on Windows 10, and have tried clearing the Read-only attribute in its properties. But it keeps being reset to Read-only.

The error is:
C:\Users\Bruce\Dropbox\Code\AWS TUTS\react-amplified>amplify push
× There was an error pulling the backend environment dev.
An error occurred during the push operation: EBUSY: resource busy or locked, rmdir 'C
'C:\Users\Bruce\Dropbox\Code\AWS TUTS\react-amplified\amplify\.temp'

Everything worked up to this point (some of the command line prompts were different than shown in the tutorial, but easy to work around.)

Thanks in advance for any help.
Bruce

**Comment by mauerbac** [comment]
hi @martinduo - i haven't seen that error before. Let me see who can reproduce that on a windows machine. Stay tuned. Thank you

**Comment by renebrandel** [comment]
Hi - I believe this issue is fixed in the latest version of the CLI. Can you try updating to the latest version and re-open this issue if it's still present.
