### ISSUE TITLE
[missing-page]

### ISSUE THREAD

**Issue by ScarredDemonIV** [aws-amplify/docs#2714]
**Page**: [`https://docs.amplify.aws/ui/storage/tracking-events/q/framework/angular`](https://docs.amplify.aws/ui/storage/tracking-events/q/framework/angular)

**Feedback**:

**Comment by mauerbac** [comment]
Can you provide more details? Please try in an incognito mode without browser extensions.

**Comment by ScarredDemonIV** [comment]
Interesting. Apologies should've included more info.
I was expecting the link to give the same behavior as I experienced.

The page seems fine in a cognito window.
Getting a 404 in a normal chrome window.
