### ISSUE TITLE
How to configure AppSync Websocket endpoint?

### ISSUE THREAD

**Issue by kevzettler** [aws-amplify/docs#2716]
How do I specify a websocket endpoint using `Amplify.configure(awsConfig)` The docs only demonstrate how to do a http endpoint using the `aws_appsync_graphqlEndpoint`

https://docs.amplify.aws/lib/client-configuration/configuring-amplify-categories/q/platform/js#graphql-api-aws-appsync

I have separate appsync urls one is a `realtime` websocket  url.

```
REACT_APP_GRAPHQL_ENDPOINT_HTTP=https://cdbpiojsfvegvo552oijlydjau.appsync-api.us-west-2.amazonaws.com/graphql
REACT_APP_GRAPHQL_ENDPOINT_WS: wss://cdbpiojsfvegvo552oijlydjau.appsync-realtime-api.us-west-2.amazonaws.com/graphql
```

**Comment by mauerbac** [comment]
This looks to be updated. Please let me know if that is not the case.
