### ISSUE TITLE
[Feedback]Wrong Code snippet when testing GraphQL locally.

### ISSUE THREAD

**Issue by absynthe** [aws-amplify/docs#2718]
**Page**: [`/start/getting-started/data-model/q/integration/next`](https://docs.amplify.aws/start/getting-started/data-model/q/integration/next#create-a-graphql-api-and-database)

**Feedback**:

In the GraphiQL toolbar, select Use: User Pool and try creating a post: 

```
mutation CreatePost {
  createPost(input: {title: "Test Post", content: "post content"}) {
    id
    owner
    title
    updatedAt
    createdAt
    content
  }
}
```

updatedAt and createdAt are not in the definition of the Post type.

**Comment by absynthe** [comment]
Same for :

```
query ListPosts {
  listPosts {
    items {
      content
      createdAt
      id
      owner
      title
    }
  }
}

```

There is no createdAt.

**Comment by absynthe** [comment]
Under API with Incremental Static Site Generation (SSG) the code explanation mentions handleCreatePost and Home, but those are not part of the [id].js code.

**Comment by frimfram** [comment]
The timestamp fields (createdAt/updatedAt) are auto-generated by the model directive. Though they are not in the schema written by graphql SDL, they do get generated in the `build/schema.graphql`. This is the expected behavior.
