### ISSUE TITLE
Code blocks should have a horizontal scroll bar

### ISSUE THREAD

**Issue by triqi** [aws-amplify/docs#274]
**Is your feature request related to a problem? Please describe.**
Where ever there is a code block showing example implementation, some of the example code is longer than the width of the code block and requires horizontal scrolling. The current code blocks do not allow for horizontal scrolling, which makes viewing the code difficult.

**Describe the solution you'd like**
The simplest solution is to allow the code block to scroll horizontally.

**Describe alternatives you've considered**
The optimal solution is to use a feature-rich code viewer, such as the [Monaco Editor (powered by VS Code](https://github.com/Microsoft/monaco-editor)). This will allow viewers to choose how they would like to view the code, such as wrapped, reduced size, etc.

**Additional context**
![image](https://user-images.githubusercontent.com/2232035/49512957-98d28c00-f8e3-11e8-97a3-21a9a38b1d30.png)

**Comment by nikhil-dabhade** [comment]
@triqi : I think I am more clear on your request. You were asking to have an explicit horizontal scroll bar rather than using keyboard or a touch pad.

**Comment by triqi** [comment]
@nikhil-dabhade, I am using Chrome on Windows 10 and no touch input (just mouse and keyboard). So yes, the only way I'm able to see the hidden text (albeit difficultly) is to use the mouse "drag-select" on the hidden text, which causes the scroll to happen.
