### ISSUE TITLE
[Feedback] confusing grammar

### ISSUE THREAD

**Issue by cyrfer** [aws-amplify/docs#2746]
**Page**: [`/lib/datastore/how-it-works/q/platform/js`](https://docs.amplify.aws/lib/datastore/how-it-works/q/platform/js)

**Feedback**:

This is not a complete sentence. Please adjust it to convey meaning.

> For many-to-many relations, such as the one shows in the GraphQL Transformer examples.

https://docs.amplify.aws/lib/datastore/relational/q/platform/js#many-to-many

**Comment by jamesonwilliams** [comment]
Thanks for catching it, let me know if @2750 helps.

**Comment by cyrfer** [comment]
@jamesonwilliams thank you. It helps a lot. 👍
