### ISSUE TITLE
[Feedback]FEEDBACK_TITLE_HERE

### ISSUE THREAD

**Issue by grgkro** [aws-amplify/docs#2747]
**Page**: [`/lib/auth/getting-started/q/platform/android`](https://docs.amplify.aws/lib/auth/getting-started/q/platform/android)

**Feedback**:
on https://docs.amplify.aws/lib/auth/getting-started/q/platform/android#next-steps under section"Initialize Amplify Auth"
you say:

"Add the Auth plugin along with any other plugins you added per the instructions in the Prerequisites section:"

Where do I have to add the code exactly? In the Prerequisites section there is nothing said about plugins?

**Comment by jamesonwilliams** [comment]
Hi @grgkro, it refers to the [code you added during Project Setup](https://docs.amplify.aws/lib/project-setup/create-application/q/platform/android#n4-initialize-amplify-in-the-application). PR #2749 makes a minor update to the instruction, to make that link more clear.

```kotlin
try {
    Amplify.addPlugin(AWSAuthCognitoPlugin())
    Amplfiy.configure(applicationContext)
} catch (error: AmplifyException) {
    Log.e("YourApp", "Failed to initialize Amplify.", error)
}
```
