### ISSUE TITLE
[Feedback] Authenticator example request for custom fields on sign-up component

### ISSUE THREAD

**Issue by glb** [aws-amplify/docs#2748]
**Page**: [`/ui/q/framework/react`](https://docs.amplify.aws/ui/q/framework/react)

**Feedback**:

There are examples for customizing the sign-up to omit or customize default fields, but there isn't one for adding custom fields. The reference hints that it might be possible to do so, and a quick peek into the code hints something similar in the `FormFieldType` declaration, but if it's possible to add a custom field I'm really unsure what `type` might be or how it would map into the user attributes.

```ts
FormFieldType {
    type: string;
    label?: string;
    placeholder?: string;
    hint?: string | FunctionalComponent | null;
    required?: boolean;
    handleInputChange?: (inputEvent: Event) => void;
    value?: string;
    inputProps?: object;
    disabled?: boolean;
}
```

Doing some experimenting, I found that `type` is used as the attribute name when creating the user.

It would be super-helpful to include an example of this use case in the documentation.

**Comment by glb** [comment]
Perhaps something like this?

```
    <AmplifyAuthenticator usernameAlias="email" initialAuthState="signup">
      <AmplifySignUp
        slot="sign-up"
        usernameAlias="email"
        formFields={[
          { type: "email" },
          { type: "password" },
          {
            type: "name",
            label: "Name",
            placeholder: "What should we show as your name?",
          },
          {
            type: "custom:bio",
            label: "Bio",
            placeholder: "Tell us a little about yourself",
          },
          {
            type: "custom:pronouns",
            label: "Pronouns",
            placeholder: "What are your pronouns?",
          },
          {
            type: "custom:location",
            label: "Location",
            placeholder: "Where are you?",
          },
        ]}
      />
    </AmplifyAuthenticator>
```

**Comment by siegerts** [comment]
Hi @glb, Thanks for opening. The new UI Authenticator docs go into this in more detail - https://ui.docs.amplify.aws/components/authenticator#form-field-customization
