### ISSUE TITLE
Android Getting Started - code snippet requires additional info 

### ISSUE THREAD

**Issue by hjp709394** [aws-amplify/docs#2754]
**Page**: [`/start/getting-started/nextsteps/q/integration/android`](https://docs.amplify.aws/start/getting-started/nextsteps/q/integration/android)

**Feedback**:

In the above page, it fails to mentioned that AWSApiPlugin needs to be added into the initialization code: 'Amplify.addPlugin(new AWSApiPlugin());' missing this will introduce a lot of confuse to new users. Hope you can fix it quick.

**Comment by jamesonwilliams** [comment]
Hi @hjp709394. The page you've linked is the "next steps" page, which includes no setup steps, itself. I'm guesting your referring to the page before it, ["Connect to the cloud"](https://docs.amplify.aws/start/getting-started/add-api/q/integration/android). This page does contain sample code that includes the line `Amplify.addPlugin(new AWSApiPlugin());`. Please let us know if we can clarify anything further.
