### ISSUE TITLE
Customize initial authState

### ISSUE THREAD

**Issue by ikarakus** [aws-amplify/docs#2755]
**Page**: [`/ui/auth/authenticator/q/framework/angular`](https://docs.amplify.aws/ui/auth/authenticator/q/framework/angular#usage-1)

**Feedback**:

Hello,

I want to set the amplify-authenticator with signup state first. Bu I couldn't succeed. Could you please help me?

Best regards,

**Comment by mauerbac** [comment]
Hello! Can you provide more information around steps you followed to complete this? What was the result? What was the expected result? It might be easier to use a GitHub discussion in our JS repo for this: https://github.com/aws-amplify/amplify-js/discussions

**Comment by ikarakus** [comment]
<amplify-authenticator usernameAlias="email"  [initialAuthState]="signup">
          <amplify-sign-up
            slot="sign-up"
            usernameAlias="email"
          ></amplify-sign-up>
          <amplify-sign-in
            slot="sign-in"
            usernameAlias="email"
            [formFields]="signInFields"
          ></amplify-sign-in>
    </amplify-authenticator>

I am setting  the  amplify-authenticator as [initialAuthState]="signup". Bu it doesn't work. That's angular project.
