### ISSUE TITLE
Failed to apply plugin [id 'com.amplifyframework.amplifytools'] in Android Studio

### ISSUE THREAD

**Issue by mstfldmr** [aws-amplify/docs#2759]
**Describe the bug**

**To Reproduce**

Followed the steps at [https://docs.amplify.aws/start/getting-started/setup/q/integration/android#add-amplify-to-your-application](https://docs.amplify.aws/start/getting-started/setup/q/integration/android#add-amplify-to-your-application)

1- Add to build.gradle (:app):
`implementation 'com.amplifyframework:aws-api:1.6.4'
 implementation 'com.amplifyframework:aws-datastore:1.6.4'`

2- Add to dependencies section of build.gradle (Todo):
`classpath 'com.amplifyframework:amplify-tools-gradle-plugin:0.2.1'`

3- Add to the end of build.gradle (Todo):
`apply plugin: 'com.amplifyframework.amplifytools'`

4- Sync gradle

**Result:**
`Error: Command failed with ENOENT: amplify init --quickstart --frontend android`

```
Build file '/Users/aldemim/AndroidStudioProjects/Todo/build.gradle' line: 31

A problem occurred evaluating root project 'Todo'.
> Failed to apply plugin [id 'com.amplifyframework.amplifytools']
   > Process 'command 'npx'' finished with non-zero exit value 1
```

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.7
 - Tool: Android Studio 4.1.1
 - API: 21
 - Target SDK: 29

**Comment by jamesonwilliams** [comment]
Hi @mstfldmr! The current version of the Gradle plugin is 1.0.2. Please update your dependency to:
```gradle
classpath 'com.amplifyframework:amplify-tools-gradle-plugin:1.0.2'
```
Let us know if you're still facing problems after this.
