### ISSUE TITLE
Documentation bug in instruction for adding amplify-authenticator

### ISSUE THREAD

**Issue by samira-zarandioon** [aws-amplify/docs#277]
The documentation at https://aws-amplify.github.io/docs/js/ionic states:

"To use Authenticator, just add the amplify-authenticator directive in your .html view
```  
  ...
  <amplify-authenticator framework="Ionic"></amplify-authenticator>
  ...
```
"

However, when I did this I go the following error:

```'amplify-authenticator' is not a known element:```

I had to add the following so that the error goes away:

```
...
import { AmplifyAngularModule, AmplifyIonicModule, AmplifyService } from 'aws-amplify-angular' // Added by me
...
@NgModule({
  imports: [
...
    AmplifyAngularModule, // Added by me
    AmplifyIonicModule,   // Added by me
...
```

If you search the Internet, you will see that I'm not the only one facing this issue, the documentation needs to be fixed.

**Comment by AustinBrock** [comment]
Thank you very much, @samira-zarandioon, I indeed was struggling with this until I found your post.

**Comment by jordanranz** [comment]
Documentation for adding the angular and ionic module can be found here:
https://aws-amplify.github.io/docs/js/angular#option-1-configuring-the-amplify-provider-with-every-amplify-js-module

The docs for the Ionic component have been updated here:
https://aws-amplify.github.io/docs/js/angular#ionic-4-components
