### ISSUE TITLE
Migrating from old Authenticator to ui-react libraries - another breaking change not listed

### ISSUE THREAD

**Issue by jfo8000** [aws-amplify/docs#2782]
https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#authenticate-with-email-or-phone-number
There is one more breaking change in the Authenticator

The name of the federated providers has changed from underscores to camel casing

Old
```
const federated = {
    facebook_app_id: "facebook app id",
    google_client_id:"google app id",
  }
 ```
  
New
```
const federated = {
    facebookAppId: "facebook app id",
    googleClientId:"google app id",
  }
 ```
 
  If you use your existing constant you get a blank area where the buttons should be.

**Comment by jfo8000** [comment]
Section that needs updating:


**Breaking changes for withAuthenticator**
We have deprecated some of the properties passed into withAuthenticator. If you were providing additional options to withAuthenticator (e.g. includeGreetings, authenticatorComponents, federated, theme), these have changed. Refer to the updated list of Properties here.

The previous withAuthenticator component would render a Greetings and Sign Out button at the top of your app after logging in. If you would like to add a Greetings or Sign Out button to your app you can add the AmplifyGreetings or AmplifySignOut component to your app. Visit the withAuthenticator example above to see this.

**Comment by mauerbac** [comment]
Thanks for flagging this @jfo8000 . Let me work with the JS team to get this updated.

**Comment by mauerbac** [comment]
Closing as we have new Auth UI docs -> https://ui.docs.amplify.aws/components/authenticator
