### ISSUE TITLE
Link Broken

### ISSUE THREAD

**Issue by GabrielSuttner** [aws-amplify/docs#2787]
**Page**: [`/ui/q/framework/react-native`](https://docs.amplify.aws/ui/q/framework/react-native)

**Feedback**:

The link under Customization > Theming > "For React Native, you must override properties defined in AmplifyTheme.js here" is broken. 
I think it is supposed to go here: https://github.com/aws-amplify/amplify-js/blob/main/packages/aws-amplify-react/src/Amplify-UI/Amplify-UI-Theme.tsx

Also related to this post, custom themes aren't overwriting the default ones. I'm trying to simply change the default SIGN IN button color to blue instead of orange: 

```

import 'react-native-gesture-handler';
import * as React from 'react';

import {DrawerNavigator} from './navigation';

import {createStore, combineReducers, applyMiddleware} from 'redux';
import ReduxThunk from 'redux-thunk';
import {Provider, useDispatch, useSelector} from 'react-redux';
import {NavigationContainer} from '@react-navigation/native';

import {withAuthenticator, AmplifyTheme} from 'aws-amplify-react-native';
import Amplify from 'aws-amplify';

const myButton = Object.assign({}, AmplifyTheme.button, {
  backgroundColor: 'blue',
});
const MyTheme = Object.assign({}, AmplifyTheme, {
  button: myButton,
});

import reducers from './store/reducers';

import {COGNITO_CONFIG} from './constants';

Amplify.configure(COGNITO_CONFIG);

const rootReducer = combineReducers({
  user: reducers,
});

const store = createStore(rootReducer, applyMiddleware(ReduxThunk));

const app = () => {
  return (
    <Provider store={store}>
      <NavigationContainer>
        <DrawerNavigator />
      </NavigationContainer>
    </Provider>
  );
};

export default withAuthenticator(app, {
  includeGreetings: true,
  usernameAttributes: 'email',

  theme: {MyTheme},
  signUpConfig: {header: 'Welcome to Celeste, Please sign up'},
});
```

I'm using .button because that's the only one that would seem to work according to https://github.com/aws-amplify/amplify-js/blob/main/packages/aws-amplify-react-native/src/AmplifyTheme.ts. All other configuration stuff for the Authenticator work besides custom themes for me.

**Comment by medelman17** [comment]
Theming-related issues were fixed here: https://github.com/aws-amplify/amplify-js/pull/7925
