### ISSUE TITLE
Document DataStore queries for 1:n and m:n relationships

### ISSUE THREAD

**Issue by jamesonwilliams** [aws-amplify/docs#2791]
Currently, if you have a 1:n or m:n relationship, and you attempt to query the parent object, the returned objects will have null children. This is a surprising system behavior, and it is not documented as explicitly as it ought to be. Internally, the team is working to add support for "lazy loading," which would change this behavior. However, until that happens, we should document the suggested workaround.

For 1:n relationships, the suggested workaround is to query the _child_ type. The user provides a predicate  for the child. The predicate matches any child whose parent is the original parent.

For m:n relationships, the suggested workaround is to query the join table. For example, if you have `m`-many `Resident`s, and `n`-many `City`s, you would query the `ResidentCity`s table. As in the 1:n case, you need to supply a predicate. The predicate will match against _either_ the resident ID or the city ID, to get the IDs of the entity on the other side of the relationship. Lastly, you can use this list of IDs to query directly for items by ID.

cc: @iartemiev @drochetti

**Comment by jamesonwilliams** [comment]
@NinaSoroush also pointed out that: 

> The workaround should work but the only caveat is that UserContentCategory model has @model(queries: null) which is the way it is suggested to be done in [the docs](https://docs.amplify.aws/lib/datastore/relational/q/platform/flutter#many-to-many docs).

**Comment by medelman17** [comment]
Closed by #3216
