### ISSUE TITLE
clientmetadata null inconsistency

### ISSUE THREAD

**Issue by mauerbac** [aws-amplify/docs#2793]
From Cognito Engineering team -- 

The presence of Client Metadata in Post Auth depends on whether the Post Auth trigger is invoked from InitiateAuth API or RespondToAuthChallenge API.
If it is the former, that client metadata will be null, if it's through RespondToAuthChallenge api then the client metadata will be passed along.

In the case of the remembered device a DEVICE_SRP_AUTH challenge is throw in InitiateAuth, and the sdk invoked RespondToAuthChallenge to get tokens.

In the 'Don't Remember Device' setting, the token's are immediately issued immediately after InitiateAuth, and therefore RespondToAuthChallenge is not invoked and client metadata will NOT be returned.

**Comment by mauerbac** [comment]
https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference...

https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-...

In above link we no where talk about device remembered or not may have different behavior. Other side on postauth trigger docs we mention to use clientmetadata which is null if device remembered.

Here is with or without device remember event on post trigger lambda:
----------:Post auth device remembered:----
{
"ApplicationName": "PostAuthenticationTrigger",
"ApplicationGroup": "AccountManagement",
"Domain": "auth",
"Message": "LAMBDA REQUEST",
"LogLevel": 2,
"Data": {
"request": {
"newDeviceUsed": false,
"userAttributes": {
"email": "r***m",
"email_verified": "true",
"phone_number": "+***3",
"phone_number_verified": "true",
"custom:taxcamp_id": "9825240"
},
"clientMetadata": null
},
"response": {},
"version": "1",
"triggerSource": "PostAuthentication_Authentication",
"region": "us-east-1",
"userPoolId": "u***J",
"callerContext": {
"awsSdkVersion": "aws-sdk-unknown-unknown",
"clientId": "4***8"
},
"userName": "r***2"
},
"TimeStamp": "2020-11-30T22:37:22.2597763+00:00"
}


------:Post auth device not remembered:----
{
"ApplicationName": "PostAuthenticationTrigger",
"ApplicationGroup": "AccountManagement",
"Domain": "auth",
"Message": "LAMBDA REQUEST",
"LogLevel": 2,
"Data": {
"request": {
"newDeviceUsed": false,
"userAttributes": {
"email": "s***m",
"email_verified": "true",
"phone_number": "+***2",
"phone_number_verified": "true",
"custom:taxcamp_id": "9908104"
},
"clientMetadata": {
"ResponseRecapcha": "xxxxxxxx",
"DeviceKey": "us-east-1_xxxxxx",
"ip_address": "204.19.204.126, 107.162.4.81, 10.61.78.100"
}
},
"response": {},
"version": "1",
"triggerSource": "PostAuthentication_Authentication",
"region": "us-east-1",
"userPoolId": "u***J",
"callerContext": {
"awsSdkVersion": "aws-sdk-unknown-unknown",
"clientId": "4***8"
},
"userName": "s***9"
},
"TimeStamp": "2020-11-30T22:37:14.8439168+00:00"
}

If this behaviour is expected then we might need to update the documentation and specify device remembered /not remember behaviour.

**Comment by man-andy** [comment]
Hi @mauerbac 
We are also having this issue. Did you managed to fix this?
