### ISSUE TITLE
How to invoke a hello world lambda?

### ISSUE THREAD

**Issue by cosimtaiuz** [aws-amplify/docs#2802]
I cannot for the life of me understand how I am supposed to invoke a lambda I created through Amplify.
It's not documented anywhere and this makes me think that maybe the only way one should use Lambdas created via Amplify is via triggers? I.e. one cannot invoke it via code in, say, a react app?

What I am trying to do is the following (in a react app):
1. Upload a series of images  as "protected"
2. After that's finished, invoke a Lambda which takes the first one of these images from the S3 bucket and reduces its size, then stores the result, again as "protected"
3. Update an entry in my GraphQL API

Could you maybe add some more info in the documentation on how to do something like this?

Thanks in advance.

**Comment by jamesonwilliams** [comment]
Hey @cosimtaiuz! In a nutshell, Amplify wants you to invoke your Lambda function through an API Gateway. Checkout the documentation on [integrating the API (REST) category](https://docs.amplify.aws/lib/restapi/getting-started/q/platform/js).

That documentation actually does show you how to invoke a Lambda without API Gateway, too. But there's a big orange warning under it, that reads:

> THIS IS NOT A RECOMMENDED ARCHITECTURE and we highly recommend you leverage AWS AppSync or API Gateway as the endpoint to invoke your Lambda functions.

--------

That said, invoking the lambda directly from an S3 trigger sounds like a better solution to me. Less calls the client needs to make.

**Comment by cosimtaiuz** [comment]
Thanks @jamesonwilliams , I'll take a look!
