### ISSUE TITLE
[Feedback]Flutter Identify User Code Sample Incomplete

### ISSUE THREAD

**Issue by danallen88** [aws-amplify/docs#2807]
**Page**: [`/lib/analytics/identifyuser/q/platform/flutter`](https://docs.amplify.aws/lib/analytics/identifyuser/q/platform/flutter)

**Feedback**:

In the code snippet on the above page, the code sample does not indicate how to acquire the userId, nor does it show how the configured properties are used when identifying the user.  The `userProfile` variable is also not used, as there is a misnamed variable `profile` that gets passed to the `userProfile` named parameter.

**Comment by mauerbac** [comment]
Thanks for flagging @danallen88 . I'll pass to the flutter team.
