### ISSUE TITLE
No Selective Sync documentation for iOS

### ISSUE THREAD

**Issue by jamesonwilliams** [aws-amplify/docs#2810]
DataStore includes a feature called "selective sync," wherein a user can provide predicates to specify what data should be synchronized.

This feature is documented for [JavaScript](https://docs.amplify.aws/lib/datastore/sync/q/platform/js#selectively-syncing-a-subset-of-your-data) and [Android](https://docs.amplify.aws/lib/datastore/sync/q/platform/android#selectively-syncing-a-subset-of-your-data).

**However**, we haven't done iOS docs for it, yet. Note that it is [currently absent from the corresponding iOS sync docs](https://docs.amplify.aws/lib/datastore/sync/q/platform/ios).

**Comment by diegocstn** [comment]
PR: https://github.com/aws-amplify/docs/pull/2857
