### ISSUE TITLE
[Feedback]FEEDBACK_TITLE_HERE

### ISSUE THREAD

**Issue by YoLoADR** [aws-amplify/docs#2814]
**Page**: [`/ui/storage/s3-image/q/framework/react-native`](https://docs.amplify.aws/ui/storage/s3-image/q/framework/react-native)

**Feedback**:
On React Native, we don't have something clear. On the web we find a lot of things obsolete and in particular for storage bucket and datastore

**Comment by amhinson** [comment]
Would you be able to elaborate on what you're looking for? Are you having issues with the components, or just the documentation?

**Comment by medelman17** [comment]
Closing as stale. Please reopen should further context become available.
