### ISSUE TITLE
How can I get the values from FormFieldTypes in the aws-amplify/ui-components library?

### ISSUE THREAD

**Issue by DeniseJames** [aws-amplify/docs#2821]
**Page**: [`/ui/auth/authenticator/q/framework/angular`](https://docs.amplify.aws/ui/auth/authenticator/q/framework/angular#custom-form-fields)

**Feedback**:

I would like to get the values from the form that is used on sign up. How can I do that?

import { Component } from '@angular/core';
import { FormFieldTypes } from '@aws-amplify/ui-components';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  formFields: FormFieldTypes;

  constructor() {
    this.formFields = [
      {
        type: "email",
        label: "Custom email Label",
        placeholder: "custom email placeholder",
        required: true,
      },
      {
        type: "password",
        label: "Custom Password Label",
        placeholder: "custom password placeholder",
        required: true,
      },
      {
        type: "phone_number",
        label: "Custom Phone Label",
        placeholder: "custom Phone placeholder",
        required: false,
      },
    ];
  }
}

This is the HTML from the auth example:

<amplify-authenticator usernameAlias="email">
  <amplify-sign-up
    slot="sign-up"
    usernameAlias="email"
    [formFields]="formFields"
  ></amplify-sign-up>
  <amplify-sign-in slot="sign-in" usernameAlias="email"></amplify-sign-in>
</amplify-authenticator>

**Comment by mauerbac** [comment]
hi @DeniseJames - so sorry for the delay here and that this slipped through our cracks. We should have transferred this question to our JS repo. If you are still having an issue, please join our community on discord (www.discord.gg/amplify) or open a new issue and tag me. Thank you!
