### ISSUE TITLE
[Feedback]Update Tutorial Documentation

### ISSUE THREAD

**Issue by polymorcodeus** [aws-amplify/docs#2822]
**Page**: [`/start/getting-started/add-api/q/integration/ios`](https://docs.amplify.aws/start/getting-started/add-api/q/integration/ios)

**Feedback**:

Heya-

Going through this tutorial and it looks like the steps are out of date. I've had to supplement with things learned [here](https://aws.amazon.com/getting-started/hands-on/build-ios-app-amplify/) as well as some basic troubleshooting found [here]( https://github.com/aws-amplify/amplify-cli/issues/5339). The code syntax is different and/or just doesn't work, perform what the tutorial states. Once you make it past the initial tutorial, you'll find those same solutions, but the quick start should be stand alone without the need for any additional knowledge or experience.

**Comment by royjit** [comment]
@polymorcodeus  Thank you for bring this to our notice. I am listing down the issues I found so far. Feel free to add if I missed something. We will address each one. You have mentioned about code syntax, can you provide more information regarding the issue?

Issues found so far:

1. Under [`Provision backend`](https://docs.amplify.aws/start/getting-started/add-api/q/integration/ios#provision-backend) no explanation regarding `amplify init` - 
2. Under  [`Provision backend`](https://docs.amplify.aws/start/getting-started/add-api/q/integration/ios#provision-backend) no explanation regarding the question "? Do you want to generate code for your newly created GraphQL API" when you try `amplify push`
3. Under [`Query for mutations using the console`](https://docs.amplify.aws/start/getting-started/add-api/q/integration/ios#query-for-mutations-using-the-console), `amplify console api` gives the following error: 
```terminal
$ amplify console api
? Please select from one of the below mentioned services: GraphQL
Error opening console.
Missing AmplifyAppId in amplify-meta.json

$ amplify --version
4.41.2
```

**Comment by royjit** [comment]
# 3 above was because my account reached it limit for the number of apps. - https://github.com/aws-amplify/amplify-cli/issues/6598.

**Comment by royjit** [comment]
The other two issues has been updated in the doc. https://github.com/aws-amplify/docs/pull/2935

**Comment by medelman17** [comment]
@royjit -- can you propose some new documentation to mitigate these issues going forward?

**Comment by royjit** [comment]
The reported issues are addressed, and there is no action item left. I am closing this issue.
