### ISSUE TITLE
[Feedback]Misleading directions

### ISSUE THREAD

**Issue by polymorcodeus** [aws-amplify/docs#2823]
**Page**: [`/lib/project-setup/create-application/q/platform/ios`](https://docs.amplify.aws/lib/project-setup/create-application/q/platform/ios)

**Feedback**:

The screenshot has you creating a SwiftUI application, however all the subsequent directions for for an AppDelegate UI.

**Comment by mauerbac** [comment]
Thanks @polymorcodeus .

**Comment by lawmicha** [comment]
hi @polymorcodeus , thanks for bringing this up. Before we make any changes to the documentation, i'd like to make sure new directions address your feedback

1. When creating a SwiftUI app, you can select Life Cycle: UIKit App Delegate. this should give you the AppDeleate.swift to follow along with the directions.

2. If you prefer to create the App with "SwiftUI App" Lifecycle, i believe you can initialize in a constructor you create yourself inside `@main` like this:

```swift
import SwiftUI
import Amplify

@main
struct testingSwiftUIAppApp: App {
    init() {
        do {
            try Amplify.configure()
        } catch {
            print("An error occurred setting up Amplify: \(error)")
        }
    }
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
```

3. If you do require the AppDelegate for other reasons, you may attach one like so:
```swift
import SwiftUI
import Amplify

@main
struct testingSwiftUIAppApp: App {
    @UIApplicationDelegateAdaptor(AppDelegate.self) private var appDelegate

    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
class AppDelegate: UIResponder, UIApplicationDelegate {
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
        do {
            try Amplify.configure()
        } catch {
            print("An error occurred setting up Amplify: \(error)")
        }
        return true
    }
}

```

**Comment by lawmicha** [comment]
We can have code tabs for these three scenarios under https://docs.amplify.aws/lib/project-setup/create-application/q/platform/ios#n4-initialize-amplify-in-the-application Let us know if you have additional questions or feedback

**Comment by lawmicha** [comment]
Updated the docs with example 3. Closing this out for now, let us know if you have any questions
