### ISSUE TITLE
Nav Bar Issues on Firefox

### ISSUE THREAD

**Issue by jamesonwilliams** [aws-amplify/docs#2824]
**Describe the bug**
The left-hand navigation bar overflows the content when using Firefox. See screenshot.

**To Reproduce**
Visit the docs site in Firefox. Expand the nav bar for a long context menu, e.g., Android's Auth drop-down.

**Expected behavior**
Probably the subsequent divs should clear the menu.

**Screenshots**

<img width="1047" alt="Screen Shot 2021-01-04 at 11 06 05 AM" src="https://user-images.githubusercontent.com/899569/103560343-3d39aa80-4e7d-11eb-92e5-42e772b14723.png">

**Desktop (please complete the following information):**
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:78.0) Gecko/20100101 Firefox/78.0
```

**Comment by mauerbac** [comment]
Thanks @jamesonwilliams . @tjleing , we should take a look

**Comment by tjleing** [comment]
This should be resolved now!  @jamesonwilliams can you take a look again?
