### ISSUE TITLE
[Feedback]Subscription handler from tutorial does not receive data

### ISSUE THREAD

**Issue by peterkruty** [aws-amplify/docs#2827]
**Page**: [`/start/getting-started/data-model/q/integration/vue`](https://docs.amplify.aws/start/getting-started/data-model/q/integration/vue)

**Feedback**:

I followed the tutorial but when I used the code to subscribe, it does not work. Steps to reproduce:

1. I copy & pasted the code to App.vue
2. I created a new todo item via AppSync Queries.

`mutation MyMutation {
  createTodo(input: {name: "hm?", description: "klokoko", id: "asd"}) {
    id
  }
}`

The handler from the tutorial receives the event, but does not contain data, but 3 errors. Here is example from chrome console:

```
{provider: AWSAppSyncRealTimeProvider, value: {…}}
provider: AWSAppSyncRealTimeProvider {_config: {…}, socketStatus: 1, keepAliveTimeout: 300000, subscriptionObserverMap: Map(2), promiseArray: Array(0), …}
value:
data: {onCreateTodo: null}
errors: Array(3)
0: {message: "Cannot return null for non-nullable type: 'String' within parent 'Todo' (/onCreateTodo/name)", path: Array(2)}
1: {message: "Cannot return null for non-nullable type: 'AWSDate…e' within parent 'Todo' (/onCreateTodo/createdAt)", path: Array(2)}
2: {message: "Cannot return null for non-nullable type: 'AWSDate…e' within parent 'Todo' (/onCreateTodo/updatedAt)", path: Array(2)}
length: 3
__proto__: Array(0)
__proto__: Object
__proto__: Object
```

**Comment by sammartinez** [comment]
https://github.com/aws-amplify/docs/issues/2796

**Comment by wlee221** [comment]
Hello @peterkruty, I was unable to reproduce this with latest `@vue/cli` and Vue 3. Tested creating mutation with both AppSync and in-browser input. 

Do you still experience this error? If so, can you provide us more info by running 
```
npx envinfo --system --binaries --browsers --npmPackages --duplicates --npmGlobalPackages
```
on your project root and send back the results so that we can investigate further?
