### ISSUE TITLE
[Feedback]Dead link for "the documentation for @connection"

### ISSUE THREAD

**Issue by alexchen2231** [aws-amplify/docs#2830]
**Page**: [`/cli/graphql-transformer/key`](https://docs.amplify.aws/cli/graphql-transformer/key#combining-key-with-connection)

**Feedback**:

No link for "the documentation for @connection"

**Comment by mauerbac** [comment]
Thanks @alexchen2231. 

@aws-amplify/amplify-cli - can you update this link ?

**Comment by renebrandel** [comment]
The link should work now.
