### ISSUE TITLE
Missing steps in Angular guide

### ISSUE THREAD

**Issue by nubpro** [aws-amplify/docs#2836]
1. How did this file `../types/restaurant` gets generated? The guide did not mention about it at all.
![image](https://user-images.githubusercontent.com/762914/104035951-c3534980-520d-11eb-8c54-2f1892d66b32.png)

2. What does this do?
![image](https://user-images.githubusercontent.com/762914/104036052-e67df900-520d-11eb-90ed-8f3e5be32c14.png)

**Comment by dabit3** [comment]
Hey @nubpro, the step to add the types file should be there:

<img width="709" alt="Screen Shot 2021-02-15 at 6 59 56 PM" src="https://user-images.githubusercontent.com/1857282/108006075-11ebc480-6fc0-11eb-9ed5-3cad0d1a0807.png">

Regarding the `compilerOptions` flag, the docs with the details are located [here](https://www.typescriptlang.org/tsconfig#types)
