### ISSUE TITLE
Incorrectly documented method to retrieve model's name for DataStore events (Amplify JS)

### ISSUE THREAD

**Issue by nubpro** [aws-amplify/docs#2837]
![image](https://user-images.githubusercontent.com/762914/104036653-a1a69200-520e-11eb-94f2-69bbe1eb9eaa.png)
![image](https://user-images.githubusercontent.com/762914/104036679-ab2ffa00-520e-11eb-8579-b1c0353435a0.png)
![image](https://user-images.githubusercontent.com/762914/104036717-b71bbc00-520e-11eb-86fd-fa15418c51d7.png)

This `modelName` does not exists and is a lie.
To retrieve the model's name you need to do `model.name` from the model instance.

Related issue:
https://github.com/aws-amplify/amplify-js/issues/7219

**Comment by amhinson** [comment]
Closing, as this appears to be addressed in #2844.

**Comment by nubpro** [comment]
> Closing, as this appears to be addressed in #2844.

Hmm that pr didnt get merged as it requires changes from AmplifyJS instead of the doc.

**Comment by amhinson** [comment]
Ah sorry my mistake 👍

**Comment by nubpro** [comment]
> Ah sorry my mistake 👍

All good 😬
