### ISSUE TITLE
Incorrect environment variable (Calling GraphQL API from a Lambda function)

### ISSUE THREAD

**Issue by nubpro** [aws-amplify/docs#2840]
Original doc link: https://docs.amplify.aws/cli/function

![image](https://user-images.githubusercontent.com/762914/104086025-0bff1700-528f-11eb-80f3-be60549340f1.png)
![image](https://user-images.githubusercontent.com/762914/104086031-17ead900-528f-11eb-8685-ef11cb3a01e2.png)

Change `process.env.API_URL` to `process.env.API_<YOUR_API_NAME>_GRAPHQLAPIENDPOINTOUTPUT`.

Also I think it will be super helpful how `process.env.API_<YOUR_API_NAME>_GRAPHQLAPIKEYOUTPUT` come about. Like tell us how to generate this or what needs to enabled to get this generated.

**Comment by ssamakar** [comment]
@nubpro helped me solve this, so for others in the same situation, here is how to get `GRAPHQLAPIKEYOUTPUT` in your Lambda function's index.js file:
`amplify update api` -> `GraphQL` -> `update auth settings` -> `API key` -> optional description -> expiration date.

Then you'll need to run `amplify update function` -> Lambda function -> your function -> `Resource access permissions` -> `api` -> your API's name -> pick the actions you'd like to allow. Now you should have `GRAPHQLAPIKEYOUTPUT` available in your lambda function.

**Comment by dabit3** [comment]
Hey @nubpro, I believe it's set that way to be generic and give people the understanding that it's just their GraphQL URL, regardless of how it was set in the lambda.

I think an alternative way to get this across may be to leave a comment saying that it may look like `API_<YOUR_API_NAME>_GRAPHQLAPIENDPOINTOUTPUT`?

Thoughts?

**Comment by nubpro** [comment]
> Hey @nubpro, I believe it's set that way to be generic and give people the understanding that it's just their GraphQL URL, regardless of how it was set in the lambda.
> 
> I think an alternative way to get this across may be to leave a comment saying that it may look like `API_<YOUR_API_NAME>_GRAPHQLAPIENDPOINTOUTPUT`?
> 
> Thoughts?

It's just that the default env variable generated through Amplify-cli is `API_<YOUR_API_NAME>_GRAPHQLAPIENDPOINTOUTPUT`. I think it should be consistent with the rest.
Perhaps we can add an additional comment to indicate or to explain what it is. It's pretty clear cut to me as we are clearly passing that variable to `url`.

When people copy and paste that chunk of the code from the doc into their workspace, I believe their expectation is that it will work OOTB without any changes.

**Comment by djsjr** [comment]
There must be some sort of comment or sentence in the docs that explain that API_<YOUR_API_NAME>_GRAPHQLAPIKEYOUTPUT will only be created if API Key is set up with the api category. The [query and mutation doc](https://docs.amplify.aws/cli/function/#query) needs to specify that this is a prerequisite to using the example code.
