### ISSUE TITLE
[Feedback] Documentation update request for mock options.

### ISSUE THREAD

**Issue by pickles** [aws-amplify/docs#2841]
**Page**: [`/cli/usage/mock`](https://docs.amplify.aws/cli/usage/mock)

**Feedback**:
When mocking Lambda function, sometimes need increase timeout settings.
There are --timeout option on "amplify mock" sub-command but it seems not documented.
It can be also used when we mock GraphQL API with lambda resolver.

Please add all options of amplify mock to this document and help command.
And could you please consider that create complete reference for CLI sub commands and it's options.

https://docs.amplify.aws/cli/start/workflows#amplify-configure-project
is not completed, no mock subcommand, and some options like amplify pull --restore option is missing.

**Comment by edwardfoyle** [comment]
We've added several improvements to mocking in the latest version of the CLI and updated the docs here: https://docs.amplify.aws/cli/usage/mock#function-mocking-setup
