### ISSUE TITLE
[Feedback] amplify javascript tutorial

### ISSUE THREAD

**Issue by makrmark** [aws-amplify/docs#2842]
**Page**: [`/start/q/integration/js`](https://docs.amplify.aws/start/q/integration/js)

**Feedback**:
Many warnings reported when performing npm install. Can you update the dependencies to later versions?

**npm install**                                    
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated buffer@4.9.1: This version of 'buffer' is out-of-date. You must update to v4.9.2 or newer
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

**Comment by sammartinez** [comment]
@makrmark This is for the vanilla js intergration correct?

**Comment by sammartinez** [comment]
Thanks for reporting this @makrmark. We will do a release this week to resolve the warning called out above. Once the release is complete, you will not see the above warnings. Resolving this issue as the above statement
