### ISSUE TITLE
[Feedback]amplify-app command is not needed

### ISSUE THREAD

**Issue by onizine** [aws-amplify/docs#2843]
**Page**: [`/start/getting-started/generate-model/q/integration/ios`](https://docs.amplify.aws/start/getting-started/generate-model/q/integration/ios)

**Feedback**:
I found miss below

```
2. Next, generate the classes for these models and add them to your Xcode project. Run the command:

amplify codegen models && amplify-app
```

i think 

```
amplify codegen models 
```

not need "&& amplify-app"

**Comment by lawmicha** [comment]
hi @onizine, thanks for opening this issue, i believe this has been updated here https://github.com/aws-amplify/docs/pull/2888
