### ISSUE TITLE
[AppSync] Apollo cache table renders incorrectly

### ISSUE THREAD

**Issue by diegocstn** [aws-amplify/docs#2853]
**Describe the bug**
In the iOS docs, the Apollo cache example table renders incorrectly https://docs.amplify.aws/sdk/api/graphql/q/platform/ios#client-architecture

**Expected behavior**
Android docs: https://docs.amplify.aws/sdk/api/graphql/q/platform/android#client-architecture

**Comment by lawmicha** [comment]
See mentioned PR above
