### ISSUE TITLE
[Feedback]URL blocked when using user pool domain as redirect URI

### ISSUE THREAD

**Issue by pnewhook** [aws-amplify/docs#2854]
**Page**: [`/lib/auth/social/q/platform/js`](https://docs.amplify.aws/lib/auth/social/q/platform/js)

**Feedback**:
When using Facebook login I believe the Valid OAuth Redirect URIs should be the application URL, not User Pool URL. With `https://<your-user-pool-domain>/oauth2/idpresponse` I got the following error
![2021-01-13 10_29_54-https___www facebook com_v5 0_dialog_oauth_app_id=148470056905112 cbt=1610551791](https://user-images.githubusercontent.com/92876/104516127-d8d7c300-55c1-11eb-823d-f0439223bb2d.png)

**Comment by mauerbac** [comment]
hey @pnewhook - did you also whitelist that domain? 
![image](https://user-images.githubusercontent.com/1507886/104752336-88c54180-5724-11eb-9a88-2db13a8c954f.png)

**Comment by pnewhook** [comment]
@mauerbac Yes, on the Facebook console App Domains included the user-pool-domain as shown above. I believe the only incorrect bit of documentation is **Valid OAuth Redirect URIs** should be `https://app-domain/` instead of `https://<your-user-pool-domain>/oauth2/idpresponse`

It's my understanding that `https://<your-user-pool-domain>/` should like `https://<cognito-user-pool-id>.auth.<region>.amazoncognito.com` whereas `https://app-domain/` is more like `https://<environment>.<amplify-app-id>.amplifyapp.com/`

**Comment by pnewhook** [comment]
I've created another test app, and I've found my issue. I was using `withAuthenticator` instead of the hosted UI. When you use the Hosted UI, `https://<your-user-pool-domain>/oauth2/idpresponse` is the correct redirect URI. I think some documentation around using `withAuthenticator` with social logins would be helpful, but that's a separate feature request.
