### ISSUE TITLE
[Feedback]Amplify CLI

### ISSUE THREAD

**Issue by Dicondur** [aws-amplify/docs#2858]
**Page**: [`/cli`](https://docs.amplify.aws/cli)
https://docs.amplify.aws/cli/start/install#option-2-follow-the-instructions

**Feedback**:

With regards to setting up Amplify CLI, this requires that we create IAM admin user.
How would a Feradated user connected to Active Directory or other wise and will be assuming a Role be given acess to Amplify CLI

**Comment by siegerts** [comment]
Hi @Dicondur, apologies for the delay in follow up here. Are you able to provide more details on the context and process of what you're trying to do here? Are there specific tools that you're already using, etc?

**Comment by Dicondur** [comment]
Hi thanks for getting back, with `amplify init` earlier needed IAM credentials to be passed.
Now support for profile has been added, and I tried it.
This saves me some time working around with it.
Thanks anyways 👍
