### ISSUE TITLE
 i.util.crypto.lib.randomBytes is not a function

### ISSUE THREAD

**Issue by idkjs** [aws-amplify/docs#286]
**Describe the bug**
In the [react add api](https://aws-amplify.github.io/docs/js/react#add-graphql-backend) section, when you go to confirm in the AppSync Console you have to log in.
Logging returns this error ".util.crypto.lib.randomBytes is not a function"

**Expected behavior**
Expected that you log in successfully

**Screenshots**
<img width="619" alt="screen shot 2018-12-07 at 10 03 42 am" src="https://user-images.githubusercontent.com/2370391/49638103-805b9200-fa07-11e8-812d-756ab7e1d6a0.png">

- client id from Cognito
<img width="943" alt="screen shot 2018-12-07 at 10 05 01 am" src="https://user-images.githubusercontent.com/2370391/49638158-abde7c80-fa07-11e8-9247-4148821f67af.png">

**Desktop (please complete the following information):**
```s
PrisBook:~$ macnodeyarnv
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G3025
yarn version: 1.10.1
node version: v9.10.1
```

**Comment by Jobel91** [comment]
Same here.
I need to test queries, but unable to login...

**Comment by itrestian** [comment]
Sorry for the issue. This should be fixed now. Can you guys give it another try?

**Comment by Jobel91** [comment]
Solved, thanks. It works now.

**Comment by nikhil-dabhade** [comment]
@Jobel91 Thank you for confirming. 
@idkjs If this is also fixed for you, can you mark the issue closed ?

**Comment by Jobel91** [comment]
resolve

**Comment by nikhil-dabhade** [comment]
Thank you @idkjs !
