### ISSUE TITLE
Links from docs.amplify.aws for iOS SDK don't resolve. 

### ISSUE THREAD

**Issue by mohitb117** [aws-amplify/docs#2860]
**Describe the bug**
Certain Links for docs dont resolve.

**To Reproduce**
1. Go to https://docs.amplify.aws/sdk/analytics/kinesis/q/platform/ios#working-with-the-api

2. Click on 'To learn more about the Amazon Kinesis classes, see the **class reference for AWSKinesisRecorder**.'

Unresolved Links:
https://aws-amplify.github.io/aws-sdk-ios/docs/reference/Classes/AWSKinesisRecorder.html

Correct Links (via Google Indexing):
https://aws-amplify.github.io/aws-sdk-ios/docs/reference/AWSKinesis/Classes/AWSKinesisRecorder.html

**Expected behavior**
The links should resolve to the correct documentations.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: ANY
 - Browser ANY
 - Version ANY

**Additional context**

**Comment by mauerbac** [comment]
thanks @mohitb117 -- I have verified this. @drochetti , can you look into this?

**Comment by lawmicha** [comment]
PR has been merged!
