### ISSUE TITLE
[Feedback]Analytics Documentation - Suggested update

### ISSUE THREAD

**Issue by Pioank** [aws-amplify/docs#2866]
**Page**: [`/lib/analytics/getting-started/q/platform/js`](https://docs.amplify.aws/lib/analytics/getting-started/q/platform/js)

**Feedback**:

After experimenting with Amplify JS SDK and Pinpoint, I have encountered 2 issues that could have been avoided if they were explicitly mentioned in the documentation:

1. There is no mention that there is a limit of 10 endpoints per user in the Amplify Analytics section and that developers / testers should be aware of that as well as a way to avoid it

2. There is no mention that the default value of optOut is "ALL" and that results to endpoints not being eligible for Pinpoint Campaigns and Journeys. Furthermore it would be good to explain why this the default value and that one can change it by using updateEndpoint

Thank you

**Comment by nickarocho** [comment]
Hi @Pioank thank you for your feedback.

I've added a callout for the quota set by Pinpoint for the max endpoints per user ID (it's 15 now), along with a link to their endpoint [quota documentation](https://docs.aws.amazon.com/pinpoint/latest/developerguide/quotas.html#quotas-endpoint).

I've also added a `(default)` label next to the `optOut: 'ALL'` option in the "Setting up an existing analytics backend" code snippet (which, though not super obvious, does contains a `// OPTIONAL - Default Endpoint Information` comment).

Thanks again!
