### ISSUE TITLE
404 Error "see Real-time data" link

### ISSUE THREAD

**Issue by Jobel91** [aws-amplify/docs#287]
**Describe the bug**
I'm getting a 404 error with this link : https://aws-amplify.github.io/docs/js/aws-appsync-real-time-data

Location : 

AWS Amplify Docs -> API Guides -> API -> Using GraphQL Endpoints -> AWS AppSync SDK -> Subscribe to Data (end of section)

**Comment by nikhil-dabhade** [comment]
@Jobel91 : Thank you for pointing this out. I can confirm that this link is not being directed correctly. Apologies for the inconvenience here. I will update you on the status of this issue by end of this week.
Meanwhile, here is the missing link: https://docs.aws.amazon.com/appsync/latest/devguide/real-time-data.html

**Comment by Jobel91** [comment]
Thanks

**Comment by jordanranz** [comment]
I have added a PR for this fix.
