### ISSUE TITLE
[Feedback] Usage of parameters.json

### ISSUE THREAD

**Issue by michalpochwala** [aws-amplify/docs#2870]
**Page**: [`/cli/usage/customcf`](https://docs.amplify.aws/cli/usage/customcf)

**Feedback**:

I find it confusing when I should define my cloud formation parameters in parameters.json file. Empirically the parameters.json file is not required. All I have to do is to define new cloud formation parameters using provided convention and set up backend-config properly. 

eg. 

backend-config.json

`  "stepFunction": {
    "multiVariantWorkflow": {
      "service": "Step Function",
      "providerPlugin": "awscloudformation",
      "dependsOn": [
        {
          "category": "function",
          "resourceName": "qualifyVariantItemsForValidation",
          "attributes": [
            "Arn"
          ]
        },`

multiVariantWorkflow-..cloudformation.json

`---
AWSTemplateFormatVersion: '2010-09-09'
Description: Multi variant workflow Step Function
Parameters:
  env:
    Type: String
  functionqualifyVariantItemsForValidationArn:
    Type: String
    Default: function qualifyVariantItemsForValidation arn`

Based on above adding cross category item to parameters.json seems to be unnecessary boilerplate. Could you add a bit more info what is the intention of adding upstream resources outputs to the the file?

**Comment by Straubulous** [comment]
Now that we have extensibility, the approach has evolved. We have updated documentation here:
https://docs.amplify.aws/cli/reference/files/#parametersjson
https://docs.amplify.aws/cli/custom/cdk/

Closing this issue - @michalpochwala  - please reopen with additional details if you think there is still something needed.
