### ISSUE TITLE
[Feedback] Missing mobile documentation on Shadow APIs

### ISSUE THREAD

**Issue by elprl** [aws-amplify/docs#2871]
Not sure why PubSub documentation can't be called IoT or IoT Core.
Missing API documentation for Classic Shadow interactions.
Can't use Shadow API with Named Shadows.

**Comment by elprl** [comment]
Why is the PubSub menu missing? You can see it here https://docs.amplify.aws/sdk/pubsub/working-api/q/platform/ios
but when you hit the Libraries menu tab, it disappears.

**Comment by raphkim** [comment]
Hi @elprl, Amplify Native libraries (Android/iOS) currently do not support PubSub category. Meanwhile, you will be able to continue to use the low-level SDKs provided by either platform for your IoT needs.
