### ISSUE TITLE
[DOCS] Sort by Date Data Access Example

### ISSUE THREAD

**Issue by amcdnl** [aws-amplify/docs#2883]
## Request
The current documentation on https://docs.amplify.aws/cli/graphql-transformer/dataaccess shows a variety of different access patterns, however, a very common one might just to be sort by created date descending. It would be beneficial to spell out that pattern ( or if not support ) then mention that at minimal.

It looks like in another spot of the docs you suggest adding a 'placeholder' like field to give it something to hash on -  https://docs.amplify.aws/guides/api-graphql/query-with-sorting/q/platform/js#implementation - maybe worth mentioning this here?

## References
- https://github.com/aws-amplify/amplify-cli/issues/2307
- https://stackoverflow.com/questions/57954689/graphql-with-aws-amplify-how-to-enable-sorting-on-query
- https://github.com/aws-amplify/amplify-cli/issues/4261
- https://medium.com/@mrsze/sorting-data-in-awsamplify-and-dynamodb-with-key-directive-6f04f0cd427f

**Comment by dabit3** [comment]
Hey, have a look at this guide and let me know if this is what you're looking for: https://docs.amplify.aws/guides/api-graphql/query-with-sorting/q/platform/js#overview

**Comment by amcdnl** [comment]
Yes, however, its not obvious. It should really spell it out "sorting by date requires you to create a new index, we need to add a placeholder field....etc'

**Comment by medelman17** [comment]
Closed by #2883
