### ISSUE TITLE
Upgrade instructions aren't married back to the new cURL approach

### ISSUE THREAD

**Issue by drochetti** [aws-amplify/docs#2892]
Not for this PR, but on a somewhat related note:

Our upgrade instructions aren't married back to the new cURL approach. They only talk about updating via `npm`.

https://docs.amplify.aws/cli/usage/upgrade

_Originally posted by @jamesonwilliams in https://github.com/aws-amplify/docs/issues/2889#issuecomment-768551643_

**Comment by dabit3** [comment]
Hey @drochetti , do you think that just adding the instructions for the additional installation options is enough to make this work as expected?
