### ISSUE TITLE
[Feedback]Data Model Importing

### ISSUE THREAD

**Issue by nickzitzer** [aws-amplify/docs#2893]
**Page**: [`/console/data/data-model`](https://docs.amplify.aws/console/data/data-model)

**Feedback**:

It would be awesome if there was a mechanism to import data models, either from standard DB schema exports or from excel, csv, XML, JSON. It is very slow to make large DB schemas or to migrate from a legacy database.

**Comment by dabit3** [comment]
Hey, this sounds like a feature request for the Admin UI. Do you mind opening an issue there with these, and maybe a few more details (like a proposed flow or DX)?

**Comment by nickzitzer** [comment]
Apologies, I have moved this over to there:
https://github.com/aws-amplify/amplify-adminui/issues/120
