### ISSUE TITLE
onAuthUIStateChange() not working as expected after page navigation when already logged in

### ISSUE THREAD

**Issue by tonykaram1993** [aws-amplify/docs#2895]
**Describe the bug**
Authentication is not working as expected. On first visit, all works fine. When navigating away to other pages and then back, a black page appears and user is considered as not authenticated.

**To Reproduce**
1. Clone the following repo: https://github.com/tonykaram1993/amplify-auth-bug
2. `yarn` or `npm install`
3. `yarn start` or `npm run start`
4. Open `localhost:3000`
5. Click on `Test`
6. SignIn
7. Click `Back` on your browser
8. Click `Forward` on your browser
9. Page is now black

**Expected behavior**
Page should load, auth state should refresh and page should show `Hello` and the signOut Button.

**Code Snippet**
https://github.com/tonykaram1993/amplify-auth-bug

**What is Configured?**
`aws-exports` file:
   ```
   const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:421237b2-811e-4692-a0fd-1b60bceee1c3",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_N98Y1zw3v",
    "aws_user_pools_web_client_id": "388mnkrc9p04bq06s7q1it06t2",
    "oauth": {},
   };
   ```

**Comment by matthewberryman** [comment]
I have been encountering this in Safari (desktop). The solution in https://github.com/aws-amplify/docs/issues/2895#issuecomment-699132676 worked although I had to change the last line to include authState in the dependency array otherwise modern versions of React correctly give the warning
`React Hook React.useEffect has a missing dependency: 'authState'. Either include it or remove the dependency array  react-hooks/exhaustive-deps`

Modified code to include it:
```typescript
  React.useEffect(() => {

    if (authState === undefined) {
      Auth.currentAuthenticatedUser().then(authData => {
        setAuthState(AuthState.SignedIn);
        setUser(authData);
      });
    }

    return onAuthUIStateChange((nextAuthState, authData) => {
      setAuthState(nextAuthState);
      setUser(authData);
      console.log('auth state changing');
    });
  }, [authState]);
```

**Comment by Path-A** [comment]
Currently having the same problem, but with Ionic-Vue.

**Comment by mauerbac** [comment]
Going to close this out due to issue age. If you are still encountering issues, please open a new issue and I will address it. Please tag me. Thank you
