### ISSUE TITLE
Bad link to "Cloud API" in REST PUT docs

### ISSUE THREAD

**Issue by mrcoles** [aws-amplify/docs#290]
**Describe the bug**

In the docs for [API > REST > PUT](https://aws-amplify.github.io/docs/js/api#put):

> #### PUT
>
> When used together with [Cloud API](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/web-access-apis.html), PUT method can be used to create or update records. It updates the record if a matching record is found. Otherwise, a new record is created.

The Cloud API link is bad: https://docs.aws.amazon.com/aws-mobile/latest/developerguide/web-access-apis.html

It just redirects back to the main docs page.

**To Reproduce**

1. Go to [API > REST > PUT](https://aws-amplify.github.io/docs/js/api#put)
2. Click on [Cloud API](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/web-access-apis.html)
3. See page it leaves you on

**Expected behavior**

I would expect this to go to a meaningful page that explains what the "Cloud API" is.

**Additional context**

Separately it’d be great to see more examples (maybe tutorials) for setting up both AppSync and Rest integrations that goes into the backend part of the implementation.

**Comment by nikhil-dabhade** [comment]
@mrcoles Thank you for pointing this out. I can confirm that this link is not being directed to the correct place. Will share the expected link today. Apologies for the inconvenience. 

For tutorials, here is a list of tutorials that may be useful : https://docs.aws.amazon.com/appsync/latest/devguide/tutorials.html 

Let me know if these are not helpful.
