### ISSUE TITLE
[Feedback]SSR documentation is misnamed

### ISSUE THREAD

**Issue by HoraceShmorace** [aws-amplify/docs#2905]
**Page**: [`/lib/ssr/q/platform/js`](https://docs.amplify.aws/lib/ssr/q/platform/js)

**Feedback**:

This literally has nothing to do with server-side rendering, but rather server-side implementation (effectively, to create a service to fetch data, not to render UI), with really no mention as to how you'd reconcile this with your client-side implementation without having two separate codebases for each.

**Comment by mauerbac** [comment]
Thanks @HoraceShmorace . Thoughts @ericclemmons ?

**Comment by medelman17** [comment]
Closing as stale; feel free to ping me here or on twitter if this issue arises again.
