### ISSUE TITLE
Framework switcher regression

### ISSUE THREAD

**Issue by mauerbac** [aws-amplify/docs#2907]
**Describe the bug**
While on a page and switching framework, the switcher brings you back to the getting started guide not the same page.

**To Reproduce**
1. Go to https://docs.amplify.aws/start/getting-started/setup/q/integration/angular
2. Click on Ionic

**Expected behavior**
You are brought to the incorrect page.

**Comment by tjleing** [comment]
I've seen it as well, wasn't sure if it was a regression or always there... will look into after writing this Adobe Analytics doc

**Comment by tjleing** [comment]
Worth mentioning that that repro you posted is working fine for me right now, but I have definitely seen the issue before -- this might be pretty difficult to track down.

**Comment by swaminator** [comment]
@tjleing what's the status with this? It's very easily reproducible.

**Comment by tjleing** [comment]
Ah, I just figured out why I wasn't able to reproduce the problem -- there's an important step before the ones listed in the repro.

Correct repro:
1. Go to https://docs.amplify.aws/start/getting-started/setup/q/integration/angular
2. Click on "Connect API and database to the app"
3. Switch to JS
4. The page _should_ be https://docs.amplify.aws/start/getting-started/data-model/q/integration/js, but instead it's https://docs.amplify.aws/start/getting-started/setup/q/integration/js.

I'd been checking on the exact repro Matt mentioned every few days and seeing everything working fine... no wonder!  Now that I have the repro, tracking this down should be much easier.

**Comment by tjleing** [comment]
and when I say "much easier," I guess I mean "solvable in 20 minutes."  Looking to merge in tomorrow after review.

**Comment by tjleing** [comment]
Merged earlier today -- going to close this tomorrow unless anyone sees any unresolved issues with this.
