### ISSUE TITLE
[Feedback]the angular code doesn't compile

### ISSUE THREAD

**Issue by jmagaram** [aws-amplify/docs#2918]
**Page**: [`/lib/datastore/examples/q/platform/js`](https://docs.amplify.aws/lib/datastore/examples/q/platform/js)

**Feedback**: the onQuery method is missing, "subscription" declaration generates error when no data type is provided (using TypeScript/Angular strict mode)

Come on guys, give a little love to Angular!

**Comment by wlee221** [comment]
Hello @jmagaram, apologies on the late response. The subscription typing should be fixed from #3606. Specifically, we now are importing `Restaurant` type directly from `"./API.service"`, which you can use to strictly type API functions. Please let us know if you see the same issue with the latest snippets. 

And +1 on giving some love to Angular! There are a lot of Angular gaps we have seen with current UI components, and we'll work our best to bridge that gap in our new [Angular UI components](https://ui.docs.amplify.aws/ui/components/authenticator) that we're developing now 🎉
