### ISSUE TITLE
[Feedback]FEEDBACK_TITLE_HERE

### ISSUE THREAD

**Issue by jhachtel** [aws-amplify/docs#2919]
**Page**: [`/ui/auth/authenticator/q/framework/angular`](https://docs.amplify.aws/ui/auth/authenticator/q/framework/angular)

**Feedback**:
You have two different versions of the app.component.html file in the Recommended Usage section. Which is correct? Also, you have two identical app.module.ts files there. You can delete one of them.

**Comment by dabit3** [comment]
Thanks for the issue, an update has been pushed and is waiting to merge!
