### ISSUE TITLE
iOS - Add information regarding preferPrivateSession for signInWithWebUI

### ISSUE THREAD

**Issue by royjit** [aws-amplify/docs#2922]
Amplify 1.6.0 released new support for ASWebAUthenticationSession and preferPrivateSession - https://github.com/aws-amplify/amplify-ios/releases/tag/v1.6.0. We need to add this into the documentation.

**Comment by royjit** [comment]
PR - https://github.com/aws-amplify/docs/pull/2923

**Comment by palpatim** [comment]
#2923 merged, closing
