### ISSUE TITLE
[Feedback] What happens when you try to use amplify mock function?

### ISSUE THREAD

**Issue by WilliamCadenas21** [aws-amplify/docs#2926]
**Page**: [`/guides/functions/integrating-dynamodb-with-lambda/q/platform/ios`](https://docs.amplify.aws/guides/functions/integrating-dynamodb-with-lambda/q/platform/ios)

**Feedback**:

What happens when you try to use amplify mock function?  the permissions works well in the cloud but not in local

**Comment by palpatim** [comment]
@WilliamCadenas21 is this a question about documentation (e.g., you want an explanation in docs about what happens behind the scenes) or are you encountering an error that you want to report as a bug (e.g., you want to file a bug on the CLI repo)?

**Comment by WilliamCadenas21** [comment]
Actually I found why the function didn't work, it was the event.js, thanks for the response
