### ISSUE TITLE
Docs for using onAuthUIStateChange() in useEffect() hook incorrect

### ISSUE THREAD

**Issue by mpvosseller** [aws-amplify/docs#2928]
1) In the [Recommended usage section](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#recommended-usage) of the React Authenticator documentation it says:
> Make sure not to return the result of `onAuthUIStateChange` within the `useEffect` hook.

2) Also the code snippet does not return the return value of `onAuthUIStateChange()`

My understanding is that we _should_ be returning the value of `onAuthUIStateChange()` in the `useEffect` hook so that the listener will be removed when the component unmounts. 

Seems like we should remove the word "not" from the note and add a "return" statement to the code? Apologies if I am misunderstanding something.

<img width="768" alt="Screen Shot 2021-02-09 at 10 48 05 PM" src="https://user-images.githubusercontent.com/566863/107463809-ea62ab00-6b2c-11eb-8875-607e6be02e24.png">

**Comment by dabit3** [comment]
cc @wlee221 Any context on this? I think this was added a few months ago in this pr:

https://github.com/aws-amplify/docs/commit/a16f77e19338d4bf51e9ff480d189dfa17cadc25#diff-c6210880660caf94ef044aa7a8dc6cf9b8172840f6790a4d43c19e654491db91

**Comment by wlee221** [comment]
Hi @mpvosseller! You are right, and the value of `onAuthUIStateChange()` should be returned. I have a PR for reverting that fix:  https://github.com/aws-amplify/docs/pull/2896. @dabit3, can you review this?

**Comment by dabit3** [comment]
@wlee221 done! Thank you :)

**Comment by mpvosseller** [comment]
Thanks for the quick fix @wlee221
