### ISSUE TITLE
[missing-page] Amplify javascript push notifications

### ISSUE THREAD

**Issue by tdwebb** [aws-amplify/docs#2934]
**Page**: [`https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/js`](https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/js)

**Feedback**:

**Comment by palpatim** [comment]
@tdwebb I'm not clear what you're reporting here? The page you link to details instructions for React native on Android & iOS, which is [the only currently supported platform](https://docs.amplify.aws/lib/push-notifications/overview/q/platform/js). If you're reporting a problem on these documentation pages, could you add more detail?

**Comment by medelman17** [comment]
Closing this issue as stale. @tdwebb, to the extent you can provide more detail, we can reopen.

**Comment by tdwebb** [comment]
When I click on the link above, it goes to a 404 page, not to any documentation page.
