### ISSUE TITLE
[Feedback]Stuck at connecting the API

### ISSUE THREAD

**Issue by paullmullen** [aws-amplify/docs#2950]
**Page**: [`/start/getting-started/data-model/q/integration/js`](https://docs.amplify.aws/start/getting-started/data-model/q/integration/js#connect-frontend-to-api)

**Feedback**:

Thanks for what appears to be a great tutorial.

I'm stuck at the point after the insertion of code into the app.js file and as we run **npm start** the second time.

I keep getting errors for importing two files:
  ./graphql/mutations
  ./aws-exports

Neither file seems to have been created by the scripts on the tutorial.

Thoughts?

Paul Mullen

**Comment by dabit3** [comment]
Did `amplify push` work for you after adding the API?

Do you mind looking around to see if the files have been created in another folder in your app?

**Comment by medelman17** [comment]
Closing as stale; feel free to ping me here or on twitter if this arises again.
