### ISSUE TITLE
Trouble shooting to introduce common errors and their solutions

### ISSUE THREAD

**Issue by watilde** [aws-amplify/docs#2959]
**Is your feature request related to a problem? Please describe.**

User story: as a developer, I want to easily find a solution to the common errors so that I can save time to search on GitHub issues.

**Describe the solution you'd like**

Taking npm's trouble shooting as an example, we might can list common errors developers face and put answers to them.
https://docs.npmjs.com/common-errors

The first candidates in my mind are the below questions:

+ aws-exports.js is not generated: https://github.com/aws-amplify/amplify-cli/issues/186
+ Migrate project to another AWS Account: https://github.com/aws-amplify/amplify-cli/issues/3350

I'd appreciate if I can hear more advices from the community on the general impression of this proposal and what candidates we should put into the list.

**Describe alternatives you've considered**

Considering to have error-log format like `npm-debug.log` to share that will help developers to search and investigate the issues.

**Additional context**

I've heard from some developers that stack trace was used by users as a search resource sometimes and having a trouble shooting page would be helpful to leverage.

**Comment by watilde** [comment]
Let me cc @yuth and @dabit3 who may know what frequent questions we should add to the first candidates.

**Comment by yuth** [comment]
We could add GraphQL API Key expiration error

**Comment by yuth** [comment]
@aspittel Do you have additional common error suggestions?

**Comment by medelman17** [comment]
I'm 💯 on board as a general matter. Do we have any telemetry on this to inform where to invest initially?

**Comment by watilde** [comment]
@medelman17 Thank you for your comment! What I did to investigate last time was to search issues with filters `questions` and sorted by the number of comments on cli and js repositories, and then did some spelunking. Hope it helps :)
