### ISSUE TITLE
Pinpoint configuration mobiletargeting:PutEvents action does not exist

### ISSUE THREAD

**Issue by izieg-lo3** [aws-amplify/docs#296]
I am following this guide: [https://aws-amplify.github.io/docs/js/analytics](https://aws-amplify.github.io/docs/js/analytics)

When creating the policy specified in this guide: 
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "mobiletargeting:UpdateEndpoint",
                "mobiletargeting:PutEvents"
            ],
            "Resource": [
                "arn:aws:mobiletargeting:*:${accountID}:apps/${appId}*"
            ]
        }
    ]
}
```

Using the IAM Management Console in AWS to create this policy, it reports that the `mobiletargeting:PutEvents` action does not exist.

What action are we supposed to use here?

**Comment by JeshurunRoach** [comment]
I've been struggling with the same issue, but it turns out that if you ignore the warning in the console it works fine. Just make sure the policy successfully gets added to the role that you have attached to your identity pool.

**Comment by sshilko** [comment]
@izieg-lo3 i was able to set the policy in AWS exactly as described in PinPoint project settings setup section, including "mobiletargeting:PutEvents". 
Previously we created PinPoint project in end of September 2018 and this particular action was NOT included in policy.

My speculation is AWS changed something in SDK, as with latest SDK we saw problems w/o this "mobiletargeting:PutEvents" permissions.

Anyway AWS IAM editor works fine with "mobiletargeting:PutEvents" and accepts it, as per PinPoint project setup.

**Comment by schellack** [comment]
This issue appears to still occur. Here's a screenshot of the error in the IAM Policy editor:
![image](https://user-images.githubusercontent.com/70819/52391708-42f59e00-2a64-11e9-9970-3b8b13cc6e97.png)

**Comment by roborourke** [comment]
Same problem here. It's strange because events are properly recorded via `Analytics.autoTrack()` but not when using `Analytics.record()`. It's a total blocker to evaluating and implementing anything with this right now.

**Comment by sshilko** [comment]
Just posting as noone posted yet, using this as per project configuration page

https://console.aws.amazon.com/pinpoint/home/?region=us-east-1#/apps/YOURPROJECTID/settings/push

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "mobiletargeting:PutEvents"
      ],
      "Resource": [
          "arn:aws:mobiletargeting:us-east-1:123123123123:apps/YOURPROJECTID"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
          "mobiletargeting:UpdateEndpoint"
      ],
      "Resource": [
          "arn:aws:mobiletargeting:us-east-1:123123123123:apps/YOURPROJECTID"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
          "mobileanalytics:PutEvents"
      ],
      "Resource": [
          "*"
      ]
    }
  ]
}
```

**Comment by roborourke** [comment]
Anyone else seeing this issue - for me it helped to turn on debug mode, the error message with regards to the IAM role is a red herring.

I set a breakpoint and stepped back through the call stack, in my case it turned out I had some custom attributes being recorded that were not of type "string". It'd be good if some type detection could be inferred but for now you have to force all attributes to be strings.

**Comment by quintensis** [comment]
Try using the Logging DEBUG option with. It culd show you the reason why. 

import Amplify, { ConsoleLogger as Logger} from '@aws-amplify/core';
Amplify.Logger.LOG_LEVEL = 'DEBUG';

**Comment by quintensis** [comment]
We also had the IAM role issue. It turned out that the Cognito identity pool did not allow "Unauthenticated identities". After checking "Enable access to unauthenticated identities" in the identity pool, the issue was fixed.

**Comment by jordanranz** [comment]
@izieg-lo3 or anyone on this thread, are you guys still have issue with the documentation here/what should be changed?

**Comment by sshilko** [comment]
No issue anymore, not using Pinpoint anymore 👍

**Comment by kaushikbhanu** [comment]
this is sad

**Comment by kaushikbhanu** [comment]
"No issue anymore, not using Pinpoint anymore " this is acceptable ?
