### ISSUE TITLE
Amplify Console Documentation Doesn't Actually Ever Link to The Console Itself!

### ISSUE THREAD

**Issue by huperniketes** [aws-amplify/docs#2963]
**Page**: [`/console`](https://docs.amplify.aws/console)

**Feedback**:

Is there a link in the document subdomain that actually gets to the Amplify services? Anywhere???

**Comment by mauerbac** [comment]
Hello - Im not following. Are you able to explain in more detail ?

**Comment by huperniketes** [comment]
As far as I could tell, there is no link on that (or other) page in the
docs section which directed the browser back to the Amplify Console. Is
there one? Because it sure would be nice if there were.

**Comment by jamesonwilliams** [comment]
@huperniketes Let me see if I understand what you're saying. I think this is actually a common issue I have when I read documentation, myself.

When you visit documentation about the Foo Website, that documentation better have a big fat link at the top like:

## [Click Here To Actually User The Foo Website](http://foo.website)

Is that right?

The Amplify Console is here: https://console.aws.amazon.com/amplify/home

I agree there should be a big link on that page.

**Comment by huperniketes** [comment]
> @huperniketes Let me see if I understand what you're saying. I think this is actually a common issue I have when I read documentation, myself.
> 
> Our documentation talks about how to use the Amplify Console. But it's missing a big, obvious link at the top like:
> 
> ## [Click Here To Actually _Use_ The Amplify Console, Not Just Read About It](https://docs.amplify.aws/console)
> Is that right?
> 
> The Amplify Console is here: https://console.aws.amazon.com/amplify/home
> 
> I agree there should be a big link on this page: https://docs.amplify.aws/console.

Yep.

**Comment by medelman17** [comment]
Makes sense to me. @huperniketes, can you open a PR with the change you would like to see, and we can go from there?

**Comment by medelman17** [comment]
@mauerbac & @tjleing -- let's see if we can move this forward. Please see attached PR.

**Comment by medelman17** [comment]
Bumped to @mauerbac & @tjleing internally--let us know if this is a 'won't fix' or whether we can move forward with this PR.

**Comment by mauerbac** [comment]
brilliant , approved
