### ISSUE TITLE
More Pre-requisite Documentation

### ISSUE THREAD

**Issue by SarahDudley** [aws-amplify/docs#298]
As I followed the CLI instructions for aws-amplify I kept getting authentication errors in relation to my aws user account. I had to create a couple policies on AWS IAM in order to have permission for CloudFormation and GraphQLApi.

I think it would be helpful to have a description of all the permissions necessary beforehand. It would be helpful in avoiding these authentication issues.

**Comment by nikhil-dabhade** [comment]
@SarahDudley Thank you for pointing this out. This is useful feedback.
Can you share what policies did you have to add that were missing in the documentation?
Sorry for the inconvenience.

**Comment by SarahDudley** [comment]
In order to complete the "amplify init" command I need a few permissions. I created a policy that included the following permissions:

cloudformation:CreateStack
cloudformation:DescribeStacks
cloudformation:DescribeStackEvents
iam:GetRole
s3:CreateBucket

**Comment by kaustavghosh06** [comment]
@SarahDudley According to our docs, if you go ahead and use the `amplify configure` command to create a new IAM user (with admin privelages), and a corresponding AWS profile in your local system, then you shouldn't be seeing permission issues like the one above. Please take  alook at this - https://aws-amplify.github.io/docs/cli/init#amplify-configure for more information.
