### ISSUE TITLE
Migrate Use of “Master” to “Main” in Docs re: GitHub

### ISSUE THREAD

**Issue by medelman17** [aws-amplify/docs#2985]
**Is your feature request related to a problem? Please describe.**
Since October 2020, all new GitHub repositories are named 'main' instead of 'master'. 

**Describe the solution you'd like**
As a user, I would like the amplify documentation to consistently conform to the new GitHub standard vis-a-vis 'main' vs 'master' in any/all code examples.

See also #2979

**Comment by tjleing** [comment]
Also in this repository itself, probably.

**Comment by kakabisht** [comment]
Could I take this up?

**Comment by oieduardorabelo** [comment]
hey folks 👋

I created a fork renaming `master`  to  `main` in all files (e.g. including github actions etc)

we can compare it here:
https://github.com/aws-amplify/docs/compare/master...oieduardorabelo:main?expand=1

we would need a `docs/main` branch `master`, so I could point my `oieduardorabelo/main` to `docs/main`, at the moment is pointing to `docs/master`

**Comment by medelman17** [comment]
@tjleing -- we're wondering: do you have any insight/input re: whether this would louse up CI/CD bits etc?

**Comment by tjleing** [comment]
@medelman17 AFAIK the only thing this would mess up is the Amplify Console deployment -- both Prod and Staging are connected to the `master` branch.  Unfortunately I don't think we can just swap the branch; we probably have to create a brand new deployment, set it up exactly the same, and then hot-swap them.  It worries me a little with respect to logs and metrics.

**Comment by medelman17** [comment]
Ok. Who do we need to call to move this forward?

**Comment by tjleing** [comment]
Done!
