### ISSUE TITLE
POSTING INTO WSL 20.14 [Feedback]FEEDBACK_TITLE_HERE

### ISSUE THREAD

**Issue by qmutz** [aws-amplify/docs#2986]
**Page**: [`/console/adminui/extend-cli`](https://docs.amplify.aws/console/adminui/extend-cli)

**Feedback**:

UBUNTU 20.04 + installed into WSL 2 with no problem the content manifest was pulled from the URL - COMPUTE USER RESOURCE LOGIC  - in  cmd the CLI intalled  just fine in CMD system 32 ...

**Comment by medelman17** [comment]
@qmutz, can you clarify the above and add additional context? Thanks!
