### ISSUE TITLE
Searching for "DataStore events" yields no result

### ISSUE THREAD

**Issue by nubpro** [aws-amplify/docs#2991]
![image](https://user-images.githubusercontent.com/762914/109250543-d5706200-7824-11eb-89cb-a4fc05dae83e.png)

Expected result:
https://docs.amplify.aws/lib/datastore/datastore-events/q/platform/js#observe-data-in-real-time

**Comment by medelman17** [comment]
Closing this as duplicative of #2993

**Comment by nubpro** [comment]
@medelman17 Isnt this a different issue altogether?
This is "datastore events" text is not indexed, another is search result rankings

**Comment by nubpro** [comment]
Searching for "feature flags" yields no result as well. Can you reopen this? @medelman17

**Comment by medelman17** [comment]
@nubpro, all of the above (including the other issue I mentioned) seem to relate to indexing issues with our search provider? Do you see it differently? I'm not sure I follow.

**Comment by nubpro** [comment]
> @nubpro, all of the above (including the other issue I mentioned) seem to relate to indexing issues with our search provider? Do you see it differently? I'm not sure I follow.

I feel like #2993 requires some changes to the client as the client need to inform the search provider which platform the user is on.

Whereas for this issue, Algolia probably havent index all the pages in the docs(?)
