### ISSUE TITLE
Rank search results based on platform chosen

### ISSUE THREAD

**Issue by nubpro** [aws-amplify/docs#2993]
**Is your feature request related to a problem? Please describe.**
Whenever I use the search feature, it does not always return me relevant results. Say I'm viewing the Javascript docs and I search for "datastore", the first search results is always the docs from iOS. This can be confusing at times.

![image](https://user-images.githubusercontent.com/762914/109252466-917f5c00-7828-11eb-92f2-e2d37735b418.png)

**Describe the solution you'd like**
If I'm viewing Javascript docs, return me the docs from Javascript first.

**Comment by medelman17** [comment]
@nubpro -- this is very, very much on our radar. I'm going to close because, unfortunately, it's not actionable in the immediate. Happy to discuss rationale offline if you would like. Hit me up on Twitter.
