### ISSUE TITLE
Additional guides to use TypeScript at functions for a TypeScript beginner 

### ISSUE THREAD

**Issue by mats16** [aws-amplify/docs#2996]
**Is your feature request related to a problem? Please describe.**

To use TypeScript at function, this guides is very helpful.
https://docs.amplify.aws/cli/function/build-options

But I think some information are lack to use TypeScript.

As a TypeScript beginner, I want to know where I should place package.json and node_modules within Amplify project during Amplify Tutorial so that I don't need to back and forth among their guides.

**Describe the solution you'd like**

I think it is better to mention node_modules and package.jsom on docs.

for example ..

```json: tsconfig.json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "lib": ["dom", "esnext"],
    "module": "commonjs",
    "moduleResolution": "node",
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "outDir": "./src",
    "baseUrl": "./",
    "rootDir": "./lib",
    "paths": {
      "src": ["./lib"],
      "*": [
        "./src/node_modules/@types/*",
        "./src/node_modules/*"
      ]
    }
  }
}
```

```bash
$ tree
.
├── Function-cloudformation-template.json
├── amplify.state
├── dist
│   └── latest-build.zip
├── function-parameters.json
├── lib
│   └── index.ts
├── parameters.json
├── src
│   ├── event.json
│   ├── index.js
│   ├── package-lock.json
│   └── package.json
└── tsconfig.json
```

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by medelman17** [comment]
I agree. There are a lot of disparate resources in the community; we should have and promote a canonical approach that embraces best practices and makes it as easy as possible for folks to get started with Functions and TypeScript. 

In the meantime, feel free too take a look [here](https://github.com/medelman17/edelman.dev/tree/main/amplify/backend/function) re: how I tend to approach adding TS to my Amplify-based Lambda deployments, my tsconfig, etc.  

The other key point, not captured above, is to add a "generate:<MY_TS_FUNCTION_NAME>" script to the package.json file in your project root with instructions re: how to build your TS-based function. Amplify will execute that script prior to uploading your source to the cloud.

**Comment by ykethan** [comment]
Closing this in favor of https://github.com/aws-amplify/amplify-cli/issues/659. Please feel free in adding additional information on your use case.
