### ISSUE TITLE
Amplify Console

### ISSUE THREAD

**Issue by larboyer** [aws-amplify/docs#3006]
**Page**: [`/cli`](https://docs.amplify.aws/cli)

**Feedback**:

Where are my apps? These tools look amazing. I'm trying to work through "Build a Full-Stack React Application in AWS". The tutorial isn't quite up to date, so there were some misfires, but I've now build the app three times. But I can't get back to any console showing my apps? Amplify Console should show them. Instead it only has "getting started" like I want to do it all over again. Not really a console if it's not a central place to work on my apps. 
Thanks for any advice. 
Like I said; the tools so far look great. 
Larry Boyer

**Comment by swaminator** [comment]
@larboyer please make sure you are in the right region. It's possible you're not.
