### ISSUE TITLE
NPM package mismatch

### ISSUE THREAD

**Issue by rajinder-yadav** [aws-amplify/docs#3024]
**Page**: [`/start/getting-started/setup/q/integration/vue`](https://docs.amplify.aws/start/getting-started/setup/q/integration/vue)

**Feedback**:

This line doesn't match the install command above it (both for npm, yarn)

The @aws-amplify/ui-vue package is a set of Vue-specific UI components that make it easy to integrate functionality like end-to-end authentication flows.

The command

```
yarn add aws-amplify @aws-amplify/ui-components
```

Command show "@aws-amplify/ui-components" not "@aws-amplify/ui-vue", which is correct??

**Comment by rajinder-yadav** [comment]
Not sure but I believe, " @aws-amplify/ui-vue" was from Vue.js 2 and not Vue 3? possibly was missed in the update, but the sentence could be re-written to provide better context and explanation.

**Comment by wlee221** [comment]
Hi @rajinder-yadav, thanks for raising this up! Yes,  this should be `@aws-amplify/ui-vue` in the comment below the command. And you're right that it's `ui-vue` for Vue 2 and `ui-components` for Vue 3. I'll make a PR to fix the typo and make this more obvious.
