### ISSUE TITLE
How to login on AWS AppSync console if Cognito enforces MFA?

### ISSUE THREAD

**Issue by danielesalvatore** [aws-amplify/docs#3027]
**Describe the bug**
Since when we configured our Cognito Instance to mandatory enforce MFA for all users, it seems to be impossible to login in the AWS AppSync console. It seems the MFA input is not handled by the AppSync UI.
While trying to inspect the network traffic, it seems Cognito is challenging the AppSync console to insert MFA, but the use case seems not to be handled.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add an `auth` resource to your project using the amplify console.
2. To enforce MFA for Cognito follow the `Manual configuration`
3. Configure the Cognito instance as the attached screenshot (the important step is MFA enabled: ON)
4. Register a User to Cognito instance, registering his/her MFA device
5. Access the AWS AppSync console and select Query
6. Try to login using the newly created user

**Expected behavior**
The AWS AppSynch console should show an input form to insert the 6-digit MFA code.

**Screenshots**
<img width="1431" alt="Screenshot 2021-03-06 at 12 05 38" src="https://user-images.githubusercontent.com/6150475/110204731-e5b3bd00-7e74-11eb-89d4-31ec8912a2f6.png">
<img width="1190" alt="Screenshot 2021-03-06 at 11 09 37" src="https://user-images.githubusercontent.com/6150475/110204735-e9dfda80-7e74-11eb-827e-f584a1ad82f8.png">
<img width="1238" alt="Screenshot 2021-03-06 at 12 15 32" src="https://user-images.githubusercontent.com/6150475/110204880-b5b8e980-7e75-11eb-9f9f-c882f1cea4ba.png">

**Desktop (please complete the following information):**
- All

**Smartphone (please complete the following information):**
- Al

**Additional context**
It seems the case was handled in the past. If you browse this [repo](https://github.com/amazon-archives/aws-serverless-appsync-loyalty) the README.md file includes: `Go to the AppSync console and select the QUERY section. Click LOGIN WITH USER POOLS, use the client ID you just retrieved from aws-exports.js and the credentials from the user you signed up earlier. You'll also need to provide a MFA code.` [here](https://github.com/amazon-archives/aws-serverless-appsync-loyalty#creating-some-unicorns)

**Comment by matteocarpi** [comment]
Hey, any news with this. I'm experiencing exactly the same bug. :(

**Comment by palpatim** [comment]
@danielesalvatore Sorry for the troubles you're having. This repo is for issues with the documentation site, but since you're having an issue with the AWS AppSync console, please contact AWS Support, or post the issue to the [AWS AppSync Forum](https://forums.aws.amazon.com/forum.jspa?forumID=280).

**Comment by danielesalvatore** [comment]
Hi @palpatim thank you for your reply and for pointing the AppSync forum!

**Comment by danielesalvatore** [comment]
This is the question asked on the forum for future reference: https://forums.aws.amazon.com/thread.jspa?threadID=336745
