### ISSUE TITLE
AWSTask explanation in iOS

### ISSUE THREAD

**Issue by minbi** [aws-amplify/docs#303]
Customer is requesting how AWSTasks functions and how to use the programming paradigm.

The stackoverflow post is old, but new people are commenting. [Post](https://stackoverflow.com/questions/44688027/what-is-the-proper-way-to-work-with-awstask-objects-in-swift/44707249?noredirect=1#comment94181875_44707249)

The previous link provided is now dead. http://docs.aws.amazon.com/mobile/sdkforios/developerguide/awstask.html

**Comment by nikhil-dabhade** [comment]
@rohandubal Did you have any thoughts on this? Can we add more details around AWSTask and its usage?

**Comment by dankuchler** [comment]
I see this documentation in the documentation repository - but couldn't find it linked into the AWS Amplify documentation anywhere:
https://github.com/aws-amplify/docs/blob/master/ios/how-to-ios-asynchrounous-tasks.md

Can you confirm where this documentation exists within the AWS Amplify web based documentation?

**Comment by minbi** [comment]
Hi @dankuchler ,

You are correct, it is not currently part of the website, but the pages do exist and would be available through URL manipulation https://aws-amplify.github.io/docs/ios/how-to-ios-asynchrounous-tasks
