### ISSUE TITLE
[Feedback]What happned to the previous doc in https://aws.amazon.com/ ?

### ISSUE THREAD

**Issue by GMerakis** [aws-amplify/docs#3032]
**Page**: https://docs.amplify.aws/start/getting-started/setup/q/integration/flutter

**Feedback**:

This doc now is much worse than the previous doc. Why?

1. Legacy feel UI. Previous ui on aws.amazon.com looks much better
2. confusing steps. Before each step are clearly separated. First step being create app. Now first step is use amplify. [I may have misunderstood the concept]. But the rest still stands. I have no idea how to use the app after reading the first tutorial and it has introduced more trouble than benefits

Please have an option to use the old doc
aws.amazon.com › hands-on › build-flutter-app-amplify

**Comment by medelman17** [comment]
Hi, @GMerakis. Can you provide a bit more specific context/feedback for what you would like to see in the documentation. I'm having a bit of trouble making this issue actionable.
