### ISSUE TITLE
[Feedback]amplify init fails and recommended solution does not work

### ISSUE THREAD

**Issue by GMerakis** [aws-amplify/docs#3033]
https://github.com/amazon-archives/amplify-photo-gallery-workshop/issues/3

Same error as described and solution does not work.

You should call out this in the tutorial.

It's the first step and it's failing, this is a hardly acceptable user experience

**Comment by palpatim** [comment]
@GMerakis

Can you provide links to the tutorial or guide you're following? It's not clear where you encountered the error, and the guide that issue references is out of date.

**Comment by medelman17** [comment]
Closing as stale.
