### ISSUE TITLE
[missing-page] Analytics

### ISSUE THREAD

**Issue by bradlee96** [aws-amplify/docs#3034]
**Page**: [`https://docs.amplify.aws/lib/analytics/autotrack/q/platform/ios`](https://docs.amplify.aws/lib/analytics/autotrack/q/platform/ios)

**Feedback**: The page is missing!

**Comment by palpatim** [comment]
@bradlee96 Can you clarify what page is missing? Do you mean that when you issue the `amplify console analytics` command, your browser displays a "missing page" error, or that the documentation site itself has missing content?

**Comment by bradlee96** [comment]
Hi! I just meant that the documentation site itself has missing content. It does not load the page properly when attempting to access it from the rest of the documentation (for instance, from https://docs.amplify.aws/lib/analytics/record/q/platform/ios > "Automatically track sessions"). It doesn't affect me personally but I just noticed that it wasn't working so I figured I should report it.

**Comment by palpatim** [comment]
@bradlee96 

I'm not seeing that same problem. Here are my steps:

- Navigate to https://docs.amplify.aws/lib/analytics/record/q/platform/ios
- Click **Automatically track sessions** in the left navigation

**Actual results**
- The page https://docs.amplify.aws/lib/analytics/autotrack/q/platform/ios loads, and displays the following content:
    ![image](https://user-images.githubusercontent.com/227982/110958457-900e6300-8301-11eb-97da-5c37fb32192c.png)

Can you confirm that you are seeing something different following those steps, or can you provide different steps so we can understand the issue?

**Comment by bradlee96** [comment]
Here is a screenshot of what I see!

![image](https://user-images.githubusercontent.com/16856014/110966856-58acb000-831b-11eb-973b-259b5d3023b8.png)

**Comment by lawmicha** [comment]
are there other pages missing for you? Do you see any errors in the browser console? have you tried private browse session?

**Comment by bradlee96** [comment]
No, not as far as I was aware looking through the docs. I have tried private browse, which still does not work.

I get the following errors when:

1) Opening the page from the url directly:
![image](https://user-images.githubusercontent.com/16856014/110976966-2b65ff00-8327-11eb-952e-c22517183965.png)

2) Opening the page from another page:
p-9111c406.js:1725 POST https://pinpoint.us-west-2.amazonaws.com/v1/apps/53496f1ec97f4f57b6f9b1b5df579cda/events 400
FetchHttpHandler.handle @ p-9111c406.js:1725
(anonymous) @ p-6cf98df3.js:1882
(anonymous) @ p-9111c406.js:4023
(anonymous) @ p-9111c406.js:196
(anonymous) @ p-9111c406.js:207
(anonymous) @ p-9111c406.js:128
__awaiter @ p-9111c406.js:107
(anonymous) @ p-9111c406.js:4018
(anonymous) @ p-cafb6dd9.js:31
(anonymous) @ p-9111c406.js:196
(anonymous) @ p-9111c406.js:207
fulfilled @ p-9111c406.js:110
Promise.then (async)
step @ p-9111c406.js:126
fulfilled @ p-9111c406.js:110
Promise.then (async)
step @ p-9111c406.js:126
(anonymous) @ p-9111c406.js:128
__awaiter @ p-9111c406.js:107
(anonymous) @ p-cafb6dd9.js:10
__generator$2.pinpointClient._config.credentials._config.credentials.sessionToken.e.sessionToken._config.credentials.identityId.e.identityId.pinpointClient.middlewareStack.addRelativeTo.step @ p-6cf98df3.js:3122
(anonymous) @ p-9111c406.js:2096
(anonymous) @ p-9111c406.js:196
(anonymous) @ p-9111c406.js:207
(anonymous) @ p-9111c406.js:155
(anonymous) @ p-9111c406.js:207
fulfilled @ p-9111c406.js:110
Promise.then (async)
step @ p-9111c406.js:126
(anonymous) @ p-9111c406.js:128
__awaiter @ p-9111c406.js:107
StandardRetryStrategy.retry @ p-9111c406.js:2081
(anonymous) @ p-9111c406.js:1913
(anonymous) @ p-9111c406.js:196
(anonymous) @ p-9111c406.js:207
(anonymous) @ p-9111c406.js:128
__awaiter @ p-9111c406.js:107
(anonymous) @ p-9111c406.js:1911
(anonymous) @ p-9111c406.js:2491
(anonymous) @ p-9111c406.js:196
(anonymous) @ p-9111c406.js:207
(anonymous) @ p-9111c406.js:128
__awaiter @ p-9111c406.js:107
(anonymous) @ p-9111c406.js:2483
(anonymous) @ p-9111c406.js:2456
(anonymous) @ p-9111c406.js:196
(anonymous) @ p-9111c406.js:207
(anonymous) @ p-9111c406.js:128
__awaiter @ p-9111c406.js:107
(anonymous) @ p-9111c406.js:2450
(anonymous) @ p-9111c406.js:3079
(anonymous) @ p-9111c406.js:4057
(anonymous) @ p-9111c406.js:196
(anonymous) @ p-9111c406.js:207
fulfilled @ p-9111c406.js:110
Promise.then (async)
step @ p-9111c406.js:126
(anonymous) @ p-9111c406.js:128
__awaiter @ p-9111c406.js:107
(anonymous) @ p-9111c406.js:4045
(anonymous) @ p-9111c406.js:2513
(anonymous) @ p-9111c406.js:196
(anonymous) @ p-9111c406.js:207
(anonymous) @ p-9111c406.js:128
__awaiter @ p-9111c406.js:107
(anonymous) @ p-9111c406.js:2508
Client.send @ p-9111c406.js:3222
(anonymous) @ p-6cf98df3.js:2628
(anonymous) @ p-6cf98df3.js:2550
(anonymous) @ p-6cf98df3.js:2561
(anonymous) @ p-6cf98df3.js:2484
__awaiter$1 @ p-6cf98df3.js:2463
EventsBuffer._putEvents @ p-6cf98df3.js:2620
EventsBuffer._sendBatch @ p-6cf98df3.js:2617

**Comment by lawmicha** [comment]
ERR_BLOCKED_BY_CLIENT looks like a client side issue, do you have any extensions that could be blocking the page? can you try a different broswer or try accessing it from another device/phone broswer?

**Comment by bradlee96** [comment]
Ah, my apologies! It seems like uBlock Origin was blocking it for some reason.

**Comment by tjleing** [comment]
Should be fixed now due to #3110 being merged in!  Please reopen if the problem persists 😄
