### ISSUE TITLE
[Feedback]Sample code throws error

### ISSUE THREAD

**Issue by GMerakis** [aws-amplify/docs#3035]
**Page**: https://docs.amplify.aws/start/getting-started/integrate/q/integration/flutter#add-amplify-to-your-application

**Feedback**:

compiler shows

Undefined name 'amplifyconfig'.

when using code from Initializing the Amplify Flutter Library

**Comment by GMerakis** [comment]
Seems I need to generate my own amplifyconfiguration.dart

but this is not mentioned in the tutorial.

**Comment by offlineprogrammer** [comment]
Hi @GMerakis 

The link you shared is the 4th section of the tutorial. You need to start with the Prerequisites section [here](https://docs.amplify.aws/start/getting-started/installation/q/integration/flutter).

Regards
Mo
