### ISSUE TITLE
Content Needed re: Pinpoint/Kinesis Implementation 

### ISSUE THREAD

**Issue by marekq** [aws-amplify/docs#3055]
**Page**: [`/lib/analytics/getting-started/q/platform/js`](https://docs.amplify.aws/lib/analytics/getting-started/q/platform/js)

**Feedback**:

The "getting started" page of Amplify Analytics only shows a code example for the Pinpoint option and not the Kinesis one, it is easy to overlook both options exist. It would be helpful if a sample for the Kinesis configuration would be included too.

**Comment by medelman17** [comment]
Hi, @marekq! Could you let us know if the following addresses your issue: https://docs.amplify.aws/lib/analytics/streaming/q/platform/js If not, we can reopen the issue and dig further.
