### ISSUE TITLE
Content Needed re: Integrating Amplify & Cloud Development Kit (CDK)

### ISSUE THREAD

**Issue by watilde** [aws-amplify/docs#3058]
**Is your feature request related to a problem? Please describe.**
CDK has been used to build apps on top of AWS and it seems to bring chemistry with Amplify sometimes as [`@aws-cdk/aws-amplify`](https://www.npmjs.com/package/@aws-cdk/aws-amplify) exists. If I put this into a user-story, it'd look like the following: As a begineer, I want to know when to use Amplify, CDK or the both when I build an app.

**Describe the solution you'd like**
Having a guide about how to build an app with Amplify and CDK under [Guides](https://docs.amplify.aws/guides/q/platform/js) and describe when to levarage CDK with Amplify based on an example. I think [Nader's article](https://dev.to/dabit3/full-stack-serverless-building-a-real-time-chat-app-with-graphql-cdk-appsync-and-react-1dbb) looks great starting point.

**Describe alternatives you've considered**
The guide could be a part of advanced tutorial based as well. I'd love to hear more inputs from the community.

**Additional context**
I had a chat with some developers who have been using CDK and started using Amplify today and they asked us if there is a tutorial or a guide to learn Amplify with CDK.

**Comment by watilde** [comment]
Leaving a comment to avoid closing

**Comment by falnyr** [comment]
Dumping more resources here:
 - https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-amplify.App.html
 - https://aws.amazon.com/blogs/mobile/deploying-a-static-website-with-aws-amplify-and-cdk/
 - https://github.com/dabit3/amplify-with-cdk

**Comment by josefaidt** [comment]
Hey folks :wave: you can now use AWS CDK to create [custom resources](https://docs.amplify.aws/cli/custom/cdk/) and [override](https://docs.amplify.aws/cli/auth/override/) Amplify-managed resources
