### ISSUE TITLE
[Feedback] Ionic - Missing Step on Getting Started Tutorial

### ISSUE THREAD

**Issue by billygerhard** [aws-amplify/docs#3064]
**Page**: [`/start/getting-started/setup/q/integration/ionic#initialize-a-new-backend`](https://docs.amplify.aws/start/getting-started/setup/q/integration/ionic#initialize-a-new-backend)

**Feedback**:

After setting up your "start command" there is another step on the CLI "Select the authentication method" that isn't explained on which option you would want to choose and why.

**Comment by mauerbac** [comment]
This is outdated
