### ISSUE TITLE
Google API Change Renders Amplify (iOS, Android) "SignIn" Documentation Obsolete 

### ISSUE THREAD

**Issue by ruiguoamz** [aws-amplify/docs#3068]
**Describe the bug**
Follow this [link](https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/ios#amazon-cognito-user-pool-setup)
Step 1: Go to [Google Developer Console](https://developers.google.com/identity/sign-in/web/sign-in)
Step 2: There is no `Configure a project` button anymore. So that it breaks the customer experience.

**Additional context**
I will create a PR to fix this issue later

**Comment by ruiguoamz** [comment]
step 1: Go to [`Google developer console dashboard`](https://console.cloud.google.com/apis/dashboard) to create a project instead of doing it on a later step per current doc. 
step 2: Once a project is created, create an `OAuth Client`, get the `app id` and `app secret`.
step 3: Configure Amplify Auth using `app id` and `app secret` from step 2, and get the `hostedUI endpoint` once `amplify push` completes
step 4: Go back to `Google developer console dashboard`, from the OAuth client just created, edit `Authorized JavaScript origins` and `Authorized redirect URIs`.

**Comment by medelman17** [comment]
Can we solve this issue by linking to a google-maintained resource (instead of homebrew) so that we don't have to take on the risk of our documentation being outdated?

**Comment by ruiguoamz** [comment]
Regarding this issue:

The short term fix would be simply updating screenshots and steps descriptions for `Sign In With Google` part

The long term fix is to provide link to social providers managed resource for every social providers (not only Google)
