### ISSUE TITLE
[missing-page] Push Notifications Docs

### ISSUE THREAD

**Issue by armenr** [aws-amplify/docs#3082]
**Page**: [`https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/js`](https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/js)

**Feedback**: 
Uncertain why or how, but looks like the docs for Push notifications don't exist/have gone missing.

**Comment by medelman17** [comment]
Hi @armenr, can you be a bit more specific? If I travel to the URL you posted above, everything appears to be working properly. What do you see?

**Comment by armenr** [comment]
Caching issue. Please disregard. Very bizarre. Thank you! I apologize for wasting your time!

**Comment by medelman17** [comment]
Haha. No problem. Never a waste of time. You sure it was on your end and not ours?

**Comment by armenr** [comment]
Pretty sure! Checked with an InCognito window, and all was well. No clue what the deal is, but I know for a fact that FireFox and/or Brave appear increasingly attractive to me, with each passing day. Chrome is just...*sigh*

Thanks again! :) You're awesome!

**Comment by medelman17** [comment]
Are your running any ad blocking software in Chrome, by chance? If so, could you try and disable and see if it works as expected? We're having some issues related to the above and my radar is going off :-)

**Comment by armenr** [comment]
Will do! Give me 10 minutes!

**Comment by armenr** [comment]
You're right. 

On my phone, I run AdGuard. 

When enabled, I get the 404. 

When disabling adguard, I see the documentation. 

Adguard enabled:

![Screenshot_20210329-220101_Chrome.jpg](https://user-images.githubusercontent.com/7662191/112936291-61063880-90da-11eb-92dd-80c0114894e9.jpg)

Adguard disabled:
![Screenshot_20210329-220242_Chrome.jpg](https://user-images.githubusercontent.com/7662191/112936338-809d6100-90da-11eb-9174-30e2a6ea1855.jpg)

Sooooo, it sounds like your intuition is correct!

**Comment by medelman17** [comment]
Thanks, @armenr! I'm going to close this issue, but link to it internally/in a new issue that tackles this issue globally.

**Comment by tjleing** [comment]
Should be fixed now due to #3110 being merged in!  Please reopen if the problem persists 😄
