### ISSUE TITLE
Content Needed re: Analytics User Profile Attributes for iOS and Android Users

### ISSUE THREAD

**Issue by drochetti** [aws-amplify/docs#3084]
**Is your feature request related to a problem? Please describe.**
The Analytics documentation has no details on the different use cases and attributes that can be updated using the `identifyUser` API.

**Describe the solution you'd like**
The documentation should address the different attributes and also present the API in terms of possible use cases. Also, it could clarify the level of abstraction and how that maps to the underlying Pinpoint functionality.

**Describe alternatives you've considered**
N/A

**Additional context**
Customers using the Pinpoint Dashboard and documentation are not clear on how to update specific endpoint attributes through the `Amplify.Analytics` abstraction.

**Comment by medelman17** [comment]
@drochetti -- let's collaborate on moving this issue forward. The reference documentation regarding the `identifyUser` api seems like a fairly straight forward, actionable task. As for the content regarding potential use-cases, my initial thought is that we should explicitly identify the most pertinent use cases and break creating content for each out into a separate issue/task.

**Comment by phantumcode** [comment]
@drochetti Can you provide additional clarification? It looks like there's already documentation for Analytics identifyUser on both [iOS ](https://docs.amplify.aws/lib/analytics/identifyuser/q/platform/ios/)and [Android](https://docs.amplify.aws/lib/analytics/identifyuser/q/platform/android/).  Are you requesting to add additional use cases and context to these existing documentation for each platform? Or are you look to add additional details to the [API reference](https://aws-amplify.github.io/amplify-ios/docs/Protocols/AnalyticsCategoryBehavior.html#/s:7Amplify25AnalyticsCategoryBehaviorP12identifyUser_11withProfileySS_AA0bfH0VSgtF)

**Comment by phantumcode** [comment]
Per offline response from @drochetti 
_When should users call identifyUser ? When can they just ignore it? What if the user is not signed in, how to identify anonymous users? How does this API relate to Pinpoint.updateEndpoint (this is a common confusion)?_

See other documentation for reference:

- https://segment.com/docs/connections/spec/identify/

- https://developer.mixpanel.com/docs/javascript#identify
