### ISSUE TITLE
[Feedback]FEEDBACK_TITLE_HERE

### ISSUE THREAD

**Issue by hville** [aws-amplify/docs#3089]
**Page**: [`/start/q/integration/js`](https://docs.amplify.aws/start/q/integration/js?sc_icampaign=js-start&sc_ichannel=choose-integration)

**Feedback**:

"Once the user is created, Amplify CLI will ask you to provide the accessKeyId and the secretAccessKey to connect Amplify CLI with your newly created IAM user."
??? where do we get these 2 accessKeyId and the secretAccessKey

**Comment by medelman17** [comment]
Hi, @hville -- I think the documentation you are looking for lives here: https://docs.amplify.aws/cli/start/install#option-2-follow-the-instructions 

![user-creation](https://user-images.githubusercontent.com/14793389/113192975-6c1dad80-922d-11eb-8f14-5d75e4be115a.gif)
