### ISSUE TITLE
[broken-link] Flutter Install Prerequisites Tutorial

### ISSUE THREAD

**Issue by siddharthram** [aws-amplify/docs#3093]
**Page**: [`https://docs.amplify.aws/start/getting-started/installation/q/integration/flutter?sc_icampaign=flutter-start

**Comment by siddharthram** [comment]
broken link

**Comment by medelman17** [comment]
Hi, @siddharthram -- can you let me know how you navigated to the link above?

**Comment by jakeburden** [comment]
Update:
https://github.com/aws-amplify/docs/pull/3109 is ready for review and resolves this issue.

**Comment by medelman17** [comment]
Thanks for the quick turn around @jakeburden!

**Comment by jakeburden** [comment]
Update:
Issue was auto-closed as https://github.com/aws-amplify/docs/pull/3109 has been merged
