### ISSUE TITLE
Clarification Needed re: Use of Enums and GraphQL

### ISSUE THREAD

**Issue by Kilo-Loco** [aws-amplify/docs#3096]
**Is your feature request related to a problem? Please describe.**
The docs don't cover use cases for handling enums with GraphQL, specifically mutations seem to be lacking. So then the customer tries to do something pretty logical like this and gets an unexpected result.

<img width="668" alt="Screen Shot 2021-03-31 at 2 22 31 PM" src="https://user-images.githubusercontent.com/13292981/113213283-ce29e300-922c-11eb-826d-e199f2e8ad28.png">

This problem actually requires a more complex solution when working with Flutter specifically. When the mutation requires an enum to be passed as a variable, the customer is expected to know that the variable value should be a String. So if the customer DOES know that, then a natural implementation might be to use the `.toString()` method. However, this is incorrect because an enum like `MyEnum.WORKING.toString()` will output `MyEnum.WORKING`, when in reality, the GraphQL request needs just `WORKING`.

The solution to this problem is as follows:

```dart
extension SexyPayload on MyEnum {
  String get payloadValue {
    String value;
    switch (this) {
      case MyEnum.WORKING:
        value = 'WORKING';
        break;
      case MyEnum.NOTWORKING:
        value = 'NOTWORKING';
        break;
    }
    return value;
  }
}
```

Then the GraphQL request can be made like so:

```dart
final variables = {'myEnum': someEnum.payloadValue};

final request = GraphQLRequest(document: document, variables: variables);
```

**Describe the solution you'd like**
We should consider either using a more verbose object in our documentation which includes objects like enums and other possible types, or we should have code snippets that directly showcase how to work with these more complex types.

**Describe alternatives you've considered**
Maybe this use case doesn't satisfy what should be included directly in the docs, maybe it should be in Guides?

**Additional context**
n/a

**Comment by medelman17** [comment]
@Kilo-Loco, I can't speak to flutter, but the JS/TS implementation appears to be working as expected. See schema/operation/result below.

Also, I note in your JS-example above, you likely want to enclose your item variables inside an `input` object and such that the request looks like the one below. 

Schema: 
```graphql
type Post @model {
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  text: String
  status: PostStatus
}

enum PostStatus {
  DRAFT
  PUBLISHED
}
```

Operation:
```typescript
async function handleApiBasedMutation() {
    try {
      const input: CreatePostInput = {
        text: "Another test post with enums!",
        status: PostStatus.DRAFT,       // using string-type "DRAFT", here, throws a TS error...
      };

      const result = await API.graphql(
        graphqlOperation(mutations.createPost, {
          input,
        })
      );
      console.log("result", result);
    } catch (err) {
      console.log("err", err);
    }
  }
```

Result: 

```javascript
{
    "createPost": {
        "id": "7019efef-6c92-4c67-9ee8-8e9200605289",
        "createdAt": "2021-03-31T22:08:39.957Z",
        "updatedAt": "2021-03-31T22:08:39.957Z",
        "text": "Another test post with enums!",
        "status": "DRAFT",
        "_version": 1,
        "_deleted": null,
        "_lastChangedAt": 1617228519979
    }
}
```

**Comment by medelman17** [comment]
Flutter bit looks potentially related to serialization issues/codgen-outputs. 

See, e.g., https://github.com/aws-amplify/amplify-flutter/issues/241; https://github.com/aws-amplify/amplify-flutter/issues/462; https://github.com/aws-amplify/amplify-flutter/issues/279

**Comment by Kilo-Loco** [comment]
> Flutter bit looks potentially related to serialization issues/codgen-outputs.
> 
> See, e.g., [aws-amplify/amplify-flutter#241](https://github.com/aws-amplify/amplify-flutter/issues/241); [aws-amplify/amplify-flutter#462](https://github.com/aws-amplify/amplify-flutter/issues/462); [aws-amplify/amplify-flutter#279](https://github.com/aws-amplify/amplify-flutter/issues/279)

While there are some similarities in these issues, the fact of the matter is that the docs are only showing off the simplest use cases for a core feature that makes Amplify appealing. [Analytics](https://docs.amplify.aws/lib/analytics/record/q/platform/ios#record-event) on the other hand seems to be covering the different types that can be logged with an event, even if it's still a simple use case. 

I think the ideal documentation would allow a developer to write Amplify code in an app like NotePad/TextEdit and not have to rely on code completion and compilation errors to guide them.

**Comment by medelman17** [comment]
I'm not disagreeing; just suggesting that the pain point here might be arising out of a faulty implementation rather than lack of documentation full stop. I'm not terribly enthused about documenting in official docs something that might be better understood as a workaround for an implementation issue that should be fixed. 

I can recreate the Flutter issue locally. Interestingly, the idiopathic flutter implementation seems to work without issue using `DataStore` instead of `API`. For example, I can execute the following code successfully: 

```dart
void _createPost(String title) async {
    Post newPost = Post(title: title, rating: 15, status: PostStatus.DRAFT);
    print('Creating new post...' + newPost.toString());
    try {
      await Amplify.DataStore.save(newPost);
      print('Created post');
    } catch (e) {
      print(e);
    }
  }
```

Result: 

```bash
flutter: Creating new post...Post {id=e846e1e5-7f83-40e3-873a-ae8b94e7fe69, title=Create Todo with DataStore and Enum, status=DRAFT, rating=15, content=null}
flutter: ***
flutter: Received event of type EventType.create
flutter: Received post Post {id=e846e1e5-7f83-40e3-873a-ae8b94e7fe69, title=Create Todo with DataStore and Enum, status=DRAFT, rating=15, content=null}
flutter: Received post Instance of 'SubscriptionEvent<Post>'
flutter: ***
flutter: Created post
flutter: ***
```

I wonder what they're doing under the hood and if the same couldn't be done for API.

**Comment by Lorenzohidalgo** [comment]
@medelman17 with DataStore while creating new instances work, querying by a variable that is an Enum fails.

The example in the documentation just passes the Enum like:
```
List<Post> posts = await Amplify.DataStore.query(Post.classType,
    where: Post.RATING.eq(2).and(Post.STATUS.eq(PostStatus.PUBLISHED)));
```

But querying a model passing the Enum (created via AdminUI) Fails:
```dart
switch (_spaceType) {
  case SpaceTypeEnum.STARTER:
  case SpaceTypeEnum.AGILE:
  case SpaceTypeEnum.PRO:
    final result = await Amplify.DataStore.query(
      PricingStructure.classType,
      where: PricingStructure.SPACETYPE.eq(_spaceType),
    );
    if (result.isNotEmpty) {
      _structure = result.first;
    }
    break;
```
The error:
![image](https://user-images.githubusercontent.com/22448611/115758335-4bb1c080-a39f-11eb-99ca-0c79afde6f56.png)
