### ISSUE TITLE
[missing-page] push-notification for android?

### ISSUE THREAD

**Issue by ensean** [aws-amplify/docs#3098]
**Page**: [`https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/android`](https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/android)

**Feedback**:

**Comment by medelman17** [comment]
Hi @ensean! Are you running any ad blocking software in Chrome, by chance? If so, could you try and disable and see if it works as expected? We're having some issues related to the above and my radar is going off :-)

See, e.g., https://github.com/aws-amplify/docs/issues/3082

**Comment by ensean** [comment]
@medelman17 If I open the link https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/js , it works as expected, the page contains setup guide for Android and iOS. But since the platform is `js`, is this a bit confuse?

Push notification menu can be found for `Javascript` platform
![image](https://user-images.githubusercontent.com/12255172/113373142-d0ab4a80-939c-11eb-98bd-1e101c47964e.png)

Push notificaiton menu is missing for `Android` platform?
![image](https://user-images.githubusercontent.com/12255172/113373235-fb959e80-939c-11eb-9344-70a08b774464.png)

**Comment by medelman17** [comment]
I gotcha! Thanks for the feedback!

**Comment by palpatim** [comment]
Amplify only supports Push notifications for JS (and by extension, React Native), which is why there's no specific section in the Android, iOS, and Flutter docs.

**Comment by medelman17** [comment]
> Amplify only supports Push notifications for JS (and by extension, React Native), which is why there's no specific section in the Android, iOS, and Flutter docs.

I'm not sure this is the root issue, here? But I'm happy to be mistaken. It looks @ensean is suggesting that like we're advertising the functionality for JS when it doesn't exist?

**Comment by palpatim** [comment]
@medelman17 I'm interpreting the question as "Why are you advertising push notifications for JS with setup instructions for Android & iOS, but not providing setup instructions in the platform-specific sections?" If that is an accurate interpretation of the question, my explanation applies.

If your interpretation is accurate, I'd ask what is implying that we don't support the functionality? My understanding (which could easily be wrong!) is that we do support notifications in RN, which are backed by native features.

**Comment by swaminator** [comment]
We are working on first class React Native support in the platform picker. In the interim, we've made it clearer in the docs that React Native is the only supported platform for push notifications.
