### ISSUE TITLE
[Feedback] Breaking down permissions by module

### ISSUE THREAD

**Issue by edwardaux** [aws-amplify/docs#3099]
**Page**: [`/cli/usage/iam`](https://docs.amplify.aws/cli/usage/iam)

**Feedback**:

The [Getting Started](https://docs.amplify.aws/cli/start/install#option-2-follow-the-instructions) says that the recommended process is to create a user with `AdministratorAccess` 😱 ... however, I eventually stumbled across a [page](https://docs.amplify.aws/cli/usage/iam) that contains a detailed list that could, in theory, be filtered down to a least-privilege list.

Might I suggest, though, that rather than putting the burden onto every developer to somehow find and remove the un-needed items, perhaps a better way to structure this page would be to group the various entries that are required for each module and then we can at least just combine the entries that we know we need for the module we're using. Otherwise, you're forcing every developer to take a guess and use trial'n'error to properly secure our assets (or worse, they follow the advice to just give global admin access).

For example, something like this:

## Core
These are needed no matter which module you're using:
```
"amplify:CreateApp",
...
```

## Authentication
These are needed to support authentication (in addition to the entries in Core):
```
"cognito-identity:CreateIdentityPool",
...
```
 
## Storage
These are needed to support storage (in addition to the entries in Core):
```
"s3:CreateBucket",
...
```

and so on...

**Comment by edwardaux** [comment]
Nothing quite indicates a disregard for users taking the time to offer suggestions like having a bot that automatically closes issues. Sigh.

**Comment by ykethan** [comment]
The page has been removed in favor of [AWS managed policies](https://docs.aws.amazon.com/amplify/latest/userguide/security-iam-awsmanpol.html#security-iam-awsmanpol-AdministratorAccess-Amplify). Closing the issue.
