### ISSUE TITLE
API: Document `NONE` authorizationType option

### ISSUE THREAD

**Issue by palpatim** [aws-amplify/docs#3105]
In the referenced issue, the customer had custom authorization behavior that relied on the idToken from a User Pool claim. While we'd normally expect the customer to set up authentication on their REST endpoint with out-of-the-box User Pools support, in this case, the logic was custom.

The customer had custom logic to insert an **Authorization** header with a `Bearer` value that included the User Pool's **identityToken**. This custom header was being overwritten by the normal Amplify behavior to inject **Authorization** headers with User Pools credentials per the standard.

The issue is likely solvable by setting the API's **authorizationType** to `NONE`, but that value is not documented [in our API Authorization docs](https://docs.amplify.aws/lib/restapi/authz/q/platform/ios#unauthenticated-requests). 

We should add documentation for that option, rather than making customers discover it in the IDE or by inspecting source code. Note that "public APIs" are not the only use case--this is also suitable for custom authentication use cases as described here.

_Originally posted by @palpatim in https://github.com/aws-amplify/amplify-ios/issues/1130#issuecomment-812566001_

**Comment by palpatim** [comment]
Nice try, stalebot

**Comment by atierian** [comment]
Closing as the `NONE` `authorizationType` is now documented [here](https://docs.amplify.aws/lib/restapi/authz/q/platform/ios/#none).
