### ISSUE TITLE
[Feedback] AWS Amplify without nodejs depedency

### ISSUE THREAD

**Issue by asesh** [aws-amplify/docs#3112]
**Page**: [`/lib/project-setup/prereq/q/platform/ios`](https://docs.amplify.aws/lib/project-setup/prereq/q/platform/ios)

**Feedback**:

Do you guys have any plan to make AWS Amplify available without Nodejs dependency at all? Well not all use Nodejs to develop apps, so I see reason to install it on our machines.
Thanks

**Comment by palpatim** [comment]
@asesh We have [deprecated the Amplify/Tools pod](https://github.com/aws-amplify/amplify-ios/releases/tag/v1.6.1) that requires NPM/NPX, but the Amplify CLI still has a dependency on NPM and NodeJS. Some customers have worked around this by creating Docker containers that have requirements preinstalled, but ultimately, the CLI is still using that.

**Comment by asesh** [comment]
> @asesh We have [deprecated the Amplify/Tools pod](https://github.com/aws-amplify/amplify-ios/releases/tag/v1.6.1) that requires NPM/NPX, but the Amplify CLI still has a dependency on NPM and NodeJS. Some customers have worked around this by creating Docker containers that have requirements preinstalled, but ultimately, the CLI is still using that.

Well I understand that but is there any plan to remove Nodejs dependency from it too? Like I said before, not all use Nodejs, so for that reason and other security reasons we would prefer not to install Nodejs on our machines.

Thanks
