### ISSUE TITLE
[Feedback]I believe following the documentation for setting up one to one relationships causes an error

### ISSUE THREAD

**Issue by karsenkeith** [aws-amplify/docs#3116]
**Page**: [`/console/data/relationships`](https://docs.amplify.aws/console/data/relationships)

**Feedback**:

The documentation shows creating a connection in the console. Then it says - "Now repeat the same steps for the Book model - define a 1:1 relationship from Book to ISBN." 

After creating the reference on both models I get "Error: Models are not topologically sortable. Please verify your schema.", and I did not get this error when the reference was only on one of the models.

**Comment by palpatim** [comment]
Thanks for calling this out. We do normally recommend that one side of a "1:1" relationship is not actually "1:1".

**Comment by medelman17** [comment]
Hi, @karsenkeith. Thanks for the feedback. We've ticketed this internally.
