### ISSUE TITLE
[Feedback] Location guides should highlight Cognito unauth pool limitations

### ISSUE THREAD

**Issue by mojodna** [aws-amplify/docs#3120]
## Pages

* [`/guides/location-service/setting-up-your-app/q/platform/ios#allow-guest-users-access-to-the-place-index`](https://docs.amplify.aws/guides/location-service/setting-up-your-app/q/platform/ios#allow-guest-users-access-to-the-place-index)
* [`/guides/location-service/setting-up-your-app/q/platform/android#allow-guest-users-access-to-the-place-index`](https://docs.amplify.aws/guides/location-service/setting-up-your-app/q/platform/android#allow-guest-users-access-to-the-place-index)
* [`/guides/location-service/tracking-device-location/q/platform/ios#allow-guest-users-access-to-the-tracker`](https://docs.amplify.aws/guides/location-service/tracking-device-location/q/platform/ios#allow-guest-users-access-to-the-tracker)
* [`/guides/location-service/tracking-device-location/q/platform/android#allow-guest-users-access-to-the-tracker`](https://docs.amplify.aws/guides/location-service/tracking-device-location/q/platform/android#allow-guest-users-access-to-the-tracker)

## Feedback

When using Cognito unauthenticated identity pools with Amazon Location Service, there are some implicit limits on the actions that can be used. These are documented in [Allowing unauthenticated guest access using Amazon Cognito](https://docs.aws.amazon.com/location/latest/developerguide/authenticating-using-cognito.html#cognito-create-user-pool) within the service developer guide, but should probably be replicated on the pages above to highlight them. We have received reports from multiple customers who are using Amplify but were unaware of this limitation and ran into unanticipated errors with this as the cause when attempting geofence-related operations.

Specifically, including some variation on the following would be helpful:

>  IAM policies associated with unauthenticated identity roles are limited to the following actions:
>
> * `geo:GetMap*`
> * `geo:SearchPlaceIndex*`
> * `geo:BatchUpdateDevicePosition`
>
> Including any other Amazon Location actions will have no effect, and unauthenticated identities will be unable to call them.

**Comment by eeatonaws** [comment]
Additional information on using guest access with Amazon Location Service has been added to the following pages for Android and Swift, respectively:
- https://docs.amplify.aws/lib/geo/existing-resources/q/platform/android/
- https://docs.amplify.aws/lib/geo/existing-resources/q/platform/ios/
