### ISSUE TITLE
[Feedback] Amplify Flutter Datastore Documentation - Import line mistake

### ISSUE THREAD

**Issue by martinzuccotti** [aws-amplify/docs#3123]
**Page**: [`/lib/datastore/getting-started/q/platform/flutter`](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/flutter)

**Feedback**:

In initialize [amplify datastore section](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/flutter#initialize-amplify-datastore), the code snippet should be say `import 'models/ModelProvider.dart';` instead of `import 'codegen/ModelProvider.dart';`

![imagen](https://user-images.githubusercontent.com/43626965/114189055-25f8d600-9920-11eb-9d48-976f0e8edccb.png)

**Comment by cshfang** [comment]
Think this can be closed after #3137
