### ISSUE TITLE
Update Auth Theming Docs to Ref Current UI Components

### ISSUE THREAD

**Issue by wlee221** [aws-amplify/docs#3126]
**Page**: [`/lib/auth/customui/q/platform/js`](https://docs.amplify.aws/lib/auth/customui/q/platform/js)

**Feedback**: 

[Customize UI Theme](https://docs.amplify.aws/lib/auth/customui/q/platform/js#customize-ui-theme) section is outdated and is based on the legacy `aws-amplify-react` components. This should be linked to UI Components [Theming Documentation](https://docs.amplify.aws/ui/customization/theming/q/framework/react) instead.

**Comment by medelman17** [comment]
To be clear, @wlee221 -- this doesn't require the creation of additional documentation, just the re-linking to an already updated resource?

**Comment by wlee221** [comment]
Yep, that is right. I'll get this done this week; I just wanted to create an issue to track this until I get the time to make the PR.

**Comment by medelman17** [comment]
We can take care of this for you, @wlee221. :-)

cc: @jakeburden, @tjleing
