### ISSUE TITLE
Documentation for "Predictions" > "Identify entities from images" (JS) does not include option to provide source image as bytes

### ISSUE THREAD

**Issue by rajrajhans** [aws-amplify/docs#3129]
**Is your feature request related to a problem? Please describe.**
For many usecases, there is a need to provide source image in base64 encoded image binary format to `Predictions.identify`. An example usecase is when one is taking image from a webcam source. For this, the [Rekognition API](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Rekognition.html) does provide an option to have input image in `Bytes`. Amplify Predictions JS library supports it too, **but it is not documented**. The [documentation page](https://docs.amplify.aws/lib/predictions/identify-entity/q/platform/js) only includes two options - "File object" and "S3 Object".

**Describe the solution you'd like**
Include necessary documentation for providing image as [ArrayBuffer object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer) (which is supported by Amplify Predictions) in addition to providing it as File Object. 

**Describe alternatives you've considered**
An alternative is to convert to File and then provide, but it is an extra step which is not necessary since Predictions does support taking in image as `bytes`. Also, the [Amazon Rekognition Image operation latency](https://docs.aws.amazon.com/rekognition/latest/dg/operation-latency.html) page mentions that "Calling an Amazon Rekognition Image operation with image bytes is faster than uploading the image to an Amazon S3 bucket and then referencing the uploaded image in an Amazon Rekognition Image operation".

**Comment by medelman17** [comment]
Hi, @rajrajhans -- thanks for the feedback! At first glance, sounds like something we would want to document. Would you want to take a stab at creating the doc and file a pull request?

**Comment by medelman17** [comment]
Nevermind, @rajrajhans -- I found it. :-) Next time, add a `closes #3130` in your commit message and it'll link automatically!
