### ISSUE TITLE
Not clear documentaton on withAuthenticator authenticatorComponents

### ISSUE THREAD

**Issue by sakhmedbayev** [aws-amplify/docs#313]
**Describe the bug**
Not clear what the following [config](https://aws-amplify.github.io/docs/js/authentication#props) does in `withAuthenticatore`
```
// Show only certain components
                authenticatorComponents = [MyComponents],
```

**To Reproduce**
1. Go here https://aws-amplify.github.io/docs/js/authentication#props

**Expected behavior**
More clear explanation

**Comment by sakhmedbayev** [comment]
@nikhil-dabhade, "what constitutes the components" is not clear.

**Comment by justinclayton** [comment]
Also, the section written as-is throws an error. A properties object `{}` must exist. It should read:

```
export default withAuthenticator(App, {
                // Render a sign out button once logged in
                includeGreetings: true, 
                // Show only certain components
                authenticatorComponents: [MyComponents],
                // display federation/social provider buttons 
                federated: {myFederatedConfig}, 
                // customize the UI/styling
                theme: {myCustomTheme}
});
```

**Comment by joelvh** [comment]
I get a blank screen if I try to specify `authenticatorComponents`

**Comment by jzacharuk** [comment]
I am also having an issue with this.

`export default withAuthenticator(App);` 
Displays a login with option to Reset Password / Create Account.
After entering username/password and clicking login, it displays the application.

Either of these:
`export default withAuthenticator(App, true, [<SignIn />]);`
`export default withAuthenticator(App, { includeGreetings: true, authenticatorComponents: [<SignIn />] });`
Displays a login with no option to Reset Password / Create Account (as expected and desired).
After entering username/password and clicking login it displays a blank screen.
Refreshing the page then displays application.

**Comment by arhoy** [comment]
What myFederatedConfig? IT is not clear from the docs what this value should be . I am trying to use Facebook Auth. Please point me to the right direction!

I am getting  'myFederatedConfig' is not defined  no-undef

```
export default withAuthenticator(AppPage, {
  includeGreetings: true,
  federated: { myFederatedConfig },
});

```

**Comment by rosmu** [comment]
@arhoy myFederatedConfig is as follows:

export interface FederatedConfig {
    auth0Config?: {
        audience?: string;
        clientID: string;
        domain: string;
        responseType: string;
        redirectUri: string;
        returnTo?: string;
        scope?: string;
    };
    amazonClientId?: string;
    facebookAppId?: string;
    googleClientId?: string;
    oauthConfig?: {
        [key: string]: any;
    };
}

**Comment by harshmsomani** [comment]
> 

Unable to display a login page with no option to Reset Password / Create Account. Any suggestions?
