### ISSUE TITLE
[Feedback]Module not found: Can't resolve './aws-exports'

### ISSUE THREAD

**Issue by apoorvatvk** [aws-amplify/docs#3133]
**Page**: [`/start/q/integration/react`](https://docs.amplify.aws/start/q/integration/react)

**Feedback**:

I keep getting this error, despite following all the steps in the tutorial. 
I'm at the authentication stage of the tutorial 
https://docs.amplify.aws/start/getting-started/auth/q/integration/react#create-authentication-service

**Comment by medelman17** [comment]
Hi @apoorvatvk -- can you link to your code and or provide a minimal reproduction? Do you see the `aws-exports.js` file existing anywhere within your project?

**Comment by MachariaK** [comment]
Hello @apoorvatvk. In VueJs, I usually get this error if the path is './aws-exports' but when I change to '@/aws-exports', it works. Please check the location of your "aws-exports" file and update the path and it will work.
