### ISSUE TITLE
Ionic - app.component.ts code reference needs help

### ISSUE THREAD

**Issue by hansmon** [aws-amplify/docs#3149]
**Page**: [`/start/getting-started/data-model/q/integration/ionic`](https://docs.amplify.aws/start/getting-started/data-model/q/integration/ionic)

**Feedback**:

The code instructions on this tutorial page https://docs.amplify.aws/start/getting-started/data-model/q/integration/ionic#connect-frontend-to-api (specifically related to app.component.ts) is difficult to follow. Couldn't get past this page. Maybe it needs a review and update?

**Comment by hansmon** [comment]
Following needs to be added to tutorial to get it working

import { Platform } from '@ionic/angular'; 
public platform: Platform (under constructor)

**Comment by rachelnabors** [comment]
We're removing Ionic from the tutorials, so closing this out
