### ISSUE TITLE
[Feedback] documentation for recording custom event attributes is inconsistent/wrong

### ISSUE THREAD

**Issue by gspeicher** [aws-amplify/docs#3151]
**Page**: [`/lib/analytics/record/q/platform/js#record-a-custom-event-with-attributes`](https://docs.amplify.aws/lib/analytics/record/q/platform/js#record-a-custom-event-with-attributes)

**Feedback**:

Under "Record a Custom Event with Attributes", the code example contains the comment "Attribute values must be strings" but then below the code block, the documentation states that "Attributes must have the type `String` or be an array of strings". Which is correct? Are array values allowed?

If I actually attempt to record an event with a custom attribute containing an array of strings, the operation never completes, never returns an error, and the event never gets recorded. It just hangs indefinitely. Not sure if that is the expected behavior but can't tell from the documentation whether or not this is a bug.

**Comment by nickarocho** [comment]
Hi @gspeicher, just wanted to check in here and let you know I'm working on replicating the issue to further understand the underlying functionality.

Once I am getting custom event attributes to show up in my sample app I'll update you to see if we need to simply make a documentation change or if there is a problem in the underlying method's source code.

**Comment by nickarocho** [comment]
Hi @gspeicher, I am working with an internal team to resolve this issue on a technical level. For now, we've removed the line in question from our documentation for now as a safeguard to avoid any further confusion.

Thanks for pointing this out to us!
