### ISSUE TITLE
Simplify subheadings for sidebar

### ISSUE THREAD

**Issue by nubpro** [aws-amplify/docs#3156]
![image](https://user-images.githubusercontent.com/762914/115370460-a9a5a300-a1fb-11eb-8d7b-b675f27cbea8.png)

Lets make it easier for devs to find out what they want in a glance

For example:
Define model types -> @model - Define model types
Index your data with keys -> @keys - Index data
Setup authorization rules -> @auth - Authorization rules
...
...
You get the picture

less words = less things to read = less fatigue = better DX?

**Comment by medelman17** [comment]
@nubpro -- we're currently reevaluating the entire information architecture for the docs site, including navigation-related bits. I'm going to close this as a `won't fix` for the the time being, but, rest assured, it's on the roadmap.
