### ISSUE TITLE
"How to contribute" guide

### ISSUE THREAD

**Issue by watilde** [aws-amplify/docs#3159]
**Is your feature request related to a problem? Please describe.**
As a developer who is interested to contribute to amplify projects, I want to know how to contribute and where to start so that I can start contributing.

**Describe the solution you'd like**
Host https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md as a web page in somewhere like Guides section.

**Describe alternatives you've considered**
Hosting the markdown as a web page in community site would be an alternative option.

**Additional context**
I'm recently asked how to contribute to Amplify projects from community members of Amplify. I usually refer the CONTRIBUTING.md and [`good-first-issue`](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) to explore which is mentioned at https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#finding-contributions. It'd be great if we also can host the markdown as a page.

Refs: https://nodejs.org/en/get-involved/contribute/

**Comment by medelman17** [comment]
This makes sense to me; @watilde -- can you open a PR and reference this issue?

**Comment by watilde** [comment]
Leaving a comment to keep this opening.

**Comment by mauerbac** [comment]
Will close as https://www.contributetoamplify.com/ has launched
