### ISSUE TITLE
no GraphQL Endpoint URL info

### ISSUE THREAD

**Issue by pshkurateniuk-griddynamics** [aws-amplify/docs#3163]
**Page**: [`/lib/graphqlapi/getting-started/q/platform/js`](https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/js#enable-queries-mutations-and-subscriptions)

**Feedback**:

There is literaly 0 info about GraphQL Endpoint URL, how can I use graphqlOperation without this info?

**Comment by nubpro** [comment]
Your graphql endpoint is set on your `aws-exports.js` file.
It you have successfully configured your project with Amplify though Amplify.configure. It should work as expected when calling `API.graphql(...)`

**Comment by pshkurateniuk-griddynamics** [comment]
Thank you, 
I know this by now (found this info on some medium page)
But this chapter called: "API (GRAPHQL) Getting started"
and you can't really use anything from this page without `graphql_endpoint`, and there is nothing that describes it here (not even a link to configuration or any mention about it)

So I don't get how are we **Getting started with GraphQL** without

**Comment by nubpro** [comment]
ugh
