### ISSUE TITLE
Docs are obsolete and requires an update

### ISSUE THREAD

**Issue by azamsharp** [aws-amplify/docs#3164]
**Page**: [`/lib/project-setup/create-application/q/platform/ios`](https://docs.amplify.aws/lib/project-setup/create-application/q/platform/ios)

**Feedback**:

Please update your docs. Most of the docs are old and none of the AWSAmplify stuff works now.

**Comment by palpatim** [comment]
@azamsharp Which parts in particular are you finding issues with? What is the "AWSAmplify" stuff you're referring to?
