### ISSUE TITLE
Suggestion: Provide detailed "under the hood" documentation about the authentication libraries

### ISSUE THREAD

**Issue by gomesp** [aws-amplify/docs#3165]
**Is your feature request related to a problem? Please describe.**

For additional clarity, it would be great to expand the documentation for the authentication libraries. The current state explains what they do from an consumer's perspective, but not how it is implemented. The source code is obviously available, but it is not as accessible as a write-up.

**Describe the solution you'd like**

A description of how the authentication libraries work together, why were they composed like that (i.e. what were the design decisions), what happens in the clients when they are in use. Even if just some diagrams were available it would be fantastic already.

**Describe alternatives you've considered**

Reading the source code is the only existing alternative. 

**Additional context**

**Comment by medelman17** [comment]
Agree. The team is aligned. We're in the process of evaluating existing documentation and making improvements. Auth and its particularities is on our radar. 

In light of the above, I'm going to close this issue, but, rest assured, it's not gone unnoticed. If there are specific bits you would have us prioritize, feel free to open up new issues or reach out directly. 

You can find me on Twitter -> https://twitter.com/edelman215

**Comment by gomesp** [comment]
Thanks for taking the time to respond @medelman17. Looking forward to the documentation improvements that the team is planning.
