### ISSUE TITLE
[Feedback]FEEDBACK_TITLE_HERE

### ISSUE THREAD

**Issue by pacsoft** [aws-amplify/docs#3167]
**Page**: [`/ui/auth/select-mfa-type/q/framework/react`](https://docs.amplify.aws/ui/auth/select-mfa-type/q/framework/react)

**Feedback**:

The Documents for view do not exist. Trying to figure out 

<amplify-select-mfa-type :MFATypes="mfaTypes" :authData="user"></amplify-select-mfa-type>

I get "Less than two MFA types available" just spinning my wheels with absolutely no clue how to figure this out.   There's a full example for react but not for vue is the property name different? WTF? There's not link to the Interfaces either

**Comment by medelman17** [comment]
Hi @pacsoft -- we need more detail / context to address the issue you raise. I'm going to close this issue for now, but feel free to reopen if you're still running into trouble.
