### ISSUE TITLE
Sorry team. just 2 words from me - "nothing works" as documented

### ISSUE THREAD

**Issue by kollyhood** [aws-amplify/docs#3169]
**Page**: [`/start/q/integration/android`](https://docs.amplify.aws/start/q/integration/android?sc_icampaign=android-start&sc_ichannel=docs-home)

**Feedback**:

**Comment by medelman17** [comment]
Hi! Sorry to hear the above. Can you be a bit more specific about where/how we can improve? We're 💯 open to feedback, but, without more context, hard to know where to best begin. A good start would be to describe any specific pain points you encountered.
