### ISSUE TITLE
[missing-page]

### ISSUE THREAD

**Issue by basavarajph** [aws-amplify/docs#3170]
**Page**: [`https://docs.amplify.aws/lib/auth/social/q/pla%20tform/js

Getting 404 error when I try to open 
https://docs.amplify.aws/lib/auth/social/q/platform/js#setup-your-auth-provider

I was trying to do below thing
In terminal.
amplify update auth
Please note that certain attributes may not be overwritten if you choose to use defaults settings.
Using service: Cognito, provided by: awscloudformation
 What do you want to do? Update OAuth social providers
 Select the identity providers you want to configure for your user pool: Login With Amazon
  
 You've opted to allow users to authenticate via Amazon.  If you haven't already, you'll need to create an Amazon App ID. Head to https://docs.amplify.aws/lib/auth/social/q/pla
tform/js#setup-your-auth-provider to learn more.

**Comment by medelman17** [comment]
Can you try again? I can't reproduce. Could be that you caught a cache invalidation after redeployment of the site at exactly the wrong time.
