### ISSUE TITLE
[Feedback] Connecting an iOS app to an existing AppSync backend

### ISSUE THREAD

**Issue by Tulakshana** [aws-amplify/docs#3172]
**Page**: [`/start/q/integration/ios`](https://docs.amplify.aws/start/q/integration/ios)

**Feedback**:

Hello folks!
The company I'm working for has a web app built using AppSync and I'm trying to connect the iOS app to the same. I was following https://docs.amplify.aws/start/q/integration/ios but it doesn't look like it covers my scenario.

**Comment by palpatim** [comment]
Hi @Tulakshana 

Please see if these resources give you better help:

- AppSync Use existing AWS resources: https://docs.amplify.aws/lib/graphqlapi/existing-resources/q/platform/ios
- General Use existing AWS resources: https://docs.amplify.aws/lib/project-setup/use-existing-resources/q/platform/ios

If you're still having trouble finding the info you need, please add more details here--what are you trying to accomplish exactly?

**Comment by Tulakshana** [comment]
@palpatim thank you very much. I will have a look.
