### ISSUE TITLE
Something Works for sure and it is good enough for me

### ISSUE THREAD

**Issue by kollyhood** [aws-amplify/docs#3174]
**Page**: [`/lib/q/platform/android`](https://docs.amplify.aws/lib/q/platform/android)

**Feedback

My apologies for dropping a bad comment, It was a reflection of my frustration. I did not even realize that the feedback is driven through github.  I will try to locate and remove the comment

Finally what worked for me is the approach to build application from front-end to back end, my front end is android and i am basically working on a data capture application and so i created the app as described in this link. My backend has 2 parts 1) grapghl 2) REST API and so far it is responding well.

What did not work in the past was an approach from the Amplify Admin UI. I tried few times and junked few amplify apps in the process. maybe I did not do enough of reading. Even today the graphql models built through the front end are not getting generated through the Amplify Admin UI. I do not want to dig anymore, as i need to cover some distance in my own app domain. 

However this link was an absolute rescue - https://docs.amplify.aws/lib/project-setup/prereq/q/platform/android

Many thanks to the team for providing this.

**Comment by mauerbac** [comment]
Hey @kollyhood - thanks for providing this feedback. We will be re-thinking part of this content. Will close this issue. If you have specific feedback please open a new issue.
