### ISSUE TITLE
IoT Pub/Sub only first cognito user can work

### ISSUE THREAD

**Issue by josh-chai** [aws-amplify/docs#319]
**Describe the bug**
Develop on the Swift
When using AWSMobileClient to connect IoT Pub/Sub/Shadow, only the first cognito user can success, but second and more new user both can't connecting IoT.

I have use amplify js SDK on the web frontend, try the same parameters, Cognito User Pool, Idp, Idp Auth Role, IoT. That's all success. so I check my settings was right

**To Reproduce**
1. Sign up first user(in the User pool is first user)
2. Use AWSMobileClient to connect IoT is success
3. Sign up second user or more new user
4. Use AWSMobileClient to connect IoT is failed

**Expected behavior**
All user can connect to IoT

**Screenshots**
AWSMobileClient response connect error status

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: iOS 12
 - Version AWSMobileClient 2.7.3 AWSIoT 2.7.4

**Comment by desokroshan** [comment]
We are tracking this in [aws-sdk-ios repo Issue#1149](https://github.com/aws-amplify/aws-sdk-ios/issues/1149).

**Comment by muellerfr** [comment]
Closing this issue since we're tracking the issue in the iOS repo.
