### ISSUE TITLE
[Feedback]Error with amplify push

### ISSUE THREAD

**Issue by firatn** [aws-amplify/docs#3190]
**Page**: [`/start/getting-started/data-model/q/integration/next`](https://docs.amplify.aws/start/getting-started/data-model/q/integration/next)

**Feedback**:

@auth directive with 'userPools' provider found, but the project has no Cognito User Pools authentication provider configured.

**Comment by medelman17** [comment]
Hi, @firatn! Can you provide a bit more context/specifics regarding the above?
