### ISSUE TITLE
[Feedback]Improve documentation to reflect how to return CORS headers

### ISSUE THREAD

**Issue by etiennemunnich** [aws-amplify/docs#3204]
**Page**: [`/lib/restapi/getting-started/q/platform/js`](https://docs.amplify.aws/lib/restapi/getting-started/q/platform/js)

**Feedback**: 

Please add how one can return CORS headers, particularly when using Lambda.

**Comment by etiennemunnich** [comment]
Particularly import to provide examples for the GET using Amplify API:
 - https://docs.amplify.aws/lib/restapi/fetch/q/platform/js#accessing-query-parameters--body-in-lambda-proxy-function
 - https://github.com/axios/axios#request-config

**Comment by mauerbac** [comment]
Sorry about that! This didn't have the correct label.

**Comment by josefaidt** [comment]
Hey folks :wave: CORS headers are have since been added to all function templates as comments. When making requests using the `API` module it is not necessary to include CORS headers.

```js
/**
 * @type {import('@types/aws-lambda').APIGatewayProxyHandler}
 */
exports.handler = async (event) => {
    console.log(`EVENT: ${JSON.stringify(event)}`);
    return {
        statusCode: 200,
    //  Uncomment below to enable CORS requests
    //  headers: {
    //      "Access-Control-Allow-Origin": "*",
    //      "Access-Control-Allow-Headers": "*"
    //  }, 
        body: JSON.stringify('Hello from Lambda!'),
    };
};
```

Closing issue
