### ISSUE TITLE
[Feedback]Update or create another "migration lambda version page" to newer runtimes

### ISSUE THREAD

**Issue by iwilliam317** [aws-amplify/docs#3230]
**Page**: [`/cli/migration/lambda-node-version-update`](https://docs.amplify.aws/cli/migration/lambda-node-version-update)

**Feedback**:

Since Lambda NodeJS v10 will be deprecated in August 30, 2021, it would be helpful to update this page (highlighting any possible breaking change) for newer runtimes like Node.js v12.

**Comment by medelman17** [comment]
Thanks, @iwilliam317! I've forwarded the above to the team responsible for maintaining this documentation!
