### ISSUE TITLE
[Feedback] React Tutorial feedback

### ISSUE THREAD

**Issue by scottbentley** [aws-amplify/docs#3237]
**Page**: [`/start/getting-started/nextsteps/q/integration/react`](https://docs.amplify.aws/start/getting-started/nextsteps/q/integration/react)

**Feedback**:

In the last step where the project is published to Amplify, there is a footer note about configuring the DistributionDir correctly, but does not even give a hint as to what that parameter does. A note should be added that the DistributionDir should be the root of your React application files, e.g. "src" or if you are compiling to a "build" directory then that should be the directory.

**Comment by medelman17** [comment]
Thanks, @scottbentley! I've forwarded the above to the team responsible for updating the guide.

**Comment by jamesaucode** [comment]
Closing this issue as it looks like https://github.com/aws-amplify/docs/pull/3665 has fixed this.
