### ISSUE TITLE
configure Storage level private not working as documented?

### ISSUE THREAD

**Issue by kentbarber** [aws-amplify/docs#325]
I am calling the following code in my angular app.

Storage.configure({ level: 'private' });
Storage.get('pic/photo.jpg');

This always retrieves the photo from the public folder. 

[DEBUG] 38:02.146 AWSS3Provider - get pic/photo.jpg from public/pic/photo.jpg

However if I pass in the option into the get call directly then it works as expected and I get the private path.

[DEBUG] 41:02.567 AWSS3Provider - get pic/photo.jpg from private/us-east-1:b22de581-f007-47ee-9120-480c679b84ae/pic/photo.jpg

I tried tracing through the code for Storage.configure and it looks like this code

 var amplifyConfig = core_1.Parser.parseMobilehubConfig(config);

is placing the { level: "private" } into a Storage object instead of directly on the amplifyConfig itself. And the code in Storage.get() doesn't check this Storage object for the level, instead it gets it directly from the config itself.

But I could be missing something here since I am new to both angular and amplify. But to me it looks like data for the config is in the wrong place.

**Comment by kentbarber** [comment]
I am using it with Angular following this documentation to begin with...

https://aws-amplify.github.io/docs/js/angular

But the docs for Storage are located here...

https://aws-amplify.github.io/docs/js/storage

**Comment by kriugen** [comment]
Similar problem. I am following [Amplify React Doc](https://aws-amplify.github.io/docs/js/react)
I put `Storage.configure({ level: 'private' })` as per documentation but all pictures get saved in /public folder in the bucket with this command:

```
Storage.put(name, file).then(() => {
      this.setState({ file: name });
})
```
