### ISSUE TITLE
Instructions for Flutter 2.2.0 compatibility with Amplify

### ISSUE THREAD

**Issue by Kilo-Loco** [aws-amplify/docs#3258]
**Describe the bug**
AWS Amplify Flutter doesn't currently support null safety and it causes issues for new apps running the stable version of Flutter (2.2.0). The docs should instruct the user to add the Dart language version at the top of Amplify generated files and use the command line to run the Flutter app.

Add the following comment to the top of Amplify generated files:
```dart
// @dart=2.9
```

To run the app, enter the following into the command line:
```bash
$ flutter run --no-sound-null-safety
```

**To Reproduce**
1. Create a new Flutter app (version 2.2.0)
2. Add Amplify dependencies
3. Import one of the dependencies into the main.dart file
4. Attempt to build the app.

**Expected behavior**
The app compiles and null safety can be used with the Amplify Libraries

**Desktop (please complete the following information):**
 - OS: Flutter (iOS & Android)
 - Version: 0.1.5

**Additional context**
The error logs currently look like this:
```
Launching lib/main.dart on iPhone 11 in debug mode...
lib/main.dart:1
Xcode build done.                                           11.1s
Failed to build iOS app
Error output from Xcode build:
↳
    objc[91184]: Class AMSupportURLConnectionDelegate is implemented in both ?? (0x1fcb40188) and ?? (0x1166842b8). One of the two will be used. Which one is undefined.
    objc[91184]: Class AMSupportURLSession is implemented in both ?? (0x1fcb401d8) and ?? (0x116684308). One of the two will be used. Which one is undefined.
    ** BUILD FAILED **
Xcode's output:
↳
    Error: Cannot run with sound null safety, because the following dependencies
    don't support null safety:
- package:amplify_flutter
- package:amplify_datastore
- package:amplify_core
- package:amplify_storage_plugin_interface
- package:amplify_auth_plugin_interface
- package:amplify_analytics_plugin_interface
- package:amplify_datastore_plugin_interface
- package:amplify_api_plugin_interface
- package:date_time_format
    For solutions, see https://dart.dev/go/unsound-null-safety
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete
Could not build the application for the simulator.
Error launching application on iPhone 11.
Exited (sigterm)
```

**Comment by offlineprogrammer** [comment]
You need to disable null safety check the instruction [here](https://dart.dev/null-safety/unsound-null-safety#testing-or-running-mixed-version-programs)

**Comment by Kilo-Loco** [comment]
> You need to disable null safety check the instruction [here](https://dart.dev/null-safety/unsound-null-safety#testing-or-running-mixed-version-programs)

Just updated the issue of what should be included in the docs following link you provided
