### ISSUE TITLE
Missing docs on Storage metadata

### ISSUE THREAD

**Issue by Kilo-Loco** [aws-amplify/docs#3266]
**Is your feature request related to a problem? Please describe.**
Adding metadata to files during upload is only shown for the [Flutter](https://docs.amplify.aws/lib/storage/upload/q/platform/flutter) platform; but [Android](https://docs.amplify.aws/lib/storage/upload/q/platform/android), [iOS](https://docs.amplify.aws/lib/storage/upload/q/platform/ios), and [JavaScript](https://docs.amplify.aws/lib/storage/upload/q/platform/js) don't show how to include metadata with files during upload.

**Describe the solution you'd like**
The upload examples should include at least one metadata parameter to showcase the possibility to include metadata with the uploaded file. Assuming that the platform supports accessing metadata from the `Storage.download` and `Storage.list` APIs, there should be docs on accessing the metadata of downloaded files.

**Additional context**
There is also a [related issue](https://github.com/aws-amplify/amplify-flutter/issues/597) of not being able to access the metadata once uploaded.

**Comment by medelman17** [comment]
@chrisbonifacio -- can you work with @Kilo-Loco and @aws-amplify/android-team, @aws-amplify/ios-team, and @aws-amplify/amplify-js teams to get a PR in the works?
