### ISSUE TITLE
JS SDK V3 docs for consuming graphql api from lambda

### ISSUE THREAD

**Issue by apoorvmote** [aws-amplify/docs#3274]
**Describe the bug**

https://docs.amplify.aws/lib/graphqlapi/graphql-from-nodejs/q/platform/js#signing-a-request-from-lambda
The link above shows how to consume graphql api with lambda using SDK v2. But its been many months since SDK v3 has been generally available.  So I would like updated documentation for v3. The new version is very confusing.

I am using IAM authentication for lambda to have access to graphql api but its failing with error its unauthenticated. I don't want to use API Key. Instead I want to give lambda access to graphql api.

**Comment by chrisbonifacio** [comment]
@medelman17 transferred this over from js repo.

**Comment by apoorvmote** [comment]
There is an old aws support video. https://www.youtube.com/watch?v=KXyATZctkmQ

It shows signing request through postman but I want to do the same from inside lambda to make request to graphql api.

So please make video like this along with written docs.

**Comment by medelman17** [comment]
Closing as duplicative of #2920
