### ISSUE TITLE
[Feedback]Code to Post an Amplify Rest Request Won't Build

### ISSUE THREAD

**Issue by joec58** [aws-amplify/docs#3277]
**Page**: [`/lib/restapi/getting-started/q/platform/android`](https://docs.amplify.aws/lib/restapi/getting-started/q/platform/android)

**Feedback**:

In the **Make a POST Request** section of the page we are told to "_Copy and paste the following code in your application so that it runs only once when the app starts:_" **The Kotlin Coroutines (Beta)** version of the code is:
```kotlin
val request = RestOptions.builder()
    .addPath("/todo")
    .addBody("{\"name\":\"Mow the lawn\"}".toByteArray())
    .build()
try {
    val response = Amplify.API.post(request)
    Log.i("MyAmplifyApp", "POST succeeded: $response")
} catch (error: ApiException) {
    Log.e("MyAmplifyApp", "POST failed", error)
}
```
`val response = Amplify.API.post(request)` doesn't compile because neither of the declared signatures for the `post` function have only one argument.
The build error is:
```
None of the following functions can be called with the arguments supplied:
public open fun post(p0: RestOptions, p1: Consumer<RestResponse!>, p2: Consumer<ApiException!>): RestOperation? defined in com.amplifyframework.api.ApiCategory
public open fun post(p0: String, p1: RestOptions, p2: Consumer<RestResponse!>, p3: Consumer<ApiException!>): RestOperation? defined in com.amplifyframework.api.ApiCategory
```

**Comment by medelman17** [comment]
Thanks, @joec58! I've forwarded the above to the Android team.

**Comment by raphkim** [comment]
https://docs.amplify.aws/lib/project-setup/coroutines/q/platform/android

[Please ensure that you have imported the correct version of Amplify!](https://docs.amplify.aws/lib/project-setup/coroutines/q/platform/android)

```
import com.amplifyframework.kotlin.core.Amplify
```
