### ISSUE TITLE
[Feedback][Authentication] Regression of Quality of Documentation

### ISSUE THREAD

**Issue by laurenzfg** [aws-amplify/docs#3278]
**Describe the bug**
Comparing the current AWS Amplify Documentation to an old version (cf this [fork](https://haverchuck.github.io/docs/js/authentication)), I believe the quality has worsened.

The old documentation had:

- more example code for using auth with an own UI
- great examples regarding the Cognito Hosted UI. The current documentation recommends to call `Auth.federatedSignIn()` to send the user to the Hosted UI, which feels like a hack to me. To me, a first day user of Amplify, `Auth.federatedSignIn()` seems to be used **only** to deal with Federated Identities directly. Changing the windows URL to the Hosted UI like suggested in the old documentation seems to be more clear to me. In _Advanced workflows_ you explicitly advise against calling this function.

**Comment by laurenzfg** [comment]
Sure! You can find my email on my GH profile.

**Comment by medelman17** [comment]
Awesome! I will make sure to follow up next week. As noted, the feedback is duly noted. That said, I'm going to close this issue; we can open up more specific/actionable bits that arise our of our discussion.
