### ISSUE TITLE
[Guide] Persisting data outside of DataStore (ie. AWS Lambda) when using DataStore

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/docs#3292]
**Is your feature request related to a problem? Please describe.**
I'd like to persist data to DynamoDB and have it synced to my apps using DataStore. To achieve this I have to call the AppSync endpoint to ensure the subscriptions are triggered for the DataStore clients. To call the AppSync endpoint, I can enable additional auth models like IAM and perform the request from an AWS Lambda. 

**Describe the solution you'd like**
1. Advanced workflow docs under DataStore or under Guides
2. How to set up multi auth to IAM
3. How to set up AWS Lambda with the correct dependencies (AppSync SDK)
4. How to make a call to the AppSync backend
5. Based on the call, what to put in the GraphQL document to make sure DataStore clients will receive the subscription successfully. For example, if it is just a raw GraphQL document, list which fields are required (_version, deleted, createdAt, updatedAt, etc)
6. How to test this and verify data is received by the apps sucessfully. This entire guide is probably going to need a pre-requisted such as getting started with DataStore and the Todo schema

**Other considerations**

- custom mutation resolver 

**Related**
- https://docs.amplify.aws/lib/datastore/how-it-works/q/platform/ios#sync-data-to-cloud
- https://docs.amplify.aws/guides/functions/graphql-from-lambda/q/platform/ios

**Comment by medelman17** [comment]
I would certainly be open to a PR regarding the above if you have it in you. Otherwise, this is probably a `won't fix` for the time-being.

**Comment by lawmicha** [comment]
what's the criteria for `won't fix`? perhaps this wasn't the right place to put this

**Comment by medelman17** [comment]
While I love where your head is at and I'm 💯 going to add this to our backlog, it's an epic and we're struggling to keep up as it is. So, in this case, I don't see anyone being able to take up this work within a reasonable timeframe on our end--hence the "won't fix for the time being" in the absence of an inside/outside PR and someone to Sherpa it through review, etc-- just playin it straight with ya. :-)
