### ISSUE TITLE
Add official workshops to the docs

### ISSUE THREAD

**Issue by mtliendo** [aws-amplify/docs#3303]
**Is your feature request related to a problem? Please describe.**
no.

**Describe the solution you'd like**
I would like to have a tab added to the Amplify docs where folks can go through a guided set of workshops.

**Describe alternatives you've considered**
Alternatively, the Amplify team could own a separate domain ie _amplifyworkshops.com_ where folks could go, but this adds to the growing number of sites one would have to bookmark (cc the amplify admin-ui site)

**Additional context**

This request takes a page from [Eric Johnson](https://twitter.com/edjgeek) and the folks at Serverless Land are doing with their [learning material](https://serverlessland.com/learn).

This is sort of implemented by the [amplify community page](https://amplify.aws/community/resources), though I'm proposing migrating high-quality workshops and guides over to the official docs.

### Ownership

In conjunction with the Amplify team and the community, I envision the Amplify Developer Advocates having a role in what content is approved and updating content to ensure it's up to date.

**Comment by markramrattan** [comment]
Sorry, late to the party. Not sure why there isn't others providing feedback on this. I think this is needed. Many different ways of comprehension. For me, official workshops to the docs is great mechanism to up-skill on getting the results we seek through amplify. Another domain to host the workshops, I wouldn't go that route. There is so much to keep a track of (look how late I am to this post, lol), anything to simplify and increase speed (workshop tab) would be my suggestion. Maybe even a rating / feedback system on the workshops too. Those that drop below 3/5 get dropped after 90 days (vice versa).
