### ISSUE TITLE
[Feedback] Amazon Location Service guide - brittle

### ISSUE THREAD

**Issue by cunneen** [aws-amplify/docs#3318]
**Page**: [`/guides/location-service/setting-up-your-app/q/platform/js`](https://docs.amplify.aws/guides/location-service/setting-up-your-app/q/platform/js)

**Feedback**:

• Wouldn't the instructions here (e.g. visit the console, copy the ARN, navigate to IAM console, update IAM inline policy) need to be manually performed every time a new amplify environment is created? 
• Is there a way to allow only authenticated users access?
• How can we edit the amplify yml/json files to add these policies in a more robust fashion?

**Comment by siegerts** [comment]
Hi @cunneen , thanks for raising. Closing this now since the docs have been updated to reflect use of the `geo` category with the CLI (provisioning, permissions, etc). Also, using existing resources.

https://docs.amplify.aws/cli/geo/maps/#setup-a-new-map
