### ISSUE TITLE
Annotate GraphQL schema with API_KEY

### ISSUE THREAD

**Issue by watilde** [aws-amplify/docs#3324]
**Is your feature request related to a problem? Please describe.**
Doc[(link)](https://docs.amplify.aws/console/authz/permissions#to-set-a-public-authorization-rule) shows read only schema with API_KEY as an example, but GraphQL schema with API_KEY cannot have a read only permission as it's mentioned in API docs[(link)](https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/js#using-amplify-graphql-client) in my understanding. Let me know if this is my misunderstanding.

**Describe the solution you'd like**
To replace the example with CRUD permissions and add an explanation that API with API_KEY cannot have read-only permission.

**Describe alternatives you've considered**
Use Cognito user pool auth type and keep using read only permission

**Additional context**
A developer who tries to use Amplify with Admin UI as CMS and asked me why they can do `create` graphql query even they set read only permission today. It turned out amplify doesn't seem to support read only permission for `API_KEY` type and also does not support read only permission for guest users.
![Screen Shot 2021-06-17 at 11 05 30](https://user-images.githubusercontent.com/1716463/122364167-7f225d00-cf94-11eb-8cf0-6fff8832e919.png)

**Comment by yppartyk** [comment]
Hi @watilde, can you please expand on `A developer who tries to use Amplify with Admin UI as CMS and asked me why they can do create graphql query even they set read only permission`?

Do you mean why they were able to create records in Admin UI even though they set Read-Only access with API Key? Or was the user creating records programmatically?

**Comment by offlineprogrammer** [comment]
Hey @watilde 

I am closing this issue for now as I didn't hear from you. We can reopen it if you are still facing the issue and when you details. details

Regards
Mo
