### ISSUE TITLE
Add SSE-C for Amplify's Storage.Get function

### ISSUE THREAD

**Issue by bmw46033** [aws-amplify/docs#3345]
**Is your feature request related to a problem? Please describe.**
Though Storage.Put supports SSE-C with customer provided encryption key, the Storage.Get function does not.

**Describe the solution you'd like**
Implement the following SSE-C specification:  [https://docs.aws.amazon.com/AmazonS3/latest/userguide/specifying-s3-c-encryption.html] for the GetObjectCommand.

**Describe alternatives you've considered**

S3 AWS-SDK

**Additional context**

**Comment by bmw46033** [comment]
I cloned this project and made a change locally and linked my project to it.
The following change in AWSS3Provider.ts allows for me to Get a document that was Put with SSE-C.

Can this be tested and eventually worked to production?

Thank you.

	/**
	 * Get a presigned URL of the file or the object data when download:true
	 *
	 * @param {string} key - key of the object
	 * @param {Object} [config] - { level : private|protected|public, download: true|false }
	 * @return - A promise resolves to Amazon S3 presigned URL on success
	 */
	public async get(key: string, config?): Promise<string | Object> {
		const credentialsOK = await this._ensureCredentials();
		if (!credentialsOK) {
			return Promise.reject(StorageErrorStrings.NO_CREDENTIALS);
		}

		const opt = Object.assign({}, this._config, config);
		const {
			bucket,
			download,
			cacheControl,
			contentDisposition,
			contentEncoding,
			contentLanguage,
			contentType,
			expires,
			track,
		} = opt;
		const {
			serverSideEncryption,
			SSECustomerAlgorithm,
			SSECustomerKey,
			SSECustomerKeyMD5,
			SSEKMSKeyId,
		} = opt;

		const prefix = this._prefix(opt);
		const final_key = prefix + key;
		const s3 = this._createNewS3Client(opt);
		logger.debug('get ' + key + ' from ' + final_key);

		const params: any = {
			Bucket: bucket,
			Key: final_key,
		};

		// See: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getObject-property
		if (cacheControl) params.ResponseCacheControl = cacheControl;
		if (contentDisposition)
			params.ResponseContentDisposition = contentDisposition;
		if (contentEncoding) params.ResponseContentEncoding = contentEncoding;
		if (contentLanguage) params.ResponseContentLanguage = contentLanguage;
		if (contentType) params.ResponseContentType = contentType;

		if (serverSideEncryption) {
			params.ServerSideEncryption = serverSideEncryption;
			if (SSEKMSKeyId) {
				params.SSEKMSKeyId = SSEKMSKeyId;
			}
		}
		if (SSECustomerAlgorithm) {
			params.SSECustomerAlgorithm = SSECustomerAlgorithm;
		}
		if (SSECustomerKey) {
			params.SSECustomerKey = SSECustomerKey;
		}
		if (SSECustomerKeyMD5) {
			params.SSECustomerKeyMD5 = SSECustomerKeyMD5;
		}

		if (download === true) {
			const getObjectCommand = new GetObjectCommand(params);
			try {
				const response = await s3.send(getObjectCommand);
				dispatchStorageEvent(
					track,
					'download',
					{ method: 'get', result: 'success' },
					{
						fileSize: Number(response.Body['size'] || response.Body['length']),
					},
					`Download success for ${key}`
				);
				return response;
			} catch (error) {
				dispatchStorageEvent(
					track,
					'download',
					{
						method: 'get',
						result: 'failed',
					},
					null,
					`Download failed with ${error.message}`
				);
				throw error;
			}
		}

		params.Expires = expires || 900; // Default is 15 mins as defined in V2 AWS SDK

		try {
			const signer = new S3RequestPresigner({ ...s3.config });
			const request = await createRequest(s3, new GetObjectCommand(params));
			const url = formatUrl(
				(await signer.presign(request, { expiresIn: params.Expires })) as any
			);
			dispatchStorageEvent(
				track,
				'getSignedUrl',
				{ method: 'get', result: 'success' },
				null,
				`Signed URL: ${url}`
			);
			return url;
		} catch (error) {
			logger.warn('get signed url error', error);
			dispatchStorageEvent(
				track,
				'getSignedUrl',
				{ method: 'get', result: 'failed' },
				null,
				`Could not get a signed URL for ${key}`
			);
			throw error;
		}
	}

**Comment by jamesaucode** [comment]
Closing this as this is now supported via https://github.com/aws-amplify/amplify-js/pull/8380
