### ISSUE TITLE
[Feedback]Prerequisites

### ISSUE THREAD

**Issue by rajinder-yadav** [aws-amplify/docs#3353]
**Page**: [`/start/getting-started/installation/q/integration/js`](https://docs.amplify.aws/start/getting-started/installation/q/integration/js)

**Feedback**:

Would be nice to show a few of amplify commands, of a link to the set of commands, such as listing, deleting, updating a aws-amplify profile. Viewing  profile configuration setting and finally the location these is saved, like: ~/.aws/

**Comment by medelman17** [comment]
Hi, @rajinder-yadav, I think the documentation you are looking for lives here: https://docs.amplify.aws/cli/usage/iam-roles-mfa 

If that doesn't suffice, let me know!

**Comment by rajinder-yadav** [comment]
Thanks @medelman17, could you add this link with a mention in that page, I think that would help.
