### ISSUE TITLE
[Feedback] Add Point in Time recovery for GraphQL to documentation page

### ISSUE THREAD

**Issue by gitandrewk** [aws-amplify/docs#3360]
**Page**: [`/cli/graphql-transformer/config-params`](https://docs.amplify.aws/cli/graphql-transformer/config-params)

**Feedback**:
Hello - I was trying to look up how to enable Point in Time recovery for my GraphQL API, but did not see anything on the official documentation page. 

However, I was able to find a couple GitHub issues where this was answered:
https://github.com/aws-amplify/amplify-cli/issues/4163
https://github.com/aws-amplify/amplify-cli/issues/2186

Would be nice to have this documented. 

Thank you

**Comment by siegerts** [comment]
Hi @gitandrewk, closing as this is now in the docs - https://docs.amplify.aws/cli-legacy/graphql-transformer/config-params/#dynamodbenablepointintimerecovery.
