### ISSUE TITLE
Analytics "Custom Plugin" Documentation Outdated

### ISSUE THREAD

**Issue by medelman17** [aws-amplify/docs#3363]
**Describe the bug**

The `Using a Custom Plugin` section of the JS Analytics documentation is no longer accurate; Amplify no longer exports a `AnalyticsProvider` class to extend. 

**To Reproduce**

1. Go to https://docs.amplify.aws/lib/analytics/getting-started/q/platform/js#using-a-custom-plugin

**Screenshots**
<img width="562" alt="Screen Shot 2021-06-30 at 9 51 22 AM" src="https://user-images.githubusercontent.com/14793389/123972334-c04d4080-d988-11eb-9a8c-60bf6aaef56b.png">

**Comment by sammartinez** [comment]
Thanks for cutting this issue to us! We have resolved this issue with performing a bug fix and release on the Amplify JavaScript repo. This code snippet works as intended now. Please let us know if you are still experiencing this.
