### ISSUE TITLE
[Feedback]logs for push operation

### ISSUE THREAD

**Issue by rajinder-yadav** [aws-amplify/docs#3375]
**Page**: [`/start/getting-started/data-model/q/integration/angular`](https://docs.amplify.aws/start/getting-started/data-model/q/integration/angular)

**Feedback**:

After I type  `amplify push`, I see a bunch of output in the console, are these message getting saved to a log file? if so how can I see them later. 

Also how can I view all the resources the push command created in my AWS account, is there a amplify command for this? I rather not log into the AWS console. Which could be confusing if there are multiple projects in my AWS account/

**Comment by siegerts** [comment]
Hi @rajinder-yadav, thanks for the question!

You can see the status/diff of your changes with the `amplify status` and `amplify status --verbose` command using the Amplify CLI.  Additionally, logs can be found in the `~/.amplify/logs/amplify-cli-<issue-date>.log` directory.

For builds in the Amplify Console, you can view the build history `https://console.aws.amazon.com/amplify/home?region=<region>#/<app-id>/<env>/history`.

Hope that this helps!

**Comment by charlieforward9** [comment]
@siegerts I am trying to find a trace of an unknown `amplify push` that was made which reverted our schema to a previous version. None of the team members are aware of making a push so this is appearing to be a security vulnerability that we need to get to the bottom of asap.

> For builds in the Amplify Console, you can view the build history https://console.aws.amazon.com/amplify/home?region=<region>#/<app-id>/<env>/history.

Following this link, I am redirected to `https://us-east-2.console.aws.amazon.com/amplify/apps`. Looking in the cloudformation logs, I am unable to determine much more than THAT a push was `user initiated`. 

Do you have any recommendations for: 
A) Understanding how/when/from where a push was made
B) Restricting push access to a specific user?

Thank you in advance.
