### ISSUE TITLE
[Feedback]Tons of errors in Angular 12 app

### ISSUE THREAD

**Issue by rajinder-yadav** [aws-amplify/docs#3376]
**Page**: [`/start/getting-started/data-model/q/integration/angular`](https://docs.amplify.aws/start/getting-started/data-model/q/integration/angular)

**Feedback**:

Here are the following errors I am seeing initially, I attempted to fix some.

1. Need to move the code from onInit into the constructor.
2. Rrename file, 'aws-exports.js' to 'aws-exports.ts'
3. Assign empty array to class field `restaurants: Array<Restaurant> = [];`

```ts
Error: src/app/app.component.ts:13:10 - error TS2564: Property 'createForm' has no initializer and is not definitely assigned in the constructor.

13   public createForm: FormGroup;
            ~~~~~~~~~~


Error: src/app/app.component.ts:15:3 - error TS2564: Property 'restaurants' has no initializer and is not definitely assigned in the constructor.

15   restaurants: Array<Restaurant>;
     ~~~~~~~~~~~


Error: src/app/app.component.ts:16:3 - error TS7008: Member 'subscription' implicitly has an 'any' type.

16   subscription;
     ~~~~~~~~~~~~


Error: src/app/app.component.ts:29:7 - error TS2322: Type '({ __typename: "Restaurant"; id: string; name: string; description: string; city: string; createdAt: string; updatedAt: string; } | null)[] | null | undefined' is not assignable to type 'Restaurant[]'.
  Type 'undefined' is not assignable to type 'Restaurant[]'.

29       this.restaurants = event.items;
         ~~~~~~~~~~~~~~~~

Error: src/main.ts:5:25 - error TS7016: Could not find a declaration file for module './aws-exports'. '/home/yadav/dev/tmp/amplify-app/src/aws-exports.js' implicitly has an 'any' type.

5 import aws_exports from "./aws-exports";
                          ~~~~~~~~~~~~~~~
```

After making these changes, there is still one more error I am unable to fix at the moment.

```sh

Error: src/app/app.component.ts:26:7 - error TS2322: Type '({ __typename: "Restaurant"; id: string; name: string; description: string; city: string; createdAt: string; updatedAt: string; } | null)[]' is not assignable to type 'Restaurant[]'.
  Type '{ __typename: "Restaurant"; id: string; name: string; description: string; city: string; createdAt: string; updatedAt: string; } | null' is not assignable to type 'Restaurant'.
    Type 'null' is not assignable to type 'Restaurant'.

26       this.restaurants = event.items;
         ~~~~~~~~~~~~~~~~
```

**Comment by rajinder-yadav** [comment]
Also the type for Restaurant should be something like this, 

```ts
export type Restaurant = {
    __typename: "Restaurant";
    id: string;
    name: string;
    description: string;
    city: string;
    createdAt: string;
    updatedAt: string;
};
```

The one provided has commas and is missing fields. This still is not fixing the last error I am seeing.

**Comment by rajinder-yadav** [comment]
Here is the final fix in file `app.components.ts`, a typecast is required.

```ts
    this.api.ListRestaurants().then(event =>  {
      this.restaurants = (event.items as Array<Restaurant>);
    });
```

Please update the doc and have someone go through everything for Angular 12, the text is out of date and it's really frustrating to learn like this.

**Comment by rajinder-yadav** [comment]
One more **important** thing, one should always unsubscribe from a stream, otherwise this will lead to resource leaks in a real-world application.

In file, `app.component.ts` add the following class field

```ts
  subscription: any;
```

Update the code to assign the subscription:

```ts
    this.subscription = this.api.OnCreateRestaurantListener.subscribe( (event: any) => {
      const newRestaurant = event.value.data.onCreateRestaurant;
      this.restaurants = [newRestaurant, ...this.restaurants];
    });
```

Finally add the OnDestroy method

1. Update import: `import { Component, OnDestroy } from '@angular/core';`
2. Update class definition: `export class AppComponent implements OnDestroy {`
3. Add `ngOnDestroy` method.

```ts
  ngOnDestroy() {
    if(this.subscription) {
      this.subscription.unsubscribe();
    }
    this.subscription = null;
  }
```

Note method `OnInit` is not required as mentioned earlier (required to move code to ctor), so it should be removed.

**Comment by wlee221** [comment]
Hi @rajinder-yadav, thanks for your detailed feedback! These issues are stemming from Angular 12 enforcing Typescript strict mode by default. I opened up #3606 to provide the necessary updates to the documentation, based on your suggestions (also confirmed locally 🎉 ).

**Comment by rajinder-yadav** [comment]
Thanks @wlee221, hopefully my suggestions will help others.

**Comment by rolance** [comment]
Had to add `"skipLibCheck": true` to tsconfig.json to get things to work.
