### ISSUE TITLE
Better documentation around AppSync Subscription reconnection logic

### ISSUE THREAD

**Issue by ahansson89** [aws-amplify/docs#3377]
**Is your feature request related to a problem? Please describe.**
There is no documentation for how to resubscribe an AppSync subscription if connection failure is happening

**Describe the solution you'd like**
Ideally, I do not want to handle this myself and just let the framework handle the reconnection. 

**Describe alternatives you've considered**
Write code that handles the exponential backoff

**Additional context**
This is how I tried to do it, but I do not get a successful reconnect. Obviously there is no backoff implemented yet..
```
useEffect(() => {
    let subscription;

    const observable = API.graphql(
      graphqlOperation(onCreateChild, {
        owner: user.sub
      })
    );

    const subscriptionSettings = {
      error: e => {
        subscription.unsubscribe();
        subscription = null;
        subscription = observable.subscribe(subscriptionSettings);
        console.log("onCreateChild", JSON.stringify(e));
      },
      next: childData => {
        console.log(childData)
      }
    };

    subscription = observable.subscribe(subscriptionSettings);

    return () => {
      if (subscription) {
        console.log("unsubscribe");
        subscription.unsubscribe();
      }
    };
  }, [user.sub]);

```

What is the best way to handle this?

**Comment by renebrandel** [comment]
Hi we've added the documentation here: https://docs.amplify.aws/lib/graphqlapi/subscribe-data/q/platform/js/#connection-issues-and-automated-reconnection
