### ISSUE TITLE
[Feedback] Inaccurate Lambda Config Code Example

### ISSUE THREAD

**Issue by garethbradley** [aws-amplify/docs#3384]
**Page**: [`/guides/functions/configuring-lambda/q/platform/js`](https://docs.amplify.aws/guides/functions/configuring-lambda/q/platform/js)

**Feedback**:
Hi - just been following the information on setting the runtime and default memory for lambda functions from Amplify. The following is what's in the documentation:

```
"Resources": {
  "LambdaFunction": {
      ...
      "Runtime": "nodejs14.x",
      "MemorySize": "1024", // Memory size now set to 1024 mb
      "Layers": [],
      ...
    }
  },
}
```

The code examples suggest the Runtime and `MemorySize` params sit under the `LambdaFunction` object, which fails with a CloudFormation error `Invalid template resource property 'MemorySize'`. I believe they need to be under `Properties`...

```
"Resources": {
  "LambdaFunction": {
      "Properties": {
          ...
          "Runtime": "nodejs14.x",
          "MemorySize": "1024", // Memory size now set to 1024 mb
          "Layers": [],
          ...
       }
    }
  },
}
```

**Comment by lazpavel** [comment]
This looks to be fixed by #3386
