### ISSUE TITLE
[Docs Site] Determine "active" links with asPath instead of pathname

### ISSUE THREAD

**Issue by ericclemmons** [aws-amplify/docs#3397]
Hi! 👋 
      

When working on the Amplify UI docs, my pages are powered by `[[...slugs]].tsx`.  `pathname` returns this value, so none of `SecondaryNav` is active.

Using `asPath` correctly returned `/ui/...` strings, making `active` finally return `true` as expected.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/amplify-docs/src/components/SecondaryNav/index.tsx b/node_modules/amplify-docs/src/components/SecondaryNav/index.tsx
index 5a13939..34f4c54 100644
--- a/node_modules/amplify-docs/src/components/SecondaryNav/index.tsx
+++ b/node_modules/amplify-docs/src/components/SecondaryNav/index.tsx
@@ -16,7 +16,7 @@ import {Container} from "../Container";
 
 export default function SecondaryNav({platform, pageHasMenu}) {
   const router = useRouter();
-  const path = router.pathname;
+  const path = router.asPath;
 
   return (
     <SecondaryNavStyle id="secondary-nav">
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by mauerbac** [comment]
Do we still want to do this @jakeburden ?

**Comment by rachelnabors** [comment]
Looks like this is fixed!
