### ISSUE TITLE
[Feedback] Missing Docs re: Required Variables for Update Mutation using AppSync SDK

### ISSUE THREAD

**Issue by dn-l** [aws-amplify/docs#3408]
**Page**: [`/lib/graphqlapi/mutate-data/q/platform/js`](https://docs.amplify.aws/lib/graphqlapi/mutate-data/q/platform/js)

https://docs.amplify.aws/lib/graphqlapi/mutate-data/q/platform/js#using-aws-appsync-sdk

For the update, you need to pass a `_version` of a current object otherwise fields wouldn't be updated.

**Comment by chrisbonifacio** [comment]
Hi @dn-l 👋 thanks for raising this issue! Just wanted to note really quick that this is only necessary if you've enabled DataStore (Conflict Resolution) for your GraphQL API and still want to use `API.graphql`. I'll add a note to the page you linked regarding this.
