### ISSUE TITLE
[missing-page] iOS Push Notifications

### ISSUE THREAD

**Issue by afern247** [aws-amplify/docs#3410]
**Page**: [https://docs.amplify.aws/sdk/push-notifications/getting-started/q/platform/ios](https://docs.amplify.aws/sdk/push-notifications/getting-started/q/platform/ios)

Where is the documentation for iOS Notifications?

**Comment by medelman17** [comment]
Hi, @afern247 -- I'm confused. It looks like the page you linked above contains the documentation you're looking for. Are you having trouble accessing it?

**Comment by afern247** [comment]
Reading your comment I just went to check in Chrome and it works, it seems the website has an issue with Firefox:

[![Screen-Shot-2021-08-03-at-8-47-48-PM.png](https://i.postimg.cc/0jhyGyTq/Screen-Shot-2021-08-03-at-8-47-48-PM.png)]

I'm using Firefox version: 90.0.2 (64-bit)

Please correct the issue or at least say you are not supporting the browser, this is very misleading.

**Comment by medelman17** [comment]
I'm still having trouble reproducing this issue. Are you running any sort of ad blocking extension by chance?

**Comment by afern247** [comment]
Yep I was running uBlock Origin, deactivated it and worked. Thanks
