### ISSUE TITLE
Amplify CLI Secret Definition needs clarification

### ISSUE THREAD

**Issue by attilah** [aws-amplify/docs#3417]
**Describe the bug**

Amplify CLI Container Secret configuration needs some clarification based on the issue described here: https://github.com/aws-amplify/amplify-cli/issues/7661

Official docker compose secrets page could be linked as well to not to duplicate content.

The docs is missing the part on how to reference root level defined secrets at the container level in docker compose yaml.

**Comment by sundersc** [comment]
PR [#3951](https://github.com/aws-amplify/docs/pull/3951) updates the `docker-compose.yml` example to mention the correct secrets usage.
