### ISSUE TITLE
[Feedback] Amplify Auth (React) Instructions

### ISSUE THREAD

**Issue by lack-of-gravitas** [aws-amplify/docs#3420]
**Page**: [`/start/getting-started/auth/q/integration/react`](https://docs.amplify.aws/start/getting-started/auth/q/integration/react)

**Feedback**:

Instructions for Amplify Auth including drop in ui components for react are incomplete and bad. Random examples provided for only parts of the HOC components. NO explanation of how federated auth works or how to wire it up -- had to google an obscure github issue to realise that a <amplify-facebook-button> tag was required to add a Facebook button only then to find out it wasn't wired and a federated parameter needed to be supplied with clientid -- where is this documented? API reference docs take me to overall Amplify and not the specific impliementation in question.

**Comment by rachelnabors** [comment]
Thanks for this feedback! 

We revised and updated the [authorization docs](https://docs.amplify.aws/lib/auth/social/q/platform/js/) to address these issues. Please have a look, and let us know what we can do better!
