### ISSUE TITLE
[Feedback] Target iOS Platform

### ISSUE THREAD

**Issue by reecestart** [aws-amplify/docs#3427]
**Page**: [`/start/getting-started/setup/q/integration/flutter`](https://docs.amplify.aws/start/getting-started/setup/q/integration/flutter)

**Feedback**:

"Update target iOS platform

From your project root, navigate to the ios/ directory and modify the Podfile using a text editor of your choice and update the target iOS platform to 13.0 or higher.

platform :ios, '13.0'"

^^ re: the above. There is no Podfile in the ios/ directory. Only:

❯ ls
Flutter            Runner             Runner.xcodeproj   Runner.xcworkspace

**Comment by mauerbac** [comment]
cc @offlineprogrammer

**Comment by abdallahshaban557** [comment]
@reecestart  - are you using a windows or Mac machine when you have created your app? The POD file would get created if you have initiated your app using a Mac.

**Comment by reecestart** [comment]
@abdallahshaban557 sorry I don't have this setup again to test, this issue can be closed as I can't reproduce at this time.
