### ISSUE TITLE
Incorrect function name in aws-amplify getting started documentation for Flutter

### ISSUE THREAD

**Issue by itspersie** [aws-amplify/docs#3437]
[https://docs.amplify.aws/start/getting-started/add-api/q/integration/flutter#add-api-and-auth-plugins](url)

![screenshot](https://user-images.githubusercontent.com/56320328/127753195-e6c2d15e-2fea-4338-a48a-938ade1cfc9f.png)

**We have to add these lines in _configureAmplify() whereas in the documentation it's saying to add these in _fetchTodos()**

![Untitled](https://user-images.githubusercontent.com/56320328/127753253-83acd8da-1ba7-4ab0-b285-4dd140d7f198.png)

  // add Amplify plugins
- await Amplify.addPlugins([_dataStorePlugin]);
+ await Amplify.addPlugins([_dataStorePlugin, _apiPlugin, _authPlugin]);

**Comment by abdallahshaban557** [comment]
Issue fixed now!
