### ISSUE TITLE
Geo: upgrade MapLibre GL JS to 1.15.2

### ISSUE THREAD

**Issue by mojodna** [aws-amplify/docs#3441]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

I'd like to see the [docs for Geo](https://docs.amplify.aws/lib/geo/maps/q/platform/js) reference the current version of MapLibre GL JS (1.15.2 at the moment, vs. 1.14.0 as documented).

**Describe alternatives you've considered**

N/a

**Additional context**

1.15.x contains additional stabilization changes after the Mapbox GL JS fork.

**Comment by mauerbac** [comment]
This has been updated!

**Comment by thaddmt** [comment]
Just adding PR here for posterity https://github.com/aws-amplify/docs/commit/8ae1e9c50e4830b99d360c2c9e43ab38fdec76b7
