### ISSUE TITLE
Clarify DataStore.start() uses

### ISSUE THREAD

**Issue by palpatim** [aws-amplify/docs#3445]
**Is your feature request related to a problem? Please describe.**
A customer was confused in a [Discord conversation](https://discord.com/channels/705853757799399426/707328996995760179/871754663958028309) about why their DataStore didn't start syncing until performing a query. I explained that it was necessary to call `DataStore.start()` first, and the customer pointed out that the docs don't call this out.

**Describe the solution you'd like**
We should clarify the situations in which `DataStore.start()` should be called. Although we currently document this behavior in the [`start()` method docs](https://docs.amplify.aws/lib/datastore/other-methods/q/platform/ios#start), we should also document it in the [sync discussion](https://docs.amplify.aws/lib/datastore/sync/q/platform/ios), so it's clear that sync won't start until something triggers it.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by abdallahshaban557** [comment]
Added clarifications about when Datastore starts syncing. Closing this issue, @palpatim please feel free to open it if you feel like the added description needs any changes.
