### ISSUE TITLE
[Feedback] add `interactions` documentation to CLI docs

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/docs#3446]
**Is your feature request related to a problem? Please describe.**

The `interactions` category is currently documented under Libraries > JS, however this is not also documented under the CLI section, making it difficult to find when searching under the context of using this category with the CLI.

**Describe the solution you'd like**

Add documentation similar to the ["Getting Started" section of the Libraries docs](https://docs.amplify.aws/lib/interactions/getting-started/q/platform/js) in CLI with notes to known limitations such as no current support for [Context Management (late 2020 release)](https://aws.amazon.com/about-aws/whats-new/2020/11/announcing-context-management-on-amazon-lex/) and [Amazon Lex V2 (early 2021 release)](https://aws.amazon.com/about-aws/whats-new/2021/01/launching-amazon-lex-v2-console-apis-improved-bot-building-experience/).

**Describe alternatives you've considered**

Placeholder category page for `interactions` linking to the Libraries' documentation for `interactions`

**Additional context**

**Comment by rachelnabors** [comment]
We're planning to merge CLI and Studio docs with Guides docs in the future, thus solving this problem. Will close when we get to integrations

**Comment by josefaidt** [comment]
this is no longer applicable, closing
