### ISSUE TITLE
[Feedback] Vue 3 requires npm install aws-amplify @aws-amplify/ui-components instead of npm install aws-amplify @aws-amplify/ui-vue

### ISSUE THREAD

**Issue by mangozango** [aws-amplify/docs#3454]
**Page**: [`/lib/auth/getting-started/q/platform/js`](https://docs.amplify.aws/lib/auth/getting-started/q/platform/js#create-authentication-service)

**Feedback**:

I believe the following error can be easily resolved with the command ```npm install aws-amplify @aws-amplify/ui-components instead of npm install aws-amplify @aws-amplify/ui-vue```.  It is a matter of the Amplify Get Started guide being out of date.    See below for the full solution to this issue (there is a bit more outdated code highlighted and then resolved):

**The following code (found here, https://docs.amplify.aws/lib/auth/getting-started/q/platform/js#create-authentication-service) yields this error in the browser:**

**Error:** ```Uncaught Error: No Vue 2 export was found. For later versions of Vue, please use `@aws-amplify/ui-components` according to this guide: https://docs.amplify.aws/start/getting-started/setup/q/integration/vue.```:

**Code:**
```javascript
import { createApp } from 'vue';
import App from './App.vue';
import router from './router';
// eslint-disable-next-line no-unused-vars
import Amplify, { Auth } from 'aws-amplify';
import awsconfig from './aws-exports';
import '@aws-amplify/ui-vue';
Amplify.configure(awsconfig);

createApp(App).use(router).mount('#app');
```

**The following code fixes the error (found here, https://aws.amazon.com/blogs/mobile/amplify-javascript-releases-support-for-vue-3/):**

```javascript
import { createApp } from 'vue';
import App from './App.vue';
import router from './router';
import Amplify from 'aws-amplify';
import awsconfig from './aws-exports';
import {
  applyPolyfills,
  defineCustomElements, 
} from '@aws-amplify/ui-components/loader';

applyPolyfills().then(() => {
  defineCustomElements(window);
});
Amplify.configure(awsconfig);

createApp(App).use(router).mount('#app');

```

**Comment by ErikCH** [comment]
Hi @mangozango ! 

Thanks for the feedback. Yes, you're right the getting started on the Libraries page is for Vue 2 not Vue 3, if you're wanting to use the UI components library. We'll get that updated.

In the meantime there is documentation on using Vue 3 on the UI Components page [here](https://docs.amplify.aws/ui/q/framework/vue/). Just make sure you select the `Vue 3` tab.

It's also worth mentioning a brand new library for UI components and [Vue 3](https://github.com/aws-amplify/amplify-ui) will have a preview release in early October.
