### ISSUE TITLE
[Feedback]Having version number in the documentation would greatly help

### ISSUE THREAD

**Issue by bilal-grotabyte** [aws-amplify/docs#3459]
**Page**: [`/lib/interactions/getting-started/q/platform/js`](https://docs.amplify.aws/lib/interactions/getting-started/q/platform/js)

**Feedback**:

Currently I am trying to work with Amazon lex but confused between Chatbot vs AmplifyChatbot tags. Not sure which one is the latest. Chatbot is not working. Thanks

**Comment by medelman17** [comment]
Thanks, @bilal-grotabyte! I'll forward this issue to the relevant team for further review.
