### ISSUE TITLE
Allow public IAM @auth on @function outside of @model

### ISSUE THREAD

**Issue by CodySwannGT** [aws-amplify/docs#3488]
This subject keeps coming up in a number of issues but there is never any resolution.

[This questions specifically](https://github.com/aws-amplify/amplify-cli/issues/2711#issuecomment-841604000)

**Comment by CodySwannGT** [comment]
Understood and good to know. Thank you. Feel free to close if you want. I wasn't sure if you wanted to leave it open for doc

**Comment by chrisbonifacio** [comment]
Closing this, added a note with the CLI warning to the docs under the [Chaining functions](https://docs.amplify.aws/cli/graphql/custom-business-logic/#chaining-functions) section of the CLI's Custom business logic page.
