### ISSUE TITLE
[missing-page]

### ISSUE THREAD

**Issue by abhijit201** [aws-amplify/docs#3494]
**Page**: [`https://docs.amplify.aws/cli/function/`](https://docs.amplify.aws/cli/function/)

**Feedback**:

**Comment by mauerbac** [comment]
Hello @abhijit201 -  can you share the steps to reproduce ? Where did you encounter this link? Thank you

**Comment by tjleing** [comment]
That URL is correctly 404'ing, the page for that content is https://docs.amplify.aws/cli/function/function/.  Also, I don't see the link you posted anywhere on the docs site currently.  If you can let us know where the link came from that would be very helpful!

**Comment by tjleing** [comment]
It seems that link came from the previous version of the docs site.  To restore backwards compatibility we've created #3514 which fixes two pages like this one -- will close once that lands.
