### ISSUE TITLE
[Documentation] Wrong description about plugin addition in the tutorial page.

### ISSUE THREAD

**Issue by chari8** [aws-amplify/docs#3495]
**Page**: [`https://docs.amplify.aws/start/getting-started/add-api/q/integration/flutter/`](https://docs.amplify.aws/start/getting-started/add-api/q/integration/flutter/)

**Feedback**:

In the second last part of [ **Add Api and Auth plugins** section ](https://docs.amplify.aws/start/getting-started/add-api/q/integration/flutter/#add-api-and-auth-plugins) , the page says 

> Add the additional plugins to Amplify in the _fetchTodos() function of the _TodosPageState class.

, where `_fetchTodos()` is supposed to be `_configureAmplify()` .

**Comment by abdallahshaban557** [comment]
This issue has now been corrected.
