### ISSUE TITLE
Example class for Managing Security Tokens is incomplete or more information need to be added.

### ISSUE THREAD

**Issue by developerjohan01** [aws-amplify/docs#35]
**Describe the bug**
In the section 
https://aws-amplify.github.io/docs/js/authentication#managing-security-tokens
that describes `class MyStorage` it is stated 

> you need to sync those items into the memory in this method

```
    // If the storage operations are async(i.e AsyncStorage)
    // Then you need to sync those items into the memory in this method
    static sync(): Promise<void>;
```
How is this supposed to be done?
You can't use _async storage_ unless you know how to do this. 
You can look for other solutions to bridge the gap between sync/async which means that you might not use the provided `sync()` method.
The general description of `class MyStorage` is straight forward.

I have found this
https://github.com/aws-amplify/amplify-js/blob/4644b432/packages/core/src/StorageHelper/reactnative.ts#L66
Would that serve as an example implementation? 
If so, then the documentation needs updating 

**Expected behavior**
A clear and concise example and description of what you are expected to do.

**Comment by max77p** [comment]
@developerjohan01 any luck with this? The amplify doc is so implement on this section. How does one actually implement static getItem(key: string): string; in react js? I am so confused

**Comment by developerjohan01** [comment]
@max77p In my case, I could use the default behaviour. 
As you probably know you don't have to implement your own storage. 

> When using Authentication with AWS Amplify, you don’t need to refresh Amazon Cognito tokens manually. The tokens are automatically refreshed by the library when necessary.

and 

>Security Tokens like IdToken or AccessToken are stored in localStorage for the browser and in AsyncStorage for React Native. 

https://aws-amplify.github.io/docs/js/authentication#managing-security-tokens
