### ISSUE TITLE
Update react-native documentation on API Graphql Client subscription

### ISSUE THREAD

**Issue by vision669** [aws-amplify/docs#350]
The documentation on react-native API graphql client subscription is incorrect for react-native. Please update. I am getting "Error No pubsub module applied for subscription". The documentation mention nothing about pobsub"

**Comment by nikhil-dabhade** [comment]
@vision669 : Can you share the page which you followed when you got the error?

**Comment by nikhil-dabhade** [comment]
@vision669 Can you confirm is this is the section which is giving you errors ? https://aws-amplify.github.io/docs/js/api#subscriptions
