### ISSUE TITLE
Next.js Example Delete Post Confusion

### ISSUE THREAD

**Issue by plusplushq** [aws-amplify/docs#3515]
**Is your feature request related to a problem? Please describe.**
The Docs for the Next.js Fullstack Example Allow any User to delete a Post, which throws an error when a user other then the post creator tries to delete it. 
**Describe the solution you'd like**
Put a conditional on the [id].js component, to only allow deleting if the currentAuthenticatedUser is the post owner.

**Additional context**
I can help w/ this if needed :)

**Comment by mauerbac** [comment]
Sorry we didn't get to this sooner. I take it this is too outdated? Please open a new issue or PR if you are interested in contributing
