### ISSUE TITLE
Overwrite resolvers needs more information

### ISSUE THREAD

**Issue by dn-l** [aws-amplify/docs#3519]
Hello,

https://docs.amplify.aws/cli/graphql-transformer/resolvers/#overwriting-resolvers needs more explanation and examples. What is `req.vtl` file? How should it look like?

**Comment by dn-l** [comment]
Would be nice to mention `build/resolvers` folder for reference

**Comment by renegoretzka** [comment]
The structure of overwriting resolvers is changed with the new version of the CLI having the GraphQL Transformer v2.

**Comment by dn-l** [comment]
I don't mind if this issue is closed, not using Amplify anymore

**Comment by rachelnabors** [comment]
Closing because this page lives in legacy docs now
