### ISSUE TITLE
Update Next.js hosting documentation

### ISSUE THREAD

**Issue by kmhalpin** [aws-amplify/docs#3520]
**Is your feature request related to a problem? Please describe.**
Next.js amplify hosting docs still refers to old version next.js of amplify hosting, amplify now supports next.js 11 and its features like the automatic image optimization

**Describe the solution you'd like**
wrong text snippet from the next.js hosting docs that needs to be updated
`
Currently, Amplify doesn't fully support Image Component and Automatic Image Optimization available in Next.js 10.
`

**Additional context**
**page:** [docs.amplify.aws/guides/hosting/nextjs/q/platform/js](https://docs.amplify.aws/guides/hosting/nextjs/q/platform/js/)
I can help if needed

**Comment by medelman17** [comment]
Thanks, @kmhalpin! I will alert the appropriate team members. That said, if you want to go ahead and take a crack at solving the above with a PR, that would be amazing!
