### ISSUE TITLE
[missing-page]

### ISSUE THREAD

**Issue by pedroherreraj** [aws-amplify/docs#3521]
**Page**: [`https://docs.amplify.aws/lib/storage/getting-started.md/q/platform/js/
**Page**: [https://docs.amplify.aws/lib/storage/configureaccess.md/q/platform/js/#customize-object-key-path

**Comment by medelman17** [comment]
Hi @pedroherreraj! Can you provide a bit more detail/context re: the issue you mean to report above? Thanks!

**Comment by pedroherreraj** [comment]
Hey! Sorry the bit information. Yes i mean that! Those links doesn't work

**Comment by siegerts** [comment]
Closing for now. Please reopen if this pops up again.
