### ISSUE TITLE
GitHub Edit Button Links to Nonexistent Resource

### ISSUE THREAD

**Issue by naufilshaikh09** [aws-amplify/docs#3523]
**Page**: [`/start`](https://docs.amplify.aws/start/?sc_icampaign=start&sc_ichannel=docs-home/q/integration/angular)

**Feedback**:

Github edit button is not working.

**Comment by medelman17** [comment]
@tjleing & @jakeburden -- I can reproduce the above by clicking the button on the following page: https://docs.amplify.aws/start/?sc_icampaign=start&sc_ichannel=docs-home/q/integration/angular 

FWIW, some of these links seem to be working as expected. See, e.g., https://docs.amplify.aws/ui/interactions/chatbot/q/framework/angular/

**Comment by jakeburden** [comment]
@tjleing I think we can address this in the upcoming PR:
https://github.com/aws-amplify/docs/pull/3512

**Comment by tjleing** [comment]
Thank you for the find @naufilshaikh09!  I will add it to #3512 -- these autogenerated pages with no markdown attached either shouldn't have an "edit this page on github" button at all, or it should link to [this page](https://github.com/aws-amplify/docs/blob/main/src/pages/ChooseFilterPage.tsx), but that's likely unhelpful to users.  Open to UI thoughts @jakeburden @medelman17
