### ISSUE TITLE
[Feedback] Push Notification Docs for Android, iOS, and Flutter AWOL? 

### ISSUE THREAD

**Issue by DavidAZimmerly** [aws-amplify/docs#3530]
**Page**: [`/lib/push-notifications/getting-started`](docs.amplify.aws/lib/push-notifications/getting-started)

**Feedback**:

no android push notification docs?

**Comment by palpatim** [comment]
Amplify for Android & iOS [do not support native push notifications](https://github.com/aws-amplify/amplify-ios/issues/662). The only push notification support Amplify currently offers is via React Native.

**Comment by DavidAZimmerly** [comment]
>Amplify for Android & iOS do not support native push notifications<https://github.com/aws-amplify/amplify-ios/issues/662>. The only push notification support Amplify currently offers is via React Native.

I already have them working on Android native via the old docs which is mostly Amplify.
https://docs.amplify.aws/sdk/push-notifications/getting-started/q/platform/android/

Are you certain they aren't supported? I certainly don't want to build something with old code and have it break and be unsupported at some point.
________________________________

**Comment by palpatim** [comment]
@DavidAZimmerly You're implementing push notification support via the AWS Mobile SDK, which is fine. My comment was related to Amplify library--Amplify does not support the Notifications category for native Android or iOS apps.

**Comment by mauerbac** [comment]
Reviewing old issues. Closing as this as a question.
