### ISSUE TITLE
[Feedback] While integrating the app .. Error Amplify plugin was not added

### ISSUE THREAD

**Issue by mcrvchalam** [aws-amplify/docs#3533]
https://docs.amplify.aws/start/getting-started/integrate/q/integration/flutter/#configure-amplify

The flutter app works till this. But after the heading manipulating Data:
after
Update the _saveTodo() function in the _AddTodoFormState class. 
step:

when I try to do :flutter run 
 I get error : 
 Amplify plugin was not added
An error occurred while configuring Amplify: AmplifyException$(message: Amplify plugin AmplifyDataStore was not added
successfully., recoverySuggestion: We currently don't have a recovery suggestion for this exception.,
underlyingException: MissingPluginException(No implementation found for method configureDataStore on channel
com.amazonaws.amplify/datastore))
An error occurred while saving Todo: AmplifyException$(message: DataStore plugin has not been added to Amplify,
recoverySuggestion: Add DataStore plugin to Amplify and call configure before calling DataStore related APIs,
underlyingException: null)

Note: I use command prompt with administrative access
I have logged in aws console and created user with administrative access also

**Comment by abdallahshaban557** [comment]
@mcrvchalam  - are you still facing this issue?

**Comment by gawshan** [comment]
Yes, problem is happening to me too

**Comment by altieres** [comment]
I had the same problem while using "default run" (desktop?!) of vscode.
Runing on iOS phone emulator solved the problem.

**Comment by juskek** [comment]
> I had the same problem while using "default run" (desktop?!) of vscode. Runing on iOS phone emulator solved the problem.

This worked for me too

**Comment by abdallahshaban557** [comment]
@altieres that is great! I am glad that solved the issue for you as well @juskek.

@gawshan  - did you try the suggestion from @altieres to fix this issue?

**Comment by abdallahshaban557** [comment]
We are closing this issue. Please inform us if you are still facing issues!

**Comment by Udayanrevergon** [comment]
Hey @abdallahshaban557  I am facing this issue when I am running it on flutter web
My code runs fine when working on android/ios Emulator 
Would really appreciate it if I could get some help

**Comment by abdallahshaban557** [comment]
Hi @Udayanrevergon  - can you please create a [Github issue](https://github.com/aws-amplify/amplify-flutter/issues/new?assignees=&labels=&projects=&template=BUG-REPORT.yaml) on this repo so that we can investigate this for you?
