### ISSUE TITLE
Timestamps for GraphQL/AppSync models

### ISSUE THREAD

**Issue by FWirtz** [aws-amplify/docs#355]
**Is your feature request related to a problem? Please describe.**
I am just playing around with the GraphQL/AppSync bit of Amplify.
When creating objects, I want to be able to have a timestamp automatically added for it.
After peaking in `build/resolvers/Mutation.createMODELNAME.request` I found out that luckily `updatedAt` and `createdAt` are added automatically.
I feel like this could/should be added/noted in the docs.

**Describe the solution you'd like**
Maybe something like:

> ## Timestamps
> Amplify supports automatic timestamps for your models. To use them, add them to your schema as such:
> ```graphql
> type MyModel @model {
>     createdAt: String
>     updatedAt: String
>     # ... other attributes
> }
> ```
> Amplify will populate these accordingly.
>

**Describe alternatives you've considered**
I don't really think taking a look at the build code and finding it yourself is a viable alternative.

**Additional context**
%

Looking forward to hear your thoughts on this.

**Comment by nikhil-dabhade** [comment]
@FWirtz : Thank you for your feedback. Can you for share the page where you think this will be apt for adding ?

**Comment by FWirtz** [comment]
@nikhil-dabhade hm yeah, good question. You go into more detail about GraphQL Schemas on the [transforms page](https://aws-amplify.github.io/docs/cli/graphql?sdk=js), but as it's not a transform it doesn't really fit in, or what would you say?

**Comment by kareemsuhail** [comment]
any updates? 
related to where you should add it I think you should create a detailed new section for graphql schemas and add timestamps to it  as @FWirtz said
