### ISSUE TITLE
[Feedback] Feature flags aren't showing up since Next.js migration

### ISSUE THREAD

**Issue by renebrandel** [aws-amplify/docs#3550]
**Page**: [`/cli/reference/feature-flags`](docs.amplify.aws/cli/reference/feature-flags/#configuration)

**Feedback**:
Since the Next.js migration, all the feature flags (at the bottom of the page) aren't shown anymore. 

Expected:
- Feature flags to be shown just as before.

**Comment by jakeburden** [comment]
Fixed in: https://github.com/aws-amplify/docs/pull/3554
