### ISSUE TITLE
[Feedback] `amplify add geo` must run after `amplify init`

### ISSUE THREAD

**Issue by mojodna** [aws-amplify/docs#3551]
**Page**: [`/lib/geo/getting-started/q/platform/[platform]`](docs.amplify.aws/lib/geo/getting-started/q/platform/js/)

**Feedback**: When starting from scratch, I need to run `amplify init`; this page does not include that step.

**Comment by TreTuna** [comment]
Thanks for this note, I added a step into the docs for running `amplify init` to the geo getting started guide here: https://github.com/aws-amplify/docs/pull/3583
