### ISSUE TITLE
Got unexpected error when scroll down the page

### ISSUE THREAD

**Issue by rishithakkar48** [aws-amplify/docs#3558]
**Page**: [`/cli/#serverless-containers`](https://docs.amplify.aws/cli/#serverless-containers)

**Feedback**:
I got an unexpected error when I scroll down. For better understanding please watch the video
video: https://www.loom.com/share/870ed5613fb240f28f0de4422a2219b1

![image](https://user-images.githubusercontent.com/76834886/131949410-948b3cec-6da4-41c9-bbb2-ab79baef38f6.png)

**Comment by DominikIlski** [comment]
Same error here https://docs.amplify.aws/cli/
when changing the url (for example while scrolling) to https://docs.amplify.aws/cli/#serverless-containers
an error appears

**Comment by tjleing** [comment]
Should be fixed by #3559; please let us know if it's still broken!
