### ISSUE TITLE
Update login with Facebook tutorial

### ISSUE THREAD

**Issue by khacminh** [aws-amplify/docs#3587]
**Describe the bug**
The setup tutorial of Login with Facebook will cause an Facebook App warning

**To Reproduce**
1. Go to Libraries -> Authentication -> Social sign-in (OAuth)
2. Choose Facebook Login
3. Scroll down to Configure Auth Category
4. At step **5. Under Website, type your user pool domain with the /oauth2/idpresponse endpoint into Site URL**.

Adding `/oauth2/idpresponse` will make the URL return response code outside 200-299, which violates the FB terms.

**Screenshots**

![Tutorial](https://user-images.githubusercontent.com/13713865/133407271-6cee7eaa-9442-4977-aab8-af6d35d27a41.png)

![FB warning](https://user-images.githubusercontent.com/13713865/133407187-d263b5f4-2a3a-4f93-b691-d8497fe50a15.png)

**Comment by nadetastic** [comment]
Hi @khacminh the docs were recently updated with this PR https://github.com/aws-amplify/docs/pull/4731

I'll go ahead and close out this issue. Let me know if you have any questions.
