### ISSUE TITLE
[Feedback] wrong query for "6 | Show all open orders within a given date range across all customers"

### ISSUE THREAD

**Issue by bombchu** [aws-amplify/docs#3588]
**Page**: [`/cli/graphql-transformer/dataaccess`](https://docs.amplify.aws/cli/graphql-transformer/dataaccess)

**Feedback**:

I think you have the wrong query type for "6 | Show all open orders within a given date range across all customers"

The one you provided won't work for the description provided. The closest example I can think of that will work is:

query MyQuery {
  listCustomers {
    items {
      ordersByStatusDate(statusDate: {between: [
        { status: "pending" date:  "2018-01-22" },
        { status: "pending", date: "2020-10-11"}
      ]}) {
        items {
          id
          amount
          date
        }
      }
    }
  }
}

I've tested this with the schema and it works.

Cheers.

**Comment by medelman17** [comment]
Hi @bombchu, thanks for the heads up! I'll make sure that this gets in front of the appropriate sets of eyes!
