### ISSUE TITLE
[Feedback] Markdown markup literal in HTML documentation

### ISSUE THREAD

**Issue by kggilmer** [aws-amplify/docs#3590]
**Page**: [`/lib/graphqlapi/authz/q/platform/[platform]`](https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/ios/#oidc)

**Feedback**:  

See the text `### AWS Lambda` in linked documentation.

Expected behavior: `### AWS Lambda` is rendered as HTML heading
Actual behavior: It's rendered as literal text

**Comment by medelman17** [comment]
Hi, @kggilmer -- I'm having trouble reproducing the issue above. Can you confirm that it still exists? Perhaps someone on the team also saw this and made a fix already?

**Comment by kggilmer** [comment]
Confirmed the issue is no longer present.  Closing!
