### ISSUE TITLE
[missing-page]

### ISSUE THREAD

**Issue by Molaire** [aws-amplify/docs#3594]
**Page**: [`https://docs.amplify.aws/lib/auth/getting-started/q/platform/js/q/platform/js/`](https://docs.amplify.aws/lib/auth/getting-started/q/platform/js/q/platform/js/)

**Feedback**:

**Comment by jakeburden** [comment]
Thanks @Molaire!

I did a sweep to fix links. Do you remember what page you found this on, and would you be willing to check it again to see if the link is fixed?

**Comment by siegerts** [comment]
Closing for now. Please open another issue if this happens again.
