### ISSUE TITLE
[Feedback]ES6 build instructions no longer work - they appear to be out of date

### ISSUE THREAD

**Issue by tweber** [aws-amplify/docs#3622]
**Page**: [`/cli/function/build-options`](https://docs.amplify.aws/cli/function/build-options)

**Feedback**:
The page gives the following sample `.babelrc` file:
```
{
  "presets": [
    [
      "env",
      {
        "exclude": ["transform-regenerator"],
        "targets": {
          "node": "10.18"
        }
      }
    ]
  ],
  "plugins": [
    "transform-async-to-generator",
    "transform-exponentiation-operator",
    "transform-object-rest-spread"
  ]
}
```
This fails with Babel 7.15 with "transform-async-to-generator not found" error. I believe it should be updated similar to the following:
```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "exclude": ["@babel/plugin-transform-regenerator"],
        "targets": {
          "node": "10.18"
        }
      }
    ]
  ],
  "plugins": [
    "@babel/plugin-transform-async-to-generator",
    "@babel/plugin-transform-exponentiation-operator",
    "@babel/plugin-proposal-object-rest-spread"
  ]
}
```

Note also the target Node version 10.18, which is old -- current Lambda functions use version 14.

**Comment by josefaidt** [comment]
Hey @tweber apologies for the delay here but I've chatted with the team and the appropriate change would require code changes from the CLI side, however in the meantime we can adopt Node ESM in Lambda's by adding a `"type": "module"` to the Lambda's `package.json` (with the caveat of [being unable to mock](https://github.com/aws-amplify/amplify-cli/issues/10432))

**Comment by ykethan** [comment]
Closing this in favor of https://github.com/aws-amplify/docs/issues/3971. Please feel free in adding additional information on your use case to the issue.
