### ISSUE TITLE
Amplify Auth calls sync function of MyStorage twice

### ISSUE THREAD

**Issue by anis-shaikh** [aws-amplify/docs#363]
**Describe the bug**
I am trying to configure custom storage for storing the cognito tokens with Amplify Auth MyStorage.
https://aws-amplify.github.io/docs/js/authentication#managing-security-tokens

**To Reproduce**
Configure the MyStorage object as mentioned in the link and override the sync method and log something in console and return some mock promise as per the contract.

**Expected behavior**
On loading the application sync method should be invoked once.

**Actual behavior**
Console log is getting print twice.
(Actually I am calling the API to get appropriate tokens and store it to my custom storage however because of this my API server is getting two calls on page load)

**Comment by powerful23** [comment]
@anis-shaikh to avoid running sync function multiple time, you can define a static member in your Storage class, say 'syncPromise' and assign this member the promise returned by the `sync` function when this function is called in the first time.

**Comment by anis-shaikh** [comment]
@powerful23 Thanks for the quick reply with solution. It help me to solve the issue.
