### ISSUE TITLE
[Feedback] Note on Social sign-in with UI document is misleading

### ISSUE THREAD

**Issue by kyleliao321** [aws-amplify/docs#3644]
Page: [/lib/auth/android/signin_web_ui/20_platform_specific_setup](https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/android/#add-response-handler)

Feedback:

`If you are using a version of Amplify 1.17.8 or above and have already declared HostedUIRedirectActivity in your manifest file, then you may skip this step.`

This sentence is not entirely correct. You still have to add response handler when you need to receive user cancel exception, since canceling action will not fire intent for HostedUIRedirectActivity. As a result, following this note to ignore adding response handler actually makes the project unable to receive user cancel exception.

I think this note needs to be removed to prevent unexpected behavior.

**Comment by div5yesh** [comment]
@kyleliao321 Thank you for pointing this out. We will update our docs.
