### ISSUE TITLE
[Feedback] Invalid Syntax in documentation.

### ISSUE THREAD

**Issue by Kumfert** [aws-amplify/docs#3674]
**Page**: [`/lib/pubsub/subunsub/q/platform/[platform]`](https://docs.amplify.aws/lib/pubsub/subunsub/q/platform/js)

**Feedback**:

The first example doesn't  pass syntax checks in TypeScript. This does: 
```javascript
    PubSub.subscribe('myTopic').subscribe(
      (data) => console.log('Message received', data),
      (error) => console.error(error),
      () => console.log('Done')
  );
```

**Comment by david-mcafee** [comment]
The issue here in the docs is that `close` should be `complete`. For instance, the following passes the TypeScript check:

```
PubSub.subscribe('myTopic').subscribe({
    next: data => console.log('Message received', data),
    error: error => console.error(error),
    complete: () => console.log('Done'),
});
```
