### ISSUE TITLE
Table formatting cut off

### ISSUE THREAD

**Issue by edwardfoyle** [aws-amplify/docs#3677]
**Describe the bug**
The table on [this page](https://docs.amplify.aws/cli/graphql-transformer/resolvers/#custom-resolvers) is too narrow and causes the description column to be cut off in places

**To Reproduce**
1. Go to https://docs.amplify.aws/cli/graphql-transformer/resolvers/#custom-resolvers
2. Scroll down to the table describing the CFN parameters
3. Observe that the "description" column is cut off

**Expected behavior**
The table is wider / description column fully visible

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 94

**Comment by evcodes** [comment]
This issue was fixed with @nilisha-jais's contribution
