### ISSUE TITLE
Create separate docs for react-native

### ISSUE THREAD

**Issue by AfanasievN** [aws-amplify/docs#370]
**Is your feature request related to a problem? Please describe.**
Yes

**Describe the solution you'd like**
I want docs be separated from react explanation of installation. Should be separate docs for react-native and react.
"This tutorial walks you through how to use AWS Amplify to build a React application. You can use a similar process with a React Native application (omitting hosting)." is not a good answer and it misleading in my integration to my react-native project, and it's not looking proffesional from aws side

**Comment by nikhil-dabhade** [comment]
@AfanasievN Sorry to hear about this.
Can you elaborate more on what part was more problematic when it came to distinguishing for both?
An example and a user case from your end would help to make this better.
