### ISSUE TITLE
[Feedback]Example doesn't work with Next v12

### ISSUE THREAD

**Issue by jcvold** [aws-amplify/docs#3717]
**Page**: [`/start/getting-started/data-model/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/data-model/q/integration/next/#api-with-server-side-rendering-ssr)

**Feedback**: Was working through this project using Next.js version 12 and when I got to the section on Server-Side Rendering, the build began throwing errors when trying to compile locally. I rolled back to version 11 and it worked fine.

**Comment by mauerbac** [comment]
hi @jcvold - At this time, Amplify doesn't support v12 of Next.
