### ISSUE TITLE
[missing-page] CLI Upgrade

### ISSUE THREAD

**Issue by OskarD** [aws-amplify/docs#3767]
**Page**: [`https://docs.amplify.aws/cli/usage/upgrade/

**Comment by OskarD** [comment]
It's available from the search function, but the link is dead

**Comment by siegerts** [comment]
Hi @OskarD , thanks for opening! The correct redirect is now in place to catch that URL change.

https://docs.amplify.aws/cli/start/workflows/#upgrade-amplify-cli
