### ISSUE TITLE
Switch create-react-native-app to Expo CLI

### ISSUE THREAD

**Issue by ijemmy** [aws-amplify/docs#377]
**Describe the bug**
It has been merged with Expo CLI >> https://github.com/react-community/create-react-native-app 

**To Reproduce**
Go to this page https://aws-amplify.github.io/docs/js/start?ref=amplify-rn-btn&platform=react-native 

**Expected behavior**
Use `expo init` instead. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Mac 10.12.6

**Smartphone (please complete the following information):**
 N/A

**Additional context**

**Comment by jordanranz** [comment]
Merged a change to update this. Thanks for submitting.
