### ISSUE TITLE
[Feedback]Add an example of how managing scoped access to resources could work in Admin UI 

### ISSUE THREAD

**Issue by lukasrossa** [aws-amplify/docs#3773]
**Page**: [`/console/adminui/access-management`](https://docs.amplify.aws/console/adminui/access-management/#to-invite-team-members-to-access-a-project)

**Feedback**:

The statement "Admin UI developers can create accounts with scoped access to resources and invite team members to join via email." is confusing. What accounts being created are we talking about here? None of the instructions further down talk about any account creation but only reference inviting users by email. Is that something different? 
Additionally, what exactly is meant by "team members with Manage only access can edit application content and users." - what is considered 'application content' - this terminology is not used anywhere. What users? Does it assume I am using cognito for Authentication and it's talking about the users stored there?

![image](https://user-images.githubusercontent.com/294971/142171389-29dc7a8e-ed74-4015-9e22-32877f900114.png)

**Comment by siegerts** [comment]
Hi @lukasrossa, this information has been updated in the docs to distinguish what the access levels indicate. Additionally, application content and users can be seen when Amplify Studio is enabled for the application.

For example, 
<img width="807" alt="image" src="https://user-images.githubusercontent.com/634958/160687556-306ab8cd-b79b-4e2a-9cc9-f30602d19813.png">
