### ISSUE TITLE
[Feedback] Outdated Next.js support

### ISSUE THREAD

**Issue by LouisAmon** [aws-amplify/docs#3776]
**Page**: [`/guides/hosting/nextjs/q/platform/[platform]`](https://docs.amplify.aws/guides/hosting/nextjs/q/platform/js/#deploy-and-host-an-ssg-only-app)

**Feedback**:

A paragraph says:
> Currently, Amplify doesn't fully support Image Component and Automatic Image Optimization available in Next.js 10

It seems the overall Next.js support has been built for Next.js 9.3, whereas last week they announced Next.js 12.
Specifically, what's been said about images is no longer relevant since v10

**Comment by siegerts** [comment]
Hi @LouisAmon , thanks for opening. I'll open a PR to update the portion that you mentioned. For reference, the current support for Next.js SSR in Amplify Hosting is outlined here - https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#ssr-Amplify-support
