### ISSUE TITLE
S3 buckets open to the public.   This is not ideal, causes alarms.

### ISSUE THREAD

**Issue by tomgilman** [aws-amplify/docs#379]
**Describe the bug**

This particular section is problematic.   The S3 buckets are public, and this causes alarms.

_Step 3. Set up the AWS Backend
Create new AWS backend resources and pull the AWS services configuration into the app. In a terminal window, change to the root directory of your app and run the following command (for this app, accepting all defaults is OK):**To Reproduce**_

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by muellerfr** [comment]
@tomgilman, can you please confirm that this is the page you are referring to? https://aws-amplify.github.io/docs/js/start?platform=purejs#step-3-set-up-the-aws-backend

**Comment by tomgilman** [comment]
That is correct.
