### ISSUE TITLE
[Feedback] Want to fix Amplify Push Notification with Javascript.

### ISSUE THREAD

**Issue by Jeontaeyun** [aws-amplify/docs#3794]
**Page**: [`/lib/push-notifications/overview/q/platform/[platform]`](https://docs.amplify.aws/lib/push-notifications/overview/q/platform/js)

**Feedback**:

When I saw document `Javascript > PushNotification`, I face that code example. 
```javascript
import Amplify from 'aws-amplify';
import PushNotification from '@aws-amplify/pushnotification';
import { PushNotificationIOS } from '@react-native-community/push-notification-ios';
import awsconfig from './aws-exports';

Amplify.configure(awsconfig);
```

when it comes to `@react-native-community/push-notification-ios`, It should be like that:

```javascript
import PushNotificationIOS from '@react-native-community/push-notification-ios';
```

FYI, I attach some reference for that, https://www.npmjs.com/package/@react-native-community/push-notification-ios and you can see **Migrating from the core react-native module** section

It is chore thing but it makes some confusion to developer. and If I can fix or pr for them, I feel so happy to fix it and PR 8-).
Thank you so much for good module.

**Comment by Jeontaeyun** [comment]
FYI How was it going? Can I make some PR for it?

**Comment by mauerbac** [comment]
Hey @Jeontaeyun - sorry for the delay :( 

If you are still up for it, a PR would be awesome!
