### ISSUE TITLE
[Feedback] How to use CDK outputs in Amplify?

### ISSUE THREAD

**Issue by shishkin** [aws-amplify/docs#3802]
**Page**: [`/cli/custom/cdk`](https://docs.amplify.aws/cli/custom/cdk)

**Feedback**:

Hi 👋

I'm trying to write a lambda in Amplify (all in Node.js) that is triggered by S3 upload. So far, that works great. This lambda needs to call Textract asynchronously and let it know SNS topic and IAM role to send the notification of completion. Here is Textract docs for that flow: https://docs.aws.amazon.com/textract/latest/dg/api-async.html. I figured I need a custom CDK stack in Amplify to provision SNS and IAM role. Amplify docs on CDK (https://docs.amplify.aws/cli/custom/cdk) provide nice example to do just that.

Now the real question is: how can I configure the SNS topic and IAM role ARNs inside the lambda without first deploying CDK and and then hardcoding it? I see how to get project and env from Amplify inside CDK, but not how to get CDK outputs inside Amplify aws-exports.

Thanks!

**Comment by ykethan** [comment]
Closing this in favor of feature request https://github.com/aws-amplify/amplify-cli/issues/11113 and https://github.com/aws-amplify/amplify-cli/issues/9087. Please feel free in adding your use case to the issues.
