### ISSUE TITLE
Fix typo: "_fetchTodos()" -> "_configureAmplify()"

### ISSUE THREAD

**Issue by dorontal** [aws-amplify/docs#3832]
**Describe the bug**
This is a simple typo - the function name is wrong in the documentation: 'Connect to the cloud' section of Flutter tutorial getting-started app.

**To Reproduce**
N/A

**Expected behavior**
Replace text: "_fetchTodos()" -> "_configureAmplify()"
on this page: https://docs.amplify.aws/start/getting-started/add-api/q/integration/flutter/#add-api-and-auth-plugins

**Comment by abdallahshaban557** [comment]
Duplicate of https://github.com/aws-amplify/docs/issues/3437. Closing this ticket.
