### ISSUE TITLE
[missing-page]

### ISSUE THREAD

**Issue by IvanKarnaukhov** [aws-amplify/docs#3854]
**Page**: [`https://docs.amplify.aws/ui-legacy/interactions/chatbot/`](https://docs.amplify.aws/ui-legacy/interactions/chatbot/)

I got 404 the page is missing

**Feedback**:

**Comment by mauerbac** [comment]
Hello - where did you find the link to that? I found this -> https://docs.amplify.aws/ui/interactions/chatbot/q/framework/react-native/
