### ISSUE TITLE
Getting started - Configure Amplify and DataStore not working

### ISSUE THREAD

**Issue by jhallam3** [aws-amplify/docs#3869]
**Page**: [`/start/getting-started/integrate/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/integrate/q/integration/ios/#configure-amplify-and-datastore)

**Feedback**:

<img width="1138" alt="Screenshot 2021-12-12 at 14 01 01" src="https://user-images.githubusercontent.com/5174328/145715459-bfabe738-9af5-44e1-ae7e-bfa39aa961ed.png">

having followed what is said in the document I get this  does not conform to protocol 'App' issue. Ive tried this multiple times

**Comment by mauerbac** [comment]
Going to close since this is outdated. Please let us know if you are still experiencing this issue and we will help to resolve asap. Sorry for the lack of response
