### ISSUE TITLE
[Feedback] "Sync with Figma" how ?

### ISSUE THREAD

**Issue by koxon** [aws-amplify/docs#3877]
**Page**: [`/console/tutorial/buildui`](https://docs.amplify.aws/console/tutorial/buildui)

**Feedback**:

I don't understand where to click "Synch with Figma" on the first tutorial page.
I don't find the screenshot with the button anywhere in Amplify

**Comment by mauerbac** [comment]
Hey - this sounds like a question about our new Amplify Studio. Can you join our Discord (discord.gg/amplify) . I also made this twitter post that has screenshots https://twitter.com/mauerbac/status/1467374905033437185
