### ISSUE TITLE
[Feedback] AmplifyAuthContainer Not Found

### ISSUE THREAD

**Issue by h-skye** [aws-amplify/docs#3882]
**Page**: [`/ui/auth/authenticator/q/framework/[framework]`](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react)

**Feedback**:

**AmplifyAuthContainer** was not found in @aws-amplify/ui-react, I was wondering if there is an updated way of doing the Auth/Login as this page seems outdated.

**Comment by siegerts** [comment]
Hi @h-skye, the documentation for the updated Authenticator is at https://ui.docs.amplify.aws/components/authenticator.

**Comment by Milan-Shah** [comment]
@h-skye As @siegerts mentioned above, you can find all documentation for our Authenticator UI Component and the upcoming ones at our new [UI doc site](https://ui.docs.amplify.aws/components/authenticator).
