### ISSUE TITLE
[Feedback] Unsure of how to view logs in AWS

### ISSUE THREAD

**Issue by michael-mcmasters** [aws-amplify/docs#3889]
**Page**: [`/lib/utilities/logger/q/platform/[platform]`](https://docs.amplify.aws/lib/utilities/logger/q/platform/js/#setting-logging-levels)

**Feedback**: I'm unsure of how to use the logger to view logs in the Amplify Console / Cloudwatch. If this logger is only for viewing logs in browser window, it would maybe be nice to clarify. And possibly link to a page that shows me how to view my console.logs in AWS because I can't find anything online.

**Comment by ashika01** [comment]
@michael-mcmasters At the moment, you could only view them in browser. If you would to view them in cloudwatch logs , I would suggest you open a feature request in the JS repo for it - https://github.com/aws-amplify/amplify-js/issues/new?assignees=&labels=feature-request&template=2.feature_request.yaml

**Comment by siegerts** [comment]
Closing as per the comment above.
