### ISSUE TITLE
[Feedback]FEEDBACK_TITLE_HERE

### ISSUE THREAD

**Issue by jessebarnum** [aws-amplify/docs#3899]
**Page**: [`/ui/auth/authenticator/q/framework/[framework]`](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react)

**Feedback**:

Your code example does not work.

import React from "react";
import Amplify from "aws-amplify";
import {AmplifyAuthenticator, AmplifySignOut} from "@aws-amplify/ui-react";
import awsconfig from "./aws-exports";

Gives this error:
TS2305: Module '"@aws-amplify/ui-react"' has no exported member 'AmplifyAuthenticator'.

**Comment by ashika01** [comment]
@jessebarnum - `AmplifyAuthenticator` is part of our `1.x` of UI components. so if u try to install `@aws-amplify/ui-react@1.x` it would work.

For the current usage refer - https://ui.docs.amplify.aws/

**Comment by ashika01** [comment]
I will keep this issue open to update our docs of those changes.

**Comment by siegerts** [comment]
Hi @jessebarnum, the docs page is updated to reflect the correct packages mentioned above for current and legacy Authenticators. - https://docs.amplify.aws/ui/q/framework/react/ .
