### ISSUE TITLE
improvePluralization=true after v1 to v2 migration not behaving same way

### ISSUE THREAD

**Issue by ingwinlu** [aws-amplify/docs#3906]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

7.6.5

### What operating system are you using?

Ubuntu WSL

### Amplify Categories

api

### Amplify Commands

codegen

### Describe the bug

After applying the v1 to v2 migration we noticed some queries changed their naming (emitting the appended 's). This came as a surprise as https://docs.amplify.aws/cli/migration/transformer-migration/ mentions improvePluralization is now ignored (but we never disabled it).

in two cases we now miss pluralization:
* listSensorDatas is now generated as listSensorData
  ![image](https://user-images.githubusercontent.com/4435962/147662870-5121d5d3-fe50-456e-87e4-443a4e3a5770.png)
* listShadowHistorys is now generated as ListShadowHistories
   ![image](https://user-images.githubusercontent.com/4435962/147662911-35884bac-5db2-4c5f-869a-fc016cb3a1ac.png)

both are autogenerated

### Expected behavior

Add to migration that not just versions with disabled pluralization are affected.

### Reproduction steps

have old codegen. apply api migration from v1 to v2. generate new code. models are supplied in the bug description.
The original v1 schema was created with v5.x.x

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line

type ShadowHistory
  @model(timestamps: null)
  @auth(
    rules: [
     # nuked
    ]
  ) {
  unitName: String! @primaryKey(sortKeyFields: ["datetime"])
  datetime: AWSDateTime!
  customerName: String!
  shadow: AWSJSON!
}

type SensorData
  @model(timestamps: null)
  @auth(
    rules: [
    # nuked
    ]
  ) {
  sensor: String! @primaryKey(sortKeyFields: ["datetime"])
  datetime: AWSDateTime!
  value: Float!
  min: Float
  max: Float
  count: Int
  customerName: String!
  unitName: String!
}
```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by nealdeters** [comment]
Why can this not be set anymore? This completely changes our api and forces not only us but our users to change to a different query name and breaks any sort of backwards compatibility.

**Comment by nealdeters** [comment]
I guess there is a workaround in that we can manually change the query names. But it would be nice to not have to do that for all these cases.

**Comment by cjihrig** [comment]
This change was by design. With the previous behavior, the transformer was generating nonsensical resolver names. We used the v2 major version bump to introduce a behavior change. The old behavior still works with the v1 transformer.
