### ISSUE TITLE
[Feedback]Missing information for hosting

### ISSUE THREAD

**Issue by pb-berige** [aws-amplify/docs#3914]
**Page**: [`/guides/hosting/gatsby/q/platform/[platform]`](https://docs.amplify.aws/guides/hosting/gatsby/q/platform/js/#deploying-the-site-to-amplify-console-hosting)

**Feedback**:

This page is missing the requirment to modify the default 'Rewrites and redirects' to allow for .manifest, .webp and .avif files to be served.

**Comment by nickarocho** [comment]
Hi @pb-berige thank you for your feedback.

I've added this information in the Gatsby, Next, Nuxt, and Gridsome hosting tutorials.

Thanks again!
