### ISSUE TITLE
[Feedback] npm install doc outdated

### ISSUE THREAD

**Issue by benjyz** [aws-amplify/docs#3916]
**Page**: [`/start/getting-started/setup/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/setup/q/integration/react)

**Feedback**:

this doc is outdated, npm doesnt support global install anymore
"We no longer support global installation of Create React App."

**Comment by ashika01** [comment]
@benjyz what do u mean by this doc is outdated? I see in the docs we use `npx create-react-app ...` which is same as the CRA official docs site for installation?! https://create-react-app.dev/docs/getting-started/#quick-start

**Comment by marcvberg** [comment]
Closing this issue due to no response
