### ISSUE TITLE
[missing-page]

### ISSUE THREAD

**Issue by nzw3yl** [aws-amplify/docs#3931]
**Page**: [`https://docs.amplify.aws/cli/graphql/codegen/`](https://docs.amplify.aws/cli/graphql/codegen/)

**Feedback**: 
Told I was looking at legacy codegen docs and the link for the latest documentation is broken

**Comment by aspittel** [comment]
Hey, can you include the page that the broken link was on? I can't find the page that this link is on!

**Comment by aspittel** [comment]
Thanks so much for raising this!
