### ISSUE TITLE
[Feedback] `http://localhost:8080` should be with port `8081`

### ISSUE THREAD

**Issue by rayeeroded** [aws-amplify/docs#3935]
**Page**: [`/start/getting-started/setup/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/setup/q/integration/js/#install-local-development-dependencies)

**Feedback**:
Currently doc says:
Open a browser and navigate to http://localhost:8080.

but this should be `http://localhost:8081`

the 8080 port server has no 'add data; button or anything

**Comment by ashika01** [comment]
@rayeeroded webpack-dev-server by default is configured to 8080. Thats the reason it is noted there as 8080. Unless you have a different port configuration or something else running in 8080 already. 
Reference from webpack-dev-server - https://github.com/webpack/webpack-dev-server#the-result

Correct me if I am wrong and I will reopen this ticket and update the docs.
