### ISSUE TITLE
[missing-page]

### ISSUE THREAD

**Issue by reubenjamesbishop** [aws-amplify/docs#3941]
**Page**: [`https://docs.amplify.aws/ui/auth/sign-out/q/framework/react/

**Comment by ashika01** [comment]
@reubenjamesbishop UI docs have been migrated to https://ui.docs.amplify.aws/

You will see this in UI page,
<img width="761" alt="Screen Shot 2022-01-28 at 12 49 45 PM" src="https://user-images.githubusercontent.com/35131273/151620280-99bfdf3a-cc86-474b-b43d-06adb5c87d2d.png">

Please feel free to open a new issue if something is missing in the new ui docs site.
