### ISSUE TITLE
Missing Amplify CLI v2 CodeGen page

### ISSUE THREAD

**Issue by johnrizzo4** [aws-amplify/docs#3943]
**Page**: [`https://docs.amplify.aws/cli/graphql/codegen/`](https://docs.amplify.aws/cli/graphql/codegen/)

**Feedback**:  the legacy page [https://docs.amplify.aws/cli-legacy/graphql-transformer/codegen/] refers the v2 page but it does not exist.

**Comment by aspittel** [comment]
Thanks so much for raising this!
