### ISSUE TITLE
[Feedback]Section on using Relational Data Sources?

### ISSUE THREAD

**Issue by danshev** [aws-amplify/docs#3946]
**Page**: [`/cli/graphql/data-modeling`](https://docs.amplify.aws/cli/graphql/data-modeling/#setup-database-tables)

**Feedback**:

The legacy notes had a section about connecting RDS instances (i.e., using `add-graphql-datasource`) -- I haven't been able to find any such thing in the new docs ... am I missing something or is that section missing?  Thank you!

**Comment by siegerts** [comment]
Hi @danshev 👋🏻 -  Currently, the new GraphQL Transformer does not support relational data sources.

https://docs.amplify.aws/cli/migration/transformer-migration/#changes-that-amplify-cli-requires-you-to-manually-migrate
