### ISSUE TITLE
[Feedback]Getting Started Amplify should include Import info

### ISSUE THREAD

**Issue by AlphaJuliettOmega** [aws-amplify/docs#3949]
**Page**: [`/lib/q/platform/[platform]`](https://docs.amplify.aws/lib/q/platform/js)

**Feedback**:

Imports were recently split.

1. Are there repercussions if you use the non-split Amplify with parts that are Split
2. Which is better practice?
3. How to import correctly should be the first thing
4. the first result if you search up top when typing 'import', should be on importing the library instead of Amplify Studio stuff

**Comment by AlphaJuliettOmega** [comment]
Ok, I found out what my issue was.

Please do not close this ticket until you document this or improve documentation on this. 
It's related to there being 0 documentation on the modular split

This works:
```
import Amplify from '@aws-amplify/core'
Amplify.configure(config)
```
Until you try to use a subscription from a GraphQL endpoint.
I removed these three packages:
```
    "@aws-amplify/auth": "^4.3.15",
    "@aws-amplify/core": "^4.3.7",
    "@aws-amplify/storage": "^4.4.8",
```
and now only import like this:
```
    "aws-amplify": "^4.2.4",
```

And subscriptions to my appsync graphql endpoint works flawlessly.

There are hundreds of threads probably caused by this.


I also got:
```
"Subscribe only available for AWS AppSync endpoint"
```
as well as:
```
AppSync Realtime subscription init error: Error: No credentials
```
as well as No Current User as specified in [this issue](https://github.com/aws-amplify/amplify-js/issues/1252)

With Amplify.Loglevel set to debug I got:
```
Error: No credentials at GraphQLAPIClass.eval
```
Trying different ways of modifying the call/config all resulted in errors that aren't useful and hours could have been prevented with a:

```
Warning: You have multiple AWS Auth packages imported, use one
```
or any kind of documentation whatsoever **including** the imports, the docs I could find all show the code with imports omitted.

**Comment by AlphaJuliettOmega** [comment]
Same symptoms for examples:
https://github.com/aws-amplify/amplify-js/issues/5814
https://github.com/aws-amplify/amplify-cli/issues/4141
https://github.com/aws-amplify/amplify-js/issues/1252
https://github.com/aws-amplify/docs/issues/2177

Another person who had the same issue:
https://github.com/aws-amplify/amplify-js/issues/8888#issuecomment-951816343

Example of recommendation that causes bug:
https://github.com/aws-amplify/amplify-js/issues/488#issuecomment-425511461

Modularisation that caused this small documentation gap:
https://github.com/aws-amplify/amplify-js/issues/3365

I just felt compelled to round this off with this comment.

**Comment by ashika01** [comment]
@AlphaJuliettOmega thank you for detailed issue here. We do have what configuration goes into each category in the library like this,
<img width="780" alt="Screen Shot 2022-01-28 at 1 01 38 PM" src="https://user-images.githubusercontent.com/35131273/151621009-a947722f-bdd2-4a83-a0ab-59efff8c42e4.png">


Would you like for us to have a separate single page on configuration talking about various ways of configuration and also add note on cleaning up `node_modules` and other artifacts everytime they add/remove package?

**Comment by siegerts** [comment]
@AlphaJuliettOmega, just following up on the comments above. Any thoughts on this?

**Comment by siegerts** [comment]
Closing for now. Can reopen if there is more information or follow up.
