### ISSUE TITLE
Add configurable parameters section to the latest document of GraphQL API

### ISSUE THREAD

**Issue by jaga810** [aws-amplify/docs#3963]
**Is your feature request related to a problem? Please describe.**
Legacy doc of GraphQL API has section called "Configurable parameters"
https://docs.amplify.aws/cli-legacy/graphql-transformer/config-params/
Though we can use configurable parameters with  GraphQL transformer v2, there is no documentation about it now.

**Describe the solution you'd like**
It would be nice to replicate "Configurable parameters" page of legacy doc to the latest doc.

**Additional context**
If "configurable parameters" is not recommended now,  I'd like to know why it's not recommended.

**Comment by renebrandel** [comment]
hi @jaga810 - while the configurable parameters approach is backwards compatible in v2, we have opened up a more flexible approach to override the settings via `amplify override api` https://docs.amplify.aws/cli/graphql/override/ 

Is there a particular workflow you're missing via the overrides approach? Also would love to hear if your thoughts on the different developer experiences here to achieve the results.

**Comment by enishenish** [comment]
Hello.
I would like to know the answer ("Configurable parameters" will be deprecated or not) too.

Because I use the DynamoDBEnablePointInTimeRecovery setting by "Configurable parameters" now. If "Configurable parameters" will be deprecated, I should prepare to move this setting to an override approach.

**Comment by jaga810** [comment]
Hi @renebrandel,  I agree with  using `amplify override api` approach which is so flexible and it could cover almost all the use cases once configurable parameters covered. 

On the other hand, we have 2 problems here 
1. New docs missing some examples of override settings once covered by configurable parameters in the documentation such as `DynamoDBEnablePointInTimeRecovery `, `DynamoDBModelTableWriteIOPS` and `ElasticSearchInstanceType`. Not all the Amplify users are familiar with CDK or CloudFormation, it would be great if we have specific examples of CDK overrides sample codes in doc.
2. Amplify users wonders if they should migrate settings from configurable parameters to overrides as @enishenish mentioned.

**Comment by renebrandel** [comment]
@AnilMaktala is going to add a few more examples to this page: https://docs.amplify.aws/cli/graphql/override/#customize-amplify-generated-resources-for-model-directive. Our goal is primarily make edits from overrides moving forward.
