### ISSUE TITLE
Specifying how changing schema.graphql will determine the schema at 'amplify push'

### ISSUE THREAD

**Issue by lillpham** [aws-amplify/docs#3968]
**Page**: [`/start/getting-started/data-model/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/data-model/q/integration/js/#connect-frontend-to-api)

**Feedback**:
Hi there,
I was following the tutorial and wanted to use my own schema, however it wasn't clear on the documentation that changing schema.graphql will add the queries, mutations, etc. that would correspond to that new schema after running 'amplify push'. I think it would be helpful to add a side-note explaining that this is what the users could do if they wanted to use a different schema. Thanks!

Kind regards,
Lillian

**Comment by ykethan** [comment]
Hey @lillpham, following up on this. could you provide us some additional information on what you are looking for?
Please refer to https://docs.amplify.aws/cli/graphql/client-code-generation/ providing additional information on client side code generation.
