### ISSUE TITLE
Default for Destination folder break the starting Guide

### ISSUE THREAD

**Issue by wascou** [aws-amplify/docs#397]
**Describe the bug**
In the documentation of the [start guide](https://github.com/aws-amplify/docs/blob/master/js/start.md), it said in the Step 3 that the all the defaults are ok but there's a explanation after the script block.

I guess 1/ this specification should be above the script block and  2/ you should remove the information telling that it's OK to accept all the defaults. It's confusing.

Cheers,

Max

**Comment by mlabieniec** [comment]
Was not able to reproduce this. The cli will default to a dist folder and will upload that folder so the defaults are ok. Not sure how to update/fix this please feel free to comment/update with more details on how we can improve.
