### ISSUE TITLE
[Feedback] Update outdate guide in implenting authenticator

### ISSUE THREAD

**Issue by rcp522** [aws-amplify/docs#3977]
**Page**: [`/ui/auth/authenticator/q/framework/[framework]`](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react)

**Feedback**:

This guide is outdated as it is using version 1.x.x of the authenticator implementation. The new way to implement it can be seen here https://ui.docs.amplify.aws/components/authenticator, which was announced here https://aws.amazon.com/blogs/mobile/amplify-uis-new-authenticator-component-makes-it-easy-to-add-customizable-login-pages-to-your-react-angular-or-vue-app/ . 

Could you please update the guide to either use the new implementation or indicate that this one is referring to version 1 of the component.

**Comment by siegerts** [comment]
Hi @rcp522, thanks for opening. Closing this now as this page has been updated with the correct links to the new (and legacy) docs.
