### ISSUE TITLE
[Feedback]Run amplify init to Generate model files 

### ISSUE THREAD

**Issue by afd998** [aws-amplify/docs#3986]
**Page**: [`/start/getting-started/generate-model/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/generate-model/q/integration/react-native)

**Feedback**:

You never told us to run amplify init?

**Comment by offlineprogrammer** [comment]
@afd998 Thanks for your feedback 

Please note you don't to run `amplify init` When you use `amplify pull --sandboxId <UUID> `

Check step 3 [here](https://docs.amplify.aws/start/getting-started/generate-model/q/integration/react-native/#generate-the-models-locally)
