### ISSUE TITLE
[Feedback]AWS profile or AWS access keys?

### ISSUE THREAD

**Issue by dtJon** [aws-amplify/docs#3996]
**Page**: [`/start/getting-started/setup/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/setup/q/integration/react/#initialize-a-new-backend)

**Feedback**:

amplify init prompts me for AWS profile or AWS access keys, but I'm not sure what the best answer is.

**Comment by mauerbac** [comment]
Hello -- it is more or less the same thing. AWS profiles allow you to work with many access keys/accounts. Setting one access key would give access to one account and not as easy to switch.
