### ISSUE TITLE
Push Notification documentation is missing FCM setup

### ISSUE THREAD

**Issue by martincalvert** [aws-amplify/docs#4002]
**Describe the bug**
The link for how to setup FCM and get reds is broken across numerous AWS documentation resources. 

**To Reproduce**
1. Go to https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/js/
2. Proceed to step 2
3. Click "Click here for instructions"
4. Click Android
5. Observe documentation skips to handling messages and not setup

**Expected behavior**
The documentation page should be about setting up and obtaining firebase credentials, mirror the flow for iOS which takes you to a setup section before the handling message section.

**Additional context**
Looked in the fragments for what would be the missing object but no such luck looking for a `setup-fcm` that mirrors the `setup-apps.mdx`

**Comment by offlineprogrammer** [comment]
Hi @martincalvert 

I couldn't reproduce this issue. The documentation land on Setting up push notification services https://docs.amplify.aws/sdk/push-notifications/setup-push-service/q/platform/android/

Can you please try again and let us know if you still get the issue 

Regards
Mo

**Comment by martincalvert** [comment]
So part of the confusion here might be my poor wording. Essentially when following the setup guide for push notifications for android there is a link that says "Get your push messaging credentials for Android in Firebase console. [Click here for instructions](https://docs.amplify.aws/sdk/push-notifications/setup-push-service/q/platform/js/).". After clicking through to that link you are presented with 2 options iOS or android. The iOS version walks you through setting up the pieces needed for APNS, while the android one takes you past the firebase setup and drops you off at handling the push notifications for a java based project.

So essentially the miss is  the "how to generate firebase credentials" page is missing for usage in a react native/js project.

**Comment by offlineprogrammer** [comment]
@martincalvert Thanks for the clarification I will flag this with the team
