### ISSUE TITLE
[missing-page] Updated list of authenticator properties

### ISSUE THREAD

**Issue by mttwise** [aws-amplify/docs#4005]
**Page**: [`https://docs.amplify.aws/ui/auth/authenticator/q/framework/react/q/framework/react/`]

origin page: https://docs.amplify.aws/ui/auth/authenticator/q/framework/react/#migration
target page: https://docs.amplify.aws/ui/auth/authenticator/q/framework/react/q/framework/react/#props-attr-amplify-authenticator

On the react framework Authentication docs, there is a link that is supposed to take you to the updated list of 'withAuthenticator' properties.  This link leads to a 404 page.
![image](https://user-images.githubusercontent.com/24458226/152569423-5a43126a-3057-4019-a1b4-294897b2f403.png)

**Comment by jakeburden** [comment]
Thanks @mttwise! This should be resolved when this PR merges
https://github.com/aws-amplify/docs/pull/4018
