### ISSUE TITLE
[Feedback]Error when I When i hit npm run dev for testing SSR

### ISSUE THREAD

**Issue by trizest** [aws-amplify/docs#4013]
**Page**: [`/start/getting-started/data-model/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/data-model/q/integration/next/#api-with-server-side-rendering-ssr)

**Feedback**:

When i hit npm run dev I get: 

<Server Error
Error: Body must be a string. Received: undefined.

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source
pages/index.js (14:33) @ getServerSideProps

  12 | export async function getServerSideProps({ req }) {
  13 |   const SSR = withSSRContext({ req });
> 14 |   const response = await SSR.API.graphql({ query: listPosts });
     |                                 ^
  15 | 
  16 |   return {
  17 |     props: {>

Very stuck. Not the best for an intro tute.

**Comment by aspittel** [comment]
Thanks for pointing this out! I submitted a pull request to fix this.
