### ISSUE TITLE
Add auth trigger migration information

### ISSUE THREAD

**Issue by enishenish** [aws-amplify/docs#4014]
**Is your feature request related to a problem? Please describe.**
I encountered this issue. (I didn't know this update and my trigger settings were unexpectedly wiped out)
https://github.com/aws-amplify/amplify-cli/issues/8997#issuecomment-991253670

**Describe the solution you'd like**
Please describe Information about this problem at the "Migration & Backwards Compatibility" section of amplify CLI docs.
At least, information below should be needed.
- trigger setting will be wiped if amplify cli is updated from old one
- `amplify auth update` is solution

**Comment by siegerts** [comment]
Closing this out now as this should be resolved via the newer version(s) of the CLI.
