### ISSUE TITLE
Get Feedback Module

### ISSUE THREAD

**Issue by jakeburden** [aws-amplify/docs#4022]
**Is your feature request related to a problem? Please describe.**
As an engineer, I'd like to know what pages of the docs need improving. What pages are helpful or unhelpful?

**Describe the solution you'd like**
There should be a component on each page that allows readers of our docs to submit feedback, letting us know if a page is helpful or not.

**Additional context**
An example is [Netlify's docs](https://docs.netlify.com/visitor-access/identity/registration-login/) have thumbs up and down button, along with a comment box.
<img width="815" alt="image" src="https://user-images.githubusercontent.com/2081699/153031960-a818f6c0-280f-42d7-a4ff-99fa230756a3.png">

**Comment by jakeburden** [comment]
@timngyn lets use this issue to discuss our approach for a Get Feedback module/component.

**Comment by timngyn** [comment]
The Netlify example you have looks good! I found some other examples here as well:

- https://www.twilio.com/docs/usage/api
  - I like the “thumbs up” and “thumbs down” more, but Twilio has a 5 star rating that when clicked opens up a modal to get more info.
  - Uses a captcha to handle bots.
  - Asks for clarification questions to gather more info about why a person selected that rating.
- https://docs.github.com/en/rest/guides/getting-started-with-the-rest-api
  - Clicking on the “thumbs up” or “thumbs down” expands the comment box to add comments.
  - Asks users for email in case they want to be reached out by GitHub.
  - Lets user know that they should contact support if they need a reply.
  
I like how these examples hide the extra fields to gather more info and show them only when a user is interacting with the feedback form. Maybe this is something we could try as well?

**Comment by tjleing** [comment]
Just to recall the discussion that @jakeburden and I had about this feature earlier -- one issue that cropped up was preventing users from submitting duplicate votes.  I like the captcha for preventing spamming; it might also be a good idea to save a user's feedback (thumbs up or down, stars out of 5, but not the specific text of the feedback) in local storage.  Of course then you'd need a way to change it if the page changes, for example.  It's an interesting design question.

**Comment by timngyn** [comment]
Some ideas we have so far:
- Create UUID for submissions containing vote, timestamp of submission, and text. UUID gets stored in local storage so we can keep track of submissions.

- Could use this component in conjunction with when a docs page was “last updated“. Only let the user submit new feedback if their last submission is older than the page's last update

- Keep track of the timestamp when a page finishes “loading” and the timestamp when the feedback form gets submitted. Allow the submission to go through if the difference between these two timestamps is larger than an arbitrary value.

**Comment by timngyn** [comment]
Closing issue as feedback component has been merged into docs! #4086
