### ISSUE TITLE
[missing-page]

### ISSUE THREAD

**Issue by damon-beaven** [aws-amplify/docs#4027]
**Page**: [`https://docs.amplify.aws/cli/usage/uninstall/

It looks like the "how to uninstall aws amplify cli" page is missing.

**Comment by jakeburden** [comment]
Thanks for spotting this! The contents of this page has been moved. I've setup a redirect so that URL goes to the new location:
https://docs.amplify.aws/cli/start/workflows/#uninstall-amplify-cli
