### ISSUE TITLE
[Feedback] Python-based s3 Lambda Triggers

### ISSUE THREAD

**Issue by dudzin** [aws-amplify/docs#4034]
**Page**: [`/cli/usage/lambda-triggers`](https://docs.amplify.aws/cli/usage/lambda-triggers/#s3-lambda-triggers)

**Feedback**:

Hi, 
On this page there is no mention that those triggers work only with JS lambdas. I tried python and I simply didn't see the option to add lambda trigger, nor use any preexisting template. I would love to see the same support for python (which I am mainly using), but I think at least a comment would be useful

**Comment by josefaidt** [comment]
Hey @dudzin :wave: thanks for raising this! While I noticed we are unable to choose the runtime for the Lambda trigger when adding through the `amplify add storage` flow, a workaround would be to add a Python function first, then step through the `amplify add storage` flow and choose the existing function.

For better support on this feature request, would you mind opening a [feature request issue in the Amplify CLI](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=2.feature_request.yaml) repo?

**Comment by josefaidt** [comment]
Hey @dudzin quick update, I've added the CLI feature request here https://github.com/aws-amplify/amplify-cli/issues/10020
Once the feature is complete we can revisit the docs update, closing issue
