### ISSUE TITLE
[missing-page]  Amplify CLI Export command

### ISSUE THREAD

**Issue by maBarabas** [aws-amplify/docs#4044]
**Page**: [`https://docs.amplify.aws/usage/export-to-cdk/`](https://docs.amplify.aws/usage/export-to-cdk/)

**Feedback**:  This is linked in the readme for https://github.com/aws-amplify/amplify-cli-export-construct.

The correct page is https://docs.amplify.aws/cli/usage/export-to-cdk/.

**Comment by maBarabas** [comment]
@calavera Could you please explain the incorrect-info label?

The link is a 404 for me, and it is referenced in https://github.com/aws-amplify/amplify-cli-export-construct/blob/main/README.md

**Comment by siegerts** [comment]
Hi @maBarabas, I've opened a PR to fix the readme in the export construct repo. Closing this as the issue is with that project. 

https://github.com/aws-amplify/amplify-cli-export-construct/pull/33
