### ISSUE TITLE
[Feedback] port custom subscription for GraphQL transformer v1 to new transformer docs

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/docs#4084]
**Page**: [`/cli-legacy/graphql-transformer/examples`](https://docs.amplify.aws/cli-legacy/graphql-transformer/examples/#filter-subscriptions-by-model-fields-andor-relations)

**Feedback**:

**Comment by josefaidt** [comment]
found this doc in the guides section https://docs.amplify.aws/guides/api-graphql/subscriptions-by-id/q/platform/js/

**Comment by renebrandel** [comment]
Closing this issue because it's handled by-default with the server-side subscription filtering experience. https://docs.amplify.aws/cli/graphql/data-modeling/#server-side-filtering-for-subscriptions
