### ISSUE TITLE
[Example-Required] How to add a  pre-signup lambda trigger to the Auth resource in an Amplify project 

### ISSUE THREAD

**Issue by sachscode** [aws-amplify/docs#4090]
**Is your feature request related to a problem? Please describe.**
Customers have expressed a requirement to configure  preAuth, preSignup lambda triggers into the Auth resource. Customers have historically resolved this by manually editing their Cloudformation . 
 e.g  [[9680](https://github.com/aws-amplify/amplify-cli/issues/9680) , [6513](https://github.com/aws-amplify/amplify-js/issues/6513), [5318](https://github.com/aws-amplify/amplify-js/issues/5318) ] 

**Describe the solution you'd like**
This solution https://github.com/aws-amplify/amplify-cli/issues/9680#issuecomment-1055637786 presented by @akshbhu illustrates a way to achieve this using custom-resources , which is generic enough for customers to use in all of the above cases.

**Describe alternatives you've considered**
Currently this is the only way we could achieve this ( until extensibility is implemented for Function resource. )

**Additional context**

**Comment by josefaidt** [comment]
Hey @sachscode :wave: this is supported in the CLI workflow for adding and updating auth:

<img width="340" alt="image" src="https://user-images.githubusercontent.com/5033303/169590330-5c9ec8f9-10a2-4985-b28f-6f193ec6ce4c.png">
