### ISSUE TITLE
 amplify configure -bash: amplify: command not found

### ISSUE THREAD

**Issue by flutterreddy** [aws-amplify/docs#410]
After running command

`npm install -g @aws-amplify/cli`

**I got an error**
Please check the below log for details.
 
`
Chandras-MacBook-Pro:~ chandramoulireddyporeddy$ **npm install -g @aws-amplify/cli**
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/Users/chandramoulireddyporeddy/.npm-global/bin/amplify -> /Users/chandramoulireddyporeddy/.npm-global/lib/node_modules/@aws-amplify/cli/bin/amplify
npm WARN **graphql-import@0.4.5 requires a peer of graphql@^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.**

+ @aws-amplify/cli@0.1.44
updated 3 packages in 43.354s
Chandras-MacBook-Pro:~ chandramoulireddyporeddy$ **amplify configure**
-bash: amplify: command not found
Chandras-MacBook-Pro:~ chandramoulireddyporeddy$ 
`

**Comment by nikhil-dabhade** [comment]
@kaustavghosh06 : Ping

**Comment by kaustavghosh06** [comment]
@nikhil-dabhade This is not a docs issue and a similar issue had been opened up and tracked by flutterreddy on our CLI repo.

**Comment by kaustavghosh06** [comment]
Here's the issue: https://github.com/aws-amplify/amplify-cli/issues/778
Please take a look at it for a solution.

**Comment by sirshannon** [comment]
There is no solution in that thread.

**Comment by aldokhayel** [comment]
I have same issue, any suggestion to fix it?

**Comment by edoantonioco** [comment]
@aldokhayel you can try
npm cache clean --force
and install amplify again

**Comment by aldokhayel** [comment]
Thanks but still same, weird !

**Comment by aldokhayel** [comment]
@e

> Thanks but still same, weird !

@edoantonioco

**Comment by alexbeattie** [comment]
Just ran into this issue. I fixed it by uninstalling homebrew... which caused Node.js to be uninstalled. Reinstalled Node.js from node site & reran the aws amplify / configure tool and it worked. 

Pretty sure it has to do with the /Cellar path ...

**Comment by aldokhayel** [comment]
After running this command:
`npm install -g @aws-amplify/cli` 
it appears:
=========
> npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/Users/abdulrahman/npm/bin/amplify -> /Users/abdulrahman/npm/lib/node_modules/@aws-amplify/cli/bin/amplify
npm WARN graphql-import@0.4.5 requires a peer of graphql@^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.

+ @aws-amplify/cli@1.1.6
updated 3 packages in 14.009s
=========

I think it download correctly, but when I run this command:
`amplify configure`

> -bash: amplify: command not found

**Comment by kaustavghosh06** [comment]
@aldokhayel 
Can you run `echo $PATH` and see if `/usr/local/bin` is a path in it?

**Comment by aldokhayel** [comment]
when I run:
`echo $PATH`

the output is:
> /usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin

@kaustavghosh06

**Comment by kaustavghosh06** [comment]
@aldokhayel Can you locate the `amplify` executable in `/usr/local/bin`? If yes can you run `/usr/local/bin/amplify` and see if that works??

**Comment by aldokhayel** [comment]
I tried, but this is the output:

> internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '../src/cli'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/bin/amplify:3:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)


I think the issue is not related to amplify directly, because I just try to run the : "amplify" from original path which is:
`/Users/abdulrahman/npm/lib/node_modules/@aws-amplify/cli/bin/amplify configure`
and it works fine 👍 

@kaustavghosh06

**Comment by kaustavghosh06** [comment]
Looks like something messed up with your node installation/configuration. I would recommend trying out nvm since that helped a user out here who was running into a similar issue - https://github.com/aws-amplify/amplify-cli/issues/778#issuecomment-461934424

**Comment by aldokhayel** [comment]
Many thanks @kaustavghosh06 for contribution. 
This solution worked for me, just should find where is the executable file, the add it's folder to your $PATH, like what I did below: :
`export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/YourName/npm/bin"`

**Comment by ayushme001** [comment]
try this
$export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/YOURUSERNAME/.npm-global/bin"

HOPE it might work!! 🙂

**Comment by pzlydak** [comment]
Had the same issue. I had to add the path to PATH. For OSX I did this:
vim /etc/paths
Added this path to the end of the file
/usr/local/Cellar/node/11.11.0/bin/amplify
Relaunch terminal
It now works.

**Comment by DanielCarns** [comment]
I had the same issue and it was caused by a few factors. The above solutions won't work unless you follow step #1 here.

1.) Amplify documentation doesn't tell you to first install the AWS CLI, it assumes you already have. Go here to follow those instructions: [(https://docs.aws.amazon.com/cli/latest/userguide/install-linux-al2017.html)]
2.) Make sure your version of node is updated (common sense I know) I got a syntax error upon installing it again because I was somehow running 5. instead of 12.

Hope this helps!!

**Comment by JuliaUsanova** [comment]
try `sudo npm install -g @aws-amplify/cli --unsafe-perm=true`

**Comment by toonsend** [comment]
If you are using nvm, ensure you 'nvm use'  the version where the library is installed.

**Comment by BaronChen** [comment]
Not sure if this is the same reason that cause problem for other people but here is what I was facing with nvm:
When I am running `npm config get prefix -g` the path is pointing to a different node version then the one I am using currently. I have to run 
`npm config get prefix /Users/$YOUR_USER/.nvm/versions/node/$YOUR_VERSION` to fix the path of NPM.

**Comment by hdsantos89** [comment]
Ran into this issue, after some headache here is how I solved it:

after running:
`npm install -g @aws-amplify/cli`

it would give me the following:
`/Users/USERNAME/.npm-global/bin/amplify -> /Users/USERNAME/.npm-global/lib/node_modules/@aws-amplify/cli/bin/amplify`

Since the error that I was getting was:
`-bash: amplify: command not found`

I changed my my etc/paths:
`sudo vim /etc/paths`

Then I just appended a last entry of:
`/Users/USERNAME/.npm-global/bin`

Save and exit the file, restarted the terminal and voila!

Didn't need to reinstall anything. I think the reason behind it is because Amazon expects you to have AWS CLI installed before installing AWS Amplify CLI, since in my other machine it worked fine.

**Comment by cyber-tanaharaguy** [comment]
Hi guys just in case any of this solutions work here is what a I did ->
write in terminal 
/usr/local/Cellar/node/15.14.0/lib/node_modules/@aws-amplify/cli/bin/amplify configure
the main thing is to find the amplify exe. Some folders are hidden you can un hidden with cmd + shift + period (cmd + shift + .)

It was a headache for me but now is working!

**Comment by rafaelperozin** [comment]
I had the same issue and the unique solution that worked for me was installing the amplify using the `cURL` that you can get [here](https://docs.amplify.aws/start/getting-started/installation/q/integration/js#option-1-watch-the-video-guide).

For mac and linux
```
curl -sL https://aws-amplify.github.io/amplify-cli/install | bash && $SHELL
```

For windows
```
curl -sL https://aws-amplify.github.io/amplify-cli/install-win -o install.cmd && install.cmd
```

**Comment by 07anhad** [comment]
> try `sudo npm install -g @aws-amplify/cli --unsafe-perm=true`

Works! 
Thanks @JuliaUsanova

**Comment by mfp4073** [comment]
if you have verified amplify cli is installed you can run amplify with this command
`npx amplify`

**Comment by samirpatil2000** [comment]
try this `npm install @aws-amplify/cli` 
instead of this 
`npm install -g @aws-amplify/cli`
when you added `-g` as in global then it download that package to your `/Users/samir/.npm-global`, but somehow it wasn't able to read from there

**Comment by soydanius** [comment]
I tried whatever I could for so long. What solved it for me was that I was running amplify init in the bash terminal in vscode. Running it in the cmd terminal works without issue.
