### ISSUE TITLE
Document that *.cloudfront.net URLs don't work for Amplify Hosting

### ISSUE THREAD

**Issue by calavera** [aws-amplify/docs#4112]
**Is your feature request related to a problem? Please describe.**

Sometimes, customers are confused because *.cloudfront.net URLs don't work for apps hosted on Amplify Hosting. This is by design because Amplify Hosting needs to manage the routing layer internally. 
**Describe the solution you'd like**

We need to document this behavior.

See https://github.com/aws-amplify/amplify-hosting/issues/2104#issuecomment-929377151

**Comment by ShepSims** [comment]
Hmmm... its worth noting that it is not that they "dont work," it's just that they do not resolve directly to the application, as mentioned in your linked thread.  They DO work as intended for hosted apps, just not as documented.  

> *.cloudfront.net URLs don't work for apps hosted on Amplify Hosting

**Comment by calavera** [comment]
This information has been added to the troubleshooting page: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-404-cloudfront-url

**Comment by teamteak** [comment]
So just to be clear.

If Amplify Hosting is asking me to update our ANAME to: <id>.cloudfront.net AND we are NOT using S3 AND it throws a 404, we should rather create a CNAME on our third-party DNS for the corresponding branch application URL we want our domain to resolve to which does work and resolves correctly.

Example:

We want our example.com production domain to resolve to our root branch, AND <id>.cloudfront.net is throwing a 404, however, root.<id>.amplifyapp.com does work, therefore, use root.<id>.amplifyapp.com app URL for your CNAME.

Is this correct?
