### ISSUE TITLE
Lambda Handler Function Name in Blog Code

### ISSUE THREAD

**Issue by ioanthony** [aws-amplify/docs#4118]
**Page**: [`/guides/functions/dynamodb-from-python-lambda/q/platform/[platform]`](https://docs.amplify.aws/guides/functions/dynamodb-from-python-lambda/q/platform/js/#getting-an-item-by-primary-key-in-dynamodb-from-lambda)

**Feedback**:
The code under "Getting an item by primary key in DynamoDB from Lambda" has:
`def handler(event, context)`

Per this response:
https://stackoverflow.com/questions/50790789/handler-lambda-handler-missing-on-module-lambda-function

It should be
`def lambda_handler(event, context)`

Could you confirm?

**Comment by siegerts** [comment]
Hi @ioanthony, the default set up for Python functions in Amplify is to use `def handler(event, context)`. This name determines how the Lambda configuration knows what function to call (screenshot from Lambda below). Theoretically, it's possible to change the handler function this but it's not required as Amplify passes along the correct config.

<img width="1150" alt="image" src="https://user-images.githubusercontent.com/634958/158210584-749081bd-1047-4dfa-8dd5-647dd5b7f158.png">
