### ISSUE TITLE
More clear documentation that AWSMobileClient does not work with SignInUI or IdentityManager

### ISSUE THREAD

**Issue by minbi** [aws-amplify/docs#413]
Customers are facing issues with the combined usage of AWSMobileClient and IdentityManager or SignInUI.

**Comment by nikhil-dabhade** [comment]
@minbi Can you add details around what "does not work" with error messages ?

**Comment by minbi** [comment]
@nikhil-dabhade , The AWSMobileClient is not meant to work with the IdentityManager or SignInUI. The mobile client is meant to mask usage of the previous clients and it gives us the opportunity to change/completely replace IdentityManager and any underlying clients.
