### ISSUE TITLE
More clear documentation that AWSMobileClient will block calls

### ISSUE THREAD

**Issue by minbi** [aws-amplify/docs#414]
Customers are being confused that there is deadlock on waitForSignIn even though this is expected behavior. A clearer statement that customers should use addSignInStateListener for a signed out expired token event.

**Comment by minbi** [comment]
Android Authentication section. Probably very near the top of the page in the introduction and in proximity to `getCredentials()` mentions.

**Comment by palpatim** [comment]
This is also confusing customers on iOS: https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/185

**Comment by zigfreid5** [comment]
@palpatim for what it's worth, I don't think just updating the documentation is the best solution here. I think a different strategy should be used as the SDK crashes if calling `releaseSignInWait()` without there being a request waiting on sign in. That may be a different issue, but the opinion stands. It may be better to approach the solution differently, perhaps by making the request-hanging-behavior optional, as the expected behavior is different.

**Comment by zigfreid5** [comment]
As a side note, is there a proper way to test these scenarios (UserPoolTokenInvalid)? Using the cli to invoke admin global sign out user does nothing, and clearing the credentials in the SDK doesn't invalidate the refresh token. The SDK crashes when calling `releaseSignInWait()` without a request waiting for sign in, so all, in all, I'm struggling trying to find a way to test this.

If there is a way, can that be included in the documentation as well?

**Comment by rohandubal** [comment]
Hello @zigfreid5 

One solution could be that we can write a functional test which uses the admin operations(via code) and client operations in the same test where we log-in a user, call the admin signout operation and test the behavior. Other option is to reduce the token duration and validate it manually.

I will try to write up a test which does the above.

Thanks,
Rohan

**Comment by liviu-timar** [comment]
Hello,

Can you please outline a basic flow for this case in Android? Operations are not unblocked when signing again in the UseStateListener... I'm getting a new token and passing it again to federatedSignIn. But nothing happens. What should I do more?

Thanks
