### ISSUE TITLE
cognito does not have event.request.userAttributes.sub parameter

### ISSUE THREAD

**Issue by davidallenmann** [aws-amplify/docs#4147]
**Page**: [`/guides/functions/cognito-trigger-lambda-dynamodb/q/platform/[platform]`](https://docs.amplify.aws/guides/functions/cognito-trigger-lambda-dynamodb/q/platform/js/#create-the-lambda-function)

**Feedback**:

In this example I do not believe there is a event.request.userAttributes.sub parameter returned from Cognito.

This is what I get when I log 'event' from a cognito lambda trigger for pre-signup.
```
{
  version: '1',
  region: 'us-east-1',
  userPoolId: 'us-east-1_xxxx',
  userName: 'xxxxxxxx-xxxx-xxxx-xxxx-12bee4f032fb',
  callerContext: {
    awsSdkVersion: 'aws-sdk-unknown-unknown',
    clientId: 'xxxxxxxxx'
  },
  triggerSource: 'PreSignUp_SignUp',
  request: {
    userAttributes: { email: 'xxxxxx@xxxxxxxxxx.com' },
    validationData: null
  },
  response: {
    autoConfirmUser: false,
    autoVerifyEmail: false,
    autoVerifyPhone: false
  }
}
```

**Comment by siegerts** [comment]
Hi @davidallenmann , thanks for raising. Have you tried with the `post signup trigger`? The above output is from the `pre signup` so I don't expect that the user is created at that point. The above linked page is setting up the `post` confirmation trigger.

**Comment by siegerts** [comment]
Closing for now, please reopen if still needed.
