### ISSUE TITLE
[Feedback] AmplifyUIAngularModule module is no longer available

### ISSUE THREAD

**Issue by kaustavbecs** [aws-amplify/docs#4163]
**Page**: [`/start/getting-started/data-model/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/data-model/q/integration/angular/#connect-frontend-to-api)

**Feedback**:

**Comment by siegerts** [comment]
Hi @kaustavbecs , thanks for opening. Those docs are referencing the [legacy Angular Authenticator](https://github.com/aws-amplify/amplify-ui/tree/legacy/legacy/amplify-ui-angular) . The docs for the current version of the Authenticator are [here](https://ui.docs.amplify.aws/components/authenticator?platform=angular).
