### ISSUE TITLE
[Feedback]Ampliy SDK API Reference link is broken

### ISSUE THREAD

**Issue by mineoni** [aws-amplify/docs#4167]
**Page**: [`/start/q/integration/[integration]`](https://docs.amplify.aws/start/q/integration/android/?sc_icampaign=android-start&sc_ichannel=docs-home)

**Feedback**:

API Reference link is broken.

https://aws-amplify.github.io/aws-sdk-android/docs/reference/

**Comment by sktimalsina** [comment]
Link has been restored.
