### ISSUE TITLE
Documentation incomplete for integrating with AppSync services outside of a given Amplify application

### ISSUE THREAD

**Issue by stocaaro** [aws-amplify/docs#4178]
**Is your feature request related to a problem? Please describe.**
Re: [this conversation](https://discord.com/channels/705853757799399426/707328986077855836/960522834420043797)
An application team has elected to build an AppSync API outside of an Amplify application, then integrate it using the Amplify libraries.

Hypothetically this documentation could also support use-cases where multiple application API's need grant API access to other applications that don't share their backend directly.

**Describe the solution you'd like**
I would expect to find a section devoted to this in the [library API documentation](https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/js/).

Having not found it here, there is a bit of documentation down in ["Configuring Amplify Categories"](https://docs.amplify.aws/lib/client-configuration/configuring-amplify-categories/q/platform/js/), which alone is incomplete as it doesn't give guidance on the IAM needs necessary to successfully integrate. To work around this problem, the team had to add a user pool and to add two IAM roles for auth and unauth to grant the Amplify application access to the API.

**Additional context**
The above discord conversation covers the context that is available, pending further conversation here.

**Comment by micklaw** [comment]
Looping myself in here as I was the one moaning :D

**Comment by renebrandel** [comment]
This should be addressed as part of this documentation. https://docs.amplify.aws/lib/graphqlapi/existing-resources/q/platform/js/#using-awsiam

**Comment by renebrandel** [comment]
Please @-mention me if there's more context you're looking for.
