### ISSUE TITLE
[Feedback]FEEDBACK_TITLE_HERE

### ISSUE THREAD

**Issue by ulanka** [aws-amplify/docs#4197]
**Page**: [`/start/getting-started/add-api/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/add-api/q/integration/react-native)

**Feedback**:

Could you please point out at which point "models" generated which we import in Home.js with `import { Todo } from './models';`

**Comment by arundna** [comment]
Hey @ulanka 👋  as @siegerts shared the link for generation of models above, we'll proceed to close this issue. 

Feel free to re-open or open a new issue in case of further queries.
