### ISSUE TITLE
[Feedback] Outdated and confusing docs for Function - Calling GraphQL API from a Lambda function

### ISSUE THREAD

**Issue by EPMatt** [aws-amplify/docs#4202]
**Page**: [`/guides/functions/graphql-from-lambda/q/platform/[platform]`](https://docs.amplify.aws/guides/functions/graphql-from-lambda/q/platform/js/#signing-a-request-from-lambda)

**Feedback**:

The guide explaining how to call a GraphQL API from a Lambda function is outdated. Code snippets provided in all the 3 sections use `aws-sdk` v2, while the v3 of the SDK has been released for a while now. Moreover, the section "Signing a request from Lambda" uses a really old version of the SDK to sign the request:

```javascript
const signer = new AWS.Signers.V4(req, "appsync", true);
signer.addAuthorization(AWS.config.credentials, AWS.util.date.getDate())
```
I was not able to find any docs regarding `AWS.Signers.V4` even in the SDK v2 doc website.

I'd also like to point out that the "Signing a request from Lambda" section might be quite confusing for users not really experienced with the SDK and AWS in general: from the description it's not clear whether the Lambda is using either IAM or api keys to call the GraphQL API. The code snippet doesn't have any comments explaining what's going on in the code.

First, the doc page reports this code snippet, which adds access to the GraphQL API via `amplify update function`, with the following result:

```
? Select which capability you want to update: Lambda function (serverless function)
? Select the Lambda function you want to update: MyFunction
General information
| Name: MyFunction
| Runtime: nodejs
...

? Which setting do you want to update? Resource access permissions
? Select the categories you want this function to have access to. (Select using <space>)
> api
? Select the operations you want to permit on <YOUR_API_NAME> (Select using <space>)
> Query, Mutation, Subscription

You can access the following resource attributes as environment variables from your Lambda function
    API_<YOUR_API_NAME>_GRAPHQLAPIENDPOINTOUTPUT
    API_<YOUR_API_NAME>_GRAPHQLAPIIDOUTPUT
    API_<YOUR_API_NAME>_GRAPHQLAPIKEYOUTPUT
? Do you want to edit the local lambda function now? No
```
If I correctly grasped the concept from the docs, running this command both sets up the environment variables above, as well as adds the proper IAM policies for the lambda function, to correctly access the API.

The api key is obtained from the environment at line 8:
```javascript
const apiKey = process.env.API_<YOUR_API_NAME>_GRAPHQLAPIKEYOUTPUT;
```

In the following section, auth information is added to the request (line 30):

```javascript
    if (apiKey) {
        req.headers["x-api-key"] = apiKey;
    } else {
        const signer = new AWS.Signers.V4(req, "appsync", true);
        signer.addAuthorization(AWS.config.credentials, AWS.util.date.getDate());
    }
```
The steps in this guide lead to having the `API_<YOUR_API_NAME>_GRAPHQLAPIKEYOUTPUT` environment variable correctly set up in the execution runtime. Therefore, `apiKey` will always be defined, and the V4 signing process using IAM would never run.

I believe a simpler example should be provided to users who just want to access the GraphQL API from Lambdas with IAM only.

Thank you for your time and efforts, and for maintaining the Amplify docs. 👍🏻

**Comment by josefaidt** [comment]
Closing as examples have been updated to use `fetch` and aws-sdk v3
