### ISSUE TITLE
[Feedback] Bug in example on Amplify Site

### ISSUE THREAD

**Issue by jeff-accountably** [aws-amplify/docs#4218]
**Page**: [`/guides/functions/appsync-operations-to-lambda-layer/q/platform/[platform]`](https://docs.amplify.aws/guides/functions/appsync-operations-to-lambda-layer/q/platform/js)

**Feedback**:
In appSyncRequest.js

```
return new Promise((resolve, reject) => {
    const httpRequest = https.request({ ...req, host: endpoint }, (result) => {
      result.on('data', (data) => {
        resolve(JSON.parse(data.toString()))
      })
    })

    httpRequest.write(req.body)
    httpRequest.end()
  })
```

It should be something like:
```
  return new Promise((resolve, reject) => {
    const httpRequest = https.request({ ...req, host: endpoint }, (result) => {
      var returnData = "";

      result.on("data", (data) => {
        returnData += data;
      });

      result.on("end", () => {
        resolve(JSON.parse(returnData));
      });
    });

    httpRequest.write(req.body);
    httpRequest.end();
  });
};
```

The issue is if the data is not fully read in the first response from the server you end up parsing invalid JSON. Move the parse to results.on("end") instead.

**Comment by josefaidt** [comment]
Hey @jeff-accountably :wave: thanks for raising this! We'll address this soon, however in the meantime this appears related to https://github.com/aws-amplify/docs/issues/4202
