### ISSUE TITLE
consider deprecating CLI's IAM Policy page in favor of managed policy

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/docs#4232]
ref: https://github.com/aws-amplify/docs/issues/3422
page: https://docs.amplify.aws/cli/reference/iam/
policy: [AdministratorAccess-Amplify](https://console.aws.amazon.com/iam/home#policies/arn:aws:iam::aws:policy/AdministratorAccess-Amplify)

**Comment by josefaidt** [comment]
We should keep this doc and be more clear about the intent where this is a reference to provide least amount of privilege to the IAM user, where `AdministratorAccess-Amplify` is sufficient for most cases

**Comment by ykethan** [comment]
closing the issue as this page has been deprecated.
