### ISSUE TITLE
Broken tutorial for generating model files

### ISSUE THREAD

**Issue by Teekink** [aws-amplify/docs#4259]
**Page**: [`/start/getting-started/generate-model/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/generate-model/q/integration/react-native)

**Feedback**:

At the "Generate the models locally" step, there is no longer a "Test locally in your app" screen. The corresponding next step, amplify pull --sandboxId <UUID>, does not function without additional work, which is not provided by the tutorial

**Comment by renebrandel** [comment]
this should be addressed, just went through the flow and can see the test locally button.
![image](https://user-images.githubusercontent.com/4989523/226918756-b5e9c840-f5fc-4ec6-a0ae-49c2a009c26e.png)
