### ISSUE TITLE
Make "Authentication Modes" section part of "Client Initialization" in API section

### ISSUE THREAD

**Issue by muellerfr** [aws-amplify/docs#427]
Originally suggested by @devxpy as part of https://github.com/awslabs/aws-mobile-appsync-sdk-android/issues/97:

Make "Authentication Modes" section part of "Client Initialization" so that `AWSAppSyncClient` is properly setup before attempting to query.

**Comment by jonneymendoza** [comment]
I am having the exact same issue as well

**Comment by bryannevega** [comment]
@jonneymendoza . Give me an hour, I found a solution but not in my PC

**Comment by bryannevega** [comment]
> 
> 
> I am having the exact same issue as well

Sorry it took long, but I created a small repo to share it publicly.

[Initialize AWS SDK with Developer IDs & AppSync](https://github.com/bryannevega/aws)
