### ISSUE TITLE
Mislieading/incorrect component name in example

### ISSUE THREAD

**Issue by dfetterman** [aws-amplify/docs#4275]
On page https://docs.amplify.aws/console/uibuilder/eventhandling/#update-a-record-from-database

It looks like the "HomeCollection" component is being called "CardBCollection" in the following example. There is no other reference to "CardBCollection" in the doc.

I'm suggesting that someone should change:

`...
      <UpdateHome home={updateHome}/>
      <CardBCollection overrideItems={({ item }) => ({
        onClick: () => setUpdateHome(item)
...`

to

`...
      <UpdateHome home={updateHome}/>
      <HomeCollection overrideItems={({ item }) => ({
        onClick: () => setUpdateHome(item)
...
 `

**Comment by renebrandel** [comment]
Another good catch! Created a PR to address this issue!
