### ISSUE TITLE
[missing-page]

### ISSUE THREAD

**Issue by cfromns** [aws-amplify/docs#4292]
**Page**: [`https://docs.amplify.aws/cli/graphql/per-user--owner-based-data-access/`](https://docs.amplify.aws/cli/graphql/per-user--owner-based-data-access/)

Clicking the link 'Per-user / owner-based data access' in Amplify CLI / Get Started / Authorization Rules / Signed-in user data access returns a 404 page error.

**Comment by mauerbac** [comment]
Fixed!, thank you @cfromns
