### ISSUE TITLE
Incorrect location of aws-exports file for React Native Getting Started guide

### ISSUE THREAD

**Issue by JohnMealy23** [aws-amplify/docs#4305]
**Page**: [`/start/getting-started/setup/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/setup/q/integration/react-native)

**Feedback**:
Your tutorial advises adding the following line...

```
import awsconfig from './src/aws-exports'
```

However, the file structure at this point does not contain a `'./src/aws-exports'`.

**Comment by arundna** [comment]
@JohnMealy23 👋 Thanks for opening this issue. I'm curious about your environment setup. 

- Have you used Expo or React CLI?
- Have you created a new directory for your project before running `expo init amplified_todo` / `npx react-native init amplified_todo`?

The setup guide provides instructions to initialize a new RN project in the **amplified_todo** directory. If you create a new directory prior to running the commands, then the `aws-exports` file will be located in the root of your project directory.

**Comment by arundna** [comment]
@JohnMealy23 Following up to see if you still encounter the issue based on my above comment on the directory structure setting up a React Native project.
