### ISSUE TITLE
Documentation for SSG/SSR examples refer to command that install latest NextJS (12) which is broken on Amplify

### ISSUE THREAD

**Issue by mrenrich84** [aws-amplify/docs#4307]
**Describe the bug**
Documentation for SSG/SSR examples refer to command that install latest NextJS (12) which is broken on Amplify

**To Reproduce**
1. Go to https://docs.amplify.aws/guides/hosting/nextjs/q/platform/js/
2. Suggested command is `npm init next-app`
3. This will install next@12 which is known to be broken https://github.com/aws-amplify/amplify-hosting/issues/2343

**Expected behavior**
I'd like to have a clear description on how to install a supported NextJS version.

**Additional context**
I tried installing a previous version of create-react-app and that didn't worked, e.g. with:
```
npm i -g create-next-app@next-11
npx create-next-app
```

**Comment by mrenrich84** [comment]
I have created this template meantime https://github.com/mrenrich84/nextjs-11-template

**Comment by arundna** [comment]
@mrenrich84 - Thanks for reporting this and creating the nextjs 11 template. AWS Amplify currently supports Next.js versions 9, 10 and 11. Next.js 12 works with Amplify Hosting, with the exception of bot-aware ISR, AVIF image optimization and middleware features that are currently unsupported. The complete support for Next.js 12 is currently on the roadmap and actively being worked on. Once released, we will update our docs to reflect this and also update [Support Next.js 12](https://github.com/aws-amplify/amplify-hosting/issues/2343) .

Closing this issue. Feel free to re-open if you need further assistance.
