### ISSUE TITLE
[Feedback]  Amplify plugin was not added

### ISSUE THREAD

**Issue by endriv** [aws-amplify/docs#4311]
**Page**: [`/start/getting-started/integrate/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/integrate/q/integration/flutter)

**Feedback**:
At this stage there will be this error:

Amplify plugin was not added
An error occurred while configuring Amplify: AmplifyException(message: Amplify plugin AmplifyDataStore was not added successfully., recoverySuggestion: We currently don't have a recovery suggestion for this exception., underlyingException: MissingPluginException(No implementation found for method configureDataStore on channel com.amazonaws.amplify/datastore))

And also the github Repo is not corresponding to the one of the tutorial.

**Comment by abdallahshaban557** [comment]
Hi @endriv - are you seeing this error when trying to run your app on the browser maybe? You mentioned the GH repo is not corresponding to one of the tutorials, can you elaborate on that?

**Comment by endriv** [comment]
Thank you @abdallahshaban557. Yes I confirm you that I was running a web emulator and that on an iPhone one I dont get the issue. Regarding the github repo the differences are on the new folders [pages](https://github.com/cshfang/amplify-flutter-datastore-starter/tree/main/amplified_todo/lib/pages) and
[widgets](https://github.com/cshfang/amplify-flutter-datastore-starter/tree/main/amplified_todo/lib/widgets) but I think this is just a better version of the code source. Btw I get an issue now with amplify push and cant login to the Studio if I want to deploy my application but I will raise un other issue ;-)
All the best.
