### ISSUE TITLE
Opportunity to better educate user on availability of Next.js and React-Native getting started guides

### ISSUE THREAD

**Issue by plug-n-play** [aws-amplify/docs#4316]
**Describe the bug**
On home page, in the Hero section, we don't have direct links for Next.js and React-Native Guides.
![image](https://user-images.githubusercontent.com/6245927/169039364-200fb14a-8e47-40a5-933c-768fb1ec7cbc.png)

**To Reproduce**
1. Go to https://docs.amplify.aws/
2. Click on 'React.js' logo
3. It takes user to [Getting started guide for React.js & AWS Amplify](https://docs.amplify.aws/start/q/integration/react/?sc_icampaign=react-start&sc_ichannel=docs-home)

**Expected behavior**
A new user looking for Next.js or React Native guides would not know upfront if there are dedicated pages for these entities. Instead, clicking React.js logo in the Hero section of [Getting started guide for React.js & AWS Amplify](https://docs.amplify.aws/start/q/integration/react/?sc_icampaign=react-start&sc_ichannel=docs-home) should either open the getting started [page ](https://docs.amplify.aws/start/) listing all technologies, or open a new page where user can choose between all React.js flavors, namely: React.js, Next.js or React Native

i.e., clicking React.js logo on Home page should either open the existing page with all libraries/frameworks listed:
![image](https://user-images.githubusercontent.com/6245927/169039759-58f6a65c-c87a-42bd-b858-aa7bdc70e2fd.png)

or we should create a new page to list React.js related libraries/Frameworks similar to:
![image](https://user-images.githubusercontent.com/6245927/169040034-f971d840-576d-4114-aaa8-47f59bbaeb12.png)

**Comment by nadetastic** [comment]
@plug-n-play Thank you for opening this issue, the docs landing page has been updated to link the additional integrations.
