### ISSUE TITLE
Document Directive API

### ISSUE THREAD

**Issue by taneba** [aws-amplify/docs#4320]
I opened this issue based on the conversation on discord.

In the latest documentation, there's no detail pages about each directive's API.
It's great to have one that we can use it as a API reference, like we had in the old docs. ([link](https://docs.amplify.aws/cli-legacy/graphql-transformer/directives/))

API document would have:
- A short definition or explanation of what the directive is about. 
- API Definition
- Basic usage
- Advanced usage 
- caveats

Additionally, I'd like to know how it affects corresponding AWS resources (e.g. index is going to create GSI in DynamoDB).

**Comment by Voyager-Two** [comment]
+1
For example, there is no explanation as to how we can implement a modified AuthRule directive:
https://docs.amplify.aws/cli/graphql/authorization-rules/#how-it-works
![Screen Shot 2022-06-20 at 8 17 21 PM](https://user-images.githubusercontent.com/3676208/174812363-29a21ba7-83d8-4998-86ec-ce6b3487b0b1.png)
