### ISSUE TITLE
[Feedback] Amplify iOS Advanced Workflows

### ISSUE THREAD

**Issue by Leinadzet** [aws-amplify/docs#4322]
**Page**: [`/lib/graphqlapi/advanced-workflows/q/platform/[platform]`](https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/ios)

**Feedback**:

I have been trying to get that work for the last 3 hours - how do I get a nested object?

The nested data section does not help at all - its very unclear how to work with the docs. 

If I copy paste this:

```
extension GraphQLRequest {
    static func getPostWithComments(byId id: String) -> GraphQLRequest<Post.self> {
        let document = """
        query getPost($id: ID!) {
          getPost(id: $id) {
            id
            title
            rating
            status
            comments {
              items {
                id
                postID
                content
              }
            }
          }
        }
        """
        return GraphQLRequest<JSONValue>(document: document,
                                         variables: ["id": id],
                                         responseType: Post.self)
    }
}
```

I get an error with says "'self' is not a member type of struct ...."

It also says nothing about how to query a list of nested data objects. 

I tried my luck with the JSONValue response but without luck. 

Is there anywhere a working example how to retrieve nested data? 

Thanks

Daniel

**Comment by atierian** [comment]
Closing this issue as the documentation has been updated.
