### ISSUE TITLE
[Feedback] amplify-meta.json' does not exist

### ISSUE THREAD

**Issue by jedgrant** [aws-amplify/docs#4329]
**Page**: [`/start/getting-started/data-model/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/data-model/q/integration/react)

**Feedback**:

Following the tutorial from the beginning, first it fails on the command "npm install aws-amplify @aws-amplify/ui-react" now as I try to run "npm install @aws-amplify/ui-react" and then continue, I run "amplify add api" which fails with an error "File at path: '.../react-amplified/amplify/backend/amplify-meta.json' does not exist" - So far, this tutorial is no fun.

**Comment by siegerts** [comment]
Hi @jedgrant , did you have any issues initializing your amplify project with `amplify init` before trying to add the API?

**Comment by jedgrant** [comment]
Yes. I started a new project that was entirely empty and got it to work, now however, after doing a few pulls, my backend folder is gone and running amplify init throws an error when I try to use that existing environment.

Error: File at path: '/Users/grantjed/wh-app/amplify/backend/backend-config.json' does not exist

Did an `amplify pull` using the appId from studio which got me the folder back, but now AppSync doesnt seem to work because the stuff I'm creating appears to be all local and I have no way to look at it. Either way, I think this particular issue is resolved, from a tutorial feedback perspective, it would be really helpful to have some guidance about common troubleshooting issues.

Thanks for your quick responses.

**Comment by josefaidt** [comment]
Hey @jedgrant :wave: sorry to hear about the rough first experience, and we appreciate the feedback! I'm curious, prior to receiving the initial error regarding the missing `amplify-meta.json` file was there an existing `amplify` directory present?

> AppSync doesnt seem to work because the stuff I'm creating appears to be all local and I have no way to look at it.

What sort of issues are you running into using the created GraphQL API? It will create local records when using `amplify mock api`, however otherwise it will create records in the cloud instance

**Comment by jedgrant** [comment]
Yes, the amplify directory existed even with those errors. But there were very few files.

For the stuff that appeared to be happening locally, I kept creating records, which I could render in a react app, but when I went to the Amplify Studio console's Content page for those tables, no data displayed no matter how many times I reloaded the page.

Today, when I re-pulled because the amplify backend folder disappeared (I did delete my node_modules direct and reinstall everything which could have done that). After I did that, AppSync appeared to be working again. For the moment, everything appears to be working.

For what it's worth, I had started a basic react projects and make some good progress with mock data before even finding Amplify, and I tried to plug that directly into the project using the getting started tutorial... which failed and broke the project in a way I couldn't fix, so I created a new project, copied the JS files over,  add the packages etc and then I could get it to work with Amplify.

**Comment by jedgrant** [comment]
To be honest, I think I first made the project in the amplify console, then tried to follow the tutorial. During which, I killed the setup process when it was asking questions about app ids and secrets. After that, I believe it broke. Unfortunately, I don't remember the exact steps.

**Comment by siegerts** [comment]
Closing for now. we can reopen if it happens again in the future, possibly against the CLI repo.
