### ISSUE TITLE
[Feedback]Problem with render inputs

### ISSUE THREAD

**Issue by Jgmaza** [aws-amplify/docs#4330]
**Page**: [`/start/getting-started/auth/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/auth/q/integration/react/#authentication-with-amplify)

**Feedback**:

There are a problem with inputs in the code, you should solve the code

**Comment by siegerts** [comment]
Hi @Jgmaza, can you provide a bit more info here - what inputs specifically?

**Comment by siegerts** [comment]
Have you seen these docs for the UI component? Wondering if these can help https://ui.docs.amplify.aws/react/components/authenticator

**Comment by Jgmaza** [comment]
Ok, thanks!. I found Access Auth State and maybe that can be the solution to prevent re-renders, but you can follow the documentation of amplify + react and see the problem

**Comment by Jgmaza** [comment]
I solved with withAuthenticator, It is in the documentation, thanks!

**Comment by siegerts** [comment]
Awesome!
