### ISSUE TITLE
[Feedback] Not enough information to know how to consecutively save with useState

### ISSUE THREAD

**Issue by jedgrant** [aws-amplify/docs#4336]
**Page**: [`/lib/datastore/data-access/q/platform/[platform]`](https://docs.amplify.aws/lib/datastore/data-access/q/platform/js)

**Feedback**:

It would be very helpful if there were some info here about state and iterative saving. If I query a record, store it in a state variable, then try to update the data with `DataStore.save()` it works fine the first time but not subsequent times unless I refetch that record every time I want to update it. This is likely my lack of experience, but I'd love to see this information added or alluded to in some way. Here's the example:

**This works, but seems like a waste when I can store that data in state as I continue typing on a text area and update if the user stops typing for 2 seconds**
```
async function saveChanges(e) {
    const original = await DataStore.query(Section, section.id);
    const updatedSection = await DataStore.save(
      Section.copyOf(original, (updated) => {
        updated.content = content;
      })
    );
    setSection(updatedSection);
}
```

**This works once, then fails every consecutive time until reload**
It appears that because I am unable to cut the updated item with the right version and other data the save function is rejected without a failure message.
```
const [section, setSection] = useState();
useEffect(() => {
    fetchSection();
  }, []);
async function fetchSection() {
  const s = await DataStore.query(Section, id);
  setSection(s);
}
//Version 1 - doesn't work
async function saveChanges(e) {
    const updatedSection = await DataStore.save(
      Section.copyOf(section, (updated) => {
        updated.content = content;
      })
    );
    setSection(updatedSection);
}
//Version 2 - doesn't work
async function saveChanges(e) {
    await DataStore.save(
      Section.copyOf(section, (updated) => {
        updated.content = content;
      })
    ).then(s => {
      setSection(s);
    });
}
```

In the tutorial, it would be VERY helpful to know how to get the updated version of the record (after saving) in a way that will allow me to use it to save again without having to run a query. Also, clicking around the documentation doesn't provide details. The promise also doesn't return what's in the database. The version is wrong.

Some clarity would be helpful.

**Comment by jedgrant** [comment]
This works, but it also appears others issues indicated messing with the version is a bad thing? 

```
async function saveChanges(e) {
    const updatedSection = await DataStore.save(
      Section.copyOf(section, (updated) => {
        updated.content = content;
        updated._version = section._version;
      })
    ).then(x => {
        return x;
    });
    setSection(updatedSection);
  }
  ```

**Comment by jedgrant** [comment]
For what it's worth, he's the data difference on first and second save along with the function I attempted to use to update the data onChange.

**First save**
![image (2)](https://user-images.githubusercontent.com/2252647/170555598-de1ea90e-5332-4e81-93a2-63d48fadb0ff.png)

**Second save**
![image (3)](https://user-images.githubusercontent.com/2252647/170555771-81ca8c72-f1fe-4107-94e0-62945c4be6c0.png)

**Comment by rachelnabors** [comment]
Hey hey, we addressed this in this PR: https://github.com/aws-amplify/amplify-js/pull/10471 Thanks so much for your feedback!!
