### ISSUE TITLE
[Feedback]FEEDBACK_TITLE_HERE

### ISSUE THREAD

**Issue by AzharRaeisi** [aws-amplify/docs#4346]
**Page**: [`/lib/datastore/setup-auth-rules/q/platform/[platform]`](https://docs.amplify.aws/lib/datastore/setup-auth-rules/q/platform/flutter)

**Feedback**:

Tried to setup datastore with multi auth

**Comment by offlineprogrammer** [comment]
Duplicated https://github.com/aws-amplify/docs/issues/4347
