### ISSUE TITLE
Missing Local Development guide for File Storage under Studio docs

### ISSUE THREAD

**Issue by ilia-luk** [aws-amplify/docs#4357]
**Page**: [`https://docs.amplify.aws/console/storage/develop/`](https://docs.amplify.aws/console/storage/develop/)

navigated from: https://docs.amplify.aws/console/storage/file-storage/#to-set-the-authorization-modes-on-new-file-storage

**Comment by arundna** [comment]
@ilia-luk - Thanks for raising this issue! The page was removed by the PR - https://github.com/aws-amplify/docs/pull/3779/files. I'm investigating the cause for this and will keep you posted.
