### ISSUE TITLE
Amplify CLI doc is missing a complete reference of options available

### ISSUE THREAD

**Issue by manu2504** [aws-amplify/docs#4398]
**Is your feature request related to a problem? Please describe.**
I'm always quite frustrated when getting permission issues because I'm not using the right aws profile. The doc does not mention a way to specify the profile as an option to the `amplify` command line.

**Describe the solution you'd like**
Amplify CLI probably provides a way to specify the aws profile to use to perform an amplify operation (such as `amplify publish`), like with a `--profile` option). However the [docs](https://docs.amplify.aws/cli/), simply does not provide this (or it is very well hidden...).

**Comment by ykethan** [comment]
Closing this in favor of https://github.com/aws-amplify/docs/issues/2110. Please feel free in adding additional information  on your use case.
