### ISSUE TITLE
[ios][storage] Add guide for uploading security scoped resources

### ISSUE THREAD

**Issue by atierian** [aws-amplify/docs#4405]
**Is your feature request related to a problem? Please describe.**
Uploading files stored in the iCloud Drive is a common use case. Amplify currently doesn't have any guides on how to properly handle security scoped resources (in iCloud Drive).

**Describe the solution you'd like**
Add a guide explaining how to properly access and upload security scoped resources.

**Describe alternatives you've considered**
N/A

**Additional context**
[Original issue](https://github.com/aws-amplify/aws-sdk-ios/issues/4044) that inspired this issue, including a (simplified) solution.

**Comment by phantumcode** [comment]
Documentation updated, closing issue.
