### ISSUE TITLE
[Feedback]Update Next.js tutorial to use new UI components

### ISSUE THREAD

**Issue by LittleSurimi** [aws-amplify/docs#4408]
**Page**: [`/start/getting-started/data-model/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/data-model/q/integration/next)

**Feedback**:

The code for pages/index.js is outdated. the component 'AmplifyAuthenticator' has been replaced https://aws.amazon.com/blogs/mobile/amplify-uis-new-authenticator-component-makes-it-easy-to-add-customizable-login-pages-to-your-react-angular-or-vue-app/

**Comment by abdallahshaban557** [comment]
This has now been addressed!
