### ISSUE TITLE
[Feedback] Directory naming ambigouos

### ISSUE THREAD

**Issue by tbelmega** [aws-amplify/docs#4432]
**Page**: [`/start/getting-started/setup/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/setup/q/integration/react)

**Feedback**:

Hi, thanks for the great tutorial!

The only thing that confused me a little was the difference between "your projects directory" and "From the root of the project".

In the step "Initialize a new backend" it says "From the root of the project, run". I wasn't sure if this refers to the root of the react app that was referred to before ("Now that we're in the root of the project") or the parent folder that I considered the actual root of my project, referred to before as "From your projects directory".

Since it sounded ambiguous and my (beginner's) expectation was that the overall project would live outside of the frontend directory, I ran "amplify init" in the parent directory. 
But know I think that's not intended, because amplify init placed aws-export.js in the ../src instead of ./src

I think I figured it out now, but future readers might benefit from a clarification in the tutorial.

Keep up the great work!

**Comment by arundna** [comment]
@tbelmega -👋 Thanks for providing this feedback. We've received feedback on the directory structure, and your suggestion sounds great. We'll add clarity to the tutorial for explicit information in the path and directory structure to avoid errors.

**Comment by vimode** [comment]
Hello,

I would like to fix this small issue in the docs. 

As per my understanding the `amplify init` command should be run while being in the `react-amplified` folder. 

I think just clarifying that folder name wherever the term *root of the project* (2 instances) is used should give a clear understanding of the directory structure. 

Thank you.

**Comment by Safadurimo** [comment]
I ran into the exact same issue. @vimode , Go ahead and fix that!

**Comment by vimode** [comment]
@Safadurimo Thanks for alerting it.
I am still waiting on someone from the team to assign me or at least give me a go ahead that this indeed needs to be updated.

**Comment by rachelnabors** [comment]
You don't have to ask for permission to submit a PR! Go for it, @vimode <3

**Comment by vimode** [comment]
@rachelnabors  I misunderstood the guidelines of contributing, I mistook *mention you are working on the issue* as I need permission from maintainers. 

Thank you for clarifying that. 

As I see now, most of it is fixed in PR #4676 
So my PR updates only the one that was missed.
