### ISSUE TITLE
[Feedback]FEEDBACK_TITLE_HERE

### ISSUE THREAD

**Issue by FireAndIceFrog** [aws-amplify/docs#4437]
**Page**: [`/cli-legacy/graphql-transformer/key`](https://docs.amplify.aws/cli-legacy/graphql-transformer/key)
This page is deprecated and should be noted as such. I tried to use the @key directive and it said `Your GraphQL Schema is using "@key", "@connection" directives from an older version of the GraphQL Transformer. Visit https://docs.amplify.aws/cli/migration/transformer-migration/ to learn how to migrate your GraphQL schema.`

Please update your documents :)

**Comment by offlineprogrammer** [comment]
Hi @FireAndIceFrog 

This is the legacy transformer docs as marked in the bottom lefthand corner of the page. It is still valid if you are using the legacy transformer.

Thanks
Mo
