### ISSUE TITLE
[Feedback] How to add Amplify as dependency in my SPM package (not in my project)

### ISSUE THREAD

**Issue by anandhoum** [aws-amplify/docs#4466]
**Page**: [`/lib/devpreview/getting-started/q/platform/[platform]`](https://docs.amplify.aws/lib/devpreview/getting-started/q/platform/ios)

**Feedback**: 

https://docs.amplify.aws/lib/devpreview/getting-started/q/platform/ios/#next-steps has steps to add Amplify to the project directly. But what I am looking for is "How to add it to my SPM package"

Adding below lines in Package.swift is giving error when I try to run XCTestCase test
dependencies: [
        // Dependencies declare other packages that this package depends on.
        .package(url: "https://github.com/aws-amplify/amplify-ios", from: "1.27.0"),
    ]

**Comment by anandhoum** [comment]
<img width="1116" alt="Screenshot 2022-07-15 at 7 51 26 AM" src="https://user-images.githubusercontent.com/108971401/179133891-ec58c8e3-623d-4b20-9a38-fa6e7c7ba641.png">

**Comment by anandhoum** [comment]
Resolved myself. This is how it should look like.

`let package = Package(
    name: "MyLibrary2",
    platforms: [.iOS(.v15)],
    products: [
        // Products define the executables and libraries a package produces, and make them visible to other packages.
        .library(
            name: "MyLibrary2",
            targets: ["MyLibrary2"]),
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
        //.package(url: "https://github.com/aws-amplify/amplify-ios", from: "1.27.0"),
        .package(url: "https://github.com/daltoniam/Starscream.git", from: "4.0.4"),
        .package(url: "https://github.com/aws-amplify/amplify-ios.git", from: "1.27.0")
        
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages this package depends on.
        .target(
            name: "MyLibrary2",
            dependencies: ["Starscream", .product(name: "Amplify", package: "amplify-ios")]),
        .testTarget(
            name: "MyLibrary2Tests",
            dependencies: ["MyLibrary2"]),
    ]
)`

**Comment by atierian** [comment]
Thanks for opening this. Using Amplify as a dependency of another Swift Package is not the typical use case. So including this in the documentation is likely to lead to confusion. 

Here's an Apple reference on the adding creating a Swift package should anyone come along this issue in future. [Create a standalone Swift package with Xcode](https://developer.apple.com/documentation/xcode/creating-a-standalone-swift-package-with-xcode)
