### ISSUE TITLE
Mobile View: API references navigates to Page Not Found

### ISSUE THREAD

**Issue by minbi** [aws-amplify/docs#447]
**Describe the bug**
API link in menu navigates to Page Not Found.

**To Reproduce**
1. Go to https://aws-amplify.github.io/docs
2. Click on Menu
3. Click on API in list
4. Page Not Found

**Expected behavior**
Show me options to choose between JS, Android, and iOS.

**Screenshots**
![image](https://user-images.githubusercontent.com/6525769/52582673-98bea300-2de2-11e9-8a70-c84671838478.png)

**Smartphone (please complete the following information):**
 - OS: Android
 - Browser Firefox 65.0 or Chrome 71.0.3578.99

**Comment by dblock** [comment]
![amplify-broken-link](https://user-images.githubusercontent.com/542335/55290116-d7adb580-539c-11e9-99d6-8a2ea5986ef1.gif)

I was trying to debug this and I can't for the life of me figure out what's going on and how the link is generated in that menu. Locally it always works.

Fail: /docs/media/quick_start?platform=purejs
Pass: /js/start?platform=purejs

I think it's something in the production _config.yml that we're not seeing in this repo.
