### ISSUE TITLE
AmplifyChatbot was not found in '@aws-amplify/ui-react'

### ISSUE THREAD

**Issue by AvinandanBandyopadhyay** [aws-amplify/docs#4474]
export 'AmplifyChatbot' (imported as 'AmplifyChatbot') was not found in '@aws-amplify/ui-react' (possible exports: Alert, AmplifyProvider, Authenticator, Badge, Button, ButtonGroup, Card, CheckboxField, Collection, ComponentClassNames, ComponentClassObject, ComponentPropsToStylePropsMap, ComponentPropsToStylePropsMapKeys, Divider, Expander, ExpanderItem, FieldGroupIcon, FieldGroupIconButton, Flex, Geocoder, Grid, Heading, Icon, Image, Link, Loader, LocationSearch, MapView, Menu, MenuButton, MenuItem, Pagination, PasswordField, PhoneNumberField, Placeholder, Radio, RadioGroupField, Rating, ScrollView, SearchField, SelectField, SliderField, StepperField, SwitchField, TabItem, Table, TableBody, TableCell, TableFoot, TableHead, TableRow, Tabs, Text, TextAreaField, TextField, ThemeProvider, ToggleButton, ToggleButtonGroup, View, VisuallyHidden, components, createTheme, defaultDarkModeOverride, defaultTheme, primitives, translations, useAmplify, useAuthenticator, useBreakpointValue, usePagination, useTheme, withAuthenticator)

with "@aws-amplify/ui-react": "^3.1.0"

**Comment by siegerts** [comment]
HI @AvinandanBandyopadhyay, thanks for raising. Can you please provide more information on how you got to this state. Was this going through a specific guide? Or using the library here - https://ui.docs.amplify.aws/react/legacy-components/chatbot#amplify-id-9 ?

**Comment by siegerts** [comment]
Closing for now. Please reopen with more detail if the issue persists.
