### ISSUE TITLE
Flutter Online Sync Requirements

### ISSUE THREAD

**Issue by jkmaina** [aws-amplify/docs#4477]
**Page**: [`/start/getting-started/setup/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/setup/q/integration/flutter)

**Feedback**:

The documentation needs to explicitly say that to enable online sync, the dependecies need to include the amplify api dependency.

> environment:
>   sdk: ">=2.15.0 <3.0.0"
> 
> dependencies:
>   flutter:
>     sdk: flutter
> 
>   amplify_flutter: ^0.6.0
>   amplify_datastore: ^0.6.0
>  **amplify_api: ^0.6.0**

**Comment by abdallahshaban557** [comment]
This is further elaborated on in this section https://docs.amplify.aws/start/getting-started/add-api/q/integration/flutter/#add-api-and-auth-plugins
