### ISSUE TITLE
Android DataStore invalid code snippets

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/docs#4482]
**Describe the bug**
Android DataStore code snippets do not compile

**To Reproduce**
1a. See https://docs.amplify.aws/lib/datastore/data-access/q/platform/android/#predicates

Under "Kotlin - Callbacks"

```
Amplify.DataStore.query(Post::class.java,
    { posts ->
        while (posts.hasNext()) {
            val post = allPosts.next()
            Log.i("MyAmplifyApp", "Title: ${post.title}")
        }
    },
    { Log.e("MyAmplifyApp", "Query failed", it) }
)
```

It appears `allPosts` should be `posts`.

1b. Under Delete
![image](https://user-images.githubusercontent.com/1365977/181057335-cef3f6ca-be52-4ead-8725-cf129d294489.png)

Remove first sentence. This might require some work due to shared fragments

2a. See https://docs.amplify.aws/lib/datastore/real-time/q/platform/android/

```
Amplify.DataStore.observe(Post::class.java,
    { Log.i("MyAmplifyApp", "Observation began") },
    {
        val post = postChanged.item()
        Log.i("MyAmplifyApp", "Post: $post")
    },
    { Log.e("MyAmplifyApp", "Observation failed", it) },
    { Log.i("MyAmplifyApp", "Observation complete") }
)
```
"postChanged" should be "it" i think, here's a screenshot of the code in Android Studio
<img width="593" alt="image" src="https://user-images.githubusercontent.com/1365977/181048473-5cee10ca-c479-46fb-8a61-6e17a2fd45ee.png">

2b. Indentation on the RT page looks off
![image](https://user-images.githubusercontent.com/1365977/181048114-1b5951fe-c189-4935-856d-a60d18a3bcb8.png)

**Comment by rachelnabors** [comment]
Fixed with PR #4519
