### ISSUE TITLE
[Feedback] Mention version campatibility of nextjs in Tutorials

### ISSUE THREAD

**Issue by rcp522** [aws-amplify/docs#4491]
**Page**: [`/start/getting-started/setup/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/setup/q/integration/next)

**Feedback**:

Feedback on installing NextJS apps in the docs [[1]](https://docs.amplify.aws/start/getting-started/setup/q/integration/next/) [[2]](https://docs.amplify.aws/guides/hosting/nextjs/q/platform/js/#deploy-and-host-a-hybrid-app-ssg-and-ssr) . The first doc mentions using create-next-app which is an issue as create-next-app seems to only be able to install the canary release(12) even after attempting to run npx create-next-app@11. Both docs also don't mention that version 12 of Next is not yet supported and might work(but could run into issues). This becomes an issue as it might work and then down the line run into issues such as [2551](https://github.com/aws-amplify/amplify-hosting/issues/2551)

**Comment by nadetastic** [comment]
Hi @rcp522  👋, previously there was a limitation with Amplify hosting and Next JS support. Although this had not been in the _Amplify docs_, it has been mentioned in the _AWS Amplify docs_ at - https://docs.aws.amazon.com/amplify/latest/userguide/ssr-Amplify-support.html

As of today, Amplify does support the latest version of Next JS.

For future limitations, I will discuss with the team to also include this in the Amplify Docs.
