### ISSUE TITLE
Update required to Tutorial for Amplify Hosting 

### ISSUE THREAD

**Issue by PrecisionAquaculture** [aws-amplify/docs#4499]
**Page**: [`/start/getting-started/hosting/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/hosting/q/integration/js)

**Feedback**:

<!-- Reference the attached snip showing differences in the selectable  hosting deployment options --
![Amplify Docs Update Needed](https://user-images.githubusercontent.com/78007516/182074700-cc22545c-d1f5-4a50-a0e5-aae16d07f396.PNG)
>

**Comment by arundna** [comment]
@PrecisionAquaculture - Thanks for raising this issue. Do you have any specific feedback or errors encountered on the tutorial to add hosting to your app?
