### ISSUE TITLE
Update Getting Started Authentication section to display full example

### ISSUE THREAD

**Issue by westr33** [aws-amplify/docs#4502]
**Page**: [`/start/getting-started/auth/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/auth/q/integration/react)

**Feedback**:

<!-- I have found this tutorial to be very nice.  I am stuck on the "Add authentication" step "Create login UI".  for part 1 and 2, I see where you comment to add the "Todo logic here" and "Add Todo JSX here", but it is confusing.  It would be useful at this point in the tutorial to list the full code including step 1 and 2 code.  Then a simple explanation of what steps 1 and 2 code are doing.  I would like to see the "src/App.js" code after steps 1 and 2 have been completed.  Thanks.

**Comment by westr33** [comment]
**Page**: [`/start/getting-started/auth/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/auth/q/integration/react)

**Feedback**:

**Comment by alistairholmes** [comment]
@siegerts Hey, I see that there's no page for Flutter at the moment. I would like to contribute to that page as I already have a working example with Authentication. What would be the best way for me to go about contributing to this?

**Comment by salihgueler** [comment]
Hey @alistairholmes the example there is using the Authenticator UI libraries, are you planning to add that as well?

**Comment by rachelnabors** [comment]
@alistairholmes @salihgueler I love this enthusiasm! Please file a PR with this new section for the Flutter docs. You can reference the use of Amplify Libraries to add authentication vs the Next or React docs which use Amplify UI.

Meanwhile, @westr33, I believe an upcoming update to the tutorials will answer this problem for you. I'll update this here when they are all live!

**Comment by rachelnabors** [comment]
Should be addressed with https://github.com/aws-amplify/docs/pull/4676

Does this help, @westr33 ? https://docs.amplify.aws/start/getting-started/auth/q/integration/react/#create-login-ui
