### ISSUE TITLE
Provide documentation for TOTP flow for JS

### ISSUE THREAD

**Issue by abdallahshaban557** [aws-amplify/docs#4512]
**Is your feature request related to a problem? Please describe.**
As an Amplify JS customer, I want to have a clear description and walkthrough of how to setup TOTP authentication using the Amplify JS library, so that I do not have to spend a lot of time in setting up my application.

**Describe the solution you'd like**
Add a documentation page to the Authentication category documentation on docs.amplify.aws

**Additional context**
There are [steps](https://github.com/aws-amplify/amplify-js/issues/5271#issuecomment-1205797880) mentioned here on how to make TOTP work in Amplify JS

**Comment by cwomack** [comment]
Closing this after PR #4961 was merged in.
