### ISSUE TITLE
Clarity on File Access Levels for Storage - Public, Private and Protected

### ISSUE THREAD

**Issue by ksbains** [aws-amplify/docs#4513]
There should be a more clearer explanation between the levels. I created a s3 bucket that was NOT open to the public, however after uploading an image to my s3 bucket manually i could not get it to list. I saw that the "level" referred to the "prefix" which referred to having a directory named, "public" in my s3 bucket where my image should be in order to list it. This should be explained a lot clearer

**Comment by rachelnabors** [comment]
Thanks for your feedback, @ksbains! Can you provide a link to the page where you would expect this to be explained?

**Comment by nadetastic** [comment]
Hi @ksbains following up on this. The access levels are currently explained under `File access levels` section under each library. For example this link is for JS library - https://docs.amplify.aws/lib/storage/configureaccess/q/platform/js/

I'll go ahead and close this out, but feel free to update this issue.
