### ISSUE TITLE
[Feedback] Provided Example for Authorization does not provide package or version specifications

### ISSUE THREAD

**Issue by alexthemitchell** [aws-amplify/docs#4514]
**Page**: [`/lib/auth/delete_user/q/platform/[platform]`](https://docs.amplify.aws/lib/auth/delete_user/q/platform/js)

**Feedback**:

The function on this page uses `Auth.deleteUser()`; when importing as provided in previous examples, Auth.deleteUser does not appear to be a function for `aws-amplify 4.3.12` .

```
import { Auth } from 'aws-amplify';
```

```
TypeError: _awsAmplify.Auth.deleteUser is not a function
```

It seems that this example expects that we have imported `@aws-amplify/auth`
```
import Auth from '@aws-amplify/auth';
```

Then the provided example returns a `Promise<string | void>` that resolves to `SUCCESS` as expected.

**Comment by nadetastic** [comment]
Hi @alexthemitchell 👋

This issue was specific to `aws-amplify 4.3.12` and the current version should work without generating this error. Closing this out for now, but let me know if you have any questions/comments.
