### ISSUE TITLE
Document that Amplify Export only supports CDK v1

### ISSUE THREAD

**Issue by adilosa** [aws-amplify/docs#4523]
**Describe the bug**
The docs state that `amplify export` provides a CDK-compatible export of the Amplify backend. However, it actually only supports CDK v1 which is in maintenance mode and effectively deprecated. Users are misled into thinking this migration path is an option. 

Pending https://github.com/aws-amplify/amplify-cli-export-construct/issues/28, the docs should explicitly warn that this is only an option for CDK v1.

**Comment by sobolk** [comment]
`amplify-cli-export-construct` has been updated to support CDK v2.
