### ISSUE TITLE
[Feedback]code suggestion to fix no-unused-vars error for login UI code snippet

### ISSUE THREAD

**Issue by botanyhelp** [aws-amplify/docs#4537]
**Page**: [`/start/getting-started/auth/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/auth/q/integration/vue)

**Feedback**:

I get this error when running the **login UI** code snippet:

  20:10  error  'Authenticator' is defined but never used  no-unused-vars

I fix it by adding this line of code to my **./src/App.vue** file:

components: { Authenticator, },

..which now looks like this, in its entirety and runs okay with **npm run serve**

```
<template>
  <div id="app">
    <h1>Todo App</h1>
    <input type="text" v-model="name" placeholder="Todo name">
    <input type="text" v-model="description" placeholder="Todo description">
    <button v-on:click="createTodo">Create Todo</button>
  </div>
  <authenticator>
    <template v-slot="{ user, signOut }">
      <h1>Hello {{ user.username }}!</h1>
      <button @click="signOut">Sign Out</button>
    </template>
  </authenticator>
</template>

<script>
import { API } from 'aws-amplify';
import { createTodo } from './graphql/mutations';

import { Authenticator } from '@aws-amplify/ui-vue';
import '@aws-amplify/ui-vue/styles.css';

export default {
  name: 'app',
  components: { Authenticator, },
  data() {
    return {
      name: '',
      description: ''
    }
  },
  methods: {
    async createTodo() {
      const { name, description } = this;
      if (!name || !description) return;
      const todo = { name, description };
      await API.graphql({
        query: createTodo,
        variables: {input: todo},
      });
      this.name = '';
      this.description = '';
    }
  }
};
</script>
```

**Comment by siegerts** [comment]
Hi @botanyhelp, thanks for raising. The guide is using Vue 3 and the snippet referenced above in the docs is within a `script setup` tag for the composition API. It may just be the use of the Options API here that is causing that without the explicit reference to the component.

**Comment by botanyhelp** [comment]
Thanks @siegerts for the quick response, you may close this Issue.  I have not made it yet, to learning Composition API.  Vuex, pinia, nuxt and other sweets have consumed me and gotten me to ignore learning about Composition API syntax.  These docs.amplify.aws are excellent, keep up the great work!
