### ISSUE TITLE
[Feedback]Ionic Angular subscribe function error

### ISSUE THREAD

**Issue by BinarySyrup** [aws-amplify/docs#4542]
**Page**: [`/start/getting-started/data-model/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/data-model/q/integration/ionic)

**Feedback**:

On the last section of [Connect frontend to API](https://docs.amplify.aws/start/getting-started/data-model/q/integration/ionic/#connect-frontend-to-api), the "ngOnInit" to "setup a subscription on app start" fails to compile.  I get the following error on the "subscribe" function name:
`this.apiService.OnCreateTodoListener.subscribe((evt) => {`

TS2339: Property 'subscribe' does not exist on type '(filter?: ModelSubscriptionTodoFilterInput) => Observable  __SubscriptionContainer, "onCreateTodo">>>'.

**Comment by rachelnabors** [comment]
We're removing this guide in the near future, I'm afraid.
