### ISSUE TITLE
[Feedback] Remove lambda functions from an API gateway

### ISSUE THREAD

**Issue by MarcoDo99** [aws-amplify/docs#4543]
**Page**: [`/cli`](https://docs.amplify.aws/cli)

**Feedback**:

It would be nice to be able to remove lambda functions from an API gateway. Right now, I can not remove the lambda function (error message: Resource cannot be removed because it has a dependency on another resource, Dependency: API Gateway)
and it is not possible to change the runtime of a lambda function (amplify update function does not have this capability)

**Comment by josefaidt** [comment]
Hey @MarcoDo99 :wave: thanks for raising this! As we look to improve the experience here, please manually replace `12.x` in your function's CloudFormation template with `14.x` or `16.x`. The DX enhancement is being tracked here https://github.com/aws-amplify/amplify-cli/issues/10894

> It would be nice to be able to remove lambda functions from an API gateway. Right now, I can not remove the lambda function (error message: Resource cannot be removed because it has a dependency on another resource, Dependency: API Gateway)

To clarify, are you looking for an improvement to the `amplify remove function` workflow where it also disassociates from the REST API and automatically removes the API route? If so would you mind filing that as a [feature request](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=2.feature_request.yaml) on the CLI repo? I think this would be a great feature request

**Comment by MarcoDo99** [comment]
Hey @josefaidt, yes, I have filed a feature request to improve the ```amplify remove function``` workflow.
