### ISSUE TITLE
Incorrect case for userId attributes for Analytics updateEndpoint

### ISSUE THREAD

**Issue by KeiSugiyasu** [aws-amplify/docs#4552]
**Page**: [`/lib/analytics/getting-started/q/platform/[platform]`](https://docs.amplify.aws/lib/analytics/getting-started/q/platform/js)

**Feedback**:

In my app it doesn't work.
```
Analytics.updateEndpoint({ userId: 'hogehoge' }).
```

It works.
```
Analytics.updateEndpoint({ UserId: 'hogehoge' }).
```

So I think the 'userId' parameter in the below link needs to be modified to 'UserId'.
[Update Endpoint](https://docs.amplify.aws/lib/analytics/getting-started/q/platform/js/#update-endpoint)

**Comment by siegerts** [comment]
Hi @KeiSugiyasu, thanks for raising - are you interested in opening a PR for this?

**Comment by KeiSugiyasu** [comment]
I'm sorry, it's my mistake.

I have read amplify source code and found both work fine.
```
Analytics.updateEndpoint({ userId: 'hogehoge' })
Analytics.updateEndpoint({ UserId: 'hogehoge' })
```

So when I reported this issue I should have made some mistake.

Please accept my apologize for taking your time for my mistake.

I close this ticket.
