### ISSUE TITLE
Error login facebook with ios

### ISSUE THREAD

**Issue by hieunv12** [aws-amplify/docs#4581]
Hi everyone i am a newbie and currently i am a mobile developer(i am using React Native platform) i am having a problem with login social. I followed the instructions but the problem occurs.
1 - I am trying to login with facebook social.
2- redirectSignIn is a schema for users to return to the app but safari cannot return giving an invalid url error
3- I tried with inappbrowser-reborn like in the tutorial, the path I get is: myapp//?code=...&state=...
but Linking.openUrl() doesn't seem to work on IOS.
Can anyone help me in this matter ? thank you very much.

**Comment by offlineprogrammer** [comment]
@hieunv12 In #4580 it seems you passed this issue correct? if not whats the different between you setup on #4580 and this one?

**Comment by siegerts** [comment]
Hi @hieunv12 , following up here. Does @offlineprogrammer 's comment help?

**Comment by rachelnabors** [comment]
I'm going to assume that thumbs up was a yes and close :)
