### ISSUE TITLE
Need "as you go" examples of the app.js in tutorial..

### ISSUE THREAD

**Issue by andrewwaites** [aws-amplify/docs#4603]
**Page**: [`/start/getting-started/auth/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/auth/q/integration/react)

**Feedback**:

Wrap your application with the withAuthenticator component.

and the following code snippet ... do not make it clear AT ALL how to wrap the code. I had followed the build on the previous page and added a data entry form then went on to add authentication and I have tried guessing what "wrap the application" means but with no joy whatsoever. My apologies for being a react newbie but this is a newbie page so....

I tried just adding that snippet below the existing code but (unsurprisingly) it was unhappy with 2 entry points. I tried munging to a single entry point but that blows up, etc.

What would be INCREDIBLY USEFUL here is a separate snippet that was headed: "This is what your entire app.js file should look like now"

**Comment by siegerts** [comment]
Hi @andrewwaites, following up here on @tannerabread 's comment. Does that help?

**Comment by rachelnabors** [comment]
We've got a tutorial edit that I hope will clarify this! Will update here as soon as it launches

**Comment by siegerts** [comment]
ref - https://github.com/aws-amplify/docs/pull/4676

**Comment by rachelnabors** [comment]
Does this help, @tannerabread ? https://docs.amplify.aws/start/getting-started/auth/q/integration/react/#create-login-ui
