### ISSUE TITLE
Amplify simply won't install

### ISSUE THREAD

**Issue by Arnav7501** [aws-amplify/docs#4607]
**Page**: [`/cli/start/install`](https://docs.amplify.aws/cli/start/install)

**Feedback**:

Have tried for several hours, I installed the client, but whenever i try to run an amplify command, i get this error
zsh: command not found: amplify

**Comment by tannerabread** [comment]
Hi @Arnav7501 👋 
What is your OS/environment and which command are you trying to run that is throwing that error?

**Comment by tannerabread** [comment]
it's possible that `npm bin -g` is not in your `PATH`

try running:
```bash
PATH=$PATH:$(npm bin -g)
```

**Comment by siegerts** [comment]
Hi @Arnav7501 , following up here on @tannerabread 's comment. Does that help?

**Comment by Arnav7501** [comment]
I get npm ERR! bin (not in PATH env variable)

**Comment by tannerabread** [comment]
```bash
echo 'export PATH=$(npm bin -g):$PATH' >> ~/.profile
```

This should solve that problem and allow you to use the amplify command

**Comment by Arnav7501** [comment]
worked like a charm, thanks so much

**Comment by tannerabread** [comment]
Closing this as completed. If you experience any more issues feel free to open another issue or find us on discord!

Thank you!
