### ISSUE TITLE
Documentation on Identity ID for Storage is misleading

### ISSUE THREAD

**Issue by Jordan-Nelson** [aws-amplify/docs#4608]
**Describe the bug**

[This page](https://docs.amplify.aws/lib/storage/configureaccess/q/platform/flutter/) has the following text:

> For protected and private access, the [IDENTITY_ID] below corresponds to the unique ID of the user. Once the user has signed in, the [IDENTITY_ID] can be retrieved from the session by accessing the identity id. See [Accessing credentials](https://docs.amplify.aws/lib/auth/access_credentials/q/platform/flutter/) to retrieve the identity id, and use this as the unique ID of the authenticated user.

The first sentence is misleading, as "the unique ID of the user" could be interpreted as the Cognito User ID. The next sentence links to more detailed docs on fetching the identity ID, but unless the customer clicks through and reads those docs, it is not clear what value to use.

This came out of a discussion on Discord, where a customer misunderstood what "the unique ID of the user" was referring to.

This applies to iOS, Android, and Flutter.

**Comment by NikaHsn** [comment]
aws-amplify/amplify-flutter#3517

**Comment by NikaHsn** [comment]
aws-amplify/amplify-flutter#3517

**Comment by NikaHsn** [comment]
aws-amplify/amplify-flutter#3517

**Comment by NikaHsn** [comment]
aws-amplify/amplify-flutter#3517

**Comment by tjleing** [comment]
Looks like this was actually completed for all platforms in #5742, not just Flutter.  Closing.
