### ISSUE TITLE
[Feedback] please include "last updated" date at top of docs

### ISSUE THREAD

**Issue by renschler** [aws-amplify/docs#4613]
**Page**: [`/guides/hosting/nextjs/q/platform/[platform]`](https://docs.amplify.aws/guides/hosting/nextjs/q/platform/js)

**Feedback**:

It would be helpful if the documentation had a date stamp saying when it was lasted updated.

**Comment by siegerts** [comment]
Hi @renschler, thanks for raising this. I'm going to close this in favor of the related feature request - https://github.com/aws-amplify/docs/issues/4161
