### ISSUE TITLE
[Feedback] Angular Update don't work

### ISSUE THREAD

**Issue by phfoxer** [aws-amplify/docs#4616]
**Page**: [`/start/getting-started/data-model/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/data-model/q/integration/ionic)

**Feedback**:

In the documentation have no examples about  this.apiService.UpdateTodo, when a update is fire do not work

**Comment by siegerts** [comment]
Hi @phfoxer, thanks for raising. Is there an error thrown? Or just the service is not updated?

**Comment by siegerts** [comment]
Is there an error, or do you have a code sample? Just trying to get more context to narrow down :)

**Comment by rachelnabors** [comment]
We updated the Angular getting started guide with your feedback. Thank you very much!
