### ISSUE TITLE
Improve docs around identify broken components 

### ISSUE THREAD

**Issue by mauerbac** [aws-amplify/docs#4618]
More clarification around "how to identify broken Components" in order to update the same as per the documentation.
https://docs.amplify.aws/console/uibuilder/figmatocode/#upgrading-figma-files

If possible could we please add more details around identification for the same in the existing documentation.

**Comment by ykethan** [comment]
https://github.com/aws-amplify/docs/commit/fd529f6c7b5c38013edc7baa8ecab39a179ae2c8
addresses this information. closing the issue
