### ISSUE TITLE
[Feedback] What is most recent version?

### ISSUE THREAD

**Issue by slefcourt27** [aws-amplify/docs#4629]
**Page**: [`/ui/storage/s3-image/q/framework/[framework]`](https://docs.amplify.aws/ui/storage/s3-image/q/framework/react)

**Feedback**:

It would be great to say the most recent version on the webpage.  What version is each example associated with?  Current components that are in the documentation are not in my installation yet my installation is also not the oldest v1.

**Comment by siegerts** [comment]
Linking to https://github.com/aws-amplify/docs/issues/4161

**Comment by rachelnabors** [comment]
You might be looking for https://ui.docs.amplify.aws/react/components/image
The UI docs moved to a new site. We need to set up redirects.

**Comment by reesscot** [comment]
Closing this out, as the redirects for these components have been put in place.
