### ISSUE TITLE
[Feedback] (Amplify) & S3 Image Not Found

### ISSUE THREAD

**Issue by slefcourt27** [aws-amplify/docs#4630]
**Page**: [`/ui-legacy/q/framework/[framework]`](https://docs.amplify.aws/ui-legacy/q/framework/react)

**Feedback**:

Hi, I am confused because the legacy code offers: amplify-ui-react v1.x but mine is 3.2.1 and does not have the AmplifyS3Image or the S3Image. How can I use this component?

**Comment by siegerts** [comment]
Hi @slefcourt27 , thanks for opening. The S3Image is a deprecated component in the new UI Libraries - https://ui.docs.amplify.aws/react/legacy-components/storage. There is information listed on that page and also the supported component matrix is also listed here - https://github.com/aws-amplify/amplify-ui#component-matrix

**Comment by slefcourt27** [comment]
Thanks for your help @siegerts I appreciate it!
