### ISSUE TITLE
[Feedback] _version field required for graphql mutate

### ISSUE THREAD

**Issue by lien-dkseo** [aws-amplify/docs#4632]
**Page**: [`/lib/graphqlapi/mutate-data/q/platform/[platform]`](https://docs.amplify.aws/lib/graphqlapi/mutate-data/q/platform/flutter)

**Feedback**:

- no update with this code

```
Future<void> updateTodo(Todo originalTodo) async {
  final todoWithNewName = originalTodo.copyWith(name: 'new name');

  final request = ModelMutations.update(todoWithNewName);
  final response = await Amplify.API.mutate(request: request).response;
  print('Response: $response');
}
```

- maybe `_version` field is required to `API.mutate`.
- class `Todo` have no `_version` field
- how to get `_version` from https://docs.amplify.aws/lib/graphqlapi/query-data/q/platform/flutter/
- and how to save `_version` to class `Todo`

i use flutter 3.3.3 & amplify 10.2.1

**Comment by abdallahshaban557** [comment]
Hi @lien-dkseo  - the `_version` field is needed if you are using Datastore. Are you using Datastore or just GraphQL in your app?

**Comment by lien-dkseo** [comment]
Hi~ @abdallahshaban557 

using graphql

and.

https://docs.amplify.aws/lib/graphqlapi/mutate-data/q/platform/flutter/
examples is not working.

thankyou~

**Comment by abdallahshaban557** [comment]
Hi @lien-dkseo  - what is not working exactly? can you please paste your schema and your API call here for us to examine?

**Comment by lien-dkseo** [comment]
hi @abdallahshaban557 

no update with this code
```
Future<void> updateTodo(Todo originalTodo) async {
  final todoWithNewName = originalTodo.copyWith(name: 'new name');

  final request = ModelMutations.update(todoWithNewName);
  final response = await Amplify.API.mutate(request: request).response;
  print('Response: $response');
}
```
![image](https://user-images.githubusercontent.com/91306431/200449266-f2d679d8-b54d-484e-bd13-452c14583da1.png)
https://docs.amplify.aws/lib/graphqlapi/mutate-data/q/platform/flutter/

**Comment by abdallahshaban557** [comment]
Hi @lien-dkseo - so did you build the Todo schema, and then try to use an update and it didn't work? I tried following the steps in our docs and it worked for me. The _version field is needed only if you enable conflict detection and use the Datastore category. If you do not, then you don't need it.

**Comment by lien-dkseo** [comment]
Hi @abdallahshaban557 ~
`The _version field is needed only if you enable conflict detection and use the Datastore category. If you do not, then you don't need it.`
oh....
i'll check the config.
thank you.

**Comment by lien-dkseo** [comment]
@abdallahshaban557 
Then, datastore(enable conflict detection) and graphql(disable conflict detection) cannot be used at the same time?

**Comment by abdallahshaban557** [comment]
That is correct @lien-dkseo. That is one of the most heavily requested features - but we do not have it available just yet. Please upvote this issue - we use this feedback to help us prioritize new features! https://github.com/aws-amplify/amplify-category-api/issues/179

**Comment by lien-dkseo** [comment]
thank you~ @abdallahshaban557 

https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/flutter/#configure-api
```
Troubleshooting:
 The AWS API plugins do not support conflict detection.
 If AppSync returns errors about missing _version and _lastChangedAt fields, or unhandled conflicts, disable conflict detection.
 Run amplify update api, and choose Disable conflict detection.
 If you started with the Getting Started guide, which introduces DataStore, this step is required.
```
