### ISSUE TITLE
[Feedback]Flutter Example Bug

### ISSUE THREAD

**Issue by FearlessHyena** [aws-amplify/docs#4662]
**Page**: [`/start/getting-started/integrate/q/integration/flutter`](https://docs.amplify.aws/start/getting-started/integrate/q/integration/flutter)

**Feedback**:

The Flutter code example has a bug on line 151

```dart
todo.isComplete
```

should be 

```dart
todo.isComplete ?? false
```

Since the type is a `bool?` and not a `bool`

**Comment by salihgueler** [comment]
Hello @FearlessHyena, thank you for the issue.

Did you use the model that is created on the earlier page? 

Because the `isComplete` GraphQL property is not nullable:
```
type Todo @model @auth(rules: [{ allow: public }]) {
    id: ID!
    name: String!
    description: String
    isComplete: Boolean!
}
```

 and when the code is generated it creates the non-nullable code below: 

```
bool get isComplete {
  try {
    return _isComplete!;
  } catch(e) {
    throw new AmplifyCodeGenModelException(
        AmplifyExceptionMessages.codeGenRequiredFieldForceCastExceptionMessage,
        recoverySuggestion:
          AmplifyExceptionMessages.codeGenRequiredFieldForceCastRecoverySuggestion,
        underlyingException: e.toString()
        );
  }
}
```

If you can share your schema file and generated code maybe we can identify the problem better. Thanks!

**Comment by abdallahshaban557** [comment]
@FearlessHyena - can you please provide us with your schema to investigate this further?

**Comment by FearlessHyena** [comment]
Hi @abdallahshaban557 @salihgueler  it's been a while since I've worked on this so I don't have the code anymore, but I followed the documentation exactly and that error popped up
Maybe it's been fixed since?

**Comment by abdallahshaban557** [comment]
Hi @FearlessHyena  - yes, we've made changes to our docs and followed them ourselves and have not been able to experience a bug.
