### ISSUE TITLE
Join DOCStoberfest for Hacktoberfest 2022 🎃

### ISSUE THREAD

**Issue by siegerts** [aws-amplify/docs#4665]
Hi 👋!

The [AWS Amplify Docs](https://github.com/aws-amplify/docs) is participating in Hacktoberfest 2022! To learn more about the program, visit https://hacktoberfest.com/.

If you are interested in contributing to the Amplify docs project, please take these steps:

*Code*

- Review [how to participate in Hacktoberfest](https://hacktoberfest.com/participation/).
- Check for issues labeled [good first issue or hacktoberfest 🎃](https://github.com/aws-amplify/docs/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22%2C%22hacktoberfest+%F0%9F%8E%83%22) -- this is a good starting point.
- Review the [Contributor Guide](https://github.com/aws-amplify/docs/#amplify-framework-documentation) in the repo to understand what the contribution process is and how to get set up
- State that you want to tackle the issue in a comment and link to your PR
- When you submit your PR, add it as a comment to the issue (i.e `fixes #...`)
- The team will add the `hacktoberfest-accepted` label if the PR meets criteria and is accepted

*Low or No Code*

You can also contribute without writing code. Check out the different types of [low and no code](https://hacktoberfest.com/about/#low-or-non-code) submission options.

1. Contributors submitting low- or non-code content to projects should create a pr/mr to track it.
2. The team will add the hacktoberfest-accepted label to the PR if the content meets the above criteria and is accepted

Have a question? Reach out on the [Amplify Discord](https://discord.gg/amplify) Contributing Channel 🎉

**Comment by PanikaGupta** [comment]
hey! I want to participate in hacktoberfest
will this be counted in it.
can i do this?

**Comment by PanikaGupta** [comment]
hey! I want to participate in hactoberfest
can I work oh this and will it be counted?

**Comment by siegerts** [comment]
@PanikaGupta , please read through https://github.com/aws-amplify/docs/issues/4665#issue-1400071910 for more info.
