### ISSUE TITLE
[iOS] Missing CLI documentation for Signin With Apple

### ISSUE THREAD

**Issue by sebsto** [aws-amplify/docs#4678]
**Describe the bug**
Social Web SignIn doc, Signin With Apple tab, is lacking details about CLI parameters format 
https://docs.amplify.aws/lib/auth/social/q/platform/ios/#launch-social-web-ui-sign-in

The doc above does not show CLI 10.x question / response and give no clue about what parameter format is expected for the private key

**To Reproduce**
- amplify add auth, with Social Provider 
- select Signin With Apple 
- CLI asks for 4 parameter that are not documented at the URL above 

```
 Enter your Services ID for your OAuth flow:  com.amazonaws.amplify.workshop.landmarks.signin
 Enter your Team ID for your OAuth flow:  56U756R2L2
 Enter your Key ID for your OAuth flow:  3HL6GKYJ5L
 Enter your Private Key for your OAuth flow:  file://~/Downloads/AuthKey_3HL6GKYJ5L.p8
```

Deployment fails when the private key format is not correct. But without doc, developer have no clue what to enter. (I tried many, still do not know what the CLI expects) 

**Expected behavior**
The doc should describe the type of parameter expected and provide an example

The CLI does not validate the parameter (https://github.com/aws-amplify/amplify-cli/issues/8097)

**Comment by sebsto** [comment]
What worked for me was to enter the p8 file content on one single line

Example
`-----BEGIN PRIVATE KEY-----MIGT....ogty6P-----END PRIVATE KEY-----% `

<img width="1450" alt="2022-10-10_09-13-22" src="https://user-images.githubusercontent.com/401798/194816433-91482da5-c6b1-43f0-9d6c-23c7b6426dd0.png">

**Comment by siegerts** [comment]
Thanks for opening @sebsto! Is this something that you'd like to open a PR for? I can coordinate with the CLI team for review.

**Comment by sebsto** [comment]
I don't have bandwidth before re:Invent

**Comment by josefaidt** [comment]
This will be fixed via https://github.com/aws-amplify/amplify-cli/issues/8097

**Comment by sebsto** [comment]
@josefaidt Thank you. But the PR you mentioned did nor progress since September 2021.
