### ISSUE TITLE
Replace "Amplify framework" with "Amplify <Product>"

### ISSUE THREAD

**Issue by rachelnabors** [aws-amplify/docs#4691]
Currently we refer to an "Amplify framework" throughout our docs. This is a holdover from an earlier day. Amplify is now more of a suite of dev tools: Amplify Libraries, Amplify CLI, Amplify Studio, Amplify Hosting, and Amplify UI. 

Replace all instances of "Amplify framework" with "Amplify <Libraries/CLI/Studio/Hosting/UI>" or just refer to it as "Amplify" if the product is ambiguous.

**Comment by FidalgoMonica** [comment]
I will grab this one if you don't mind! Thanks :)

**Comment by MonicaFidalgo** [comment]
I will work on this one if you don't mind! Thanks :)

**Comment by rachelnabors** [comment]
Go for it!

**Comment by katiegoines** [comment]
This has been closed out with #4709. Thanks for your help @MonicaFidalgo!
