### ISSUE TITLE
Replace "we" with "you"

### ISSUE THREAD

**Issue by rachelnabors** [aws-amplify/docs#4692]
Replace "we" with "you" as below throughout the docs. Where possible, omit pronouns entirely.

# “We” are the authors; “you” is the reader

When writing, use “you” to refer to the reader, use “we” to refer to the team writing docs and building Amplify. Using “we” is popular in technical blogs and YouTube content where the author is individually taking the person on the other side of the screen on a journey. They may say things like, “To access the console, we just use `amplify console`.” This is confusing in official docs because they are written by many people and represent the team that builds Amplify. “We” should be used very rarely in documentation—only when explaining technical decisions or official recommendations where you could substitute “Amplify Team.”

## Don’t

Congratulations, our app is online!

Amplify recommends you use X because it’s been built to run with Feature Y.

Next, when we have finished deploying our app, we will add an Amplify UI component.

## Do

Congratulations, your app is online!

We recommend you use X because it’s been built to run with Feature Y.

Next, when the app has finished deploying, you will add an Amplify UI component.

**Comment by NizarAhamed97** [comment]
Can i work on this?

**Comment by YuriDevAT** [comment]
Hi @rachelnabors. I would love to work on the issue.

**Comment by rachelnabors** [comment]
@NizarAhamed97 Please go ahead and do so

**Comment by Lorenzohidalgo** [comment]
PR ready, @rachelnabors let me know if there is any issue with my changes. I've also added two proposed change to the PR description, let me know if you want me to implement it in the same PR 😉
