### ISSUE TITLE
Remove emojis from the docs

### ISSUE THREAD

**Issue by rachelnabors** [aws-amplify/docs#4693]
Emojis are a bit too personal for formal documentation. Find them and remove them!

**Comment by kaustav202** [comment]
can I take this up @rachelnabors

**Comment by haseeb-xd** [comment]
i wanna work on this

**Comment by YuriDevAT** [comment]
Hey  @rachelnabors I would love to work on this issue.

**Comment by AmirNaghibi** [comment]
@rachelnabors could you link a page in the documentation where an emoji is used?

**Comment by katiegoines** [comment]
Hi! Here is an example of a page that includes an emoji: https://docs.amplify.aws/start/getting-started/nextsteps/q/integration/react/

**Comment by rachelnabors** [comment]
This one will be a little tough because there are many emojis in the world!

**Comment by Lorenzohidalgo** [comment]
PR ready, @rachelnabors let me know if there are any other emojis I've missed.
