### ISSUE TITLE
Minimum list of IAM permissions is incorrect

### ISSUE THREAD

**Issue by sebsto** [aws-amplify/docs#4702]
**Describe the bug**
The list of minimum IAM permissions to use Amplify CLI is incorrect.
Here is the link to documentation page https://docs.amplify.aws/cli/reference/iam/

It used to work 2 years ago, but current version of Amplify CLI uses two additional AWS APIs that are not documented by the URL above.

Missing permissions are 

```
"cloudformation:ListStackResources",
"lambda:TagResource",
```

**To Reproduce**
- Create an IAM Role with the documented list 
- Create an AWS CLI profile to use that role 
- type `amplify push` to create a Auth or GraphQL category

`amplify push` command fails with authorization errors.
 
**Expected behavior**
The IAM permissions should include all AWS API used by amplify CLI

When adding the two above permissions, `amplify push` commands are working as expected.

**Comment by Rishav-12** [comment]
The change has to be made in https://github.com/aws-amplify/docs/blob/main/src/pages/cli/reference/iam.mdx, am I right?

**Comment by sebsto** [comment]
@Rishav-12 if that page is the source for https://docs.amplify.aws/cli/reference/iam/, then yes you are correct.
From what I see, it looks like it is the source for this documentation page, but your are the doc expert :-)

**Comment by sebsto** [comment]
as I am adding more plugins to my project, I discover new permissions missing.

To use DataStore, the policy also need the following permissions:

```
                "dynamodb:UpdateTimeToLive",
                "dynamodb:DescribeTimeToLive",
```

**Comment by Rishav-12** [comment]
But these are already present on lines 134 and 126 in the json example
![screenshot-of-iam-policy-json](https://user-images.githubusercontent.com/76068105/197191081-6e9ed5ee-59c9-4291-9a37-544bcd871865.png)

**Comment by sebsto** [comment]
Great - they were not present on mine, but I had a snapshot from 2019

**Comment by ykethan** [comment]
Hey @sebsto, thank you for the information. The page has been removed in favor of https://docs.aws.amazon.com/amplify/latest/userguide/security-iam-awsmanpol.html#security-iam-awsmanpol-AdministratorAccess-Amplify
the page provides the updated updated policy information.
