### ISSUE TITLE
Add secondary nav to docs home page

### ISSUE THREAD

**Issue by rachelnabors** [aws-amplify/docs#4732]
As a person new to Amplify or returning to the docs for reference material, I would like to be able to quickly navigate to Guides, CLI, etc from the landing page at docs.amplify.aws. But that page doesn't have the navigation bar to those things:

<img width="1209" alt="Screen Shot 2022-10-20 at 2 56 51 PM" src="https://user-images.githubusercontent.com/236306/197066960-4862733e-2d43-4ad8-adf7-e788ff34a122.png">

I have no choice but to click on one of the links on the page, then use that page's secondary navigation:
<img width="1215" alt="Screen Shot 2022-10-20 at 2 57 00 PM" src="https://user-images.githubusercontent.com/236306/197066903-048298a6-0456-4a47-acae-a18851e00be2.png">

This makes the docs hard to navigate. It would be better if the landing page had the secondary navigation present

**Comment by oscarcao** [comment]
I'll look into this first issue.
