### ISSUE TITLE
[Feedback] Amplify.Publisher call is getting an error

### ISSUE THREAD

**Issue by lseidman** [aws-amplify/docs#4734]
**Page**: [`/guides/api-graphql/subscriptions-by-id/q/platform/[platform]`](https://docs.amplify.aws/guides/api-graphql/subscriptions-by-id/q/platform/ios)

**Feedback**:

In the final block of code on line 6 (in the Combine tab), it says the following:

`cancellable = Amplify.Publisher.create(sequence)`

This is causing the following error for me:

> Type 'Amplify' has no member 'Publisher'

I checked the Amplify class, and I am not seeing a Publisher variable there.  Perhaps this documentation is out of sync with what's in the current iOS Amplify package?

If not, could someone advise me on what I might be doing wrong, and how I might resolve this?

**Comment by atierian** [comment]
Thanks for opening this @lseidman. `Amplify.Publisher.create(_:)` does exist in v2 of Amplify Swift. If you're not finding it, you're likely still on v1.

**Comment by atierian** [comment]
Closing this issue. Please leave a comment here or open a new issue if you're still experiencing this. Thanks!
