### ISSUE TITLE
[Feedback]Please update for Amplify 2.0.0

### ISSUE THREAD

**Issue by gurkarangulati** [aws-amplify/docs#4746]
**Page**: [`/sdk/push-notifications/getting-started/q/platform/[platform]`](https://docs.amplify.aws/sdk/push-notifications/getting-started/q/platform/ios)

**Feedback**:

```
var pinpoint: AWSPinpoint?
```

```
let pinpointConfiguration = AWSPinpointConfiguration
            .defaultPinpointConfiguration(launchOptions: launchOptions)
        // Set debug mode to use APNS sandbox, make sure to toggle for your production app
        pinpointConfiguration.debug = true
        pinpoint = AWSPinpoint(configuration: pinpointConfiguration)
```
        
```
pinpoint?.notificationManager.interceptDidRegisterForRemoteNotifications(
            withDeviceToken: deviceToken)
```
            

These lines of code don't work anymore after upgrading to Amplify 2.0.0 I would really appreciate if we can update the example provided by the newly released Amplify 2.0.0. Super excited for the updates!

**Comment by ruisebas** [comment]
The linked page describes the **AWS Pinpoint Push Notifications** support that is part of the `AWSPinpoint` module in **AWS SDK for iOS** (in the [`aws-sdk-ios`](https://github.com/aws-amplify/aws-sdk-ios) repo).

Amplify **v1.x** depends on **aws-sdk-ios**, so this functionality is accessible via _Analytics_' escape hatch.

Amplify **v2.x** however has moved away from **aws-sdk-ios**, so Pinpoint Push Notifications support is not yet available.
