### ISSUE TITLE
When registering to get the verification code for verification, the mobile phone number is entered incorrectly. What should I do if I cannot get the verification code?

### ISSUE THREAD

**Issue by maxiaodegithub** [aws-amplify/docs#4748]
**Page**: [`/lib/auth/sms_flows/q/platform/[platform]`](https://docs.amplify.aws/lib/auth/sms_flows/q/platform/flutter)

**Feedback**:
When registering to get the verification code for verification, the mobile phone number is entered incorrectly. What should I do if I cannot get the verification code?
When the user entered the wrong mobile phone number during registration, the verification code could not be obtained. When the user obtained it again, the mobile phone number was already bound to the user name. Is the system still using the wrong mobile phone number to obtain the verification code? How to fix this wrong phone number?

**Comment by khatruong2009** [comment]
Hi @maxiaodegithub, I just wanted to confirm some details about the issue you're having. So the user entered the wrong phone number during registration and could not get a verification code. Then, the user was able to get the verification code later? Were they able to log in after getting the verification code again? If the user wasn't able to get log in after getting the wrong verification code, the only way to change that would be for the admin to change it on the console in Cognito. If they are able to log in without verification, you could use the [updateUserAttribute](https://docs.amplify.aws/lib/auth/user-attributes/q/platform/flutter/#fetch-the-current-users-attributes) call once the user is logged in.

**Comment by maxiaodegithub** [comment]
The situation is that when a user registers, they enter their phone number
for account authentication and activation, but there may be a situation
where they enter the wrong number, which results in the user's ID
(username) being registered but unable to receive the correct verification
code. The account is in an inactive state, but the registered ID (username)
has already been occupied. Causes the user to be unable to log in.
If there is no other way to update the phone number, it can only be
modified from the console.

Kha Truong ***@***.***> 于2023年7月14日周五 02:40写道：

**Comment by khatruong2009** [comment]
Hi @maxiaodegithub. Unfortunately, for this situation, there is no other way to update the phone number other than an admin changing it in the console.

**Comment by maxiaodegithub** [comment]
No problem, I understand.

Kha Truong ***@***.***> 于2023年7月19日周三 08:25写道：
