### ISSUE TITLE
Wrong page link: Firebase credentials

### ISSUE THREAD

**Issue by lroellin** [aws-amplify/docs#475]
**Describe the bug**

https://aws-amplify.github.io/docs/js/push-notifications#setup-for-android

> Get your push messaging credentials for Android in Firebase console. [Click here for instructions.](https://aws-amplify.github.io/docs/js/Get%20Push%20Messaging%20Credentials%20for%20Android)

The link behind "Click here for instructions" is dead.

**To Reproduce**
1. Click on link
2. Observe 404

**Expected behavior**
Page found

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by lroellin** [comment]
The issue is not fixed and still there.

**Comment by beaurushton** [comment]
Still broken.
