### ISSUE TITLE
AWS Amplify - Cognito sync - Import issue

### ISSUE THREAD

**Issue by jayalog** [aws-amplify/docs#476]
In this page (https://aws-amplify.github.io/docs/js/start) there is a import "import Route53 from 'aws-sdk/clients/route53';"

But it throws error as "has no default export" I am actually migrating my application to aws amplify. I want to integrate aws cognito sync methods.

Anyone have idea how to do this?

**Comment by nikhil-dabhade** [comment]
@jayalog  Can you try
import * as Route53 from 'aws-sdk/clients/route53'

@manueliglesias : Just to make sure I am not doing this wrong ^^
