### ISSUE TITLE
Using "AWSAppSyncCacheConfiguration" causes an error.

### ISSUE THREAD

**Issue by RomeoDelta** [aws-amplify/docs#477]
**Describe the bug**
Using "AWSAppSyncCacheConfiguration" causes an error.

**To Reproduce**
I followed this instruction:
 https://aws-amplify.github.io/docs/ios/start?ref=amplify-iOS-btn

At Step 5: Integrate into your app, Xcode shows an error.
 
 Use of unresolved identifier 'AWSAppSyncCacheConfiguration'; did you mean 'AWSAppSyncClientConfiguration'?
 Replace 'AWSAppSyncCacheConfiguration' with 'AWSAppSyncClientConfiguration'

**Expected behavior**
I'd like to dismiss the error.

**Screenshots**
Shown below.

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.3
 - Xcode 10.1 (10B61)

![image](https://user-images.githubusercontent.com/19186112/53206701-038a9c80-3675-11e9-98d1-8f8abbbd36d7.png)

**Comment by kvasukib** [comment]
@RomeoDelta Sorry for the inconvenience caused. 

`AWSAppSyncCacheConfiguration` was introduced in `2.10.0` version of the AWS SDK for AppSync in iOS.

Reference to the [CHANGELOG](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/blob/6c8a0bbcd277b0bca63418fcb8b10ee687a0bc9f/CHANGELOG.md#2100) here.

Please refer to the notes in the Change Log for additional details.

**Comment by kvasukib** [comment]
Submitted PR #478 to fix the issue. Thank you for pointing it out.

**Comment by muellerfr** [comment]
The PR to update the docs has been merged.
