### ISSUE TITLE
[Feedback] Running 'amplify add api' does not set up Cognito Auth as described in docs

### ISSUE THREAD

**Issue by bleirdalag** [aws-amplify/docs#4771]
**Page**: [`/start/getting-started/data-model/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/data-model/q/integration/next)

**Feedback**:

Running 'amplify add api' does not give the output in the docs.

Here is the output I got to console after running `amplify add api` while going through this tutorial:

```
$ amplify add api
? Select from one of the below mentioned services: GraphQL
? Here is the GraphQL API that we will create. Select a setting to edit o
r continue Continue
? Choose a schema template: Single object with fields (e.g., “Todo” with 
ID, name, description)

```

**Comment by abdallahshaban557** [comment]
Hi @bleirdalag  - you should be able to have Auth setup if you select Cognito User pools as an authorization mode when setting up API. Did you select that from the CLI flow?

**Comment by bleirdalag** [comment]
I did not see any option to select and authorization mode when setting up the API

**Comment by bleirdalag** [comment]
Here is the output I got to console after running `amplify add api` while going through this tutorial:

```
$ amplify add api
? Select from one of the below mentioned services: GraphQL
? Here is the GraphQL API that we will create. Select a setting to edit o
r continue Continue
? Choose a schema template: Single object with fields (e.g., “Todo” with 
ID, name, description)


```

**Comment by bleirdalag** [comment]
Ah, I see the problem -- I needed to select a setting to edit. This was unclear to me going through the tutorial and I went with the default choice of continuing without editing settings :(

**Comment by cwomack** [comment]
@bleirdalag, there was a recent PR to update the Next.js docs that provides more examples of the CLI output.  I'll close this issue down, but feel free to comment back if you have any additional feedback to improve the examples further.
