### ISSUE TITLE
[missing-page] What happened to the Ionic documentation

### ISSUE THREAD

**Issue by TE-RobertMcCain** [aws-amplify/docs#4781]
**Page**: [`https://docs.amplify.aws/start/getting-started/hosting/q/integration/ionic/

**Comment by abdallahshaban557** [comment]
Hi @TE-RobertMcCain  - we removed the guide since it was outdated and we did not have customers asking us for updates on it. Would you be interested in contributing to an updated tutorial for using Amplify with Ionic?

**Comment by TE-RobertMcCain** [comment]
Hello @abdallahshaban557 . Thank you for your reply. 

You mentioned that the documentation is outdated. Are there updated materials or is Amplify removing support for ionic? I 

I am not sure that I have the expertise to create a tutorial for Amplify. I have just started creating an Ionic/Amplify project and noticed that the documentation no longer exists. Can I make a request to have the documentation updated?

**Comment by abdallahshaban557** [comment]
We are slimming down our tutorials section so we can ensure the tutorials we do maintain stay up to date and support the same components as Amplify UI. You can still use Ionic and Amplify together. Try following the React JS tutorial with Ionic. Or check YouTube for more in depth tutorials.

https://www.youtube.com/watch?v=5eq_UiLyymk

**Comment by TE-RobertMcCain** [comment]
Hi @abdallahshaban557. Thank you for the update!

ok so it sounds like the Ionic documentation will not be returning unless someone from the user community creates it. 

And yes there are many unofficial resources to help with creating Ionic/Amplify apps but the official documentation I think was the most helpful. Can you make the ionic documentation available for download even if it is deprecated?

**Comment by TE-RobertMcCain** [comment]
Hi @abdallahshaban557. Just wanted to check again to see if the Ionic/Amplify documentation can be made available for download.

**Comment by abdallahshaban557** [comment]
Hi @TE-RobertMcCain  - I've been able to locate the PR where the Ionic getting started was [removed](https://github.com/aws-amplify/docs/pull/4677) - however I am not able to find an easy way to get you that information. Would going through that PR with seeing the things removed be helpful for now?

**Comment by TE-RobertMcCain** [comment]
Hi @abdallahshaban557 . I am so sorry for my late reply. It might be helpful to see what was removed but for me as a user of the content and not necessarily a content editor I think it might be difficult for me to make use of it in this form. Would it be possible for me to download the content somehow before the pull request to remove it and then build it locally?

**Comment by rachelnabors** [comment]
You should be able to see an older version of the site using https://archive.org/

**Comment by rachelnabors** [comment]
Try this: https://web.archive.org/web/20220526141035/https://docs.amplify.aws/start/q/integration/ionic/

**Comment by cwomack** [comment]
@TE-RobertMcCain, let us know if the replies and links from @rachelnabors and @abdallahshaban557 are sufficient to reference at this point. 

I'll close out this issue since we've removed the Ionic Getting Started guides from our docs and have no plans on bringing them back at this point.
