### ISSUE TITLE
Incorrect numbering in "Facebook Login in Your Mobile App" section

### ISSUE THREAD

**Issue by nikhil-dabhade** [aws-amplify/docs#479]
**Describe the bug**
In the section, "Facebook Login in Your Mobile App" the numbering of points is incorrect.

**To Reproduce**
1. Go to 'https://aws-amplify.github.io/docs/ios/authentication'
2. Click on 'https://aws-amplify.github.io/docs/ios/authentication#facebook-login-in-your-mobile-app'
3. See error

**Expected behavior**
The numbering should be 1, 2.

**Screenshots**
![screen shot 2019-02-20 at 5 39 03 pm](https://user-images.githubusercontent.com/16342547/53137147-7b05e200-3536-11e9-8189-2d8709b7a611.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome

**Comment by muellerfr** [comment]
Fixed

**Comment by nikhil-dabhade** [comment]
Thank you !

**Comment by nikhil-dabhade** [comment]
The issue is still present.
