### ISSUE TITLE
Incorrect numbering in section "Google Login in Your App"

### ISSUE THREAD

**Issue by nikhil-dabhade** [aws-amplify/docs#480]
**Describe the bug**
The numbering in the section "Google Login in Your App" on the link https://aws-amplify.github.io/docs/ios/authentication#google-with-cognito-identity is incorrect

**To Reproduce**
1. Go to 'https://aws-amplify.github.io/docs/ios/authentication#google-with-cognito-identity'
2. Check the numbering in this section

**Expected behavior**

**Screenshots**
![screen shot 2019-02-21 at 4 58 15 pm](https://user-images.githubusercontent.com/16342547/53212521-1d3ace00-35fa-11e9-994a-b839a9dd3a1f.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome

**Comment by muellerfr** [comment]
Fixed

**Comment by nikhil-dabhade** [comment]
Thank you !

**Comment by nikhil-dabhade** [comment]
Issue still seems to be present.
