### ISSUE TITLE
Correct sentence construction

### ISSUE THREAD

**Issue by nikhil-dabhade** [aws-amplify/docs#483]
**Describe the bug**
Incorrect sentence construction 

**To Reproduce**
1. Go to '1. Go to https://aws-amplify.github.io/docs/ios/authentication#automated-setup'
2. Search for "When the Options dialog box that appears, do the following:"

**Expected behavior**
The sentence should be "When the Options dialog box appears, do the following:"

**Comment by muellerfr** [comment]
Fixed
