### ISSUE TITLE
[Feedback]Typo on page

### ISSUE THREAD

**Issue by cguajard** [aws-amplify/docs#4837]
**Page**: [`/lib/storage/upload/q/platform/[platform]`](https://docs.amplify.aws/lib/storage/upload/q/platform/js)

**Feedback**:

Think this is a typo on this page:
If a file extension is not provided in the key of the uploaded object, the S3 console's 'Type' field will be **emitted**.

I think that should probably be "omitted" vs "emitted"

**Comment by abdallahshaban557** [comment]
Will be addressed when this PR is merged  https://github.com/aws-amplify/docs/pull/4836#pullrequestreview-1179802972

**Comment by cguajard** [comment]
Doesn't look like this ever got addressed. Not a big deal but just thought I'd mention it since I stumbled upon it again!

**Comment by tannerabread** [comment]
@cguajard you're right! This was overlooked, thank you for reminding us. Going to fix it now

**Comment by tannerabread** [comment]
@cguajard the changes for this should now be incorporated into the docs. Thank you again for bringing this to our attention!
