### ISSUE TITLE
Multiple Env doc has broken links for images

### ISSUE THREAD

**Issue by sebsto** [aws-amplify/docs#485]
**Describe the bug**
The page at https://aws-amplify.github.io/docs/cli/multienv?sdk=js has broken links for images

Images are linked to 
`/cli/images/AmplifyEnvSwitching.jpg` 

Correct link is 
`/docs/cli/images/AmplifyEnvSwitching.jpg`

**Comment by swaminator** [comment]
+1

**Comment by nikhil-dabhade** [comment]
@kaustavghosh06  ^^

**Comment by kaustavghosh06** [comment]
We've fixed this issue -> https://aws-amplify.github.io/docs/cli/multienv?sdk=js
Please take a look at the site and let me know if you're still seeing the issue.

**Comment by sebsto** [comment]
LGTM. 
Thanks for the quick fix 

--Seb
