### ISSUE TITLE
[Feedback] error during iOS getting started tutorial: [StorageEngine] - Unable to find suitable API plugin for syncEngine. syncEngine will not be started

### ISSUE THREAD

**Issue by jefemagril** [aws-amplify/docs#4865]
**Page**: [`/start/getting-started/integrate/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/integrate/q/integration/ios)

**Feedback**:

I've followed the Getting started tutorial step-by-step and everything has been working until the "Create a Todo" section where I get this error upon trying to run the code:
```
2022-11-16 18:31:39.187999-0500 Todo[41171:13677117] [Amplify] Configuring
Initialized Amplify
2022-11-16 18:31:39.365684-0500 Todo[41171:13677374] [StorageEngine] Unable to find suitable API plugin for syncEngine. syncEngine will not be started
```

Was there some setup option I missed? Per the tutorial, the only time I've touched the AWS Console so far was to set up an IAM user.

**Comment by phantumcode** [comment]
@jefemagril I'm able to following the iOS Getting Started guide using Amplify Swift version 2.7.1.  I was not able to reproduce your issue.  Are you still running into this issue?

**Comment by phantumcode** [comment]
Closing issue, please re-open if this issue still exists.

**Comment by macinsmithpub** [comment]
I'm having the same issue with 2.25.3 that I just created today by following the iOS getting started guide.

**Comment by youngcadam** [comment]
@macinsmithpub I had a similar issue on the most recent version of iOS/Xcode/macOS/Amplify/Swift attempting to follow the Quick Start guide for AmplifyV2, specifically during the steps listed on this page https://docs.amplify.aws/swift/start/getting-started/integrate/.

I was able to fix the issue by running
```bash
amplify init
```
and then
```bash
amplify push
```

I also modified the `TodoApp.swift` file to be the following
```swift
//
//  TodoApp.swift
//  Todo
//
//  Created by Adam Young on 1/15/24.
//

import SwiftUI
import Amplify
import AWSDataStorePlugin
import AWSAPIPlugin

func configureAmplify() {
    let dataStorePlugin = AWSDataStorePlugin(modelRegistration: AmplifyModels())
    let awsAPIPlugin = AWSAPIPlugin(modelRegistration: AmplifyModels())
    do {
        Amplify.Logging.logLevel = .info
        try Amplify.add(plugin: awsAPIPlugin)
        try Amplify.add(plugin: dataStorePlugin)
        try Amplify.configure()
        print("Initialized Amplify");
    } catch {
        // simplified error handling for the tutorial
        print("Could not initialize Amplify: \(error)")
    }
}

@main
struct TodoApp: App {
    // Add a default initializer and configure Amplify
    init() {
        configureAmplify()
    }
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
```

I hope this helps!

**Comment by macinsmithpub** [comment]
Hi Adam,

Thanks for the suggestions, but they did not work.

First, the documentation is out of date with the plugin manager UI. Note that it doesn’t have the check boxes for selecting which plugins.

￼

Also note that the generated code for ContentView has a binding for document, so the body var in TodoApp that you showed doesn’t match and it uses a DocumentGroup rather than a WindowGroup

￼

Third, Even though I import ASWAPIPlugin, it does not resolve as shown in the following screenshot (notice I even imported all the AWS modules just to see if it was hiding in one of them.

￼


I also did the amplify init and amplify push and it made no difference.

Steve

On Jan 15, 2024, at 5:48 PM, Adam Young ***@***.***> wrote:


@macinsmithpub <https://github.com/macinsmithpub> I had a similar issue on the most recent version of iOS/Xcode/macOS/Amplify/Swift attempting to follow the Quick Start guide for AmplifyV2, specifically during the steps listed on this page https://docs.amplify.aws/swift/start/getting-started/integrate/.

I was able to fix the issue by running

amplify init
and then

amplify push
I also modified the TodoApp.swift file to be the following

//
//  TodoApp.swift
//  Todo
//
//  Created by Adam Young on 1/15/24.
//

import SwiftUI
import Amplify
import AWSDataStorePlugin
import AWSAPIPlugin

func configureAmplify() {
    let dataStorePlugin = AWSDataStorePlugin(modelRegistration: AmplifyModels())
    let awsAPIPlugin = AWSAPIPlugin(modelRegistration: AmplifyModels())
    do {
        Amplify.Logging.logLevel = .info
        try Amplify.add(plugin: awsAPIPlugin)
        try Amplify.add(plugin: dataStorePlugin)
        try Amplify.configure()
        print("Initialized Amplify");
    } catch {
        // simplified error handling for the tutorial
        print("Could not initialize Amplify: \(error)")
    }
}

@main
struct TodoApp: App {
    // Add a default initializer and configure Amplify
    init() {
        configureAmplify()
    }
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
I hope this helps!

**Comment by macinsmithpub** [comment]
I too chose Todo for each target.

I don’t see what you mean by "backed resources provision".

Here is the console log.  

[Todo](main *): amplify codegen models
ProjectNotInitializedError: No Amplify backend project files detected within this folder.
Successfully generated models. Generated models can be found in /Users/srsmitty/code/Examples/Todo/amplify/generated/models
Updating Xcode project:
-- Amplify models folder found at /Users/srsmitty/code/Examples/Todo/amplify/generated/models
-- Successfully added models ["AmplifyModels.swift", "Priority.swift", "Todo+Schema.swift", "Todo.swift"] to 'AmplifyModels' group.
Amplify setup completed successfully.


[Todo](main *): amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the environment dev
? Choose your default editor: Xcode (macOS only)
Using default provider  awscloudformation
? Select the authentication method you want to use: AWS access keys
? accessKeyId:  ********************
? secretAccessKey:  ****************************************
? region:  us-east-1
Adding backend environment dev to AWS Amplify app: d1xuzgyfzm4wt2

Deployment completed.
Deployed root stack Todo [ ======================================== ] 4/4
	amplify-todo-dev-95853         AWS::CloudFormation::Stack     CREATE_COMPLETE                Tue Jan 16 2024 09:59:35…   
	AuthRole                       AWS::IAM::Role                 CREATE_COMPLETE                Tue Jan 16 2024 09:59:20…   
	DeploymentBucket               AWS::S3::Bucket                CREATE_COMPLETE                Tue Jan 16 2024 09:59:32…   
	UnauthRole                     AWS::IAM::Role                 CREATE_COMPLETE                Tue Jan 16 2024 09:59:20…   

Deployment state saved successfully.
✔ Initialized provider successfully.
✅ Initialized your environment successfully.
✅ Your project has been successfully initialized and connected to the cloud!
Some next steps:

"amplify status" will show you what you've added already and if it's locally configured or deployed
"amplify add <category>" will allow you to add features like user login or a backend API
"amplify push" will build all your local backend resources and provision it in the cloud
"amplify console" to open the Amplify Console and view your project status
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud


Pro tip:
Try "amplify add api" to create a backend API and then "amplify push" to deploy everything

Updating Xcode project:
-- Amplify project found.
-- Amplify config files found.
-- Successfully updated project /Users/srsmitty/code/Examples/Todo.
Amplify setup completed successfully.


[Todo](main *): amplify push
✔ Successfully pulled backend environment dev from the cloud.

    Current Environment: dev
    
┌──────────┬───────────────────┬───────────┬───────────────────┐
│ Category │ Resource name     │ Operation │ Provider plugin   │
├──────────┼───────────────────┼───────────┼───────────────────┤
│ Api      │ amplifyDatasource │ Create    │ awscloudformation │
└──────────┴───────────────────┴───────────┴───────────────────┘
✔ Are you sure you want to continue? (Y/n) · yes
✅ GraphQL schema compiled successfully.

Edit your schema at /Users/srsmitty/code/Examples/Todo/amplify/backend/api/amplifyDatasource/schema.graphql or place .graphql files in a directory at /Users/srsmitty/code/Examples/Todo/amplify/backend/api/amplifyDatasource/schema
? Do you want to generate code for your newly created GraphQL API Yes
? Enter the file name pattern of graphql queries, mutations and subscriptions graphql/**/*.graphql
? Do you want to generate/update all possible GraphQL operations - queries, mutations and subscriptions Yes
? Enter maximum statement depth [increase from default if your schema is deeply nested] 2
? Enter the file name for the generated code API.swift

Deployment completed.
Deployed root stack Todo [ ======================================== ] 2/2
	amplify-todo-dev-95853         AWS::CloudFormation::Stack     UPDATE_COMPLETE                Tue Jan 16 2024 10:03:48…   
	apiamplifyDatasource           AWS::CloudFormation::Stack     CREATE_COMPLETE                Tue Jan 16 2024 10:03:46…   

✔ Generated GraphQL operations successfully and saved at graphql
✅ GraphQL schema compiled successfully.

Edit your schema at /Users/srsmitty/code/Examples/Todo/amplify/backend/api/amplifyDatasource/schema.graphql or place .graphql files in a directory at /Users/srsmitty/code/Examples/Todo/amplify/backend/api/amplifyDatasource/schema
Successfully generated models. Generated models can be found in /Users/srsmitty/code/Examples/Todo/amplify/generated/models
✔ Code generated successfully and saved in file API.swift
Deployment state saved successfully.

GraphQL endpoint: https://********************.appsync-api.us-east-1.amazonaws.com/graphql
GraphQL API KEY: ********************

GraphQL transformer version: 2


[Todo](main *): amplify add api
? Select from one of the below mentioned services: GraphQL
⚠️ You already have an AppSync API in your project. Use the "amplify update api" command to update your existing AppSync API.


[Todo](main *): 


Steve

On Jan 16, 2024, at 10:37 AM, Adam Young ***@***.***> wrote:


@macinsmithpub <https://github.com/macinsmithpub> you are right that the documentation is still outdated, and particularly that the checkboxes are missing from the Add plugins section. For that step, I chose Todo as my target on the boxes they checked in the quickstart guide.

Did you see backed resources provision when you ran amplify init and amplify push? I am unable to see the screenshots in your comment so it's a bit challenging to diagnose what happened.

**Comment by macinsmithpub** [comment]
It doesn’t appear that the awsAPIPlugin was installed. I ran amplify console and got this:

[Todo](main *): amplify console
https://us-east-1.console.aws.amazon.com/amplify/home?region=us-east-1#/d1xuzgyfzm4wt2/YmFja2VuZA/dev
[Todo](main *): amplify pull --appId d1xuzgyfzm4wt2 --envName dev

Pre-pull status:

    Current Environment: dev
    
┌──────────┬───────────────────┬───────────┬───────────────────┐
│ Category │ Resource name     │ Operation │ Provider plugin   │
├──────────┼───────────────────┼───────────┼───────────────────┤
│ Api      │ amplifyDatasource │ No Change │ awscloudformation │
└──────────┴───────────────────┴───────────┴───────────────────┘

✔ Successfully pulled backend environment dev from the cloud.
✅ 
✅ GraphQL schema compiled successfully.

Edit your schema at /Users/srsmitty/code/Examples/Todo/amplify/backend/api/amplifyDatasource/schema.graphql or place .graphql files in a directory at /Users/srsmitty/code/Examples/Todo/amplify/backend/api/amplifyDatasource/schema
Successfully generated models. Generated models can be found in /Users/srsmitty/code/Examples/Todo/amplify/generated/models
Post-pull status:

    Current Environment: dev
    
┌──────────┬───────────────────┬───────────┬───────────────────┐
│ Category │ Resource name     │ Operation │ Provider plugin   │
├──────────┼───────────────────┼───────────┼───────────────────┤
│ Api      │ amplifyDatasource │ No Change │ awscloudformation │
└──────────┴───────────────────┴───────────┴───────────────────┘

Updating Xcode project:
-- Amplify project found.
-- Amplify config files found.
-- Successfully updated project /Users/srsmitty/code/Examples/Todo.
-- Amplify models folder found at /Users/srsmitty/code/Examples/Todo/amplify/generated/models
-- Successfully added models ["AmplifyModels.swift", "Priority.swift", "Todo+Schema.swift", "Todo.swift"] to 'AmplifyModels' group.
Amplify setup completed successfully.




On Jan 16, 2024, at 1:44 PM, ***@***.*** ***@***.***> wrote:

I too chose Todo for each target.

I don’t see what you mean by "backed resources provision".

Here is the console log.  

[Todo](main *): amplify codegen models
ProjectNotInitializedError: No Amplify backend project files detected within this folder.
Successfully generated models. Generated models can be found in /Users/srsmitty/code/Examples/Todo/amplify/generated/models
Updating Xcode project:
-- Amplify models folder found at /Users/srsmitty/code/Examples/Todo/amplify/generated/models
-- Successfully added models ["AmplifyModels.swift", "Priority.swift", "Todo+Schema.swift", "Todo.swift"] to 'AmplifyModels' group.
Amplify setup completed successfully.


[Todo](main *): amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the environment dev
? Choose your default editor: Xcode (macOS only)
Using default provider  awscloudformation
? Select the authentication method you want to use: AWS access keys
? accessKeyId:  ********************
? secretAccessKey:  ****************************************
? region:  us-east-1
Adding backend environment dev to AWS Amplify app: d1xuzgyfzm4wt2

Deployment completed.
Deployed root stack Todo [ ======================================== ] 4/4
	amplify-todo-dev-95853         AWS::CloudFormation::Stack     CREATE_COMPLETE                Tue Jan 16 2024 09:59:35…   
	AuthRole                       AWS::IAM::Role                 CREATE_COMPLETE                Tue Jan 16 2024 09:59:20…   
	DeploymentBucket               AWS::S3::Bucket                CREATE_COMPLETE                Tue Jan 16 2024 09:59:32…   
	UnauthRole                     AWS::IAM::Role                 CREATE_COMPLETE                Tue Jan 16 2024 09:59:20…   

Deployment state saved successfully.
✔ Initialized provider successfully.
✅ Initialized your environment successfully.
✅ Your project has been successfully initialized and connected to the cloud!
Some next steps:

"amplify status" will show you what you've added already and if it's locally configured or deployed
"amplify add <category>" will allow you to add features like user login or a backend API
"amplify push" will build all your local backend resources and provision it in the cloud
"amplify console" to open the Amplify Console and view your project status
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud


Pro tip:
Try "amplify add api" to create a backend API and then "amplify push" to deploy everything

Updating Xcode project:
-- Amplify project found.
-- Amplify config files found.
-- Successfully updated project /Users/srsmitty/code/Examples/Todo.
Amplify setup completed successfully.


[Todo](main *): amplify push
✔ Successfully pulled backend environment dev from the cloud.

    Current Environment: dev
    
┌──────────┬───────────────────┬───────────┬───────────────────┐
│ Category │ Resource name     │ Operation │ Provider plugin   │
├──────────┼───────────────────┼───────────┼───────────────────┤
│ Api      │ amplifyDatasource │ Create    │ awscloudformation │
└──────────┴───────────────────┴───────────┴───────────────────┘
✔ Are you sure you want to continue? (Y/n) · yes
✅ GraphQL schema compiled successfully.

Edit your schema at /Users/srsmitty/code/Examples/Todo/amplify/backend/api/amplifyDatasource/schema.graphql or place .graphql files in a directory at /Users/srsmitty/code/Examples/Todo/amplify/backend/api/amplifyDatasource/schema
? Do you want to generate code for your newly created GraphQL API Yes
? Enter the file name pattern of graphql queries, mutations and subscriptions graphql/**/*.graphql
? Do you want to generate/update all possible GraphQL operations - queries, mutations and subscriptions Yes
? Enter maximum statement depth [increase from default if your schema is deeply nested] 2
? Enter the file name for the generated code API.swift

Deployment completed.
Deployed root stack Todo [ ======================================== ] 2/2
	amplify-todo-dev-95853         AWS::CloudFormation::Stack     UPDATE_COMPLETE                Tue Jan 16 2024 10:03:48…   
	apiamplifyDatasource           AWS::CloudFormation::Stack     CREATE_COMPLETE                Tue Jan 16 2024 10:03:46…   

✔ Generated GraphQL operations successfully and saved at graphql
✅ GraphQL schema compiled successfully.

Edit your schema at /Users/srsmitty/code/Examples/Todo/amplify/backend/api/amplifyDatasource/schema.graphql or place .graphql files in a directory at /Users/srsmitty/code/Examples/Todo/amplify/backend/api/amplifyDatasource/schema
Successfully generated models. Generated models can be found in /Users/srsmitty/code/Examples/Todo/amplify/generated/models
✔ Code generated successfully and saved in file API.swift
Deployment state saved successfully.

GraphQL endpoint: https://********************.appsync-api.us-east-1.amazonaws.com/graphql
GraphQL API KEY: ********************

GraphQL transformer version: 2


[Todo](main *): amplify add api
? Select from one of the below mentioned services: GraphQL
⚠️ You already have an AppSync API in your project. Use the "amplify update api" command to update your existing AppSync API.


[Todo](main *): 


Steve

On Jan 16, 2024, at 10:37 AM, Adam Young ***@***.***> wrote:


@macinsmithpub <https://github.com/macinsmithpub> you are right that the documentation is still outdated, and particularly that the checkboxes are missing from the Add plugins section. For that step, I chose Todo as my target on the boxes they checked in the quickstart guide.

Did you see backed resources provision when you ran amplify init and amplify push? I am unable to see the screenshots in your comment so it's a bit challenging to diagnose what happened.

**Comment by macinsmithpub** [comment]
I'm on MacOS Sonoma 14.2.1 and Xcode 15.0.1 and using and amplify-swift 2.25.4

Steve


On Jan 16, 2024, at 2:23 PM, ***@***.*** ***@***.***> wrote:

It doesn’t appear that the awsAPIPlugin was installed. I ran amplify console and got this:

[Todo](main *): amplify console
https://us-east-1.console.aws.amazon.com/amplify/home?region=us-east-1#/d1xuzgyfzm4wt2/YmFja2VuZA/dev
[Todo](main *): amplify pull --appId d1xuzgyfzm4wt2 --envName dev

Pre-pull status:

    Current Environment: dev
    
┌──────────┬───────────────────┬───────────┬───────────────────┐
│ Category │ Resource name     │ Operation │ Provider plugin   │
├──────────┼───────────────────┼───────────┼───────────────────┤
│ Api      │ amplifyDatasource │ No Change │ awscloudformation │
└──────────┴───────────────────┴───────────┴───────────────────┘

✔ Successfully pulled backend environment dev from the cloud.
✅ 
✅ GraphQL schema compiled successfully.

Edit your schema at /Users/srsmitty/code/Examples/Todo/amplify/backend/api/amplifyDatasource/schema.graphql or place .graphql files in a directory at /Users/srsmitty/code/Examples/Todo/amplify/backend/api/amplifyDatasource/schema
Successfully generated models. Generated models can be found in /Users/srsmitty/code/Examples/Todo/amplify/generated/models
Post-pull status:

    Current Environment: dev
    
┌──────────┬───────────────────┬───────────┬───────────────────┐
│ Category │ Resource name     │ Operation │ Provider plugin   │
├──────────┼───────────────────┼───────────┼───────────────────┤
│ Api      │ amplifyDatasource │ No Change │ awscloudformation │
└──────────┴───────────────────┴───────────┴───────────────────┘

Updating Xcode project:
-- Amplify project found.
-- Amplify config files found.
-- Successfully updated project /Users/srsmitty/code/Examples/Todo.
-- Amplify models folder found at /Users/srsmitty/code/Examples/Todo/amplify/generated/models
-- Successfully added models ["AmplifyModels.swift", "Priority.swift", "Todo+Schema.swift", "Todo.swift"] to 'AmplifyModels' group.
Amplify setup completed successfully.




On Jan 16, 2024, at 1:44 PM, ***@***.*** ***@***.***> wrote:

I too chose Todo for each target.

I don’t see what you mean by "backed resources provision".

Here is the console log.  

[Todo](main *): amplify codegen models
ProjectNotInitializedError: No Amplify backend project files detected within this folder.
Successfully generated models. Generated models can be found in /Users/srsmitty/code/Examples/Todo/amplify/generated/models
Updating Xcode project:
-- Amplify models folder found at /Users/srsmitty/code/Examples/Todo/amplify/generated/models
-- Successfully added models ["AmplifyModels.swift", "Priority.swift", "Todo+Schema.swift", "Todo.swift"] to 'AmplifyModels' group.
Amplify setup completed successfully.


[Todo](main *): amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the environment dev
? Choose your default editor: Xcode (macOS only)
Using default provider  awscloudformation
? Select the authentication method you want to use: AWS access keys
? accessKeyId:  ********************
? secretAccessKey:  ****************************************
? region:  us-east-1
Adding backend environment dev to AWS Amplify app: d1xuzgyfzm4wt2

Deployment completed.
Deployed root stack Todo [ ======================================== ] 4/4
	amplify-todo-dev-95853         AWS::CloudFormation::Stack     CREATE_COMPLETE                Tue Jan 16 2024 09:59:35…   
	AuthRole                       AWS::IAM::Role                 CREATE_COMPLETE                Tue Jan 16 2024 09:59:20…   
	DeploymentBucket               AWS::S3::Bucket                CREATE_COMPLETE                Tue Jan 16 2024 09:59:32…   
	UnauthRole                     AWS::IAM::Role                 CREATE_COMPLETE                Tue Jan 16 2024 09:59:20…   

Deployment state saved successfully.
✔ Initialized provider successfully.
✅ Initialized your environment successfully.
✅ Your project has been successfully initialized and connected to the cloud!
Some next steps:

"amplify status" will show you what you've added already and if it's locally configured or deployed
"amplify add <category>" will allow you to add features like user login or a backend API
"amplify push" will build all your local backend resources and provision it in the cloud
"amplify console" to open the Amplify Console and view your project status
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud


Pro tip:
Try "amplify add api" to create a backend API and then "amplify push" to deploy everything

Updating Xcode project:
-- Amplify project found.
-- Amplify config files found.
-- Successfully updated project /Users/srsmitty/code/Examples/Todo.
Amplify setup completed successfully.


[Todo](main *): amplify push
✔ Successfully pulled backend environment dev from the cloud.

    Current Environment: dev
    
┌──────────┬───────────────────┬───────────┬───────────────────┐
│ Category │ Resource name     │ Operation │ Provider plugin   │
├──────────┼───────────────────┼───────────┼───────────────────┤
│ Api      │ amplifyDatasource │ Create    │ awscloudformation │
└──────────┴───────────────────┴───────────┴───────────────────┘
✔ Are you sure you want to continue? (Y/n) · yes
✅ GraphQL schema compiled successfully.

Edit your schema at /Users/srsmitty/code/Examples/Todo/amplify/backend/api/amplifyDatasource/schema.graphql or place .graphql files in a directory at /Users/srsmitty/code/Examples/Todo/amplify/backend/api/amplifyDatasource/schema
? Do you want to generate code for your newly created GraphQL API Yes
? Enter the file name pattern of graphql queries, mutations and subscriptions graphql/**/*.graphql
? Do you want to generate/update all possible GraphQL operations - queries, mutations and subscriptions Yes
? Enter maximum statement depth [increase from default if your schema is deeply nested] 2
? Enter the file name for the generated code API.swift

Deployment completed.
Deployed root stack Todo [ ======================================== ] 2/2
	amplify-todo-dev-95853         AWS::CloudFormation::Stack     UPDATE_COMPLETE                Tue Jan 16 2024 10:03:48…   
	apiamplifyDatasource           AWS::CloudFormation::Stack     CREATE_COMPLETE                Tue Jan 16 2024 10:03:46…   

✔ Generated GraphQL operations successfully and saved at graphql
✅ GraphQL schema compiled successfully.

Edit your schema at /Users/srsmitty/code/Examples/Todo/amplify/backend/api/amplifyDatasource/schema.graphql or place .graphql files in a directory at /Users/srsmitty/code/Examples/Todo/amplify/backend/api/amplifyDatasource/schema
Successfully generated models. Generated models can be found in /Users/srsmitty/code/Examples/Todo/amplify/generated/models
✔ Code generated successfully and saved in file API.swift
Deployment state saved successfully.

GraphQL endpoint: https://********************.appsync-api.us-east-1.amazonaws.com/graphql
GraphQL API KEY: ********************

GraphQL transformer version: 2


[Todo](main *): amplify add api
? Select from one of the below mentioned services: GraphQL
⚠️ You already have an AppSync API in your project. Use the "amplify update api" command to update your existing AppSync API.


[Todo](main *): 


Steve

On Jan 16, 2024, at 10:37 AM, Adam Young ***@***.***> wrote:


@macinsmithpub <https://github.com/macinsmithpub> you are right that the documentation is still outdated, and particularly that the checkboxes are missing from the Add plugins section. For that step, I chose Todo as my target on the boxes they checked in the quickstart guide.

Did you see backed resources provision when you ran amplify init and amplify push? I am unable to see the screenshots in your comment so it's a bit challenging to diagnose what happened.

**Comment by macinsmithpub** [comment]
Hi Adam,

Everything is working fine now.  Thank you for your help.

Steve
