### ISSUE TITLE
[missing-page]

### ISSUE THREAD

**Issue by wintunmmocc** [aws-amplify/docs#4883]
**Page**: [`https://docs.amplify.aws/lib/in-app-messaging/prerequisites/q/platform/js/

**Comment by rachelnabors** [comment]
Looks like the page was removed as it was no longer required. That said, external resources may still be pointing at it. @wintunmmocc where did you find this link from?

@abdallahshaban557, can we forward this link to a more appropriate URL, like https://docs.amplify.aws/lib/in-app-messaging/getting-started/q/platform/js/ which includes a pre-reqs section?

**Comment by timngyn** [comment]
Redirect was set up and `https://docs.amplify.aws/lib/in-app-messaging/prerequisites/q/platform/js/` goes to `https://docs.amplify.aws/lib/in-app-messaging/getting-started/q/platform/js/` now
