### ISSUE TITLE
JS/RN Troubleshooting TypeScript Strict Mode

### ISSUE THREAD

**Issue by tannerabread** [aws-amplify/docs#4895]
**Describe the bug**
The first link on the page for troubleshooting TypeScript Strict Mode 
This shows up in the JavaScript picker and the React Native picker, I suspect they are using the same fragment for the troubleshooting page

**To Reproduce**
1. Go to https://docs.amplify.aws/lib/troubleshooting/strict-mode/q/platform/js/
2. Click on `strict mode` in the first paragraph
3. See error - 404 page not found (https://docs.amplify.aws/lib/troubleshooting/strict-mode/q/platform/js/q/platform/js/)

**Expected behavior**
The hyperlink for strict mode does not navigate to a 404 page

**Desktop (please complete the following information):**
 - OS: macOS 12.6.1
 - Browser: Chrome
 - Version: 107.0.5304.87

**Comment by cwomack** [comment]
Closing this as PR #4913 updates the link to the appropriate documentation from TS Docs site now.
