### ISSUE TITLE
[missing-page] Prerequisites

### ISSUE THREAD

**Issue by tlongo1226** [aws-amplify/docs#4899]
[Prerequisites](https://docs.amplify.aws/start/getting-started/setup/q/integration/android/q/integration/android/#prerequisites) page which is linked on this [page](https://docs.amplify.aws/start/sample-apps/todo-app/q/integration/android/) seems to be incorrect.

**Comment by cwomack** [comment]
Closing this as PR #4913 updates the links and no longer lead to 404 page.

**Comment by cwomack** [comment]
Thank you for your submission to help us improve the docs @tlongo1226!
