### ISSUE TITLE
amplify init doesnt work in amplify getting started documentation

### ISSUE THREAD

**Issue by edoantonioco** [aws-amplify/docs#491]
**Describe the bug**
'amplify init' doesnt work in amplify getting started documentation.

I followed this guide to set up amplify in react native expo
https://aws-amplify.github.io/docs/js/start?platform=react-native

so after installing
npm install --save aws-amplify
npm install --save aws-amplify-react-native

next step is to run 
amplify init

but it doesnt work. It says

-bash: amplify: command not found

so I cant continue. Please update this documentation to work as expected.

**Comment by kaustavghosh06** [comment]
We have a prerequisite section if you observe, at the top, which involves installing of the Amplify CLI. Did you follow the steps out there to install the CLI?

**Comment by edoantonioco** [comment]
yeah I think I didnt finished it because it failed its installation and then I assumed it was installed. But that would be another bug report.
