### ISSUE TITLE
FR - Use Semantic HTML for sidenav

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/docs#4920]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

it was noticed the left sidenav is comprised of divs, buttons, and heading 4's. this is to propose a semantic structure:

```
nav
	ul
		li details/summary - Category
			ul
				li - Category Item
```

**Describe alternatives you've considered**

**Additional context**

**Comment by rachelnabors** [comment]
I like this proposal

**Comment by reesscot** [comment]
Closing this out, as this has been implemented in the new version of the docs site! 🙌
