### ISSUE TITLE
change all occurrences of `AmplifyAuthenticator` to `Authenticator` for React examples

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/docs#4924]
**Page**: [`/guides/authentication/email-only-authentication/q/platform/[platform]`](https://docs.amplify.aws/guides/authentication/email-only-authentication/q/platform/js)

**Feedback**:

https://docs.amplify.aws/guides/authentication/email-only-authentication/q/platform/js/#ui-components

![image](https://user-images.githubusercontent.com/5033303/206020666-dff28039-73c4-4279-9ceb-d3e66a5e81a6.png)

**Comment by abdallahshaban557** [comment]
This has been fixed now
