### ISSUE TITLE
Missing images on multienv docs page

### ISSUE THREAD

**Issue by sirshannon** [aws-amplify/docs#493]
https://aws-amplify.github.io/docs/cli/multienv

<img width="1422" alt="screen shot 2019-02-24 at 3 07 23 pm" src="https://user-images.githubusercontent.com/3629297/53304672-fc66b880-3845-11e9-895d-477459ce505e.png">

A couple of the references images, both of which are currently 404:
https://aws-amplify.github.io/cli/images/AmplifyEnvSwitching.jpg
https://aws-amplify.github.io/cli/images/AmplifyEnvAddDeploySwitching.jpg

**Comment by kaustavghosh06** [comment]
We've fixed the issue. Please let us know if you're still not able to view the images.
