### ISSUE TITLE
Link no longer working on aws-exportsjs page

### ISSUE THREAD

**Issue by tylerjroach** [aws-amplify/docs#4931]
**Describe the bug**
On this page: https://docs.amplify.aws/cli/reference/files/#aws-exportsjs, there is a link to [Cognito security best practices for web app](https://forums.aws.amazon.com/message.jspa?messageID=757990#757990) that no longer resolves.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by atrasatti** [comment]
Suggest we remove the link. There doesn't seem to be a good replacement that I could find on the new re:post or in the Cognito docs
