### ISSUE TITLE
Non-JS/RN platforms missing Logger documentation 

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/docs#4942]
**Describe the bug**
Non-JS/RN platforms are missing the Logging category. At a minimum, we should have the section "Setting Logging Levels" for enabling verbose logging

**To Reproduce**
<img width="972" alt="image" src="https://user-images.githubusercontent.com/1365977/206787941-54da54c7-a287-4382-a4bd-60c676256f26.png">

**Comment by atierian** [comment]
Resolved
- https://docs.amplify.aws/swift/build-a-backend/more-features/logging/
- https://docs.amplify.aws/android/build-a-backend/more-features/logging/
