### ISSUE TITLE
Left vertical menu doesn't scroll to the very bottom

### ISSUE THREAD

**Issue by helgabalashova** [aws-amplify/docs#4943]
**Describe the bug**
When several menu items dropdowns are open, it is impossible to scroll to the very bottom of the left vertical menu. The ways to get there are to close dropdowns or to scroll all content on the right side to the bottom and then the menu will also be scrolled to the very bottom.

**To Reproduce**
1. Go to [amplify docs](https://docs.amplify.aws/lib/auth/getting-started/q/platform/js/)
2. Click on Authentication and DataStore dropdowns
3. Place cursor to the left menu and try to scroll down.
4. It will only scroll to a certain point and then content on the right will start scrolling
5. after scrolling on the right goes to the end, the menu on the left will also scroll down

**Expected behavior**
Should be able to scroll to the very bottom of the left nav bar

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version 108.0.5359.71 (Official Build) (arm64)

**Comment by timngyn** [comment]
Hi @helgabalashova, sorry I forgot to let you know that this should be fixed now. Please feel free to open another issue if there is something wrong still. Closing this issue now. Thank you!
