### ISSUE TITLE
amplify not found error after installing it globally

### ISSUE THREAD

**Issue by 5ecured** [aws-amplify/docs#4946]
I have just installed amplify by doing `npm install -g @aws-amplify/cli`

Now I am trying to `amplify configure` but it is giving me an error: `zsh: permission denied: amplify`

So I used `sudo` in front of it, entered my password, but this time it says `amplify: command not found`

I have a feeling it is likely to do with my PATH environment variable. But I am worried because I am not too familiar with this stuff. All I know is I can see my global packages are installed in both **usr -> local -> lib -> node_modules AND opt -> homebrew -> bin** because I see global packages in both folders.

Could someone please help me with this? Just give me the commands for setting my PATH env variable to be correct, and I will do it. Thanks in advance!

EDIT 1: I tried putting this command in my `zshrc`: `export PATH="$PATH:/opt/homebrew/bin/"` and it does not work. I realized that my `/opt/homebrew/bin` is actually located in `macintoshHD/opt/homebrew/bin`. This means I have to go back twice, because `$PATH` is my `userName`. so I tried putting `export PATH=$PATH:/../../opt/homebrew/bin/` but it still does not work.....

**Comment by josefaidt** [comment]
Hey @5ecured :wave: thanks for raising this! If you run `npm bin -g` does it print a warning? This is the path you'll want to add to your `PATH`.

**Comment by 5ecured** [comment]
@josefaidt I managed to fix this issue. You may close this issue. Thank you.

**Comment by josefaidt** [comment]
Hey @5ecured glad to hear you were able to resolve your issue 🙏
