### ISSUE TITLE
[missing-page]

### ISSUE THREAD

**Issue by CKalt** [aws-amplify/docs#4952]
**Page**: [`https://docs.amplify.aws/start/getting-started/auth/q/integration/lib/auth/getting-started/q/platform/js/`](https://docs.amplify.aws/start/getting-started/auth/q/integration/lib/auth/getting-started/q/platform/js/)

**Feedback**: 
This broken link is at the bottom of this [https://docs.amplify.aws/start/getting-started/auth/q/integration/react/#bonus-use-amplify-ui-primitives](https://docs.amplify.aws/start/getting-started/auth/q/integration/react/#bonus-use-amplify-ui-primitives)

Here's the paragraph:

In addition to the withAuthenticator, you can build [custom authentication flows Amplify Libraries for JS](https://docs.amplify.aws/start/getting-started/auth/q/integration/lib/auth/getting-started/q/platform/js/). Amplify's Auth class has over 30 methods including signUp, signIn, forgotPassword, and signOut that allow you full control over all aspects of the user authentication flow. Check out the complete API [here](https://aws-amplify.github.io/amplify-js/api/classes/authclass.html).

**Comment by timngyn** [comment]
@CKalt, thank you so much for creating the issue and bringing it to our attention! The link should be updated now and correctly links to https://docs.amplify.aws/lib/auth/getting-started/q/platform/js/. 

Closing the issue now, thanks again!
