### ISSUE TITLE
[Feedback]example code does not work

### ISSUE THREAD

**Issue by txtcoder** [aws-amplify/docs#4965]
**Page**: [`/start/getting-started/integrate/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/integrate/q/integration/ios)

**Feedback**:
let todos = try await Amplify.DataStore.query(Todo.self)
returns AnyPublisher type and so it will error on the next line

error build: For-in loop requires 'AnyPublisher<[Todo], DataStoreError>' to conform to 'Sequence'

**Comment by a13e** [comment]
Hey, I also faced the exact same issue, and I could fix this by re-adding amplify-swift with minimum version 2.0.0 like https://github.com/aws-amplify/amplify-swift#swift-package-manager explains.

>  Choose Up to Next Major Version and enter 2.0.0 as the minimum version for the Dependency Rule, then click Add Package.

**Comment by phantumcode** [comment]
Closing issue, please re-open if this issue still exists.
