### ISSUE TITLE
[missing-page] lambda. node version update seems to be missing 

### ISSUE THREAD

**Issue by akinwol** [aws-amplify/docs#4974]
**Page**: [`https://docs.amplify.aws/cli/migration/lambda-node-version-update/`](https://docs.amplify.aws/cli/migration/lambda-node-version-update/)

**Feedback**:

**Comment by ykethan** [comment]
Hey @akinwol, please refer to [Updating the Runtime](https://docs.amplify.aws/cli/function/configure-options/#updating-the-runtime) section on the Amplify CLI function documentation providing this information.
