### ISSUE TITLE
styleguide suggestion: use of contractions (you'll vs you will, won't vs will not)

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/docs#4980]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Consider documenting whether or not to use contractions and/or when they are appropriate. From the APA styleguide checklist:

> Conciseness (Sections 2.4–2.6): Choose words and phrases carefully and deliberately. Eliminate wordiness, redundancy, evasiveness, circumlocution, overuse of the passive voice, and clumsy prose. Do not use jargon, contractions, or colloquialisms. Avoid overusing both short, simple sentences and long, involved sentences; instead, use varied sentence lengths. Avoid both single-sentence paragraphs and paragraphs longer than one double-spaced page.

**Describe alternatives you've considered**

**Additional context**

**Comment by hibler13** [comment]
Updated style guide to include section on use of contractions.
