### ISSUE TITLE
Graphql use case for overriding with lambda

### ISSUE THREAD

**Issue by kevin-lindsay-1** [aws-amplify/docs#499]
**Is your feature request related to a problem? Please describe.**
I would like to override a resolver, but still have it ultimately do the same thing, but with custom functionality (external side effects) beforehand.

**Describe the solution you'd like**
Documentation on [the graphql cli page](https://aws-amplify.github.io/docs/cli/graphql) for the use case "Overwrite a resolver generated by the GraphQL Transform with Lambda". In my case, I want to use the generated DynamoDB table, but I simply want to put some logic in beforehand.

**Describe alternatives you've considered**
Fumbling through it.

**Additional context**

**Comment by kaustavghosh06** [comment]
We launched @function directive last week. Please take a look at this - https://aws-amplify.github.io/docs/cli/graphql#function for more information.
