### ISSUE TITLE
Async logic for iOS incorrect in auth pages

### ISSUE THREAD

**Issue by rachelnabors** [aws-amplify/docs#4993]
[Someone on Twitter](https://twitter.com/camgouldcs/status/1608357861410893825) mentioned the async logic in the Swift docs for auth is incorrect at https://docs.amplify.aws/lib/auth/getting-started/q/platform/ios/#check-the-current-auth-session

**Comment by rachelnabors** [comment]
There's a conversation about how the logic is broken: https://twitter.com/harshitadaddala/status/1610653638849855488?s=46&t=223BC6k3zAMSW8BR-ciIVQ

**Comment by phantumcode** [comment]
Closing issue as the customer issue was a result of cause Amplify Swift V1 library with Amplify Swift V2 documentation.  The Amplify Swift V2 code has been updated to mitigate the versioning confusion issue (https://github.com/aws-amplify/amplify-swift/pull/2733)
