### ISSUE TITLE
[Feedback] Potential documentation tweaking to avoid the 2 errors I found on this page

### ISSUE THREAD

**Issue by asopenag** [aws-amplify/docs#4998]
**Page**: [`/start/getting-started/setup/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/setup/q/integration/vue)

**Feedback**:

I followed the steps on the vue getting started ([here](https://docs.amplify.aws/start/getting-started/setup/q/integration/vue/)), and vscode was throwing 2 errors. Here the details and how I solved them, in case worth updating the docs:

## Error 1

Error in `main.ts` on line
```js
import awsExports from "./aws-exports";
```

It seems that adding `"allowJs": true` to the `tsconfig.json` file on `compilerOptions` solved it (`skipLibCheck = true` did not).

## Error 2

Error on `vite.config.ts` file, when adding the object to the `alias` key. The original alias was:
```js
{
  alias: {
    "@": fileURLToPath(new URL("./src", import.meta.url))
    }
}
```

it took me a moment to realize that, when using an array of alias, I'd have to switch the original object to match the find/replacement structure:

```js
{
alias: [
      {
        find: "@",
        replacement: fileURLToPath(new URL("./src", import.meta.url)),
      },
      { find: "./runtimeConfig", replacement: "./runtimeConfig.browser" },
    ],
}
```

**Comment by nadetastic** [comment]
Closing this issue as the docs updates have been merged. Thanks!
