### ISSUE TITLE
Completely Confused

### ISSUE THREAD

**Issue by bradennapier** [aws-amplify/docs#500]
So if i use amplify console do i not use amplify hosting?  These seem to be two completely unrelated related things?

Amplify Console uses the configuration from amplify cli and amplify cli hosting makes its own configurations for things outside of amplify console both do s3 and cloudfront but separate but the same...  but amplify console uses amplify cli hosting configuration and ..... LOST

I have amplify console setup now - so do i remove amplify-cli hosting?  Can you add some sort of indication of these things in the docs?  You dont even mention the amplify console exists.  Naming bieng th esame makes things very confusing - especially since they seem to intermingle but only in some edge cases and not others?  My whole setup is completely broken now and ive been waiting for cloud formation for 2 hours 

---

My current assumption is that if you use amplify console then you do not want to use amplify hosting and it is in fact a bad idea to do so. 

Perhaps `amplify hosting` should just defer to using amplify console instead?

Amplify console team fixed up most of the major flaws in their platform in the last 2 weeks and its working great and provides a really awesome git workflow.

**Comment by swaminator** [comment]
@bradennapier Thanks for using the Console and apologies for the confusion. The Amplify Console currently does not have a hosting category in the Amplify CLI (as we do not have CloudFormation support). If you want to continue using the Console for hosting, you can choose to disable the Amplify CLI hosting (which creates S3/CloudFront resources in your account).

**Comment by bradennapier** [comment]
Perfect, thanks!  Just making sure it was inline with what i was seeing and I wasnt making some big mistake :) - would be nice to add a quick note in the website docs.
