### ISSUE TITLE
[Feedback] Example data store code for relational models reports errors 

### ISSUE THREAD

**Issue by zstickel** [aws-amplify/docs#5011]
**Page**: [`/lib/datastore/relational/q/platform/[platform]`](https://docs.amplify.aws/lib/datastore/relational/q/platform/ios)

**Feedback**
When following the example code in this section for Swift/iOS and when synched to the cloud Data Store, Amplify reports this error: [ProcessMutationErrorFromCloudOperation] GraphQLError missing extensions and errorType GraphQLError(message: "The variables input contains a field name \'comments\' that is not defined for input object type \'CreatePostInput\' ", locations: nil, path: nil, extensions: nil).  
[Amplify] The operation couldn’t be completed. (Amplify.DataStoreError error 0.)

The model was created using amplfiy codegen models and the application compiles and runs with no issue. When saving to the local data store, Amplify does not complain. Only when calling the GraphQL API does this error occur. It makes Data Store unusable for relational models.

**Comment by royjit** [comment]
Hi @zstickel The example code is for datastore before adding API plugin. If you already have API plugin installed you should call `amplify push` to push the schema update to the Appsync service.
