### ISSUE TITLE
[Feedback] `amplify pull --sandboxID <uuid>` can't find schema.graphql file

### ISSUE THREAD

**Issue by jaimemarijke** [aws-amplify/docs#5017]
**Page**: [`/start/getting-started/generate-model/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/generate-model/q/integration/react-native)

**Feedback**:
When I follow the tutorial instructions, it seems like there is some kind of configuration step missing. I get this error:

```
$ amplify pull --sandboxId 6f9ad77c-9254-4527-bbe1-7a33c01c2d83
🛑 Failed to pull sandbox app.
ENOENT: no such file or directory, open '/Users/jaime/optionzero/amplified_todo/amplify/backend/api/amplifyDatasource/schema.graphql'
```

When I check my app folder hierarchy, I have `/amplify/backend`, but no `/api` folder within that.

**Comment by jaimemarijke** [comment]
It seems like maybe the react native tutorial should have something like this page from the react tutorial? https://docs.amplify.aws/start/getting-started/data-model/q/integration/react/#deploying-the-api

**Comment by Andrewk311** [comment]
> **Page**: [`/start/getting-started/generate-model/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/generate-model/q/integration/react-native)
> 
> **Feedback**: When I follow the tutorial instructions, it seems like there is some kind of configuration step missing. I get this error:
> 
> ```
> $ amplify pull --sandboxId 6f9ad77c-9254-4527-bbe1-7a33c01c2d83
> 🛑 Failed to pull sandbox app.
> ENOENT: no such file or directory, open '/Users/jaime/optionzero/amplified_todo/amplify/backend/api/amplifyDatasource/schema.graphql'
> ```
> 
> When I check my app folder hierarchy, I have `/amplify/backend`, but no `/api` folder within that.

Were you able to solve this? I have the same issue.

**Comment by Andrewk311** [comment]
> > **Page**: [`/start/getting-started/generate-model/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/generate-model/q/integration/react-native)
> > **Feedback**: When I follow the tutorial instructions, it seems like there is some kind of configuration step missing. I get this error:
> > ```
> > $ amplify pull --sandboxId 6f9ad77c-9254-4527-bbe1-7a33c01c2d83
> > 🛑 Failed to pull sandbox app.
> > ENOENT: no such file or directory, open '/Users/jaime/optionzero/amplified_todo/amplify/backend/api/amplifyDatasource/schema.graphql'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When I check my app folder hierarchy, I have `/amplify/backend`, but no `/api` folder within that.
> 
> Were you able to solve this? I have the same issue.

Never mind I figured out the issue, it happens if you run "Amplify init" before doing this.

**Comment by tannerabread** [comment]
@cesarisern feel free to try the new in progress/updated guide through [this link](https://pr-5350.d39agkzf0cwtdz.amplifyapp.com/start/q/integration/react-native/)
