### ISSUE TITLE
Example content order is swapped 

### ISSUE THREAD

**Issue by ajilpm** [aws-amplify/docs#502]
Hi, the example code for the 'define auth challenge' and 'create auth challenge' in https://aws-amplify.github.io/docs/js/authentication#custom-authentication-in-amplify is swapped here. Please correct it, I lost almost a day figuring it out while implementing the given example.

**Comment by powerful23** [comment]
@ajilpm sorry about that. I will send a pr to fix it. Thanks for your feedback!
