### ISSUE TITLE
Can I use my own figma design system file? instead of Amplify UI Kit 

### ISSUE THREAD

**Issue by ThiyaDezine** [aws-amplify/docs#5027]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ThiyaDezine** [comment]
I have project specific figma design system (.fig)files. How to sync it with Amplify studio.

**Comment by ThiyaDezine** [comment]
@jacoblogan 
![Screenshot (17)](https://user-images.githubusercontent.com/122968305/215031310-14b55d2a-051d-4511-b120-72de287e6c0e.png)
Kindly help me to resolve  figma import errors.

**Comment by ykethan** [comment]
hey @ThiyaDezine, could you open this issue in our Amplify Studio repository using the bug report: https://github.com/aws-amplify/amplify-studio/issues/new/choose . This assist us in collecting information and diving deeper into the issue.
