### ISSUE TITLE
Fix Getting started > React Native >Tutorial

### ISSUE THREAD

**Issue by mradenovic** [aws-amplify/docs#5032]
## Problem
This issue is related to #4902, #4903, #4955,  #4956, #5016, and #5017. 

**Getting started > React Native** tutorial is pulling fragments from **lib** documentation which might be outdated.

Tutorials have two different approaches:

* **AWS Amplify Studio** (e.g. React Native)
* **amplify-cli**  (e.g React)

React Native example is confusing and misleading, especially if one looks at React example first. 

## Proposition
Make consistent tutorials across frameworks that use `ampify-cli`. All tutorials should use the same project name, model name, and `amplify-cli` instructions.

- [ ] Create React Native tutorial based on React tutorial
- [ ] Identify identical sections and extract them into fragments (React and Vue already have a lot of reusable code)
- [ ] Identify steps that can be logically separated
  - [ ] Prerequisites
  - [ ] Setup fullstack project
  - [ ] Generate model files (identical for all `js` frameworks)
  - [ ]  Connect to API
  - [ ] Add authentication
  - [ ] Deploy and host
- [ ] Use new fragments to update the rest of the tutorials

I have started #5026 for this and I would appreciate any thoughts/guidance.

**Comment by webgunner** [comment]
Hey @mradenovic 
I'm a great fan of React Native and Amplify. Have you ever tried edit the page at Amplify Docs? You can fork the repo and request a pull. Have you seen the edit button in the page?
