### ISSUE TITLE
[Feedback]FEEDBACK_TITLE_HERE

### ISSUE THREAD

**Issue by wyltsi** [aws-amplify/docs#5041]
**Page**: [`/lib/datastore/data-access/q/platform/[platform]`](https://docs.amplify.aws/lib/datastore/data-access/q/platform/js)

**Feedback**:

Documentation is not accurate on querying data with filters. The current syntax is:
const posts = await DataStore.query(Post, c => c.rating("gt", 4))

**Comment by renebrandel** [comment]
Hi the page is actually correct as part of the Amplify JS v5 launch, we've updated our syntax. See more details here: https://aws.amazon.com/blogs/mobile/announcing-aws-amplify-javascript-library-version-5/?sc_channel=sm&sc_campaign=Mobile_Campaign&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&trk=sm_mobile_community&linkId=190803802
