### ISSUE TITLE
[Feedback]Add note explaining AppSync does not support custom directives.

### ISSUE THREAD

**Issue by enots227** [aws-amplify/docs#5044]
**Page**: [`/cli-legacy/graphql-transformer/directives`](https://docs.amplify.aws/cli-legacy/graphql-transformer/directives)

**Feedback**:

Can you add a note explaining that custom directives are not supported in AWS AppSync? This page lists the AWS AppSync-provided directives and then it lists 3rd party directives with a link on how create your own transformer & directives, which caused me to assume I could create custom directives for AppSync as well. 

I eventually found this that gave me the answer. https://stackoverflow.com/questions/60048645/aws-appsync-defining-graphql-schema-with-custom-directives

**Comment by renebrandel** [comment]
Hi @enots227 thanks for this feedback. Given that this is more specific feedback about the AppSync service, I recommend you to open up an issue at https://github.com/aws/aws-appsync-community. Amplify leverages many AWS services under the hood and therefore we don't intend to document all service limitations in the Amplify documentation. I'm happy to pursue this further for the Amplify documentation if we get more traction on this issue in the future.

**Comment by renebrandel** [comment]
Hi @enots227 thanks for this feedback. Given that this is more specific feedback about the AppSync service, I recommend you to open up an issue at https://github.com/aws/aws-appsync-community. Amplify leverages many AWS services under the hood and therefore we don't intend to document all service limitations in the Amplify documentation. I'm happy to pursue this further for the Amplify documentation if we get more traction on this issue in the future.
