### ISSUE TITLE
No RESTful API in the "Connect API and database to the app" chapter.

### ISSUE THREAD

**Issue by An-miyoung** [aws-amplify/docs#5054]
### Amplify CLI Version

10.6.2

### Question

 I want to deploy server-less react project using aws aplify, RESTful api, DynamoBD.

Unfortunately, there's no document about RESTful api.
(https://docs.amplify.aws/start/getting-started/data-model/q/integration/react/)

please, update the contents about "Connect RESTful API and database to the app"

**Comment by renebrandel** [comment]
Hi, our recommended path is to use the GraphQL API as the default mechanism. Given that you're viewing our "overall getting started" guide, we try to provide an opinionated path forward. As Josef has pointed out, there are additional resources available on other pages for REST APIs specifically.
