### ISSUE TITLE
How to: Automatic/programmable push notifications

### ISSUE THREAD

**Issue by bernhardt1** [aws-amplify/docs#5061]
**Is your feature request related to a problem? Please describe.**
Handling automatic push notifications seems to require somewhat hacky solutions. I have not been able to find a conventional approach to handle these notifications within amplify/ AWS mobile.

**Describe the solution you'd like**
A tutorial or article explaining the conventional solution to automatic push notifications within amplify/AWS mobile suite. 

**Describe alternatives you've considered**
Based on tutorials and articles I've pieced together a solution. Something like:
track if user is online/offline -> use appsync local resolver to catch desired notification and send to lambda -> use lambda to generate a 1-time pinpoint message.

Thanks in advance.

**Comment by abdallahshaban557** [comment]
Hello! We have launched a new version of Push Notifications for React Native, Swift, Android, and Flutter. You can follow this tutorial to learn more about programatically sending push notifications from your backend.

https://docs.amplify.aws/lib/push-notifications/getting-started/ 

https://dev.to/codebeast/take-advantage-of-aws-amplifys-push-notification-feature-in-a-react-native-app-2cd2
