### ISSUE TITLE
Typo in example for custom elasticsearch resolver

### ISSUE THREAD

**Issue by chris-merapar** [aws-amplify/docs#510]
**Describe the bug**
The example on the following page gives the DataSourceName as ElasticsearchDomain, but it should be ElasticSearchDomain:

https://aws-amplify.github.io/docs/cli/graphql#add-a-custom-geolocation-search-resolver-that-targets-an-elasticsearch-domain-created-by-searchable

Otherwise Cloudformation will give an error and the amplify push will fail.

**Comment by kaustavghosh06** [comment]
@chris-merapar  This issue has been fixed.
