### ISSUE TITLE
[Feedback]Disappointed in the new content management update

### ISSUE THREAD

**Issue by Bobby-Amali** [aws-amplify/docs#5102]
**Page**: [`/console/data/content-management`](https://docs.amplify.aws/console/data/content-management)

**Feedback**:

I use your content manager for my blog and for some reason I cannot find the markdown editor anymore

**Comment by timngyn** [comment]
Hi @Bobby-Amali, I saw you posted the issue to the Amplify Studio repo: https://github.com/aws-amplify/amplify-studio/issues/815

I'll close this issue in favor of that one as I think it pertains to the app and not the Docs site
