### ISSUE TITLE
missing CLI command reference page

### ISSUE THREAD

**Issue by iwasinnam** [aws-amplify/docs#5103]
**Page**: [`https://docs.amplify.aws/cli/commands/env/`](https://docs.amplify.aws/cli/commands/env/)

**Feedback**: 
`amplify env add --help` directs me to this url

**Comment by vimode** [comment]
That page seems to have been moved to <https://docs.amplify.aws/cli/teams/commands/>

A possible solution is to create a new page /cli/commands/env with relevant information OR 
update the `cli-core` package's redirect link which might be a little complicated
https://github.com/aws-amplify/amplify-cli/blob/3fe58dddeffa8d891a3969c5b3f19d32ff544a11/packages/amplify-cli-core/src/help/help-helpers.ts#L57-L59
