### ISSUE TITLE
[Feedback] No documentation?

### ISSUE THREAD

**Issue by awesome-crab** [aws-amplify/docs#5112]
**Page**: [`/lib/storage/upload/q/platform/[platform]`](https://docs.amplify.aws/lib/storage/upload/q/platform/js)

**Feedback**:

Hello everyone,

I am pretty much overwhelmed by the aws documentation. 
And on top of that it feels like it is no "real" documentation.
It feels like somebody wrote an online blog about all the aws services. 
It is nice that in these blogposts some functionalities are described as use cases. But I would like to have a complete documentation of all arguments and parameters a function takes. And I cant seem to find that. Its just blog posts over and over.

I.e. I would like to know which parameters I can pass to the Storage.put() function from aws-amplify. Sure there is this site: https://docs.amplify.aws/lib/storage/upload/q/platform/js/ but I cannot find the documentation on that function. Additional to what parameters can be passed I would like to look at the documentation to see what is returned from the put function. What are the expected responses? 

So to add all up, the aws docs feel like a big pile of blogposts not related to each other (eventough they are). Some of the blogposts are tutorials (which dont work anymore because they are out of date (deprecated)). The documentation feels incomplete because not all parameters of a function are described.

Now it might be possible that what I am looking for exists, a traditional documentation of the functions, classes etc. available. But I cannot seem to find it. All I find are these "blog posts" which never answer the exact question I have.

So maybe for the future, if anyone ever needs to decide wheter they should create a documentation or more of a blog about the service: GO FOR THE FULL DOCUMENTATION NOT FOR THE BLOG.

thanks for reading and best regards

**Comment by rachelnabors** [comment]
Hello, friend. We hear you, and we thank you for your candid words. Currently, the Amplify documentation lives in multiple places. Is this what you were looking for? https://aws-amplify.github.io/amplify-js/api/classes/storage.html#put Our JS Libraries have their own generated docs, but they are not easy to find. We are working on making them better, and your feedback helps us prioritize this work.

We are currently working on some big changes for the docs site. If you're interested, we'd love to share what we're up to and get your feedback. Please just drop your email and name here: https://pulse.buildon.aws/survey/UPPFGGIG

Thank you again. I will leave this issue open until we achieve our goals and deliver a docs site you can love.

**Comment by awesome-crab** [comment]
thank you for pointing me to https://aws-amplify.github.io/amplify-js/api/classes/storage.html#put.
Indeed, this is what I was looking for.
But I have never seen this site before. Looks so different than other aws websites... 😄 
Thank you and have a good day!!

**Comment by rachelnabors** [comment]
Unassigning myself as I’ve moved on from AWS Amplify
