### ISSUE TITLE
Support schema documentation

### ISSUE THREAD

**Issue by kevin-lindsay-1** [aws-amplify/docs#512]
**Is your feature request related to a problem? Please describe.**
Documentation placed in my SDL does not show up in graphiql

**Describe the solution you'd like**
Support of the common documentation methods:

**Fields and Types:**
```
"""
Documentation on a Type
"""
type Person {
  """
  Documentation on a Field
  """
  id: ID!
  name: String!
}
```

**Arguments:**
```
type Query {
  person(
    "Documentation for an argument"
    name: String = "Bob"
  ): Person
}
```

**Comment by kaustavghosh06** [comment]
@kevin-lindsay-1 We have a corresponding feature request on the CLI repository and we're tracking it out there. Thanks for opening up this feature request.
