### ISSUE TITLE
[Feedback]FEEDBACK_TITLE_HERE

### ISSUE THREAD

**Issue by 1968692655** [aws-amplify/docs#5120]
**Page**: [`/start/getting-started/nextsteps/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/nextsteps/q/integration/vue)

**Feedback**:

**Comment by tannerabread** [comment]
Hi @1968692655 what was the feedback for this page?

**Comment by abdallahshaban557** [comment]
Hi @1968692655 - can you please provide us with the feedback on this page?

**Comment by tannerabread** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and are in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
