### ISSUE TITLE
Data manager not showing anything after adding authentication

### ISSUE THREAD

**Issue by matart15** [aws-amplify/docs#5122]
**Describe the bug**
Data manager was showing my data models. But after adding authentication it is stuch in this state

![スクリーンショット 2023-02-17 001145](https://user-images.githubusercontent.com/17027219/219406322-5ddb14da-c11b-4bd5-a818-19342ac75e6e.png)

**To Reproduce**
1. Go to Data, create model
2. Go to Data manager, confirm it is showing
3. Go to authentication and add email based auth
4. Got to data manager again. it does not show data

**Expected behavior**
Data manager to display datas

**Screenshots**
added

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 110.0.5481.97

**Additional context**
Maybe it is not related to auth. But I don't know how to debug

**Comment by matart15** [comment]
It showed up moment i deleted Authentication.

**Comment by ykethan** [comment]
hey @matart15, could you open this issue on Amplify studio repository with the bug template: https://github.com/aws-amplify/amplify-studio/issues/new/choose. Please provide us your schema as this would enable us to dive deeper into the issue. Additionally, could you open the browser debug console and provide a screenshot of the error if you observe any in the new issue.
