### ISSUE TITLE
Cannot create a schema that does not have an @model directive in it

### ISSUE THREAD

**Issue by kevin-lindsay-1** [aws-amplify/docs#513]
**Describe the bug**
It appears that my schema _must_ have an @model directive in it in order for AppSync to create it

**To Reproduce**
Create a schema without an @model and watch it fail when trying to set up the stack

**Expected behavior**
The schema is compiling, meaning it's valid SDL, therefore the expected behavior is to not necessarily have a table attached to every schema, for certain use cases of non-persisted data only

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.3
 - Browser: Chrome
 - Version: 72.0.x

**Comment by kaustavghosh06** [comment]
@kevin-lindsay-1 This issue has been fixed in th latest version of the CLI.
