### ISSUE TITLE
Feedback: Update @key docs to notify of deprecation

### ISSUE THREAD

**Issue by wheresthecode** [aws-amplify/docs#5130]
**Page**: [`/cli-legacy/graphql-transformer/key`](https://docs.amplify.aws/cli-legacy/graphql-transformer/key)

**Feedback**:

This page needs to be updated as the @key directive is now deprecated. It would be nice to have documentation on the replacement @index directive and a link to it.

**Comment by vimode** [comment]
For me the page you linked shows an information modal at the bottom left of the page which links to the latest docs [here](https://docs.amplify.aws/cli/graphql/data-modeling/)

![GraphQL transformer v2 docs](https://user-images.githubusercontent.com/39148877/219876971-e1a4b4e3-a5b4-4b76-b798-3f743f40904f.png)

**Comment by wheresthecode** [comment]
Oh I see. Apologies I didn't notice that! thanks for the response
