### ISSUE TITLE
[Feedback]Need update to document

### ISSUE THREAD

**Issue by chanaka3d** [aws-amplify/docs#5131]
**Page**: [`/start/getting-started/setup/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/setup/q/integration/react-native)

**Feedback**:

Overall the article is helpful. But a few issues need attention.

The step where the app is created with the name `amplified_todo `, but in the next step it asks to cd in to `my-app`.

```javascript
import awsconfig from './src/aws-exports'
```

There is no reference to how this file is created. 

Thank you.

**Comment by vimode** [comment]
I think #5026 fixes this.
