### ISSUE TITLE
[Feedback]JavaScript Getting Started Guide has link for Push Notification

### ISSUE THREAD

**Issue by tannerabread** [aws-amplify/docs#5151]
**Page**: [`/start/getting-started/nextsteps/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/nextsteps/q/integration/js)

**Feedback**:
JavaScript Getting Started Guide -> Next Steps 
Shows a link to add Push Notification but this is not currently available for JS

Recommend removing link

**Comment by LalitAswal** [comment]
i am interested to work on this issue.
