### ISSUE TITLE
DataStore `Manipulating Data` code example is broken

### ISSUE THREAD

**Issue by david-mcafee** [aws-amplify/docs#5156]
**Describe the content issue**:
A clear and concise description of what the content issue is. Is there content missing or is there incorrect content?
The code example from the listed docs page does not work when attempting to input data into the input field, resulting in a `The source object is not a valid model` error. This is because a record was never first created, and `copyOf` expects a valid model (not `undefined`).

**URL page where content issue is**:
https://docs.amplify.aws/lib/datastore/data-access/q/platform/js/#create-and-update

**Comment by renebrandel** [comment]
Issue is addressed by initial PR.
