### ISSUE TITLE
[Feedback]Legacy link on Delete User section for JS/RN

### ISSUE THREAD

**Issue by tannerabread** [aws-amplify/docs#5192]
**Page**: [`/lib/auth/delete_user/q/platform/[platform]`](https://docs.amplify.aws/lib/auth/delete_user/q/platform/react-native)

**Feedback**:

The `GraphQL transformer` link on the page goes to the [legacy page](https://docs.amplify.aws/cli-legacy/graphql-transformer/overview/) when it should go to the [newer version of those docs](https://docs.amplify.aws/cli/graphql/overview/)

**Comment by LalitAswal** [comment]
Hi @tannerabread, I would like to work on this issue.

**Comment by tannerabread** [comment]
Hi again @LalitAswal, please do :)
Remember again to follow the [contribution guidelines](https://github.com/aws-amplify/docs#amplify-documentation)

Thank you for contributing!

**Comment by LalitAswal** [comment]
sure @tannerabread,  you can assign this issue to me

**Comment by tannerabread** [comment]
@LalitAswal getting a little clarity on where we would rather point this link to or if we want to copy over the extra information that is in the legacy section to somewhere in the latest docs. Stay tuned before you submit that PR please
