### ISSUE TITLE
DocSet for Xcode documentation incomplete and/or incorrect

### ISSUE THREAD

**Issue by sirshannon** [aws-amplify/docs#520]
**To Reproduce**
1. Go to https://aws-amplify.github.io/docs/ios/manualsetup#direct-aws-service-access
2. Read "Open the macOS terminal and go to the directory containing the expanded archive."
3. Wonder what expanded archive this could be.
4. Continue reading.
 > For example:
>`$ cd ~/Downloads/aws-ios-sdk-2.9.0`
5. Maybe there is a link to a zip file with that name somewhere on this page?
6. Find one (under Frameworks).
7. Download it.
8. Continue reading.
>Copy (or move) documentation/com.amazon.aws.ios.docset from the SDK installation files
9. Assume you downloaded the wrong thing because there is no documentation folder or docset in the expanded archive.
10. Repeat the download and dismay with several archives from the github repo.
11. Give up and file this bug report.

**Expected behavior**
A clear and concise description of how to use DocSets in Xcode for aws-iOS-sdk.

**Comment by rohandubal** [comment]
Hello @sirshannon 

Sorry that you are having issues using the docset for iOS SDK. I can confirm that the documentation is not up-to-date and needs some updates to make it work. I will create a PR which has the correct instruction that updates the docs on website as well.

Thanks,
Rohan

**Comment by rohandubal** [comment]
Hello @sirshannon 

Currently there isn't a download where the docset is attached. I will work on getting it added with the SDK download.

In the meanwhile, if you need to add the docset, you will have to clone the SDK repository and generate the docset manually by using the scripts in the `Scripts` folder.

You will have to run `sh Scripts/GenerateAppleDocs.sh` which will generate the docset in `docs/` folder which you can then use to add it to Xcode. It uses `appledoc` to generate the docset, so you will have to install `appledoc` before running the script. Apologies for the inconvenience.

Best,
Rohan

**Comment by sirshannon** [comment]
This is marked as a bug, is not fixed, and is waiting on you to do the work. It should not be closed.
