### ISSUE TITLE
Storage.list paginated file access example doesn't work

### ISSUE THREAD

**Issue by TentacoolKid** [aws-amplify/docs#5210]
**Describe the bug**
The example given in the Storage.list docs for use of v5's [paginated file access](https://docs.amplify.aws/lib/storage/list/q/platform/js/#paginated-file-access) does not work.

When the `nextToken` parameter is supplied with a value of `undefined` as it is in the docs, the response returns null instead of the first set of results of length PAGE_SIZE and any nextToken corresponding to further results. 

To fix this you should only supply the nextToken option when calling `Storage.list` if you are supplying it with a real token string value. Here is an example of how that might look

```js
const PAGE_SIZE = 20;
let nextToken = undefined;
let hasNextPage = true;

const loadNextPage = async () => {
  if (hasNextPage) {
    const listOptions = {
        pageSize: PAGE_SIZE,
      };
    if (nextToken) {
      listOptions.nextToken = nextToken;
    };
    let response = await Storage.list('photos/', {
      pageSize: PAGE_SIZE,
      pageToken: nextToken,
    });
    if (response.hasNextToken) {
      nextToken = response.nextToken;
    } else {
      nextToken = undefined;
      hasNextPage = false;
    }
    // render list items from response.results
  }
}
```

**Additional context**
It also appears that these Storage.list paginated file access [docs](https://docs.amplify.aws/lib/storage/list/q/platform/js/#paginated-file-access) were updated recently to swap the parameter name `pageToken` to now say `nextToken`. Your original [v5 features post](https://aws.amazon.com/blogs/mobile/announcing-aws-amplify-javascript-library-version-5/) also needs updating to reflect this as it is misleading

**Comment by nadetastic** [comment]
Hi @TentacoolKid thanks for opening this issue, I've taken a look however Im not experiencing the problem that you described.

Supplying `nextToken` as `undefined` returns the first items based on what my `pageSize` is - for example:

```js
const response = await Storage.list('',{
    pageSize: 2,
    nextToken: undefined,
});
```
This returns the first 2 items:
```json
{
    "hasNextToken": true,
    "nextToken": "<next_token_value>",
    "results": [
	    "0":{},
	    "1":{}
	]
}
```
Could you provide any additional context on how your app is configured?

Regarding the additional note, I'm working to get the blog post update, thank you for pointing that out 😄

**Comment by nadetastic** [comment]
Hi @TentacoolKid - I'm going to go ahead and close this issue. If you have any questions or are still having problems with the `Storage.list` method, please [file an issue within the Javascript library repo](https://github.com/aws-amplify/amplify-js/issues/new?assignees=&labels=pending-triage&template=1.bug_report.yaml). Thanks!
