### ISSUE TITLE
Return 404 on broken links

### ISSUE THREAD

**Issue by 0618** [aws-amplify/docs#5221]
**Describe the bug**
A link without `/` at the end would be auto-redirected to `/` and return a 301.
If it's a broken link, it should return 404.

**To Reproduce**
1. Open the devTool --> Network
2. Go to 'https://docs.amplify.aws/lib/auth/getarted/q/platform/js'
3. See the log, the link was redirected to 'https://docs.amplify.aws/lib/auth/getarted/q/platform/js/' and return a 301
4. Then it returns 404

**Expected behavior**
It should return a 404 directly

**Comment by lavr001** [comment]
Closing this issue per discussion with @0618, known Next.js issue.
