### ISSUE TITLE
Inconsistent use of platform switcher / block switchers to display platform content

### ISSUE THREAD

**Issue by rachelnabors** [aws-amplify/docs#5227]
**Describe the bug**
On the [libraries side of the site](https://docs.amplify.aws/lib/q/platform/js/), I get a platform switcher to only see content relating to my platform of choice.
![Screenshot 2023-03-09 at 9 40 32 AM](https://user-images.githubusercontent.com/236306/224113714-845e69a7-51f2-4179-8b4c-d42ddfac9100.png)

On the [CLI side of the site](https://docs.amplify.aws/cli/auth/admin/#example), the switcher is gone, and I have to switch between platforms on individual code examples.
![Screenshot 2023-03-09 at 9 40 20 AM](https://user-images.githubusercontent.com/236306/224113912-c55953ed-4975-4ae4-b029-e2ed3e3757b2.png)

**Expected behavior**
I expect one platform picker for the entire site experience. Do not show me iOS things when I have clearly stated I'm looking at JavaScript code. Do not show me Android things when I have stated that I am an iOS engineer.

**Comment by hbuchel** [comment]
Closing since the site has been rearchitected and the platform navigator now affects the entire IA.
