### ISSUE TITLE
Typo in Flutter sign-in sample code

### ISSUE THREAD

**Issue by kg0r0** [aws-amplify/docs#5245]
**Describe the content issue**:
The following sample code appears to have a typo.

https://github.com/aws-amplify/docs/blob/bf3c733bbb7e48617c37f69fdac47868728aaf17/src/fragments/lib/auth/flutter/signin/30_signIn.mdx?plain=1#L13

I think ``result.isSignedIn`` is correct, not ``res.isSignedIn``. Could you please confirm if I can submit a pull request for this fix?
**URL page where content issue is**:

https://docs.amplify.aws/lib/auth/signin/q/platform/flutter/#sign-in-a-user

**Comment by abdallahshaban557** [comment]
Yes, you are correct @kg0r0 ! Please feel free to submit a PR!

**Comment by abdallahshaban557** [comment]
Your PR has been merged now! Thank you so much for the contribution!
