### ISSUE TITLE
[Feedback]JSON parse error when following JS getting started guide

### ISSUE THREAD

**Issue by minamidate216** [aws-amplify/docs#5247]
**Page**: [`/start/getting-started/setup/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/setup/q/integration/js)

**Feedback**:

nom startにて以下のエラーが出ます
npm ERR! code EJSONPARSE
npm ERR! path /Users/minamidatehiroki/amplify-js-app/package.json
npm ERR! JSON.parse Unexpected token ":" (0x3A) in JSON at position 9 while parsing near "\"scripts\": {\n    \"start\": \"we..."
npm ERR! JSON.parse Failed to parse JSON data.
npm ERR! JSON.parse Note: package.json must be actual JSON, not just JavaScript.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/minamidatehiroki/.npm/_logs/2023-03-15T08_51_44_564Z-debug-0.log

**Comment by tannerabread** [comment]
Hi @minamidate216, I checked this page to see if we had an error somewhere in our docs but I was only able to get this error when I _**replaced**_ the contents of `package.json` with the code shown here
![image](https://user-images.githubusercontent.com/30082936/225348295-c55408f3-2da9-49f2-af3b-c073ba40f4b6.png)

The instructions want you to _**add**_ the contents to your `package.json` which will give you a complete file like below:
```json
{
  "name": "amplify-js-app",
  "version": "1.0.0",
  "description": "",
  "main": "webpack.config.js",
  "scripts": {
    "start": "webpack && webpack-dev-server --mode development",
    "build": "webpack"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "aws-amplify": "^5.0.19"
  },
  "devDependencies": {
    "copy-webpack-plugin": "^11.0.0",
    "webpack": "^5.76.1",
    "webpack-cli": "^5.0.1",
    "webpack-dev-server": "^4.12.0"
  }
}

```

Let me know if this doesn't solve/fix the issue for you

**Comment by tannerabread** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and are in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
