### ISSUE TITLE
`Amplify.Auth.signInWithWebUI(presentationAnchor: self.view.window!)` without `try await` before it does not work.

### ISSUE THREAD

**Issue by NakaokaRei** [aws-amplify/docs#5249]
**Describe the content issue**:
`Amplify.Auth.signInWithWebUI(presentationAnchor: self.view.window!)` without `try await` before it does not work.

Current
```swift
func signInWithWebUI() async {
    do {
        let signInResult = Amplify.Auth.signInWithWebUI(presentationAnchor: self.view.window!)
        if signInResult.isSignedIn {
            print("Sign in succeeded")
        }
    } catch let error as AuthError {
        print("Sign in failed \(error)")
    } catch {
        print("Unexpected error: \(error)")
    }
}
```

Contents to be modified
```swift
func signInWithWebUI() async {
    do {
        let signInResult = try await Amplify.Auth.signInWithWebUI(presentationAnchor: self.view.window!)
        if signInResult.isSignedIn {
            print("Sign in succeeded")
        }
    } catch let error as AuthError {
        print("Sign in failed \(error)")
    } catch {
        print("Unexpected error: \(error)")
    }
}
```

**URL page where content issue is**:
https://docs.amplify.aws/lib/auth/signin_web_ui/q/platform/ios/#update-infoplist:~:text=let%20signInResult%20%3D-,Amplify,-.Auth.

**Comment by dcristolovean** [comment]
![Screenshot 2023-03-16 at 14 47 31](https://user-images.githubusercontent.com/1563547/225622527-c2bc7bac-57c8-4e4e-aaa7-3adbc07cebf3.png)

and the first error says:  No calls to throwing functions occur within try expression.

**Comment by NakaokaRei** [comment]
@dcristolovean 
Since `Amplify.Auth.signInWithWebUI(presentationAnchor: self.view.window!)` is an `async throws` function, is there an error if I don't add `try await`?

![image](https://user-images.githubusercontent.com/39183069/225627067-770a93f6-0472-4917-b353-32b4f6c5f378.png)

**Comment by dcristolovean** [comment]
![Screenshot 2023-03-16 at 16 07 02 1](https://user-images.githubusercontent.com/1563547/225642914-e7fba5f7-41d1-47fa-b359-6fe07f359ae9.png)

Other stuff happens then :).   

Long story short, I'm try to investigate migration from pre-Amplify code (and some AWSMobileClient) to Amplify and the process is slow and painful.
The doc is full of inconsistencies like that, code that doesn't work and so on.
Not to mention a complete lack of how to use Amplify without the json file, creating everything in code.  Very disappointing, it was the exact same thing years ago when we first implemented it and it's the exact same now with Amplify.
