### ISSUE TITLE
Version conflicts between AWSAppSync and AWSCore

### ISSUE THREAD

**Issue by N1LaT** [aws-amplify/docs#525]
**Describe the bug**
When trying to use AWSAppSync Pod Version 2.10.2 it says that it needs AWSCore 2.8.0. I need the latest version (2.9.2) though because I need the AWSMobileClient functions such as initialize.

**To Reproduce**
Add pod 'AWSAppSync', '~> 2.10.0'
Add pod 'AWSCore', '~> 2.9.0'
do a pod update / install

**Expected behavior**
It should install all the pods with the newest version

**Desktop (please complete the following information):**
 - OS: macOS 10.14.3
- cocoapods 1.6.1

**Comment by rohandubal** [comment]
Hello @N1LaT 

Sorry that you are having issues using the SDK. 

You are right, this is currently an issue and we already have a fix for it https://github.com/awslabs/aws-mobile-appsync-sdk-ios/pull/191 which will be released in an upcoming release.

Thanks,
Rohan

**Comment by N1LaT** [comment]
Hey and thanks for your reply.

When will this be released? Because I need it really quick ;)
Is there a possibility to do dynamo db querys without AwsAppSync in the meantime?
For users from an user pool as well as from an identity pool?

Thanks

**Comment by rohandubal** [comment]
Hello @N1LaT 

SDK version `2.10.3` is now released which fixes the version issue which you described. Please let us know if you continue to face the issues.

To do queries directly from dynamodb you would have to use `DynamoDB ObjectMapper` available in the SDK with IAM access via Cognito Identity configured to federate with Cognito UserPools. 

Hope this helps,
Rohan
