### ISSUE TITLE
Ionic Docs - Code Error

### ISSUE THREAD

**Issue by MattMcCherry** [aws-amplify/docs#527]
**Describe the bug**
When completing the Ionic Amplify tutorial, it appears there is a bug with the code. In part 4 under, "Adding CRUD Functionality to Your App". Modal uses 
`this.modal.onDidDismiss((result) => { ... })`. 
This no longer works and needs to read 
`this.modal.onDidDismiss().then((result) => { ... })`.

**To Reproduce**
Follow the tutorial to experience the issue. Or just use modalController in Ionic you will see that this does not work anymore.

**Expected behavior**
Data is passed to the parent component and the docs are correct.

**Additional context**
Will add a quick PR with change. Also, I have tested this working fix in my own repo [here](https://github.com/MattMcCherry/ionic-aws-todo).

**Comment by jordanranz** [comment]
Thanks for contributing!

I will close this issue as it seems your PR was merged. Please reopen if any related problems occur.
