### ISSUE TITLE
[Feedback] Amplify + Out-of-band modifications

### ISSUE THREAD

**Issue by weisisheng** [aws-amplify/docs#5318]
**Page**: [`/guides/api-graphql/subscriptions-by-id/q/platform/[platform]`](https://docs.amplify.aws/guides/api-graphql/subscriptions-by-id/q/platform/js)

**Feedback**:

Would like to see a simple example of OOB modifications documented here.  There are a handful of examples which can only be found by wide google search.  Appsync<-->OOB mutations are relatively easy, so the last piece is bringing it in to the front end.

**Comment by AnilMaktala** [comment]
Hi @weisisheng, Thank you for raising this. Could you please elaborate your use case?
