### ISSUE TITLE
[Feedback]ListRestaurants

### ISSUE THREAD

**Issue by Tkumar02** [aws-amplify/docs#5328]
**Page**: [`/start/getting-started/data-model/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/data-model/q/integration/angular)

**Feedback**:

Does the ListRestaurants and .CreateRestaurant need to be declared somewhere? it's throwing errors for me?
![image](https://user-images.githubusercontent.com/77967047/229516225-502ababb-9971-444d-8ac8-b9e079953064.png)

**Comment by AnilMaktala** [comment]
Hi @Tkumar02, Thanks for raising this issue. I have gone through the documents and was not able to replicate the issue you mentioned. 
Nevertheless, I would like to ask you a few more questions. 

  1. Have you followed the instructions provided in this link: https://docs.amplify.aws/start/getting-started/data- 
     model/q/integration/angular/#model-the-data-with-graphql-transform? If you have, could you kindly share the contents of 
     the /src/app/API.service.ts file?
  2. Additionally, did you change the name of the aws-export.js file to aws-exports.ts?

<img width="306" alt="image" src="https://user-images.githubusercontent.com/3206171/231616936-5af43719-85b7-477b-ac55-8f544ad41297.png">

<img width="904" alt="image" src="https://user-images.githubusercontent.com/3206171/231617049-446f9fcd-7b96-44d2-b465-f9fcbe71a2f2.png">

Here is my restaurants.component.ts content:
```
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { APIService, Restaurant } from '../API.service';

@Component({
  selector: 'app-restaurants',
  templateUrl: './restaurants.component.html',
  styleUrls: ['./restaurants.component.css']
})
export class RestaurantsComponent {
  public createForm: FormGroup;

  public restaurants: Array<Restaurant> = [];

  constructor(private api: APIService, private fb: FormBuilder) {
    this.createForm = this.fb.group({
      name: ['', Validators.required],
      description: ['', Validators.required],
      city: ['', Validators.required]
    });
  }

  async ngOnInit() {
    /* fetch restaurants when app loads */
    this.api.ListRestaurants().then((event) => {
      this.restaurants = event.items as Restaurant[];
    });
  }

  public onCreate(restaurant: Restaurant) {
    this.api
      .CreateRestaurant(restaurant)
      .then(() => {
        console.log('item created!');
        this.createForm.reset();
      })
      .catch((e) => {
        console.log('error creating restaurant...', e);
      });
  }
}```

**Comment by AnilMaktala** [comment]
Hi @Tkumar02 👋, We are closing this issue as we have not received any response from you. However, if you are still facing the same issue and require our assistance, please don't hesitate to leave a comment and provide us with the information our team had previously asked for. This way, we can reopen the issue and provide you with better assistance.

Thank you!
