### ISSUE TITLE
Documentation not within <article> blocks

### ISSUE THREAD

**Issue by Rafcin** [aws-amplify/docs#5354]
Hi there,

I've been trying to interact with the documentation pages on https://docs.amplify.aws/ using tools like Cheerio and Puppeteer. However, I've noticed that each page needs relevant documentation within `<article>` blocks; otherwise, locating the documentation when interacting with the page programmatically is challenging.

Can the documentation pages be updated to have their relevant documentation within `<article>` blocks so it is easier to locate the information when interacting with the page programmatically?

I'm currently working on indexing AWS and AWS Amplify documentation to set up a ChatGPT QA tool for the Amplify Discord bot to help reduce easy-to-solve questions and improve the user's experience writing code. The regular AWS docs have this issue as well; however, I can find the content by using the ID `id="main-content"`.

**Comment by reesscot** [comment]
Closing this out, as the Amplify docs were updated last year to use more semantic tags such as `main` and `nav`. This  should allow tooling mentioned to more easily identify the content of the pages.
