### ISSUE TITLE
Amplify Getting Started Docs (NextJS/API) has a minor typo

### ISSUE THREAD

**Issue by ejmuentes** [aws-amplify/docs#5357]
**Describe the content issue**:
Minor typo addressed in https://github.com/aws-amplify/docs/pull/5356

**URL page where content issue is**:
https://docs.amplify.aws/start/getting-started/data-model/q/integration/next/

![Screen Shot 2023-04-07 at 1 51 10 PM](https://user-images.githubusercontent.com/42398450/230682329-49bb8ca6-8611-4c19-bcfc-bd5c76ffa1b2.png)

**Comment by timngyn** [comment]
Thanks @ejmuentes for opening the issue and getting the PR up! I'll close this issue since your PR was already merged in.
