### ISSUE TITLE
Now that React.dev recommends not using CRA, the tutorial should be updated.

### ISSUE THREAD

**Issue by Bryson14** [aws-amplify/docs#5359]
**Describe the content issue**:
A clear and concise description of what the content issue is. Is there content missing or is there incorrect content?
On the tutorial, it shows to create a new web app with `create-react-app`.  According to [React Docs](https://react.dev/learn/start-a-new-react-project), they recommend Gatsby, Next JS, or Remix as a direct replacement for SSR frameworks. But also vite is perhaps the most direct replacement for CRA that focuses on SPA. The documentation should reflect the new recommendations as well as design considerations between using Amplify with SSR in mind or just SPA.

**URL page where the content issue is**:
https://docs.amplify.aws/start/getting-started/setup/q/integration/react/#create-a-new-react-app

**Comment by hbuchel** [comment]
Closing this issue as the latest React tutorial uses Vite and no longer uses CRA. https://docs.amplify.aws/gen1/react/start/getting-started/setup/#create-a-new-react-app
