### ISSUE TITLE
[Feedback] deprecate/restructure intent of "Calling DynamoDB from Lambda in Node.js"

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/docs#5392]
**Page**: [`/guides/functions/dynamodb-from-js-lambda/q/platform/[platform]`](https://docs.amplify.aws/guides/functions/dynamodb-from-js-lambda/q/platform/react-native)

**Feedback**:

This page does not describe when you would want to call DynamoDB in the context of an AWS Amplify project, nor does it highlight the caveats of calling DynamoDB directly in the context of a project with a GraphQL API. I think it would be beneficial to deprecate this page in favor of the official AWS documentation, or restructure the intent to be within the context of an Amplify project

**Comment by AnilMaktala** [comment]
This page has been deprecated, so closing this issue.
