### ISSUE TITLE
Getting AppSync API documentation

### ISSUE THREAD

**Issue by leonardocfor** [aws-amplify/docs#5413]
Hi everybody, 

Hope you're doing great. I was wondering if you can advise how to create a documentation for an AppSync API, something like in swagger or redoc in html format. An example would be something like this: 

https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/astm-utm/Protocol/master/utm.yaml&nocors

I've been trying using tools like graphql-to-openapi but I haven't found a way. Can you advise? 

Thank you

**Comment by AnilMaktala** [comment]
Hi @leonardocfor, Thank you for raising this. You can use the CLI command mentioned [here](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/appsync/get-introspection-schema.html) to generate the graphql schema and pass it to [redocly](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/astm-utm/Protocol/master/utm.yaml&nocors). Please let us know if this helps.
