### ISSUE TITLE
[Feedback] export 'default' (imported as 'Amplify') was not found in 'aws-amplify'

### ISSUE THREAD

**Issue by MitchellNeill** [aws-amplify/docs#5423]
**Page**: [`/start/getting-started/setup/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/setup/q/integration/react-native)

**Feedback**:

Hi there, I notice the instructions include this line of code:

import awsconfig from './src/aws-exports'

In order to not throw an error, "export 'default' (imported as 'Amplify') was not found in 'aws-amplify'", I believe this now needs to be:

import { Amplify } from 'aws-amplify'

All the best,
Mitchell

**Comment by tannerabread** [comment]
Hi @MitchellNeill when I go to that page I see `import { Amplify } from 'aws-amplify'` as expected

Were you seeing something different?

**Comment by MitchellNeill** [comment]
It looks like I just had my wires crossed and got two lines mixed up some how. Thanks for checking it out all the same, everything is fine
