### ISSUE TITLE
Error on Getting Started tutorial for Flutter 

### ISSUE THREAD

**Issue by rsb73** [aws-amplify/docs#5462]
**Page**: [`/start/getting-started/integrate/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/integrate/q/integration/flutter)

**Feedback**:

Following the code example you as presented results in this error.
Undefined name 'amplifyconfig'.
Try correcting the name to one that is defined, or defining the name.dart[undefined_identifier](https://dart.dev/diagnostics/undefined_identifier)

**Comment by khatruong2009** [comment]
Hi  @@rsb73, I was unable to reproduce the issue you were having when following the guide. I've run into the "undefined name 'amplifyconfig'." issue before when forgetting to import 'amplifyconfiguration.dart' (listed in the Configure Amplify subheading in the Integrate your app section). Could you provide more details if that doesn't work?

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
