### ISSUE TITLE
Sandbox Environment to Write Stackblitz Demos Against

### ISSUE THREAD

**Issue by oleersoy** [aws-amplify/docs#5474]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to demo things like static Hub methods or the general Amplify Auth API using Stackblitz.

**Describe the solution you'd like**

An public Sandbox API that anyone can code a live public demo against.  Like the Star Wars API:
https://swapi.co

**Describe alternatives you've considered**

ATM it seems this is not even possible.

**Comment by mauerbac** [comment]
Following on this thread. We took a sprint to evaluate Stackblitz for interactive sandbox and ran into concerns around security with AWS accounts. Closing this.
