### ISSUE TITLE
[Feedback] Missing link

### ISSUE THREAD

**Issue by nadetastic** [aws-amplify/docs#5486]
**Page**: [`/cli/reference/files`](https://docs.amplify.aws/cli/reference/files)

**Feedback**:
Link for "[Cognito security best practices for web app](https://forums.aws.amazon.com/message.jspa?messageID=757990#757990)" under **aws-exports.js** section goes to a missing page.

**Comment by josefaidt** [comment]
Marking as a duplicate of https://github.com/aws-amplify/docs/issues/4931 and closing in favor of tracking the existing issue
