### ISSUE TITLE
Nextjs 13.4

### ISSUE THREAD

**Issue by berkaycirak** [aws-amplify/docs#5497]
Hi, I will make a project by using Next 13.4 and I see that there is no support on amplify deploy. Will it be come soon?

**Comment by mauerbac** [comment]
Hello - it looks like this version is supported: https://github.com/aws-amplify/amplify-hosting/issues/3466#issuecomment-1547838606

If you need additonal help please open an Issue in the Amplify Hosting Repo. Thank you!
