### ISSUE TITLE
GraphQL API tutorial missing auth rules

### ISSUE THREAD

**Issue by chrisbonifacio** [aws-amplify/docs#5499]
**Describe the content issue**:
A clear and concise description of what the content issue is. Is there content missing or is there incorrect content?

https://docs.amplify.aws/start/getting-started/data-model/q/integration/react/#create-a-graphql-api-and-database

This page includes a simple schema that omits authorization rules. This can confuse developers on whether or not at least one auth rule is required. They might replace the `schema.graphql` file with this schema, removing the global auth rule, and will result in all requests being unauthorized.

It should also be clearer about how configured authorization modes work with the client side calls (specifying authMode)

**URL page where content issue is**:
https://docs.amplify.aws/start/getting-started/data-model/q/integration/react/#create-a-graphql-api-and-database

**Comment by AnilMaktala** [comment]
This issue had been addressed, hence closing this issue.
