### ISSUE TITLE
Amplify v2 codegen nodownload

### ISSUE THREAD

**Issue by gevartosky** [aws-amplify/docs#5507]
I'm migrating to Amplify v2 graphql API and I need to generate models from a local schema file but I can't find what should be the equivalent command for the old `amplify codegen --nodownload` that generates AppSync models.

I found `amplify codegen models` but it gives me the error `No Amplify backend project files detected within this folder`

**Comment by AnilMaktala** [comment]
Hey @gevartosky, Thank you for raising this. Please retry using the latest version of the CLI and make sure you run the command (`amplify codegen models`) at the app root folder.
