### ISSUE TITLE
[Feedback]stop assuming so much like just saying "index.js" file,. ok which one??? and do you mean into the actual file or using terminal?

### ISSUE THREAD

**Issue by cacherich** [aws-amplify/docs#5517]
**Page**: [`/console/uibuilder/figmatocode`](https://docs.amplify.aws/console/uibuilder/figmatocode)

**Feedback**:

um yea first of all this whole doing support on github is super annoying, i just was blown away by how disorganized this process is for such a huge organization as AWS. when you go to the Support from in Studio it brings you to this github page full of idiotic questions that have nothing to do with me why should i have to sit there and try to sift through all that crap just to ask a specific question that should covered in the first place in your documentation and or tutorials, further you leave things out of tutorial that are vital yet you have them on another page in the docs and even there you leave out critical information. in my case as i am learning to do this for the first time hands on here i don't know which index.js file you are referring to b/c i found like at least 3 of them and when you say "Your APP" where the f is my app? i don't see it in my finder? and in the tutorial you don't even mention any of this i had to find it on another page which still was very nebulous in terms of what and where my "app" root directory should be located i just was at least common sense enough to figure out to look in finder and not paste your code into terminal or am i supposed to? i swear this stuff is making me pull my hair out when it's just oversights you shouldn't assume that when 3 or more index.js files are in the awsamplify node module that someone would know which one to use and i am sure i am not using the right one b/c it's filled with code and none of which contains "App" to wrap the last bit from tutorial around this is insanely frustrating and now i have stop and wait / check here on stupid f'ing git hub unreal i pay $100 a month for ur support and i'm on github terrible

**Comment by josefaidt** [comment]
Hey @cacherich :wave: thanks for raising this and sorry to hear you had a rough experience! We're constantly looking to improve our docs to better serve developers, and can empathize with how highlighting `index.js` can be a bit confusing. We have a pull request open to help alleviate this! But to provide some clarity here this is referring to your frontend application's app file/entrypoint; the file used at the top-level of your app. When using create-react-app this will be `src/index.js`, `pages/_app.js` in Next.js, or `main.jsx` with Vite.

> i had to find it on another page which still was very nebulous in terms of what and where my "app" root directory should be located

May I ask which page helped clear this up?

We also appreciate the feedback for the "Support" button in Studio! If you are currently paying for a support plan you can file a ticket through the AWS Support portal here https://console.aws.amazon.com/support/home

**Comment by cacherich** [comment]
Hey there @josefaidt i apologize if my post seemed a bit harsh i just am super frustrated b/c i funded a project to the tune of let's just say over half a mil in my own cash and the CTO bounced a month before we were going to do our beta... so i have had to scramble to learn everything from npm in terminal to aws ec2 to vue.js on the frontend and so on... it's never been my line of work though i know enough about api's and tech to make a product or business out of it.... so again i don't mean to be rude i am just a bit OTT right now when i encounter things like as an admittedly noob but someone who learns fast and is hungry to get S done ya feel me? and to be clear, nothing has cleared anything up for me b/c i was looking in my finder for the /frontend directory or folder and never found it... so my real confusion is that it seems the tutorial i was following had a prerequisite that wasn't stated in that you had to have a create-react-app already on your local? but yet amplify let me create an App in the console and then proceed with the tutorial so i am now super confused but i really really appreciate your patience and kind response

**Comment by josefaidt** [comment]
Hey @cacherich no worries!! You've highlighted a bit of a gap we have in the docs where the guide was assuming an existing create-react-app, but we're happy to get that updated! Creating an Amplify project will allow you to define backend resources, however creating and maintaining the frontend is separate from the `init` process. Additionally, you can connect multiple frontend applications to the same backend project!
