### ISSUE TITLE
[Feedback] Following nuxt setup documentation leads to build error on amplify 

### ISSUE THREAD

**Issue by cgan0** [aws-amplify/docs#5518]
**Page**: [`/guides/hosting/nuxt/q/platform/[platform]`](https://docs.amplify.aws/guides/hosting/nuxt/q/platform/js)

Instructions in doc page does not actually work

When trying to deploy a nuxt3 app get the following error:

![Screenshot 2023-05-31 at 5 00 19 pm](https://github.com/aws-amplify/docs/assets/70501297/a6fda994-9046-41c1-8602-3abe6a5f8a0f)

Using the same build settings as the documentation:

![Screenshot 2023-05-31 at 5 01 39 pm](https://github.com/aws-amplify/docs/assets/70501297/4550fda8-eddf-4bd8-8565-7ef291c729f7)

Is there settings in nuxt.config.ts that need to be added to get this to deploy? Can these be added to the documentation page?

**Comment by hbuchel** [comment]
Closing as this was previously fixed in this [PR](https://github.com/aws-amplify/docs/pull/5523) and the site has been updated for Gen2.
