### ISSUE TITLE
[Feedback]Where to import InAppMessageInteractionEvent from

### ISSUE THREAD

**Issue by joeykay9** [aws-amplify/docs#5529]
**Page**: [`/lib/in-app-messaging/respond-interaction-events/q/platform/[platform]`](https://docs.amplify.aws/lib/in-app-messaging/respond-interaction-events/q/platform/js)

**Feedback**:

> If you are using TypeScript for your development, you can import and use the InAppMessageInteractionEvent enum...

Doesn't state where to import InAppMessageInteractionEvent enum from.

**Comment by cshfang** [comment]
Hi @joeykay9. Thanks for bringing this point of confusion to our attention. We will try to update our docs as soon as we're able in an effort to add some clarity here.

In the meantime, you should be able to import this from the scoped notifications package as follows:

```ts
import { InAppMessageInteractionEvent } from '@aws-amplify/notifications';
```

**Comment by abdallahshaban557** [comment]
This has been updated in our docs.
