### ISSUE TITLE
PubSub Example "How to reconfigure PubSub providers during runtime" runtime compile error

### ISSUE THREAD

**Issue by cigo511** [aws-amplify/docs#5535]
**Describe the content issue**:
I am trying to follow documentation that describes "[How to reconfigure PubSub providers during runtime](https://docs.amplify.aws/lib/pubsub/getting-started/q/platform/js/#how-to-reconfigure-pubsub-providers-during-runtime)".

I am running a React app (Javascript), and creating a component to manage a PubSub connection to display information for my Things.  My application has different context that requires that I am able to reconfigure the PubSub provider.

I have observed compile errors when implementing code shown in the example.
Specifically when using the line:  const pubsub = new PubSub({});

### Error Observed
When I follow the example I get an compile error when using the line:  const pubsub = new PubSub({});

aws_amplify__WEBPACK_IMPORTED_MODULE_3__.PubSub is not a constructor
TypeError: aws_amplify__WEBPACK_IMPORTED_MODULE_3__.PubSub is not a constructor
    at ./src/services/mqtt_device_test_documentation.js (http://localhost:3000/static/js/bundle.js:47278:16)
    at options.factory (http://localhost:3000/static/js/bundle.js:324887:31)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:324303:33)
    at fn (http://localhost:3000/static/js/bundle.js:324544:21)
    at ./src/MainPage/MainPage.jsx (http://localhost:3000/static/js/bundle.js:21984:102)
    at options.factory (http://localhost:3000/static/js/bundle.js:324887:31)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:324303:33)
    at fn (http://localhost:3000/static/js/bundle.js:324544:21)
    at ./src/HomePage.jsx (http://localhost:3000/static/js/bundle.js:12027:81)
    at options.factory (http://localhost:3000/static/js/bundle.js:324887:31)

### Code Example
 Note this example is attempting to use MqttOverWSProvider with a custom authorizer.  I assumed that this provider could also be reconfigured.
 Note I have been able to use MqttOverWSProvider to connect to a IoT Core endpoint with a customer authorizer successfully when it is statically configured in the global scope.
```
import React, { useState } from 'react';
import {Amplify, PubSub, Auth } from 'aws-amplify';
import { MqttOverWSProvider } from "@aws-amplify/pubsub/lib/Providers";
import { awsIotConfiguration } from '../aws-iot-configuration';

const mqtt_host = awsIotConfiguration.host;

var subscriptions = [];

const pubsub = new PubSub({});


const MqttDeviceTest1 = ({tokenId, deviceList=[], updateInfo=()=>{}, cleanupInfo=()=>{}}) => {
    const status_subscription = "deploy/prd/{group}/{thing}/status";
    
    React.useEffect(() => {
      if (tokenId){
        console.log('Connecting');
        Auth.currentAuthenticatedUser().then((user) => {
          const ampAuthToken = user.signInUserSession.idToken.jwtToken;
          pubsub.addPluggable(
            new MqttOverWSProvider({
              aws_pubsub_endpoint: `wss://${mqtt_host}/mqtt?token2={token2}&token={allow}`.replace("{allow}", ampAuthToken).replace("{token2}", tokenId), 
          })
          );
          subscribe();
        })
      }
      
      return () => {
        console.log("Leaving MqttDevice");
        unSubscribe();
        cleanupInfo();
        pubsub.removePluggable('MqttOverWSProvider');
      };
    }, [deviceList]);

    function subscribe() {
        console.log("Create Subscriptions");
        deviceList.forEach((thing, i) => {
          //Status Subscription
          //subscription_string = status_subscription.replace("{thing}",thing);
          //console.log(subscription_string);
          let status_sub = PubSub.subscribe(status_subscription.replace("{thing}",thing).replace(
            "{group}",tokenId
            )).subscribe({
                next: data => {
                    data.value.client_received_at = new Date()
                    //console.log(data.value);
                    updateInfo(data.value);
                },
                error: error => console.error(error),
                close: () => console.log('Done'),
          })
          subscriptions.push(status_sub);    
        console.log(subscriptions.length);    
      })
    }

    function unSubscribe() {
        console.log("unsubscribing");
        while (subscriptions.length) {
          let sub = subscriptions.pop();
          if (sub !== null) {
            sub.unsubscribe();
          }
        }
    }
    return (
        <>
        </>
    );
};

export default MqttDeviceTest1;
```

**URL page where content issue is**:
https://docs.amplify.aws/lib/pubsub/getting-started/q/platform/js/#third-party-mqtt-providers
"[How to reconfigure PubSub providers during runtime](https://docs.amplify.aws/lib/pubsub/getting-started/q/platform/js/#how-to-reconfigure-pubsub-providers-during-runtime)".

**Comment by cigo511** [comment]
Received feedback to use PubSub directly rather than creating a 'const pubsub'.  Code snippet below reflects the recommended change that was tested.

**Review**
- No compile error with this method.  
- I observe websocket being open when page loads (_useEffect_ triggers)
- I observe the websocket seems to close (Chrome shows a duration on the websocket, rather than 'Caution!: This request has not finished' ).
-  When the props to the component change (i.e. tokenId), the websocket uses the latest tokenId as desired.

**Observation, Open Items, Improvement Opportunity**
-  The documentation could be improved by providing an example in context.  For example, showing it used in a _useEffect_ or recommended trigger method to .  I would describe the current example in the documentation as describing "what" (i.e. the methods _PubSub.addPluggable_, _PubSub.removePluggable_) to use, but not "how" to use it (i.e. in context of a React App, how to use it with a custom authorizer, or how to use it with a changing end point).
- When running a React application in debug, _useEffect_ is ran twice.  This is causing two websockets to be opened on page loads.  It would be helpful to provide an example or method to resolve this behavior to protect applications from generating too many websockets from user behavior (such as opening multiple tabs, etc.) or potentially creating complex issues by causing the application to see duplicate packets.  For example, an _AbortController()_ can be used to manage a fetch called by _useEffect_.
Alternately, provide the preferred method to make the connection if the _useEffect_ hook is not appropriate.

Apologies for the code snippet formatting issue below.

-----------------------------------------
import React, { useState } from 'react';
import {Amplify, PubSub, Auth } from 'aws-amplify';
import { MqttOverWSProvider } from "@aws-amplify/pubsub/lib/Providers";
import { awsIotConfiguration } from '../aws-iot-configuration';

const mqtt_host = awsIotConfiguration.host;

var subscriptions = [];

//NOTE:  Global Variable Removed

const MqttDeviceTest1 = ({tokenId, deviceList=[], updateInfo=()=>{}, cleanupInfo=()=>{}}) => {
    const status_subscription = "deploy/prd/{group}/{thing}/status";
    
    React.useEffect(() => {
      if (tokenId){
        console.log('Connecting');
        Auth.currentAuthenticatedUser().then((user) => {
          const ampAuthToken = user.signInUserSession.idToken.jwtToken;
          PubSub.addPluggable(
            new MqttOverWSProvider({
              aws_pubsub_endpoint: `wss://${mqtt_host}/mqtt?token2={token2}&token={allow}`.replace("{allow}", ampAuthToken).replace("{token2}", tokenId), 
          })
          );
          subscribe();
        })
      }
      
      return () => {
        console.log("Leaving MqttDevice");
        unSubscribe();
        cleanupInfo();
        PubSub.removePluggable('MqttOverWSProvider');
      };
    }, [deviceList]);

    function subscribe() {
        console.log("Create Subscriptions");
        deviceList.forEach((thing, i) => {
          //Status Subscription
          //subscription_string = status_subscription.replace("{thing}",thing);
          //console.log(subscription_string);
          let status_sub = PubSub.subscribe(status_subscription.replace("{thing}",thing).replace(
            "{group}",tokenId
            )).subscribe({
                next: data => {
                    data.value.client_received_at = new Date()
                    //console.log(data.value);
                    updateInfo(data.value);
                },
                error: error => console.error(error),
                close: () => console.log('Done'),
          })
          subscriptions.push(status_sub);    
        console.log(subscriptions.length);    
      })
    }

    function unSubscribe() {
        console.log("unsubscribing");
        while (subscriptions.length) {
          let sub = subscriptions.pop();
          if (sub !== null) {
            sub.unsubscribe();
          }
        }
    }
    return (
        <>
        </>
    );
};

export default MqttDeviceTest1;

**Comment by cwomack** [comment]
@cigo511, closing this issue out as the update to the code examples within the documentation should eliminate the compilation errors.  

As for the double `useEffect()` and double sockets being opened, that's to be expected based on the [default behavior](https://react.dev/blog/2022/03/08/react-18-upgrade-guide#updates-to-strict-mode:~:text=No%20suppression%20of%20console%20logs%3A%20When%20you%20use%20Strict%20Mode%2C%20React%20renders%20each%20component%20twice%20to%20help%20you%20find%20unexpected%20side%20effects.) in Dev Mode (React Strict Mode) as of React v18.  There's a few comments within [this issue](https://github.com/facebook/react/issues/24502) on the React repo that explain it and work arounds, along with a section of their docs that talks about how to handle the [effect firing twice](https://react.dev/learn/synchronizing-with-effects#how-to-handle-the-effect-firing-twice-in-development). 

Hope this addresses your questions and we appreciate you opening up this issue to help us improve out docs!
