### ISSUE TITLE
Right nav does not scroll far enough to display content

### ISSUE THREAD

**Issue by david-mcafee** [aws-amplify/docs#5550]
**Describe the bug**
Right navigation does not scroll far enough to display content, and hides available menu items.

**To Reproduce**
1. Go to https://docs.amplify.aws/lib/graphqlapi/working-with-files/q/platform/js/
2. On the right nav, scroll to the bottom
3. "Complete Examples" should be visible, but is hidden

**Expected behavior**
The content at the bottom of the nav should be visible

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 114.0.5735.106 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by reesscot** [comment]
Hi @david-mcafee,
This issue has been fixed in the new version of the Amplify Docs site. You are now able to scroll both Side bar nav and Table of Contents navs all the way to the bottom.
