### ISSUE TITLE
Better description on authmode

### ISSUE THREAD

**Issue by ErhardScampi** [aws-amplify/docs#5557]
There are no examples on how to gain public access on Appsync. No IAM and no API_Key examples.
A lot of text with no running and working examples on public access. I would wish to get some for transformer V2 amplify and javascript/Typescript

**Comment by AnilMaktala** [comment]
Hey @ErhardScampi, This has been addressed in the new revamp of the docsite. Please refer this section of the docs https://docs.amplify.aws/react/build-a-backend/graphqlapi/set-up-graphql-api/ and let us know.
