### ISSUE TITLE
Definition of the awsconfiguration.json

### ISSUE THREAD

**Issue by w0mba7** [aws-amplify/docs#556]
The documentation states that to use existing AWS services to manually configure the awsconfiguration.json file and gives an example of the file.  I am currently integrating our mobile apps with existing aws services consumed by other applications so I need to create the file by hand.  The problem is beyond the one example, there is no other documentation on how to structure that file or what are all the available options. 

 I noticed on the JS section that you could add calls to change how graphql handled auth and was wonder if those kind of options existing for the iOS / Android configuration as well or if the ones listed in the example are the only ones available.

**Comment by minbi** [comment]
Hi @w0mba7 ,

My recommendation for Android would be to use the code configuration route.

iOS does support awsconfiguration.json through the pattern alluded to in the docs

If using `AWSSQS` client, the key will be `SQS`

We will try to clarify this in the documentation. If you find a key through the above rule that doesn't work. You may cut us an issue and we'll investigate.

**Comment by w0mba7** [comment]
Okay thanks, will go with the code configuration in the future.
