### ISSUE TITLE
Push notifications with SNS

### ISSUE THREAD

**Issue by alexsyd** [aws-amplify/docs#558]
Current documentation is describing how to use Pinpoint for push notifications to many subscribers but it doesn't provide information on how to send a push notification to specific user.

I need a tutorial for push notifications with SNS, not Pinpoint.

**Comment by jordanranz** [comment]
Hey @alexsyd,

Which platform/framework are you using?

**Comment by alexsyd** [comment]
For our app we use React Native. 
And we've found some information how to send a notification to one user with Pinpoint. Still the documentation could be better. And SNS documentation says it can send push notifications but we couldn't find documentation how to do it...
