### ISSUE TITLE
[Feedback]CODE FAILURE

### ISSUE THREAD

**Issue by BMscis** [aws-amplify/docs#5588]
**Page**: [`/guides/functions/appsync-operations-to-lambda-layer/q/platform/[platform]`](https://docs.amplify.aws/guides/functions/appsync-operations-to-lambda-layer/q/platform/js)

**Feedback**:

This code example fails to deploy, plus there is very liitle detail on how to debug if it fails.

**Comment by josefaidt** [comment]
Hey @BMscis :wave: just wanted to check in here, are you still experiencing this?

**Comment by BMscis** [comment]
Sorry I found a work around.
