### ISSUE TITLE
[Feedback] Wrong information

### ISSUE THREAD

**Issue by LeeChangki** [aws-amplify/docs#5604]
**Page**: [`/cli-legacy/graphql-transformer/relational`](https://docs.amplify.aws/cli-legacy/graphql-transformer/relational)

**Feedback**:

This is working for Aurora MySQL Serverless v1(2.07.1) only. The UI should be changed. It supports every region, I think.

**Comment by cwomack** [comment]
@LeeChangki, we have a PR out to address this and update the documentation.  Thank you for opening this issue!
