### ISSUE TITLE
Auth.getPreferredMFA() does not work as documented

### ISSUE THREAD

**Issue by brianreinhold** [aws-amplify/docs#5635]
On Cognito I have a user pool where I can set MFA required TOTP or No MFA.

In both cases, Auth.getPreferredMFA() (after Auth.signIn() returns successfully) returns "SOFTWARE_TOKEN_MFA".

The expected result is "TOTP" when I have MFA required with Authentication app. When no MFA is set, the expected result is "NOMFA". What good is this method if it always returns the same result? It provides no useful information.

Why do I need this?

I want to present to the user the option to 'forget device' when MFA TOTP is required and the user has selected 'remember device' during the MFA setup or during an MFA token entry.

I do not want to present the option if the device has not been remembered OR there is no MFA required.

**Comment by cwomack** [comment]
@brianreinhold, we appreciate you creating this issue to help improve our docs.  I've created a PR to add a callout for the recommended best practice of calling `Auth.setPreferredMFA()` to ensure a user has set their MFA method ***before*** retrieving MFA settings with `Auth.getPreferredMFA()`. 

This issue should get closed upon #5733 getting merged, but let me know if you have any further feedback  on this.  Thanks!
