### ISSUE TITLE
[missing-page] contributing/getting-started (404)

### ISSUE THREAD

**Issue by PatrickFfm93** [aws-amplify/docs#5638]
**Page**: [`https://docs.amplify.aws/contribute/getting-started/`](https://docs.amplify.aws/contribute/getting-started/)

**Feedback**: 
Hey Team, this page at the moment only shows 404 on brave browser (
Brave 1.52.130, Chromium 114.0.5735.198) on Android 12 Samsung S10e.

**Comment by timngyn** [comment]
Thanks for bringing this to our attention @PatrickFfm93, @jacoblogan just pushed up the fix for it. Does the link work on your end now? (it works for me now, but just wanted to check with you!)

**Comment by PatrickFfm93** [comment]
@timngyn @jacoblogan works fine on my side too. Thanks for the quick fix!
