### ISSUE TITLE
trying to use amplify and my AWS access credentials cannot be found. Even though I have them. Why can't I just type them in? Where do they need to be so that amplify can find them?  

### ISSUE THREAD

**Issue by dstrehlow** [aws-amplify/docs#565]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jordanranz** [comment]
Please explain how you are using Amplify. If this is related to the Amplify CLI have you done `amplify configure`? 

Also if you could fill out the questions above it would help us debug and reproduce the issue.

**Comment by kaustavghosh06** [comment]
@dstrehlow Please take a look at https://aws-amplify.github.io/docs/cli/init#amplify-configure for more info around this and re-open or comment on this thread if you're still stuck on this.

**Comment by iskandar47** [comment]
Now i'm realizing that Amplify is just a disaster .
