### ISSUE TITLE
[Feedback] [AmplifyConfiguration] passwordProtectionSettings is missing

### ISSUE THREAD

**Issue by sumuhans** [aws-amplify/docs#5656]
**Page**: [`/lib/auth/getting-started/q/platform/[platform]`](https://docs.amplify.aws/lib/auth/getting-started/q/platform/ios)

**Feedback**:

I think the sample amplifyconfiguration.json file is missing the following bit under Auth -> Default

            "passwordProtectionSettings": {
                "passwordPolicyMinLength": 8,
                "passwordPolicyCharacters": []
            }

When I followed the instructions and tried to use the SwiftUI Authenticator, I kept getting an error on the simulator saying "Something went wrong" along with a message saying the configuration is not correct. On the Xcode console it said "[AmplifyConfiguration] passwordProtectionSettings is missing". After looking at another configuration file posted in a [comment in the repo](https://github.com/aws-amplify/amplify-swift/issues/2881#issuecomment-1562402120), I realised what is missing and added the above bit and now it is working. So I think the sample   amplifyconfiguration.json should be updated to include the above. I also wonder if there is anything else that might be missing?

**Comment by phantumcode** [comment]
Documentation updated
