### ISSUE TITLE
add sample filenames to each code example to give context

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/docs#5657]
**Is your feature request related to a problem? Please describe.**

[This guide](https://docs.amplify.aws/guides/api-graphql/query-with-sorting/q/platform/js/#implementation) can be confusing when it walks us through a GraphQL schema example and a client-code example, where providing sample filenames such as `schema.graphql` can provide additional context without the need for describing _where_ we need to write this sample.

**Describe the solution you'd like**

![image](https://github.com/aws-amplify/docs/assets/5033303/cff2b0d6-a4be-4dcc-b058-d2464889f118)

https://www.christopherbiscardi.com/the-quick-guide-to-serverless
![image](https://github.com/aws-amplify/docs/assets/5033303/89233551-86e0-4d49-83b2-9063c6ce1d6e)

**Describe alternatives you've considered**

**Additional context**

https://github.com/aws-amplify/amplify-category-api/issues/1675

**Comment by reesscot** [comment]
Copied over the feature request description and merged https://github.com/aws-amplify/docs/issues/5942
