### ISSUE TITLE
BelongsTo relationship docs omit important step

### ISSUE THREAD

**Issue by naughton** [aws-amplify/docs#5676]
[@belongsTo](https://docs.amplify.aws/cli/graphql/data-modeling/#belongs-to-relationship) docs say that you can create a bi-directional relationship by setting the parent reference field in the creation of the child.

This only does half of the relationship.  It connects the child to the parent, but not the reverse.

you need to include the automatically generated field (in this example `postCommentsID`) and duplicate the parent id.

```
// create comment
const commentParams = {
    input: { content: 'Hi!', postID: post.id, postCommentsID: post.id },
};
```

**URL page where content issue is**: https://docs.amplify.aws/cli/graphql/data-modeling/#belongs-to-relationship

**Comment by naughton** [comment]
This could be a docs content issue, or it could be that the generated resolver code should do this automatically, which seems preferable.

**Comment by AnilMaktala** [comment]
This issue has been addressed here: https://docs.amplify.aws/javascript/build-a-backend/graphqlapi/data-modeling/#belongs-to-relationship
