### ISSUE TITLE
list items

### ISSUE THREAD

**Issue by boraoren** [aws-amplify/docs#570]
**Describe the bug**

1. go to https://aws-amplify.github.io/docs/js/react#add-rest-api-calls-to-a-database
1. find code
```
list = async () => {
    console.log('calling api');
    const response = await API.get('myapi', '/items/1');
    alert(JSON.stringify(response, null, 2));
  }
```
This is not list, this is list of 1. When you try to get /items it returns 404. What is list items code sample that works?

**Screenshots**
![image](https://user-images.githubusercontent.com/45959515/54894519-22e44600-4f0f-11e9-9a5d-6431ee76bce1.png)

Thank you.

**Comment by mlabieniec** [comment]
@boraoren did you run `amplify add api` and create the resources matching the paths in the snippets?
