### ISSUE TITLE
Images related to amplify-datastore do not have informative alt text

### ISSUE THREAD

**Issue by timngyn** [aws-amplify/docs#5716]
**Describe the content issue**:
Images listed below don't have descriptive/informative alt text. For markdown the alt text is located between the square brackets, `![alt text](...)`.

If the image is for decoration then having an empty string, `![](...)`, would be okay, provided that they are non-essential to understanding the content and purpose of the page.

If the image is being used to display info, then we need to have more descriptive text for screen readers. For example, the file `src/fragments/lib/datastore/native_common/how-it-works.mdx` has an image on line 16 that has `Image` as its alt text, which isn't descriptive or helpful for people who use screen readers. Link to page where this image is shown: https://docs.amplify.aws/lib/datastore/how-it-works/q/platform/js/#model-data-locally. Since this is a diagram, we will want to make the alt text more descriptive so people using screen readers can also understand the info from the image as well. 

I was thinking that this issue could be used to track which alt text needs to be updated or can be ignored. Please let me know if you have any questions!

Some resources to help with this:
- https://webaim.org/techniques/alttext/
- https://supercooldesign.co.uk/blog/how-to-write-good-alt-text

```
src/fragments/lib/datastore/native_common/how-it-works.mdx:
  16: ![Image](/images/storage.png)
  28: ![Image](/images/sync.png)

src/fragments/lib-v1/datastore/native_common/how-it-works.mdx:
  16: ![Image](/images/storage.png)
  28: ![Image](/images/sync.png)
```

**Comment by AnilMaktala** [comment]
This had been addressed in the latest doc's release. https://docs.amplify.aws/javascript/build-a-backend/more-features/datastore/how-it-works/#model-data-locally
