### ISSUE TITLE
Custom Authentication in Amplify does not trigger authStateChange$

### ISSUE THREAD

**Issue by wollerman** [aws-amplify/docs#573]
**Describe the bug**
When using [the example to setup custom auth](https://aws-amplify.github.io/docs/js/authentication#custom-authentication-in-amplify), the `amplifyService.authStateChange$` observable never emits a value.

**To Reproduce**
1. Setup the custom auth login with cognito
2. Use the snippet from the example of custom auth
e.g.
```
Auth.signIn(username, password)
    .then(user => {
        if (user.challengeName === 'CUSTOM_CHALLENGE') {
            // to send the answer of the custom challenge
            Auth.sendCustomChallengeAnswer(user, challengeResponse)
                .then(user => console.log(user))
                .catch(err => console.log(err));
        } else {
            console.log(user);
        }
    })
    .catch(err => console.log(err));
```
3. The `amplifyService.authStateChange$` doesn't emit the sign in.

**Expected behavior**
The `amplifyService.authStateChange$` should emit and describe the authorized event.

**Additional context**
This seems to be related to the auth decorator https://github.com/aws-amplify/amplify-js/blob/0feb0e6521d56b6dd64fd5f708eb791e546f3c02/packages/aws-amplify-angular/src/providers/auth.decorator.ts

Where sign in does not consider a `CUSTOM_CHALLENGE`.

My workaround has been to make the inner call and use the `amplifyService.setAuthState()`.

e.g.
```
Auth.sendCustomChallengeAnswer(user, challengeResponse)
                            .then(userResponse => {
                                this.amplifyService.setAuthState({state: 'signedIn', user: user});
                            })
                            .catch(err => {
                                console.log(err);
                            });
```

This also seems related to https://github.com/aws-amplify/amplify-js/issues/747

**Comment by powerful23** [comment]
Need more doc on how to use the `Authenticator` when the sign in flow is `CUSTOM_AUTH`
