### ISSUE TITLE
on 4-initialize-amplify-in-the-application

### ISSUE THREAD

**Issue by NEEtojin** [aws-amplify/docs#5736]
Hi. I am beginner to Android and could not follow instructions in 
https://docs.amplify.aws/lib/project-setup/create-application/q/platform/android/#4-initialize-amplify-in-the-application
. The code and the instruction given are not clear enough, and did not work for me.

Please clarify the followings if possible.
First. what is new here, File or Class?
Second. what should code wrapping the 'override fun onCreate()' be?

Thank you.

**Comment by mattcreaser** [comment]
Hi @NEEtojin.

In this step you create a [custom Application class](https://medium.com/droid-log/android-application-class-a8a1d64c82d1) that extends the Android SDK's base [Application class](https://developer.android.com/reference/android/app/Application). Your code should look something like this:

```kotlin
class MyAmplifyApp : Application() {
  override fun onCreate() {
      super.onCreate()
  
      try {
          Amplify.configure(applicationContext)
          Log.i("MyAmplifyApp", "Initialized Amplify")
      } catch (error: AmplifyException) {
          Log.e("MyAmplifyApp", "Could not initialize Amplify", error)
      }
  }
}
```

I would recommend you spend some time learning the basics of Android development before trying to dive too deeply into Amplify. The [Android Codelabs](https://developer.android.com/get-started/codelabs) are a great place to get started. Good luck!
