### ISSUE TITLE
[Feedback]Platform switcher is repeating platform names

### ISSUE THREAD

**Issue by hibler13** [aws-amplify/docs#5755]
**Page**: [[`/ChooseFilterPage`](https://docs.amplify.aws/start/getting-started/hosting)](https://docs.amplify.aws/start/getting-started/hosting/q/integration/android/)

**Feedback**: This bug appears throughout the Getting Started guides when a section doesn't apply to a specific platform, e.g., "Deploy and host app" for Flutter.

![Screenshot 2023-08-11 at 1 58 48 PM](https://github.com/aws-amplify/docs/assets/84857865/3b8e7952-b8b5-4d4b-872d-2e73bb7bbd40)

**Comment by jacoblogan** [comment]
Thank you, this issue has been addressed
