### ISSUE TITLE
[Feedback]Section in React Native getting started tutorial not appearing in left nav

### ISSUE THREAD

**Issue by hibler13** [aws-amplify/docs#5756]
**Page**: [`/start/getting-started/integrate/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/integrate/q/integration/react-native)

**Feedback**: This page appears on the site as part of the React Native getting started tutorial but is not listed in the tutorial TOC in the left navigation menu.

**Comment by reesscot** [comment]
Closing this out as it appears to be fixed in the new version of the docs site.
