### ISSUE TITLE
[Feedback]Page in React Native tutorial is not appearing in left nav

### ISSUE THREAD

**Issue by hibler13** [aws-amplify/docs#5758]
**Page**: [`/start/getting-started/add-api/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/add-api/q/integration/react-native)

**Feedback**: This page appears on the site but is not listed in the left navigation menu for the React Native getting started tutorial.

**Comment by jacoblogan** [comment]
This page has been removed as it should not have existed for react native
