### ISSUE TITLE
Local development shows Unhandled Runtime Error

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/docs#5763]
**Describe the bug**
Local development is showing up an error on the root page. I think this is a not a blocker as I am able to continue to navigate to another page successfully.

**To Reproduce**

1. I pulled the latest `main` code
2.  `yarn && yarn dev`
3. Launched `http://localhost:3000/` on Chrome

**Expected behavior**
No errors

**Screenshots**
<img width="896" alt="image" src="https://github.com/aws-amplify/docs/assets/1365977/027ee9a7-4f25-4f95-a343-2a7debfcb2b8">

<img width="896" alt="image" src="https://github.com/aws-amplify/docs/assets/1365977/f7dfd441-2287-4d3f-b07f-168cdc342139">

<img width="896" alt="image" src="https://github.com/aws-amplify/docs/assets/1365977/b0fda07d-c97e-42fa-9dee-38092cb0caba">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22] 115.0.5790.170

**Additional context**

**Comment by reesscot** [comment]
Closing this out, as this has been fixed in the new version of Amplify Docs.
