### ISSUE TITLE
search bar in mobile devices has unexpected behavior

### ISSUE THREAD

**Issue by ykethan** [aws-amplify/docs#5776]
**Describe the bug**

in the search bar, typing in a character then another character will erase the first character. but if you type in the same one twice it works fine

**To Reproduce**
1. Go to search bar at the top in the edge browser
2. try to type in a word say model
3. observe the first character disappears

**Expected behavior**

take in correct input

**Screenshots**

**Desktop (please complete the following information):**

https://github.com/aws-amplify/docs/assets/87995712/1510bba7-f099-4884-b6d6-03d4e50cdaa8

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] samsung s21
 - OS: [e.g. iOS8.1] android
 - Browser [e.g. stock browser, safari] edge

**Additional context**

**Comment by hbuchel** [comment]
This is fixed with the update to using the Algolia UI components for search we released with the updated docs site in Nov. 2023
