### ISSUE TITLE
Typo in Amplify PubSub documentation

### ISSUE THREAD

**Issue by jamesingham** [aws-amplify/docs#578]
**Describe the bug**
There is a typo in the sample code on https://aws-amplify.github.io/docs/ios/pubsub#aws-iot as of 2019-03-28.

Under "Installation and Configuration" on the "AWS IoT" section, the following code sample has the keys typed incorrectly:

```
AWSIoTDataManager.register(with: iotDataConfiguration!, forKey: ASWIoTDataManager)
AWSIoTDataManager iotDataManager = AWSIoTDataManager(forKey: ASWIoTDataManager)
```

The key used should be `AWSIoTDataManager`.

**Comment by jamesingham** [comment]
I also noticed that the last line of the sample code is written in Objective-C but the rest of it is in Swift.

**Comment by muellerfr** [comment]
@jamesingham - Thank you for the PR!
