### ISSUE TITLE
Configuration is invalid - temporary credentials

### ISSUE THREAD

**Issue by funes79** [aws-amplify/docs#5789]
**Describe the content issue**:

The documentation describes how to initialize or pull an existing project. But it fails with invalid configuration when only the credentials are stored in env vars as temporary credentials coming from https://github.com/aws-actions/configure-aws-credentials

Also the cli does not report anything specific what is wrong with the config.
Similar issue reported here: https://github.com/aws-amplify/amplify-cli/issues/11777

Amplify version 12.3.0

https://docs.amplify.aws/cli/usage/headless/#sample-script

```
#!/bin/bash
set -e
IFS='|'

REACTCONFIG="{\
\"SourceDir\":\"src\",\
\"DistributionDir\":\"build\",\
\"BuildCommand\":\"npm run-script build\",\
\"StartCommand\":\"npm run-script start\"\
}"
AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":false,\
\"profileName\":\"default\",\
\"accessKeyId\":\"headlessaccesskeyid\",\
\"secretAccessKey\":\"headlesssecrectaccesskey\",\
\"region\":\"us-east-1\"\
}"
AMPLIFY="{\
\"projectName\":\"headlessProjectName\",\
\"envName\":\"myenvname\",\
\"defaultEditor\":\"code\"\
}"
FRONTEND="{\
\"frontend\":\"javascript\",\
\"framework\":\"react\",\
\"config\":$REACTCONFIG\
}"
PROVIDERS="{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}"

amplify init \
--amplify $AMPLIFY \
--frontend $FRONTEND \
--providers $PROVIDERS \
--yes
```

**URL page where content issue is**:

**Comment by josefaidt** [comment]
Hey @funes79 :wave: thanks for raising this! Unfortunately this is an [active bug](https://github.com/aws-amplify/amplify-cli/issues/10484) we are tracking in the CLI repo. Please subscribe to the linked issue for further updates
