### ISSUE TITLE
iOS SDK docs for Analytics uses deprecated API to initialise Pinpoint.

### ISSUE THREAD

**Issue by eugenio79** [aws-amplify/docs#582]
**Describe the bug**
iOS SDK docs for Analytics uses deprecated API to initialise Pinpoint.

**To Reproduce**
1. Go to 'https://aws-amplify.github.io/docs/ios/analytics#add-analytics'
2. Scroll down to code snippet of point 2, initialisation of Pinpoint

**Expected behavior**
It should initialise AWSMobileClient using the new `initialize` method (but it uses a deprecated `interceptApplication` method instead).

**Desktop**
 - OS: Mac OS X
 - Browser Chrome
 - Version 72.0.3626.12

**Additional context**
Push notifications docs initialise it correctly instead:
https://aws-amplify.github.io/docs/ios/push-notifications#connect-to-your-backend

**Comment by muellerfr** [comment]
@eugenio79 - thank you for pointing this out. The documentation has been updated.
