### ISSUE TITLE
Mismatched Heading in Nav vs Content

### ISSUE THREAD

**Issue by katiegoines** [aws-amplify/docs#5859]
**Describe the content issue**:
Mismatch between Heading 1 on page and heading in left nav: 
![Image 8-21-23 at 12 34 PM](https://github.com/aws-amplify/docs/assets/30757403/01edb6e2-48bb-472c-b2d1-8996e03c13e6)

**URL page where content issue is**:
https://docs.amplify.aws/start/getting-started/integrate/q/integration/flutter/

**Comment by LalitAswal** [comment]
want to work on this issue
