### ISSUE TITLE
complex-objects examples for AppSync to S3 image storage not working

### ISSUE THREAD

**Issue by mfreeman451** [aws-amplify/docs#587]
**Describe the bug**
The example shows a schema that should work with Amplify but when you try to execute an amplify push it will faill with an error.

**To Reproduce**
1. Add the schema to schema.graphql described at https://aws-amplify.github.io/docs/js/api#complex-objects

type Todo @model {
    id: ID!
    name: String!
    description: String!
    file: S3Object
}

type S3Object {
    bucket: String!
    key: String!
    region: String!
}

input CreateTodoInput {
  id: ID
  name: String!
  description: String
  file: S3ObjectInput # This input type will be generated for you
}

2. Execute an 'amplify push'
3. See error:

✖ An error occurred when pushing the resources to the cloud

Type!! "S3ObjectInput" not found in document.

**Expected behavior**
Even if we define S3ObjectInput as:

enum Visibility {
    public
    private
}

input S3ObjectInput {
    bucket: String!
    region: String!
    localUri: String
    visibility: Visibility
    key: String
    mimeType: String
}

We then get a new error:

Conflicting input type 'CreateFishInput' found.

**Screenshots**

**Desktop (please complete the following information):**
 - OSX
- Chrome

**Comment by kjlis** [comment]
The error still occurs if you follow the documentation guide.

**Comment by ilyador** [comment]
I am getting the same issue following the guide.
