### ISSUE TITLE
Feature request: Code blocks should have filenames

### ISSUE THREAD

**Issue by qwikag** [aws-amplify/docs#5942]
This is just an example page:
[https://docs.amplify.aws/cli/graphql/data-modeling/#model-directive](https://docs.amplify.aws/cli/graphql/data-modeling/#model-directive)

The problem with reading these docs is the code and the config run together in a blur.
Some code snippets look like config snippets and vice versa.

So there is a need to have a file name at the top of a section of config or code and show that it is preceded by other code of config and or followed by other code/config.
this way when reading the docs we are able to tell what we are looking at.

All through these amplify docs, this is an extensive issue:
![image](https://github.com/aws-amplify/docs/assets/5670636/005d7a46-56b0-4690-85a9-cd9b220727a0)

[https://docs.amplify.aws/cli/graphql/data-modeling/#model-directive](https://docs.amplify.aws/cli/graphql/data-modeling/#model-directive)

----------------
**Is your feature request related to a problem? Please describe.**

[This guide](https://docs.amplify.aws/guides/api-graphql/query-with-sorting/q/platform/js/#implementation) can be confusing when it walks us through a GraphQL schema example and a client-code example, where providing sample filenames such as `schema.graphql` can provide additional context without the need for describing _where_ we need to write this sample.

**Describe the solution you'd like**

![image](https://github.com/aws-amplify/docs/assets/5033303/cff2b0d6-a4be-4dcc-b058-d2464889f118)

https://www.christopherbiscardi.com/the-quick-guide-to-serverless
![image](https://github.com/aws-amplify/docs/assets/5033303/89233551-86e0-4d49-83b2-9063c6ce1d6e)

**Describe alternatives you've considered**

**Additional context**

https://github.com/aws-amplify/amplify-category-api/issues/1675

**Comment by josefaidt** [comment]
related https://github.com/aws-amplify/docs/issues/5657

**Comment by hbuchel** [comment]
Closing this as complete since we now are able to give code blocks a title/file name as of this PR https://github.com/aws-amplify/docs/pull/6561
