### ISSUE TITLE
Hosting stages should be associated with environments

### ISSUE THREAD

**Issue by gergnz** [aws-amplify/docs#596]
**Is your feature request related to a problem? Please describe.**
No, not really

**Describe the solution you'd like**
I should be able to add a hosting configuration per environment, e.g. so that I can have cloudfront for prod, but just bucket for dev/test.

**Describe alternatives you've considered**
Manually managing this and or switching between environments.

**Additional context**
N/A

**Comment by jordanranz** [comment]
Hi @gergnz,

This seems like a feature request that belong in the [Amplify CLI repo](https://github.com/aws-amplify/amplify-cli/issues). Can you please open an issue in this repo so it can be prioritized.

Closing this as this is the wrong place to request features for the CLI.
