### ISSUE TITLE
Missing Content - Configure multiple authorization modes (Amplify w/ Flutter)

### ISSUE THREAD

**Issue by iamvalenciia** [aws-amplify/docs#5976]
**Configuring Multiple Authorization Modes in Amplify GraphQL API**

The Amplify documentation recommends configuring multiple authorization modes using the following steps:

[Documentation Link](https://docs.amplify.aws/lib-v1/graphqlapi/authz/q/platform/flutter/#configure-multiple-authorization-modes)

1. Include the `graphQLDocumentString` in the `Amplify.API.query()` method.

```dart
Future<void> _refreshBudgetEntries() async {
  try {
    const graphQLDocumentString = '''
      query MyQuery {
        listBudgetEntries {
          items {
            amount
            createdAt
            description
            id
            owner
            title
            updatedAt
          }
        }
      }
    ''';
    final operation = Amplify.API.query(
      request: GraphQLRequest<String>(
        document: graphQLDocumentString,
        apiName: 'ministrar3ApiKey',
      ),
    );

    final response = await operation.response;

    final todos = response.data;
    if (response.hasErrors) {
      safePrint('errors: ${response.errors}');
      return;
    }
    setState(() {
      final todosList =
          jsonDecode(todos!)['listBudgetEntries']['items'] as List<dynamic>;
      _budgetEntries = todosList
          .map((entry) => BudgetEntry.fromJson(entry as Map<String, dynamic>))
          .toList();
    });
  } on ApiException catch (e) {
    safePrint('Query failed: $e');
  }
}

/*
The framework's code documentation suggests using the 'apiName' parameter in ModelQueries to reduce code complexity:
This information is not in the official documentation
*/

```dart
Future<void> _refreshBudgetEntries() async {
  try {
    final request = ModelQueries.list(BudgetEntry.classType, apiName: 'ministrar3ApiKey');
    final response = await Amplify.API.query(request: request).response;

    final todos = response.data?.items;
    if (response.hasErrors) {
      safePrint('errors: ${response.errors}');
      return;
    }
    setState(() {
      _budgetEntries = todos!.whereType<BudgetEntry>().toList();
    });
  } on ApiException catch (e) {
    safePrint('Query failed: $e');
  }
}

**Comment by Jordan-Nelson** [comment]
Hello - @iamvalenciia. I am not 100% sure I understand the request.

I think there might be some confusion because the link you sent is to the documentation for Amplify Flutter v0.x. Version 1.0 was released in April, and the docs for v1.x do include examples using both the API name and the Authorization Mode (see: https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/flutter/#configure-multiple-authorization-modes).

Is that what you are hoping to see? If not, can you include a link to the inline documentation that you are referencing? Thanks

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
