### ISSUE TITLE
Feedback XR category: Sumerian export path

### ISSUE THREAD

**Issue by kay-is** [aws-amplify/docs#602]
It seems that the `amplify add xr` command requires me to give an absolute path to the Sumerian JSON file. I tried everything relative in Cloud9, but only the absolute path worked.

    sumerian-exports.json
    ./sumerian-exports.json
    vr-test/sumerian-exports.json
    /vr-test/sumerian-exports.json
    environment/vr-test/sumerian-exports.json
    ~/environment/vr-test/sumerian-exports.json

I was inside `/home/ec2-user/environment/vr-test` when I ran the command.

Would be nice if it also worked with a path, relative to "where" I ran the command, but in the docs it would be nice if the need of an absolute path is mentioned.

**Comment by jordanranz** [comment]
Hey @kay-is,

Thanks for the feedback. We can make a note in the documentation that you need an absolute path. 

In the future we would definitely like to make this part of the experience simpler. We have a branch where you can use relative files using fuzzy matching but the plugins used had some minor bugs in them that I submitted issues for. If we can resolve those, then we can start using the relative file path matching plugin for this.

**Comment by jordanranz** [comment]
@kay-is,

I have actually updated the CLI code to better handle relative paths for this use case. Can you confirm relative paths work in Cloud9?

**Comment by kaustavghosh06** [comment]
@kay-is Please let us know if you still think this is a problem after @jordanranz's change.
