### ISSUE TITLE
Documentation v6 is still not clear. Not enough noob consideration!

### ISSUE THREAD

**Issue by qwikag** [aws-amplify/docs#6054]
**Describe the content issue**:
It is not clear what these codes are and how they should be used.
If every separate code had a title with an example name then it would be 10x clearer.
right now it is difficult to get into v6 because this documentation is much the same as the old documentation. and is not helping those who are new here.

I was under the impression new docs would be improved.

I will be raising a support case and hopefully my learning from the support case will result in some answers I can add to this Issue

**URL page where content issue is**:
https://docs.amplify.aws/lib-v1/ssr/nextjs/q/platform/js/#authentication

**Comment by qwikag** [comment]
And what does v6 preview mean anyway?
It leaves doubt in my head as to whether this version is useable yet, or is it a preview of what is to come.
Very unclear.

**Comment by abdallahshaban557** [comment]
Hi @qwikag - preview means this is a version that is not yet ready to be used in production. We use preview to help us get more feedback before releasing our new major version.

Regarding our SSR pages, we are currently re-writing them to make it clearer how to use our new functionality. We take our noobs seriously, and we are on it!
