### ISSUE TITLE
[missing-page]

### ISSUE THREAD

**Issue by nikolasmq** [aws-amplify/docs#6067]
**Page**: [`https://docs.amplify.aws/lib/push-notifications/overview/q/platform/js/`](https://docs.amplify.aws/lib/push-notifications/overview/q/platform/js/)

**Feedback**:

**Comment by jacoblogan** [comment]
@nikolasmq thank you very much for bringing this issue to our attention.  This page was removed from the documentation, but we will get a redirect in place to take users to the correct location.  Could you also share where you found a link to this page so that we can get that link updated as well?

**Comment by jacoblogan** [comment]
The content for this page now lives https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/react-native/ and a redirect has been put into place to catch this.  Thanks
