### ISSUE TITLE
[missing-page]

### ISSUE THREAD

**Issue by marcinOz** [aws-amplify/docs#6071]
**Page**: [`https://docs.amplify.aws/lib/push-notifications/overview/q/platform/js/`](https://docs.amplify.aws/lib/push-notifications/overview/q/platform/js/)

**Feedback**: 
Link from this page: https://aws.amazon.com/amplify/features/?nc=sn&loc=3&dn=5
to the Push Notification section is not working.

**Comment by jacoblogan** [comment]
Thank you for bringing this to our attention.  The content for this page now lives https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/react-native/ and a redirect has been put into place.
