### ISSUE TITLE
import example seems to be deformed 

### ISSUE THREAD

**Issue by ykethan** [aws-amplify/docs#6166]
**Describe the content issue**:
The example seems to show an import that has added quotes

![image](https://github.com/aws-amplify/docs/assets/87995712/812e8ea2-6000-463e-b3fa-de09700cb2a3)

**URL page where content issue is**:
https://docs.amplify.aws/how-amplify-works/#building-an-app

**Comment by reesscot** [comment]
@ykethan Thanks for reporting this issues, it has been fixed.
