### ISSUE TITLE
iOS vs Android?  Why not both?

### ISSUE THREAD

**Issue by awhitford** [aws-amplify/docs#618]
Following [Getting Started instructions for React Native, Step 3](https://aws-amplify.github.io/docs/js/start?ref=amplify-rn-btn&platform=react-native#step-3-set-up-the-aws-backend), the `amplify init` prompts me **Choose the type of app that you're building** with the options:
 * Android
 * iOS
 * JavaScript

Why does one need to decide between Android and iOS for a React-Native application?  Ultimately, I am targeting *both*.  (How does one indicate that they want both iOS and Android supported?)

Using @aws-amplify/cli@1.6.1 and react-native-cli@2.0.1 on MacOS Mojave Version 10.14.4 (18E226), Node v10.15.0, and NPM 6.4.1.

**Comment by jordanranz** [comment]
Hey @awhitford,

For React Native you would select JavaScript as you will be utilizing and interacting with Amplify from the JavaScript layer of React Native. This will generate Amplify configuration (aws-exports.js) that can be read as a JavaScript object in the file you are trying to configure Amplify (App.js in the documentation). 

If you were to select iOS or Android here it would generate an Amplify configuration file specific to those platforms. This is used only when doing respective native development in those platforms.

Please reopen this if you have any further related concerns here.

**Comment by awhitford** [comment]
Thanks @jordanranz, this is what I finally figured out.  Alas, it would be wise to hint to this in the documentation.
