### ISSUE TITLE
amplify add auth requires "redirect signin URI" for react-native?

### ISSUE THREAD

**Issue by awhitford** [aws-amplify/docs#625]
For a **react-native** project, when using `amplify add auth`, and choosing _Default configuration with Social Provider_,  I am unclear what to specify for the prompt "**Enter your redirect signin URI**".  It says, "_The value must be a valid URI with a trailing forward slash. HTTPS must be used instead of HTTP unless you are using localhost._"  Does this still apply for a react-native application?  If so, what is the guidance?

Node 10.15.0, npm 6.4.1, @aws-amplify/cli@1.6.1, MacOS 10.14.4 (18E226).

**Comment by snmishra** [comment]
Since there's no answer yet, I guess I'll see what a random URL does for me

**Comment by AlanLattimore** [comment]
I'm using Expo, which runs on `http://localhost:19002/` so I used:
`was-exports.js`
```
        "redirectSignIn": "http://localhost:19002/",
        "redirectSignOut": "http://localhost:19002/",
```

**Comment by qalshakhoori** [comment]
If you are using expo you can use `exp://<your-ip-address>:19000`, that worked for me. I wonder if there any other proper solution rather than hardcoded ip address

**Comment by kaustavghosh06** [comment]
@awhitford We've mentioned about this in our docs out here - https://aws-amplify.github.io/docs/js/authentication#amplify-project-setup
Please let us know if you're still stuck on this.

**Comment by SystemBlad** [comment]
Hi @qalshakhoori,
Had you found a solution to use local IP address in URLs?
We are working in a team and it is a big issue.

**Comment by qalshakhoori** [comment]
Hi @SystemBlad ,

have you tried as provided in documentation ? 
exp://127.0.0.1:19000/--/

**Comment by rajugurung** [comment]
Put a trailing slash at the end of your url e.g. http://localhost:4200/

**Comment by xyn22** [comment]
https://docs.amplify.aws/lib/auth/social/q/platform/react-native/
this docs page suggests using your app's like `myapp://` as the URI
