### ISSUE TITLE
aws-exports.js file missing

### ISSUE THREAD

**Issue by awhitford** [aws-amplify/docs#626]
Consider a new *react-native* application...  Follow along the [instructions](https://aws-amplify.github.io/docs/js/react), I am trying to [add Auth](https://aws-amplify.github.io/docs/js/react#add-auth)entication.

The instructions say:
> The ./src/aws-exports.js file that’s created has all of the appropriate cloud resources defined for your application.

Alas, I do not see any such `aws-exports.js` file being created!

I am using @aws-amplify/cli@1.6.1, Node 10.15.0, NPM 6.4.1, MacOS 10.14.4.

**Comment by jordanranz** [comment]
Hey @awhitford,

During `amplify init` which platform did you select in the list of iOS, Android, and Javascript?
Also, during `amplify init` there was a prompt to enter your 'Source Directory Path'.  This is where the `aws-exports.js` file is saved.

**Comment by awhitford** [comment]
I think I figured out the issue...

When it prompted for a platform, I chose iOS instead of JavaScript because I was using **react-native**.  As a result, it never created an `aws-exports,.js` file.

To help others, a tip indicating to select JavaScript as the platform when using react-native would be wise.

**Comment by awhitford** [comment]
Issue #618 was basically the root issue; I needed to select JavaScript when using react-native.

**Comment by jordanranz** [comment]
Ok, I will close this issue as it seems the problem was solved. Please reopen if you have any more related issues.

**Comment by guptapuja7** [comment]
@jordanranz i get errorinit failed
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27) {
  message: 'read ECONNRESET',
  errno: 'ECONNRESET',
  code: 'NetworkingError',
  syscall: 'read',
  region: 'us-east-1',
  hostname: 'amplify.us-east-1.amazonaws.com',
  retryable: true,
  time: 2020-04-16T11:59:59.320Z
