### ISSUE TITLE
withAuthenticator signUpConfig example

### ISSUE THREAD

**Issue by awhitford** [aws-amplify/docs#629]
When adding authentication using `amplify add auth`, it prompted me to select required fields.  However, it didn't build a signUpConfig, so I need to do that -- without it, the sign up fails due to missing fields.

The documentation is missing 2 things:
1. An example for customizing signUpConfig -- ideally using `withAuthenticator`
2. Elaboration around the `signUpFields`, especially things like `type`.
   * What are all of the possible values for `type`?
   * Which type value would be appropriate for _Picture_?

**Comment by awhitford** [comment]
An example such as:
```

export default withAuthenticator(App, true, [], null, null, {
  signUpFields: [
    {
      label: "First Name",
      key: "name",
      placeholder: "First Name",
      required: true,
      displayOrder: 5
    },
    {
      label: "Last Name",
      key: "family_name",
      placeholder: "Last Name",
      required: true,
      displayOrder: 6
    }
  ]
});
```

**Comment by emmafass** [comment]
This example is really helpful! Could you please also provide an example of how to hide default (but non-required) fields?

I do not want to require phone number but it shows up on the sign up page anyway.

**Comment by patspam** [comment]
Reopen

**Comment by ramanasak** [comment]
> An example such as:
> 
> ```
> 
> export default withAuthenticator(App, true, [], null, null, {
>   signUpFields: [
>     {
>       label: "First Name",
>       key: "name",
>       placeholder: "First Name",
>       required: true,
>       displayOrder: 5
>     },
>     {
>       label: "Last Name",
>       key: "family_name",
>       placeholder: "Last Name",
>       required: true,
>       displayOrder: 6
>     }
>   ]
> });
> ```

any attribute for reset password ?
