### ISSUE TITLE
How to use Environment Variable in project

### ISSUE THREAD

**Issue by Abby3017** [aws-amplify/docs#636]
**Is your feature request related to a problem? Please describe.**
I want to deploy a static site on aws and I am using third party plugins. I don't want to commit authentication keys or url in git repo. I want to know how it can be done in amplify and if not are you guys gonna work on it?

**Describe the solution you'd like**
In amplify, we can save environment variable that can be used in build settings. These variables must be used in our frontend/ static site framework. Before building the frontend project, it should inherit the values from env variable and then build the project. for example, how heroku manages the secrets.

**Comment by lakshaycoder01** [comment]
I'm also facing similar issue
