### ISSUE TITLE
how to add google analytics key during build

### ISSUE THREAD

**Issue by lakshaycoder01** [aws-amplify/docs#639]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by muellerfr** [comment]
@lakshaycoder01 - which platform is this for? iOS, Android, JS, or React Native?

**Comment by lakshaycoder01** [comment]
It's static Hugo site where I want to add google analytics

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lakshaycoder01** [comment]
I want to add google analytics key during my site building but I'm not able to. Can someone help me with this

**Comment by Abby3017** [comment]
I am also having this issue. I want to add secret key of google analytics and comment system in static site HUGO but I don't want to set in my config file and push to git repo as currently required to build static sites in aws-amplify.

**Comment by jordanranz** [comment]
Which part of the Amplify docs is this related to? Can one of you provide a link.

**Comment by Abby3017** [comment]
In this [page](https://aws-amplify.github.io/docs/cli/hosting),  the last [Section](https://aws-amplify.github.io/docs/cli/hosting#using-the-aws-amplify-console). Building with static site is mentioned.

**Comment by lakshaycoder01** [comment]
@muellerfr Can you tell me how can I add google analytics in hugo static site while building it using aws amplify
