### ISSUE TITLE
export certificate as p12

### ISSUE THREAD

**Issue by lsida** [aws-amplify/docs#642]
**Is your feature request related to a problem? Please describe.**
When I followed the Setting Up APNS for Push Notifications - Step 2: Create an APNs SSL Certificate, I found it not that straightforward to export the certificate as p12 file.

**Describe the solution you'd like**
I followed the suggestion here
https://stackoverflow.com/questions/15662377/unable-to-export-apple-production-push-ssl-certificate-in-p12-format/34472980#
to select "My Certificates" first, which enable the .p12 option during export.

**Comment by kvasukib** [comment]
@lsida Sorry for the inconvenience caused. Can you elaborate more on the difficulty you are facing while setting up APNS for Push Notifications?

**Comment by lsida** [comment]
Hi @kvasukib , thank you for the reply. It will be great if you can mention to export as p12 format, you have to select 'My Certificate' in the keychain first. Because otherwise there is no way to select p12 as the export target.

**Comment by palpatim** [comment]
@lsida 

In Step 14 of ["Step 2: Create an APNs SSL Certificate"](https://aws-amplify.github.io/docs/ios/push-notifications-setup-apns#step-2-create-an-apns-ssl-certificate), the instructions state, "Context-select the push certificate and then select Export… from the context menu to export a file containing the certificate".

What is your proposal to make this clearer?

**Comment by my-name-is-nheo** [comment]
I dont know if anyone checks this but how do we know which certificate to use when generating p12?
