### ISSUE TITLE
Empty content in CLI>GraphQL

### ISSUE THREAD

**Issue by palpatim** [aws-amplify/docs#6430]
**Describe the bug**

The new docs site page https://docs.amplify.aws/javascript/tools/cli/graphqlapi/ has no content, just chrome and a title. The child page **Directives reference** does have the directives table as expected, but I was expecting either a redirect to the new "setup your backend" content, or some explanatory content.

**Navigation**

* Sidebar > CLI > API (GraphQL)

**Screenshots**

![image](https://github.com/aws-amplify/docs/assets/227982/b5157f9b-ad92-434b-83ab-fc0174bf2520)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser all

**Comment by reesscot** [comment]
Fixed by: https://github.com/aws-amplify/docs/pull/6422/
