### ISSUE TITLE
Followed Documentation and was missing aws-exports

### ISSUE THREAD

**Issue by hellocarapp** [aws-amplify/docs#646]
**Describe the bug**
After following instructions in documentation, tried running the app and received an error that "aws-exports" was missing from src folder.

**To Reproduce**
1. Follow instructions
2. Run `yarn start`
3. See error and no app.

**Expected behavior**
Follow instructions, run `yarn start`, and see a working app.

**Desktop (please complete the following information):**
 - Pop!_OS 19.04
 - Chrome 73.0.3683.103
 - node 8.16.0
 - npm 6.4.1
 - yarn 1.10.1

**Additional context**
Trying https://aws-amplify.github.io/docs/js/start?platform=react-native instead and seeing if that works.  It is confusing that this is the first hit on Google and it doesn't work and I have to look up the bug to find another tutorial that is almost titled the same way but includes different instructions.

**Comment by mlabieniec** [comment]
@hellocarapp which instructions are you referring to. The quickstarts instruct in using the Amplify CLI which will produce the `aws-exports` file.

**Comment by mlabieniec** [comment]
The aws-exports file is generated for you after you run `amplify push`. Did you run the amplify cli commands in your project?
