### ISSUE TITLE
Syntax @for in Angular is supported by version 17 that requires Node 18, not node 14 like the documentation says

### ISSUE THREAD

**Issue by Phok7** [aws-amplify/docs#6461]
In the Amplify Angular v6 framework documentation the specifitacions requires node v14.x or later but in the "Connect API and database to the app" appears a code fragment that uses the `@for` syntax in the template, which is released in the angular v17 version, which requires minimun node 18.13.

Documentation requirements: [https://docs.amplify.aws/angular/start/getting-started/installation/](https://docs.amplify.aws/angular/start/getting-started/installation/)
Angular v17 syntax: [https://docs.amplify.aws/angular/start/getting-started/data-model/#connect-frontend-to-api](https://docs.amplify.aws/angular/start/getting-started/data-model/#connect-frontend-to-api)

**Comment by nadetastic** [comment]
Hi @Phok7 thank you for pointing this out.I've updated the [Angular getting started guide](https://docs.amplify.aws/angular/start/getting-started/installation/) to mention the minimum required version of node.
