### ISSUE TITLE
Info section not visible on new site

### ISSUE THREAD

**Issue by atierian** [aws-amplify/docs#6464]
**Describe the content issue**:
The previous site had an **Info** section with two pages. The **Info** section and those two pages are no longer visible on the new site.

https://github.com/aws-amplify/docs/tree/main/src/fragments/lib/info
This includes information around uninstalling Amplify apps and a reference for data usage important for Apple platform developers.

**URL page where content issue is**:
Should be reachable from the root platform pages:
- https://docs.amplify.aws/android/
- https://docs.amplify.aws/swift/

**Comment by heatheramz** [comment]
Hi @atierian - thank you for the call out! We did a review and have addressed this by cross-listing these pages with their related categories for both Android and Swift. In additional to increasing the pages presence in the category menus, we also added an additional callout for the Swift data usage information in the Build & Connect a backend landing page.
