### ISSUE TITLE
PhotoPicker needs more documentation

### ISSUE THREAD

**Issue by et304383** [aws-amplify/docs#648]
Specifically, there's no documentation on how to use several attributes of the PhotoPicker (had to look at the source code in PhotoPicker.js).

Also, there's no documentation on how to actually upload a file to S3 after it has been selected and previewed.  In other words, after a user has previewed their photo, how do we provide a submit button for them to click that then uploads to S3?

**Comment by ronaldwidha** [comment]
It flips to an upload button after selecting file. Just make sure you provide `path` to s3 ![Annotation 2019-05-19 085601](https://user-images.githubusercontent.com/465441/57982468-f252f100-7a13-11e9-9ae2-a0352f674883.jpg)

**Comment by et304383** [comment]
@ronaldwidha this did not happen for me when testing. 

Perhaps I was missing an upload path parameter. Is this documented?

**Comment by ronaldwidha** [comment]
I'm using the photopicker Vue component, and the docs is here:
https://aws-amplify.github.io/docs/js/vue#photopicker
you pass the `path` into the `photoPickerConfig`. Hope this helps.
