### ISSUE TITLE
[missing-page] https://docs.amplify.aws/gen2/start/configure-account/

### ISSUE THREAD

**Issue by sta-vanger** [aws-amplify/docs#6550]
**Page**: [`https://docs.amplify.aws/gen2/start/configure-account/`](https://docs.amplify.aws/gen2/start/configure-account/)

**Feedback**: <!-- your feedback here  */}

**Comment by swaminator** [comment]
@sta-vanger where did you get to that page from?

**Comment by jacoblogan** [comment]
Thank you, a redirect has been put into place.
