### ISSUE TITLE
Next.js: "cookiesClient" is not a valid Next.js entry export value.

### ISSUE THREAD

**Issue by makies** [aws-amplify/docs#6594]
**Describe the bug**
Exporting cookiesClient causes build error in Next.js 14

**To Reproduce**
1.  Use Node.js 18 or 20
2. Getting Start with Next.js 14
3. Exec "Connect API and database to the app"
https://docs.amplify.aws/nextjs/start/getting-started/data-model/
4. `npm run build`
```
TS71002: "cookiesClient" is not a valid Next.js entry export value.
```

**Expected behavior**
The build succeeds without errors.

**Desktop (please complete the following information):**
 - OS: Mac
 - Version: 14.1.2

**Additional context**
 - Node.js: 18 or 20
 - aws-amplify: 6.0.5
 - Next.js: 14.0.3

**Comment by timngyn** [comment]
Hi @makies, it looks like your PR #6595 updated the docs so that `export` isn't shown in the docs when going through this page, thank you for that! Would it be okay to close this issue since it seems like `cookiesClient` shouldn't have been exported?
