### ISSUE TITLE
[missing-page] GraphQL API Page Not Found at flutter 

### ISSUE THREAD

**Issue by magisystem0408** [aws-amplify/docs#6637]
**Page**: [`https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/flutter/`](https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/flutter/)

if you click URL link `https://github.com/aws-amplify/amplify-flutter` to API(GraphQL) , show `404 not found`

### screen shot
![problem](https://github.com/aws-amplify/docs/assets/61937077/b1d40dce-d839-4dff-989d-bb09a69ebf91)

### expect result
should redirect ↓ page.
`https://docs.amplify.aws/flutter/build-a-backend/graphqlapi/set-up-graphql-api/`

**Feedback**: <!-- your feedback here  */}

**Comment by magisystem0408** [comment]
### Corresponding pull request
> https://github.com/aws-amplify/amplify-flutter/pull/4229

**Comment by AnilMaktala** [comment]
This issue has been addressed.
