### ISSUE TITLE
Invalid syntax in REST doc example 

### ISSUE THREAD

**Issue by willjstevens** [aws-amplify/docs#6643]
**Describe the content issue**:
A clear and concise description of what the content issue is. Is there content missing or is there incorrect content?

The documentation example has invalid syntax for the REST array. It should be a REST object. 

The current code does not compile.  You cannot give a Javascript array an array of key/value pairs. The REST property should be of type Javascript object. 

**URL page where content issue is**:
https://docs.amplify.aws/javascript/tools/libraries/configure-categories/#api-rest-amazon-api-gateway

**Comment by nadetastic** [comment]
Hi @willjstevens thanks for bringing this to our attention. This issue should now be fixed.
