### ISSUE TITLE
[missing-page]

### ISSUE THREAD

**Issue by jmezzera** [aws-amplify/docs#6644]
**Page**: [`https://docs.amplify.aws/lib/restapi/getting-started/`](https://docs.amplify.aws/lib/restapi/getting-started/)

<img width="1044" alt="image" src="https://github.com/aws-amplify/docs/assets/43732985/ba940ad1-91f1-4cf2-bcdb-ee95ddcc18fd">

Got here from amplify studio page (learn more)

**Comment by timngyn** [comment]
Hi @jmezzera, thank you so much for opening the issue. We've set up a redirect to this page: https://docs.amplify.aws/react/build-a-backend/restapi/configure-rest-api/

I'm going to close out this issue since this is fixed now. Please feel free to open another one if you find any more broken links.
