### ISSUE TITLE
Render method undefined in tutorial

### ISSUE THREAD

**Issue by kevinsullivan** [aws-amplify/docs#665]
**Describe the bug**

The tutorial at https://aws-amplify.github.io/docs/js/react says this:  "Next, add the following methods before the component’s render method as follows:" But there is no render method in the code.  Here is the code in the App.js file created at the start of the tutorial. Where's render?

```
import React from 'react';
import logo from './logo.svg';
import './App.css';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}

export default App;
```

**To Reproduce**
Try it.

**Expected behavior**
I expected the Amazon AWS-official tutorial to work. But it doesn't.

**Screenshots**
 - NA

**Desktop (please complete the following information):**
 - NA

**Smartphone (please complete the following information):**
 - NA

**Additional context**
 - NA

**Comment by jordanranz** [comment]
Hey @kevinsullivan, can you link to the url pertaining to the statement "the code in the App.js file created at the start of the tutorial"? Were you using `create-react-app`? It looks like the latest create-react-app creates a functional component which doesn't contain a render method. 

I believe we should change the example to use `class App extends React.Component` or refactor the Analytics.record to not live in the `componentDidMount()` lifecycle method.
