### ISSUE TITLE
[content issue]: Incorrect example of recording events in Amplify Analytics version 6.

### ISSUE THREAD

**Issue by TitusEfferian** [aws-amplify/docs#6661]
**Describe the content issue**:
I just realized that there are some incorrect attributes in the `record` example from Amplify Analytics version 6. 

I am not sure if this is expected or not according to the documentation, but there are some incorrect attributes explained in the documentation that differ from the actual implementation in the code.

amplify docs:
```
import { record } from 'aws-amplify/analytics';

record({
  event: {
    name: 'albumVisit'
  }
});
```

actual type implementation:
https://github.com/aws-amplify/amplify-js/blob/main/packages/core/src/providers/pinpoint/types/pinpoint.ts#L36-L40
```
export type PinpointAnalyticsEvent = {
    name: string;
    attributes?: Record<string, string>;
    metrics?: Record<string, number>;
};
```

Same explanation as in the example of the code comment:
https://github.com/aws-amplify/amplify-js/blob/main/packages/analytics/src/providers/pinpoint/apis/record.ts
```
/**
 * @example
 * ```ts
 * // Send an event to Pinpoint
 * record({ name: eventName })
 * ```
 *
 * @example
 * ```ts
 * // Send an event to Pinpoint with metrics & custom attributes
 * record({
 *     name: eventName,
 *     attributes: {
 *         'my-attribute': attributeValue
 *     },
 *     metrics: {
 *         'my-metric': metricValue
 *     }
 * })
 * ```
 */
 ```
<img width="443" alt="image" src="https://github.com/aws-amplify/docs/assets/27436728/cc4f5af5-209b-433b-bc97-196379929e57">

There should be no `event` object there.

**URL page where content issue is**:
https://docs.amplify.aws/react/build-a-backend/more-features/analytics/record-events/

**Comment by TitusEfferian** [comment]
In case this is a valid issue, here is my pull request:
https://github.com/aws-amplify/docs/pull/6658

**Comment by nadetastic** [comment]
Hi @TitusEfferian thank you for bringing this to our attention and provide a fix for it! It does appear to be incorrect, Im reviewing your changes and will follow up on the PR

**Comment by nadetastic** [comment]
@TitusEfferian thank you for you contribution! We have merged the changes and are currently live.
