### ISSUE TITLE
website localization to aws-amplify / docs site

### ISSUE THREAD

**Issue by kvramyasri7** [aws-amplify/docs#6672]
**Is your feature request related to a problem? Please describe.**
As we are global product would be nice to have website localization feature for docs. 

**Describe the solution you'd like**
I would like have text translation in other languages in the website. 

**Describe alternatives you've considered**
Learning English with grammar rules 😅. 

**Additional context**

**Comment by reesscot** [comment]
Hi @kvramyasri7,
Thank you for your feature request. I'm closing this out as there is an existing issue open that tracks localization here:
https://github.com/aws-amplify/docs/issues/2648

**Comment by kvramyasri7** [comment]
Great! Scott hoping to see it work One Day ❤️

**Comment by kvramyasri7** [comment]
@reesscot

**Comment by kvramyasri7** [comment]
Interesting to see this issue is opened in 2020 and yet to be resolved. Hoping to see this solved by 2030 haha kidding @reesscot
