### ISSUE TITLE
npx missing in command

### ISSUE THREAD

**Issue by bebbo-zz** [aws-amplify/docs#6680]
https://github.com/aws-amplify/docs/blob/f8e4ec216fdb188d33ed15c63a963f6977bdc668/src/pages/gen2/start/mobile-support/index.mdx#L95C1-L95C82

**Comment by hbuchel** [comment]
Closing this out as the Gen2 mobile documentation was revamped for the Gen2 launch and that code snippet no longer exists. https://docs.amplify.aws/android/start/
