### ISSUE TITLE
Please also add vanilla code examples

### ISSUE THREAD

**Issue by SteffenBurger** [aws-amplify/docs#670]
In the [Auth](https://aws-amplify.github.io/docs/js/authentication) chapter there are several examples with React etc., but there is in my POV no clear "how to" for vanilla apps.

Either it is not available, or mixing the code examples with different UI Frameworks in one single "how to" site confuse me too much.

**Comment by mlabieniec** [comment]
@SteffenBurger the initial API documentation here
https://aws-amplify.github.io/docs/js/authentication#working-with-the-api

provides example code for JS (ES6 and/or TypeScript)...are you looking for ES5 based JS samples?
