### ISSUE TITLE
How to specify aws profile?

### ISSUE THREAD

**Issue by Bryson14** [aws-amplify/docs#6713]
**Describe the content issue**:
A clear and concise description of what the content issue is. Is there content missing or is there incorrect content?

On the page https://github.com/aws-amplify/docs/blob/main/src/pages/gen2/start/quickstart/index.mdx#L71 It specifies that `npx amplify sandbox` it is unclear about how to specify a aws profile.  This is because I have multiple aws accounts and projects happening. It would be nice to specify if this command is going to create a new IAM role, or if I can specify a specific AWS profile on my ~/.aws/credentials file or just the default. so i could use a flag `--aws-profile default` or `npx amplify sandbox --aws-profile userA` .

**URL page where content issue is**:

https://github.com/aws-amplify/docs/blob/main/src/pages/gen2/start/quickstart/index.mdx#L71

**Comment by josefaidt** [comment]
Hey @Bryson14 :wave: thanks for raising this! We support a few different ways of toggling the AWS profile:

```
# with the --profile flag
npx amplify sandbox --profile my-other-profile
# or with AWS CLI environment variables
AWS_PROFILE=my-other-profile npx amplify sandbox
```

More details and examples can be found on our [CLI commands reference page](https://docs.amplify.aws/gen2/reference/cli-commands/#amplify-sandbox)

**Comment by Bryson14** [comment]
that works great! thanks!
