### ISSUE TITLE
[Gen 2] [Build] Impossible to build next app with quickstart

### ISSUE THREAD

**Issue by dz0l038** [aws-amplify/docs#6724]
When following the quickstart and trying to deploy an app with gen2, it fail because Next need node 18.17.0 or above to complete but the default is 18.13.

I tried to run nvm install v18.17.0 first in the build steps -> fal with the error `node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by node)`
Same result with 20.10.0

As there is no free tier on deploy, I have to say that it feels a bit lite paying to debug gen2...

**Comment by ykethan** [comment]
Hey @dz0l038, the issue appears to be similar to https://github.com/aws-amplify/amplify-backend/issues/852. Could you try implementing the suggestion on https://github.com/aws-amplify/amplify-backend/issues/852#issuecomment-1871612608.
Docs PR that add this information: https://github.com/aws-amplify/docs/pull/6714

**Comment by ykethan** [comment]
Closing the issue as duplicate.
