### ISSUE TITLE
Where to apply the IAM Policy referenced in Analytics setup docs?

### ISSUE THREAD

**Issue by matthewbga** [aws-amplify/docs#675]
**Is your feature request related to a problem? Please describe.**
The document here: https://aws-amplify.github.io/docs/ios/analytics#update-your-iam-policy lets us know, "Amazon Pinpoint service requires an IAM policy in order to use the submitEvents API," but it doesn't give clarity on where to apply this. The heading says something about updating your IAM Policy, but which one?

**Describe the solution you'd like**
It would be nice to understand a little more about this new policy, for clarity and confidence sake. Do I simply create the new policy and nothing further? Does this not need to be assigned to another IAM element? Should I select Pinpoint as the service when creating this? Is this simply for later use via reference?

**Comment by kvasukib** [comment]
@matthewbga Thank you for reporting to us. 

If you are using Cognito Identity pool to authenticate the requests to Amazon Pinpoint, then it would the policy attached to the authenticated or the unauthenticated role created by the Cognito Identity pool. 

On the other hand, if you are using static AWS credentials such as Access and Secret Access keys, it would be the IAM policy attached to the IAM role of the user who has the AWS credentials.

I will update the Android and iOS docs to reflect the same. Thank you for pointing it out.

**Comment by danielesalvatore** [comment]
Hi @kvasukib, thank you for your reply. We are currently working on a web React.js application. Is there a preferred/correct way to update the AuthRole with the required Pinpoint permissions and store the the updated IAM policy in the source-code repository? we are using different environment and we would like to have the whole environment described in CloudFormation templates/scripts.

Thank you for your reply!
