### ISSUE TITLE
[missing-page]

### ISSUE THREAD

**Issue by arc4randall** [aws-amplify/docs#6754]
**Page**: [`https://docs.amplify.aws/cli/project/`](https://docs.amplify.aws/cli/project/)

My logs told me to go to https://docs.amplify.aws/cli/project/ but the page is empty

**Comment by josefaidt** [comment]
Hey @arc4randall :wave: thanks for raising this! Out of curiosity are you using the Amplify (Gen 1) CLI? When you receive an error using the Gen 1 CLI it should print and direct you towards https://docs.amplify.aws/cli/project/troubleshooting, perhaps this was a case where text wrapping in the terminal truncated `/troubleshooting`?
