### ISSUE TITLE
[missing-page]

### ISSUE THREAD

**Issue by shantosh-m** [aws-amplify/docs#6755]
**Page**: [`https://docs.amplify.aws/lib/pubsub/getting-started/`](https://docs.amplify.aws/lib/pubsub/getting-started/)

**Feedback**: <!-- your feedback here  */}

**Comment by timngyn** [comment]
👋 Hi @shantosh-m, thanks for reporting this page! Would you happen to remember where this was linked from?

I think in the meantime this page should be the page you want: https://docs.amplify.aws/react/build-a-backend/more-features/pubsub/set-up-pubsub/

**Comment by reesscot** [comment]
Closing out this issue, as we haven't heard back.
