### ISSUE TITLE
[missing-page]

### ISSUE THREAD

**Issue by Pratikharsh01** [aws-amplify/docs#6760]
**Page**: [`https://docs.amplify.aws/lib/analytics/getting-started/`](https://docs.amplify.aws/lib/analytics/getting-started/)

**Feedback**: <!-- your feedback here  */}

**Comment by timngyn** [comment]
👋 Hi @Pratikharsh01, do you know where you found this URL? 

In the meantime, this should be the URL you're looking for: https://docs.amplify.aws/react/build-a-backend/more-features/analytics/set-up-analytics/

(you might need to change the platform to your specific one, but it should be under `Build a backend` -> `More features` -> `Analytics` -> `Set up Amplify Analytics`

**Comment by reesscot** [comment]
Closing this out as we haven't heard back on the source of the missing page and have a redirect in place.
