### ISSUE TITLE
Bad link on docs page

### ISSUE THREAD

**Issue by bruceweir** [aws-amplify/docs#6782]
**Describe the content issue**:
The link for the text "Serverless APIs" points to the wrong URL.
Instead of linking to anything to do with serverless apis, it links to instruction for setting up storage.

**URL page where content issue is**:
https://docs.amplify.aws/react/start/getting-started/nextsteps/

**Comment by hbuchel** [comment]
Closing as completed in this PR https://github.com/aws-amplify/docs/pull/7253
