### ISSUE TITLE
The Quick Start Next.js App Router Start a local dev server is duplicated

### ISSUE THREAD

**Issue by ErikCH** [aws-amplify/docs#6819]
**Describe the bug**
Go to the quick start [Next.js App Router](https://docs.amplify.aws/gen2/start/quickstart/nextjs-app-router/#start-local-dev-server) section. The Start a local dev server shows twice.

**Expected behavior**
Section should only be in there once.

**Comment by katiegoines** [comment]
Hi @ErikCH - I'm not able to reproduce this, are there specific circumstances when this occurs? Thanks!

**Comment by reesscot** [comment]
Closing out as this was fixed.
