### ISSUE TITLE
Docs Page Not Found Error

### ISSUE THREAD

**Issue by erickeno** [aws-amplify/docs#683]
**Describe the bug**
When trying to navigate to the individual docs i.e. javascript, it say the page is not found.

**To Reproduce**
1. Go to `Get Started` Page.
2. Under build your app click on any of the Get Started buttons.
4. You will be presented with a	`Page Not Found` Error

**Expected behavior**
Display the documentations for different platforms.

**Screenshots**
![Screen Shot 2019-05-16 at 2 50 07 PM](https://user-images.githubusercontent.com/3820632/57879226-ee438b00-77e9-11e9-9dad-aae7074fad1d.png)
![Screen Shot 2019-05-16 at 2 42 32 PM](https://user-images.githubusercontent.com/3820632/57879234-f1d71200-77e9-11e9-918c-4fe559a890b9.png)

**Desktop**
 - OS: macOS Mojave Version 10.14.4
 - Browser: chrome 
 - Version: Version 74.0.3729.131 (Official Build) (64-bit)

**Comment by kalinchernev** [comment]
Same here, feels like issue with indexing content.

**Comment by kvasukib** [comment]
Sorry for the inconvenience caused. There are issues related to URL redirection in GitHub Pages. We are looking into mitigating the issue.

**Comment by kalinchernev** [comment]
Pages I was trying to reach are ok now. Thanks!

**Comment by kaustavghosh06** [comment]
Hey guys, I beleive GitHub fixed the issue from their issue and I was able to access the pages back again :)
