### ISSUE TITLE
AWS creditencials are leaking into git repository

### ISSUE THREAD

**Issue by tomaszs** [aws-amplify/docs#693]
Here:

https://aws-amplify.github.io/docs/js/angular

There is a tip to:

Depending on your TypeScript version you may need to rename the aws-exports.js to aws-exports.ts prior to importing it into your app, or enable the allowJs compiler option in your tsconfig.

Inside .gitignore for the created project there is a line:

aws-exports.js

But it  is missing a line:

aws-exports.ts

It causes AWS creditentials to leak into repository if someone won't include this line.
It should be included in the tip in the tutorial above to add following line

**Comment by mlabieniec** [comment]
@kaustavghosh06 may want to add `aws-exports.ts` to the .gitignore as well with the cli considering this may need to be renamed in some situations. or perhaps aws-exports*
