### ISSUE TITLE
document extending auth/unauth roles in Gen 2 docs

### ISSUE THREAD

**Issue by ykethan** [aws-amplify/docs#6941]
**Is your feature request related to a problem? Please describe.**
docs currently does not show document how to modify or add policies to auth and unauth roles. 

**Describe the solution you'd like**

```
import { Policy, PolicyStatement } from "aws-cdk-lib/aws-iam";
const backend = defineBackend({
  auth,
});

const myPolicy = new Policy(backend.auth, "AuthenticatedUserIamRolePolicy",{})
backend.auth.resources.authenticatedUserIamRole.attachInlinePolicy(myPolicy);
```

**Comment by myyk** [comment]
Can you update your policies like that? I'm lost trying to find out how to update authenticated users policies or lambda policies.

**Comment by ykethan** [comment]
@myyk refer to these examples:
https://docs.amplify.aws/react/build-a-backend/functions/grant-access-to-other-resources/#using-cdk
https://docs.amplify.aws/react/build-a-backend/add-aws-services/analytics/set-up-analytics/#set-up-analytics-backend

**Comment by myyk** [comment]
Oh that looks like what I was looking for, thank you!

**Comment by ykethan** [comment]
Closing this as the examples are documented 
[docs.amplify.aws/react/build-a-backend/functions/grant-access-to-other-resources#using-cdk](https://docs.amplify.aws/react/build-a-backend/functions/grant-access-to-other-resources/#using-cdk)
[docs.amplify.aws/react/build-a-backend/add-aws-services/analytics/set-up-analytics#set-up-analytics-backend](https://docs.amplify.aws/react/build-a-backend/add-aws-services/analytics/set-up-analytics/#set-up-analytics-backend)
