### ISSUE TITLE
Is there documentation for aws-amplify-react - Authenticator component? 

### ISSUE THREAD

**Issue by uclaeagit** [aws-amplify/docs#70]
The aws-amplify docs don't go into that at all. I don't know what options I can pass to it. The source code gives me some idea, but it's still very unclear how how to use. Thanks and sorry my googling just missed it.

**Comment by bionicles** [comment]
@powerful23 @mlabieniec this document really still sucks ~1yr later since you last posted... where is the documentation for withAuthenticator and Authenticator? The code is greek to me... I'm not sure why do you use Angular in Typescript to write react... all i want to do is relabel "username" to "email" your react.js component library doesn't use react.js, it uses angular.ts!

**Comment by emergencyofstate** [comment]
Would love documentation on this. FWIW looking at the type definition sheds at least a little light.

`export declare function withAuthenticator(Comp: any, includeGreetings?: boolean, authenticatorComponents?: any[], federated?: any, theme?: any, signUpConfig?: {}): {
    new (props: any): {
        authConfig: any;
        handleAuthStateChange(state: any, data: any): void;
        render(): JSX.Element;
        context: any;
        setState<K extends string | number | symbol>(state: any, callback?: () => void): void;
        forceUpdate(callback?: () => void): void;
        readonly props: Readonly<any> & Readonly<{
            children?: React.ReactNode;
        }>;
        state: Readonly<any>;
        refs: {
            [key: string]: React.ReactInstance;
        };
        componentDidMount?(): void;
        shouldComponentUpdate?(nextProps: Readonly<any>, nextState: Readonly<any>, nextContext: any): boolean;
        componentWillUnmount?(): void;
        componentDidCatch?(error: Error, errorInfo: React.ErrorInfo): void;
        getSnapshotBeforeUpdate?(prevProps: Readonly<any>, prevState: Readonly<any>): any;
        componentDidUpdate?(prevProps: Readonly<any>, prevState: Readonly<any>, snapshot?: any): void;
        componentWillMount?(): void;
        UNSAFE_componentWillMount?(): void;
        componentWillReceiveProps?(nextProps: Readonly<any>, nextContext: any): void;
        UNSAFE_componentWillReceiveProps?(nextProps: Readonly<any>, nextContext: any): void;
        componentWillUpdate?(nextProps: Readonly<any>, nextState: Readonly<any>, nextContext: any): void;
        UNSAFE_componentWillUpdate?(nextProps: Readonly<any>, nextState: Readonly<any>, nextContext: any): void;
    };
    contextType?: React.Context<any>;
};`
