### ISSUE TITLE
Sample code for useDatabasePrefix when using multi auth

### ISSUE THREAD

**Issue by mobilequickie** [aws-amplify/docs#702]
In the docs: https://aws-amplify.github.io/docs/ios/api

in the sample code, it shows 'useDatabasePrefix' when I believe it should be 'useClientDatabasePrefix'.

Also, the example is not complete as it shows a 'try' but no throw, leaving this incomplete.

**Comment by kvasukib** [comment]
@mobilequickie Thank you for reporting to us. Submitted a PR #705 to fix the issue.
