### ISSUE TITLE
Issue with Getting Started->Integrate AWS Resources (Step 4)

### ISSUE THREAD

**Issue by viseatconcierge** [aws-amplify/docs#711]
**Describe the bug**
When I am attempt to integrate the AWS resources in the App.js files in the react native portion of Getting Started, there is something wrong when I copy the code created and paste it over 

<img width="904" alt="Screen Shot 2019-06-03 at 1 52 13 PM" src="https://user-images.githubusercontent.com/49216537/58833896-ea47a380-8606-11e9-8567-458a756e3b59.png">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: crhome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mlabieniec** [comment]
@viseatconcierge it looks like your IDE/editor (sublime?) is not liking the JSX syntax. You probably need to enable it/install a typescript package in sublime text to enable support:
https://packagecontrol.io/packages/TypeScript

**Comment by viseatconcierge** [comment]
Thank you were right!
