### ISSUE TITLE
[BUG]: Bugs in code sample in start.js

### ISSUE THREAD

**Issue by anshumanv** [aws-amplify/docs#719]
**Describe the bug**
Incorrect code sample in start.js

```js
AnaltyicsEventButton.addEventListener('click', (event) => {
  const { aws_mobile_analytics_app_region, aws_mobile_analytics_app_id } = awsconfig;

  Analytics.record('Amplify Tutorial Event')
    .then((event) => {
      const url = `https://${aws_mobile_analytics_app_region}.console.aws.amazon.com/pinpoint/home/?region=${aws_mobile_analytics_app_region}#/apps/${aws_mobile_analytics_app_id}/analytics/events`;
      AnalyticsResult.innerHTML = '<p>Event Submitted. </p>';
      AnalyticsResult.innerHTML += '<p>Events sent: '+(++EventsSent)+'</p>';
      AnalyticsResult.innerHTML += '<a href="'+url+'" target="_blank">View Events on the Amazon Pinpoint Console</a>';
    });

```
**To Reproduce**
1. Go to /docs/start.js
2. Search for abe above code instance.

**Expected behavior**
Missing brackets, variables typos

**Screenshots**
NA

**Desktop (please complete the following information):**
 I don't think this info is relevant

**Smartphone (please complete the following information):**
Not this too

**Additional context**
Not for now

**Comment by mlabieniec** [comment]
Fixed in https://github.com/aws-amplify/docs/pull/732
