### ISSUE TITLE
Typos in instruction manual Step 4

### ISSUE THREAD

**Issue by catonmat** [aws-amplify/docs#720]
**Describe the bug**
Typo

**To Reproduce**
Copy and paste code from Step 4 for src/app.js

**Expected behavior**
Should work without editing

**Screenshots**
1. Mispelled variable name ('AnalyticsEventButton').
2. broken brackets (missing '})') at end of function at end of script.

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Here is the working debugged code:
AnalyticsEventButton.addEventListener('click', (event) => {
  const { aws_mobile_analytics_app_region, aws_mobile_analytics_app_id } = awsconfig;

  Analytics.record('Amplify Tutorial Event')
    .then((event) => {
      const url = `https://${aws_mobile_analytics_app_region}.console.aws.amazon.com/pinpoint/home/?region=${aws_mobile_analytics_app_region}#/apps/${aws_mobile_analytics_app_id}/analytics/events`;
      AnalyticsResult.innerHTML = '<p>Event Submitted. </p>';
      AnalyticsResult.innerHTML += '<p>Events sent: '+(++EventsSent)+'</p>';
      AnalyticsResult.innerHTML += '<a href="'+url+'" target="_blank">View Events on the Amazon Pinpoint Console</a>';
    });
})

**Comment by mlabieniec** [comment]
Fixed in https://github.com/aws-amplify/docs/pull/732
