### ISSUE TITLE
add-social-provider Kotlin Coroutines example is wrong

### ISSUE THREAD

**Issue by emmanuelHa** [aws-amplify/docs#7263]
**Describe the content issue**:
In this documentation https://docs.amplify.aws/android/build-a-backend/auth/add-social-provider/ for Kotlin Coroutines,
it is explained that: 

> try {
>     // Replace facebook with your chosen auth provider such as google, amazon, or apple
>     val result = Amplify.Auth.signInWithSocialWebUI(AuthProvider.facebook(), this)
>     Log.i("AuthQuickstart", "Sign in OK: $result")
> } catch (error: AuthException) {
>     Log.e("AuthQuickstart", "Sign in failed", error)
> }

If I am not mistaken:

> Amplify.Auth.signInWithSocialWebUI(
>         provider: AuthProvider,
>         callingActivity: Activity
>     ) 

does not exist

> The only signInWithSocialWebUI(
>         provider: AuthProvider,
>         callingActivity: Activity
>     ) 

which exists is internal in KotlinAuthFacadeInternal

**URL page where content issue is**:
https://docs.amplify.aws/android/build-a-backend/auth/add-social-provider/

**Comment by tylerjroach** [comment]
@emmanuelHa `Amplify.Auth.signInWithSocialWebUI(AuthProvider.facebook(), this)` is a valid call.

While an options parameter is available, a default implementation is provided, which means it is not required to be passed.
