### ISSUE TITLE
Github.io docs # titles links not displayed correctly

### ISSUE THREAD

**Issue by elorzafe** [aws-amplify/docs#73]
**Describe the bug**
When you go thru github.io docs to a #title like this https://aws-amplify.github.io/amplify-js/media/analytics_guide#automated-setup The title is being hidden by the orange bar.

**To Reproduce**
Clicking on a # title or go click to this [link](https://aws-amplify.github.io/amplify-js/media/analytics_guide#automated-setup)

**Comment by nikhil-dabhade** [comment]
This seems to be fixed. I am able to see the title without it being hidden by the orange bar on Chrome and Firefox. Have not tried it on Edge browser yet. Can you confirm if you are still seeing this issue @elorzafe or @mlabieniec ?

**Comment by nikhil-dabhade** [comment]
@elorzafe : Can you confirm if you are still seeing this issue? If not, can you close this out :)

**Comment by nikhil-dabhade** [comment]
@elorzafe : Following up on this again. Can you confirm?

**Comment by nikhil-dabhade** [comment]
@elorzafe : Following up again.

**Comment by elorzafe** [comment]
@nikhil-dabhade I dont see that issue anymore.

**Comment by nikhil-dabhade** [comment]
Thank you for confirming @elorzafe
