### ISSUE TITLE
Add better JWT information for REST APIs

### ISSUE THREAD

**Issue by undefobj** [aws-amplify/docs#736]
We should give a better example in the JS documentation for REST APIs on using a JWT token as your header. We currently show this in the docs on config which isn't ideal. In the iOS/Android docs we show it on a method and that's easier for customers to grok. I suggest something like:

```
async function postData() { 
    let apiName = 'MyApiName';
    let path = '/path';
    let myInit = { 
        headers: {'Authorization' : Auth.currentSession().accessToken.jwtToken}
    }
    return await API.post(apiName, path, myInit);
}

postData();
```

**Comment by sebsto** [comment]
The above code is not correct, it should be : 
```
        let myInit = { 
            headers: { Authorization: `Bearer ${(await Auth.currentSession()).accessToken.jwtToken}` }
        }
```

The `Bearer` keyword is missing 

The `await` before `Auth.currentSession()` is missing
