### ISSUE TITLE
Is there a dropdown option in signUpFields type?

### ISSUE THREAD

**Issue by ilyador** [aws-amplify/docs#743]
The docs say `‘string’, ‘number’, ‘password’, etc`, does that include a select dropdown?
If so, how to use it?

Also, it would be helpful if the `etc` would be a full list.

**Comment by sammartinez** [comment]
Moving to the docs repo, @ilyador can you provide the link to this piece of the docs you're asking about?

**Comment by ilyador** [comment]
I'm not sure how the docs are build but here is what I found
https://github.com/aws-amplify/docs/blob/86d0e46e86f7f1f74776e30a9b0186aefb30c2a6/theme/_includes/sign-up-fields.html#L39
