### ISSUE TITLE
Search feature is gone

### ISSUE THREAD

**Issue by JoshuaGruber** [aws-amplify/docs#7474]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by renebrandel** [comment]
@JoshuaGruber - Congrats! You're one of the first customers seeing our new docs! We're reindexing the search right now. It'll be up any second.

**Comment by timngyn** [comment]
@JoshuaGruber, thanks for opening the issue, the search just finished indexing and it should be back on the site. Will close this issue out now
