### ISSUE TITLE
Gen 2 rest api sample code has confusing typo `amplifyconfig`

### ISSUE THREAD

**Issue by hangoocn** [aws-amplify/docs#7486]
**Describe the content issue**:
The sample code in section [Initialize Amplify API](https://docs.amplify.aws/react/build-a-backend/add-aws-services/rest-api/set-up-rest-api/#initialize-amplify-api) has these two lines:

Amplify.configure(outputs);
REST: amplifyconfig.custom.API,

But here `outputs` and `amplifyconfig` should both refer to `outputs` imported from '../amplify_outputs.json', so should rename `amplifyconfig` to `outputs` otherwise readers will not know where to get `amplifyconfig`.

**URL page where content issue is**:
https://docs.amplify.aws/react/build-a-backend/add-aws-services/rest-api/set-up-rest-api/#initialize-amplify-api

**Comment by ykethan** [comment]
Thank you for opening this issue, opened a PR: https://github.com/aws-amplify/docs/pull/7494 to address this.
