### ISSUE TITLE
Gen 2 doc for rest api set up can be better organized

### ISSUE THREAD

**Issue by hangoocn** [aws-amplify/docs#7487]
**Describe the content issue**:
Currently it has 3 main sections:
1. [Set up REST API with Lambda Function](https://docs.amplify.aws/react/build-a-backend/add-aws-services/rest-api/set-up-rest-api/#set-up-rest-api-with-lambda-function)
2. [Set up HTTP API with Lambda Function](https://docs.amplify.aws/react/build-a-backend/add-aws-services/rest-api/set-up-rest-api/#set-up-http-api-with-lambda-function)
3. [Initialize Amplify API](https://docs.amplify.aws/react/build-a-backend/add-aws-services/rest-api/set-up-rest-api/#initialize-amplify-api)

When I am reading this doc for rest api setup, and reach the end of first section, I think I am all done since the next section is set up http which is not I want. So I think the rest is all about http api setup.

Then I start to run my app without doing the required section in section 3 'Initialize Amplify API' and keep getting error "InvalidApiName: API name is invalid.". I struggled long time then I found out there is a section 3 after section 2 that is also required for section 1.

I think it is better to reorganize this to make readers know there will be section 3 after finish reading section 1.

**URL page where content issue is**:
https://docs.amplify.aws/react/build-a-backend/add-aws-services/rest-api/set-up-rest-api/#initialize-amplify-api

**Comment by ykethan** [comment]
@hangoocn thank you the feedback. opened a PR to address this: https://github.com/aws-amplify/docs/pull/7494
