### ISSUE TITLE
AndroidManifest.xml app scheme doesn't match documentation

### ISSUE THREAD

**Issue by ekkelenkamp** [aws-amplify/docs#752]
**Describe the bug**
The AndroidManifest.xml app scheme doesn't match documentation. See:

https://github.com/awslabs/aws-sdk-android-samples/blob/master/AmazonCognitoAuthDemo/app/src/main/AndroidManifest.xml

```
 <data android:scheme="demoapp" android:host="demo.cognitoauth.com" android:path="/signin"/>
```
When following the lab example, the following should be used:

```
<data android:scheme="demoapp" android:host="www.loginactivity.com" android:path="/mainactivity"/>

```

**Expected behavior**

The id Token and Access Token screen won't be displayed after a succesfull login if the AndroidManifest.xml isn't updated.

**Comment by palpatim** [comment]
@ekkelenkamp Thanks for noticing the discrepancy. We've merged the fix into the sample docs.
