### ISSUE TITLE
[missing-page]

### ISSUE THREAD

**Issue by myinger** [aws-amplify/docs#7567]
**Page**: [`https://docs.amplify.aws/react/start/quickstart/nextjs-pages-router/`](https://docs.amplify.aws/react/start/quickstart/nextjs-pages-router/)

**Feedback**: <!-- I'm doing Amplify Gen2 quickstart for Vue and after adding three new todos, and clicking on "Review next steps of this tutorial." end up with a 404. I'm using the latest version of chrome on a MacBook Pro (intel). */}

**Comment by riacoding** [comment]
I added a pull request for this issue
