### ISSUE TITLE
Vue documentation importing React?

### ISSUE THREAD

**Issue by rhys-daniel** [aws-amplify/docs#7622]
- Amplify Docs Gen2 - Set up Amplify Data - for Vue
- The supplied code references react multiple times e.g 'src/TodoList.tsx' top line is 'import { useState, useEffect } from "react"; and 'src/App.tsx' second line 'import { useState, useEffect } from "react";'

URL page where content issue is: https://docs.amplify.aws/vue/build-a-backend/data/set-up-data/

**Comment by ErikCH** [comment]
Hi @rhys-daniel Thanks for letting us know this. We'll work on fixing this. It should be Vue not React.
