### ISSUE TITLE
Documentation about the "aws-exports" file

### ISSUE THREAD

**Issue by brylie** [aws-amplify/docs#766]
The [guide for Vue](https://aws-amplify.github.io/docs/js/vue) says to add the following code after npm installing `aws-amplify` and `aws-amplify-vue`:

```js
...
import awsmobile from './aws-exports'
...
```

However, I cannot find mention int hat article of how to generate the `aws-exports` file. I have found this information in a [tutorial video on YouTube](https://www.youtube.com/watch?v=DFftniOvoLA), but it may be important to include the steps to generate the needed configuration in the official documentation, such as:

- directly in the Vue guide, or
- as a top level page, linked to from the Vue guide (and wherever else it is relevant)

**Comment by mlabieniec** [comment]
Is there a reason why the manual configuration documentation does not suffice for this?
https://aws-amplify.github.io/docs/js/authentication#manual-setup

The docs outline the spec needed to override or define your own configuration via the library.

**Comment by ohsik** [comment]
Agree with that a way to generate `aws-exports.js` without doing an `amplify push` is necessary. Since `amplify push` tends to give a random error and fail to build when I make changes in backend and I had to remove the entire backend and re-create every time.

**Comment by localpcguy** [comment]
In reply to @mlabieniec's question re: manual configuration - Since a lot of the other docs reference importing `aws-exports`, I think it is important to have some indication of what that file should look like. My assumption is that it should just export the object defined in the manual setup documentation. But it'd be nice to see the file and have that confirmation.

As to why, I think it's been pretty clearly identified why someone might need to do this configuration without relying on the CLI to create it. As an example, the person working on the client side of an app may not actually have access to Cognito.

**Comment by ozlatior** [comment]
In case people need it and get here like I did, here is my aws-exports file for reference:

```
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://<endpoint_id>.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "<api_key>"
};


export default awsmobile;
```

**Comment by jeyashankher** [comment]
A workaround: the client side JS file when you deploy from console has this config. You can search for "aws_project_region" and find this config.

**Comment by rvanbael** [comment]
Hello @kaustavghosh06 
Any news on this feature request? I have open an issue [here](https://github.com/aws-amplify/amplify-js/issues/5063), which I think is related. I am trying to add react front-end to an iOS project.
1) How could we generate an aws-exports file to match an existing backend?
2) How can we tell to amplify to update this aws-exports, as the backend evolve. In other words, add react to an iOS/Android project.

Thanks!

**Comment by tobilg** [comment]
Regarding the auth part, there are some infos available at https://docs.amplify.aws/lib/auth/start/q/platform/js#re-use-existing-authentication-resource

**Comment by mauerbac** [comment]
Hey all -- seems like everything has been answered? Will close out unless there are further questions.

**Comment by jakemitchellxyz** [comment]
My team needs a way to generate the aws-exports.js file. Generating it via `amplify push` will not work for us, we have spent many weeks attempting to do so in a way that doesn't violate our security least-concerns standards. We have resorted to literally opening S3, Cognito, AppSync, and API Gateway consoles in order to grab the newly provisioned data to create our aws-exports files by hand. There is no reason I can fathom that this file should be coupled to the provisioning / updating of a backend.  This file is for the frontend to connect to an existing backend, not for the frontend to have some sort of receipt of the newest backend. Please either:

- Explain to me the philosophy of why coupling the aws-exports.js to the creation of a new / updated backed somehow adds value or security to the system
- Point me to the issue number where the amplify dev team is actively working to allow the dynamic creation of new aws-exports.js files without running `amplify push`
- Keep this issue open until we create an issue to do so

Thanks for the great product overall. This missing functionality is a huge bottleneck for my team of 8; in fact, it was identified as the #1 cause of waste during our last sprint.

**Comment by jeyashankher** [comment]
I realised that another method that gets the was-exports file is to run `amplify pull` command after the backend is deployed. The exact pull command is available in the "Backend environments" tab. Might be worth trying out.

**Comment by olmax99** [comment]
@jeyashankher Tried with `amplify pull`, see below. Found that if hosting and CI is created through the console, aws-exports.js can be simply created through `amplify env checkout $BACKEND_ENV`.

However, if hosting is setup through Amplify cli, there is no way to create the `aws-exports.js` other than putting it into source control.

amplify.yaml
```
version: 0.1
backend:
  phases:
    build:
      commands:
        # NOTE: Does not create aws-exports.js
        # Execute Amplify CLI with the helper script
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - echo "USER_BRANCH:" $USER_BRANCH 
        - echo "USER_PROJECT_NAME:" $USER_PROJECT_NAME 
        - echo "AWS_APP_ID:" $AWS_APP_ID
        - touch frontend/src/aws-exports.js  
        - /bin/bash scripts/init_frontend.sh $USER_PROJECT_NAME $AWS_APP_ID $USER_BRANCH
        - cd frontend
        # update ./aws-exports.js
        - amplify env checkout $USER_BRANCH
        # check if aws-exports.js is present
        - ls -al && ls -al src && cat src/aws-exports.js
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: frontend/build
    files:
      - '**/*'
  cache:
    paths:
      - frontend/node_modules/**/*
```
scripts/init_frontend.sh
```
#!/bin/bash
set -e
IFS='|'

# Main -------------------------------------------------------------------------
# "$USER_PROJECT_NAME, "$AWS_APP_ID, $USER_BRANCH 

main() {
  if [ "$#" -ne 3 ]; then
    error_exit "Illegal number of parameters. You must pass in the projectName, the appId, and the userBranch."
  fi
 
  REACTCONFIG="{\
  \"SourceDir\":\"frontend/src\",\
  \"DistributionDir\":\"frontend/build\",\
  \"BuildCommand\":\"npm run-script build\",\
  \"StartCommand\":\"npm run-script start\"\
  }"
  # AWSCLOUDFORMATIONCONFIG="{\
  # \"configLevel\":\"project\",\
  # \"useProfile\":false,\
  # \"profileName\":\"default\",\
  # \"accessKeyId\":\"headlessaccesskeyid\",\
  # \"secretAccessKey\":\"headlesssecrectaccesskey\",\
  # \"region\":\"us-east-1\"\
  # }"
  AMPLIFY="{\
  \"projectName\":\"$1\",\
  \"appId\":\"$2\",\
  \"envName\":\"$3\",\
  \"defaultEditor\":\"emacs\"\
  }"
  FRONTEND="{\
  \"frontend\":\"javascript\",\
  \"framework\":\"react\",\
  \"config\":$REACTCONFIG\
  }"
  # PROVIDERS="{\
  # \"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
  # }"

  # amplify pull \
  # --amplify $AMPLIFY \
  # --frontend $FRONTEND \
  # --providers $PROVIDERS \
  # --yes

  amplify pull \
  --amplify $AMPLIFY \
  --frontend $FRONTEND \
  --yes

}

main "${@:-}"
```
NOTE: There are too many moving targets as to easily re-create the bug, i.e. custom source path, amplify components, custom environment variables, etc.

Current Environment: dev
```
| Category | Resource name            | Operation | Provider plugin   |
| -------- | ------------------------ | --------- | ----------------- |
| Hosting  | amplifyhosting           | Create    |                   |
| Auth     | proposalwebreact65cc57a4 | No Change | awscloudformation |
| Function | connectquoteengine       | No Change | awscloudformation |
| Api      | quoteengine              | No Change | awscloudformation |
```

**Comment by geoseong** [comment]
I'd created Hosting through Amplify CLI so I tried to follow your way suggested, it failed in "Build" step in Amplify console.
errors like below. this is the same error that I'd tried to refer to "[Deploying the Backend with Your Front End](https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#frontend-with-backend)" guide.
```
{ AlreadyExistsException: Stack [amplify-{projName}-{env}-xxx] already exists ...
```

in the case of the `amplifyPush` script,
for example, If amplify project has specific branch name like **amplify-test**, `amplifyPush --simple` does not work and this error log returns.
```
# Start initializing Amplify environment: amplify-test
# Initializing new Amplify environment: amplify-test (amplify init)
2020-06-18T16:27:51.365Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2020-06-18T16:27:51.366Z [INFO]: Environment name must be between 2 and 10 characters, and lowercase only.
2020-06-18T16:27:52.060Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2020-06-18T16:27:52.064Z [INFO]: Environment name must be between 2 and 10 characters, and lowercase only.
2020-06-18T16:27:52.066Z [ERROR]: !!! Build failed
2020-06-18T16:27:52.137Z [ERROR]: !!! Non-Zero Exit Code detected
```
you should put your environment name with **-e(or --environment)** option. `amplifyPush -e env`.

several days ago, I'd got painful days solving this problem so I've issued it to [amplify-console repository](https://github.com/aws-amplify/amplify-console/issues/750).
in that issue, I described almost everything I've tried and how to solve it.

and I think cli's hosting document contains too little information. so I will make Pull Request to attach some contents like this topic.

what I've worked on is [here](https://github.com/geoseong/docs/tree/cli-hosting), If you guys have suggestions or advice, please let me know.

**Comment by brene** [comment]
Hi all - the concept behind aws-exports.js or amplifyconfiguration.json is documented here: https://docs.amplify.aws/cli/usage/files#aws-exportsjs-file 

If you have a request on how to generate this file through a different method, please file a feature request to the /amplify-cli repo.

**Comment by atyshka** [comment]
Petition to reopen... I'm still unsure of why this is so closely tied to amplify push. My team is working on an amplify project across multiple machines, and since by default it's added to the gitignore, there's no easy way to propagate the file. Is there a reason why it isn't supposed to be added to git? Requiring every machine to push to generate this file is completely overkill here.

**Comment by mauerbac** [comment]
@atyshka - got it. That does make sense. Will re-open.

**Comment by dentonmwood** [comment]
Possibly a new pespective on this: we're trying to integrate Cognito into our React app without creating a full Amplify project to avoid adding unnecessary dependencies. We don't want to use the CLI at all - just the JS libraries and any config. I've gotten something working by using the Amplify.configure() function to set our Auth parameters as follows:

```
Amplify.configure({
  // Amplify requires app client with no secret
  Auth: {
    region: 'region',
    userPoolId: 'poolId',
    userPoolWebClientId: 'clientId,
    mandatorySignIn: true,
    authenticationFlowType: 'USER_SRP_AUTH',
    oauth: {
      domain: 'domain.com',
      scope: ['phone', 'email', 'profile', 'openid', 'aws.cognito.signin.user.admin'],
      redirectSignIn: 'http://localhost:3000',
      redirectSignOut: 'http://localhost:3000',
      responseType: 'token'
    }
  }
})
```

However, we want to be able to use different pools in our dev, staging, and prod environments. I can provide environment variables to meet all of the fields here, but it seems like it would be easier to just write an `aws-exports.js` file into the source directory in the build. A reference on how to encode this existing config into an exports file manually would be fantastic. Is this not a supported use case?

**Comment by bgever** [comment]
I come from the same perspective as @dentonmwood; for my JS SPA I simply want to use an already provisioned Cognito user pool.

It is a remarkably cumbersome process to setup the entire Amplify CLI and being forced to setup a deployment process by "Amplify conventions". Compare this to Auth0, Azure AAD B2C and Google's Firebase Auth. Then Amplify Auth has a seriously poor developer experience. These other vendors simply allow to inject a SDK (JS module dependency), and their documentation simply states what arguments to pass in to hook things up. To put this in perspective, I've already wasted over 6 hours trying to get this working with Amplify, something what takes only 10 minutes with these other vendors!

Amplify is almost there, thus I'm not sure what's the argument against providing this documentation? Except maybe for AWS to have a commercial interest to force customers to use the Amplify CLI as a vendor lock-in? 🤔

**Comment by bgever** [comment]
Great to see that docs have been updated: 👍
https://docs.amplify.aws/lib/auth/start/q/platform/js#re-use-existing-authentication-resource

Another useful addition would be to have types defined in the source code for the `Amplify.configure()` arguments.

**Comment by nikhname** [comment]
To generate the aws-exports file, an ```amplify push``` or ```pull```command must be executed which is documented. If there is a request for another way to generate the aws-exports file please create a feature-request on the amplify-cli [repo](https://github.com/aws-amplify/amplify-cli/issues/new?template=feature_request.md). The client configuration page has also been updated. If there are additional requests about the source code for Amplify.configure a feature request can be created for the JS [repo](https://github.com/aws-amplify/amplify-js/issues/new?assignees=&labels=feature-request&template=feature_request.md&title=).

**Comment by matias-ibserveis** [comment]
[https://github.com/aws-amplify/amplify-cli/issues/2038#issuecomment-643714632](url)
When I  deleted aws-export.js from gitignore, and execute  amplify push, the file appears

**Comment by hughesjj** [comment]
AWS amplify doesn't have the full functionality of the AWS CDK, so I'm using that over amplify.  The lack of manual documentation on this aws-exports file is incredibly annoying if doing anything heavier in AWS with amplify.

**Comment by noobling** [comment]
How dynamic is this file? This is relevant because im sure a lot of people have a CI/CD pipeline in which they depend on `aws-exports.js` but would prefer not to have to call any amplify commands

**Comment by amypellegrini** [comment]
Thanks @noobling I was going to raise precisely that question. My pipeline is failing after I did the Amplify setup and added `aws-exports.js` file.

I looked at the file and I noticed there is some data there which is not the kind I'd like to have pushed in my repository. I also looked at this issue:

https://github.com/aws-amplify/amplify-cli/issues/4700

So it seems I shouldn't add `aws-exports.js` to my repo, but then I need to resolve the dependency in my App. Is there any guide on how to set this up with existing CI/CD?

**Comment by noobling** [comment]
Yes we pass in secrets for our pipeline

**Comment by chriszirkel** [comment]
I'm using the Serverless Framework to extract and publish the aws-exports.js to AWS Systems Manager Parameter Store. Then I read these parameters in other services and the CI/CD pipeline. Not the best option, but I don't see an alternative unfortunetly.
