### ISSUE TITLE
Documentation for the Function plugin

### ISSUE THREAD

**Issue by ajhool** [aws-amplify/docs#767]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Is your feature request related to a problem? Please describe.**
We recently discovered and began to experiment with the `amplify add function` feature. It does not appear to be documented, anywhere. If it is documented, the "search" feature in the docs does not show anything. We've also reviewed the docs and have not found it in any expected places.

**Describe the solution you'd like**
Basic documentation for the Function plugin.

Edit: After making this issue, I see that there is a section of the Github README.md that contains the list of commands but it would be nice if there was additional information, not just the commands ( https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-category-function/Readme.md )

Some example questions that we have:
1. Do Functions deploy on "push" like the rest of the framework?
2. Is there support for Typescript (apparently not, https://github.com/aws-amplify/amplify-cli/issues/659 but this would be nice to see in documentation)
3. Do Functions have support for Triggers? Can we manually add these in the backend or will manual changes be overwritten on push?
4. Can we edit the cloudformation json file, for instance, add env variables or triggers? I see a file called `myFunctionName-cloudformation-template.json`, is that editable? Will it be overwritten?
5. Codegen generates Typescript mutations. Functions appear to only allow for javascript. It would be nice to be able to reach from the Function code into graphql mutations for API integration

**Describe alternatives you've considered**
Using trial and error and guesswork

**Additional context**
N / A

**Comment by andfk** [comment]
+1

**Comment by ajhool** [comment]
not stale

**Comment by ajhool** [comment]
not stale

**Comment by brene** [comment]
Hi all - we've completely revamped our docs. Functions are now documented here: https://docs.amplify.aws/cli/function
