### ISSUE TITLE
Add Documentation for Testing

### ISSUE THREAD

**Issue by amcdnl** [aws-amplify/docs#769]
## Problem Statement
Currently it is unclear what the best practices / tooling for testing with Amplify and AppSync is. 

## Proposal
It would be nice to have some documentation (and maybe built in tooling) for unit and e2e testing.

**Comment by mlabieniec** [comment]
Are you referring to testing the CLI cloud provider templates / scripts? i.e. in the ./amplify directory? For testing the JS projects it's really dependent on the framework you are using and up to the customer to decide. For example, react generally recommends Jest, while Angular Protractor etc. Or are you referring to iOS/Android platforms?

**Comment by amcdnl** [comment]
I mean testing the GraphQL services that amplify generates.

**Comment by brene** [comment]
Hi we've completely revamped our docs. Can you review this section? https://docs.amplify.aws/cli/usage/mock
