### ISSUE TITLE
Web Client ID 25 characters

### ISSUE THREAD

**Issue by PaulGLujan** [aws-amplify/docs#771]
In the docs in Authentication => Manual Setup Code Setup => Code Snippet 

`
        // OPTIONAL - Amazon Cognito Web Client ID (26-char alphanumeric string)
        userPoolWebClientId: 'a1b2c3d4e5f6g7h8i9j0k1l2m3',
`

I believe the Amazon Cognito Web Client ID can be 25 characters

**Comment by mlabieniec** [comment]
The Amazon Cognito Web Client IDs are 26 characters
