### ISSUE TITLE
Typo of the react package in the example code

### ISSUE THREAD

**Issue by haochang** [aws-amplify/docs#773]
**Describe the bug**
Typo in the example code

**To Reproduce**
1. Go to 'https://aws-amplify.github.io/docs/js/react#sign-upin-with-emailphone-number'

**Expected behavior**
The example code should work

**Screenshots**
![image](https://user-images.githubusercontent.com/4257280/60842057-26a08d80-a1cb-11e9-97ac-deffeaf7c1b1.png)

**Additional context**
It should be 
`import { withAuthenticator, Authenticator } from 'aws-amplify-react';`

Not
`import { withAuthenticator, Authenticator } from 'aws-amplfy-react';`

**Comment by mlabieniec** [comment]
Fixed
