### ISSUE TITLE
Dropdown menu error when run locally

### ISSUE THREAD

**Issue by fuelvin1** [aws-amplify/docs#7750]
**Describe the content issue**

Opening a dropdown menu while running on localhost throws an error. 

**Screenshots**

<img width="810" alt="image" src="https://github.com/aws-amplify/docs/assets/172301946/3d5214df-3bc8-4df4-8ddc-06c94f7ac936">

<img width="1512" alt="image" src="https://github.com/aws-amplify/docs/assets/172301946/60fbcc94-6464-45fd-8184-a0ef8fdf20fe">

**Comment by hbuchel** [comment]
@fuelvin1 thanks for reporting this! This issue should be fixed if you pull down the latest from main.
