### ISSUE TITLE
Where is the content about `cron jobs` on Amplify Gen2's documentation?

### ISSUE THREAD

**Issue by ggj0418** [aws-amplify/docs#7778]
**Describe the content issue**:
A clear and concise description of what the content issue is. Is there content missing or is there incorrect content?
it is a missing content about `function`'s `cron jobs`.

**URL page where content issue is**:

On this [documentation content](https://docs.amplify.aws/nextjs/start/migrate-to-gen2/) about amplify migration from v1 to v2, i could find about the `cron jobs` at the `function` category. And maybe~ I caught a glimpse of the content related to the `cron jobs` of `Function` on amplify gen2 documentation about two months ago.

But now, i cannot find the content of `function's cron jobs` on the document. It was originally there, but has it disappeared or has it not been there since the beginning?

**Comment by jcheck1102** [comment]
Same question here. I am looking for this documentation.

**Comment by josefaidt** [comment]
Hey folks, we now have documentation for cron jobs at https://docs.amplify.aws/react/build-a-backend/functions/scheduling-functions/, let us know if you have any questions! closing issue
