### ISSUE TITLE
Trivial bug with initial start of docs under the View path. 

### ISSUE THREAD

**Issue by techmag** [aws-amplify/docs#794]
_(Wow - A GitHub interface bug while submitting this bug -- Don't click on the "No Thanks" option unless you want your bug report erased...)_ 

**Describe the bug**

**To Reproduce**
1. Go to https://aws-amplify.github.io/docs/js/start?platform=vue
2. Follow "Step One"

**Expected behavior**
App should be created without an error 

**Screenshots**
vue create myAmplifyProject
Invalid project name: "myAmplifyProject"
Warning: name can no longer contain capital letters

**Desktop (please complete the following information):**
 - OS: OS X Mojave (clean install)

**Additional context**
vue create my-amplify-project works just fine.

**Comment by undefobj** [comment]
This is fixed in the new Getting Started docs: https://aws-amplify.github.io/docs/js/start#step-1-create-a-new-app
