### ISSUE TITLE
Trivial Bug on Example Vue Template 

### ISSUE THREAD

**Issue by techmag** [aws-amplify/docs#796]
**Describe the bug**
Missing the data binding for 'eventsSent' -- you do go to all the trouble of incrementing it on each button press so might as well show the result just as the basic JavaScript only path does. 

**To Reproduce**
1. Go to 'https://aws-amplify.github.io/docs/js/start?platform=vue'
2. Click on Step 4. Integrate AWS Resources: 'https://aws-amplify.github.io/docs/js/start#step-4-integrate-aws-resources'
3. Scroll down to 'Add the following to the <template> element:'

**Expected behavior**
Should include data binding for the eventsSent counter

**Screenshots**

![Screenshot_2019-07-19__5_14_PM](https://user-images.githubusercontent.com/2105782/61566002-c0c4c900-aa48-11e9-92a1-11608110198d.png)

**Desktop (please complete the following information):**
 - OS: OS X Mojave (clean install) 

**Additional context**

Simply needs this line in the example template: 
      Events sent: {{ eventsSent }}

![Screenshot_2019-07-19__5_16_PM](https://user-images.githubusercontent.com/2105782/61566061-ece04a00-aa48-11e9-9180-5f5d46a4e1ae.png)

**Comment by undefobj** [comment]
@techmag We recently did a full overhaul of the Getting Started and this is no longer present. Closing but if you feel there is still an issue please let us know.
