### ISSUE TITLE
There is no example of how to use the amazon pinpoint to send emails from an android app.

### ISSUE THREAD

**Issue by Vishalratnam** [aws-amplify/docs#798]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by palpatim** [comment]
@Vishalratnam 

Can you provide some details around this? Pinpoint isn't used to send emails from Android; it's a targeting platform that would allow you to send emails *to* your customers based on segments that may include device type.
