### ISSUE TITLE
[UI] Sidebar is broken when the hamburger menu is enabled.

### ISSUE THREAD

**Issue by salihgueler** [aws-amplify/docs#8012]
**Describe the bug**
![Screenshot 2024-10-01 at 20 14 06](https://github.com/user-attachments/assets/38d28551-83ca-444e-a9fe-7b12facc8a2a)

**To Reproduce**
1. Go to docs.amplify.aws
2. Make your screen smallar
3. Click on the hamburger menu

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 129.0.6668.60 (Official Build) (arm64)

**Comment by noone123456789101** [comment]
@reesscot Absolute garbage, scrappy shit, nice accessibility of sidebar.

**Comment by noone123456789101** [comment]
@katiegoines

**Comment by noone123456789101** [comment]
absolutely horrible @reesscot
