### ISSUE TITLE
Docs missing policy for elasticSearch

### ISSUE THREAD

**Issue by mtliendo** [aws-amplify/docs#811]
**Describe the bug**
When creating a user with explicit cli rights as per [the docs](https://aws-amplify.github.io/docs/cli-toolchain/usage#iam-policy-for-the-cli), it doesn't take into accoun the user using the `@searchable` directive, with their graphql api.

**To Reproduce**
1. Create a new user
2. Attach a new policy and past the in statement from the above link
3. After initializing a new amplify project/env with that user, create a new graphql API with the `@searchable` directive
4. See error:

![image](https://user-images.githubusercontent.com/5106417/62066797-c912c600-b1f7-11e9-8ee3-00127ba7c02e.png)

**Expected behavior**

I would expect the CLI to create the API mapped to the elasticsearch resource.

**Additional context**
I attempted to circumvent the issue by adding `"es:*"` to the policy, however that didn't work.  My belief is that the `*` is not capturing the `es:CreateElasticsearchDomain` action, though I haven't had chance to dive into it.

**Comment by mtliendo** [comment]
After messing around with it for a bit, I wanted to share the following:

```
               "es:CreateElasticsearchDomain",
                "es:DescribeElasticsearchDomain",
                "es:DeleteElasticsearchDomain",
                "es:DescribeReservedElasticsearchInstanceOfferings",
                "es:DescribeReservedElasticsearchInstances",
                "es:ListDomainNames",
                "es:PurchaseReservedElasticsearchInstance",
                "es:DeleteElasticsearchServiceRole",
                "es:ListElasticsearchInstanceTypes",
                "es:DescribeElasticsearchInstanceTypeLimits",
                "es:ListElasticsearchVersions",
```

which seems excessive, but also let me get the furthest in the process.  However upon doing so, I ran into this error when elasticsearch was performing some final mapping: 

![image](https://user-images.githubusercontent.com/5106417/62071213-ab4a5e80-b201-11e9-8bef-d952b250a29b.png)

**Comment by mtliendo** [comment]
@sammartinez Is the CLI tag the best tag  for this case? I was really just hoping to get the docs updated.

**Comment by sammartinez** [comment]
@mtliendo We tag our docs based on what needs to get updated. Since this is CLI related, that is the reason for the label as such.

**Comment by mtliendo** [comment]
Oh duh, sorry that makes sense.
