### ISSUE TITLE
Push Notification documentation is not clear at-least for React Native project initiated with expo

### ISSUE THREAD

**Issue by babu-upcomer** [aws-amplify/docs#812]
** Which Category is your question related to? **

`amplify add notifications`

** What AWS Services are you utilizing? **

Wanted to try AWS Pinpoint for push notifications. I am successfully able to add the FCM to pinpoint for android. Though stuck with how I can integrate the same with the frontend. I also need to do the same with APNs for iOS.

** Provide additional details e.g. code snippets **

https://aws-amplify.github.io/docs/js/push-notifications -> *Download google-services.json file and copy it under your android/app project folder.*

I don't have the `android/`folder created in the project. Also project was initiated by `expo init` as in https://aws-amplify.github.io/docs/js/start?platform=react-native. Altogether it is really confusing how to integrate AWS Pinpoint push notifications to the amplify react native project initiated with expo.

**Comment by GeorgeBellTMH** [comment]
I believe the solution to this will be to create a custom channel in pinpoint and connect it with lambda to expo's notification service....

**Comment by babu-upcomer** [comment]
The document is not showing the push notification configuration using pinpoint in the expo **managed workflow** projects. I had reached the AWS support and they are still figuring out how to solve my problem.

**Comment by sammartinez** [comment]
@babu-upcomer Are you still looking for this use case? Please let us know

**Comment by babu-upcomer** [comment]
> @babu-upcomer Are you still looking for this use case? Please let us know

No, I'm not. I moved away from amplify for now.

**Comment by sammartinez** [comment]
Understood thanks for getting back to us. Resolving this issue

**Comment by desoss** [comment]
@sammartinez can you provide us any different solution? 
I don't want to move away from amplify too.

**Comment by sammartinez** [comment]
Hello @desoss, since this issue was closed, we have taken the time to update our documentation around our Push Notifications category. If you are still experiencing issues with it, can you please create an additional issue @desoss and we can look into it? Thanks!
