### ISSUE TITLE
Update Podfile example versions

### ISSUE THREAD

**Issue by rmondragon** [aws-amplify/docs#835]
**Describe the bug**
```
→ pod install
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "AWSCore":
  In snapshot (Podfile.lock):
    AWSCore (= 2.10.2, ~> 2.10.0)

  In Podfile:
    AWSAppSync (~> 2.12.0) was resolved to 2.12.2, which depends on
      AWSCore (~> 2.9.0)

    AWSCore (~> 2.10.0)

[!] Automatically assigning platform `ios` with version `12.4` on target `amplify` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
```

**To Reproduce**
Follow instructions for ios-amplify

**Expected behavior**
Clean install. 
worked with
  pod 'AWSCore', '~> 2.9.0'
  pod 'AWSAppSync', '~> 2.12.2'

```
→ pod install
Analyzing dependencies
Downloading dependencies
Installing AWSAppSync (2.12.2)
Installing AWSCore 2.9.10 (was 2.10.2)
Installing ReachabilitySwift (4.3.0)
Installing SQLite.swift (0.11.6)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 2 dependencies from the Podfile and 4 total pods installed.

```

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.5
 - Apple Swift version 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5) 
Target: x86_64-apple-darwin18.6.0

**Comment by palpatim** [comment]
@rmondragon We had an SDK incompatibility that we've fixed recently. I've also got https://github.com/aws-amplify/docs/issues/835 in place to update to latest version.

**Comment by palpatim** [comment]
I'm not sure what PR I was originally referring to when I self-referenced this issue above, but this request should be covered by #843.
