### ISSUE TITLE
Wrong page link: Firebase credentials

### ISSUE THREAD

**Issue by beaurushton** [aws-amplify/docs#838]
**Describe the bug**

This issue duplicates https://github.com/aws-amplify/docs/issues/475 which was auto closed.  The same issue still persists.

https://aws-amplify.github.io/docs/js/push-notifications#setup-for-android

Get your push messaging credentials for Android in Firebase console. Click here for instructions.
The link behind "Click here for instructions" is dead.

**To Reproduce**
Click on link
Observe 404

**Expected behavior**
Page found

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 N/A

**Additional context**
N/A

**Comment by beaurushton** [comment]
Correct link looks to be https://aws-amplify.github.io/docs/android/push-notifications-setup-fcm

**Comment by palpatim** [comment]
Fixed on #842
