### ISSUE TITLE
@searchable directive doesn't inform of the price cost

### ISSUE THREAD

**Issue by mtliendo** [aws-amplify/docs#846]
**Is your feature request related to a problem? Please describe.**
I checked my billing to find that I owe $150, primarily due to my elasticSearch instance.

![aws-service-cost](https://user-images.githubusercontent.com/5106417/62786792-f3cb0d00-ba88-11e9-9d7f-25f081d6366f.png)

**Describe the solution you'd like**
I understood what elasticSearch was doing, but was unaware that it was doing it via an ec2 instance.  I would like documentation explaining the [pricing](https://aws.amazon.com/elasticsearch-service/pricing/) one can expect when using the `@searchable` directive.

**Describe alternatives you've considered**
Alternatives would be documentation on how to do richer queries that don't rely on ES.

**Additional context**
I had a billing alert setup, but it pointed to an old email.  Perhaps documentation on setting up a billing alert for those new to AWS or coming outside of free tier? Also, perhaps price maps for other services would help as well.

**Comment by usmansbk** [comment]
Wow! That's a lot during development and testing. Thanks for heads-up.
