### ISSUE TITLE
@auth directive contradiction

### ISSUE THREAD

**Issue by usmansbk** [aws-amplify/docs#847]
**Describe the bug**
[The docs says](https://aws-amplify.github.io/docs/cli-toolchain/graphql#auth)
> The following arguments are deprecated. It is encouraged to use the 'operations' argument.
>    ` queries: [ModelQuery]`
>     `mutations: [ModelMutation]`

Also (Draft example)

> Authorize the update mutation and both queries. Use `queries: null` to disable auth for queries.
>`{ allow: owner, ownerField: "editors", operations: [update] }`

**Expected behavior**

> Note: The operations argument was added to replace the ‘queries’ and ‘mutations’ arguments. The ‘queries’ and ‘mutations’ arguments will continue to work but it is encouraged to move to ‘operations’.

**Additional context**
Can someone explain why I'll need to use `queries: null` when it is marked as deprecated and encoraged to use the 'operations' argument. I also saw a [dev post](https://dev.to/open-graphql/graphql-recipes-building-apis-with-graphql-transform-3jp0) that uses both 'operations' and 'queries'

**Comment by namlt3820** [comment]
I also have a question regarding this section.

> { allow: owner },
> { allow: owner, ownerField: "editors", operations: [update] }

From what I understand, the first line has made it so that no one beside the owner can read, update, delete. So the second line should only allow editors to update, create. Why can they have read permission?
