### ISSUE TITLE
Docs for Apollo

### ISSUE THREAD

**Issue by amcdnl** [aws-amplify/docs#862]
## Problem Statement
The amplify frameworks makes several abstract references to apollo, however, it does not explicitly state how to configure it or leverage its tooling.

## Proposal
- Add documentation around `apollo.config.js` so that tooling like Apollo's GraphQL editor extensions will know how to read the schema. Reference: https://www.apollographql.com/docs/platform/editor-plugins/#setting-up-an-apollo-config
- Add documentation on how to use AppSync and Apollo together with Apollo's extensions

## Example Use Case
I needed to be able to handle custom error notifications and thus apollo's error link was a good solution, however, configuring that turned out to be rather tricky. The end result was a lot of googling and looking at source code to understand how to put it together. Example code:

```typescript
import Amplify from 'aws-amplify';
import { Auth } from 'core/Auth';
import AWSAppSyncClient, { createAppSyncLink } from 'aws-appsync';
import { ApolloLink } from 'apollo-link';
import { onError } from 'apollo-link-error';
import { AWS_CUSTOM_CONFIG } from '../../aws-exports';

Amplify.configure(AWS_CUSTOM_CONFIG);

const onErrorLink = onError(({ graphQLErrors, networkError }) => {
  if (graphQLErrors)
    graphQLErrors.map(({ message, locations, path }) =>
      console.error(
        `[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`
      )
    );

  if (networkError) {
    console.error(`[Network error]: ${networkError}`);
  }
});

const auth = {
  type: AWS_CUSTOM_CONFIG.aws_appsync_authenticationType as 'OPENID_CONNECT',
  jwtToken: () => {
    const session = Auth.getStoredSession();
    if (session) {
      return session.idToken;
    }
  }
};

export const appSyncClient = new AWSAppSyncClient(
  {
    url: AWS_CUSTOM_CONFIG.aws_appsync_graphqlEndpoint,
    disableOffline: true,
    region: AWS_CUSTOM_CONFIG.aws_appsync_region,
    auth
  },
  {
    link: ApolloLink.from([
      onErrorLink,
      createAppSyncLink({
        url: AWS_CUSTOM_CONFIG.aws_appsync_graphqlEndpoint,
        region: AWS_CUSTOM_CONFIG.aws_appsync_region,
        auth,
        complexObjectsCredentials: () => Auth.getStoredSession()
      })
    ])
  }
);
```

**Comment by amcdnl** [comment]
Why is this closed? This is still relevant.

**Comment by bgriffith** [comment]
This would be great - did you get it working? @amcdnl
