### ISSUE TITLE
Edit link in docs is broken

### ISSUE THREAD

**Issue by mrcoles** [aws-amplify/docs#873]
**Describe the bug**

**To Reproduce**
1. view the docs https://aws-amplify.github.io/docs/cli-toolchain/usage#build-options
2. Click on "Edit" link in top right of the screen
3. Leads to 404 this is not the page you’re looking for: https://github.com/aws-amplify/docs/edit/master/cli-toolchain/usage#build-options.md

**Expected behavior**

This should send me to a screen that let’s me propose an edit or the edit link should not exist at all. Is it possible that only mods on the repo can edit, so it works for them but no one else?

**Screenshots**

<img width="393" alt="Screen Shot 2019-08-27 at 1 50 14 PM" src="https://user-images.githubusercontent.com/136651/63795281-a0065380-c8d1-11e9-8f20-4e68e008e5ed.png">

<img width="994" alt="Screen Shot 2019-08-27 at 1 48 03 PM" src="https://user-images.githubusercontent.com/136651/63795265-92e96480-c8d1-11e9-9c50-da72784422d7.png">

**Desktop (please complete the following information):**
 - OS: Mac OSX 10.14.6
 - Browser Chrome
 - Version 76.0.3809

**Comment by swaminator** [comment]
Closing as we are now on the v2 docs.
