### ISSUE TITLE
Docs not in sync with latest CLI - iOS client fails to build

### ISSUE THREAD

**Issue by vividcode** [aws-amplify/docs#887]
I followed [the tutorial](https://aws-amplify.github.io/docs/ios/start) step by step. 

However at the point where it says API.swift is generated, it deviates from the actual execution. I see 5 files generated under **generated-src** folder.

Pod file needs to have the line:     pod 'AWSAPIGateway'

Even after that, it gives these errors:

1 - Cannot assign to property: 'endpoint' is a get-only property
2 - Value of type 'READERRESOURCESReaderResourcesClient' has no member 'invokeHTTPRequest' (happens twice)

**To Reproduce**
1. Follow the [tutorial docs for Amplify](https://aws-amplify.github.io/docs/ios/start)
2. After doing **amplify push** and **pod install** step, It yields build errors.

**Expected behavior**
API.swift should be generated. The xcworkspace should build correctly.

**Desktop (please complete the following information):**
 - MacOS Mojave
 - XCode 10.2.1

**Comment by royjit** [comment]
Hi @vividcode Thank you for reaching out. The [Getting Started](https://aws-amplify.github.io/docs/ios/start#step-4-add-api-and-database) document is for GraphQL side of setup as mentioned in [step 4](https://aws-amplify.github.io/docs/ios/start#step-4-add-api-and-database).

From the error type you have mentioned, it looks like you are using REST as the service type, for that please follow the guide here  https://aws-amplify.github.io/docs/ios/api#rest-api

**Comment by vividcode** [comment]
Good to know @royjit , thanks for the link.
It would be helpful in future to have some indicator separating GraphQL vs REST on the [iOS main page](https://aws-amplify.github.io/docs/ios/start), so readers can easily find out all possible paths. 
Thanks for the great work!
