### ISSUE TITLE
geolocation search 

### ISSUE THREAD

**Issue by diegonat** [aws-amplify/docs#890]
**Describe the bug**

I cannot follow the instruction. I believe there is something missing:

```gql 
type Location {
  lat: Float
  lon: Float
}
input LocationInput {
  lat: Float
  lon: Float
}
type Todo @model @searchable {
  id: ID!
  name: String!
  description: String
  comments: [Todo] @connection(name: "TodoComments")
  location: Location
}
type Query {
  nearbyTodos(location: LocationInput!, km: Int): TodoConnection
}
```

However, TodoConnection is not defined anywhere and this raises an error when you try to push the change.

Moreover, it is not clear IF `#set( $indexPath = "/todo/doc/_search" )` needs to be a new index

**Comment by mauerbac** [comment]
hey @diegonat - sorry for the late response. I imagine you have moved on, but will assign to get this cleared up. Docs here -> https://docs.amplify.aws/cli/graphql-transformer/resolvers#add-a-custom-geolocation-search-resolver-that-targets-an-elasticsearch-domain-created-by-searchable
