### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by Ryanauger95** [aws-amplify/docs#908]
These docs are very out of date. App store connect has none of these options.

**Comment by palpatim** [comment]
@Ryanauger95 Can you clarify your comments somewhat? Which app store are you referring to? What documentation page?

**Comment by Ryanauger95** [comment]
I didn't save the link, sorry. Was very frustrated.

**Comment by Ryanauger95** [comment]
Cant find what I was looking at. I thought this page was directly linked to it. My bad.
