### ISSUE TITLE
Auth.currentUserPoolUser() returns NetworkError instead of current user

### ISSUE THREAD

**Issue by andidev** [aws-amplify/docs#910]
**Describe the bug**
In React Native when Auth.currentUserPoolUser() is called and the network is disabled on the device the user is correctly returned from the local storage. But in some cases we get Network error thrown instead of the expected user from local storage. Not 100% sure about when but it looks it happens when the internet connection is bad. 

**Reproduce**
Cannot reproduce since it does not happen that often and is not reproducable on ios simulator or android emulator.

**Expected behavior**
In every case of network error the user should be returned from the local storage.

**Smartphone**
React Native 0.59.10
aws-amplify 1.1.28

**Error**
```javascript
{
  code: "NetworkError", 
  message: "Network error", 
  name: "Error"
}
```

**Comment by sammartinez** [comment]
@andidev Are you still experiencing this issue on later versions of Amplify JS? Please let us know

**Comment by andidev** [comment]
I'm not sure actually. I know I solved an issue by rewriting the amplify logic. It may be fixed now not sure. I'll create a new issue if not when upgrading.
