### ISSUE TITLE
Hard to scroll table of contents

### ISSUE THREAD

**Issue by kernwig** [aws-amplify/docs#915]
**Describe the bug**
Often the main content scrolls when I'm trying to scroll the left-panel table of contents. Occasionally the TOC will scroll when hovering over it, or if I click in in first, but often even then the main body scrolls instead. This is using the scroll wheel on my mouse, since it is impossible to grab the single-pixel scrollbar.

**To Reproduce**
1. Go to https://aws-amplify.github.io/docs/cli-toolchain/usage?sdk=js
2. Expand a section in the TOC.
3. Switch between trying to scroll the body and scroll the TOC.
4. After a few tries, the TOC will no longer scroll.

**Expected behavior**
It clicking to provide focus to the TOC should make future scroll event apply to it.
Add a real draggable scrollbar to the TOC section, for use without a scroll wheel.
  OR
Eliminate the separate TOC scrollbar, and just let it scroll with the page.

**Desktop (please complete the following information):**
 - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

**Comment by nickfreemandesign** [comment]
scroll also has a really hard time on https://aws-amplify.github.io/docs/js/api

**Comment by ntrabue** [comment]
At the very least, it'd be nice if once you clicked to expand you could also click on the subject to collapse it. The UI makes it seem as though that's possible but click on the arrow indicating that the section is expanded does nothing. Some of these sections are incredibly long.

**Comment by kernwig** [comment]
Keep open. Problem has not been addressed.

**Comment by kernwig** [comment]
Another month, another bump to stop the stale bot.
