### ISSUE TITLE
Distracting Documentation: Storage S3 CORS policy

### ISSUE THREAD

**Issue by kernwig** [aws-amplify/docs#918]
**Describe the bug**
The instructions at https://aws-amplify.github.io/docs/js/storage#amazon-s3-bucket-cors-policy-setup are unnecessary and should be removed.

**To Reproduce**
1. Follow the instructions for setting up storage in S3.

**Expected behavior**
Amplify already makes the configuration that the documentation is telling the reader to do manually. (This is good, as manual changes to deploy every environment for the first time would break IaC.)

**Additional context**
The instructions are an unnecessary distraction and make it _appear_ that Amplify fails to follow IaC practices.

**Comment by undefobj** [comment]
We should actually add a note that this is automatically done with the Amplify CLI, the existing docs spell out what needs to be done if using just the JavaScript lib. @nikhil-dabhade

**Comment by nikhil-dabhade** [comment]
Taking a look at this. I will have a PR out this week.

**Comment by sammartinez** [comment]
> Taking a look at this. I will have a PR out this week.

Im working on one now.
