### ISSUE TITLE
full documentation for options and parameters to withAuthenticator()

### ISSUE THREAD

**Issue by wahuneke** [aws-amplify/docs#936]
Finding this HOC very frustrating to use.  I see that other (closed / stale) issues have mentioned this in the past but there does not seem to be resolution.  Sorry if I am missing something!

Am trying to use the withAuthenticator() function in React. At the moment, I would like to disable user sign up, but I have slogged through other issues already with trial and error.  In general, I have noticed that this function lacks documentation. Instead, there are a few examples for its use covering a few common use cases.

Particularly frustrating is the fact that this function appears to take as arguments: an object of unknown shape, an array of components (or?), a theme object next (I think), and perhaps other positional arguments after that...

It appears that what you have here is a heavily-loaded, can-do-everything function.  It is understandable that this is hard to document. But please do!  :)

**Comment by wahuneke** [comment]
Taking a slice of "humble pie" here. As 'last resort', I just consulted the JS for the withAuthenticator(). 
 Things are not so hard to understand now...

With the exception of the double-meaning on the first parameter, the API to the function is not so complicated.  I think I got this now.

I would recommend at least amending the documentation with at least the full signature of the function.  Just adding this information would have been enormously helpful for me and would have saved hours of trial and error and searching the voluminous docs that you do have.

i.e. you should say this somewhere:
`
function withAuthenticator(Comp, includeGreetings = false, authenticatorComponents = [], federated = null, theme = null, signUpConfig = {})
`

**Comment by gianpaj** [comment]
I can't find in the source code what should I put for the `federated` parameter.

https://github.com/aws-amplify/amplify-js/blob/4bd5c7ebef0ad223d4c05a452e696242927a750f/packages/aws-amplify-react/src/Auth/index.tsx#L38-L45

**Comment by sammartinez** [comment]
@wahuneke Not sure if you stumbled upon this, but there is documentation break downs of the [withAuthenticator](https://aws-amplify.github.io/docs/js/authentication#using-withauthenticator-hoc). Is this what you were looking for?

**Comment by neuquen** [comment]
Is the above already outdated?  It didn't work for me until I did this:

```
const formFields = {
    signUp: {
        given_name: {
            order:1
        },
        family_name: {
            order: 2
        },
        email: {
            order: 3
        },
        password: {
            order: 4
        },
        confirm_password: {
            order: 5
        }
    },
}

export default withAuthenticator(App, {formFields});
```
There appears to be a single options parameter now instead of multiple arguments.
