### ISSUE TITLE
Update react-native docs to use @react-native-community/push-notifications-ios

### ISSUE THREAD

**Issue by MaffooBristol** [aws-amplify/docs#939]
**Is your feature request related to a problem? Please describe.**
The docs refer to using PushNotificationIOS, but their docs state that it is deprecated in favour of using [@react-native-community/push-notifications-ios](https://github.com/react-native-community/react-native-push-notification-ios) instead.

This also makes me wonder how much of the documentation for this is up to date? For example it talks a lot about manually linking libraries but I believe that the latest version of RN with cocoapods just does this by default with autolinking. My current learning of all of this is a trial by fire so if the manual linking is a specific required thing then please let me know.

**Describe the solution you'd like**
Documentation updated to use non-deprecated libraries and linking methods.

Thanks all 😄 
Matt

**Comment by sammartinez** [comment]
This documentation has been updated since this issue was created. Can you provide the link for the callout of this documentation?
