### ISSUE TITLE
Documentation error - code example in Authentication not working

### ISSUE THREAD

**Issue by spbriggs** [aws-amplify/docs#941]
On this page : https://aws-amplify.github.io/docs/js/authentication#managing-security-tokens

The second code example under Managing Security Tokens doesn't work and throws an error that MemoryStorage is undefined.

I presume either MemoryStorage should be imported or that the code has got mangled and it should actually be a reference to the MyStorage class.

**Comment by sammartinez** [comment]
@spbriggs Are you still experiencing this issue? Please let us know
