### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by bluelinecoding** [aws-amplify/docs#949]
https://aws-amplify.github.io/docs/js/start?ref=amplify-rn-btn&platform=react-native

Don't need to link anymore, should be pod install

**Comment by Ashish5591** [comment]
Thanks for bringing it to our attention. 
Will update the docs to add the pod install step for RN >=0.60 and keep react-native link for 0.59 and below.

**Comment by Ashish5591** [comment]
Closing the issue now that the docs have been updated.
