### ISSUE TITLE
@function directive docs - code snippets in examples are mixed up

### ISSUE THREAD

**Issue by PavleNeskovic** [aws-amplify/docs#952]
**Describe the bug**
Function `GraphQLResolverFunction`  from `Example: Get the logged in user from Amazon Cognito User Pools` don't have the same resolvers as `schema.graphql` in the same example (I believe schema.graphql belongs to the example above)

**To Reproduce**
1. Go to https://aws-amplify.github.io/docs/cli-toolchain/graphql?sdk=js#function
2. Scroll down to `Example: Get the logged in user from Amazon Cognito User Pools`
3. See error

**Expected behavior**
Code snippets should match examples.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Google Chrome
 - Version:  77.0.3865.90 (Official Build) (64-bit)

**Comment by brene** [comment]
@PavleNeskovic given that we've had significant changes to the docs. I'm not sure if this is still relevant. Do you mind reopening it if you identify this issue to still be persistent.
