### ISSUE TITLE
Amplify Auth birthdate cannot be filled out by mobile user

### ISSUE THREAD

**Issue by asopian** [aws-amplify/docs#954]
**Describe the bug**
BLOCKER: Amplify Angular Sign-up form with birthdate cannot be submitted.
This only happen when the user only uses mouse-clicking/tapping to select the date.

Front-end error message always display:
"The following fields need to be filled out: Birthday". There happened no XHR communication with the backend.

No issue if user enter in date using keyboard.

**To Reproduce**
1. Create an Angular page with following content:
  <amplify-authenticator
          framework="ionic"
          [signUpConfig]="customSignUpConfig">
  </amplify-authenticator>

2. Customize the authentication page with following signupConfig:
  get customSignUpConfig() {
    return {
      header: 'Create a new account',
      signUpFields: [
      ...
      {
        label: 'Birthday',
        key: 'birthdate',
        required: true,
        type: 'date',
        custom: false
      }],
      hideAllDefaults: true,
      hiddenDefaults: []
    };
  }
3. View the page and try to register a user
4. Fill in the birthdate - using mouse ONLY. (Once the date component is filled using keyboard, it can be submitted)
3. Error message will be displayed:
"The following fields need to be filled out: Birthday"

**Expected behavior**
Mobile users - who only can interact with UI through tapping - should be able to register and not blocked.

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, Firefox
 - Version: Chrome 77.0.3865.90, Firefox 69.0.1 (64-bit)

**Smartphone (please complete the following information):**
 - Device: iPhone 9, Samsung S9
 - OS: -
 - Browser: Stock browser (WebView component) come with Cordova / Ionic
 - Version: -

**Additional context**

**Comment by sammartinez** [comment]
@asopian Are you still experiencing this issue with later versions of Amplify? Please let us know.

**Comment by inexplicable01** [comment]
It looks like the SignUp component does not have preparation for a 'date'  type.  

I am also looking into adding a birthdate entry for User sign up.   But looking into https://github.com/aws-amplify/amplify-js/blob/a047ce73/packages/aws-amplify-angular/src/components/authenticator/sign-up-component/sign-up.component.core.ts#L100  
it doesn't look like the code's prepared to deal with a birthdate entry.

Am I missing something?
