### ISSUE TITLE
Documentation: signupConfig incorrect type

### ISSUE THREAD

**Issue by asopian** [aws-amplify/docs#955]
**Describe the bug**
Incorrect documentation on page:
https://aws-amplify.github.io/docs/js/angular#signup-configuration

It stated:

type | string | the type attribute for the html input element | ‘string’, ‘number’, ‘password’, etc
-- | -- | -- | --

According to:
https://www.w3schools.com/tags/att_input_type.asp

There is no type "string". It should be replaced with "text" throughout the example documentation.

**To Reproduce**
1. Visit https://aws-amplify.github.io/docs/js/angular#signup-configuration
2. Search for "the type attribute for the html input element"

**Expected behavior**
The examples should specify "text" instead of "string"

**Screenshots**
-NA

**Desktop (please complete the following information):**
 - OS: Any OS
 - Browser: Any Browsers
 - Version: Any version

**Smartphone (please complete the following information):**
 - Device: any device
 - OS: any OS
 - Browser: any browser
 - Version: any version

**Additional context**
- NA

**Comment by tulikavijay** [comment]
Hi! I would like to work on this.

**Comment by tulikavijay** [comment]
Can someone guide me with the issue? The problem seems to be in the sign-up-fields.html and sign-up-attributes.html(correct me if i am wrong). I can't locate these files.

**Comment by sammartinez** [comment]
@tulikavijay Are you still wanting to work on this?
