### ISSUE TITLE
Customize Cognito Sign in Buttons

### ISSUE THREAD

**Issue by K-ennethA** [aws-amplify/docs#956]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by K-ennethA** [comment]
Only able to customize logo and background color of Cognito Sign-In

Would like to be able to easily switch the colors of the sign in button and other blue text

Currently create new storyboard and UI and integrate Cognito to work accordingly

**Comment by drochetti** [comment]
Hi @K-ennethA thanks for getting in touch. Can you provide some more info to clarify your request?

- What platform is it related to? JS, Android or iOS?
- Do you have screenshots to show what level of customization you're looking for?
