### ISSUE TITLE
Cognito User Pools Authorization - Example

### ISSUE THREAD

**Issue by davidsteed** [aws-amplify/docs#959]
**Describe the bug**
The code in the example for Cognito Authentication below:
async function postData() { 
    let apiName = 'MyApiName';
    let path = '/path';
    let myInit = { 
        headers: { Authorization: `Bearer ${(await Auth.currentSession()).getAccessToken().getJwtToken()}` }
    }
    return await API.post(apiName, path, myInit);
}

postData();

Is wrong - it should be
headers: { Authorization: `Bearer ${(await Auth.currentSession()).getIdToken().getJwtToken()}` }

I spemt absolutely ages trying to work out why this was not working - as I thought it was an IAMs permission thing.

**Comment by meddjelaili** [comment]
> **Describe the bug**
> The code in the example for Cognito Authentication below:
> async function postData() {
> let apiName = 'MyApiName';
> let path = '/path';
> let myInit = {
> headers: { Authorization: `Bearer ${(await Auth.currentSession()).getAccessToken().getJwtToken()}` }
> }
> return await API.post(apiName, path, myInit);
> }
> 
> postData();
> 
> Is wrong - it should be
> headers: { Authorization: `Bearer ${(await Auth.currentSession()).getIdToken().getJwtToken()}` }
> 
> I spemt absolutely ages trying to work out why this was not working - as I thought it was an IAMs permission thing.

You're a lifesaver 😘  thank you

**Comment by Ettore-P** [comment]
I also spent one day to figure out this...
In all the API documentation is written that for cognito pool authentication you should use getAccessToken(): [](https://aws-amplify.github.io/docs/js/api)
Now, with getIdToken() instead getAccessToken() works, but the question is: why?
Sounds more logic that the authorization is given by the accessToken then by the idToken, why is that?

**Comment by danielpizarro** [comment]
I can't believe this, such a bad documentation

**Comment by rush86999** [comment]
I spent countless hours on this. Please update documentation for API access of lambda for cognito pools using ```getIdToken()``` and NOT ```getAccessToken()```
