### ISSUE TITLE
typo in amplify docs

### ISSUE THREAD

**Issue by insomniyackk** [aws-amplify/docs#962]
**Describe the bug**
typo in instructions

**To Reproduce**
1. Go to '...'https://aws-amplify.github.io/docs/js/start?ref=amplify-js-btn&platform=purejs
2. Scroll down to step 4
3. find the following paragraph and see the error.
"After restarting your app using npm start go back to your browser and click ADD DATA. You’ll see that your application is now submitting events to AppSync and storing records in DynamoDB. Next, update src/App.js to list all the items in the database by importing listTodos and update the page when a query runs on app start by immediately calling the function:"

**Expected behavior**
the text "src/App.js " should be "src/app.js " - the case is incorrect.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]ubuntu
 - Browser [e.g. chrome, safari]firefox

**Smartphone (please complete the following information):**
 - Version [e.g. 22]69.0.2

**Additional context**

**Comment by sammartinez** [comment]
@insomniyackk Thanks for catching this! I have cut a Pull Request for this. In the future, if you're not aware, we do take Pull Request for typos and issues like this. Please feel free if you see this again to cut a Pull Request if you'd like.
