### ISSUE TITLE
Unicode character in IAM policy section

### ISSUE THREAD

**Issue by erickeno** [aws-amplify/docs#970]
**Describe the bug**
There is a hidden unicode `(\u2028)` character at the IAM policy section of the documentation which makes it hard to spot and copy-paste.
**To Reproduce**
1. Go to `https://github.com/aws-amplify/docs/blob/master/cli-toolchain/usage.md`
2. Click on the edit icon at the top.
3. Scroll down to `iam-policy-for-the-cli` section

**Screenshots**
![Screen Shot 2019-10-16 at 3 39 28 PM](https://user-images.githubusercontent.com/3820632/66953440-85786d00-f02c-11e9-90eb-629ea65e476d.png)

**Comment by palpatim** [comment]
Fixed by https://github.com/aws-amplify/docs/pull/971.
