### ISSUE TITLE
critical 'withAuthenticator' not documented and the code is in Angular Typescript

### ISSUE THREAD

**Issue by bionicles** [aws-amplify/docs#976]
**Describe the bug**
critical 'withAuthenticator' not documented and the code is in Angular Typescript

**To Reproduce**
1. Use amplify for your react app to make an email-as-username
2. you want to change "username" to "email" (literally 1 word change) so user knows to put their email instead of a username
3. the docs tell you to _make an entirely new ui_ (what's the point of your code then?)
4. the api docs are not searchable
5. the code you use for Authenticator is written in Angular. In typescript. That is a ton of extra work and not something react developers could easily understand. Im not sure why this isn't just plain functional react, it would take [probably under] ~1week to rewrite that code with react hooks, and your customers could look at the Authenticator code and actually understand it.

**Expected behavior**
I expected to be able to change the labels of the form fields in Amplify Auth.withAuthenticator (although HOCs are deprecated)

**Comment by bionicles** [comment]
when you want to customize your react / amplify auth, you quickly run into headaches...

the docs for auth customization are scattered incoherently around the docs page nav tree:

https://aws-amplify.github.io/docs/js/react
https://aws-amplify.github.io/docs/js/authentication
https://aws-amplify.github.io/docs/js/authentication

**Comment by bionicles** [comment]
edit: i was wrong about the authenticator being in angular. this is just the version linked from API docs, for some reason ... 

https://github.com/aws-amplify/amplify-js/blob/9fc0e596/packages/aws-amplify-angular/src/components/authenticator/authenticator/authenticator.factory.ts#L43

https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/Auth/Authenticator.tsx

**Comment by brene** [comment]
We have completely revamped our docs! I believe we addressed your concerns here: https://docs.amplify.aws/ui/q/framework/react
