### ISSUE TITLE
Documentation update: Functions Examples

### ISSUE THREAD

**Issue by asmajlovicmars** [aws-amplify/docs#981]
**Describe the bug**

The instructions bellow are not valid anymore for creating Hello world function through "amplify add api"

Functions Examples
You can add a Lambda function to your project which you can alongside a REST API or as a datasource, as a part of your GraphQL API using the @function directive.

$ amplify add api
? Provide a friendly name for your resource to be used as a label for this category in the project: lambdafunction
? Provide the AWS Lambda function name: lambdafunction
? Choose the function template that you want to use: (Use arrow keys)
❯ Hello world function 
  CRUD function for Amazon DynamoDB table (Integration with Amazon API Gateway and Amazon DynamoDB) 
  Serverless express function (Integration with Amazon API Gateway) 

**To Reproduce**
1. Go to [https://aws-amplify.github.io/docs/cli-toolchain/quickstart#functions-examples](https://aws-amplify.github.io/docs/cli-toolchain/quickstart#functions-examples)

**Edit**
version: @aws-amplify/cli@3.15.0

**Comment by swaminator** [comment]
Resolved: https://docs.amplify.aws/cli/function#function-templates
