### ISSUE TITLE
documentation is very confusing #Javascript

### ISSUE THREAD

**Issue by gadielkalleb** [aws-amplify/docs#985]
Guys the documentation is very confusing from the example
 **https://aws-amplify.github.io/docs/js/start?ref=amplify-rn-btn&platform=react-native**.

The order of the tutorial is pretty confusing when it comes to **#Step 4: Integrate into your app**.

It is not clear where it goes.

the variables:

**import {createTodo} from './src/graphql/mutations';
import {listAll} from './src/graphql/queries';
import {onCreateTodo} from './src/graphql/subscriptions';**

do not exist in their respective files

Here is the example mutations **'./src/graphql/mutations'**:
```
export const createN = `mutation CreateN($input: CreateNInput!) {
  createN(input: $input) {
    id
    title
    content
    price
    rating
  }
}
`;
export const updateN = `mutation UpdateN($input: UpdateNInput!) {
  updateN(input: $input) {
    id
    title
    content
    price
    rating
  }
}
`;
export const deleteN = `mutation DeleteN($input: DeleteNInput!) {
  deleteN(input: $input) {
    id
    title
    content
    price
    rating
  }
}
`;

```
Isn't there in the repository a real example that is used in the example?
I basically gave up, documentation is very raw, 
the idea is very cool on aws, but technology is not witchcraft.
 I will use firebase with GPC again. when you get the documentation, I'll try it again.

**Comment by undefobj** [comment]
Hi I just went through the tutorial again and it lists that you need to update your `App.js` as part of the React Native project with the code which is copy & paste. If those files weren't generated by the CLI could you try to run `amplify add api` and `amplify push` again?

**Comment by gadielkalleb** [comment]
Well I can try again this weekend, I'm at the end of a sprint, and give you feedback on what you told me @undefobj .

**Comment by sammartinez** [comment]
@gadielkalleb Were you able to go through it again? Please let us know.

**Comment by sammartinez** [comment]
Resolving issue as there has been no update since November on this. Please let us know if you are still experiencing this issue after the above callouts and we can look to reopen.
