### ISSUE TITLE
Docs still show use of AWSMobileClient and AWSCognitoAuth together

### ISSUE THREAD

**Issue by bkocik** [aws-amplify/docs#987]
**Describe the bug**
If you add both AWSMobileClient and AWSCognitoAuth into your podfile, install pods, and attempt to build you'll end up with an error ("AWSCognitoAuth_Internal.h file not found")

Per this issue, these should not be used together: https://github.com/aws-amplify/aws-sdk-ios/issues/1328

However the documentation on using Cocoapods found at https://aws-amplify.github.io/docs/ios/manualsetup still has them together in the example file.

**To Reproduce**
1. Create a new Xcode iOS project.
2. Follow the above referenced Cocoapod setup guide, using the example Cocoapods file
3. Build the project.
4. Observe error: AWSCognitoAuth_Internal.h file not found

**Comment by palpatim** [comment]
@bkocik The sample is there mostly to indicate the supported pods (which are themselves out of date), but it's a good callout. We'll address this.
