### ISSUE TITLE
Documentation request: Permission requirement list

### ISSUE THREAD

**Issue by dherbig** [aws-amplify/docs#991]
**Describe the bug**
I'm trying to configure the Amplify CLI with an existing user

**To Reproduce**
1. Make a IAM user with access key and secret access key
2. Make a project etc
3. amplify init
4. Use the creds from step 1
5. Watch the access denied errors roll in

**Expected behavior**
I want the documentation to state what permissions are needed in order for amplify init to work correctly.

When you run amplify init, if your existing user doesn't have all the correct permissions, the command fails. If you told me which permissions I needed in the documentation, I'd be able to set the account up right. Instead, I have to add permissions one at a time in response to each new attempt's new error.

**Comment by mauerbac** [comment]
hello @dherbig - thanks for reaching out. This has recently been added here https://docs.amplify.aws/cli/usage/iam
