### ISSUE TITLE
Doing simple rest post requests?

### ISSUE THREAD

**Issue by oleersoy** [aws-amplify/docs#998]
**Is your feature request related to a problem? Please describe.**
When I started reading the API documentation I just wanted to know how to do a simple REST Post request using the REST API and not GraphQL.

I would be nice if the GraphQL and Rest stuff was separated.

**Comment by oleersoy** [comment]
Actually after scanning the TOC I I found it.  I would be nice it the TOC started out in a collapsed format (Accordion?) and then we could click on either GraphQL or Rest to expand the rest of the TOC.  I would also be nice if it was indexed and searchable so that we could quickly find the section we are looking for.

**Comment by mtliendo** [comment]
#1776

**Comment by mauerbac** [comment]
Thanks @oleersoy. Going to close as this is captured in that issue and team is addressing.
