### ISSUE TITLE
Sandbox Server for Stackblitz and Repl.it Demoes?

### ISSUE THREAD

**Issue by oleersoy** [aws-amplify/docs#999]
**Is your feature request related to a problem? Please describe.**

It would be nice to have a Sandbox server environment that anyone can connect to for tutorials etc.  For example we can create repl.it express servers that are always live and use these for prototype demoes.

https://medium.com/@ole.ersoy/repl-it-express-server-with-search-6070421fb2cb

If Amazon had something similar then we could write articles like the above, and give readers the ability to play with a live environment.

Maybe partner with repl.it to provide it?

**Comment by sammartinez** [comment]
cc @brene on this for Docs feedback

**Comment by mauerbac** [comment]
Closing in favor of a larger epic #2017 . Thanks for the suggestion.
